import type { Unit } from "../types";

export const UNIT_RELIGION: Unit = {
  slug: "religion",
  stage: 7,
  order: 30,
  icon: "⛪",
  title: "Religion & Vatican",
  tagline: "Chiesa, papa, messa — the basics without committing to a position. Just so you understand the city.",
  badge: "culture",
  lessons: [
    {
      slug: "religion-vocab",
      title: "Church vocabulary",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "You don't need to be Catholic to understand Rome",
          body: [
            "Rome has ~900 churches. You'll walk into a dozen on your trip whether you mean to or not. Knowing the basic words lets you read plaques, follow guides, and not feel lost.",
            "<strong>Italy is officially secular</strong>, but Catholicism is woven into everyday life: holidays, baby names, gestures, food. About 70% identify as Catholic, but practice varies hugely.",
            "<strong>Tourist etiquette:</strong> dress modestly to enter churches (shoulders + knees covered). Speak quietly. Don't use flash. Don't enter during Mass unless joining. Some churches charge entry; most are free.",
          ],
          keyPoint:
            "Italy is officially secular but culturally Catholic. Cover shoulders + knees in churches. Quiet inside. Free entry mostly.",
        },
        {
          type: "vocab",
          heading: "Church & religious vocabulary",
          items: [
            { it: "la chiesa", en: "the church" },
            { it: "la basilica", en: "the basilica (major papal church)" },
            { it: "la cattedrale / il duomo", en: "the cathedral" },
            { it: "la cappella", en: "the chapel" },
            { it: "il battistero", en: "the baptistery" },
            { it: "il campanile", en: "the bell tower" },
            { it: "la navata", en: "the nave" },
            { it: "l'altare", en: "the altar" },
            { it: "la cupola", en: "the dome" },
            { it: "il chiostro", en: "the cloister" },
            { it: "la messa", en: "the Mass" },
            { it: "il prete / il sacerdote", en: "priest" },
            { it: "il vescovo", en: "bishop" },
            { it: "il cardinale", en: "cardinal" },
            { it: "il papa", en: "the Pope" },
            { it: "il Vaticano", en: "the Vatican" },
            { it: "la Città del Vaticano", en: "Vatican City (the state)" },
            { it: "la Santa Sede", en: "the Holy See" },
          ],
        },
        {
          type: "tip",
          heading: "Famous Roman churches you'll likely visit",
          body: "<em>San Pietro</em> (St. Peter's Basilica — at the Vatican). <em>San Giovanni in Laterano</em> (Rome's cathedral — actually higher rank than St. Peter's). <em>Santa Maria Maggiore</em> (one of the four papal basilicas). <em>Pantheon</em> (originally a Roman temple, now a Catholic church). <em>Santa Maria del Popolo</em> (Caravaggios). <em>Santa Maria sopra Minerva</em> (Gothic; Michelangelo's Christ).",
        },
        {
          type: "multipleChoice",
          heading: "Quick vocabulary check",
          questions: [
            {
              q: "'The Pope' =",
              options: ["il prete", "il vescovo", "il papa", "il santo"],
              correct: 2,
            },
            {
              q: "'Vatican City' (the state) =",
              options: ["il Vaticano", "la Città del Vaticano", "Both work — depending on context", "la Santa Sede"],
              correct: 2,
            },
            {
              q: "'Mass' (Catholic service) =",
              options: ["la chiesa", "la messa", "il rito", "la celebrazione"],
              correct: 1,
            },
            {
              q: "'Bell tower' =",
              options: ["il campanile", "il chiostro", "la cupola", "la navata"],
              correct: 0,
            },
            {
              q: "Tourist dress code for churches =",
              options: [
                "any clothing",
                "shoulders + knees covered",
                "formal wear required",
                "head covering required for women",
              ],
              correct: 1,
            },
          ],
        },
      ],
    },
    {
      slug: "religion-holidays-history",
      title: "Holidays, history, and the calendar",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The Catholic calendar shapes Italian life",
          body: [
            "Major religious holidays = national holidays in Italy. Knowing the names helps you understand store closures, transit changes, and conversations.",
            "<strong>Christmas / Natale</strong> (December 25) + Santo Stefano (Dec 26). Many things closed.",
            "<strong>Epifania</strong> (January 6) = Epiphany. La Befana brings gifts to kids.",
            "<strong>Pasqua / Pasquetta</strong> (Easter Sunday + Monday). Spring's biggest break.",
            "<strong>Ferragosto</strong> (August 15) = Feast of the Assumption. Rome empties out — almost everything closes for 1-2 weeks.",
            "<strong>Ognissanti</strong> (November 1) = All Saints' Day. National holiday.",
            "<strong>Immacolata</strong> (December 8) = Immaculate Conception. Officially kicks off Christmas season.",
          ],
          keyPoint:
            "Major Catholic holidays = national holidays. Ferragosto (Aug 15) is when Romans flee the city — plan around it.",
        },
        {
          type: "vocab",
          heading: "Religious holidays & terms",
          items: [
            { it: "Natale", en: "Christmas" },
            { it: "Santo Stefano", en: "St. Stephen's Day (Dec 26)" },
            { it: "Epifania / Befana", en: "Epiphany / Befana (Jan 6)" },
            { it: "Pasqua", en: "Easter" },
            { it: "Pasquetta", en: "Easter Monday" },
            { it: "Ferragosto", en: "Aug 15 — Assumption / national break" },
            { it: "Ognissanti", en: "All Saints (Nov 1)" },
            { it: "Immacolata", en: "Immaculate Conception (Dec 8)" },
            { it: "il presepe / il presepio", en: "the nativity scene" },
            { it: "il santo patrono", en: "the patron saint" },
            { it: "la festa patronale", en: "the patron saint's feast" },
            { it: "battesimo", en: "baptism" },
            { it: "comunione", en: "(first) communion" },
            { it: "cresima", en: "confirmation" },
            { it: "matrimonio", en: "wedding" },
            { it: "funerale", en: "funeral" },
          ],
        },
        {
          type: "dialogue",
          heading: "Asking about a holiday",
          setup: "You see signs about a feast day in your neighborhood.",
          lines: [
            { speaker: "You", it: "Mi scusi, c'è una festa oggi?", en: "Excuse me, is there a holiday today?" },
            { speaker: "Signora", it: "Sì, è la festa di San Giovanni, patrono del quartiere. C'è la processione alle sei.", en: "Yes, it's the feast of St. John, patron of the neighborhood. There's the procession at six." },
            { speaker: "You", it: "Posso assistere anche se non sono italiano?", en: "Can I attend even if I'm not Italian?" },
            { speaker: "Signora", it: "Certo, certo. Vengono tutti — italiani, stranieri, religiosi, no. È più una festa di quartiere che una cosa solo religiosa.", en: "Of course, of course. Everyone comes — Italians, foreigners, religious, not. It's more of a neighborhood festival than just a religious thing." },
            { speaker: "You", it: "Bellissimo. A che ora finisce?", en: "Wonderful. What time does it end?" },
            { speaker: "Signora", it: "Verso le nove, poi c'è il banchetto in piazza. Si mangia tutti insieme.", en: "Around nine, then there's the feast in the piazza. We all eat together." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Holiday vocab",
          items: [
            {
              template: "A Roma, il 15 agosto è ___ .",
              answer: "Ferragosto",
              en: "In Rome, August 15 is Ferragosto.",
              options: ["Pasqua", "Natale", "Ferragosto", "Ognissanti"],
            },
            {
              template: "Il giorno dopo Natale è ___ .",
              answer: "Santo Stefano",
              en: "The day after Christmas is St. Stephen's.",
              options: ["Capodanno", "Santo Stefano", "Pasquetta", "Befana"],
            },
            {
              template: "Il ___ del Vaticano è il Papa.",
              answer: "capo",
              en: "The head of the Vatican is the Pope.",
              options: ["padre", "capo", "santo", "patrono"],
            },
            {
              template: "La ___ di Natale è il 25 dicembre.",
              answer: "festa",
              en: "The Christmas holiday is December 25.",
              options: ["festa", "messa", "data", "vigilia"],
            },
            {
              template: "Ogni città italiana ha un santo ___ .",
              answer: "patrono",
              en: "Every Italian city has a patron saint.",
              options: ["patrono", "papa", "padre", "antico"],
            },
          ],
        },
      ],
    },
    {
      slug: "religion-visiting-vatican",
      title: "Visiting the Vatican",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Practical tips for the Vatican",
          body: [
            "<strong>St. Peter's Square (Piazza San Pietro)</strong> = always free, always open. The basilica itself = free, but lines are long (1-3 hours). Get there at 7am or after 4pm.",
            "<strong>Vatican Museums + Sistine Chapel</strong> = paid (~€20 base; +€5 for online skip-the-line). Closed Sundays except the last Sunday of the month (free that day — packed).",
            "<strong>Papal audience</strong>: Wednesdays at 9 or 10:30am, free, in St. Peter's Square (summer) or Paolo VI Hall (winter). Request tickets from <em>biglietteria.va</em> a few weeks ahead.",
            "<strong>Dress code</strong>: STRICT. Shoulders and knees covered. They'll turn you away — wear a light scarf as backup.",
          ],
          keyPoint:
            "Piazza San Pietro = always free. Basilica = free, long lines (go 7am or 4pm+). Museums = paid, closed Sundays. Papal audience Wed 10:30. Dress code strict.",
        },
        {
          type: "vocab",
          heading: "Vatican-specific vocabulary",
          items: [
            { it: "i Musei Vaticani", en: "the Vatican Museums" },
            { it: "la Cappella Sistina", en: "the Sistine Chapel" },
            { it: "la Basilica di San Pietro", en: "St. Peter's Basilica" },
            { it: "la Piazza San Pietro", en: "St. Peter's Square" },
            { it: "il Colonnato del Bernini", en: "Bernini's Colonnade" },
            { it: "l'udienza papale", en: "the papal audience" },
            { it: "la benedizione", en: "the blessing" },
            { it: "il pellegrino / la pellegrina", en: "pilgrim (m / f)" },
            { it: "il pellegrinaggio", en: "pilgrimage" },
            { it: "salire sulla cupola", en: "to climb the dome" },
            { it: "ascensore + scalini", en: "elevator + stairs (to the dome)" },
            { it: "le tombe / la cripta", en: "the tombs / crypt" },
            { it: "il giubileo", en: "the Jubilee (a year of pilgrimage every 25 years)" },
            { it: "abbigliamento adatto", en: "appropriate attire" },
          ],
        },
        {
          type: "dialogue",
          heading: "Asking about the Sistine Chapel",
          setup: "At the Vatican Museums info desk.",
          lines: [
            { speaker: "You", it: "Mi scusi, come si arriva alla Cappella Sistina?", en: "Excuse me, how do you get to the Sistine Chapel?" },
            { speaker: "Addetto", it: "Segua il percorso indicato. Sono circa quaranta minuti di cammino attraverso i musei.", en: "Follow the marked path. It's about a 40-minute walk through the museums." },
            { speaker: "You", it: "C'è un'audioguida?", en: "Is there an audioguide?" },
            { speaker: "Addetto", it: "Sì, allo sportello a destra. Otto euro in inglese.", en: "Yes, at the window on the right. Eight euros in English." },
            { speaker: "You", it: "Si possono fare foto nella Cappella?", en: "Can you take photos in the Chapel?" },
            { speaker: "Addetto", it: "No, è vietato. E si deve stare in silenzio.", en: "No, it's forbidden. And you have to stay silent." },
            { speaker: "You", it: "Va bene, grazie. Quanto dura la visita totale?", en: "Okay, thanks. How long does the total visit take?" },
            { speaker: "Addetto", it: "Almeno due o tre ore.", en: "At least two or three hours." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Vatican-trip fill",
          items: [
            {
              template: "L' ___ del Papa è il mercoledì mattina.",
              answer: "udienza",
              en: "The Pope's audience is Wednesday morning.",
              options: ["udienza", "celebrazione", "messa", "preghiera"],
            },
            {
              template: "La ___ Sistina è la più famosa del Vaticano.",
              answer: "Cappella",
              en: "The Sistine Chapel is the most famous in the Vatican.",
              options: ["Cappella", "Chiesa", "Basilica", "Cripta"],
            },
            {
              template: "I Musei Vaticani sono chiusi la ___ , tranne l'ultima del mese.",
              answer: "domenica",
              en: "The Vatican Museums are closed on Sundays, except the last one of the month.",
              options: ["domenica", "lunedì", "sabato", "venerdì"],
            },
            {
              template: "Per entrare in chiesa, le ___ devono essere coperte.",
              answer: "spalle",
              en: "To enter a church, the shoulders must be covered.",
              options: ["mani", "spalle", "scarpe", "borse"],
            },
            {
              template: "Da Piazza San Pietro si vede la cupola di ___ .",
              answer: "Michelangelo",
              en: "From St. Peter's Square you see Michelangelo's dome.",
              options: ["Bernini", "Michelangelo", "Raffaello", "Caravaggio"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-it",
          prompt: "Excuse me, is the basilica open this morning?",
          reference: "Mi scusi, la basilica è aperta stamattina?",
          hint: "'È aperta' agrees with 'basilica' (f sg).",
        },
        {
          type: "tip",
          heading: "Quick history that helps",
          body: "Vatican City became an independent state in 1929 (Lateran Treaty between Mussolini and Pope Pius XI). Before that, the Pope had ruled central Italy as the \"Papal States\" until 1870. So when Italians talk about \"prima dell'Unità\" or \"prima del 1870\" — they're often referring to the era when the Pope was a temporal ruler. Useful context for museum plaques.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'The Pope' =",
        options: ["il prete", "il vescovo", "il papa", "il santo"],
        correct: 2,
      },
      {
        q: "Vatican City became an independent state in…",
        options: ["1870", "1929", "1945", "1962"],
        correct: 1,
      },
      {
        q: "Papal audience is usually on…",
        options: ["Sunday", "Wednesday", "Friday", "the first day of the month"],
        correct: 1,
      },
      {
        q: "Ferragosto is on…",
        options: ["June 25", "July 15", "August 15", "September 1"],
        correct: 2,
      },
      {
        q: "Dress code for entering Roman churches =",
        options: [
          "any clothes",
          "shoulders + knees covered",
          "formal wear required",
          "head covering required for women",
        ],
        correct: 1,
      },
      {
        q: "'Mass' (Catholic service) =",
        options: ["la chiesa", "la messa", "la preghiera", "il rito"],
        correct: 1,
      },
      {
        q: "Vatican Museums are closed on…",
        options: [
          "Sundays (except last Sunday of the month)",
          "Mondays",
          "every weekend",
          "never closed",
        ],
        correct: 0,
      },
      {
        q: "'Bell tower' =",
        options: ["la cupola", "il chiostro", "il campanile", "la navata"],
        correct: 2,
      },
      {
        q: "The Sistine Chapel ceiling is by…",
        options: ["Bernini", "Raffaello", "Caravaggio", "Michelangelo"],
        correct: 3,
      },
      {
        q: "Translate: 'Is the basilica open today?'",
        options: [
          "È la basilica aperta oggi?",
          "La basilica è aperto oggi?",
          "La basilica è aperta oggi?",
          "È aperta la basilica oggi?",
        ],
        correct: 2,
      },
    ],
  },
};
