import type { Unit } from "../types";

export const UNIT_SMALL_TALK: Unit = {
  slug: "small-talk",
  stage: 7,
  order: 32,
  icon: "💬",
  title: "Small talk",
  tagline: "Weather, sports, che bello! — the conversations that fill the gaps and make Italians warm to you.",
  badge: "culture",
  lessons: [
    {
      slug: "small-talk-weather",
      title: "Weather, time of day, the date",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Weather is the global small-talk currency",
          body: [
            "Italians love weather chat, especially with strangers or in elevators.",
            "<em>«Che giornata!»</em> = What a day! (positive or negative — tone matters).",
            "<em>«Fa un caldo / freddo terribile.»</em> = It's terribly hot / cold.",
            "<em>«Sta per piovere.»</em> = It's about to rain. <em>«Speriamo che non piova.»</em> = Let's hope it doesn't rain.",
            "<em>«Che bel tempo!»</em> = What nice weather! / <em>«Che brutto tempo!»</em> = What awful weather!",
          ],
          keyPoint:
            "Weather works as universal small talk. Fare + caldo/freddo (it's hot/cold). Sta per + infinitive (it's about to…).",
        },
        {
          type: "vocab",
          heading: "Weather vocabulary",
          items: [
            { it: "il tempo / il meteo", en: "weather (general / forecast)" },
            { it: "fa caldo / freddo / fresco", en: "it's hot / cold / cool" },
            { it: "fa bel tempo / brutto tempo", en: "the weather's nice / bad" },
            { it: "c'è il sole", en: "it's sunny" },
            { it: "c'è vento", en: "it's windy" },
            { it: "c'è nebbia", en: "it's foggy" },
            { it: "piove / sta piovendo", en: "it's raining / it's currently raining" },
            { it: "nevica", en: "it's snowing" },
            { it: "tira vento", en: "the wind is blowing" },
            { it: "è nuvoloso / nuvolo", en: "it's cloudy" },
            { it: "è sereno", en: "it's clear" },
            { it: "umido / secco", en: "humid / dry" },
            { it: "la temperatura", en: "temperature" },
            { it: "trenta gradi", en: "thirty degrees (always Celsius)" },
            { it: "il temporale", en: "thunderstorm" },
            { it: "l'arcobaleno", en: "rainbow" },
          ],
        },
        {
          type: "dialogue",
          heading: "Elevator small talk",
          setup: "You and a neighbor share an elevator.",
          lines: [
            { speaker: "Signora", it: "Buongiorno! Che caldo oggi, eh?", en: "Good morning! What heat today, huh?" },
            { speaker: "You", it: "Eh, sì. Almeno c'è un po' di vento.", en: "Yeah, yes. At least there's a bit of wind." },
            { speaker: "Signora", it: "Speriamo che fra qualche giorno cambia. È prevista pioggia per giovedì.", en: "Let's hope it changes in a few days. Rain is forecast for Thursday." },
            { speaker: "You", it: "Magari! Ne abbiamo bisogno.", en: "I wish! We need it." },
            { speaker: "Signora", it: "Esatto. Buona giornata!", en: "Exactly. Have a good day!" },
            { speaker: "You", it: "Anche a Lei!", en: "You too!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Weather fill-ins",
          items: [
            {
              template: "Oggi ___ caldo, almeno trenta gradi.",
              answer: "fa",
              en: "Today it's hot, at least 30 degrees.",
              options: ["è", "fa", "c'è", "sta"],
            },
            {
              template: "Domani ___ piovere.",
              answer: "sta per",
              en: "Tomorrow it's about to rain.",
              options: ["fa per", "sta per", "va a", "è"],
            },
            {
              template: "Che ___ tempo! Andiamo al parco?",
              answer: "bel",
              en: "What nice weather! Let's go to the park?",
              options: ["bello", "bel", "buon", "bueno"],
            },
            {
              template: "C'è il ___ , bellissima giornata.",
              answer: "sole",
              en: "It's sunny, beautiful day.",
              options: ["sole", "vento", "tempo", "cielo"],
            },
            {
              template: "Non uscire senza ombrello, ___ piovendo.",
              answer: "sta",
              en: "Don't go out without an umbrella, it's raining.",
              options: ["è", "sta", "fa", "ha"],
            },
          ],
        },
      ],
    },
    {
      slug: "small-talk-sports-news",
      title: "Sports and current chat",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Calcio is the universal language",
          body: [
            "Italian football (<em>calcio</em>) is a national obsession. Knowing your conversational partner's team can unlock genuine warmth.",
            "Big teams: <em>Juventus</em> (Turin, the most popular), <em>Inter Milan</em>, <em>AC Milan</em> (the Milan derby = <em>il derby della Madonnina</em>), <em>Roma</em> + <em>Lazio</em> (Roman derby = <em>il derby della Capitale</em>), <em>Napoli</em>.",
            "Easy conversation openers: <em>«Hai visto la partita ieri sera?»</em> = Did you see the game last night? <em>«Per quale squadra fai il tifo?»</em> = Which team do you support?",
            "If you don't follow: <em>«Non seguo molto il calcio, ma mi piace l'atmosfera.»</em> = I don't follow soccer much, but I like the atmosphere.",
          ],
          keyPoint:
            "Calcio is national glue. Knowing Roma vs Lazio (Roman derby) or Juventus is enough to make small talk. 'Tifo' = supporting a team.",
        },
        {
          type: "vocab",
          heading: "Sports & news",
          items: [
            { it: "il calcio / il pallone", en: "soccer / 'the ball'" },
            { it: "la partita", en: "the match / game" },
            { it: "il campionato / la Serie A", en: "championship / Italian top league" },
            { it: "la nazionale (italiana)", en: "the (Italian) national team" },
            { it: "i Mondiali", en: "the World Cup" },
            { it: "gli Europei", en: "the Euros" },
            { it: "il tifoso / la tifosa", en: "fan / supporter" },
            { it: "fare il tifo per…", en: "to support a team" },
            { it: "il gol", en: "the goal" },
            { it: "l'arbitro", en: "the referee" },
            { it: "vincere / perdere / pareggiare", en: "to win / lose / draw" },
            { it: "il derby", en: "the derby (rival local match)" },
            { it: "il tennis / il basket / il volley", en: "tennis / basketball / volleyball" },
            { it: "le notizie / il telegiornale", en: "the news / TV news" },
            { it: "la politica", en: "politics (tread carefully)" },
          ],
        },
        {
          type: "tip",
          heading: "Topics to avoid (or tread carefully)",
          body: "Italians are open about most things, but be careful with:<br>• <strong>Politics</strong> — opinions are strong, regional divides deep. Don't volunteer opinions about Berlusconi/Meloni/etc. unless invited.<br>• <strong>Mafia / mafia-related jokes</strong> — especially in the south, this is offensive.<br>• <strong>North vs South</strong> — stereotypes are real and people are sensitive about them.<br>• <strong>Religion</strong> — practice varies; don't assume Catholic or atheist.<br>Safe: food, family, kids, travel, soccer (with sensitivity), weather.",
        },
        {
          type: "dialogue",
          heading: "Sports chat",
          setup: "You're at a café when a stranger comments on the TV.",
          lines: [
            { speaker: "Sconosciuto", it: "Hai visto la partita ieri sera?", en: "Did you see the game last night?" },
            { speaker: "You", it: "No, non l'ho vista. Chi giocava?", en: "No, I didn't see it. Who was playing?" },
            { speaker: "Sconosciuto", it: "Roma-Napoli. Tre a uno per il Napoli. Disastro!", en: "Roma-Napoli. 3-1 for Napoli. Disaster!" },
            { speaker: "You", it: "Sei tifoso della Roma?", en: "Are you a Roma supporter?" },
            { speaker: "Sconosciuto", it: "Romanista da quarant'anni. E tu, per chi tifi?", en: "Roma fan for forty years. And you, who do you support?" },
            { speaker: "You", it: "Sinceramente, non seguo molto il calcio. Ma a casa tifano per i Patriots, football americano.", en: "Honestly, I don't follow soccer much. But at home they root for the Patriots, American football." },
            { speaker: "Sconosciuto", it: "Ah, americano! Benvenuto a Roma. Spero che almeno conosci Totti, no?", en: "Ah, American! Welcome to Rome. I hope at least you know Totti, no?" },
            { speaker: "You", it: "Sì, lo conosco di nome.", en: "Yes, I know him by name." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Sports talk",
          items: [
            {
              template: "Per quale squadra fai il ___ ?",
              answer: "tifo",
              en: "Which team do you support?",
              options: ["tifo", "calcio", "amico", "amore"],
            },
            {
              template: "Hai visto la ___ di ieri?",
              answer: "partita",
              en: "Did you see yesterday's match?",
              options: ["partita", "vittoria", "squadra", "stadio"],
            },
            {
              template: "Tre a uno per il Napoli — un bel ___ !",
              answer: "risultato",
              en: "3-1 for Napoli — a nice result!",
              options: ["risultato", "perdita", "esito", "punto"],
            },
            {
              template: "Non seguo molto il ___ , preferisco il tennis.",
              answer: "calcio",
              en: "I don't follow soccer much, I prefer tennis.",
              options: ["calcio", "tifoso", "pallone", "gioco"],
            },
            {
              template: "Sono ___ della Juventus da quando ero piccolo.",
              answer: "tifoso",
              en: "I've been a Juventus fan since I was little.",
              options: ["tifoso", "amico", "fan", "tifosa"],
            },
          ],
        },
      ],
    },
    {
      slug: "small-talk-exits",
      title: "Reactions and graceful exits",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "How to react and how to leave",
          body: [
            "Italians use a rich set of reaction phrases. Sprinkle them in:",
            "<em>«Davvero?!»</em> = Really?! / <em>«Sul serio?»</em> = Seriously?",
            "<em>«Ma dai!»</em> = Come on! / No way! (surprise or disbelief)",
            "<em>«Che bello!»</em> = How nice! / <em>«Che peccato!»</em> = What a shame!",
            "<em>«Mi dispiace.»</em> = I'm sorry (sympathy).",
            "Graceful exit lines: <em>«Allora ti / La saluto.»</em> = Well, I'll say goodbye. <em>«Devo scappare.»</em> = I have to run. <em>«Mi ha fatto piacere parlare con te / con Lei.»</em> = It was nice to talk with you.",
          ],
          keyPoint:
            "Reactions: davvero, ma dai, che bello, che peccato, mi dispiace. Exit: devo scappare / ti saluto / mi ha fatto piacere parlare.",
        },
        {
          type: "vocab",
          heading: "Reactions & exits",
          items: [
            { it: "davvero?!", en: "really?!" },
            { it: "sul serio?", en: "seriously?" },
            { it: "ma dai!", en: "come on! / no way!" },
            { it: "che bello!", en: "how nice!" },
            { it: "che peccato!", en: "what a shame!" },
            { it: "mi dispiace", en: "I'm sorry (sympathy or apology)" },
            { it: "complimenti!", en: "congratulations!" },
            { it: "auguri!", en: "best wishes! (birthday, holidays, etc.)" },
            { it: "in bocca al lupo!", en: "good luck!" },
            { it: "ti saluto / La saluto", en: "I'll say goodbye (informal / formal)" },
            { it: "devo scappare", en: "I have to run" },
            { it: "mi ha fatto piacere", en: "it was nice (to see you, etc.)" },
            { it: "ci vediamo presto", en: "see you soon" },
            { it: "fammi sapere / mi faccia sapere", en: "let me know" },
            { it: "buona giornata / serata / domenica", en: "have a good day / evening / Sunday" },
          ],
        },
        {
          type: "dialogue",
          heading: "Wrapping up a conversation",
          setup: "End of small talk at the café.",
          lines: [
            { speaker: "Signora", it: "Allora, è molto bello sentire un americano che parla bene l'italiano.", en: "Well, it's really nice to hear an American who speaks Italian well." },
            { speaker: "You", it: "Grazie, è ancora un cantiere aperto, ma ci provo.", en: "Thanks, it's still a work in progress, but I'm trying." },
            { speaker: "Signora", it: "Bravo. Quando torna in America?", en: "Good. When are you going back to America?" },
            { speaker: "You", it: "Tra una settimana. Ma spero di tornare presto.", en: "In a week. But I hope to come back soon." },
            { speaker: "Signora", it: "Sicuramente. Allora, La saluto. Devo scappare.", en: "Definitely. Well, I'll say goodbye. I have to run." },
            { speaker: "You", it: "Mi ha fatto piacere parlare con Lei. Buona giornata!", en: "It's been a pleasure talking with you. Have a good day!" },
            { speaker: "Signora", it: "Anche a Lei. In bocca al lupo per tutto!", en: "You too. Good luck with everything!" },
            { speaker: "You", it: "Crepi!", en: "Thanks! ('may the wolf die')" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Reaction & exit phrases",
          items: [
            {
              template: "Ma ___ ! Sul serio?",
              answer: "dai",
              en: "Come on! Seriously?",
              options: ["dai", "ciao", "no", "bene"],
            },
            {
              template: "Che ___ ! Non posso crederci.",
              answer: "bello",
              en: "How nice! I can't believe it.",
              options: ["bello", "buono", "bel", "grande"],
            },
            {
              template: "Mi ___ tantissimo per la tua famiglia.",
              answer: "dispiace",
              en: "I'm really sorry for your family. (sympathy)",
              options: ["dispiace", "ringrazio", "scuso", "piace"],
            },
            {
              template: "Devo ___ , ho un appuntamento.",
              answer: "scappare",
              en: "I have to run, I have an appointment.",
              options: ["scappare", "andare", "Both work — scappare is more casual", "uscire"],
            },
            {
              template: "Mi ha ___ piacere parlare con te.",
              answer: "fatto",
              en: "It's been a pleasure talking with you.",
              options: ["fatto", "dato", "preso", "ricevuto"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-it",
          prompt: "Really?! How nice! Congratulations!",
          reference: "Davvero?! Che bello! Complimenti!",
          hint: "Three back-to-back reaction phrases. Italians stack them naturally.",
        },
        {
          type: "tip",
          heading: "Italians double-cheek kiss (most of the time)",
          body: "Greetings between people who know each other: women-to-women and women-to-men typically do <em>due baci</em> = two cheek kisses (right cheek first, then left — barely touching). Men-to-men: handshake or hug between friends. Strangers / business: handshake. The cheek kiss feels weird to Americans but it's the default — go with it.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'It's hot today' =",
        options: [
          "È caldo oggi.",
          "Fa caldo oggi.",
          "C'è caldo oggi.",
          "Sta caldo oggi.",
        ],
        correct: 1,
      },
      {
        q: "Italians measure temperature in…",
        options: ["Fahrenheit", "Kelvin", "Celsius", "varies by region"],
        correct: 2,
      },
      {
        q: "'Which team do you support?' =",
        options: [
          "Quale squadra hai?",
          "Per quale squadra fai il tifo?",
          "Quale tifo hai?",
          "Sei di quale squadra?",
        ],
        correct: 1,
      },
      {
        q: "'Ma dai!' is closest to…",
        options: ["please!", "come on! / no way!", "give it to me!", "let's go!"],
        correct: 1,
      },
      {
        q: "'I'm sorry' (sympathy) =",
        options: ["Scusa.", "Mi dispiace.", "Perdono.", "Mi scuso."],
        correct: 1,
      },
      {
        q: "'I have to run' =",
        options: ["Devo correre.", "Devo scappare.", "Devo andare.", "Both B and C work — B is more casual."],
        correct: 3,
      },
      {
        q: "'See you soon' =",
        options: ["Ti vedo presto.", "Ci vediamo presto.", "Vediamoci presto.", "Both B and C are correct."],
        correct: 3,
      },
      {
        q: "Italian greeting between people who know each other =",
        options: [
          "single handshake",
          "two cheek kisses (right then left)",
          "head nod",
          "full hug",
        ],
        correct: 1,
      },
      {
        q: "Avoid as a small-talk topic with strangers =",
        options: [
          "weather",
          "food",
          "politics / mafia",
          "soccer",
        ],
        correct: 2,
      },
      {
        q: "Translate: 'Really?! What a shame!'",
        options: [
          "Veramente?! Che peccato!",
          "Davvero?! Che peccato!",
          "Sul serio?! Che bello!",
          "Both A and B work and are interchangeable.",
        ],
        correct: 3,
      },
    ],
  },
};
