import type { Unit } from "../types";

export const UNIT_OPINIONS: Unit = {
  slug: "opinions",
  stage: 8,
  order: 35,
  icon: "🗣️",
  title: "Opinions & debate",
  tagline: "Secondo me, sono d'accordo, però… The final capstone: structured opinions, polite disagreement, real conversation.",
  badge: "advanced",
  lessons: [
    {
      slug: "opinions-stating",
      title: "Stating an opinion",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "How to lead with 'I think…' without sounding lame",
          body: [
            "Italians have a hundred ways to share an opinion. Sprinkle them in to sound natural:",
            "<em>Secondo me…</em> = In my opinion… (the most common)",
            "<em>Penso che / Credo che + subjunctive</em> = I think / believe (that)…",
            "<em>Per me…</em> = For me… (slightly less formal than secondo me)",
            "<em>Trovo che + subjunctive</em> = I find that…",
            "<em>Mi sembra che + subjunctive</em> = It seems to me that…",
            "<em>A mio parere / A mio avviso</em> = In my view (more formal/written)",
            "<em>Direi che…</em> = I'd say that… (soft, conditional)",
          ],
          keyPoint:
            "Secondo me / per me (most common) · penso che / credo che + subjunctive (formal) · direi che (soft) · a mio parere (written).",
        },
        {
          type: "vocab",
          heading: "Opening an opinion",
          items: [
            { it: "secondo me", en: "in my opinion (most common)" },
            { it: "per me", en: "for me" },
            { it: "penso che + subjunctive", en: "I think that…" },
            { it: "credo che + subjunctive", en: "I believe that…" },
            { it: "trovo che + subjunctive", en: "I find that…" },
            { it: "mi sembra che + subjunctive", en: "it seems to me that…" },
            { it: "a mio parere / avviso", en: "in my view (more formal)" },
            { it: "direi che…", en: "I'd say that… (soft)" },
            { it: "ho l'impressione che + subj.", en: "I have the impression that…" },
            { it: "secondo la mia esperienza", en: "in my experience" },
            { it: "personalmente", en: "personally" },
            { it: "francamente / sinceramente", en: "frankly / honestly" },
            { it: "onestamente", en: "honestly" },
          ],
        },
        {
          type: "dialogue",
          heading: "Discussing a film",
          setup: "Post-cinema chat.",
          lines: [
            { speaker: "Anna", it: "Allora, cosa ne pensi del film?", en: "So, what do you think of the film?" },
            { speaker: "You", it: "Sinceramente, mi è piaciuto molto. Secondo me, la regia era fantastica.", en: "Honestly, I really liked it. In my opinion, the directing was fantastic." },
            { speaker: "Anna", it: "Concordo. E gli attori?", en: "I agree. And the actors?" },
            { speaker: "You", it: "Trovo che la protagonista sia bravissima. Mi sembra che reciti con una naturalezza incredibile.", en: "I find the lead actress is great. It seems to me she acts with incredible naturalness." },
            { speaker: "Anna", it: "Vero. Però il finale, secondo me, era un po' debole.", en: "True. But the ending, in my opinion, was a bit weak." },
            { speaker: "You", it: "Hai ragione, anche per me. Mi aspettavo qualcosa di più.", en: "You're right, also for me. I expected something more." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Pick the opener",
          items: [
            {
              template: "___ , il film era bellissimo.",
              answer: "Secondo me",
              en: "In my opinion, the film was beautiful.",
              options: ["Secondo me", "A mio", "Per", "Sono"],
            },
            {
              template: "Credo che ___ ragione tu. (avere)",
              answer: "abbia",
              en: "I believe you're right.",
              options: ["hai", "abbia", "avere", "avevi"],
            },
            {
              template: "Trovo che lui ___ molto interessante. (essere)",
              answer: "sia",
              en: "I find him very interesting.",
              options: ["è", "sia", "fosse", "era"],
            },
            {
              template: "Mi ___ che abbia ragione.",
              answer: "sembra",
              en: "It seems to me he's right.",
              options: ["sembra", "pare", "Both work", "credo"],
            },
            {
              template: "___ , preferisco un po' meno sale.",
              answer: "Personalmente",
              en: "Personally, I prefer a bit less salt.",
              options: ["Per me", "Personalmente", "Secondo me", "Both A and C work"],
            },
          ],
        },
      ],
    },
    {
      slug: "opinions-agree-disagree",
      title: "Agreeing and disagreeing",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Politely agreeing — and politely disagreeing",
          body: [
            "<strong>Agreeing:</strong>",
            "<em>Sono d'accordo.</em> = I agree.",
            "<em>Hai / Ha ragione.</em> = You're right.",
            "<em>Esatto / Esattamente.</em> = Exactly.",
            "<em>Concordo (con te / con Lei).</em> = I agree (more formal).",
            "<em>Anche per me.</em> = For me too.",
            "<strong>Disagreeing softly:</strong>",
            "<em>Non sono del tutto d'accordo.</em> = I'm not entirely in agreement.",
            "<em>Non sono sicuro / sicura.</em> = I'm not sure.",
            "<em>Però penso che…</em> = But I think that…",
            "<em>Da un lato sì, ma dall'altro…</em> = On the one hand yes, but on the other…",
            "<em>Vedo il tuo punto, però…</em> = I see your point, but…",
          ],
          keyPoint:
            "Agree: sono d'accordo, hai ragione, esatto, concordo. Disagree softly: non sono del tutto d'accordo, vedo il tuo punto però…",
        },
        {
          type: "vocab",
          heading: "Agree / disagree phrases",
          items: [
            { it: "sono d'accordo", en: "I agree" },
            { it: "hai / ha ragione", en: "you're right (informal / formal)" },
            { it: "esatto / esattamente", en: "exactly" },
            { it: "concordo (con te / Lei)", en: "I agree (formal)" },
            { it: "anche per me / anche secondo me", en: "for me too / I think so too" },
            { it: "in parte sì", en: "partly yes" },
            { it: "non sono del tutto d'accordo", en: "I'm not entirely in agreement" },
            { it: "non sono sicuro/a", en: "I'm not sure" },
            { it: "secondo me, invece…", en: "in my opinion, on the other hand…" },
            { it: "vedo il tuo punto, però…", en: "I see your point, but…" },
            { it: "da un lato… dall'altro…", en: "on one hand… on the other…" },
            { it: "non sono del parere", en: "I'm not of (that) opinion" },
            { it: "ti / Le faccio notare che…", en: "let me point out that…" },
          ],
        },
        {
          type: "tip",
          heading: "Italians enjoy debate — but stay civil",
          body: "In Italy, lively disagreement is normal in family dinners, café chats, even between strangers. It doesn't mean people are angry. <strong>However:</strong> avoid raising your voice, using sarcasm, or making it personal. Frame disagreement on the IDEA, not the person: <em>«Non condivido questa idea»</em> = I don't share this idea — vs <em>«Hai torto»</em> = you're wrong, which sounds harsh.",
        },
        {
          type: "dialogue",
          heading: "Polite back-and-forth",
          setup: "Friends arguing about whether Rome or Milan is better.",
          lines: [
            { speaker: "Marco", it: "Secondo me, Milano è molto più vivibile di Roma.", en: "In my opinion, Milan is much more livable than Rome." },
            { speaker: "You", it: "Vedo il tuo punto, ma non sono del tutto d'accordo. Roma ha qualcosa che Milano non ha.", en: "I see your point, but I'm not entirely in agreement. Rome has something Milan doesn't." },
            { speaker: "Marco", it: "Cosa, per esempio?", en: "Like what?" },
            { speaker: "You", it: "L'atmosfera, la storia. Cammini per il centro e sembra di essere in un museo a cielo aperto.", en: "The atmosphere, the history. You walk through the center and it feels like being in an open-air museum." },
            { speaker: "Marco", it: "Esatto, ma proprio per questo è caotica. Da un lato il fascino, dall'altro il caos quotidiano.", en: "Exactly, but that's why it's chaotic. On one hand the charm, on the other the daily chaos." },
            { speaker: "You", it: "Hai ragione anche tu. Forse dipende da quello che cerchi.", en: "You're also right. Maybe it depends on what you're looking for." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Agreement phrases",
          items: [
            {
              template: "Sono ___ con te, è così.",
              answer: "d'accordo",
              en: "I agree with you, it's like that.",
              options: ["d'accordo", "ragione", "uguale", "vero"],
            },
            {
              template: "Hai ___ , dovrei studiare di più.",
              answer: "ragione",
              en: "You're right, I should study more.",
              options: ["ragione", "vero", "esatto", "punto"],
            },
            {
              template: "Anche ___ me la pasta è meglio della pizza.",
              answer: "per",
              en: "For me too, pasta is better than pizza.",
              options: ["per", "secondo", "anche", "con"],
            },
            {
              template: "Vedo il tuo ___ , però penso diversamente.",
              answer: "punto",
              en: "I see your point, but I think differently.",
              options: ["pensiero", "opinione", "punto", "argomento"],
            },
            {
              template: "Da un ___ sì, ma dall'altro no.",
              answer: "lato",
              en: "On one hand yes, but on the other no.",
              options: ["lato", "parte", "Both work — lato is more common", "modo"],
            },
          ],
        },
      ],
    },
    {
      slug: "opinions-extended-discussion",
      title: "Building an argument & wrapping up",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Stringing thoughts together",
          body: [
            "Beyond just stating + agreeing, you'll want to build arguments and wrap them up:",
            "<em>Prima di tutto / Innanzitutto…</em> = First of all…",
            "<em>In secondo luogo / Poi…</em> = Secondly / Then…",
            "<em>Inoltre / In più…</em> = Furthermore / Plus…",
            "<em>Per esempio…</em> = For example…",
            "<em>D'altra parte…</em> = On the other hand…",
            "<em>In ogni caso…</em> = In any case…",
            "<em>Per concludere / Insomma…</em> = To conclude / In short…",
            "<em>Detto questo…</em> = Having said that…",
          ],
          keyPoint:
            "Build: prima di tutto → in secondo luogo → inoltre → per esempio → d'altra parte. Wrap: insomma / per concludere / detto questo.",
        },
        {
          type: "vocab",
          heading: "Discourse connectors",
          items: [
            { it: "innanzitutto / prima di tutto", en: "first of all" },
            { it: "in primo luogo", en: "in the first place" },
            { it: "in secondo luogo", en: "in the second place" },
            { it: "poi / inoltre / in più", en: "then / furthermore / plus" },
            { it: "per esempio / ad esempio", en: "for example" },
            { it: "in particolare", en: "in particular" },
            { it: "soprattutto", en: "above all" },
            { it: "d'altra parte / dall'altra", en: "on the other hand" },
            { it: "nonostante (ciò)", en: "despite (this)" },
            { it: "comunque / in ogni caso", en: "anyway / in any case" },
            { it: "per esempio…", en: "for example…" },
            { it: "in conclusione / per concludere", en: "in conclusion" },
            { it: "insomma", en: "in short / well" },
            { it: "detto questo", en: "having said that" },
            { it: "quindi / dunque", en: "so / therefore" },
          ],
        },
        {
          type: "dialogue",
          heading: "A reasoned argument",
          setup: "Discussing Italian-vs-American work culture.",
          lines: [
            { speaker: "You", it: "Secondo me la cultura del lavoro in Italia è molto diversa da quella americana, e in alcuni aspetti migliore.", en: "In my opinion the work culture in Italy is very different from the American one, and in some aspects better." },
            { speaker: "Marco", it: "Davvero? In che senso?", en: "Really? In what sense?" },
            { speaker: "You", it: "Innanzitutto, c'è più rispetto per la pausa pranzo — un vero pranzo, non un panino al PC. In secondo luogo, c'è più attenzione alla famiglia e al tempo libero.", en: "First of all, there's more respect for the lunch break — a real lunch, not a sandwich at the computer. Secondly, there's more attention to family and free time." },
            { speaker: "Marco", it: "Vero. D'altra parte però ci sono molti aspetti negativi — come la burocrazia, gli stipendi bassi.", en: "True. On the other hand though, there are many negative aspects — like the bureaucracy, the low salaries." },
            { speaker: "You", it: "Esatto. Per esempio, gli stipendi in America sono spesso più alti, ma si lavora molto di più e con meno protezioni.", en: "Exactly. For example, salaries in America are often higher, but you work much more and with fewer protections." },
            { speaker: "Marco", it: "Insomma, ogni sistema ha pro e contro.", en: "In short, every system has pros and cons." },
            { speaker: "You", it: "Esattamente. Detto questo, personalmente preferisco il ritmo italiano.", en: "Exactly. Having said that, personally I prefer the Italian rhythm." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Build the argument",
          items: [
            {
              template: "___ , bisogna ascoltare l'altro.",
              answer: "Prima di tutto",
              en: "First of all, you have to listen to the other person.",
              options: ["Prima di tutto", "Però", "Quindi", "Comunque"],
            },
            {
              template: "In secondo ___ , è importante dare il proprio parere.",
              answer: "luogo",
              en: "Secondly, it's important to give your opinion.",
              options: ["punto", "luogo", "modo", "parte"],
            },
            {
              template: "D'altra ___ , bisogna anche essere flessibili.",
              answer: "parte",
              en: "On the other hand, you also have to be flexible.",
              options: ["lato", "parte", "Both work — parte is the set phrase", "mano"],
            },
            {
              template: "___ , preferisco la cucina italiana.",
              answer: "Insomma",
              en: "In short, I prefer Italian cooking.",
              options: ["Insomma", "Per esempio", "Inoltre", "Quindi"],
            },
            {
              template: "Soprattutto, non bisogna ___ la calma.",
              answer: "perdere",
              en: "Above all, you shouldn't lose your cool.",
              options: ["trovare", "perdere", "tenere", "avere"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the argument",
          items: [
            { tokens: ["Secondo", "me", "il", "miglior", "ristorante", "è", "quello", "in", "via", "Cavour"], en: "In my opinion the best restaurant is the one on via Cavour." },
            { tokens: ["Innanzitutto", "il", "cibo", "è", "ottimo", ",", "e", "in", "più", "il", "servizio", "è", "veloce"], en: "First of all the food is excellent, and plus the service is fast." },
            { tokens: ["D'altra", "parte", "però", "è", "un", "po'", "caro"], en: "On the other hand, though, it's a bit expensive." },
            { tokens: ["Insomma", ",", "vale", "la", "pena", "almeno", "una", "volta"], en: "In short, it's worth it at least once." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-it",
          prompt: "In my opinion, first of all the price is too high. On the other hand, the quality is excellent.",
          reference: "Secondo me, prima di tutto il prezzo è troppo alto. D'altra parte, la qualità è ottima.",
          hint: "Three connector phrases stacked. 'Secondo me' + 'prima di tutto' + 'd'altra parte'.",
        },
        {
          type: "tip",
          heading: "You did it — full curriculum",
          body: "This is the last unit of 35. You've covered: sounds, greetings, numbers, articles, present tense, all the irregular verbs, possessives, questions, likes, sapere vs conoscere, connectors, all of Rome (transit, directions, hotel, help, landmarks), all of food (bar, trattoria, regional specialties), past tenses (avere + essere), imperfetto, future, narration, shopping, market, formal Lei, complaints, idioms, religion, museums, small talk, conditional, subjunctive, and opinions. You can now have any real conversation a tourist or A2-B1 speaker would have in Rome. <em>Bravissimo / Bravissima.</em>",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'In my opinion' (most common phrase) =",
        options: ["Penso", "Secondo me", "A mio avviso", "Per me"],
        correct: 1,
      },
      {
        q: "'I agree' =",
        options: ["Sono accordo.", "Sono d'accordo.", "Concordo.", "Both B and C work."],
        correct: 3,
      },
      {
        q: "'You're right' (informal) =",
        options: ["Hai ragione.", "Hai sbagliato.", "Hai detto bene.", "Sei giusto."],
        correct: 0,
      },
      {
        q: "Polite disagreement opener =",
        options: [
          "Sbagli completamente.",
          "Non sono del tutto d'accordo.",
          "Hai torto.",
          "No, no, no.",
        ],
        correct: 1,
      },
      {
        q: "'On the other hand' =",
        options: [
          "d'altra parte",
          "dall'altra mano",
          "ad altra parte",
          "in altra parte",
        ],
        correct: 0,
      },
      {
        q: "'First of all' =",
        options: ["primo", "innanzitutto / prima di tutto", "in primo punto", "all'inizio"],
        correct: 1,
      },
      {
        q: "'In short / well…' (wrap-up) =",
        options: ["finalmente", "insomma", "perciò", "quindi"],
        correct: 1,
      },
      {
        q: "'For example' =",
        options: ["per esempio", "ad esempio", "Both work — interchangeable", "in esempio"],
        correct: 2,
      },
      {
        q: "'I see your point, but…' =",
        options: [
          "Vedo che hai detto, ma…",
          "Vedo il tuo punto, però…",
          "Capisco il tuo opinione, ma…",
          "Sento il tuo punto, però…",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'In my opinion, first of all, you should listen. On the other hand, you have to speak too.'",
        options: [
          "Secondo me, prima di tutto, dovresti ascoltare. D'altra parte, devi anche parlare.",
          "Per me, primo, ascolti. Poi, parli.",
          "Nella mia opinione, prima, ascolto. Dopo, parlo.",
          "In opinion mia, ascolti prima. Parli anche.",
        ],
        correct: 0,
      },
    ],
  },
};
