import type { Unit } from "../../types";

export const UNIT_RESTAURANT: Unit = {
  slug: "restaurant",
  stage: 4,
  order: 16,
  icon: "🍽️",
  title: "At the restaurant",
  tagline: "Carta, menú del día, pedir, la cuenta.",
  lessons: [
    {
      slug: "restaurant-ordering",
      title: "Ordering at a Spanish restaurant",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "The menú del día",
          body: [
            "Spain's best lunchtime bargain is the <em>menú del día</em> — a set lunch menu available at most restaurants Monday–Friday. It typically includes a starter (<em>primer plato</em>), main (<em>segundo plato</em>), dessert or coffee, and bread and a drink — all for €10–15.",
            "Dinner is later than you're used to: most Spaniards eat at 9–10pm. Lunch (2–4pm) is the main meal of the day.",
          ],
          tip: {
            label: "La carta vs el menú",
            body: "In Spain, <em>la carta</em> = the full menu you choose from. <em>El menú</em> = a fixed-price set menu. Asking for 'el menú' means you want the set deal.",
          },
        },
        {
          type: "vocab",
          heading: "Restaurant vocabulary",
          items: [
            { l1: "la carta / el menú", en: "the menu / set menu" },
            { l1: "el primer plato", en: "the first course / starter" },
            { l1: "el segundo plato", en: "the main course" },
            { l1: "el postre", en: "the dessert" },
            { l1: "la bebida", en: "the drink" },
            { l1: "el pan", en: "the bread" },
            { l1: "la cuenta", en: "the bill" },
            { l1: "la propina", en: "the tip" },
          ],
        },
        {
          type: "vocab",
          heading: "Phrases for ordering",
          items: [
            { l1: "Una mesa para dos, por favor.", en: "A table for two, please." },
            { l1: "¿Nos puede traer la carta?", en: "Can you bring us the menu?" },
            { l1: "Quisiera el menú del día.", en: "I'd like the set menu." },
            { l1: "De primero quiero…", en: "For my starter I'll have…" },
            { l1: "De segundo, el pescado.", en: "For my main, the fish." },
            { l1: "¿Qué recomienda?", en: "What do you recommend?" },
            { l1: "¿Está incluido el pan?", en: "Is the bread included?" },
            { l1: "La cuenta, por favor.", en: "The bill, please." },
          ],
        },
        {
          type: "tip",
          heading: "De primero, de segundo — the magic words",
          body: "When you order from the <em>menú del día</em>, you choose one dish from each section. The waiter expects you to say <em>«De primero…»</em> (for the first course) and <em>«De segundo…»</em> (for the main). You don't need a full sentence — just <em>«De primero, la ensalada»</em> is perfectly natural. <em>De postre</em> covers dessert, and you can usually swap it for <em>café</em> or <em>fruta</em>.",
          example: { l1: "De primero, la sopa. De segundo, el pollo. Y de postre, flan.", en: "For the starter, the soup. For the main, the chicken. And for dessert, flan." },
        },
        {
          type: "multipleChoice",
          heading: "Restaurant check",
          questions: [
            {
              q: "What is the menú del día?",
              options: ["The full à la carte menu", "A fixed-price set lunch menu", "A menu only for tourists", "A menu of daily specials"],
              correct: 1,
              fb: "Menú del día = set lunch menu with starter, main, and dessert. Great value.",
            },
            {
              q: "In Spain, dinner is typically eaten at…",
              options: ["6pm", "7pm", "8pm", "9–10pm"],
              correct: 3,
              fb: "Spaniards eat dinner late — 9pm or later is standard.",
            },
            {
              q: "How do you ask 'What do you recommend?'",
              options: ["¿Qué quieres?", "¿Qué recomienda?", "¿Qué es bueno?", "¿Cuál es el mejor?"],
              correct: 1,
              fb: "¿Qué recomienda? is the polite form (usted). ¿Qué recomiendas? is informal.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Ordering the menú del día",
          intro: "Complete each phrase the way you'd say it to the waiter.",
          items: [
            {
              template: "Una ___ para dos, por favor.",
              answer: "mesa",
              en: "A table for two, please.",
              options: ["mesa", "carta", "cuenta", "silla"],
            },
            {
              template: "De ___ quiero la ensalada mixta.",
              answer: "primero",
              en: "For my starter I'll have the mixed salad.",
              options: ["primero", "segundo", "postre", "bebida"],
            },
            {
              template: "¿Nos puede traer la ___ , por favor?",
              answer: "carta",
              en: "Can you bring us the menu, please?",
              options: ["carta", "cuenta", "propina", "mesa"],
            },
            {
              template: "Para ___ , una botella de agua.",
              answer: "beber",
              en: "To drink, a bottle of water.",
              options: ["beber", "comer", "pagar", "traer"],
            },
            {
              template: "De ___ , quiero flan, por favor.",
              answer: "postre",
              en: "For dessert, I'll have flan, please.",
              options: ["postre", "primero", "segundo", "pan"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "A table for two, please. We'd like the set menu.",
          reference: "Una mesa para dos, por favor. Queremos el menú del día.",
          hint: "'Para dos' = for two. 'Queremos' (we want) is more natural than a literal 'we'd like' here, though 'quisiéramos' also works.",
        },
      ],
    },
    {
      slug: "restaurant-paying",
      title: "Paying and leaving",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The bill comes only when you ask",
          body: [
            "In Spain the waiter almost never brings <em>la cuenta</em> unprompted — lingering at the table (<em>la sobremesa</em>, chatting after the meal) is sacred, so rushing you out would be rude. Catch their eye and say <em>«La cuenta, por favor»</em> or make the little air-scribble gesture.",
            "Tipping is light: rounding up or leaving a euro or two per person is plenty. There's no 18–20% expectation — service is included in the price.",
            "Cards are accepted almost everywhere in cities, but small bars and rural spots may be cash-only, so it's worth asking <em>«¿Se puede pagar con tarjeta?»</em> before you order.",
          ],
          keyPoint: "Ask for la cuenta. Tip lightly (round up). Confirm card vs cash if unsure.",
        },
        {
          type: "vocab",
          heading: "Paying phrases",
          items: [
            { l1: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?" },
            { l1: "¿Está todo incluido?", en: "Is everything included?" },
            { l1: "Creo que hay un error en la cuenta.", en: "I think there's an error in the bill." },
            { l1: "¿Cobran por el pan?", en: "Do you charge for the bread?" },
            { l1: "¿Se acepta tarjeta?", en: "Do you accept card?" },
            { l1: "Vamos a pagar por separado.", en: "We'll pay separately." },
            { l1: "Quédese con el cambio.", en: "Keep the change." },
            { l1: "¿Me da el recibo, por favor?", en: "Can I have the receipt, please?" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Paying up",
          questions: [
            {
              q: "How do you ask if you can pay by card?",
              options: ["¿Puedo pagar con dinero?", "¿Puedo pagar con tarjeta?", "¿Se acepta efectivo?", "¿Cuánto es?"],
              correct: 1,
              fb: "Con tarjeta = by card. ¿Puedo pagar con tarjeta? is essential.",
            },
            {
              q: "'Vamos a pagar por separado' means…",
              options: ["We'll pay together", "We'll pay separately", "Can we split the bill?", "We need separate bills"],
              correct: 1,
              fb: "Por separado = separately. We'll pay separately.",
            },
            {
              q: "'Quédese con el cambio' means…",
              options: ["Give me the change", "Keep the change", "Where is the change?", "Count the change"],
              correct: 1,
              fb: "Quédese con el cambio = keep the change (formal, usted). A polite way to leave a small tip.",
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the paying phrases",
          intro: "Put the words in order.",
          items: [
            { tokens: ["La", "cuenta", ",", "por", "favor"], en: "The bill, please." },
            { tokens: ["¿", "Puedo", "pagar", "con", "tarjeta", "?"], en: "Can I pay by card?" },
            { tokens: ["Creo", "que", "hay", "un", "error", "en", "la", "cuenta"], en: "I think there's an error in the bill." },
            { tokens: ["Vamos", "a", "pagar", "por", "separado"], en: "We'll pay separately." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "The bill, please. Can we pay by card?",
          reference: "La cuenta, por favor. ¿Podemos pagar con tarjeta?",
          hint: "'Podemos' = can we (nosotros). Don't forget the opening ¿ on the question.",
        },
      ],
    },
    {
      slug: "restaurant-full-conversation",
      title: "A full restaurant experience",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Booking and arriving",
          body: [
            "For dinner at a popular spot, especially on weekends, it's smart to <em>reservar</em> (book): <em>«Quería reservar una mesa para cuatro el sábado a las nueve.»</em> On arrival the waiter asks <em>«¿Tienen reserva?»</em> — if not, you ask <em>«¿Tienen mesa para…?»</em>",
            "Inside, you'll choose between <em>la carta</em> (full à-la-carte menu) and <em>el menú del día</em>. If you want to know what's in a dish, ask <em>«¿Qué lleva este plato?»</em> — literally 'what does this dish carry?', the standard way to ask about ingredients.",
            "Common allergy/diet phrases are worth memorizing: <em>«Soy alérgico/a a…»</em> (I'm allergic to…) and <em>«¿Tienen algo sin gluten?»</em> (Do you have anything gluten-free?).",
          ],
          keyPoint: "Reservar → ¿Tienen reserva? → la carta or el menú → ¿Qué lleva este plato? → pedir.",
        },
        {
          type: "vocab",
          heading: "Reserving and asking about dishes",
          items: [
            { l1: "reservar una mesa", en: "to book a table" },
            { l1: "Quería reservar para el sábado.", en: "I'd like to book for Saturday." },
            { l1: "¿A nombre de quién?", en: "Under what name?" },
            { l1: "¿Qué lleva este plato?", en: "What's in this dish?" },
            { l1: "Soy alérgico / alérgica a…", en: "I'm allergic to… (m / f)" },
            { l1: "¿Tienen algo sin gluten?", en: "Do you have anything gluten-free?" },
            { l1: "¿Es picante?", en: "Is it spicy?" },
            { l1: "para llevar", en: "to take away" },
          ],
        },
        {
          type: "dialogue",
          heading: "From arrival to dessert",
          lines: [
            { speaker: "Waiter", l1: "Buenas tardes. ¿Tienen reserva?", en: "Good afternoon. Do you have a reservation?" },
            { speaker: "Guest", l1: "No, ¿tienen mesa para dos?", en: "No, do you have a table for two?" },
            { speaker: "Waiter", l1: "Sí, síganme por favor.", en: "Yes, follow me please." },
            { speaker: "Guest", l1: "¿Nos recomienda algo de hoy?", en: "Do you recommend anything from today's menu?" },
            { speaker: "Waiter", l1: "El bacalao al horno está muy bueno hoy.", en: "The baked cod is very good today." },
            { speaker: "Guest", l1: "Perfecto. Lo ponemos de segundo.", en: "Perfect. We'll have that as our main." },
          ],
        },
        {
          type: "vocab",
          heading: "Specific ordering phrases",
          items: [
            { l1: "¿Tienen mesa libre?", en: "Do you have a free table?" },
            { l1: "Síganme / Pase por aquí.", en: "Follow me / Come this way." },
            { l1: "¿Nos recomienda algo?", en: "Do you recommend anything?" },
            { l1: "Lo ponemos de segundo.", en: "We'll have that as our main." },
            { l1: "¿Qué viene con el plato?", en: "What comes with the dish?" },
            { l1: "¿Podemos pedir ya?", en: "Can we order now?" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Restaurant language",
          questions: [
            {
              q: "'¿Tienen mesa libre?' means…",
              options: ["Is the table free? (one specific table)", "Do you have a free table?", "Is this seat taken?", "Can I sit anywhere?"],
              correct: 1,
              fb: "¿Tienen mesa libre? = do you have a free/available table? The standard question on arrival.",
            },
            {
              q: "'Lo ponemos de segundo' means…",
              options: ["We'll have it as our starter", "We'll have it as our main", "We'll have two of it", "We'll have it second time around"],
              correct: 1,
              fb: "De segundo = as the main course. Lo ponemos = we'll have it (lit. we put it as).",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Reserving and asking",
          intro: "Fill in the gaps for these arrival-and-ordering phrases.",
          items: [
            {
              template: "Quería ___ una mesa para el sábado.",
              answer: "reservar",
              en: "I'd like to book a table for Saturday.",
              options: ["reservar", "pagar", "pedir", "traer"],
            },
            {
              template: "¿Qué ___ este plato?",
              answer: "lleva",
              en: "What's in this dish?",
              options: ["lleva", "cuesta", "quiere", "trae"],
            },
            {
              template: "Soy ___ a los frutos secos.",
              answer: "alérgico",
              en: "I'm allergic to nuts.",
              options: ["alérgico", "contento", "listo", "cansado"],
            },
            {
              template: "¿Tienen algo sin ___ ?",
              answer: "gluten",
              en: "Do you have anything gluten-free?",
              options: ["gluten", "sal", "carne", "azúcar"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "What's in this dish? I'm allergic to nuts.",
          reference: "¿Qué lleva este plato? Soy alérgico a los frutos secos.",
          hint: "'¿Qué lleva…?' is the idiomatic way to ask about ingredients. Use 'alérgica' if you're female; 'frutos secos' = nuts.",
        },
      ],
    }
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "The menú del día is…", options: ["À la carte menu", "Fixed-price set lunch", "Menu of the day's specials only", "A tourist menu"], correct: 1 },
      { q: "'La carta' is…", options: ["The set menu", "The full à la carte menu", "The bill", "The wine list"], correct: 1 },
      { q: "Spanish dinner is typically at…", options: ["6pm", "7pm", "8pm", "9–10pm"], correct: 3 },
      { q: "'De segundo, el pescado' means…", options: ["And also, the fish", "For my main, the fish", "Second, I want fish", "Fish for two"], correct: 1 },
      { q: "How do you ask for the bill?", options: ["El menú, por favor", "La cuenta, por favor", "La carta, por favor", "¿Puedo pagar?"], correct: 1 },
      { q: "'¿Qué recomienda?' is in…", options: ["Informal tú form", "Formal usted form", "Plural form", "Past tense"], correct: 1 },
      { q: "'¿Cobran por el pan?' means…", options: ["Is the bread good?", "Do you have bread?", "Do you charge for the bread?", "Is bread included?"], correct: 2 },
      { q: "How do you ask to pay separately?", options: ["Pago solo yo", "Vamos a pagar por separado", "Dos cuentas", "Pagamos juntos"], correct: 1 },
      { q: "How do you ask 'Can you bring us the menu?'", options: ["¿Nos puede traer la carta?", "¿Tiene la carta?", "Quiero la carta", "Deme la carta"], correct: 0 },
      { q: "'¿Se acepta tarjeta?' means…", options: ["Is the card mine?", "Do you accept card?", "Can I see the card?", "Is cash accepted?"], correct: 1 },
    ],
  },
};
