import type { Unit } from "../../types";

export const UNIT_FOOD_VOCAB: Unit = {
  slug: "food-vocab",
  stage: 4,
  order: 17,
  icon: "🥬",
  title: "Food vocab deep dive",
  tagline: "Verduras, carnes, pescados, formas de cocinar.",
  lessons: [
    {
      slug: "food-vocab-ingredients",
      title: "Ingredients and food groups",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Spanish food: regional, seasonal, generous",
          body: [
            "Spanish cooking leans on a handful of star ingredients: <em>el aceite de oliva</em> (olive oil), <em>el ajo</em> (garlic), <em>el pimiento</em> (pepper), and <em>el tomate</em>.",
            "Pork is everywhere — <em>el jamón</em> (cured ham), <em>el chorizo</em>, <em>el lomo</em> — and it's a point of pride: <em>el jamón ibérico</em> is world-famous.",
            "The coasts live on seafood: <em>el pulpo</em> (octopus) in Galicia, <em>las gambas</em> (prawns) and <em>el pescaíto frito</em> (fried little fish) in Andalusia.",
            "Vegetables shine in dishes like <em>el gazpacho</em> (cold tomato soup) and <em>el pisto</em> (vegetable stew), and legumes (<em>las judías</em>, <em>los garbanzos</em>, <em>las lentejas</em>) anchor hearty stews.",
          ],
          keyPoint:
            "Olive oil + garlic + pepper + tomato is the backbone. Pork (jamón, chorizo) and seafood (pulpo, gambas) are everywhere.",
        },
        {
          type: "vocab",
          heading: "Vegetables and fruit",
          items: [
            { l1: "la lechuga", en: "lettuce" },
            { l1: "el tomate", en: "tomato" },
            { l1: "la cebolla", en: "onion" },
            { l1: "el ajo", en: "garlic" },
            { l1: "el pimiento", en: "pepper (bell pepper)" },
            { l1: "la patata", en: "potato", note: "papa in Latin America" },
            { l1: "la zanahoria", en: "carrot" },
            { l1: "el calabacín", en: "courgette / zucchini" },
            { l1: "la berenjena", en: "eggplant / aubergine" },
            { l1: "el champiñón / la seta", en: "button mushroom / wild mushroom" },
            { l1: "la naranja", en: "orange" },
            { l1: "la manzana", en: "apple" },
            { l1: "el plátano", en: "banana", note: "banano in parts of Latin America" },
            { l1: "las uvas", en: "grapes" },
          ],
        },
        {
          type: "vocab",
          heading: "Meat, fish and dairy",
          items: [
            { l1: "la carne de ternera", en: "beef" },
            { l1: "el cerdo / el pollo", en: "pork / chicken" },
            { l1: "el cordero", en: "lamb" },
            { l1: "el jamón", en: "cured ham" },
            { l1: "el chorizo", en: "chorizo sausage" },
            { l1: "el salmón", en: "salmon" },
            { l1: "el bacalao", en: "cod (often salted)" },
            { l1: "la merluza", en: "hake (very common in Spain)" },
            { l1: "el pulpo", en: "octopus" },
            { l1: "las gambas", en: "prawns / shrimp" },
            { l1: "el marisco", en: "seafood/shellfish" },
            { l1: "el queso", en: "cheese" },
            { l1: "el huevo", en: "egg" },
          ],
        },
        {
          type: "vocab",
          heading: "Staples and pantry",
          intro: "The basics that show up in almost every Spanish kitchen.",
          items: [
            { l1: "el pan", en: "bread" },
            { l1: "el arroz", en: "rice (base of paella)" },
            { l1: "las judías", en: "beans / green beans" },
            { l1: "los garbanzos", en: "chickpeas" },
            { l1: "las lentejas", en: "lentils" },
            { l1: "el aceite de oliva", en: "olive oil" },
            { l1: "la sal", en: "salt" },
            { l1: "el azúcar", en: "sugar" },
            { l1: "la harina", en: "flour" },
            { l1: "el pimentón", en: "smoked paprika (key to chorizo)" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Food vocab check",
          questions: [
            {
              q: "'La patata' is called '___ ' in Latin America.",
              options: ["La papaya", "La papa", "La patata also", "La potato"],
              correct: 1,
              fb: "In Latin America, la papa is the standard word for potato.",
            },
            {
              q: "'El marisco' means…",
              options: ["Fish in general", "Seafood/shellfish", "The sea", "Smoked fish"],
              correct: 1,
              fb: "El marisco = seafood/shellfish — gambas, mejillones, langosta etc.",
            },
            {
              q: "'La merluza' is a kind of…",
              options: ["shellfish", "fish (hake)", "vegetable", "cheese"],
              correct: 1,
              fb: "La merluza (hake) is one of the most-eaten fish in Spain — often a la plancha or rebozada.",
            },
            {
              q: "'El pimentón' is essential to which food?",
              options: ["paella", "chorizo", "gazpacho", "tortilla"],
              correct: 1,
              fb: "El pimentón (smoked paprika) gives chorizo its deep red color and smoky flavor.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Build a shopping list",
          intro: "Pick the food that fits the sentence.",
          items: [
            {
              template: "Para hacer una tortilla necesito huevos y ___ .",
              answer: "patatas",
              en: "To make an omelette I need eggs and potatoes.",
              options: ["patatas", "naranjas", "gambas", "lechuga"],
            },
            {
              template: "El gazpacho lleva tomate, pepino y ___ .",
              answer: "pimiento",
              en: "Gazpacho contains tomato, cucumber and pepper.",
              options: ["pimiento", "queso", "cordero", "arroz"],
            },
            {
              template: "En Galicia es típico el ___ a la gallega.",
              answer: "pulpo",
              en: "In Galicia, octopus Galician-style is typical.",
              options: ["pulpo", "cordero", "jamón", "plátano"],
            },
            {
              template: "Soy alérgico al ___ , no puedo comer gambas ni mejillones.",
              answer: "marisco",
              en: "I'm allergic to shellfish, I can't eat prawns or mussels.",
              options: ["marisco", "queso", "pan", "huevo"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'd like half a kilo of prawns and a bit of cured ham, please.",
          reference: "Quiero medio kilo de gambas y un poco de jamón, por favor.",
          hint: "medio kilo de… (half a kilo of…), un poco de… (a bit of…), por favor (please).",
        },
      ],
    },
    {
      slug: "food-vocab-cooking",
      title: "Cooking methods",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "How Spaniards talk about cooking",
          body: [
            "Two phrases dominate Spanish menus: <strong>a la plancha</strong> (on a flat griddle, very common for fish and seafood) and <strong>al horno</strong> (baked/roasted).",
            "<strong>Frito/a</strong> (fried) is everywhere too — think <em>pescaíto frito</em> or <em>croquetas</em>. <strong>Rebozado/a</strong> means battered, like <em>calamares rebozados</em>.",
            "For meat doneness, ask for <strong>poco hecho</strong> (rare), <strong>al punto</strong> (medium), or <strong>muy hecho / bien hecho</strong> (well done).",
            "<strong>A la brasa</strong> (over embers / chargrilled) and <strong>en su tinta</strong> (in its own ink, for squid) are classics worth recognizing.",
          ],
          keyPoint:
            "A la plancha, al horno, frito, rebozado. Doneness: poco hecho (rare) → al punto (medium) → muy hecho (well done).",
        },
        {
          type: "vocab",
          heading: "How food is prepared",
          items: [
            { l1: "a la plancha", en: "grilled (on a flat griddle)" },
            { l1: "al horno", en: "baked/oven-roasted" },
            { l1: "frito/a", en: "fried" },
            { l1: "rebozado/a", en: "battered / breaded and fried" },
            { l1: "hervido/a", en: "boiled" },
            { l1: "a la brasa", en: "chargrilled (over embers)" },
            { l1: "crudo/a", en: "raw" },
            { l1: "en salsa", en: "in sauce" },
            { l1: "poco hecho / muy hecho", en: "rare / well done (steak)" },
            { l1: "al punto", en: "medium (steak)" },
            { l1: "picante", en: "spicy" },
          ],
        },
        {
          type: "vocab",
          heading: "Textures and tastes",
          intro: "Describe what's on the plate.",
          items: [
            { l1: "crujiente", en: "crunchy / crispy" },
            { l1: "jugoso/a", en: "juicy" },
            { l1: "tierno/a", en: "tender" },
            { l1: "duro/a", en: "tough / hard" },
            { l1: "soso/a", en: "bland / under-salted" },
            { l1: "salado/a", en: "salty / savory" },
            { l1: "dulce", en: "sweet" },
            { l1: "amargo/a", en: "bitter" },
            { l1: "ácido/a", en: "sour / acidic" },
          ],
        },
        {
          type: "dialogue",
          heading: "Ordering at the restaurant",
          setup: "You're ordering a fish main and a steak to share.",
          lines: [
            { speaker: "Tú", l1: "Perdone, ¿cómo está hecha la merluza?", en: "Excuse me, how is the hake cooked?" },
            { speaker: "Camarero", l1: "A la plancha, con un poco de ajo y aceite de oliva.", en: "On the griddle, with a bit of garlic and olive oil." },
            { speaker: "Tú", l1: "Perfecto. ¿Y el solomillo, lo puedo pedir poco hecho?", en: "Perfect. And the sirloin, can I order it rare?" },
            { speaker: "Camarero", l1: "Claro. ¿Poco hecho o al punto?", en: "Of course. Rare or medium?" },
            { speaker: "Tú", l1: "Al punto, por favor. Y de primero, gazpacho.", en: "Medium, please. And to start, gazpacho." },
            { speaker: "Camarero", l1: "Muy bien. ¿Algo de beber?", en: "Very good. Anything to drink?" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Cooking methods",
          questions: [
            {
              q: "If you want your steak medium, you ask for…",
              options: ["bien hecho", "poco hecho", "al punto", "a la plancha"],
              correct: 2,
              fb: "Al punto = medium. Poco hecho = rare. Muy/bien hecho = well done.",
            },
            {
              q: "'A la plancha' means…",
              options: ["Fried in oil", "Grilled on a flat griddle", "Baked in oven", "Chargrilled on open fire"],
              correct: 1,
              fb: "A la plancha = cooked on a flat metal griddle — one of the healthiest cooking methods.",
            },
            {
              q: "'Calamares rebozados' are squid that are…",
              options: ["raw", "battered and fried", "boiled", "grilled"],
              correct: 1,
              fb: "Rebozado = coated in batter and fried. Calamares rebozados are a tapas classic.",
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Put the order in order",
          intro: "Arrange the words into a natural sentence.",
          items: [
            {
              tokens: ["Quiero", "el", "pescado", "a", "la", "plancha"],
              en: "I want the fish grilled (on the griddle).",
            },
            {
              tokens: ["El", "filete", "lo", "prefiero", "al", "punto"],
              en: "I prefer the steak medium.",
            },
            {
              tokens: ["Las", "patatas", "están", "muy", "crujientes"],
              en: "The potatoes are very crispy.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'd like the hake grilled, with a salad on the side.",
          reference: "Quiero la merluza a la plancha, con una ensalada de acompañamiento.",
          hint: "a la plancha (grilled), una ensalada (a salad), de acompañamiento (on the side / as a side).",
        },
      ],
    },
    {
      slug: "food-vocab-shopping",
      title: "Food shopping phrases",
      estMinutes: 9,
      pages: [
        {
          type: "vocab",
          heading: "At the deli and cheese counter",
          items: [
            { l1: "¿De qué es este queso?", en: "What is this cheese made from?" },
            { l1: "de leche de vaca / oveja / cabra", en: "from cow's / sheep's / goat's milk" },
            { l1: "curado / semicurado / fresco", en: "mature / semi-cured / fresh" },
            { l1: "¿Tiene algo más picante?", en: "Do you have something spicier?" },
            { l1: "¿Puede cortarlo en lonchas?", en: "Can you slice it?" },
            { l1: "sin sal", en: "without salt / unsalted" },
            { l1: "¿Me pone medio kilo?", en: "Can you give me half a kilo?" },
            { l1: "¿A cuánto está el jamón?", en: "How much is the ham?" },
          ],
        },
        {
          type: "vocab",
          heading: "Describing dishes",
          items: [
            { l1: "asado/a", en: "roasted" },
            { l1: "estofado/a", en: "stewed" },
            { l1: "rehogado/a", en: "sautéed" },
            { l1: "empanado/a", en: "breaded" },
            { l1: "a la romana", en: "in batter (fried)" },
            { l1: "en adobo", en: "marinated" },
            { l1: "guisado/a", en: "braised / stewed" },
            { l1: "relleno/a", en: "stuffed / filled" },
          ],
        },
        {
          type: "dialogue",
          heading: "Buying ham at the market",
          setup: "You're at the deli counter in a Spanish mercado.",
          lines: [
            { speaker: "Tendero", l1: "Buenos días, ¿qué le pongo?", en: "Good morning, what can I get you?" },
            { speaker: "Tú", l1: "Buenos días. ¿A cuánto está el jamón ibérico?", en: "Good morning. How much is the Iberian ham?" },
            { speaker: "Tendero", l1: "Este está a noventa euros el kilo, pero merece la pena.", en: "This one is ninety euros a kilo, but it's worth it." },
            { speaker: "Tú", l1: "Vale. ¿Me pone dos cientos gramos, cortado fino?", en: "Okay. Can you give me two hundred grams, sliced thin?" },
            { speaker: "Tendero", l1: "Por supuesto. ¿Algo más?", en: "Of course. Anything else?" },
            { speaker: "Tú", l1: "Un poco de queso curado también, por favor.", en: "A bit of mature cheese too, please." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Food preparation fill",
          intro: "Choose the cooking word that fits.",
          items: [
            {
              template: "El pollo ___ es típico de los domingos en familia.",
              answer: "asado",
              en: "Roast chicken is typical of family Sundays.",
              options: ["asado", "crudo", "rebozado", "hervido"],
            },
            {
              template: "Los calamares ___ se hacen con harina y huevo.",
              answer: "a la romana",
              en: "Battered squid rings are made with flour and egg.",
              options: ["a la romana", "al horno", "en salsa", "estofados"],
            },
            {
              template: "El cocido es un plato ___ de garbanzos y carne.",
              answer: "guisado",
              en: "Cocido is a braised dish of chickpeas and meat.",
              options: ["guisado", "frito", "crudo", "empanado"],
            },
            {
              template: "Los pimientos ___ llevan carne o bacalao dentro.",
              answer: "rellenos",
              en: "Stuffed peppers have meat or cod inside.",
              options: ["rellenos", "asados", "crudos", "salados"],
            },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Food preparation check",
          questions: [
            {
              q: "'Asado' means…",
              options: ["fried", "boiled", "roasted", "raw"],
              correct: 2,
              fb: "Asado = roasted. Un pollo asado = a roast chicken.",
            },
            {
              q: "'A la romana' means…",
              options: ["Roman-style salad", "In batter (fried)", "With tomato sauce", "Grilled Roman-style"],
              correct: 1,
              fb: "A la romana = coated in batter and fried. Calamares a la romana = battered squid rings.",
            },
            {
              q: "'Estofado' describes a dish that is…",
              options: ["grilled quickly", "slowly stewed", "served raw", "deep-fried"],
              correct: 1,
              fb: "Estofado = stewed slowly in liquid, like estofado de ternera (beef stew).",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Can you slice me two hundred grams of mature cheese, please?",
          reference: "¿Me puede cortar doscientos gramos de queso curado, por favor?",
          hint: "¿Me puede cortar…? (can you slice me…?), doscientos gramos (two hundred grams), queso curado (mature cheese).",
        },
        {
          type: "tip",
          heading: "Asking for a tweak is normal",
          body: "Spanish kitchens are happy to adjust. You can say <em>«¿Lo pueden hacer sin sal / sin ajo?»</em> (Can you make it without salt / garlic?) or <em>«¿Tiene algo sin gluten?»</em> (Do you have anything gluten-free?). Don't be shy — asking is far better than leaving food on the plate.",
          example: { l1: "¿Lo pueden hacer sin picante, por favor?", en: "Can you make it without spice, please?" },
        },
      ],
    }
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "'El tomate' means…", options: ["the tomato", "the pepper", "the onion", "the garlic"], correct: 0 },
      { q: "'El ajo' means…", options: ["oil", "garlic", "onion", "vinegar"], correct: 1 },
      { q: "'Al horno' means…", options: ["grilled", "fried", "baked/oven-roasted", "boiled"], correct: 2 },
      { q: "'A la plancha' is…", options: ["Deep fried", "Grilled on flat griddle", "Baked", "Chargrilled"], correct: 1 },
      { q: "Steak 'al punto' is…", options: ["Rare", "Well done", "Medium", "Very rare"], correct: 2 },
      { q: "'El bacalao' is…", options: ["Salmon", "Tuna", "Cod", "Sea bass"], correct: 2 },
      { q: "'El marisco' includes…", options: ["All fish", "Shellfish and seafood", "Only shrimp", "Smoked fish"], correct: 1 },
      { q: "'Frito/a' means…", options: ["grilled", "baked", "fried", "boiled"], correct: 2 },
      { q: "'Poco hecho' for steak means…", options: ["Well done", "Medium", "Rare", "Overcooked"], correct: 2 },
      { q: "In Latin America, potato is…", options: ["la patata", "la papa", "la patate", "el patato"], correct: 1 },
      { q: "'La merluza' is…", options: ["hake (a fish)", "a vegetable", "a cheese", "octopus"], correct: 0 },
      { q: "'El pulpo' is…", options: ["prawns", "octopus", "lamb", "ham"], correct: 1 },
      { q: "'Rebozado/a' means…", options: ["raw", "roasted", "battered and fried", "boiled"], correct: 2 },
      { q: "Translate: 'It's too spicy for me.'", options: ["Está muy soso para mí.", "Está demasiado picante para mí.", "Me gusta el picante.", "No está picante."], correct: 1 },
    ],
  },
};
