import type { Unit } from "../../types";

export const UNIT_MARKET: Unit = {
  slug: "market",
  stage: 6,
  order: 26,
  icon: "🥕",
  title: "Market / mercado",
  tagline: "Kilos, gramos, me pone un kilo de…",
  badge: "tourist",
  lessons: [
    {
      slug: "market-vocab",
      title: "At the market",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Spain's covered markets",
          body: [
            "Spain has a rich tradition of covered food markets — <em>mercados municipales</em>. Madrid's Mercado de San Miguel and Mercado de La Paz, Barcelona's Boqueria — these are living food culture hubs, not just shops.",
            "At a stall you typically ask the vendor to give you what you want: <em>Me pone…</em> (literally 'put me' — give me…). Quantities are in kilograms and grams.",
          ],
        },
        {
          type: "vocab",
          heading: "Weights and quantities",
          items: [
            { l1: "un kilo de", en: "a kilogram of" },
            { l1: "medio kilo de", en: "half a kilogram of" },
            { l1: "cien gramos de", en: "one hundred grams of" },
            { l1: "un cuarto de kilo", en: "a quarter of a kilogram (250g)" },
            { l1: "una docena de", en: "a dozen" },
            { l1: "un manojo de", en: "a bunch of" },
            { l1: "una lata de", en: "a tin/can of" },
            { l1: "una botella de", en: "a bottle of" },
          ],
        },
        {
          type: "vocab",
          heading: "Market phrases",
          items: [
            { l1: "Me pone un kilo de tomates.", en: "Give me a kilo of tomatoes." },
            { l1: "¿A cómo está el jamón?", en: "How much is the ham (per unit)?" },
            { l1: "¿Qué tiene hoy?", en: "What do you have today? (What's fresh?)" },
            { l1: "¿Está maduro?", en: "Is it ripe?" },
            { l1: "Póngame medio kilo de queso manchego.", en: "Give me half a kilo of manchego cheese." },
            { l1: "¿Algo más?", en: "Anything else?" },
            { l1: "Es todo, gracias.", en: "That's all, thanks." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Market check",
          questions: [
            {
              q: "'Me pone un kilo de naranjas' is asking for…",
              options: ["Half a kilo of oranges", "A kilo of oranges", "One orange", "A bunch of oranges"],
              correct: 1,
              fb: "Me pone = give me. Un kilo de naranjas = a kilo of oranges.",
            },
            {
              q: "'¿A cómo está?' at a market means…",
              options: ["How is it?", "How much is it (per unit)?", "Is it fresh?", "Where does it come from?"],
              correct: 1,
              fb: "¿A cómo está? = how much is it (what's the current price)? Very common in markets.",
            },
          ],
        },
        {
          type: "tip",
          heading: "Ponme vs. me pone — tú or usted",
          body: "At a market stall you choose your register. With <em>usted</em> (polite, the default with a vendor you don't know) you say <em>me pone</em> or the imperative <em>póngame</em>. With <em>tú</em> (casual, your regular vendor) it becomes <em>me pones</em> or <em>ponme</em>. Both mean 'give me / put me' — Spaniards use this verb constantly instead of <em>quiero</em>, which can sound blunt.",
          example: { l1: "Ponme un cuarto de aceitunas, porfa.", en: "Give me a quarter-kilo of olives, please. (casual)" },
        },
        {
          type: "fillBlank",
          heading: "Order at the stall",
          intro: "Fill the blank with the right quantity or phrase.",
          items: [
            {
              template: "Me pone medio ___ de cerezas, por favor.",
              answer: "kilo",
              en: "Give me half a kilo of cherries, please.",
              options: ["litro", "kilo", "gramo", "docena"],
            },
            {
              template: "¿Me pone una ___ de huevos? Doce, sí.",
              answer: "docena",
              en: "Can you give me a dozen eggs? Twelve, yes.",
              options: ["docena", "lata", "botella", "manojo"],
            },
            {
              template: "Un ___ de kilo de jamón, que es para dos personas.",
              answer: "cuarto",
              en: "A quarter-kilo of ham, it's for two people.",
              options: ["medio", "cuarto", "cien", "manojo"],
            },
            {
              template: "Póngame cien ___ de queso curado.",
              answer: "gramos",
              en: "Give me a hundred grams of aged cheese.",
              options: ["kilos", "litros", "gramos", "docenas"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Give me a kilo of oranges and half a kilo of tomatoes, please.",
          reference: "Me pone un kilo de naranjas y medio kilo de tomates, por favor.",
          hint: "'Give me' at a stall = me pone. 'Half a kilo' = medio kilo.",
        },
      ],
    },
    {
      slug: "market-negotiating",
      title: "Choosing and leaving",
      estMinutes: 9,
      pages: [
        {
          type: "vocab",
          heading: "Commenting on produce",
          items: [
            { l1: "Están muy frescos.", en: "They're very fresh." },
            { l1: "Este está demasiado verde.", en: "This one is too unripe." },
            { l1: "¿Me puede poner uno más grande?", en: "Can you give me a bigger one?" },
            { l1: "¿Son de temporada?", en: "Are they in season?" },
            { l1: "¿Son locales / de aquí?", en: "Are they local / from here?" },
            { l1: "Me quedo con este.", en: "I'll take this one." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Final check",
          questions: [
            {
              q: "'¿Son de temporada?' means…",
              options: ["Are they expensive?", "Are they in season?", "Are they local?", "Are they fresh today?"],
              correct: 1,
              fb: "De temporada = in season. Seasonal produce is much valued in Spanish cooking.",
            },
            {
              q: "'Me quedo con este' means…",
              options: ["I'll leave this one", "I'll take this one", "This is mine", "I'll come back for this"],
              correct: 1,
              fb: "Quedarse con = to keep/take. Me quedo con este = I'll take/keep this one.",
            },
          ],
        },
        {
          type: "vocab",
          heading: "The specialist shops",
          intro: "A Spanish mercado de abastos groups stalls by specialty. Knowing the names tells you where to go.",
          items: [
            { l1: "la frutería", en: "the fruit & vegetable shop" },
            { l1: "la carnicería", en: "the butcher's" },
            { l1: "la pescadería", en: "the fishmonger's" },
            { l1: "la charcutería", en: "the deli (cured meats)" },
            { l1: "la panadería", en: "the bakery" },
            { l1: "el puesto", en: "the (market) stall" },
            { l1: "maduro / verde", en: "ripe / unripe" },
            { l1: "¿algo más?", en: "anything else?" },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the request",
          intro: "Put the words in order to make a natural market sentence.",
          items: [
            { tokens: ["¿", "A", "cuánto", "está", "el", "kilo", "de", "fresas", "?"], en: "How much is a kilo of strawberries?" },
            { tokens: ["Me", "quedo", "con", "estas", "manzanas", ",", "gracias"], en: "I'll take these apples, thanks." },
            { tokens: ["¿", "Me", "pone", "un", "manojo", "de", "perejil", "?"], en: "Can you give me a bunch of parsley?" },
            { tokens: ["¿", "Son", "de", "temporada", "los", "espárragos", "?"], en: "Are the asparagus in season?" },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "How much per kilo are the strawberries? Are they ripe?",
          reference: "¿A cuánto está el kilo de fresas? ¿Están maduras?",
          hint: "'How much per kilo' = ¿A cuánto está el kilo? 'Strawberries' (las fresas) is feminine plural, so maduras.",
        },
      ],
    },
    {
      slug: "market-full-visit",
      title: "A full market visit",
      estMinutes: 9,
      pages: [
        {
          type: "dialogue",
          heading: "At the fruit and vegetable stall",
          lines: [
            { speaker: "You", l1: "Buenos días. ¿Están maduras estas fresas?", en: "Good morning. Are these strawberries ripe?" },
            { speaker: "Vendor", l1: "Sí, llegaron esta mañana. Son de Huelva.", en: "Yes, they arrived this morning. They're from Huelva." },
            { speaker: "You", l1: "Me pone medio kilo, por favor.", en: "Give me half a kilo, please." },
            { speaker: "Vendor", l1: "¿Algo más?", en: "Anything else?" },
            { speaker: "You", l1: "Sí, un kilo de tomates y una lechuga.", en: "Yes, a kilo of tomatoes and a lettuce." },
            { speaker: "Vendor", l1: "Son cuatro euros con veinte en total.", en: "That's four euros twenty in total." },
          ],
        },
        {
          type: "vocab",
          heading: "Market numbers and transactions",
          items: [
            { l1: "Son cuatro euros con veinte.", en: "That's €4.20." },
            { l1: "Llegaron esta mañana.", en: "They arrived this morning. (very fresh)" },
            { l1: "Son de Huelva / de la zona.", en: "They're from Huelva / from around here." },
            { l1: "¿Los tienen más pequeños?", en: "Do you have smaller ones?" },
            { l1: "¿A cómo el kilo?", en: "How much per kilo?" },
            { l1: "Llévese estos, que están mejor.", en: "Take these, they're better." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Market conversation",
          questions: [
            {
              q: "'Son de Huelva' at a market stall means…",
              options: ["They cost from Huelva", "They come from Huelva (origin)", "They're on sale from Huelva", "They're Huelva brand"],
              correct: 1,
              fb: "Ser de = to be from. Origin is a selling point at Spanish markets.",
            },
            {
              q: "'¿A cómo el kilo?' means…",
              options: ["How many kilos?", "How heavy is it?", "How much per kilo?", "Can I have a kilo?"],
              correct: 2,
              fb: "¿A cómo? = at what price? ¿A cómo el kilo? = how much per kilo?",
            },
          ],
        },
        {
          type: "dialogue",
          heading: "At the fishmonger's",
          setup: "You're at the pescadería in La Boquería.",
          lines: [
            { speaker: "You", l1: "Buenas. ¿A cuánto están los boquerones hoy?", en: "Hi. How much are the anchovies today?" },
            { speaker: "Vendor", l1: "A nueve el kilo, frescos de esta mañana.", en: "Nine a kilo, fresh from this morning." },
            { speaker: "You", l1: "Vale. Póngame un cuarto de kilo.", en: "Okay. Give me a quarter-kilo." },
            { speaker: "Vendor", l1: "¿Se los limpio?", en: "Shall I clean them for you?" },
            { speaker: "You", l1: "Sí, por favor. ¿Algo de marisco fresco hoy?", en: "Yes, please. Any fresh shellfish today?" },
            { speaker: "Vendor", l1: "Tenemos gambas estupendas. ¿Le pongo medio kilo?", en: "We've got great prawns. Shall I give you half a kilo?" },
            { speaker: "You", l1: "Mejor un cuarto. Eso es todo, gracias.", en: "A quarter is better. That's all, thanks." },
          ],
        },
        {
          type: "tip",
          heading: "Spain's market culture",
          body: "A big-city <em>mercado de abastos</em> — Barcelona's La Boquería, Madrid's San Miguel, Valencia's Mercado Central — is a covered hall of independent <em>puestos</em>. You greet each vendor (<em>buenas</em>), wait your turn (<em>¿quién es el último?</em> = who's last in line?), and pay each stall separately. Many vendors will clean fish, debone, or recommend what's best that day if you ask <em>¿qué me recomienda?</em>",
          example: { l1: "¿Quién es el último para la pescadería?", en: "Who's last in line for the fish counter?" },
        },
        {
          type: "fillBlank",
          heading: "Round out the visit",
          intro: "Complete each market sentence.",
          items: [
            {
              template: "¿Quién es el ___? — Yo, vaya usted.",
              answer: "último",
              en: "Who's last in line? — Me, go ahead.",
              options: ["primero", "último", "puesto", "kilo"],
            },
            {
              template: "Estos melocotones están muy ___, los como hoy.",
              answer: "maduros",
              en: "These peaches are very ripe, I'll eat them today.",
              options: ["verdes", "maduros", "frescas", "caros"],
            },
            {
              template: "¿Qué me ___ para hacer una paella?",
              answer: "recomienda",
              en: "What do you recommend for making a paella?",
              options: ["recomienda", "pone", "cuesta", "queda"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'll take a quarter-kilo of prawns. That's all, thanks.",
          reference: "Me llevo un cuarto de kilo de gambas. Eso es todo, gracias.",
          hint: "'I'll take' (I'm taking it with me) = me llevo. 'That's all' = eso es todo.",
        },
      ],
    }
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "'Me pone…' at a market means…", options: ["Put it there", "Give me…", "I want…", "I'll take…"], correct: 1 },
      { q: "'Medio kilo' is…", options: ["100g", "250g", "500g", "750g"], correct: 2 },
      { q: "'Un cuarto de kilo' is…", options: ["100g", "250g", "500g", "750g"], correct: 1 },
      { q: "'¿A cómo está?' means…", options: ["How is it?", "What's the price?", "Is it ripe?", "Where is it from?"], correct: 1 },
      { q: "'¿Está maduro?' means…", options: ["Is it fresh?", "Is it ripe?", "Is it local?", "Is it organic?"], correct: 1 },
      { q: "'Una docena de huevos' is…", options: ["A box of eggs", "A dozen eggs", "Half a dozen eggs", "Six eggs"], correct: 1 },
      { q: "'¿Son de temporada?' means…", options: ["Are they fresh?", "Are they in season?", "Are they local?", "Are they frozen?"], correct: 1 },
      { q: "'Es todo, gracias' at a stall means…", options: ["Thanks, this is good", "That's all, thanks", "Everything is good", "Thank you very much"], correct: 1 },
      { q: "'Me quedo con este' means…", options: ["I'll leave this", "I'll take this one", "This is too much", "I'll come back"], correct: 1 },
      { q: "'¿Algo más?' means…", options: ["Something else?", "Is that all?", "How much more?", "Any other size?"], correct: 0 },
    ],
  },
};
