import type { Unit } from "../../types";

export const UNIT_GREETINGS: Unit = {
  slug: "greetings",
  stage: 1,
  order: 2,
  icon: "👋",
  title: "Greetings & politeness",
  tagline: "Oi, olá, bom dia, tudo bem? — and tu vs você, BR vs PT.",
  badge: "core",
  lessons: [
    {
      slug: "greetings-hello",
      title: "Saying hello and goodbye",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Oi, olá — and the time of day",
          body: [
            "In Brazil, the everyday hello is <em>oi</em> — short, warm, and used with almost anyone. <em>Olá</em> is a touch more neutral, and <em>e aí?</em> is the casual 'hey, what's up?' you'll hear among friends.",
            "Then there are the time-of-day greetings: <em>bom dia</em> (morning), <em>boa tarde</em> (afternoon), <em>boa noite</em> (evening/night). These double as polite goodbyes too.",
            "To say goodbye, the all-purpose word is <em>tchau</em> (yes, spelled the Italian way — Brazilians borrowed it). For 'see you', use <em>até logo</em> or <em>até mais</em>.",
          ],
          tip: {
            label: "Bom dia vs boa tarde",
            body: "Bom dia is masculine (o dia = the day); boa tarde and boa noite are feminine (a tarde, a noite). The adjective agrees with the noun, which is why it flips from bom to boa.",
          },
        },
        {
          type: "vocab",
          heading: "Essential greetings",
          items: [
            { l1: "Oi", en: "Hi", note: "The default casual hello in Brazil" },
            { l1: "Olá", en: "Hello", note: "Slightly more neutral; works any time" },
            { l1: "E aí?", en: "Hey, what's up?", note: "Very casual, among friends (BR)" },
            { l1: "Bom dia", en: "Good morning", note: "Until around noon" },
            { l1: "Boa tarde", en: "Good afternoon", note: "From midday to dusk" },
            { l1: "Boa noite", en: "Good evening / Good night", note: "After dark — also used to say goodnight" },
            { l1: "Tchau", en: "Bye", note: "The everyday goodbye; borrowed from Italian ciao" },
            { l1: "Até logo", en: "See you later", note: "" },
            { l1: "Até mais", en: "See you / Catch you later", note: "" },
            { l1: "Até amanhã", en: "See you tomorrow", note: "" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Quick check",
          questions: [
            {
              q: "Which greeting do you use in the afternoon?",
              options: ["Bom dia", "Boa tarde", "Boa noite", "Tchau"],
              correct: 1,
              fb: "Boa tarde = good afternoon. Bom dia = morning, boa noite = evening.",
            },
            {
              q: "What's the most common casual 'hi' in Brazil?",
              options: ["Olá", "Oi", "Bom dia", "Até logo"],
              correct: 1,
              fb: "Oi is the everyday Brazilian hello — friendly and used with almost anyone.",
            },
            {
              q: "Why is it 'boa tarde' but 'bom dia'?",
              options: ["Random exception", "Tarde is feminine, dia is masculine", "Tarde is plural", "Regional variation"],
              correct: 1,
              fb: "Adjectives agree with the noun's gender. o dia (day) is masculine → bom. a tarde (afternoon) is feminine → boa.",
            },
          ],
        },
        {
          type: "tip",
          heading: "Tchau, but in Portugal you'll also hear adeus",
          body: "<em>Tchau</em> is universal in Brazil and common in Portugal too. But in Portugal you'll often hear <em>adeus</em> (a more definite goodbye) and the cheerful <em>até já</em> (see you in a moment). Brazilians rarely say adeus — it sounds final, almost dramatic.",
          example: { l1: "Tchau, até amanhã!", en: "Bye, see you tomorrow!" },
        },
        {
          type: "dialogue",
          heading: "A quick hello at a padaria in São Paulo",
          setup: "You step into a bakery mid-morning to grab a coffee.",
          lines: [
            { speaker: "Você", l1: "Bom dia!", en: "Good morning!" },
            { speaker: "Atendente", l1: "Bom dia! Pois não?", en: "Good morning! How can I help?" },
            { speaker: "Você", l1: "Um cafezinho, por favor.", en: "A little coffee, please." },
            { speaker: "Atendente", l1: "Saindo. Aqui está.", en: "Coming right up. Here you go." },
            { speaker: "Você", l1: "Obrigado! Tchau, até logo.", en: "Thank you! Bye, see you later." },
            { speaker: "Atendente", l1: "De nada. Até logo!", en: "You're welcome. See you!" },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the greeting",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Bom", "dia", "senhora"], en: "Good morning, ma'am." },
            { tokens: ["Até", "logo", "e", "obrigado"], en: "See you later and thank you." },
            { tokens: ["Oi", "boa", "tarde"], en: "Hi, good afternoon." },
            { tokens: ["Tchau", "até", "amanhã"], en: "Bye, see you tomorrow." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Good morning! See you later.",
          reference: "Bom dia! Até logo.",
          hint: "Bom dia is masculine. 'See you later' = até logo (or até mais).",
        },
      ],
    },
    {
      slug: "greetings-courtesy",
      title: "Tudo bem? and being polite",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "How are you? — the Brazilian way",
          body: [
            "The classic Brazilian check-in is <em>tudo bem?</em> — literally 'all well?'. The standard reply is also <em>tudo bem</em>, often with <em>e você?</em> ('and you?'). You'll also hear <em>tudo bom?</em> — same meaning, equally common.",
            "More casual still is <em>beleza?</em> (literally 'beauty?' = 'all good?'), and the slightly more formal <em>como vai?</em> ('how's it going?').",
            "When you meet someone, say <em>prazer</em> or <em>muito prazer</em> ('a pleasure'). It's the standard 'nice to meet you'.",
          ],
          keyPoint: "tudo bem? / tudo bom? = how are you · beleza? = casual 'all good?' · prazer = nice to meet you.",
        },
        {
          type: "vocab",
          heading: "Asking and answering",
          items: [
            { l1: "Tudo bem?", en: "How are you? (lit. all well?)", note: "The everyday check-in" },
            { l1: "Tudo bom?", en: "How are you? (lit. all good?)", note: "Same as tudo bem" },
            { l1: "Como vai?", en: "How's it going?", note: "A touch more formal" },
            { l1: "Beleza?", en: "All good? / Cool?", note: "Very casual (BR slang)" },
            { l1: "Tudo bem, e você?", en: "Fine, and you?", note: "Standard reply" },
            { l1: "Tudo ótimo!", en: "Everything's great!", note: "" },
            { l1: "Mais ou menos", en: "So-so", note: "Honest, neutral answer" },
            { l1: "Prazer", en: "Nice to meet you (lit. pleasure)", note: "" },
            { l1: "Muito prazer", en: "Very nice to meet you", note: "" },
            { l1: "Igualmente", en: "Likewise", note: "Reply to 'prazer'" },
          ],
        },
        {
          type: "vocab",
          heading: "Magic words of courtesy",
          intro: "The phrases that make you sound polite anywhere in the Portuguese-speaking world.",
          items: [
            { l1: "Por favor", en: "Please", note: "" },
            { l1: "Obrigado", en: "Thank you (man speaking)", note: "Male speakers say obrigado" },
            { l1: "Obrigada", en: "Thank you (woman speaking)", note: "Female speakers say obrigada" },
            { l1: "De nada", en: "You're welcome", note: "lit. 'of nothing'" },
            { l1: "Com licença", en: "Excuse me", note: "To pass by or get attention" },
            { l1: "Desculpa", en: "Sorry (informal)", note: "" },
            { l1: "Desculpe", en: "Sorry / Excuse me (formal)", note: "" },
            { l1: "Por nada", en: "You're welcome", note: "Common alternative to de nada (BR)" },
          ],
        },
        {
          type: "tip",
          heading: "Obrigado or obrigada? It depends on YOU",
          body: "Unlike English 'thank you', the Portuguese word for thanks agrees with the <em>speaker's</em> gender, not the listener's. A man always says <em>obrigado</em>; a woman always says <em>obrigada</em> — regardless of who they're thanking. This holds in both Brazil and Portugal.",
          example: { l1: "— Aqui está. — Obrigada! (woman) / Obrigado! (man)", en: "— Here you go. — Thank you!" },
        },
        {
          type: "multipleChoice",
          heading: "Polite or not?",
          questions: [
            {
              q: "A woman wants to say 'thank you'. She says…",
              options: ["Obrigado", "Obrigada", "De nada", "Por favor"],
              correct: 1,
              fb: "A woman says obrigada — the ending agrees with the speaker's own gender, not the listener's.",
            },
            {
              q: "You need to squeeze past someone in a crowd. You say…",
              options: ["De nada", "Com licença", "Tudo bem", "Igualmente"],
              correct: 1,
              fb: "Com licença = excuse me, used to pass by or politely get attention.",
            },
            {
              q: "Someone says 'muito prazer'. A natural reply is…",
              options: ["De nada", "Igualmente", "Tchau", "Mais ou menos"],
              correct: 1,
              fb: "Igualmente = likewise. The standard answer to 'prazer / muito prazer'.",
            },
            {
              q: "'Beleza?' is best described as…",
              options: ["Very formal", "Only used at night", "Casual Brazilian 'all good?'", "Rude"],
              correct: 2,
              fb: "Beleza? is relaxed Brazilian slang — like 'all good?' or 'cool?'. Save it for friends.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Fill in the courtesy word",
          intro: "Choose the phrase that fits.",
          items: [
            {
              template: "Um café, ___ favor.",
              answer: "por",
              en: "A coffee, please.",
              options: ["por", "de", "com", "muito"],
            },
            {
              template: "— ___ pela ajuda! (said by a man)",
              answer: "Obrigado",
              en: "Thank you for the help! (man speaking)",
              options: ["Obrigado", "Obrigada", "De nada", "Igualmente"],
            },
            {
              template: "— Obrigada! — ___ nada.",
              answer: "De",
              en: "— Thank you! — You're welcome.",
              options: ["De", "Por", "Com", "Até"],
            },
            {
              template: "___ licença, posso passar?",
              answer: "Com",
              en: "Excuse me, may I get by?",
              options: ["Com", "Por", "De", "Muito"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Hi, how are you? Nice to meet you.",
          reference: "Oi, tudo bem? Muito prazer.",
          hint: "Use the casual 'oi' and 'tudo bem?'. 'Nice to meet you' = (muito) prazer.",
        },
      ],
    },
    {
      slug: "greetings-practice",
      title: "Real greetings in context",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Tu vs você — Brazil and Portugal split here",
          body: [
            "In Brazil, the normal word for 'you' is <strong>você</strong> — informal and neutral all at once. You'll use it with friends, colleagues, and most strangers. For real formality (an elder, an official), Brazilians reach for <em>o senhor</em> / <em>a senhora</em>.",
            "In Portugal, informal speech usually uses <strong>tu</strong> (with its own verb endings — <em>tu estás</em>, <em>tu tens</em>), and <em>você</em> can sound oddly formal or even distant. So 'how are you?' is <em>tudo bem?</em> in Brazil and often <em>como estás?</em> in Portugal.",
            "Good news: across this course the spine is Brazilian, so você is your default. Just recognise tu when you meet it.",
          ],
          keyPoint: "BR: você = normal 'you'; o senhor/a senhora = formal. PT: tu = informal (own verb endings); você = more formal.",
        },
        {
          type: "tip",
          heading: "Spotting tu vs você in the wild",
          body: "Listen for the verb ending. Brazilian <em>Como você está?</em> uses the same 'está' form as the formal 'o senhor'. European Portuguese <em>Como estás?</em> drops the pronoun and uses the special tu-ending '-as'. Same question, two systems — and Brazilians will understand you perfectly either way.",
          example: { l1: "BR: Você está bem? · PT: (Tu) estás bem?", en: "Are you okay?" },
        },
        {
          type: "dialogue",
          heading: "Meeting someone for the first time (Brazil)",
          lines: [
            { speaker: "Ana", l1: "Bom dia. Como você se chama?", en: "Good morning. What's your name?" },
            { speaker: "Tom", l1: "Me chamo Tom. E você?", en: "My name is Tom. And you?" },
            { speaker: "Ana", l1: "Sou a Ana. Muito prazer.", en: "I'm Ana. Very nice to meet you." },
            { speaker: "Tom", l1: "Prazer, Ana. De onde você é?", en: "Pleasure, Ana. Where are you from?" },
            { speaker: "Ana", l1: "Sou de São Paulo. E você?", en: "I'm from São Paulo. And you?" },
            { speaker: "Tom", l1: "Sou inglês, de Londres.", en: "I'm English, from London." },
          ],
        },
        {
          type: "dialogue",
          heading: "Greeting a friend",
          lines: [
            { speaker: "Carlos", l1: "E aí, Lúcia! Tudo bem?", en: "Hey, Lúcia! How are you?" },
            { speaker: "Lúcia", l1: "Tudo bem, e você?", en: "I'm fine, and you?" },
            { speaker: "Carlos", l1: "Mais ou menos. Estou cansado.", en: "So-so. I'm tired." },
            { speaker: "Lúcia", l1: "Que pena. Bom, até mais.", en: "What a shame. Well, see you." },
            { speaker: "Carlos", l1: "Tchau, até logo!", en: "Bye, see you later!" },
          ],
        },
        {
          type: "pronounce",
          heading: "Greetings to practise aloud",
          items: [
            { l1: "Bom dia", en: "Good morning", tip: "bohn JEE-ah (the 'di' softens to a 'jee' in BR)" },
            { l1: "Tudo bem?", en: "How are you?", tip: "TOO-doo BENG" },
            { l1: "Muito prazer", en: "Nice to meet you", tip: "MWEEN-too prah-ZEHR" },
            { l1: "Obrigado / Obrigada", en: "Thank you (m/f)", tip: "oh-bree-GAH-doo / -dah" },
            { l1: "Até logo", en: "See you later", tip: "ah-TEH LOH-goo" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Conversation check",
          questions: [
            {
              q: "In Brazil, the normal everyday word for 'you' is…",
              options: ["tu", "você", "vós", "o senhor (always)"],
              correct: 1,
              fb: "In Brazil você is the neutral, everyday 'you'. Portugal leans on tu for informal speech.",
            },
            {
              q: "You're greeting an elderly stranger respectfully in Brazil. You'd likely use…",
              options: ["você", "tu", "o senhor / a senhora", "e aí"],
              correct: 2,
              fb: "For real respect, Brazilians use o senhor / a senhora rather than você.",
            },
            {
              q: "Your friend asks 'tudo bem?' and you feel tired. You say…",
              options: ["Muito prazer", "Mais ou menos, estou cansado/a", "Igualmente", "Bom dia"],
              correct: 1,
              fb: "Mais ou menos = so-so. Estou cansado (m) / cansada (f) = I'm tired.",
            },
            {
              q: "In Portugal, 'Como estás?' is using which 'you'?",
              options: ["você (formal)", "tu (informal)", "o senhor", "nobody — it's wrong"],
              correct: 1,
              fb: "Como estás? uses the European-Portuguese tu form, with the special '-as' ending.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate the introduction",
          direction: "en-to-l1",
          prompt: "Good afternoon. What's your name? I'm from Brazil.",
          reference: "Boa tarde. Como você se chama? Sou do Brasil.",
          hint: "Use the Brazilian 'você se chama' for 'what's your name'. 'I'm from Brazil' = sou do Brasil.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "Which greeting means 'good morning'?", options: ["Boa noite", "Boa tarde", "Bom dia", "Tchau"], correct: 2 },
      { q: "The most common casual 'hi' in Brazil is…", options: ["Olá", "Oi", "Adeus", "Até logo"], correct: 1 },
      { q: "Which means 'see you later'?", options: ["Tchau", "Até logo", "Bom dia", "De nada"], correct: 1 },
      { q: "Why 'boa tarde' but 'bom dia'?", options: ["Arbitrary", "tarde is feminine, dia is masculine", "Regional preference", "tarde is plural"], correct: 1 },
      { q: "A man saying 'thank you' says…", options: ["Obrigada", "Obrigado", "De nada", "Por favor"], correct: 1 },
      { q: "A woman saying 'thank you' says…", options: ["Obrigado", "Obrigada", "Por nada", "Igualmente"], correct: 1 },
      { q: "'Tudo bem?' means…", options: ["What time is it?", "How are you?", "Where are you from?", "What's your name?"], correct: 1 },
      { q: "In Brazil, the normal everyday 'you' is…", options: ["tu", "você", "vós", "o senhor"], correct: 1 },
      { q: "In Portugal, informal speech commonly uses…", options: ["você", "tu", "o senhor", "a gente"], correct: 1 },
      { q: "'Com licença' is used to…", options: ["say thank you", "pass by / get attention politely", "say goodbye", "say good night"], correct: 1 },
      { q: "The reply 'mais ou menos' to tudo bem? means…", options: ["Great!", "Terrible", "So-so", "More or less done"], correct: 2 },
      { q: "You meet someone new. You say…", options: ["De nada", "Muito prazer", "Tchau", "Beleza"], correct: 1 },
    ],
  },
};
