import type { Unit } from "../../types";

export const UNIT_NUMBERS_TIME: Unit = {
  slug: "numbers-time",
  stage: 1,
  order: 3,
  icon: "🔢",
  title: "Numbers, days & time",
  tagline: "0–1000, que horas são?, dias da semana, datas.",
  badge: "core",
  lessons: [
    {
      slug: "numbers-0-100",
      title: "Numbers 0–100",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Numbers in Portuguese — spot the patterns",
          body: [
            "Portuguese numbers 1–15 must be memorised individually. From 16 onward a clean pattern takes over: the tens join the units with <em>e</em> (and): 21 = <em>vinte e um</em>, 35 = <em>trinta e cinco</em>, 99 = <em>noventa e nove</em>.",
            "The tricky part is gender. <em>Um/uma</em> (1) and <em>dois/duas</em> (2) agree with the noun: <em>um livro / uma casa</em>, <em>dois livros / duas casas</em>. The other numbers don't change.",
          ],
          tip: {
            label: "100 = cem vs cento",
            body: "Exactly 100 is <em>cem</em>. The moment you add anything to it, it becomes <em>cento</em>: <em>cento e um</em> (101), <em>cento e cinquenta</em> (150).",
          },
          keyPoint: "Join tens to units with e: vinte e um, trinta e cinco, noventa e nove.",
        },
        {
          type: "vocab",
          heading: "0–20",
          items: [
            { l1: "zero, um, dois, três", en: "0, 1, 2, 3" },
            { l1: "quatro, cinco, seis", en: "4, 5, 6" },
            { l1: "sete, oito, nove", en: "7, 8, 9" },
            { l1: "dez, onze, doze", en: "10, 11, 12" },
            { l1: "treze, catorze, quinze", en: "13, 14, 15", note: "BR also spells 14 as 'quatorze'" },
            { l1: "dezesseis, dezessete", en: "16, 17", note: "PT spells these 'dezasseis, dezassete'" },
            { l1: "dezoito, dezenove", en: "18, 19", note: "PT: 'dezanove' for 19" },
            { l1: "vinte", en: "20" },
          ],
        },
        {
          type: "vocab",
          heading: "Tens and key numbers",
          items: [
            { l1: "trinta, quarenta, cinquenta", en: "30, 40, 50" },
            { l1: "sessenta, setenta, oitenta, noventa", en: "60, 70, 80, 90" },
            { l1: "cem", en: "100", note: "cem alone; cento before more digits" },
            { l1: "vinte e um, trinta e um", en: "21, 31" },
            { l1: "cinquenta e cinco", en: "55" },
            { l1: "noventa e nove", en: "99" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Quick check",
          questions: [
            {
              q: "How do you say 45?",
              options: ["quarenta e quatro", "quarenta e cinco", "cinquenta e cinco", "quarenta cinco"],
              correct: 1,
              fb: "Quarenta (40) + e + cinco (5) = quarenta e cinco.",
            },
            {
              q: "Which is correct for 'two houses' (casa is feminine)?",
              options: ["dois casas", "duas casas", "dois casa", "duas casa"],
              correct: 1,
              fb: "Dois → duas before a feminine noun: duas casas, duas horas.",
            },
            {
              q: "What is exactly 100?",
              options: ["cento", "cem", "cento e um", "mil"],
              correct: 1,
              fb: "Cem is exactly 100. Add anything and it becomes cento (cento e dez = 110).",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Build the number",
          intro: "Fill in the missing piece. In-between numbers join the tens to the units with e.",
          items: [
            {
              template: "trinta ___ sete",
              answer: "e",
              en: "thirty-seven (37)",
              options: ["e", "y", "com", "mais"],
            },
            {
              template: "Tenho vinte e ___ anos.",
              answer: "oito",
              en: "I'm twenty-eight years old.",
              options: ["oito", "e oito", "e dez", "doze"],
            },
            {
              template: "Há ___ pessoas na sala.",
              answer: "cem",
              en: "There are a hundred people in the room.",
              options: ["cem", "cento", "cento e", "cens"],
            },
            {
              template: "Tenho ___ irmãs. (sister, feminine)",
              answer: "duas",
              en: "I have two sisters.",
              options: ["duas", "dois", "dúas", "doze"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Say the number",
          direction: "en-to-l1",
          prompt: "I have twenty-one books and two sisters.",
          reference: "Tenho vinte e um livros e duas irmãs.",
          hint: "21 with a masculine noun = vinte e um. 2 with a feminine noun = duas. Join with e.",
        },
      ],
    },
    {
      slug: "numbers-time-days",
      title: "Time, days & dates",
      estMinutes: 11,
      pages: [
        {
          type: "vocab",
          heading: "Days of the week",
          intro: "All lowercase. Weekdays are 'feira' days; weekends are not.",
          items: [
            { l1: "segunda-feira", en: "Monday", note: "Often shortened to just 'segunda'" },
            { l1: "terça-feira", en: "Tuesday" },
            { l1: "quarta-feira", en: "Wednesday" },
            { l1: "quinta-feira", en: "Thursday" },
            { l1: "sexta-feira", en: "Friday" },
            { l1: "sábado", en: "Saturday" },
            { l1: "domingo", en: "Sunday" },
          ],
        },
        {
          type: "tip",
          heading: "Telling time — É uma / São duas",
          body: "Use <em>É uma hora</em> for 1:00 (singular). For all other hours use <em>São</em> + number + <em>horas</em>: <em>São duas horas</em>. Add <em>e</em> for minutes past the hour; for minutes to the next hour use <em>para as</em>.",
          example: { l1: "São três e meia. / São quinze para as três.", en: "It's half past three. / It's a quarter to three." },
        },
        {
          type: "vocab",
          heading: "Time expressions",
          items: [
            { l1: "Que horas são?", en: "What time is it?" },
            { l1: "É uma hora", en: "It's one o'clock" },
            { l1: "São duas horas", en: "It's two o'clock" },
            { l1: "São duas e meia", en: "It's half past two" },
            { l1: "São três e quinze", en: "It's a quarter past three", note: "Or: três e um quarto" },
            { l1: "São quinze para as três", en: "It's a quarter to three", note: "PT often: três menos um quarto" },
            { l1: "meio-dia", en: "noon (12:00)" },
            { l1: "meia-noite", en: "midnight (00:00)" },
          ],
        },
        {
          type: "tip",
          heading: "Casual time — 'a gente' & dropping 'horas'",
          body: "In casual Brazilian speech people drop <em>horas</em> entirely: <em>São duas e meia</em> instead of the full <em>São duas horas e trinta minutos</em>. You'll also hear <em>a gente</em> (literally 'the people') used for 'we' when making plans: <em>A gente se vê às oito</em> = 'We'll see each other at eight.'",
          example: { l1: "A gente chega meio-dia e meia.", en: "We'll get there at half past twelve." },
        },
        {
          type: "multipleChoice",
          heading: "Time and days",
          questions: [
            {
              q: "How do you say 'It's 2:00'?",
              options: ["É duas horas", "São duas horas", "É a duas", "São dois horas"],
              correct: 1,
              fb: "São duas horas — use 'são' for all hours except one (é uma hora).",
            },
            {
              q: "What does 'São nove e meia' mean?",
              options: ["It's 9:15", "It's 9:30", "It's 8:30", "It's 9:45"],
              correct: 1,
              fb: "e meia = half past. São nove e meia = 9:30.",
            },
            {
              q: "Which day comes after terça-feira?",
              options: ["segunda-feira", "quinta-feira", "quarta-feira", "sexta-feira"],
              correct: 2,
              fb: "segunda, terça, quarta, quinta, sexta, sábado, domingo.",
            },
          ],
        },
        {
          type: "dialogue",
          heading: "At the bus station",
          setup: "You're catching a bus in São Paulo and need the time.",
          lines: [
            { speaker: "Você", l1: "Com licença, que horas são?", en: "Excuse me, what time is it?" },
            { speaker: "Atendente", l1: "São nove e vinte.", en: "It's nine twenty." },
            { speaker: "Você", l1: "A que horas sai o próximo ônibus?", en: "What time does the next bus leave?" },
            { speaker: "Atendente", l1: "Às quinze para as dez.", en: "At a quarter to ten." },
            { speaker: "Você", l1: "Perfeito, muito obrigado.", en: "Perfect, thank you very much." },
          ],
        },
        {
          type: "orderWords",
          heading: "Put it in order",
          intro: "Drag the words into a natural Portuguese sentence.",
          items: [
            { tokens: ["a", "que", "horas", "sai", "o", "ônibus"], alts: [["a", "que", "horas", "o", "ônibus", "sai"]], en: "What time does the bus leave?" },
            { tokens: ["são", "duas", "e", "meia"], en: "It's half past two." },
            { tokens: ["o", "filme", "é", "às", "oito", "horas"], en: "The film is at eight o'clock." },
          ],
        },
        {
          type: "translate",
          heading: "Tell the time",
          direction: "en-to-l1",
          prompt: "It's half past two on Thursday.",
          reference: "São duas e meia na quinta-feira.",
          hint: "Use 'são' for all hours except one. Half past = e meia. 'on Thursday' = na quinta-feira.",
        },
      ],
    },
    {
      slug: "numbers-time-practical",
      title: "Numbers in everyday life",
      estMinutes: 10,
      pages: [
        {
          type: "vocab",
          heading: "Months and dates",
          intro: "Months are lowercase in Portuguese.",
          items: [
            { l1: "janeiro, fevereiro, março", en: "January, February, March" },
            { l1: "abril, maio, junho", en: "April, May, June" },
            { l1: "julho, agosto, setembro", en: "July, August, September" },
            { l1: "outubro, novembro, dezembro", en: "October, November, December" },
            { l1: "cinco de maio", en: "the fifth of May (day + de + month)" },
            { l1: "quinze de agosto de 2024", en: "15 August 2024" },
          ],
        },
        {
          type: "vocab",
          heading: "Big numbers, prices & phones",
          items: [
            { l1: "cem, duzentos, quinhentos", en: "100, 200, 500", note: "duzentas/quinhentas before feminine nouns" },
            { l1: "mil reais", en: "one thousand reais", note: "Brazil's currency, written R$" },
            { l1: "um milhão", en: "one million" },
            { l1: "um bilhão", en: "one billion (BR)", note: "Portugal says 'mil milhões' for a billion" },
            { l1: "o número de telefone", en: "the phone number" },
            { l1: "custa três reais e cinquenta", en: "it costs R$3.50 (currency)" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Dates and numbers check",
          questions: [
            {
              q: "How do you say 'the 5th of March'?",
              options: ["cinco março", "cinco de março", "o cinco março", "quinto de março"],
              correct: 1,
              fb: "Day + de + month: cinco de março. Plain number, not an ordinal.",
            },
            {
              q: "'Custa três reais e cinquenta' means it costs…",
              options: ["R$3.15", "R$3.50", "R$13.50", "R$35.00"],
              correct: 1,
              fb: "Três reais e cinquenta = R$3.50 (three reais and fifty centavos).",
            },
            {
              q: "In Brazil, 'um bilhão' is a billion. What does Portugal say?",
              options: ["um bilhão", "mil milhões", "um milhão", "cem mil"],
              correct: 1,
              fb: "BR: um bilhão (10⁹). PT: mil milhões. A real BR/PT vocab split.",
            },
          ],
        },
        {
          type: "tip",
          heading: "Writing the date — day before month",
          body: "Brazil writes dates day-month-year. <em>12/05/2026</em> means <strong>12 May 2026</strong>, not December 5. Spoken, you say the day as a plain number plus <em>de</em>: <em>doze de maio de dois mil e vinte e seis</em>. The first of the month is usually said as <em>primeiro</em> (1º): <em>primeiro de maio</em>.",
          example: { l1: "Hoje é dezessete de junho de 2026.", en: "Today is the 17th of June, 2026." },
        },
        {
          type: "fillBlank",
          heading: "Dates and prices",
          intro: "Fill in the blank to complete each phrase.",
          items: [
            {
              template: "Meu aniversário é ___ dois de agosto.",
              answer: "no dia",
              en: "My birthday is on the second of August.",
              options: ["no dia", "em", "às", "de"],
            },
            {
              template: "O ingresso custa doze ___.",
              answer: "reais",
              en: "The ticket costs twelve reais.",
              options: ["reais", "euros", "real", "centavos"],
            },
            {
              template: "São ___ horas em ponto.",
              answer: "duas",
              en: "It's two o'clock sharp.",
              options: ["duas", "dois", "uma", "doze"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Put it in order",
          intro: "Drag the words into a natural Portuguese sentence.",
          items: [
            { tokens: ["o", "show", "é", "no", "dia", "três", "de", "abril"], en: "The concert is on the third of April." },
            { tokens: ["meu", "aniversário", "é", "primeiro", "de", "janeiro"], en: "My birthday is the first of January." },
            { tokens: ["o", "café", "custa", "cinco", "reais"], en: "The coffee costs five reais." },
          ],
        },
        {
          type: "translate",
          heading: "Translate the date & price",
          direction: "en-to-l1",
          prompt: "My birthday is the second of August and the ticket costs ten reais.",
          reference: "Meu aniversário é no dia dois de agosto e o ingresso custa dez reais.",
          hint: "Day + de + month, lowercase. Brazil's currency is reais (R$).",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "How do you say 17?", options: ["dezoito", "dezessete", "dezesseis", "dezenove"], correct: 1 },
      { q: "What is 'cem'?", options: ["10", "100", "1000", "110"], correct: 1 },
      { q: "How do you say 55?", options: ["cinquenta e cinco", "cinquenta cinco", "sessenta e cinco", "quarenta e cinco"], correct: 0 },
      { q: "What day follows sexta-feira?", options: ["quinta-feira", "domingo", "sábado", "segunda-feira"], correct: 2 },
      { q: "'São duas horas' means…", options: ["It's 1 o'clock", "It's 2 o'clock", "It's 20 past", "Two hours ago"], correct: 1 },
      { q: "'É uma hora' uses 'é' because…", options: ["Uma is feminine", "It's singular — one o'clock", "É is more formal", "Grammar exception"], correct: 1 },
      { q: "'e meia' means…", options: ["quarter past", "half past", "to the hour", "and a bit"], correct: 1 },
      { q: "How do you say 'What time is it?'", options: ["Quanto tempo?", "Que horas são?", "A que horas?", "Quando?"], correct: 1 },
      { q: "'Two sisters' (irmã, feminine) is…", options: ["dois irmãs", "duas irmãs", "dois irmã", "duas irmã"], correct: 1 },
      { q: "How do you say 'noon'?", options: ["meia-noite", "meio-dia", "doze horas", "à tarde"], correct: 1 },
      { q: "How do you say 'the second of August'?", options: ["o segundo de agosto", "dois agosto", "dois de agosto", "agosto dois"], correct: 2 },
      { q: "In Brazil, '12/05/2026' means…", options: ["December 5, 2026", "12 May 2026", "Either is fine", "May 20, 2026"], correct: 1 },
      { q: "A billion is 'um bilhão' in Brazil. In Portugal it's…", options: ["um bilhão", "mil milhões", "um milhão", "cem mil"], correct: 1 },
    ],
  },
};
