import type { Unit } from "../../types";

export const UNIT_ARTICLES: Unit = {
  slug: "articles",
  stage: 1,
  order: 4,
  icon: "📚",
  title: "Nouns, gender & articles",
  tagline: "o, a, os, as, um, uma — and contractions (do, da, no, na).",
  badge: "core",
  lessons: [
    {
      slug: "articles-gender",
      title: "Noun gender and definite articles",
      estMinutes: 11,
      pages: [
        {
          type: "intro",
          heading: "Every noun is masculine or feminine",
          body: [
            "In Portuguese, every noun has a gender — masculine or feminine. It's a grammatical property, not about biology. Most nouns ending in <strong>-o</strong> are masculine, most ending in <strong>-a</strong> are feminine. But there are exceptions you'll meet soon.",
            "The definite article ('the') matches the noun's gender and number: <strong>o</strong> (masc. singular), <strong>a</strong> (fem. singular), <strong>os</strong> (masc. plural), <strong>as</strong> (fem. plural).",
          ],
          tip: {
            label: "Learn the article with the noun",
            body: "Always learn a new noun with its article: o livro (not just livro). This locks in the gender automatically.",
          },
        },
        {
          type: "conjugation",
          heading: "The four definite articles",
          verb: "o / a / os / as",
          meaning: "the (all four forms)",
          intro: "Portuguese has just four words for 'the.' Pick the form that matches the noun's gender and number.",
          tenses: [
            {
              name: "Masculine",
              forms: [
                { person: "singular", form: "o livro", en: "the book" },
                { person: "plural", form: "os livros", en: "the books" },
              ],
            },
            {
              name: "Feminine",
              forms: [
                { person: "singular", form: "a mesa", en: "the table" },
                { person: "plural", form: "as mesas", en: "the tables" },
              ],
            },
          ],
        },
        {
          type: "vocab",
          heading: "Masculine and feminine nouns",
          items: [
            { l1: "o livro", en: "the book", note: "masc. — ends in -o" },
            { l1: "o carro", en: "the car", note: "masc." },
            { l1: "o homem", en: "the man", note: "masc." },
            { l1: "a mesa", en: "the table", note: "fem. — ends in -a" },
            { l1: "a casa", en: "the house", note: "fem. — ends in -a" },
            { l1: "a cidade", en: "the city", note: "fem. — nouns in -dade are fem." },
            { l1: "a lição", en: "the lesson", note: "fem. — nouns in -ção are fem." },
            { l1: "o problema", en: "the problem", note: "masc. — exception: ends in -a but is masculine!" },
            { l1: "o dia", en: "the day", note: "masc. — exception: ends in -a but is masculine!" },
            { l1: "o mapa", en: "the map", note: "masc. — exception: ends in -a but is masculine!" },
            { l1: "a foto", en: "the photo", note: "fem. — exception: ends in -o but is feminine (short for fotografia)!" },
          ],
        },
        {
          type: "tip",
          heading: "Endings that signal gender",
          body: "A few endings are reliable: nouns ending in <em>-ção</em>, <em>-são</em>, and <em>-dade</em> are almost always <strong>feminine</strong> (a nação, a televisão, a verdade). Greek-origin words in <em>-ma</em> like <em>problema</em>, <em>programa</em>, and <em>tema</em> are <strong>masculine</strong> despite the -a.",
          example: { l1: "a verdade / o problema", en: "the truth (fem.) / the problem (masc.)" },
        },
        {
          type: "multipleChoice",
          heading: "Quick check",
          questions: [
            {
              q: "Which article goes with 'livro' (book)?",
              options: ["a", "o", "os", "as"],
              correct: 1,
              fb: "O livro — livro ends in -o, masculine, singular.",
            },
            {
              q: "Why is 'o dia' an exception?",
              options: ["Dia ends in -a but is masculine", "Dia is plural", "Dia is a verb", "O is feminine here"],
              correct: 0,
              fb: "Dia ends in -a but is masculine — a famous exception. O dia.",
            },
            {
              q: "What article goes with 'cidades' (cities)?",
              options: ["o", "a", "os", "as"],
              correct: 3,
              fb: "Cidade is feminine, cidades is plural → as cidades.",
            },
            {
              q: "Which article goes with 'lição' (lesson)?",
              options: ["o", "a", "os", "as"],
              correct: 1,
              fb: "Nouns in -ção are feminine → a lição.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Choose the right 'the'",
          intro: "Match the article to the noun's gender and number.",
          items: [
            {
              template: "___ livro está na mesa.",
              answer: "O",
              en: "The book is on the table.",
              options: ["O", "A", "Os", "As"],
            },
            {
              template: "___ casa é grande.",
              answer: "A",
              en: "The house is big.",
              options: ["O", "A", "Os", "As"],
            },
            {
              template: "___ problema é difícil.",
              answer: "O",
              en: "The problem is difficult. (problema is masculine!)",
              options: ["O", "A", "Os", "As"],
            },
            {
              template: "___ cidades são bonitas.",
              answer: "As",
              en: "The cities are pretty.",
              options: ["O", "A", "Os", "As"],
            },
            {
              template: "___ dias passam rápido.",
              answer: "Os",
              en: "The days go by fast. (dia is masculine!)",
              options: ["O", "A", "Os", "As"],
            },
          ],
        },
      ],
    },
    {
      slug: "articles-indefinite-plural",
      title: "Indefinite articles and plurals",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Um/uma and making plurals",
          body: [
            "Indefinite articles ('a/an') also match gender: <strong>um</strong> (masculine), <strong>uma</strong> (feminine). Plural 'some' is <strong>uns/umas</strong>.",
            "Basic plurals: add <strong>-s</strong> after a vowel (livro → livros). Words ending in <strong>-r</strong>, <strong>-z</strong>, <strong>-s</strong> add <strong>-es</strong> (a flor → as flores). The tricky ones end in <strong>-ão</strong>.",
          ],
          keyPoint: "um/uma = a/an · uns/umas = some · vowel +s · -ão → -ões / -ães / -ãos",
        },
        {
          type: "vocab",
          heading: "Indefinite articles and plurals",
          items: [
            { l1: "um livro / uns livros", en: "a book / some books" },
            { l1: "uma mesa / umas mesas", en: "a table / some tables" },
            { l1: "uma flor / umas flores", en: "a flower / some flowers", note: "+es after -r" },
            { l1: "um rapaz / uns rapazes", en: "a boy / some boys", note: "+es after -z" },
            { l1: "uma lição / umas lições", en: "a lesson / some lessons", note: "-ão → -ões (most common)" },
            { l1: "um pão / uns pães", en: "a loaf / some loaves", note: "-ão → -ães (small group)" },
            { l1: "uma mão / umas mãos", en: "a hand / some hands", note: "-ão → -ãos (small group)" },
          ],
        },
        {
          type: "tip",
          heading: "The three plurals of -ão",
          body: "Words ending in <em>-ão</em> pluralize three ways. The big group becomes <strong>-ões</strong> (lição → lições, coração → corações). A smaller group becomes <strong>-ães</strong> (pão → pães, cão → cães). A few keep <strong>-ãos</strong> (mão → mãos, irmão → irmãos). When in doubt, -ões is the safe bet.",
          example: { l1: "duas lições, três pães, as mãos", en: "two lessons, three loaves, the hands" },
        },
        {
          type: "multipleChoice",
          heading: "Articles and plurals",
          questions: [
            {
              q: "What is the plural of 'a flor' (the flower)?",
              options: ["as flors", "as flores", "as flors", "os flores"],
              correct: 1,
              fb: "Flor ends in -r → add -es. As flores.",
            },
            {
              q: "Which sentence is correct?",
              options: ["a problema", "o problema", "uma problema", "as problema"],
              correct: 1,
              fb: "Problema is a Greek-origin -ma noun — masculine despite the -a. O problema.",
            },
            {
              q: "How do you say 'some books'?",
              options: ["um livros", "uns livro", "uns livros", "umas livros"],
              correct: 2,
              fb: "Livro is masculine → uns livros.",
            },
            {
              q: "The plural of 'a lição' is…",
              options: ["as liçãos", "as lições", "as liçães", "as liçãos"],
              correct: 1,
              fb: "Most -ão nouns take -ões → as lições.",
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the sentence",
          intro: "Drag the words into a natural Portuguese order.",
          items: [
            { tokens: ["Quero", "um", "café", "e", "uma", "torrada"], en: "I want a coffee and a piece of toast." },
            { tokens: ["Há", "uns", "livros", "na", "mesa"], en: "There are some books on the table." },
            { tokens: ["As", "cidades", "grandes", "são", "caras"], en: "Big cities are expensive." },
          ],
        },
        {
          type: "translate",
          heading: "Say it in Portuguese",
          direction: "en-to-l1",
          prompt: "a book and a table",
          reference: "um livro e uma mesa",
          hint: "livro is masculine, mesa is feminine.",
        },
        {
          type: "translate",
          heading: "Say it in Portuguese",
          direction: "en-to-l1",
          prompt: "some lessons",
          reference: "umas lições",
          hint: "lição → lições (-ão becomes -ões).",
        },
      ],
    },
    {
      slug: "articles-contractions",
      title: "Contractions: do, da, no, na, ao, à",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "Articles fuse with prepositions",
          body: [
            "Here's a feature that defines Portuguese: when an article follows certain prepositions, the two words <strong>contract into one</strong>. You don't say <em>de o livro</em> — you must say <strong>do livro</strong> ('of the book').",
            "This is not optional like in English. The four big prepositions are <strong>de</strong> (of/from), <strong>em</strong> (in/on), <strong>a</strong> (to), and <strong>por</strong> (by/through). Each fuses with o, a, os, as.",
          ],
          keyPoint: "de+o = do · em+a = na · a+o = ao · por+a = pela",
        },
        {
          type: "conjugation",
          heading: "The contraction table",
          verb: "de / em / a / por + article",
          meaning: "preposition + the (contracted)",
          intro: "Memorize this grid — you'll use it in nearly every sentence. Each cell is the fused form.",
          tenses: [
            {
              name: "de (of / from)",
              forms: [
                { person: "de + o", form: "do", en: "of the (m.sg.)" },
                { person: "de + a", form: "da", en: "of the (f.sg.)" },
                { person: "de + os", form: "dos", en: "of the (m.pl.)" },
                { person: "de + as", form: "das", en: "of the (f.pl.)" },
              ],
            },
            {
              name: "em (in / on)",
              forms: [
                { person: "em + o", form: "no", en: "in the (m.sg.)" },
                { person: "em + a", form: "na", en: "in the (f.sg.)" },
                { person: "em + os", form: "nos", en: "in the (m.pl.)" },
                { person: "em + as", form: "nas", en: "in the (f.pl.)" },
              ],
            },
            {
              name: "a (to)",
              forms: [
                { person: "a + o", form: "ao", en: "to the (m.sg.)" },
                { person: "a + a", form: "à", en: "to the (f.sg.) — note the crase accent" },
                { person: "a + os", form: "aos", en: "to the (m.pl.)" },
                { person: "a + as", form: "às", en: "to the (f.pl.)" },
              ],
            },
            {
              name: "por (by / through)",
              forms: [
                { person: "por + o", form: "pelo", en: "by/through the (m.sg.)" },
                { person: "por + a", form: "pela", en: "by/through the (f.sg.)" },
                { person: "por + os", form: "pelos", en: "by/through the (m.pl.)" },
                { person: "por + as", form: "pelas", en: "by/through the (f.pl.)" },
              ],
            },
          ],
        },
        {
          type: "tip",
          heading: "de + um/uma is optional",
          body: "With the <em>indefinite</em> article, contraction is optional and more common in speech: <em>de + um</em> can become <strong>dum</strong>, <em>de + uma</em> becomes <strong>duma</strong>, and <em>em + um</em> becomes <strong>num</strong>. Writing <em>de um livro</em> in full is always correct too, so don't stress about these.",
          example: { l1: "num restaurante / em um restaurante", en: "in a restaurant (both correct)" },
        },
        {
          type: "vocab",
          heading: "Contractions in everyday phrases",
          items: [
            { l1: "a porta do carro", en: "the car door (lit. the door of the car)", note: "de + o = do" },
            { l1: "a chave da casa", en: "the house key (lit. the key of the house)", note: "de + a = da" },
            { l1: "o livro está na mesa", en: "the book is on the table", note: "em + a = na" },
            { l1: "o gato está no jardim", en: "the cat is in the garden", note: "em + o = no" },
            { l1: "vou ao mercado", en: "I'm going to the market", note: "a + o = ao" },
            { l1: "vou à praia", en: "I'm going to the beach", note: "a + a = à (crase)" },
            { l1: "passo pelo parque", en: "I pass through the park", note: "por + o = pelo" },
            { l1: "obrigado pela ajuda", en: "thanks for the help", note: "por + a = pela" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Contract it",
          intro: "Fuse the preposition with the article to make one word.",
          items: [
            {
              template: "O carro está em frente ___ casa.",
              answer: "da",
              en: "The car is in front of the house. (de + a)",
              options: ["do", "da", "na", "à"],
            },
            {
              template: "Os livros estão ___ estante.",
              answer: "na",
              en: "The books are on the shelf. (em + a — estante is fem.)",
              options: ["no", "na", "da", "ao"],
            },
            {
              template: "Vamos ___ cinema hoje.",
              answer: "ao",
              en: "We're going to the cinema today. (a + o — cinema is masc.)",
              options: ["ao", "à", "no", "do"],
            },
            {
              template: "Vou ___ farmácia comprar remédio.",
              answer: "à",
              en: "I'm going to the pharmacy to buy medicine. (a + a, with crase)",
              options: ["ao", "à", "na", "da"],
            },
            {
              template: "Obrigada ___ convite!",
              answer: "pelo",
              en: "Thanks for the invitation! (por + o — convite is masc.)",
              options: ["pela", "pelo", "do", "no"],
            },
          ],
        },
        {
          type: "tip",
          heading: "BR vs. PT: articles before names",
          body: "European Portuguese (and parts of Brazil) puts the definite article before given names and possessives: <em>a Maria</em>, <em>o João</em>, <em>a minha casa</em>. Standard Brazilian Portuguese usually <strong>drops it</strong>: <em>Maria</em>, <em>João</em>, <em>minha casa</em>. Both are correct — this course teaches the Brazilian default, but you'll hear the article often, especially from Portugal.",
          example: { l1: "BR: Vou à casa de João. · PT: Vou a casa do João.", en: "I'm going to João's house." },
        },
        {
          type: "dialogue",
          heading: "At the café",
          setup: "Notice how contractions appear in nearly every line.",
          lines: [
            { speaker: "Garçom", l1: "Bom dia! O que você vai querer?", en: "Good morning! What would you like?" },
            { speaker: "Ana", l1: "Um café com leite e uma torrada, por favor.", en: "A coffee with milk and a piece of toast, please." },
            { speaker: "Garçom", l1: "A torrada já está na chapa. E para o senhor?", en: "The toast is already on the grill. And for the gentleman?" },
            { speaker: "Pedro", l1: "Para mim, um suco de laranja. A conta fica na mesa?", en: "For me, an orange juice. Does the bill stay on the table?" },
            { speaker: "Garçom", l1: "Sim, deixo a conta ao lado do açúcar.", en: "Yes, I'll leave the bill next to the sugar." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Contraction check",
          questions: [
            {
              q: "How do you say 'I'm going to the beach' (praia, fem.)?",
              options: ["Vou ao praia", "Vou à praia", "Vou na praia", "Vou da praia"],
              correct: 1,
              fb: "a + a praia = à praia. The crase accent marks the fusion.",
            },
            {
              q: "'The car door' (de + o carro) is…",
              options: ["a porta de carro", "a porta no carro", "a porta do carro", "a porta ao carro"],
              correct: 2,
              fb: "de + o = do → a porta do carro.",
            },
            {
              q: "Which is the contraction of 'em + as'?",
              options: ["nas", "das", "às", "pelas"],
              correct: 0,
              fb: "em + as = nas. (in/on the, fem. plural)",
            },
          ],
        },
        {
          type: "translate",
          heading: "Say it in Portuguese",
          direction: "en-to-l1",
          prompt: "The cat is in the garden.",
          reference: "O gato está no jardim.",
          hint: "em + o jardim = no jardim.",
        },
        {
          type: "translate",
          heading: "Say it in Portuguese",
          direction: "en-to-l1",
          prompt: "I'm going to the market and to the beach.",
          reference: "Vou ao mercado e à praia.",
          hint: "a + o mercado = ao; a + a praia = à.",
        },
        {
          type: "translate",
          heading: "Say it in Portuguese",
          direction: "en-to-l1",
          prompt: "Thanks for the help with the house keys.",
          reference: "Obrigado pela ajuda com as chaves da casa.",
          hint: "por + a ajuda = pela; de + a casa = da casa.",
        },
        {
          type: "translate",
          heading: "Read it in English",
          direction: "l1-to-en",
          prompt: "Os livros das crianças estão na mochila.",
          reference: "The children's books are in the backpack.",
          hint: "das = de + as; na = em + a.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "Which article goes with 'mesa' (table)?", options: ["o", "a", "os", "um"], correct: 1 },
      { q: "Which article goes with 'livros' (books, plural)?", options: ["o", "a", "os", "as"], correct: 2 },
      { q: "'O dia' is unusual because…", options: ["dia is feminine", "dia ends in -a but is masculine", "o is feminine", "dia is a verb"], correct: 1 },
      { q: "What is the plural of 'lição'?", options: ["liçãos", "lições", "liçães", "liçós"], correct: 1 },
      { q: "Which article goes with 'problema'?", options: ["a", "o", "os", "as"], correct: 1 },
      { q: "'Uns' is the plural of…", options: ["a", "um", "o", "uma"], correct: 1 },
      { q: "What is de + a (of the, feminine)?", options: ["do", "da", "na", "à"], correct: 1 },
      { q: "What is em + o (in/on the, masculine)?", options: ["no", "na", "ao", "do"], correct: 0 },
      { q: "What is a + a (to the, feminine)?", options: ["ao", "à", "na", "da"], correct: 1 },
      { q: "What is por + o (by/through the, masculine)?", options: ["pela", "pelo", "polo", "pro"], correct: 1 },
      { q: "Nouns ending in -ção are usually…", options: ["masculine", "feminine", "plural", "neuter"], correct: 1 },
      { q: "'I'm going to the beach' (praia, fem.) is…", options: ["Vou ao praia", "Vou à praia", "Vou na praia", "Vou da praia"], correct: 1 },
    ],
  },
};
