import type { Unit } from "../../types";

export const UNIT_SER_ESTAR: Unit = {
  slug: "ser-estar",
  stage: 1,
  order: 5,
  icon: "🧱",
  title: "Ser, estar & present tense",
  tagline: "The two 'to be' verbs + ter; -ar/-er/-ir regular verbs.",
  badge: "core",
  lessons: [
    {
      slug: "ser-estar-difference",
      title: "Ser vs estar — which 'to be'?",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "Portuguese has two verbs for 'to be'",
          body: [
            "This is the most important distinction in Portuguese grammar. <strong>Ser</strong> is for permanent or defining things: identity, origin, profession, time, material. <strong>Estar</strong> is for location, temporary states, and feelings.",
            "The rough guide: if it's a core part of what something IS, use <strong>ser</strong>. If it's a state that can change, use <strong>estar</strong>.",
            "We default to <strong>você</strong> for \"you\" — that's how most of Brazil speaks. It takes the same verb form as ele/ela (the third person), so one form covers \"you\", \"he\", and \"she\".",
          ],
          tip: {
            label: "Permanent vs temporary",
            body: "Ser: identity, origin, profession, time, material, relationships. Estar: location, current state, mood, condition, weather right now.",
          },
        },
        {
          type: "conjugation",
          heading: "Ser — present tense",
          verb: "ser",
          meaning: "to be (identity/origin)",
          intro: "In Brazil, você takes the same form as ele/ela.",
          tenses: [{ name: "Presente", forms: [
            { person: "eu", form: "sou", en: "I am" },
            { person: "você / ele / ela", form: "é", en: "you are / he/she is" },
            { person: "nós", form: "somos", en: "we are" },
            { person: "vocês / eles / elas", form: "são", en: "you all/they are" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "Estar — present tense",
          verb: "estar",
          meaning: "to be (location/state)",
          intro: "Watch the accents: está, estão.",
          tenses: [{ name: "Presente", forms: [
            { person: "eu", form: "estou", en: "I am" },
            { person: "você / ele / ela", form: "está", en: "you are / he/she is" },
            { person: "nós", form: "estamos", en: "we are" },
            { person: "vocês / eles / elas", form: "estão", en: "you all/they are" },
          ] }],
        },
        {
          type: "tip",
          heading: "Portugal uses \"tu\" — and you'll hear it",
          body: "Brazil mostly uses <em>você</em> for informal \"you\" (você é, está). Portugal (and parts of southern Brazil) uses <em>tu</em>, which has its own endings: <strong>tu és, tu estás, tu tens, tu falas</strong>. We teach você, but recognize the tu-forms when you hear European Portuguese or Brazilian music.",
          example: { l1: "BR: Você é brasileiro? · PT: Tu és português?", en: "Are you Brazilian? / Are you Portuguese?" },
        },
        {
          type: "vocab",
          heading: "Ser or estar?",
          items: [
            { l1: "Eu sou brasileiro.", en: "I'm Brazilian. (ser — origin/identity)", note: "ser" },
            { l1: "Eu sou médico.", en: "I'm a doctor. (ser — profession)", note: "ser" },
            { l1: "São três horas.", en: "It's three o'clock. (ser — time)", note: "ser" },
            { l1: "Eu estou em São Paulo.", en: "I'm in São Paulo. (estar — location)", note: "estar" },
            { l1: "Você está cansado.", en: "You're tired. (estar — temporary state)", note: "estar" },
            { l1: "Ele está doente.", en: "He's sick. (estar — condition)", note: "estar" },
            { l1: "O café está frio.", en: "The coffee is cold. (estar — current state)", note: "estar" },
            { l1: "A neve é branca.", en: "Snow is white. (ser — inherent quality)", note: "ser" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Ser or estar?",
          questions: [
            {
              q: "'She is a teacher' uses…",
              options: ["está", "é", "são", "estão"],
              correct: 1,
              fb: "Profession → ser. Ela é professora.",
            },
            {
              q: "'The coffee is cold right now' uses…",
              options: ["é", "está", "são", "estou"],
              correct: 1,
              fb: "Temporary current state → estar. O café está frio.",
            },
            {
              q: "'I'm in Rio' uses…",
              options: ["sou", "é", "estou", "somos"],
              correct: 2,
              fb: "Location → estar. Eu estou no Rio.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Ser or estar? Fill the blank",
          intro: "Choose the right form. Ask: defining trait, or changeable state?",
          items: [
            {
              template: "Eu ___ de Salvador.",
              answer: "sou",
              en: "I'm from Salvador. (origin → ser)",
              options: ["sou", "estou", "é", "está"],
            },
            {
              template: "A sopa ___ quente.",
              answer: "está",
              en: "The soup is hot. (current state → estar)",
              options: ["é", "está", "são", "estão"],
            },
            {
              template: "Minha irmã ___ professora.",
              answer: "é",
              en: "My sister is a teacher. (profession → ser)",
              options: ["está", "é", "estão", "estou"],
            },
            {
              template: "Nós ___ no parque.",
              answer: "estamos",
              en: "We're in the park. (location → estar)",
              options: ["somos", "estamos", "são", "estão"],
            },
            {
              template: "O livro ___ de papel.",
              answer: "é",
              en: "The book is made of paper. (material → ser)",
              options: ["está", "é", "são", "estamos"],
            },
            {
              template: "Como você ___ hoje?",
              answer: "está",
              en: "How are you today? (mood/condition → estar)",
              options: ["é", "está", "sou", "são"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it — ser vs estar",
          direction: "en-to-l1",
          prompt: "I'm Brazilian, but right now I'm in France.",
          reference: "Eu sou brasileiro, mas agora estou na França.",
          hint: "Nationality is identity → ser. Location → estar. \"in France\" = na França.",
        },
      ],
    },
    {
      slug: "ser-estar-regular-verbs",
      title: "Regular -ar, -er, -ir verbs + ter",
      estMinutes: 13,
      pages: [
        {
          type: "intro",
          heading: "Three verb families",
          body: [
            "Portuguese infinitives end in <strong>-ar</strong>, <strong>-er</strong>, or <strong>-ir</strong>. Regular verbs in each family follow predictable patterns: drop the infinitive ending and add the suffix for each person.",
            "Most Portuguese verbs are -ar verbs (falar, trabalhar, morar). Learn this pattern well — most new verbs you meet will follow it.",
          ],
          keyPoint: "Você/ele/ela always take the third-person form. Endings (eu/você/nós/vocês): -ar = -o/-a/-amos/-am · -er = -o/-e/-emos/-em · -ir = -o/-e/-imos/-em",
        },
        {
          type: "conjugation",
          heading: "falar (to speak) — regular -ar",
          verb: "falar",
          meaning: "to speak",
          tenses: [{ name: "Presente", forms: [
            { person: "eu", form: "falo", en: "I speak" },
            { person: "você / ele / ela", form: "fala", en: "you/he/she speak(s)" },
            { person: "nós", form: "falamos", en: "we speak" },
            { person: "vocês / eles / elas", form: "falam", en: "you all/they speak" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "comer (to eat) — regular -er",
          verb: "comer",
          meaning: "to eat",
          tenses: [{ name: "Presente", forms: [
            { person: "eu", form: "como", en: "I eat" },
            { person: "você / ele / ela", form: "come", en: "you/he/she eat(s)" },
            { person: "nós", form: "comemos", en: "we eat" },
            { person: "vocês / eles / elas", form: "comem", en: "you all/they eat" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "abrir (to open) — regular -ir",
          verb: "abrir",
          meaning: "to open",
          intro: "The -ir endings match -er except the nós form: -imos.",
          tenses: [{ name: "Presente", forms: [
            { person: "eu", form: "abro", en: "I open" },
            { person: "você / ele / ela", form: "abre", en: "you/he/she open(s)" },
            { person: "nós", form: "abrimos", en: "we open" },
            { person: "vocês / eles / elas", form: "abrem", en: "you all/they open" },
          ] }],
        },
        {
          type: "vocab",
          heading: "Common verbs in context",
          items: [
            { l1: "Eu falo português.", en: "I speak Portuguese." },
            { l1: "Você fala inglês?", en: "Do you speak English?" },
            { l1: "Nós comemos às duas.", en: "We eat at two." },
            { l1: "A loja abre às nove.", en: "The shop opens at nine. (abrir, -ir)" },
            { l1: "Onde você trabalha?", en: "Where do you work? (trabalhar, -ar)" },
            { l1: "Eu moro no Rio.", en: "I live in Rio. (morar, -ar)" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Conjugation check",
          questions: [
            {
              q: "What is the 'eu' form of 'falar'?",
              options: ["fala", "falo", "falam", "falamos"],
              correct: 1,
              fb: "Regular -ar: eu form drops -ar and adds -o. falo.",
            },
            {
              q: "What is 'they eat'?",
              options: ["comemos", "come", "comem", "como"],
              correct: 2,
              fb: "Eles/elas comem — third person plural -er: -em.",
            },
            {
              q: "What is 'we open' from 'abrir'?",
              options: ["abrimos", "abremos", "abrem", "abro"],
              correct: 0,
              fb: "-ir verbs: nós form is -imos. abrimos.",
            },
          ],
        },
        {
          type: "tip",
          heading: "Ter for age and possession",
          body: "Portuguese uses <em>ter</em> (to have) where English uses <em>be</em> for age. <em>Eu tenho trinta anos</em> = \"I'm thirty (I have thirty years).\" Ter is also the everyday verb for possession: <em>Eu tenho dois irmãos</em> = \"I have two brothers.\" It's irregular — note the accent on <strong>têm</strong> (they have).",
          example: { l1: "Eu tenho trinta anos e tenho um cachorro.", en: "I'm thirty and I have a dog." },
        },
        {
          type: "conjugation",
          heading: "ter (to have) — irregular",
          verb: "ter",
          meaning: "to have (age, possession)",
          intro: "Note the irregular eu form (tenho) and the circumflex on têm (plural).",
          tenses: [{ name: "Presente", forms: [
            { person: "eu", form: "tenho", en: "I have" },
            { person: "você / ele / ela", form: "tem", en: "you/he/she has" },
            { person: "nós", form: "temos", en: "we have" },
            { person: "vocês / eles / elas", form: "têm", en: "you all/they have" },
          ] }],
        },
        {
          type: "orderWords",
          heading: "Build the sentence",
          intro: "Drag the words into a natural Portuguese order.",
          items: [
            { tokens: ["Eu", "tenho", "vinte", "e", "cinco", "anos"], en: "I'm twenty-five years old." },
            { tokens: ["Quantos", "anos", "você", "tem?"], en: "How old are you?" },
            { tokens: ["Meu", "irmão", "tem", "um", "carro"], en: "My brother has a car." },
            { tokens: ["Eu", "moro", "no", "Rio"], en: "I live in Rio." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it — verbs in action",
          direction: "en-to-l1",
          prompt: "I live in Lisbon and I work in a restaurant.",
          reference: "Eu moro em Lisboa e trabalho num restaurante.",
          hint: "morar → moro (-ar). trabalhar → trabalho (-ar). \"in a\" = num.",
        },
      ],
    },
    {
      slug: "ser-estar-continuous",
      title: "Present continuous & tricky cases",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Saying what's happening right now",
          body: [
            "To say something is happening at this moment, you use <strong>estar</strong> plus another verb. This is where Brazil and Portugal split most visibly.",
            "Brazil uses <strong>estar + gerund</strong> (the -ndo form): <em>estou comendo</em> (I'm eating), <em>estou falando</em> (I'm talking). Make the gerund by swapping the infinitive ending: -ar → -ando, -er → -endo, -ir → -indo.",
          ],
          keyPoint: "BR: estou + (-ando/-endo/-indo). Estou falando, estou comendo, estou abrindo.",
        },
        {
          type: "tip",
          heading: "The biggest BR/PT difference: present continuous",
          body: "Brazil says <em>estar + gerund</em>: <strong>estou fazendo</strong>, <strong>estou comendo</strong>. Portugal says <em>estar a + infinitive</em>: <strong>estou a fazer</strong>, <strong>estou a comer</strong>. Both mean exactly the same \"I'm doing / I'm eating\" — this is one of the most recognizable splits between the two dialects. We teach the Brazilian gerund form.",
          example: { l1: "BR: Estou comendo agora. · PT: Estou a comer agora.", en: "I'm eating now." },
        },
        {
          type: "vocab",
          heading: "Present continuous (Brazilian)",
          items: [
            { l1: "Estou falando com você.", en: "I'm talking to you. (falar → falando)" },
            { l1: "Ela está comendo pizza.", en: "She's eating pizza. (comer → comendo)" },
            { l1: "Nós estamos trabalhando.", en: "We're working. (trabalhar → trabalhando)" },
            { l1: "Eles estão abrindo a loja.", en: "They're opening the shop. (abrir → abrindo)" },
            { l1: "O que você está fazendo?", en: "What are you doing? (fazer → fazendo)" },
          ],
        },
        {
          type: "intro",
          heading: "Ser vs estar — tricky cases",
          body: [
            "Some adjectives go with either verb but change meaning. <em>Ele é chato</em> = he's a boring/annoying person (character). <em>Ele está chateado</em> = he's upset right now (state).",
            "Location of a place uses <em>ser</em> or <em>ficar</em> when it's a fixed address: <em>O banco fica na esquina</em> = the bank is on the corner. But for where someone is at the moment, use <em>estar</em>: <em>Eu estou no banco</em>.",
          ],
          keyPoint: "Character/identity → ser. Current state/feeling → estar. Permanent location of a building → ser/ficar.",
        },
        {
          type: "multipleChoice",
          heading: "Continuous & tricky cases",
          questions: [
            {
              q: "Brazilian for 'I'm eating now' is…",
              options: ["Estou a comer agora", "Estou comendo agora", "Sou comendo agora", "Como agora"],
              correct: 1,
              fb: "Brazil uses estar + gerund: estou comendo. (Portugal: estou a comer.)",
            },
            {
              q: "The gerund of 'trabalhar' is…",
              options: ["trabalhindo", "trabalhendo", "trabalhando", "trabalhar"],
              correct: 2,
              fb: "-ar verbs form the gerund with -ando: trabalhando.",
            },
            {
              q: "'He's upset right now' uses…",
              options: ["é", "está", "são", "tem"],
              correct: 1,
              fb: "A temporary feeling → estar. Ele está chateado.",
            },
          ],
        },
        {
          type: "dialogue",
          heading: "Putting it together",
          setup: "Two travelers meet at a hostel in Rio.",
          lines: [
            { speaker: "Lúcia", l1: "Oi, como você se chama?", en: "Hi, what's your name?" },
            { speaker: "You", l1: "Eu me chamo Tom. Sou americano. E você?", en: "I'm Tom. I'm American. And you?" },
            { speaker: "Lúcia", l1: "Sou a Lúcia, sou de Salvador. Quantos anos você tem?", en: "I'm Lúcia, I'm from Salvador. How old are you?" },
            { speaker: "You", l1: "Tenho vinte e oito anos. Estou um pouco cansado da viagem.", en: "I'm twenty-eight. I'm a bit tired from the trip." },
            { speaker: "Lúcia", l1: "Você fala muito bem português! O que você está fazendo agora?", en: "You speak Portuguese really well! What are you doing now?" },
            { speaker: "You", l1: "Estou descansando no hostel. É barato e fica perto do centro.", en: "I'm resting at the hostel. It's cheap and it's near the center." },
          ],
        },
        {
          type: "translate",
          heading: "Final translation challenge",
          direction: "en-to-l1",
          prompt: "I'm twenty-eight years old, I'm from New York, and right now I'm eating.",
          reference: "Eu tenho vinte e oito anos, sou de Nova York e agora estou comendo.",
          hint: "Age → ter. Origin → ser. \"right now I'm eating\" → estar + gerund (Brazilian).",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "'I'm from Brazil' uses…", options: ["estou", "sou", "é", "tenho"], correct: 1 },
      { q: "'He's tired' uses…", options: ["é", "são", "está", "estou"], correct: 2 },
      { q: "'It's three o'clock' uses…", options: ["estão", "estou", "são", "somos"], correct: 2 },
      { q: "The eu form of 'comer' is…", options: ["come", "comes", "como", "comemos"], correct: 2 },
      { q: "The nós form of 'falar' is…", options: ["falam", "fala", "falamos", "falo"], correct: 2 },
      { q: "'I'm 25 years old' uses…", options: ["Sou vinte e cinco", "Estou vinte e cinco anos", "Tenho vinte e cinco anos", "É vinte e cinco anos"], correct: 2 },
      { q: "Profession/identity uses which verb?", options: ["estar", "ser", "ter", "ficar"], correct: 1 },
      { q: "What is 'you (você) speak'?", options: ["falo", "fala", "falam", "falamos"], correct: 1 },
      { q: "The eles form of 'abrir' is…", options: ["abrimos", "abre", "abrem", "abro"], correct: 2 },
      { q: "Brazilian for 'I'm eating' is…", options: ["Estou a comer", "Estou comendo", "Sou comendo", "Como"], correct: 1 },
      { q: "Portugal's present continuous uses…", options: ["estar + gerund (-ndo)", "estar a + infinitive", "ser + gerund", "ter + infinitive"], correct: 1 },
      { q: "The eu form of 'ter' is…", options: ["teno", "tens", "tenho", "tem"], correct: 2 },
    ],
  },
};
