import type { Unit } from "../../types";

export const UNIT_ABOUT_ME: Unit = {
  slug: "about-me",
  stage: 2,
  order: 6,
  icon: "🪪",
  title: "About me",
  tagline: "Nationalities, professions, family, possessives.",
  badge: "core",
  lessons: [
    {
      slug: "about-me-origin",
      title: "Where you're from & nationality",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Three building blocks: ser, vir de, morar em",
          body: [
            "To say your nationality, use <strong>sou + nationality</strong>: <em>Sou brasileiro / brasileira</em>. The ending agrees with you — <strong>-o</strong> for a man, <strong>-a</strong> for a woman.",
            "To say where you come FROM, use <strong>sou de + place</strong>: <em>Sou de São Paulo</em>. With countries that take an article, <em>de</em> contracts: <em>do Brasil</em> (de + o), <em>dos Estados Unidos</em> (de + os).",
            "To say where you live NOW, use <strong>moro em + place</strong>: <em>Moro em Lisboa</em>. With an article it contracts too: <em>moro no Rio</em> (em + o), <em>moro na Bahia</em> (em + a).",
          ],
          keyPoint: "Sou [nationality+o/a]. Sou de [city] / do [country]. Moro em [city] / no/na [place].",
        },
        {
          type: "vocab",
          heading: "Nationalities (m / f)",
          intro: "In Portuguese, nationalities are NOT capitalized — only the country name is.",
          items: [
            { l1: "brasileiro / brasileira", en: "Brazilian" },
            { l1: "americano / americana", en: "American" },
            { l1: "português / portuguesa", en: "Portuguese", note: "Drops the accent in the feminine: portuguesa" },
            { l1: "inglês / inglesa", en: "English" },
            { l1: "francês / francesa", en: "French" },
            { l1: "alemão / alemã", en: "German", note: "Irregular feminine: alemã" },
            { l1: "espanhol / espanhola", en: "Spanish" },
            { l1: "italiano / italiana", en: "Italian" },
            { l1: "canadense", en: "Canadian (same m/f in BR)", note: "Portugal says canadiano / canadiana" },
            { l1: "mexicano / mexicana", en: "Mexican" },
            { l1: "japonês / japonesa", en: "Japanese" },
          ],
        },
        {
          type: "tip",
          heading: "Countries are capitalized; nationalities are not",
          body: "Country names take a capital: <em>Brasil, Portugal, Estados Unidos, Inglaterra, França, Alemanha, Espanha, Itália, México, Japão</em>. The adjective forms (the nationalities above) stay lowercase. Many countries also carry an article, which contracts with <em>de</em> and <em>em</em>: <em>o Brasil → do Brasil → no Brasil</em>.",
          example: { l1: "Sou dos Estados Unidos, mas moro no Brasil.", en: "I'm from the United States, but I live in Brazil." },
        },
        {
          type: "tip",
          heading: "BR vs PT: morar vs viver, and 'estado' words",
          body: "Both Brazil and Portugal use <em>morar em</em> for 'to live in a place'. <em>Viver</em> exists in both but leans more toward 'to be alive / to live (a life)'. One spelling note: Brazil writes <em>você</em> and uses it as the default 'you', while in Portugal the everyday informal 'you' is <em>tu</em> — so a Portuguese speaker might ask <em>De onde és?</em> where a Brazilian asks <em>De onde você é?</em>",
          example: { l1: "BR: De onde você é? · PT: De onde és?", en: "Where are you from?" },
        },
        {
          type: "fillBlank",
          heading: "Sou / sou de / moro em",
          items: [
            {
              template: "___ São Paulo, mas agora moro em Lisboa.",
              answer: "Sou de",
              en: "I'm from São Paulo, but now I live in Lisbon.",
              options: ["Sou de", "Moro em", "Sou em", "Venho a"],
            },
            {
              template: "Ela ___ portuguesa.",
              answer: "é",
              en: "She is Portuguese.",
              options: ["sou", "é", "somos", "são"],
            },
            {
              template: "Eu ___ no Rio de Janeiro.",
              answer: "moro",
              en: "I live in Rio de Janeiro.",
              options: ["sou", "moro", "tenho", "venho"],
            },
            {
              template: "Nós somos ___ Estados Unidos.",
              answer: "dos",
              en: "We are from the United States.",
              options: ["de", "do", "dos", "da"],
            },
            {
              template: "Os meus amigos ___ canadenses.",
              answer: "são",
              en: "My friends are Canadian.",
              options: ["sou", "é", "são", "somos"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'm Brazilian, I'm from Salvador, but I live in Lisbon for work.",
          reference: "Sou brasileiro, sou de Salvador, mas moro em Lisboa a trabalho.",
          hint: "Two clauses joined by 'mas'. 'For work' = a trabalho. Use morar em for where you live.",
        },
      ],
    },
    {
      slug: "about-me-work-family",
      title: "Work, age & family",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Profession: drop the 'a/an'; age uses ter",
          body: [
            "English says \"I'm <em>a</em> teacher.\" Portuguese drops the article: <em>Sou professor</em> — literally \"I am teacher.\" You can also say <em>Trabalho como professor</em> ('I work as a teacher').",
            "Professions usually have masculine and feminine forms: <em>professor / professora</em>, <em>médico / médica</em>, <em>advogado / advogada</em>.",
            "Age is NOT 'to be' — it uses <strong>ter</strong> (to have): <em>Tenho trinta anos</em> = literally \"I have thirty years.\" Never say <em>sou trinta</em>.",
          ],
          keyPoint: "Sou [profissão] — no article. Trabalho como [profissão]. Age: Tenho X anos (with ter).",
        },
        {
          type: "vocab",
          heading: "Common professions",
          items: [
            { l1: "professor / professora", en: "teacher" },
            { l1: "estudante", en: "student (same m/f)" },
            { l1: "médico / médica", en: "doctor" },
            { l1: "advogado / advogada", en: "lawyer" },
            { l1: "engenheiro / engenheira", en: "engineer" },
            { l1: "enfermeiro / enfermeira", en: "nurse" },
            { l1: "cozinheiro / cozinheira", en: "cook / chef" },
            { l1: "garçom / garçonete", en: "waiter / waitress", note: "Portugal says empregado / empregada de mesa" },
            { l1: "vendedor / vendedora", en: "salesperson" },
            { l1: "motorista", en: "driver (same m/f)" },
            { l1: "aposentado / aposentada", en: "retired person", note: "Portugal says reformado / reformada" },
            { l1: "autônomo / autônoma", en: "self-employed", note: "Portugal spells it autónomo" },
          ],
        },
        {
          type: "vocab",
          heading: "Family",
          items: [
            { l1: "a família", en: "the family" },
            { l1: "o pai / a mãe", en: "father / mother" },
            { l1: "os pais", en: "the parents", note: "Same word as 'fathers' — context decides" },
            { l1: "o filho / a filha", en: "son / daughter" },
            { l1: "o irmão / a irmã", en: "brother / sister" },
            { l1: "o marido / a esposa", en: "husband / wife", note: "Wife is also a mulher" },
            { l1: "o avô / a avó", en: "grandfather / grandmother", note: "avô = oh sound; avó = aw sound" },
            { l1: "o tio / a tia", en: "uncle / aunt" },
            { l1: "o primo / a prima", en: "cousin" },
            { l1: "o namorado / a namorada", en: "boyfriend / girlfriend" },
            { l1: "os filhos", en: "the children (or sons)" },
            { l1: "os irmãos", en: "the siblings (or brothers)" },
          ],
        },
        {
          type: "dialogue",
          heading: "First small talk",
          setup: "Bruno asks Carla about herself.",
          lines: [
            { speaker: "Bruno", l1: "Carla, de onde você é?", en: "Carla, where are you from?" },
            { speaker: "Carla", l1: "Sou de Recife, mas moro em São Paulo há cinco anos.", en: "I'm from Recife, but I've lived in São Paulo for five years." },
            { speaker: "Bruno", l1: "O que você faz?", en: "What do you do?" },
            { speaker: "Carla", l1: "Sou advogada. E você?", en: "I'm a lawyer. And you?" },
            { speaker: "Bruno", l1: "Trabalho como engenheiro. Quantos anos você tem?", en: "I work as an engineer. How old are you?" },
            { speaker: "Carla", l1: "Tenho trinta e dois anos. Você tem irmãos?", en: "I'm thirty-two. Do you have siblings?" },
            { speaker: "Bruno", l1: "Tenho uma irmã mais velha e um irmão mais novo.", en: "I have an older sister and a younger brother." },
            { speaker: "Carla", l1: "Que legal! A minha família é pequena.", en: "How nice! My family is small." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Spot the mistake",
          questions: [
            {
              q: "Which is correct?",
              options: ["Sou um advogado.", "Sou advogado.", "Eu sou o advogado.", "Tenho advogado."],
              correct: 1,
              fb: "No article after 'sou' for professions — just 'Sou advogado.'",
            },
            {
              q: "How do you say 'I'm thirty years old'?",
              options: ["Sou trinta anos.", "Tenho trinta anos.", "Estou trinta anos.", "Faço trinta anos."],
              correct: 1,
              fb: "Age uses ter (to have): Tenho trinta anos — literally 'I have thirty years.'",
            },
            {
              q: "'My parents are teachers' is…",
              options: [
                "Os meus pais são professores.",
                "Os meus pais são os professores.",
                "O meu pai é professores.",
                "Os meus pais têm professores.",
              ],
              correct: 0,
              fb: "Drop the article after 'são' + profession; use the plural form professores.",
            },
            {
              q: "How do you ask 'What do you do?' (for a living) in Brazil?",
              options: ["O que você faz?", "Quem você é?", "Onde você mora?", "Como você está?"],
              correct: 0,
              fb: "O que você faz? = What do you do? The verb is fazer (to do/make).",
            },
          ],
        },
      ],
    },
    {
      slug: "about-me-possessives",
      title: "Possessives — meu, seu, nosso",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Possessives agree with the THING owned",
          body: [
            "Portuguese possessives change with the gender and number of the thing owned, NOT the owner: <strong>meu / minha / meus / minhas</strong> (my). <em>Meu carro</em> (m.sg), <em>minha casa</em> (f.sg), <em>meus livros</em> (m.pl), <em>minhas ideias</em> (f.pl).",
            "Same pattern for <em>seu / sua / seus / suas</em> (your, his, her) and <em>nosso / nossa / nossos / nossas</em> (our). <em>Seu</em> covers 'your' (você), 'his', and 'her' — context tells you which.",
            "The owner's own gender is irrelevant. A man's house is still <em>a sua casa</em> (because casa is feminine), and a woman's car is still <em>o seu carro</em> (because carro is masculine).",
          ],
          keyPoint: "Possessive agrees with the noun: meu carro, minha casa, meus livros, minhas ideias.",
        },
        {
          type: "conjugation",
          heading: "Possessives in all 4 forms",
          verb: "meu / seu / nosso",
          meaning: "my / your-his-her / our",
          intro: "Each has four forms — masculine/feminine × singular/plural. They agree with the thing owned.",
          tenses: [
            {
              name: "Possessive table",
              forms: [
                { person: "my", form: "meu / minha / meus / minhas", en: "meu carro, minha casa, meus livros, minhas ideias" },
                { person: "your / his / her", form: "seu / sua / seus / suas", en: "seu carro, sua casa — context = você, ele, or ela" },
                { person: "our", form: "nosso / nossa / nossos / nossas", en: "nosso carro, nossa casa, nossos amigos" },
                { person: "your (you all)", form: "seu(s) / sua(s) de vocês", en: "BR often says 'de vocês' to mean 'your (plural)'" },
                { person: "their (Brazilian)", form: "dele / dela / deles / delas", en: "o carro dele = his car; a casa dela = her house" },
              ],
            },
          ],
        },
        {
          type: "tip",
          heading: "BR drops the article before possessives; PT keeps it",
          body: "This is one of the clearest Brazil-vs-Portugal splits. In <strong>Brazil</strong>, you usually drop the article: <em>minha mãe</em>, <em>meu carro</em>, <em>nossa casa</em>. In <strong>Portugal</strong>, the article is normally kept: <em>a minha mãe</em>, <em>o meu carro</em>, <em>a nossa casa</em>. Both are correct — just match the region. Brazilians do still use the article sometimes for emphasis, but the bare form is the everyday norm.",
          example: { l1: "BR: minha mãe · PT: a minha mãe", en: "my mother" },
        },
        {
          type: "tip",
          heading: "Avoid ambiguity: dele / dela for 'his' vs 'her'",
          body: "Because <em>seu/sua</em> can mean your, his, OR her, Brazilians very often swap to <em>dele</em> (his) and <em>dela</em> (her) after the noun to be crystal clear. <em>O carro dele</em> = his car; <em>o carro dela</em> = her car. These never change for the owner's count: <em>deles</em> (their, m/mixed), <em>delas</em> (their, f).",
          example: { l1: "A casa dela é grande, mas o apartamento dele é pequeno.", en: "Her house is big, but his apartment is small." },
        },
        {
          type: "fillBlank",
          heading: "Fill in the possessive",
          intro: "Match the possessive to the noun's gender and number (Brazilian style — no article).",
          items: [
            {
              template: "___ pai é brasileiro.",
              answer: "Meu",
              en: "My father is Brazilian.",
              options: ["Meu", "Minha", "Meus", "Minhas"],
            },
            {
              template: "___ irmãs moram em Recife.",
              answer: "Minhas",
              en: "My sisters live in Recife.",
              options: ["Meu", "Minha", "Minhas", "Meus"],
            },
            {
              template: "Onde está ___ carro?",
              answer: "seu",
              en: "Where's your car?",
              options: ["sua", "seu", "seus", "suas"],
            },
            {
              template: "A Ana perdeu ___ chaves.",
              answer: "as suas",
              en: "Ana lost her keys.",
              options: ["os seus", "as suas", "sua", "seu"],
            },
            {
              template: "Esta é ___ casa, onde moramos.",
              answer: "nossa",
              en: "This is our house, where we live.",
              options: ["nosso", "nossa", "nossos", "nossas"],
            },
            {
              template: "O livro ___ é interessante. (de ele)",
              answer: "dele",
              en: "His book is interesting.",
              options: ["dela", "dele", "deles", "delas"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the sentences",
          intro: "Tap the words into the correct order (Brazilian, no article before the possessive).",
          items: [
            { tokens: ["Meu", "irmão", "é", "médico"], en: "My brother is a doctor." },
            { tokens: ["Minhas", "irmãs", "moram", "em", "Florianópolis"], en: "My sisters live in Florianópolis." },
            { tokens: ["Nossos", "amigos", "são", "brasileiros"], en: "Our friends are Brazilian." },
            { tokens: ["A", "esposa", "dele", "é", "francesa", "?"], en: "Is his wife French?" },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "My sister is a teacher and her husband is a chef.",
          reference: "Minha irmã é professora e o marido dela é cozinheiro.",
          hint: "Brazilian style: drop the article (minha irmã). Use 'dela' to make 'her' clear. No 'a/an' before professions.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "Translate: 'I'm Brazilian, from Salvador.'",
        options: [
          "Sou brasileiro, sou da Salvador.",
          "Sou brasileiro, sou de Salvador.",
          "Sou de brasileiro, sou Salvador.",
          "Tenho brasileiro, de Salvador.",
        ],
        correct: 1,
      },
      {
        q: "Which is correct?",
        options: ["Sou um médico.", "Sou médico.", "Tenho médico.", "Meu médico."],
        correct: 1,
      },
      {
        q: "'I'm twenty-five years old' =",
        options: [
          "Sou vinte e cinco anos.",
          "Estou vinte e cinco anos.",
          "Tenho vinte e cinco anos.",
          "Faço vinte e cinco anos.",
        ],
        correct: 2,
      },
      {
        q: "'My father' (Brazilian style) =",
        options: ["o meu pai", "meu pai", "minha pai", "meus pai"],
        correct: 1,
      },
      {
        q: "'My sisters' =",
        options: ["meu irmãs", "minhas irmãs", "minha irmãs", "meus irmãs"],
        correct: 1,
      },
      {
        q: "Her car (car = carro, masculine):",
        options: ["a carro dela", "o carro dele", "o carro dela", "a sua carro"],
        correct: 2,
      },
      {
        q: "In Portugal (not Brazil), 'my mother' is usually said as…",
        options: ["minha mãe", "a minha mãe", "mãe minha", "minha a mãe"],
        correct: 1,
      },
      {
        q: "Country names vs nationalities in Portuguese:",
        options: [
          "both are capitalized",
          "both are lowercase",
          "countries are capitalized; nationalities (adjectives) are lowercase",
          "there is no rule",
        ],
        correct: 2,
      },
      {
        q: "'I live in Brazil' =",
        options: ["Moro em Brasil.", "Moro no Brasil.", "Sou no Brasil.", "Tenho no Brasil."],
        correct: 1,
      },
      {
        q: "Translate: 'What do you do?' (Brazilian)",
        options: [
          "Quem você é?",
          "O que você faz?",
          "Onde você mora?",
          "Quantos anos você tem?",
        ],
        correct: 1,
      },
    ],
  },
};
