import type { Unit } from "../../types";

export const UNIT_LANDMARKS: Unit = {
  slug: "landmarks",
  stage: 3,
  order: 14,
  icon: "🏛️",
  title: "Landmarks & sightseeing",
  tagline: "Cristo Redentor, Pão de Açúcar, Belém, Torre de Belém.",
  badge: "culture",
  lessons: [
    {
      slug: "landmarks-monuments",
      title: "The big sights and their names",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Portuguese names, not English ones",
          body: [
            "Cariocas don't say 'Christ the Redeemer' — they say <strong>o Cristo Redentor</strong>. And the famous mountain isn't 'Sugarloaf', it's <strong>o Pão de Açúcar</strong> (literally 'bread of sugar'). Learn the Portuguese names and you'll sound far less like a lost tourist.",
            "The icons of Brazil: <em>o Cristo Redentor</em>, <em>o Pão de Açúcar</em>, <em>as Cataratas do Iguaçu</em>, <em>o Pelourinho</em> (Salvador), <em>a Amazônia</em>, <em>o Teatro Amazonas</em> (Manaus), <em>a praia de Copacabana</em>, <em>a praia de Ipanema</em>.",
            "Portugal has its own treasures: <em>a Torre de Belém</em>, <em>o Mosteiro dos Jerónimos</em>, <em>o Castelo de São Jorge</em> — most of them in or near Lisbon, in a district also called <em>Belém</em>.",
          ],
          keyPoint:
            "Portuguese names are gendered: o Cristo (m), a Torre (f), o Mosteiro (m), as Cataratas (f. plural).",
        },
        {
          type: "vocab",
          heading: "Top Brazilian sights (in Portuguese)",
          items: [
            { l1: "o Cristo Redentor", en: "Christ the Redeemer (Rio)" },
            { l1: "o Pão de Açúcar", en: "Sugarloaf Mountain (Rio)" },
            { l1: "o Corcovado", en: "Corcovado (the mountain Cristo sits on)" },
            { l1: "as Cataratas do Iguaçu", en: "the Iguaçu Falls" },
            { l1: "o Pelourinho", en: "the Pelourinho (historic Salvador)" },
            { l1: "a Amazônia / a floresta amazônica", en: "the Amazon / the Amazon rainforest" },
            { l1: "o Teatro Amazonas", en: "the Amazon Theatre (Manaus)" },
            { l1: "a praia de Copacabana", en: "Copacabana beach" },
            { l1: "a praia de Ipanema", en: "Ipanema beach" },
            { l1: "o Maracanã", en: "the Maracanã (stadium)" },
            { l1: "Ouro Preto", en: "Ouro Preto (colonial town, Minas Gerais)" },
            { l1: "o Lençóis Maranhenses", en: "Lençóis Maranhenses (dunes & lagoons)" },
          ],
        },
        {
          type: "vocab",
          heading: "A few Portuguese (Portugal) sights",
          items: [
            { l1: "a Torre de Belém", en: "the Belém Tower (Lisbon)" },
            { l1: "o Mosteiro dos Jerónimos", en: "the Jerónimos Monastery (Lisbon)" },
            { l1: "o Castelo de São Jorge", en: "St. George's Castle (Lisbon)" },
            { l1: "o Padrão dos Descobrimentos", en: "the Monument to the Discoveries" },
            { l1: "o Palácio da Pena", en: "the Pena Palace (Sintra)" },
            { l1: "a Ribeira", en: "the Ribeira (riverside, Porto)" },
          ],
        },
        {
          type: "tip",
          heading: "Pronunciation: the nasal sounds in Pão de Açúcar",
          body: "<em>Pão</em> ends in the famous Portuguese nasal -ão (say 'powng' through the nose). <em>Açúcar</em>: the ç is a soft /s/ (ah-SOO-car), never /k/. <em>Cristo</em> in Brazil softens the final vowel — KREES-too. And <em>Iguaçu</em> = ee-gwah-SOO, again with that soft ç. The accent marks aren't decoration: <em>Açúcar</em> and <em>Amazônia</em> need them.",
        },
        {
          type: "tip",
          heading: "BR vs PT: the spelling of Belém",
          body: "<em>Belém</em> is both a district of Lisbon (home to the Torre de Belém) <em>and</em> a city in northern Brazil at the mouth of the Amazon. Same spelling, same nasal -ém ending (beh-LENG). Note also that Portugal writes <em>Jerónimos</em> with an ó, while Brazil would tend to write <em>Jerônimos</em> with a ô — the same word, different accent because the two countries nasalise that vowel differently.",
          example: { l1: "BR: Jerônimos · PT: Jerónimos", en: "the Jerónimos Monastery" },
        },
        {
          type: "multipleChoice",
          heading: "Match the name",
          questions: [
            {
              q: "'Christ the Redeemer' in Portuguese =",
              options: [
                "o Cristo Salvador",
                "o Cristo Redentor",
                "o Senhor do Bonfim",
                "o Cristo Rei",
              ],
              correct: 1,
            },
            {
              q: "'Sugarloaf Mountain' =",
              options: [
                "a Montanha de Açúcar",
                "o Pico do Açúcar",
                "o Pão de Açúcar",
                "o Morro Doce",
              ],
              correct: 2,
            },
            {
              q: "The great waterfalls on the Brazil–Argentina border are…",
              options: [
                "as Cataratas do Iguaçu",
                "as Quedas do Amazonas",
                "as Cachoeiras de Salvador",
                "as Águas de Foz",
              ],
              correct: 0,
            },
            {
              q: "The historic colonial centre of Salvador is called…",
              options: ["o Pelourinho", "a Ribeira", "o Corcovado", "o Maracanã"],
              correct: 0,
            },
            {
              q: "The Torre de Belém and Mosteiro dos Jerónimos are in…",
              options: ["Rio de Janeiro", "Salvador", "Lisboa (Portugal)", "Manaus"],
              correct: 2,
              fb: "Both are in the Belém district of Lisbon — UNESCO World Heritage sites.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Christ the Redeemer and Sugarloaf are in Rio.",
          reference: "O Cristo Redentor e o Pão de Açúcar ficam no Rio.",
          hint: "Use 'ficam' (ficar) for 'are located'. 'In Rio' = no Rio (em + o).",
        },
      ],
    },
    {
      slug: "landmarks-history-talk",
      title: "Talking about history & nature",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "A few words go a long way",
          body: [
            "You don't need to be a historian. A handful of words let you read plaques, follow guides, and chat about what you're seeing — whether it's a baroque church in Ouro Preto or a waterfall in Iguaçu.",
            "<strong>Antigo</strong> = old / ancient. <strong>Colonial</strong> = colonial (the Portuguese era). <strong>Barroco</strong> = Baroque (huge in Brazilian church art). <strong>Moderno</strong> = modern (think Brasília and Niemeyer).",
            "Brazil's story mixes <em>indígena</em> (indigenous), <em>colonial</em> (Portuguese), and <em>moderno</em>. Centuries use ordinals: <em>o século XVI</em> = the 16th century, when the Portuguese arrived.",
          ],
          keyPoint:
            "antigo (old), colonial, barroco (Baroque), moderno. Centuries: o século XVI = the 1500s.",
        },
        {
          type: "vocab",
          heading: "Sights, history & art",
          items: [
            { l1: "o monumento", en: "the monument" },
            { l1: "o museu", en: "the museum" },
            { l1: "a igreja", en: "the church" },
            { l1: "o mosteiro", en: "the monastery" },
            { l1: "a catedral", en: "the cathedral" },
            { l1: "o castelo", en: "the castle" },
            { l1: "a estátua", en: "the statue" },
            { l1: "a torre", en: "the tower" },
            { l1: "o teatro", en: "the theatre" },
            { l1: "o centro histórico", en: "the historic centre" },
            { l1: "o patrimônio (da humanidade)", en: "(world) heritage" },
            { l1: "o século", en: "the century" },
            { l1: "a época", en: "the era / period" },
          ],
        },
        {
          type: "vocab",
          heading: "Nature & the view",
          items: [
            { l1: "a vista", en: "the view" },
            { l1: "o mirante", en: "the lookout / viewpoint" },
            { l1: "a praia", en: "the beach" },
            { l1: "o morro", en: "the hill (esp. in Rio)" },
            { l1: "a montanha", en: "the mountain" },
            { l1: "a cachoeira / a catarata", en: "the waterfall" },
            { l1: "a floresta", en: "the forest" },
            { l1: "o rio", en: "the river" },
            { l1: "o teleférico / o bondinho", en: "the cable car (BR: bondinho)" },
            { l1: "o pôr do sol", en: "the sunset" },
            { l1: "vale a pena", en: "it's worth it" },
            { l1: "deslumbrante", en: "breathtaking / stunning" },
          ],
        },
        {
          type: "dialogue",
          heading: "On a guided tour of Ouro Preto",
          setup: "A guide explains a baroque church to your group.",
          lines: [
            { speaker: "Guia", l1: "Bom dia a todos. Estamos diante de uma das igrejas barrocas mais bonitas de Minas Gerais.", en: "Good morning everyone. We're in front of one of the most beautiful baroque churches in Minas Gerais." },
            { speaker: "Guia", l1: "Ouro Preto é do século XVIII, da época do ouro. Hoje é patrimônio da humanidade pela UNESCO.", en: "Ouro Preto is from the 18th century, the gold era. Today it's a UNESCO World Heritage site." },
            { speaker: "Você", l1: "Com licença, uma pergunta: quem fez as esculturas?", en: "Excuse me, a question: who made the sculptures?" },
            { speaker: "Guia", l1: "O Aleijadinho, o maior escultor do barroco brasileiro. Olhem os detalhes da fachada.", en: "Aleijadinho, the greatest sculptor of the Brazilian Baroque. Look at the details on the façade." },
            { speaker: "Você", l1: "Que lindo. E vale a pena subir até o mirante?", en: "How beautiful. And is it worth going up to the lookout?" },
            { speaker: "Guia", l1: "Vale muito a pena. Lá de cima a vista da cidade é deslumbrante.", en: "It's totally worth it. From up there the view of the town is breathtaking." },
          ],
        },
        {
          type: "fillBlank",
          heading: "History & nature fill",
          items: [
            {
              template: "Ouro Preto é uma cidade ___ , do século XVIII.",
              answer: "colonial",
              en: "Ouro Preto is a colonial town, from the 18th century.",
              options: ["moderna", "colonial", "indígena", "futura"],
            },
            {
              template: "Do mirante, a ___ da cidade é deslumbrante.",
              answer: "vista",
              en: "From the lookout, the view of the city is breathtaking.",
              options: ["praia", "vista", "torre", "igreja"],
            },
            {
              template: "As Cataratas do Iguaçu são uma enorme ___ .",
              answer: "cachoeira",
              en: "The Iguaçu Falls are an enormous waterfall.",
              options: ["floresta", "montanha", "cachoeira", "estátua"],
            },
            {
              template: "Subimos no ___ até o topo do Pão de Açúcar.",
              answer: "bondinho",
              en: "We went up in the cable car to the top of Sugarloaf.",
              options: ["bondinho", "barco", "ônibus", "avião"],
            },
            {
              template: "O Aleijadinho foi um grande escultor do ___ brasileiro.",
              answer: "barroco",
              en: "Aleijadinho was a great sculptor of the Brazilian Baroque.",
              options: ["moderno", "gótico", "barroco", "futuro"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "This church is very old. It's from the colonial period.",
          reference: "Esta igreja é muito antiga. É do período colonial.",
          hint: "Use 'do' (de + o) for 'from the'. 'Old' = antigo/antiga — agree with igreja (feminine).",
        },
      ],
    },
    {
      slug: "landmarks-visit",
      title: "Visiting — tickets, hours, photos",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The tourist-survival phrases",
          body: [
            "<em>«Quanto custa a entrada?»</em> = How much is admission? Adult <em>inteira</em>, half-price <em>meia</em> (students and seniors), free <em>gratuito</em>.",
            "<em>«Que horas abre / fecha?»</em> = What time does it open / close? Many sights close on Mondays (<em>segunda-feira</em>).",
            "<em>«Tem visita guiada em inglês?»</em> = Is there a guided tour in English? Often a little extra.",
            "<em>«Pode tirar foto?»</em> = Can you take photos? Outdoors, usually yes — inside some museums, no.",
          ],
          keyPoint:
            "entrada inteira / meia / gratuita · visita guiada = guided tour · vale a pena = it's worth it.",
        },
        {
          type: "vocab",
          heading: "Buying tickets & visiting",
          items: [
            { l1: "o ingresso / a entrada", en: "the ticket / admission" },
            { l1: "a entrada inteira", en: "full-price admission" },
            { l1: "a meia (entrada)", en: "half-price (students, seniors)" },
            { l1: "a entrada gratuita", en: "free admission" },
            { l1: "a visita guiada", en: "the guided tour" },
            { l1: "o guia turístico", en: "the tour guide (person)" },
            { l1: "a bilheteria", en: "the ticket office (BR)" },
            { l1: "a fila", en: "the queue / line" },
            { l1: "o horário de funcionamento", en: "opening hours" },
            { l1: "a saída", en: "the exit" },
            { l1: "tirar foto / fotografar", en: "to take a photo" },
            { l1: "proibido", en: "forbidden / not allowed" },
          ],
        },
        {
          type: "tip",
          heading: "BR vs PT: ingresso, bilhete, entrada",
          body: "In Brazil the usual word for an admission ticket is <em>o ingresso</em> (or simply <em>a entrada</em>), bought at the <em>bilheteria</em>. In Portugal you'll hear <em>o bilhete</em> or <em>a entrada</em>, bought at the <em>bilheteira</em>. Same idea, three words — and a student discount is <em>meia-entrada</em> in Brazil but often just <em>desconto de estudante</em> in Portugal.",
          example: { l1: "BR: um ingresso, por favor · PT: um bilhete, por favor", en: "one ticket, please" },
        },
        {
          type: "dialogue",
          heading: "At the Pão de Açúcar ticket office",
          setup: "You're at the bondinho (cable car) ticket window with a friend.",
          lines: [
            { speaker: "Você", l1: "Boa tarde. Quanto custa a entrada para o bondinho?", en: "Good afternoon. How much is admission for the cable car?" },
            { speaker: "Atendente", l1: "A inteira custa cento e cinquenta reais. Tem meia para estudante.", en: "Full price is a hundred and fifty reais. There's a half-price ticket for students." },
            { speaker: "Você", l1: "Então dois ingressos: uma inteira e uma meia, por favor.", en: "Then two tickets: one full and one half-price, please." },
            { speaker: "Atendente", l1: "Tem o comprovante de estudante?", en: "Do you have the student ID?" },
            { speaker: "Você", l1: "Tenho, aqui está. Que horas fecha hoje?", en: "Yes, here it is. What time does it close today?" },
            { speaker: "Atendente", l1: "Fecha às nove da noite. O pôr do sol lá de cima vale muito a pena.", en: "It closes at nine p.m. The sunset from up there is really worth it." },
            { speaker: "Você", l1: "Ótimo. Pode tirar foto no mirante?", en: "Great. Can you take photos at the lookout?" },
            { speaker: "Atendente", l1: "Pode, claro. À vontade.", en: "Yes, of course. Feel free." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Visiting phrases",
          items: [
            {
              template: "Quanto custa a ___ para o museu?",
              answer: "entrada",
              en: "How much is admission to the museum?",
              options: ["entrada", "saída", "fila", "visita"],
            },
            {
              template: "Tem ___ para estudante?",
              answer: "meia",
              en: "Is there a half-price ticket for students?",
              options: ["inteira", "meia", "saída", "fila"],
            },
            {
              template: "Que horas o museu ___ ?",
              answer: "fecha",
              en: "What time does the museum close?",
              options: ["abre", "fecha", "começa", "termina"],
            },
            {
              template: "Pode ___ foto aqui dentro?",
              answer: "tirar",
              en: "Can you take photos in here?",
              options: ["dar", "tirar", "fazer", "ver"],
            },
            {
              template: "A visita guiada ___ a pena.",
              answer: "vale",
              en: "The guided tour is worth it.",
              options: ["custa", "vale", "abre", "tira"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the request",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Quanto", "custa", "a", "entrada", "?"], en: "How much is admission?" },
            { tokens: ["Que", "horas", "abre", "o", "museu", "?"], en: "What time does the museum open?" },
            { tokens: ["Tem", "visita", "guiada", "em", "inglês", "?"], en: "Is there a guided tour in English?" },
            { tokens: ["Uma", "inteira", "e", "uma", "meia", "por", "favor"], en: "One full and one half-price, please." },
          ],
        },
        {
          type: "tip",
          heading: "Free days, queues & booking ahead",
          body: "Many Brazilian museums offer free entry on certain days (often Sundays or Tuesdays) — beautiful, but the <em>fila</em> (line) can be long. For the big icons — Cristo Redentor, Pão de Açúcar, the Iguaçu boat trips — buy your <em>ingresso</em> online in advance to skip the queue. The Cristo is best at sunrise; Sugarloaf is best at the <em>pôr do sol</em> (sunset). Go up early or late to dodge the crowds and the midday haze.",
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Two tickets, please. One full and one half-price for a student.",
          reference: "Dois ingressos, por favor. Uma inteira e uma meia para estudante.",
          hint: "BR uses 'ingresso'. inteira (full) / meia (half-price). 'For a student' = para estudante.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'Christ the Redeemer' =",
        options: [
          "o Cristo Salvador",
          "o Cristo Redentor",
          "o Senhor do Bonfim",
          "o Cristo Rei",
        ],
        correct: 1,
      },
      {
        q: "'Sugarloaf Mountain' =",
        options: [
          "o Pão de Açúcar",
          "o Pico Doce",
          "a Montanha de Açúcar",
          "o Morro do Pão",
        ],
        correct: 0,
      },
      {
        q: "The Iguaçu Falls in Portuguese =",
        options: [
          "as Quedas do Amazonas",
          "as Cataratas do Iguaçu",
          "as Cachoeiras de Foz",
          "as Águas do Paraná",
        ],
        correct: 1,
      },
      {
        q: "The Torre de Belém and Mosteiro dos Jerónimos are in…",
        options: ["Rio de Janeiro", "Lisboa (Portugal)", "Salvador", "Manaus"],
        correct: 1,
      },
      {
        q: "In Brazil, an admission ticket is usually called…",
        options: ["o bilhete", "o ingresso", "o passe", "a senha"],
        correct: 1,
      },
      {
        q: "'Half-price ticket (student/senior)' in Brazil =",
        options: ["a inteira", "a meia", "a gratuita", "o desconto"],
        correct: 1,
      },
      {
        q: "'What time does it close?' =",
        options: [
          "Que horas abre?",
          "Que horas fecha?",
          "Quanto custa?",
          "Onde fica?",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'How much is admission?'",
        options: [
          "Quanto custa a entrada?",
          "Quanto faz a entrada?",
          "Qual é a entrada?",
          "Onde está a entrada?",
        ],
        correct: 0,
      },
      {
        q: "'It's worth it' =",
        options: ["custa a pena", "vale a pena", "faz a pena", "tem a pena"],
        correct: 1,
      },
      {
        q: "The cable car up the Pão de Açúcar is the…",
        options: ["o barco", "o bondinho", "o trem", "o metrô"],
        correct: 1,
      },
    ],
  },
};
