import type { Unit } from "../../types";

export const UNIT_FOOD_VOCAB: Unit = {
  slug: "food-vocab",
  stage: 4,
  order: 17,
  icon: "🥬",
  title: "Food vocab deep dive",
  tagline: "Legumes, carnes, peixes, formas de preparo.",
  badge: "tourist",
  lessons: [
    {
      slug: "food-meat",
      title: "Carnes — meat at the açougue and on the menu",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Brazil runs on meat — know your animals",
          body: [
            "Brazilian cooking, and especially the churrasco (barbecue), is built on meat. The umbrella word is <em>carne</em> — but on its own <em>carne</em> almost always means beef.",
            "By animal: <em>carne (de boi)</em> = beef, <em>frango</em> = chicken, <em>porco</em> = pork, <em>carne de carneiro / cordeiro</em> = lamb, <em>peru</em> = turkey.",
            "Cured and processed meats are everywhere at the <em>café da manhã</em> (breakfast): <em>presunto</em> (cooked ham), <em>queijo</em> (cheese), <em>linguiça</em> (sausage), <em>bacon</em>.",
            "At a churrascaria the star cuts are <em>picanha</em> (the prized rump cap), <em>costela</em> (ribs), and <em>maminha</em> — words you won't find in a textbook but will hear constantly.",
          ],
          keyPoint:
            "carne (de boi) = beef · frango = chicken · porco = pork · presunto = ham · linguiça = sausage · picanha = the famous churrasco cut.",
        },
        {
          type: "vocab",
          heading: "Carnes (meat)",
          items: [
            { l1: "a carne", en: "meat / beef", note: "Alone, usually means beef" },
            { l1: "a carne de boi", en: "beef", note: "boi = ox; spells it out when needed" },
            { l1: "o frango", en: "chicken", note: "The bird on the plate; live bird = a galinha" },
            { l1: "o porco / a carne de porco", en: "pork", note: "" },
            { l1: "a carne de carneiro / o cordeiro", en: "lamb / mutton", note: "cordeiro = young lamb" },
            { l1: "o peru", en: "turkey", note: "Classic at Christmas (Natal)" },
            { l1: "o bife", en: "steak / beefsteak", note: "Any pan-fried slice of beef" },
            { l1: "a picanha", en: "rump cap (prized churrasco cut)", note: "The most beloved BR steak" },
            { l1: "a costela", en: "ribs", note: "Slow-cooked at churrasco" },
            { l1: "o presunto", en: "(cooked) ham", note: "Shared BR/PT; breakfast staple" },
            { l1: "a linguiça", en: "fresh sausage", note: "Grilled at every churrasco" },
            { l1: "a salsicha", en: "hot-dog sausage", note: "The cachorro-quente type" },
            { l1: "o bacon", en: "bacon", note: "Borrowed straight from English" },
            { l1: "a almôndega", en: "meatball", note: "" },
          ],
        },
        {
          type: "tip",
          heading: "Frango vs galinha — bird on the plate vs bird in the yard",
          body: "Both mean 'chicken', but Brazilians use <em>frango</em> for the meat you eat (<em>frango grelhado</em>, <em>peito de frango</em> = chicken breast) and <em>galinha</em> for the live hen or for a stewed old bird (<em>canja de galinha</em> = chicken soup). Order <em>frango</em> at a restaurant.",
          example: { l1: "Eu quero peito de frango grelhado.", en: "I want grilled chicken breast." },
        },
        {
          type: "multipleChoice",
          heading: "Quick check",
          questions: [
            {
              q: "On a menu, plain 'carne' most often means…",
              options: ["pork", "beef", "chicken", "lamb"],
              correct: 1,
              fb: "Carne by itself almost always means beef in Brazil. For other meats they name the animal: carne de porco, etc.",
            },
            {
              q: "Which is the prized Brazilian churrasco cut?",
              options: ["costela", "picanha", "linguiça", "presunto"],
              correct: 1,
              fb: "Picanha (rump cap) is the most beloved cut at a Brazilian barbecue.",
            },
            {
              q: "You want chicken at a restaurant. You ask for…",
              options: ["galinha", "frango", "peru", "porco"],
              correct: 1,
              fb: "Frango is the chicken-as-food word. Galinha is the live hen or a stewed old bird.",
            },
            {
              q: "'Presunto' is…",
              options: ["sausage", "bacon", "cooked ham", "ribs"],
              correct: 2,
              fb: "Presunto = cooked ham — a breakfast staple shared by Brazil and Portugal.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'd like grilled chicken and a little sausage.",
          reference: "Eu quero frango grelhado e um pouco de linguiça.",
          hint: "Use frango (not galinha). grelhado = grilled. 'a little' = um pouco de.",
        },
      ],
    },
    {
      slug: "food-fish-veg",
      title: "Peixes, frutos do mar, legumes e verduras",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "From the coast and from the garden",
          body: [
            "Brazil has a huge coastline, so seafood (<em>frutos do mar</em>) is everywhere: <em>peixe</em> = fish, <em>camarão</em> = shrimp, <em>lula</em> = squid, <em>polvo</em> = octopus, <em>caranguejo</em> = crab.",
            "The everyday plate, though, is <em>arroz e feijão</em> — rice and beans, the soul of Brazilian home cooking, eaten almost daily.",
            "Two useful umbrella words: <em>legumes</em> (the fruit-of-the-plant vegetables — tomato, pumpkin, carrot) and <em>verduras</em> (leafy greens — lettuce, kale, spinach). Together people just say <em>verduras e legumes</em>.",
            "Aromatics that flavor nearly everything: <em>cebola</em> (onion), <em>alho</em> (garlic), and the chopped-herb mix <em>cheiro-verde</em> (parsley + scallion).",
          ],
        },
        {
          type: "vocab",
          heading: "Peixes e frutos do mar (fish & seafood)",
          items: [
            { l1: "o peixe", en: "fish" },
            { l1: "o camarão", en: "shrimp / prawn", note: "Star of moqueca and acarajé" },
            { l1: "a lula", en: "squid" },
            { l1: "o polvo", en: "octopus" },
            { l1: "o caranguejo", en: "crab", note: "" },
            { l1: "o salmão", en: "salmon" },
            { l1: "o atum", en: "tuna" },
            { l1: "o bacalhau", en: "salt cod", note: "Beloved BR & PT; Portuguese classic" },
            { l1: "a sardinha", en: "sardine" },
            { l1: "o marisco", en: "shellfish", note: "Generic mollusk/shellfish" },
          ],
        },
        {
          type: "vocab",
          heading: "Legumes e grãos (vegetables & staples)",
          items: [
            { l1: "o arroz", en: "rice", note: "Half of arroz e feijão" },
            { l1: "o feijão", en: "beans", note: "The other half; base of feijoada" },
            { l1: "a batata", en: "potato" },
            { l1: "a batata-doce", en: "sweet potato" },
            { l1: "a mandioca / o aipim", en: "cassava / manioc", note: "aipim & macaxeira are regional names" },
            { l1: "a cebola", en: "onion" },
            { l1: "o alho", en: "garlic" },
            { l1: "o tomate", en: "tomato" },
            { l1: "a cenoura", en: "carrot" },
            { l1: "a abóbora", en: "pumpkin / squash" },
            { l1: "o milho", en: "corn" },
            { l1: "o pimentão", en: "bell pepper" },
          ],
        },
        {
          type: "vocab",
          heading: "Verduras (leafy greens & herbs)",
          items: [
            { l1: "a alface", en: "lettuce" },
            { l1: "a couve", en: "kale / collard greens", note: "Sliced thin alongside feijoada" },
            { l1: "o espinafre", en: "spinach" },
            { l1: "a rúcula", en: "arugula / rocket" },
            { l1: "a salsa / a salsinha", en: "parsley" },
            { l1: "a cebolinha", en: "scallion / spring onion" },
            { l1: "o cheiro-verde", en: "parsley + scallion mix", note: "Sold as a bunch; flavors everything" },
            { l1: "o coentro", en: "cilantro / coriander", note: "Big in the Northeast (Bahia)" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Vocab check",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "O prato do dia é ___ e feijão.",
              answer: "arroz",
              en: "The dish of the day is rice and beans.",
              options: ["arroz", "alho", "atum", "alface"],
            },
            {
              template: "Quero uma moqueca de ___ .",
              answer: "camarão",
              en: "I want a shrimp moqueca.",
              options: ["frango", "camarão", "cebola", "couve"],
            },
            {
              template: "Para a salada, só ___ e tomate.",
              answer: "alface",
              en: "For the salad, just lettuce and tomato.",
              options: ["alface", "feijão", "milho", "polvo"],
            },
            {
              template: "Pode pôr menos ___ ? Não gosto muito de alho.",
              answer: "alho",
              en: "Can you put less garlic? I don't like garlic much.",
              options: ["alho", "arroz", "atum", "lula"],
            },
            {
              template: "A feijoada vem com ___ refogada do lado.",
              answer: "couve",
              en: "The feijoada comes with sautéed kale on the side.",
              options: ["rúcula", "couve", "cenoura", "abóbora"],
            },
          ],
        },
        {
          type: "tip",
          heading: "Legumes ≠ legumes (a false friend)",
          body: "In English a 'legume' is a bean or pulse. In Portuguese <em>legumes</em> means vegetables in general (the fruity ones: tomato, carrot, squash). Beans are <em>feijão</em>, and leafy greens are <em>verduras</em>. So 'I eat lots of vegetables' = <em>como muitos legumes e verduras</em>.",
          example: { l1: "Como muitos legumes e verduras.", en: "I eat lots of vegetables (and greens)." },
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'd like fish with rice, beans, and a salad.",
          reference: "Eu quero peixe com arroz, feijão e salada.",
          hint: "peixe = fish. Remember arroz e feijão (rice and beans). salada = salad.",
        },
      ],
    },
    {
      slug: "food-fruit-cooking",
      title: "Frutas tropicais e formas de preparo",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Tropical fruit + how it's cooked",
          body: [
            "Brazil is a paradise of <em>frutas</em>. Beyond the familiar ones (<em>banana</em>, <em>laranja</em> = orange, <em>maçã</em> = apple, <em>uva</em> = grape), the tropical stars are <em>manga</em> (mango), <em>maracujá</em> (passion fruit), <em>mamão</em> (papaya), <em>abacaxi</em> (pineapple), <em>goiaba</em> (guava), and <em>caju</em> (cashew fruit).",
            "These show up as <em>suco</em> (juice) and <em>vitamina</em> (fruit-and-milk smoothie) — <em>suco de maracujá</em> is a national favorite.",
            "For the kitchen, a handful of preparation words cover almost any menu line: <em>grelhado</em> (grilled), <em>assado</em> (roasted/baked), <em>frito</em> (fried), <em>cozido</em> (boiled/cooked), and <em>na chapa</em> (on the flat-top griddle).",
          ],
          keyPoint:
            "Tropical: manga, maracujá, mamão, abacaxi, goiaba. Preparo: grelhado, assado, frito, cozido, na chapa.",
        },
        {
          type: "vocab",
          heading: "Frutas (fruit)",
          items: [
            { l1: "a fruta", en: "fruit" },
            { l1: "a banana", en: "banana" },
            { l1: "a laranja", en: "orange" },
            { l1: "a maçã", en: "apple" },
            { l1: "a uva", en: "grape" },
            { l1: "a manga", en: "mango", note: "Tropical; also means 'sleeve' — context tells" },
            { l1: "o maracujá", en: "passion fruit", note: "suco de maracujá is iconic" },
            { l1: "o mamão", en: "papaya", note: "BR word; see the tip on papaia" },
            { l1: "o abacaxi", en: "pineapple", note: "BR word; PT says ananás" },
            { l1: "a goiaba", en: "guava", note: "Also goiabada, a thick paste" },
            { l1: "o caju", en: "cashew fruit", note: "Its nut = a castanha de caju" },
            { l1: "o abacate", en: "avocado", note: "In BR often eaten sweet, in a vitamina" },
            { l1: "o limão", en: "lime / lemon", note: "The caipirinha citrus" },
            { l1: "o coco", en: "coconut", note: "água de coco = coconut water" },
          ],
        },
        {
          type: "tip",
          heading: "Abacaxi / ananás and mamão / papaia — BR vs PT",
          body: "Two classic vocabulary splits: pineapple is <strong>abacaxi</strong> in Brazil but <strong>ananás</strong> in Portugal. Papaya is <strong>mamão</strong> in Brazil; in Portugal it's <strong>papaia</strong> (and a small variety is called papaia there too). Both countries fully understand the other word, but locals default to their own.",
          example: { l1: "BR: suco de abacaxi · PT: sumo de ananás", en: "pineapple juice" },
        },
        {
          type: "vocab",
          heading: "Formas de preparo (cooking methods)",
          intro: "Add these to a food word to describe how it's cooked.",
          items: [
            { l1: "grelhado", en: "grilled", note: "frango grelhado = grilled chicken" },
            { l1: "assado", en: "roasted / baked", note: "frango assado = roast chicken" },
            { l1: "frito", en: "fried", note: "batata frita = french fries" },
            { l1: "cozido", en: "boiled / cooked through", note: "ovo cozido = boiled egg" },
            { l1: "na chapa", en: "on the flat-top griddle", note: "Very Brazilian: pão na chapa" },
            { l1: "na brasa", en: "char-grilled (over embers)", note: "The churrasco way" },
            { l1: "refogado", en: "sautéed (with onion/garlic)", note: "How beans & greens start" },
            { l1: "ensopado", en: "stewed (in broth)", note: "" },
            { l1: "no vapor", en: "steamed", note: "" },
            { l1: "empanado / à milanesa", en: "breaded", note: "filé à milanesa = breaded cutlet" },
            { l1: "cru", en: "raw", note: "Feminine: crua" },
            { l1: "no ponto", en: "medium / just right (steak)", note: "mal passado = rare · bem passado = well done" },
          ],
        },
        {
          type: "dialogue",
          heading: "Ordering and asking how it's cooked",
          setup: "You're at a por-quilo (pay-by-weight) restaurant counter.",
          lines: [
            { speaker: "Você", l1: "O peixe é grelhado ou frito?", en: "Is the fish grilled or fried?" },
            { speaker: "Atendente", l1: "Tem dos dois. O grelhado vem com legumes no vapor.", en: "We have both. The grilled one comes with steamed vegetables." },
            { speaker: "Você", l1: "Quero o grelhado, então. E o bife, posso pedir no ponto?", en: "I'll have the grilled one, then. And the steak, can I order it medium?" },
            { speaker: "Atendente", l1: "Claro. No ponto, mal passado ou bem passado?", en: "Of course. Medium, rare, or well done?" },
            { speaker: "Você", l1: "No ponto, por favor. Com arroz e feijão.", en: "Medium, please. With rice and beans." },
            { speaker: "Atendente", l1: "Saindo. Algo para beber?", en: "Coming up. Anything to drink?" },
            { speaker: "Você", l1: "Um suco de maracujá, por favor.", en: "A passion-fruit juice, please." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Preparo fill",
          items: [
            {
              template: "Eu quero a batata ___ , bem crocante.",
              answer: "frita",
              en: "I want the potato fried, nice and crispy.",
              options: ["frita", "cozida", "crua", "assada"],
            },
            {
              template: "O frango ___ é mais saudável que o frito.",
              answer: "grelhado",
              en: "Grilled chicken is healthier than fried.",
              options: ["grelhado", "ensopado", "cru", "empanado"],
            },
            {
              template: "No churrasco, a picanha vem ___ .",
              answer: "na brasa",
              en: "At the barbecue, the picanha comes char-grilled.",
              options: ["no vapor", "na brasa", "cozida", "crua"],
            },
            {
              template: "Prefiro o bife ___ , não gosto de carne crua.",
              answer: "bem passado",
              en: "I prefer the steak well done, I don't like raw meat.",
              options: ["mal passado", "no ponto", "bem passado", "cru"],
            },
            {
              template: "De sobremesa, um suco de ___ , por favor.",
              answer: "maracujá",
              en: "For dessert, a passion-fruit juice, please.",
              options: ["alface", "maracujá", "cebola", "couve"],
            },
          ],
        },
        {
          type: "pronounce",
          heading: "Tricky food words to say aloud",
          items: [
            { l1: "abacaxi", en: "pineapple", tip: "ah-bah-kah-SHEE (final 'xi' = 'shee')" },
            { l1: "maracujá", en: "passion fruit", tip: "mah-rah-koo-ZHAH (stress the last syllable)" },
            { l1: "mamão", en: "papaya", tip: "mah-MOWNG (nasal -ão ending)" },
            { l1: "linguiça", en: "sausage", tip: "leen-GWEE-sah (the 'gui' = 'gwee')" },
            { l1: "couve", en: "kale", tip: "KOH-vee" },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I want the fish grilled, with steamed vegetables.",
          reference: "Eu quero o peixe grelhado, com legumes no vapor.",
          hint: "grelhado = grilled. 'steamed vegetables' = legumes no vapor.",
        },
        {
          type: "tip",
          heading: "Ask freely — Brazilian kitchens flex",
          body: "Brazilians order with lots of small modifications and nobody minds. Useful openers: <em>«Pode ser sem…?»</em> (Can it be without…?), <em>«Pode trocar X por Y?»</em> (Can you swap X for Y?), and <em>«Tem opção sem glúten / vegetariana?»</em> (Is there a gluten-free / vegetarian option?). The por-quilo (pay-by-weight) and self-service buffets make it even easier — you just take what you want.",
          example: { l1: "Pode ser sem cebola, por favor?", en: "Can it be without onion, please?" },
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "On a menu, plain 'carne' usually means…",
        options: ["pork", "beef", "chicken", "fish"],
        correct: 1,
      },
      {
        q: "The chicken-as-food word (used at restaurants) is…",
        options: ["galinha", "frango", "peru", "pato"],
        correct: 1,
      },
      {
        q: "The famous prized Brazilian churrasco cut is…",
        options: ["costela", "linguiça", "picanha", "presunto"],
        correct: 2,
      },
      {
        q: "'Camarão' =",
        options: ["squid", "shrimp", "crab", "octopus"],
        correct: 1,
      },
      {
        q: "The soul of Brazilian home cooking, eaten almost daily, is…",
        options: ["bacalhau e batata", "arroz e feijão", "pão e queijo", "milho e couve"],
        correct: 1,
      },
      {
        q: "In Portuguese, 'legumes' means…",
        options: ["beans / pulses", "vegetables in general", "leafy greens only", "fruit"],
        correct: 1,
      },
      {
        q: "Pineapple is 'abacaxi' in Brazil. In Portugal it's…",
        options: ["ananás", "mamão", "papaia", "goiaba"],
        correct: 0,
      },
      {
        q: "'Mamão' (BR) is called what in Portugal?",
        options: ["ananás", "papaia", "abacaxi", "manga"],
        correct: 1,
      },
      {
        q: "'Grelhado' means…",
        options: ["fried", "boiled", "grilled", "raw"],
        correct: 2,
      },
      {
        q: "You want your steak cooked medium. You ask for it…",
        options: ["mal passado", "no ponto", "bem passado", "cru"],
        correct: 1,
      },
    ],
  },
};
