import type { Unit } from "../../types";

export const UNIT_BRAZILIAN_FOOD: Unit = {
  slug: "brazilian-food",
  stage: 4,
  order: 19,
  icon: "🥘",
  title: "Brazilian & Portuguese food",
  tagline: "Feijoada, pão de queijo, pastel, bacalhau, gorjeta.",
  badge: "tourist",
  lessons: [
    {
      slug: "brazilian-food-classics",
      title: "Brazilian classics: feijoada to açaí",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The dishes Brazil is famous for",
          body: [
            "Brazilian food is regional and abundant, but a handful of dishes show up everywhere. <strong>Feijoada</strong> is the national favourite: a rich black-bean stew with cuts of pork, served with rice, <em>couve</em> (collard greens), orange slices, and <em>farofa</em>. It's heavy — traditionally a Saturday lunch, not a weeknight dinner.",
            "<strong>Pão de queijo</strong> (cheese bread) is a small, chewy, gluten-free roll made with <em>polvilho</em> (cassava starch) and cheese. It's eaten any time — breakfast, snack, alongside coffee. It comes from Minas Gerais but is now everywhere.",
            "<strong>Açaí</strong> (ah-sah-EE) is a frozen purple bowl of Amazonian berry, usually served thick like sorbet and topped with <em>granola</em> and banana. In Rio it's a beach staple; in the north it's eaten savoury with fish.",
            "<strong>Brigadeiro</strong> is the birthday-party chocolate truffle — condensed milk, cocoa, butter, rolled in sprinkles. No Brazilian celebration happens without it.",
          ],
          keyPoint:
            "Feijoada (black-bean + pork stew, Saturday lunch) · pão de queijo (cheese bread, any time) · açaí (frozen berry bowl) · brigadeiro (party truffle).",
        },
        {
          type: "vocab",
          heading: "The Brazilian lineup",
          items: [
            { l1: "a feijoada", en: "black-bean and pork stew", note: "The national dish; eaten at lunch" },
            { l1: "o feijão", en: "beans", note: "Daily staple, usually with rice (arroz)" },
            { l1: "o arroz", en: "rice", note: "arroz e feijão = the everyday base plate" },
            { l1: "a couve", en: "collard greens", note: "Sliced thin, sautéed; served with feijoada" },
            { l1: "a farofa", en: "toasted cassava flour", note: "Sprinkled over the plate for crunch" },
            { l1: "o pão de queijo", en: "cheese bread", note: "Chewy, gluten-free; from Minas Gerais" },
            { l1: "o açaí", en: "açaí (frozen berry bowl)", note: "ah-sah-EE; topped with granola + banana" },
            { l1: "o brigadeiro", en: "chocolate condensed-milk truffle", note: "The birthday-party sweet" },
            { l1: "a moqueca", en: "fish/seafood coconut stew", note: "Bahian; cooked with dendê palm oil" },
            { l1: "o churrasco", en: "barbecue (Brazilian style)", note: "Grilled meats; the rodízio buffet" },
          ],
        },
        {
          type: "tip",
          heading: "Arroz e feijão — the plate underneath everything",
          body: "Most Brazilian lunches are built on <em>arroz e feijão</em> (rice and beans) — the comfort base that everything else sits on. If someone offers <em>comida caseira</em> (home cooking) or a <em>prato feito</em> (PF — a fixed plate at a cheap restaurant), expect rice, beans, a protein, and a small salad. It's the most authentic everyday meal you can order.",
          example: { l1: "Hoje tem arroz, feijão e bife. Quer farofa?", en: "Today there's rice, beans, and steak. Want farofa?" },
        },
        {
          type: "dialogue",
          heading: "Ordering feijoada at lunch",
          setup: "It's Saturday and you're at a botequim that serves feijoada.",
          lines: [
            { speaker: "Garçom", l1: "Boa tarde! A feijoada hoje está ótima. Vai querer?", en: "Good afternoon! The feijoada is great today. Want some?" },
            { speaker: "Você", l1: "Quero, sim. Vem com arroz e couve?", en: "Yes, I do. Does it come with rice and collard greens?" },
            { speaker: "Garçom", l1: "Vem com arroz, couve, farofa e laranja. Pode ser para uma pessoa?", en: "It comes with rice, collards, farofa, and orange. For one person?" },
            { speaker: "Você", l1: "Pode. E o que vocês têm para beber?", en: "Sure. And what do you have to drink?" },
            { speaker: "Garçom", l1: "Suco de laranja, refrigerante, ou uma caipirinha?", en: "Orange juice, soda, or a caipirinha?" },
            { speaker: "Você", l1: "Um suco de laranja, por favor. A feijoada é pesada!", en: "An orange juice, please. Feijoada is heavy!" },
            { speaker: "Garçom", l1: "Boa escolha. Já trago.", en: "Good choice. I'll bring it right away." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Classics check",
          questions: [
            {
              q: "Feijoada is best described as…",
              options: [
                "a frozen berry bowl",
                "a black-bean and pork stew",
                "a chocolate truffle",
                "a cheese bread",
              ],
              correct: 1,
              fb: "Feijoada is the black-bean and pork stew, traditionally a Saturday lunch.",
            },
            {
              q: "Pão de queijo is naturally gluten-free because it's made with…",
              options: ["wheat flour", "cassava starch (polvilho)", "cornmeal", "rice flour"],
              correct: 1,
              fb: "Polvilho (cassava starch) replaces wheat, so pão de queijo is gluten-free and chewy.",
            },
            {
              q: "Brigadeiro is…",
              options: [
                "a savoury fish stew",
                "the birthday-party chocolate truffle",
                "a grilled-meat platter",
                "a frozen dessert",
              ],
              correct: 1,
              fb: "Brigadeiro — condensed milk, cocoa, butter, rolled in sprinkles — is the party sweet.",
            },
            {
              q: "'Arroz e feijão' refers to…",
              options: [
                "a fancy restaurant dish",
                "the everyday rice-and-beans base plate",
                "a dessert",
                "a regional drink",
              ],
              correct: 1,
              fb: "Arroz e feijão (rice and beans) is the comfort base of most Brazilian lunches.",
            },
            {
              q: "Farofa is…",
              options: ["a drink", "toasted cassava flour for crunch", "a kind of bean", "a cut of pork"],
              correct: 1,
              fb: "Farofa is toasted cassava flour, sprinkled over the plate for texture.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'd like the feijoada with rice. Does it come with farofa?",
          reference: "Eu queria a feijoada com arroz. Vem com farofa?",
          hint: "'I'd like' = eu queria (soft, polite). 'Does it come with…?' = Vem com…?",
        },
      ],
    },
    {
      slug: "brazilian-food-street-snacks",
      title: "Street food: pastel, coxinha, churrasco",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Snacking like a Brazilian",
          body: [
            "Brazilian street and bar snacks are called <em>salgados</em> (savouries). The two icons: the <strong>pastel</strong> — a thin, crispy fried pastry pocket stuffed with cheese, meat, or <em>palmito</em> (heart of palm), classic at weekend markets (<em>feiras</em>) with a glass of sugarcane juice (<em>caldo de cana</em>) — and the <strong>coxinha</strong>, a teardrop of shredded chicken in dough, breaded and fried.",
            "<strong>Pão na chapa</strong> is the breakfast-bar staple: a French roll split, buttered, and toasted flat on the griddle. Order it with a <em>pingado</em> (coffee with a little milk) and you've had a proper São Paulo morning.",
            "<strong>Churrasco</strong> is the Brazilian barbecue. At a <em>churrascaria</em> with <em>rodízio</em> service, waiters circle the room with skewers of meat (<em>picanha</em>, sausage, chicken hearts) and carve onto your plate until you flip your card to red to say 'stop'.",
          ],
          keyPoint:
            "Salgados = savoury snacks · pastel (fried pocket) + caldo de cana · coxinha (chicken teardrop) · pão na chapa (toasted buttered roll) · churrasco rodízio (all-you-can-eat grill).",
        },
        {
          type: "vocab",
          heading: "Snacks, grill, and the bar",
          items: [
            { l1: "o salgado", en: "savoury snack", note: "Umbrella term for pastel, coxinha, etc." },
            { l1: "o pastel", en: "fried pastry pocket", note: "Crispy; filled with queijo, carne, palmito" },
            { l1: "a coxinha", en: "shredded-chicken croquette", note: "Teardrop-shaped, breaded, fried" },
            { l1: "o caldo de cana", en: "sugarcane juice", note: "The classic drink with a pastel" },
            { l1: "o pão na chapa", en: "toasted buttered roll", note: "Breakfast-bar staple" },
            { l1: "o pingado", en: "coffee with a little milk", note: "lit. 'dripped'; pairs with pão na chapa" },
            { l1: "o churrasco", en: "barbecue", note: "Grilled meats, often at a churrascaria" },
            { l1: "a picanha", en: "top sirloin cap", note: "The prized cut at a churrasco" },
            { l1: "o rodízio", en: "all-you-can-eat service", note: "Waiters bring skewers until you say stop" },
            { l1: "o espetinho", en: "small grilled skewer", note: "Street-corner meat-on-a-stick" },
            { l1: "a feira", en: "open-air market", note: "Where you find the weekend pastel" },
            { l1: "o palmito", en: "heart of palm", note: "Popular vegetarian pastel filling" },
          ],
        },
        {
          type: "tip",
          heading: "The red-card rule at a rodízio",
          body: "At a churrasco rodízio, each diner gets a small disc on the table: green side up means 'keep bringing meat', red side up means 'I'm full, stop'. Flip it to red when you want a break — otherwise the <em>passadores</em> (the meat-carving waiters) will keep arriving. Save room: the <em>picanha</em> usually comes out partway through, not first.",
          example: { l1: "Pode virar a plaquinha no vermelho — estou satisfeito.", en: "You can flip the little card to red — I'm full." },
        },
        {
          type: "dialogue",
          heading: "At the pastel stand in the feira",
          setup: "Sunday market. You walk up to the busy pastel stall.",
          lines: [
            { speaker: "Você", l1: "Oi! Quais sabores de pastel vocês têm?", en: "Hi! What pastel flavours do you have?" },
            { speaker: "Vendedor", l1: "Queijo, carne, frango com catupiry, e palmito.", en: "Cheese, meat, chicken with catupiry, and heart of palm." },
            { speaker: "Você", l1: "Me vê um de queijo e um de palmito, por favor.", en: "Give me one cheese and one heart of palm, please." },
            { speaker: "Vendedor", l1: "Saindo. Vai querer um caldo de cana?", en: "Coming up. Want a sugarcane juice?" },
            { speaker: "Você", l1: "Quero! Com limão, se tiver.", en: "Yes! With lime, if you have it." },
            { speaker: "Vendedor", l1: "Tem sim. Os pastéis saem quentinhos, cuidado.", en: "We do. The pastéis come out hot, careful." },
            { speaker: "Você", l1: "Quanto fica tudo?", en: "How much for everything?" },
            { speaker: "Vendedor", l1: "Vinte reais. Pode pagar no pix ou no cartão.", en: "Twenty reais. You can pay by Pix or card." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Street-food fill-ins",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "Me vê um ___ de queijo, por favor.",
              answer: "pastel",
              en: "Give me a cheese pastel, please.",
              options: ["pastel", "caldo", "rodízio", "pingado"],
            },
            {
              template: "A ___ é feita de frango desfiado.",
              answer: "coxinha",
              en: "The coxinha is made of shredded chicken.",
              options: ["picanha", "coxinha", "farofa", "couve"],
            },
            {
              template: "No churrasco, vire a plaquinha no ___ quando estiver cheio.",
              answer: "vermelho",
              en: "At the barbecue, flip the card to red when you're full.",
              options: ["verde", "vermelho", "azul", "amarelo"],
            },
            {
              template: "Um pastel combina com um ___ de cana.",
              answer: "caldo",
              en: "A pastel goes well with a sugarcane juice.",
              options: ["caldo", "pão", "prato", "copo"],
            },
            {
              template: "A ___ é o corte mais famoso do churrasco.",
              answer: "picanha",
              en: "Picanha is the most famous cut at a barbecue.",
              options: ["coxinha", "couve", "picanha", "farofa"],
            },
          ],
        },
        {
          type: "pronounce",
          heading: "Snack words to say aloud",
          items: [
            { l1: "o pastel", en: "fried pastry pocket", tip: "pahs-TEW (the final 'l' becomes a 'w')" },
            { l1: "a coxinha", en: "chicken croquette", tip: "ko-SHEEN-yah (the 'nh' is like 'ny' in canyon)" },
            { l1: "o caldo de cana", en: "sugarcane juice", tip: "KOW-doo jee KAH-nah" },
            { l1: "a picanha", en: "top sirloin cap", tip: "pee-KAHN-yah" },
            { l1: "o churrasco", en: "barbecue", tip: "shoo-HAH-skoo (BR 'rr' is a soft 'h')" },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Give me one cheese pastel and a sugarcane juice, please.",
          reference: "Me vê um pastel de queijo e um caldo de cana, por favor.",
          hint: "'Give me' (casual BR) = me vê. 'Cheese pastel' = pastel de queijo.",
        },
      ],
    },
    {
      slug: "brazilian-food-meals-portugal-tipping",
      title: "Meals, Portugal, and the bill",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Three meals, Brazilian rhythm",
          body: [
            "<strong>Café da manhã</strong> (lit. 'morning coffee') is breakfast: coffee, fruit, bread or pão na chapa, sometimes <em>tapioca</em> or cheese. <strong>Almoço</strong> (lunch) is the big meal of the day — often the warm rice-beans-protein plate — eaten around noon to 2 pm. <strong>Jantar</strong> (dinner) is lighter and later, frequently just a sandwich, soup, or leftovers.",
            "A useful in-between is the <em>lanche</em> — an afternoon snack (a coffee with a salgado, or a <em>misto quente</em>, the toasted ham-and-cheese). Brazilians love an afternoon <em>cafezinho</em>, the small strong coffee offered everywhere.",
            "Don't confuse meal words across languages: in Portugal lunch is <em>almoço</em> too, but breakfast is <em>pequeno-almoço</em> — not <em>café da manhã</em>. A small but reliable tell of which side of the Atlantic you're on.",
          ],
          keyPoint:
            "BR: café da manhã (breakfast) · almoço (big lunch) · jantar (lighter dinner) · lanche/cafezinho (afternoon snack + coffee). PT breakfast = pequeno-almoço.",
        },
        {
          type: "vocab",
          heading: "Meals and the table",
          items: [
            { l1: "o café da manhã", en: "breakfast (BR)", note: "PT says pequeno-almoço" },
            { l1: "o almoço", en: "lunch", note: "The main meal of the day in Brazil" },
            { l1: "o jantar", en: "dinner", note: "Lighter and later than lunch" },
            { l1: "o lanche", en: "afternoon snack", note: "A coffee + salgado break" },
            { l1: "o cafezinho", en: "little strong coffee", note: "Offered everywhere, all day" },
            { l1: "a tapioca", en: "cassava crêpe", note: "Common breakfast/snack, sweet or savoury" },
            { l1: "o misto quente", en: "toasted ham-and-cheese", note: "The everyday hot sandwich" },
            { l1: "o cardápio", en: "the menu", note: "PT often says ementa instead" },
            { l1: "a conta", en: "the bill / check", note: "'A conta, por favor' = the check, please" },
            { l1: "a gorjeta", en: "the tip", note: "See the tipping note" },
          ],
        },
        {
          type: "intro",
          heading: "Portugal's table: bacalhau and pastéis de nata",
          body: [
            "Portuguese cuisine has its own icons. The biggest is <strong>bacalhau</strong> (salt cod) — the Portuguese say there are <em>mil maneiras</em> ('a thousand ways') to cook it: <em>bacalhau à brás</em> (shredded with egg and potato), <em>à Gomes de Sá</em> (baked with potato and onion), and many more. It's the Christmas Eve dish and a national obsession.",
            "<strong>Pastéis de nata</strong> are the famous custard tarts — crisp flaky pastry, caramelised custard, a dusting of cinnamon. The original from Belém in Lisbon is called <em>pastel de Belém</em>. <strong>Francesinha</strong> is Porto's monster sandwich: layers of meat under melted cheese in a beer-and-tomato sauce. <strong>Caldo verde</strong> is the comforting kale-and-potato soup with a slice of <em>chouriço</em>.",
            "Brazil and Portugal share a language and a love of cod (Brazilians eat <em>bacalhau</em> at Easter), but the everyday staples differ: rice-and-beans and tropical fruit in Brazil, cod and hearty soups in Portugal.",
          ],
          keyPoint:
            "PT: bacalhau (salt cod, 'a thousand ways') · pastéis de nata (custard tarts) · francesinha (Porto sandwich) · caldo verde (kale soup).",
        },
        {
          type: "vocab",
          heading: "Portuguese plates",
          items: [
            { l1: "o bacalhau", en: "salt cod", note: "PT national fish; 'mil maneiras' to cook it" },
            { l1: "o bacalhau à brás", en: "cod with egg and shredded potato", note: "A classic preparation" },
            { l1: "o pastel de nata", en: "custard tart", note: "Plural: pastéis de nata; from Belém" },
            { l1: "a francesinha", en: "Porto layered meat sandwich", note: "Cheese + beer-tomato sauce" },
            { l1: "o caldo verde", en: "kale-and-potato soup", note: "Served with chouriço" },
            { l1: "o chouriço", en: "smoked sausage (PT)", note: "BR says linguiça for fresh sausage" },
            { l1: "a ementa", en: "the menu (PT)", note: "BR says cardápio" },
            { l1: "o pequeno-almoço", en: "breakfast (PT)", note: "BR says café da manhã" },
          ],
        },
        {
          type: "tip",
          heading: "Bacalhau: a Portuguese obsession, a Brazilian holiday treat",
          body: "In Portugal, salt cod is a year-round staple — affordable, beloved, and cooked countless ways (<em>mil maneiras de bacalhau</em>). In Brazil the same fish is more of a special-occasion dish, eaten mainly around Easter and Christmas, and it's pricier as an import. So a Portuguese kitchen smelling of cod is a Tuesday; a Brazilian one usually means a holiday.",
          example: { l1: "Em Portugal há mil maneiras de fazer bacalhau; no Brasil é mais para a Páscoa.", en: "In Portugal there are a thousand ways to make cod; in Brazil it's more of an Easter thing." },
        },
        {
          type: "tip",
          heading: "Tipping: gorjeta and the 10%",
          body: "In Brazil, restaurants usually add a <em>serviço</em> of <strong>10%</strong> to the bill — it shows as <em>taxa de serviço</em> or 'os 10%'. It's customary but technically optional; you can decline it politely. Beyond that, extra tipping isn't expected. In Portugal, service is rarely added; rounding up or leaving a small <em>gorjeta</em> (a euro or two, or ~5–10%) for good service is the norm. Neither country expects the 18–20% common in the US.",
          example: { l1: "Os dez por cento estão incluídos na conta?", en: "Is the 10% service included in the bill?" },
        },
        {
          type: "dialogue",
          heading: "Asking for the bill",
          setup: "End of lunch in São Paulo. You wave the waiter over.",
          lines: [
            { speaker: "Você", l1: "A conta, por favor.", en: "The check, please." },
            { speaker: "Garçom", l1: "Claro. Já trago. Vai querer sobremesa ou um cafezinho?", en: "Of course. I'll bring it. Want dessert or a little coffee?" },
            { speaker: "Você", l1: "Só um cafezinho, obrigado. Os dez por cento estão incluídos?", en: "Just a little coffee, thanks. Is the 10% included?" },
            { speaker: "Garçom", l1: "Estão sim, a taxa de serviço já está na conta.", en: "Yes, the service charge is already on the bill." },
            { speaker: "Você", l1: "Perfeito. Posso pagar no cartão?", en: "Perfect. Can I pay by card?" },
            { speaker: "Garçom", l1: "Pode. Crédito ou débito? Também aceitamos pix.", en: "You can. Credit or debit? We also take Pix." },
            { speaker: "Você", l1: "Crédito. Estava tudo ótimo, obrigado!", en: "Credit. Everything was great, thank you!" },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the restaurant phrase",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["A", "conta", "por", "favor"], en: "The check, please." },
            { tokens: ["Os", "dez", "por", "cento", "estão", "incluídos"], en: "Is the 10% included?" },
            { tokens: ["Posso", "pagar", "no", "cartão"], en: "Can I pay by card?" },
            { tokens: ["Estava", "tudo", "ótimo", "obrigado"], en: "Everything was great, thank you." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Meals, Portugal, and paying",
          questions: [
            {
              q: "In Brazil, the big meal of the day is usually…",
              options: ["o café da manhã", "o almoço", "o jantar", "o lanche"],
              correct: 1,
              fb: "Almoço (lunch) is the main meal in Brazil; jantar (dinner) is lighter.",
            },
            {
              q: "In Portugal, 'breakfast' is…",
              options: ["o café da manhã", "o pequeno-almoço", "o almoço", "o lanche"],
              correct: 1,
              fb: "Portugal says pequeno-almoço; Brazil says café da manhã.",
            },
            {
              q: "'Mil maneiras de bacalhau' refers to…",
              options: [
                "a thousand ways to cook salt cod",
                "a Brazilian bean stew",
                "a custard tart",
                "a kind of coffee",
              ],
              correct: 0,
              fb: "Bacalhau (salt cod) is the Portuguese obsession cooked countless ways.",
            },
            {
              q: "Pastéis de nata are…",
              options: ["salt-cod fritters", "custard tarts", "kale soup", "barbecue skewers"],
              correct: 1,
              fb: "Pastéis de nata are the famous Portuguese custard tarts, originally from Belém.",
            },
            {
              q: "In a Brazilian restaurant, the service charge added to the bill is usually…",
              options: ["20%", "10%", "nothing", "5%"],
              correct: 1,
              fb: "Brazil adds about 10% (a taxa de serviço); it's customary but technically optional.",
            },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "Feijoada is…",
        options: [
          "a frozen berry bowl",
          "a black-bean and pork stew",
          "a Portuguese custard tart",
          "a sugarcane juice",
        ],
        correct: 1,
      },
      {
        q: "Pão de queijo is gluten-free because it uses…",
        options: ["wheat flour", "cassava starch (polvilho)", "rye", "oats"],
        correct: 1,
      },
      {
        q: "Açaí is typically served as…",
        options: [
          "a hot soup",
          "a thick frozen bowl with granola and banana",
          "a fried pocket",
          "a grilled skewer",
        ],
        correct: 1,
      },
      {
        q: "A coxinha is filled with…",
        options: ["heart of palm", "shredded chicken", "salt cod", "beans"],
        correct: 1,
      },
      {
        q: "At a churrasco rodízio, flipping your card to red means…",
        options: ["bring more meat", "I'm full, stop", "I want dessert", "the bill, please"],
        correct: 1,
      },
      {
        q: "The prized cut at a Brazilian barbecue is…",
        options: ["picanha", "couve", "farofa", "palmito"],
        correct: 0,
      },
      {
        q: "In Brazil, the main meal of the day is…",
        options: ["café da manhã", "almoço", "jantar", "lanche"],
        correct: 1,
      },
      {
        q: "'Mil maneiras de bacalhau' is associated with…",
        options: ["Brazil's daily plate", "Portugal's love of salt cod", "Bahian moqueca", "Minas cheese bread"],
        correct: 1,
      },
      {
        q: "Pastéis de nata are…",
        options: ["kale soup", "custard tarts", "fried pastry pockets", "chocolate truffles"],
        correct: 1,
      },
      {
        q: "A Brazilian restaurant's 'taxa de serviço' is usually about…",
        options: ["20%", "10%", "0% (never added)", "30%"],
        correct: 1,
      },
      {
        q: "In Portugal, 'breakfast' is called…",
        options: ["café da manhã", "pequeno-almoço", "almoço", "jantar"],
        correct: 1,
      },
      {
        q: "Translate: 'The check, please. Is the 10% included?'",
        options: [
          "A conta, por favor. Os dez por cento estão incluídos?",
          "O cardápio, por favor. Tem gorjeta?",
          "A gorjeta, por favor. Vem com arroz?",
          "A conta, obrigado. Quer sobremesa?",
        ],
        correct: 0,
      },
    ],
  },
};
