import type { Unit } from "../../types";

export const UNIT_NARRATE_TRIP: Unit = {
  slug: "narrate-trip",
  stage: 5,
  order: 24,
  icon: "📖",
  title: "Narrating a trip",
  tagline: "Combine tenses to tell your travel story.",
  badge: "core",
  lessons: [
    {
      slug: "narrate-structure",
      title: "How a trip story is structured",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "A Brazilian trip story has a recognizable shape",
          body: [
            "<strong>1. Set the scene</strong> with the imperfeito: <em>Era cedo. Fazia calor. Eu tinha só uma mochila.</em>",
            "<strong>2. Drop the events</strong> with the pretérito perfeito: <em>Cheguei no Rio de manhã. Peguei um táxi para Copacabana.</em>",
            "<strong>3. Add background details</strong> with the imperfeito: <em>Enquanto o táxi andava, eu olhava o mar.</em>",
            "<strong>4. The conclusion</strong> often shifts to the present: <em>Hoje, toda vez que penso naquela viagem, eu sorrio.</em>",
            "Connector words tie it together: <em>primeiro, depois, então, aí, de repente, enquanto, quando, no final…</em>",
          ],
          keyPoint:
            "Scene (imperfeito) → events (pretérito perfeito) → background of events (imperfeito) → conclusion (present). Connect with depois / então / enquanto / quando.",
        },
        {
          type: "vocab",
          heading: "Storytelling connectors",
          items: [
            { l1: "primeiro", en: "first" },
            { l1: "no começo / no início", en: "at the beginning" },
            { l1: "depois", en: "then / afterward" },
            { l1: "então", en: "so / then" },
            { l1: "aí", en: "then / and so (very common in BR speech)" },
            { l1: "de repente", en: "suddenly" },
            { l1: "enquanto", en: "while" },
            { l1: "quando", en: "when" },
            { l1: "logo", en: "right away / soon" },
            { l1: "no final / no fim", en: "in the end" },
            { l1: "por sorte / felizmente", en: "luckily" },
            { l1: "infelizmente", en: "unfortunately" },
            { l1: "que legal!", en: "how cool! (BR)" },
            { l1: "que pena!", en: "what a pity!" },
          ],
        },
        {
          type: "tip",
          heading: "The 'canvas and paint' rule",
          body: "Think of the imperfeito as the canvas — it paints the scene, gives the weather, describes how things felt and what was going on in the background (<em>fazia calor</em>, <em>era cedo</em>, <em>estava chovendo</em>). Think of the pretérito perfeito as the paint splash — it drops specific, completed events onto that canvas (<em>cheguei</em>, <em>vi</em>, <em>fomos</em>). A story with no imperfeito reads as a dry list; a story with no perfeito has no plot. You need both.",
        },
        {
          type: "tip",
          heading: "BR vs PT: 'was -ing' inside a story",
          body: "To describe an action in progress in the background, Brazil uses <em>estar + gerúndio</em>: <strong>estava chovendo</strong>, <strong>estava fazendo as malas</strong>. Portugal uses <em>estar a + infinitivo</em>: <strong>estava a chover</strong>, <strong>estava a fazer as malas</strong>. Both mean the same thing inside a narration. We tell stories the Brazilian way, but you'll hear the PT form in European Portuguese.",
          example: { l1: "BR: Estava chovendo quando cheguei. · PT: Estava a chover quando cheguei.", en: "It was raining when I arrived." },
        },
        {
          type: "dialogue",
          heading: "Telling your travel story",
          setup: "A friend asks about your weekend in Rio de Janeiro.",
          lines: [
            { speaker: "Bruno", l1: "E aí, como foi a viagem pro Rio?", en: "Hey, how was the trip to Rio?" },
            { speaker: "Você", l1: "Foi incrível! Era a minha primeira vez no Rio. Fazia muito calor, mas estava lindo. Cheguei na sexta de manhã.", en: "It was amazing! It was my first time in Rio. It was very hot, but it was beautiful. I arrived Friday morning." },
            { speaker: "Bruno", l1: "Onde você ficou?", en: "Where did you stay?" },
            { speaker: "Você", l1: "Reservei um hostel em Copacabana. Enquanto eu procurava o endereço, me perdi completamente. Por sorte, um senhor me ajudou.", en: "I booked a hostel in Copacabana. While I was looking for the address, I got completely lost. Luckily, a man helped me." },
            { speaker: "Bruno", l1: "E o que você fez lá?", en: "And what did you do there?" },
            { speaker: "Você", l1: "De tudo! Subi no Pão de Açúcar, fui à praia e comi muito açaí. Num dia o tempo estava nublado, então a gente foi ao museu.", en: "Everything! I went up Sugarloaf, went to the beach, and ate a lot of açaí. One day the weather was cloudy, so we went to the museum." },
            { speaker: "Bruno", l1: "Você vai voltar?", en: "Will you go back?" },
            { speaker: "Você", l1: "Com certeza. No ano que vem quero conhecer Paraty também.", en: "Definitely. Next year I want to see Paraty too." },
          ],
        },
      ],
    },
    {
      slug: "narrate-mix-tenses",
      title: "Mixing tenses fluidly",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The two-tense braid",
          body: [
            "A polished trip story weaves the imperfeito and the pretérito perfeito together naturally:",
            "<em><strong>Era</strong> uma bela manhã de janeiro. (imperfeito — scene)</em>",
            "<em><strong>Acordei</strong> às seis e <strong>tomei</strong> um café. (pretérito perfeito — events)</em>",
            "<em>Enquanto eu <strong>tomava</strong> o café, <strong>li</strong> a mensagem do Bruno. (imperfeito background + perfeito event)</em>",
            "<em>Ele <strong>dizia</strong> que <strong>ia chegar</strong> no Rio no dia seguinte. (imperfeito + 'ia + infinitive' = was going to)</em>",
            "<em>Hoje, toda vez que penso naquele dia, eu sorrio. (present — conclusion)</em>",
          ],
          keyPoint:
            "Imperfeito = states, ongoing background, weather, age, repeated habits. Pretérito perfeito = single completed events that move the story forward. Present = wraps it up.",
        },
        {
          type: "conjugation",
          heading: "Imperfeito — the 'background' tense",
          verb: "falar / comer / ir",
          meaning: "was/were …-ing, used to …",
          intro: "Regular endings: -ar → -ava, -er/-ir → -ia. 'Ser' and 'ir' are irregular (era…, ia…).",
          tenses: [{ name: "Imperfeito", forms: [
            { person: "eu falava", form: "eu comia / abria", en: "I was speaking / eating" },
            { person: "você/ele/ela falava", form: "comia / abria", en: "you/he/she was speaking" },
            { person: "nós falávamos", form: "comíamos / abríamos", en: "we were speaking" },
            { person: "vocês/eles falavam", form: "comiam / abriam", en: "they were speaking" },
            { person: "ser → era, éramos", form: "ir → ia, íamos", en: "(irregular)" },
          ] }],
        },
        {
          type: "fillBlank",
          heading: "Choose the right tense",
          items: [
            {
              template: "Ontem ___ (ser) um dia lindo.",
              answer: "era",
              en: "Yesterday was a beautiful day. (description → imperfeito)",
              options: ["era", "foi", "é", "será"],
            },
            {
              template: "Enquanto eu ___ (andar) pelo centro, ___ (encontrar) um amigo.",
              answer: "andava / encontrei",
              en: "While I was walking through downtown, I met a friend.",
              options: [
                "andava / encontrei",
                "andei / encontrava",
                "ando / encontro",
                "andava / encontrava",
              ],
            },
            {
              template: "Quando eu era criança, ___ (ir) à praia todo domingo.",
              answer: "ia",
              en: "When I was a kid, I used to go to the beach every Sunday. (habit → imperfeito)",
              options: ["ia", "fui", "vou", "irei"],
            },
            {
              template: "O ônibus ___ (chegar) atrasado ontem à noite.",
              answer: "chegou",
              en: "The bus arrived late last night. (single event → perfeito)",
              options: ["chegava", "chegou", "chega", "chegará"],
            },
            {
              template: "Eu ___ (estar) muito cansado quando ___ (chegar) no hotel.",
              answer: "estava / cheguei",
              en: "I was very tired when I arrived at the hotel. (state + event)",
              options: [
                "estive / chegava",
                "estava / cheguei",
                "estou / cheguei",
                "estava / chegava",
              ],
            },
            {
              template: "De repente ___ (começar) a chover e nós ___ (correr) pra dentro.",
              answer: "começou / corremos",
              en: "Suddenly it started to rain and we ran inside. (two events → perfeito)",
              options: [
                "começava / corríamos",
                "começou / corremos",
                "começava / corremos",
                "começou / corríamos",
              ],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the narrative",
          items: [
            { tokens: ["Era", "uma", "manhã", "fria", "de", "julho"], en: "It was a cold July morning." },
            { tokens: ["Saí", "cedo", "para", "pegar", "o", "ônibus"], en: "I left early to catch the bus." },
            { tokens: ["Enquanto", "eu", "esperava", ",", "começou", "a", "chover"], en: "While I was waiting, it started to rain." },
            { tokens: ["No", "final", ",", "cheguei", "no", "trabalho", "todo", "molhado"], en: "In the end, I arrived at work all wet." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it — mixing the two tenses",
          direction: "en-to-l1",
          prompt: "It was raining. I was having dinner when the phone rang. It was my mother.",
          reference: "Estava chovendo. Eu estava jantando quando o telefone tocou. Era a minha mãe.",
          hint: "Three imperfeito states (was raining, was having dinner, it was — description) + one event (rang → tocou). BR uses estar + gerúndio for 'was -ing'.",
        },
        {
          type: "tip",
          heading: "Estar + gerúndio for 'was/were -ing'",
          body: "To stress an action in progress, Brazil uses <em>estar + gerúndio</em>: <em>estava jantando</em> = I was having dinner. (<em>Jantava</em> also works but is less vivid.) Make the gerúndio by swapping the infinitive ending: -ar → -ando, -er → -endo, -ir → -indo. So <em>falar → falando, comer → comendo, dormir → dormindo</em>. Portugal would say <em>estava a jantar</em> instead.",
        },
      ],
    },
    {
      slug: "narrate-write-your-own",
      title: "Write your own trip story",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "Time to put it all together",
          body: [
            "This lesson is mostly translation practice — you'll build a short trip story piece by piece using both past tenses.",
            "Story setup: \"A weekend trip to Paraty.\" You'll translate sentences that, together, form one complete narrative.",
            "Lean on the Brazilian model under each one — these are graded by Claude, so you'll get feedback if you drift off-track.",
          ],
        },
        {
          type: "translate",
          heading: "Scene-setting (use imperfeito)",
          direction: "en-to-l1",
          prompt: "It was a Saturday morning in June. The weather was beautiful and I was happy.",
          reference: "Era um sábado de manhã em junho. O tempo estava lindo e eu estava feliz.",
          hint: "All description = imperfeito. 'The weather was beautiful' = O tempo estava lindo. 'I was happy' = eu estava feliz.",
        },
        {
          type: "translate",
          heading: "First event (pretérito perfeito)",
          direction: "en-to-l1",
          prompt: "I took the bus from Rio at seven. The trip lasted four hours.",
          reference: "Peguei o ônibus do Rio às sete. A viagem durou quatro horas.",
          hint: "Two completed events: peguei (pegar) + durou (durar). In BR, 'to take a bus' = pegar o ônibus.",
        },
        {
          type: "translate",
          heading: "On arrival (mix of tenses)",
          direction: "en-to-l1",
          prompt: "When I arrived in Paraty, it was hot. I left the bus station and walked to the historic center.",
          reference: "Quando cheguei em Paraty, estava calor. Saí da rodoviária e fui andando até o centro histórico.",
          hint: "Arrived (event → cheguei) + it was hot (background → estava calor) + left (event → saí) + walked (event). 'Bus station' = rodoviária.",
        },
        {
          type: "translate",
          heading: "Background detail (imperfeito)",
          direction: "en-to-l1",
          prompt: "While I was walking, I was looking at the old houses and listening to music.",
          reference: "Enquanto eu andava, eu olhava as casas antigas e escutava música.",
          hint: "Three simultaneous ongoing actions = three imperfeitos: andava, olhava, escutava.",
        },
        {
          type: "translate",
          heading: "Sudden event (pretérito perfeito)",
          direction: "en-to-l1",
          prompt: "Suddenly I saw a small restaurant by the sea. I decided to go in.",
          reference: "De repente eu vi um restaurante pequeno perto do mar. Decidi entrar.",
          hint: "Two events: vi (ver) + decidi (decidir). 'Suddenly' = de repente. 'By the sea' = perto do mar.",
        },
        {
          type: "translate",
          heading: "The meal (mix)",
          direction: "en-to-l1",
          prompt: "I ate fresh fish with rice and beans. It was the best meal of the trip.",
          reference: "Comi peixe fresco com arroz e feijão. Foi a melhor refeição da viagem.",
          hint: "Comi (event → perfeito). 'It was' here = foi (one specific, completed meal → pretérito perfeito, NOT era).",
        },
        {
          type: "translate",
          heading: "Conclusion (present + future)",
          direction: "en-to-l1",
          prompt: "I love Paraty. Next month I'll definitely go back.",
          reference: "Eu amo Paraty. No mês que vem eu vou voltar com certeza.",
          hint: "'I love' = eu amo (present). Future: 'vou voltar' = I'm going to go back. 'Definitely' = com certeza.",
        },
        {
          type: "tip",
          heading: "Congratulations — you can narrate now",
          body: "You just told a seven-sentence story using two past tenses, agreement, and connector words. That's real B1-level narrative skill in Brazilian Portuguese. From here you can describe any past trip, weekend, or memory naturally. The next stages add nuance (formal você/o senhor, conditional, subjuntivo) — but the structural heavy lifting is done.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'It was raining' (background) =",
        options: ["Choveu", "Estava chovendo", "Chove", "Vai chover"],
        correct: 1,
      },
      {
        q: "'I went home' (single completed event) =",
        options: ["Eu ia para casa", "Eu fui para casa", "Eu vou para casa", "Eu irei para casa"],
        correct: 1,
      },
      {
        q: "'While I was eating, the phone rang' =",
        options: [
          "Enquanto eu comia, o telefone tocou.",
          "Enquanto eu comi, o telefone tocava.",
          "Enquanto eu comia, o telefone tocava.",
          "Enquanto eu comi, o telefone tocou.",
        ],
        correct: 0,
      },
      {
        q: "Brazilian for 'I was having dinner' (emphatic) =",
        options: [
          "Eu jantei",
          "Eu estava jantando",
          "Eu estava a jantar",
          "Eu jantarei",
        ],
        correct: 1,
      },
      {
        q: "The gerúndio of 'comer' is…",
        options: ["comando", "comendo", "comindo", "comia"],
        correct: 1,
      },
      {
        q: "'When I was a kid, I lived in Salvador' (habit/state) =",
        options: [
          "Quando eu era criança, morei em Salvador.",
          "Quando eu era criança, morava em Salvador.",
          "Quando eu fui criança, morava em Salvador.",
          "Quando eu era criança, moro em Salvador.",
        ],
        correct: 1,
      },
      {
        q: "'Suddenly' =",
        options: ["enquanto", "de repente", "logo", "sempre"],
        correct: 1,
      },
      {
        q: "Storyteller's connector for 'then / afterward' =",
        options: ["enquanto", "depois", "porque", "no início"],
        correct: 1,
      },
      {
        q: "'I was tired when I arrived' (state + event) =",
        options: [
          "Estive cansado quando chegava.",
          "Estava cansado quando cheguei.",
          "Estive cansado quando cheguei.",
          "Estava cansado quando chegava.",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'It was a beautiful day. I went out at 10 and walked for two hours.'",
        options: [
          "Era um dia lindo. Saí às dez e andei por duas horas.",
          "Foi um dia lindo. Saía às dez e andava por duas horas.",
          "Era um dia lindo. Saía às dez e andava por duas horas.",
          "Foi um dia lindo. Saí às dez e andei por duas horas.",
        ],
        correct: 0,
      },
    ],
  },
};
