import type { Unit } from "../../types";

export const UNIT_SHOPPING: Unit = {
  slug: "shopping",
  stage: 6,
  order: 25,
  icon: "🛍️",
  title: "Money & shopping",
  tagline: "Quanto custa? desconto, posso pagar com cartão?",
  badge: "tourist",
  lessons: [
    {
      slug: "shopping-money-basics",
      title: "Talking about money",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Reais, centavos, and 'quanto custa?'",
          body: [
            "Brazil uses the <strong>real (R$)</strong>, plural <em>reais</em>. Cents = <em>centavos</em>. R$4,50 is said <em>quatro reais e cinquenta</em> — Brazilians usually drop the word 'centavos'. R$3,99 = <em>três reais e noventa e nove</em>. (Note the comma: Brazil writes <em>R$4,50</em>, not 4.50.)",
            "Asking the price: <em>«Quanto custa?»</em> (one item) or <em>«Quanto custam?»</em> (plural). At the register you'll also hear <em>«Quanto é?»</em> and <em>«Quanto deu?»</em> = how much is it / how much was it (total).",
            "Discounts: <em>desconto</em> = discount. <em>Em promoção</em> = on offer / on sale. <em>Liquidação</em> = a clearance sale (whole store marked down). <em>Oferta</em> = a special deal.",
            "<em>Caro</em> = expensive. <em>Barato</em> = cheap. <em>Em conta</em> = good value / affordable.",
          ],
          keyPoint:
            "Quanto custa? (singular) / custam? (plural). Desconto = discount. Caro = expensive, barato = cheap. R$X,YY said as 'X reais e YY'.",
        },
        {
          type: "vocab",
          heading: "Money & price vocabulary",
          items: [
            { l1: "o real / os reais", en: "the real / reais (currency)", note: "R$ — Brazil's currency" },
            { l1: "os centavos", en: "cents" },
            { l1: "o preço", en: "the price" },
            { l1: "quanto custa?", en: "how much does it cost? (singular)" },
            { l1: "quanto custam?", en: "how much do they cost? (plural)" },
            { l1: "quanto é?", en: "how much is it?" },
            { l1: "quanto deu?", en: "how much was it (total)?" },
            { l1: "o desconto", en: "discount" },
            { l1: "em promoção", en: "on sale / on offer" },
            { l1: "a liquidação", en: "clearance sale" },
            { l1: "caro / barato", en: "expensive / cheap" },
            { l1: "em conta", en: "good value / affordable" },
            { l1: "o troco", en: "the change (money returned)" },
            { l1: "a nota fiscal / o cupom", en: "the receipt / sales slip" },
            { l1: "dinheiro", en: "cash / money" },
            { l1: "a maquininha", en: "card-payment machine (BR slang)" },
          ],
        },
        {
          type: "tip",
          heading: "Pix — Brazil's instant payment everyone uses",
          body: "Beyond cash and cards, Brazil runs on <em>Pix</em> — a free, instant bank transfer you make from a phone app by scanning a QR code or entering a <em>chave Pix</em> (phone, email, or CPF). Small shops, market stalls, even street vendors take it. Ask <em>«Aceita Pix?»</em> ('Do you take Pix?') — the answer is almost always yes. (Portugal uses <em>MB WAY</em> for something similar.)",
          example: { l1: "Posso pagar no Pix?", en: "Can I pay with Pix?" },
        },
        {
          type: "multipleChoice",
          heading: "Price talk",
          questions: [
            {
              q: "'How much does it cost?' (singular item) =",
              options: ["Quanto deu?", "Quanto custa?", "Quanto custam?", "Quanto são?"],
              correct: 1,
              fb: "Quanto custa? for one item; quanto custam? for plural.",
            },
            {
              q: "'On sale / on offer' =",
              options: ["em conta", "em promoção", "caro", "no troco"],
              correct: 1,
              fb: "Em promoção = on offer. Liquidação is a bigger clearance sale.",
            },
            {
              q: "'Cheap' =",
              options: ["caro", "barato", "preço", "desconto"],
              correct: 1,
              fb: "Barato = cheap; caro = expensive.",
            },
            {
              q: "The change you get back from cash is…",
              options: ["o desconto", "o troco", "o preço", "a nota"],
              correct: 1,
              fb: "O troco = the change handed back to you.",
            },
            {
              q: "R$4,50 is said…",
              options: [
                "quatro ponto cinquenta",
                "quatro vírgula cinco",
                "quatro reais e cinquenta",
                "quatro reais cinquenta centavos — and only that",
              ],
              correct: 2,
              fb: "'Quatro reais e cinquenta' — Brazilians drop 'centavos' in speech.",
            },
          ],
        },
      ],
    },
    {
      slug: "shopping-clothes",
      title: "Clothes shopping",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Trying on, sizes, colors",
          body: [
            "<em>«Posso experimentar?»</em> = Can I try it on? You can add the object: <em>«Posso experimentar essa blusa?»</em>",
            "<em>«Que tamanho você usa?»</em> = What size do you wear? Brazilian sizes run P, M, G, GG (pequeno, médio, grande, extra-grande) or numeric (36–46). Shoe sizes (<em>número</em>) run ~33–44.",
            "<em>«Ficou grande / pequeno em mim»</em> = It came out big / small on me. <em>«Ficou apertado / folgado»</em> = It's tight / loose.",
            "<em>«Vou levar»</em> = I'll take it (literally 'I'll take/carry it'). This is the everyday way to say you'll buy something.",
            "<em>«Onde fica o provador?»</em> = Where's the fitting room?",
          ],
          keyPoint:
            "Experimentar = to try on. Tamanho = size, número = shoe size. Ficou grande/pequeno = it's big/small. 'Vou levar' = I'll take it.",
        },
        {
          type: "vocab",
          heading: "Clothes",
          items: [
            { l1: "a roupa", en: "clothes / clothing" },
            { l1: "a camiseta", en: "a t-shirt" },
            { l1: "a camisa", en: "a (button-up) shirt" },
            { l1: "a blusa", en: "a top / blouse" },
            { l1: "o suéter / o casaco", en: "a sweater / a coat" },
            { l1: "o vestido", en: "a dress" },
            { l1: "a calça", en: "trousers / pants", note: "Singular in BR: uma calça = one pair" },
            { l1: "a calça jeans", en: "jeans" },
            { l1: "a saia", en: "a skirt" },
            { l1: "a jaqueta", en: "a jacket" },
            { l1: "o sapato / o tênis", en: "shoe / sneakers" },
            { l1: "a sandália", en: "sandal" },
            { l1: "o chinelo", en: "flip-flop", note: "Havaianas territory" },
            { l1: "o boné / o chapéu", en: "cap / hat" },
            { l1: "o cinto", en: "a belt" },
          ],
        },
        {
          type: "vocab",
          heading: "Colors & sizes",
          items: [
            { l1: "branco / preto / cinza", en: "white / black / gray" },
            { l1: "vermelho / azul / verde", en: "red / blue / green" },
            { l1: "amarelo / laranja", en: "yellow / orange" },
            { l1: "rosa / roxo", en: "pink / purple" },
            { l1: "marrom / bege", en: "brown / beige" },
            { l1: "o tamanho", en: "size (clothes)" },
            { l1: "o número", en: "size (shoes)" },
            { l1: "apertado / folgado", en: "tight / loose" },
            { l1: "curto / comprido", en: "short / long" },
            { l1: "um número maior / menor", en: "a size up / down" },
          ],
        },
        {
          type: "dialogue",
          heading: "At a clothing store",
          setup: "You're looking at a top on a rack.",
          lines: [
            { speaker: "Vendedora", l1: "Oi! Posso ajudar?", en: "Hi! Can I help?" },
            { speaker: "Você", l1: "Oi. Gostei desta blusa. Vocês têm no meu tamanho?", en: "Hi. I like this top. Do you have it in my size?" },
            { speaker: "Vendedora", l1: "Que tamanho você usa?", en: "What size do you wear?" },
            { speaker: "Você", l1: "Normalmente M. Posso experimentar?", en: "Usually M. Can I try it on?" },
            { speaker: "Vendedora", l1: "Claro, o provador é ali no fundo.", en: "Of course, the fitting room is over there at the back." },
            { speaker: "Você", l1: "(depois) Ficou um pouco apertada. Tem um número maior?", en: "(later) It came out a bit tight. Do you have a size up?" },
            { speaker: "Vendedora", l1: "Tenho sim, aqui está o G.", en: "Yes I do, here's the G (L)." },
            { speaker: "Você", l1: "Essa ficou ótima. Vou levar. Quanto custa?", en: "This one's perfect. I'll take it. How much is it?" },
            { speaker: "Vendedora", l1: "Setenta e nove reais. Está em promoção, com dez por cento de desconto.", en: "Seventy-nine reais. It's on sale, with ten percent off." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Shopping fill",
          items: [
            {
              template: "Que ___ você usa? (clothes)",
              answer: "tamanho",
              en: "What size do you wear?",
              options: ["tamanho", "número", "preço", "troco"],
            },
            {
              template: "Posso ___ esta blusa?",
              answer: "experimentar",
              en: "Can I try this top on?",
              options: ["levar", "experimentar", "pagar", "custar"],
            },
            {
              template: "Ficou um pouco ___ . Tem um número maior?",
              answer: "apertado",
              en: "It's a bit tight. Do you have a size up?",
              options: ["apertado", "folgado", "curto", "barato"],
            },
            {
              template: "Está com vinte por cento de ___ ?",
              answer: "desconto",
              en: "Is it 20% off?",
              options: ["desconto", "troco", "preço", "promoção"],
            },
            {
              template: "Gostei muito. ___ levar.",
              answer: "Vou",
              en: "I really like it. I'll take it.",
              options: ["Vou", "Quero", "Posso", "Tenho"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I like this jacket. Do you have it in black, size M?",
          reference: "Gostei desta jaqueta. Vocês têm em preto, tamanho M?",
          hint: "'Gostei de' = I like (lit. 'I liked'). 'Do you have' to a shop = 'vocês têm'. 'In black' = em preto.",
        },
      ],
    },
    {
      slug: "shopping-pay",
      title: "Paying — card, cash, installments",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The payment script",
          body: [
            "<em>«Posso pagar com cartão?»</em> = Can I pay by card? Reply you'll hear: <em>«Débito ou crédito?»</em> = debit or credit?",
            "<em>«Vou pagar à vista.»</em> = I'll pay in full (cash or one card charge, no installments). <em>«Em dinheiro»</em> = with cash.",
            "<em>«Posso parcelar?»</em> = Can I pay in installments? <em>«Em quantas vezes?»</em> = In how many installments? You answer e.g. <em>«Em 3 vezes»</em> (in 3) — see the next tip.",
            "<em>«Aceita Pix?»</em> = Do you take Pix? Often gets you a small discount.",
            "<em>«Pode me dar a nota fiscal / o cupom?»</em> = Can you give me the receipt?",
          ],
          keyPoint:
            "Pagar com cartão / em dinheiro / no Pix. À vista = in full. Parcelar = pay in installments. 'Em quantas vezes?' = how many installments.",
        },
        {
          type: "tip",
          heading: "Parcelar — Brazil's installment culture",
          body: "In Brazil it's completely normal to split almost any purchase — clothes, a phone, even groceries — into monthly installments on a credit card. You'll see prices advertised as <em>«em 3x sem juros»</em> ('in 3 payments, interest-free') or <em>«10x de R$50»</em> ('10 payments of R$50'). <em>x</em> is read <em>vezes</em> ('times'). <em>Sem juros</em> = no interest; <em>com juros</em> = with interest. Paying <em>à vista</em> (in full) sometimes earns a discount, so it's worth asking. This installment habit is much stronger in Brazil than in Portugal.",
          example: { l1: "Pode parcelar em 3x sem juros?", en: "Can I split it into 3 interest-free payments?" },
        },
        {
          type: "vocab",
          heading: "Payment vocabulary",
          items: [
            { l1: "pagar", en: "to pay" },
            { l1: "o cartão de crédito / de débito", en: "credit / debit card" },
            { l1: "em dinheiro", en: "in cash" },
            { l1: "no Pix", en: "via Pix (instant transfer)", note: "BR — see lesson 1 tip" },
            { l1: "à vista", en: "paid in full (no installments)" },
            { l1: "parcelar / parcelado", en: "to split into installments / in installments" },
            { l1: "em quantas vezes?", en: "in how many installments?" },
            { l1: "sem juros / com juros", en: "interest-free / with interest" },
            { l1: "a maquininha", en: "the card machine (BR slang)" },
            { l1: "a senha", en: "the PIN" },
            { l1: "o troco", en: "the change" },
            { l1: "a nota fiscal / o cupom", en: "receipt / sales slip" },
            { l1: "a garantia", en: "warranty" },
            { l1: "a troca / o reembolso", en: "exchange / refund" },
          ],
        },
        {
          type: "dialogue",
          heading: "Paying for a phone",
          setup: "You're at the counter buying a new celular (cell phone).",
          lines: [
            { speaker: "Caixa", l1: "Então, um celular. Deu mil e duzentos reais.", en: "So, one phone. That came to twelve hundred reais." },
            { speaker: "Você", l1: "Posso pagar com cartão?", en: "Can I pay by card?" },
            { speaker: "Caixa", l1: "Pode. Débito ou crédito?", en: "Sure. Debit or credit?" },
            { speaker: "Você", l1: "Crédito. Dá para parcelar?", en: "Credit. Can I pay in installments?" },
            { speaker: "Caixa", l1: "Dá sim. Em quantas vezes?", en: "Yes you can. In how many installments?" },
            { speaker: "Você", l1: "Em três vezes, sem juros, se puder.", en: "In three, interest-free, if possible." },
            { speaker: "Caixa", l1: "Perfeito, 3x sem juros. Digite a senha, por favor.", en: "Perfect, 3x interest-free. Enter your PIN, please." },
            { speaker: "Você", l1: "Pronto. Pode me dar a nota fiscal?", en: "Done. Can you give me the receipt?" },
            { speaker: "Caixa", l1: "Claro. Guarde a nota para a garantia.", en: "Of course. Keep the receipt for the warranty." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Pay-up fill",
          items: [
            {
              template: "Posso ___ com cartão?",
              answer: "pagar",
              en: "Can I pay by card?",
              options: ["pagar", "levar", "custar", "trocar"],
            },
            {
              template: "Vou pagar à ___ , sem parcelar.",
              answer: "vista",
              en: "I'll pay in full, without installments.",
              options: ["vista", "prazo", "troco", "conta"],
            },
            {
              template: "Dá para parcelar em quantas ___ ?",
              answer: "vezes",
              en: "How many installments can I split it into?",
              options: ["vezes", "notas", "senhas", "trocas"],
            },
            {
              template: "Pode me dar a ___ fiscal, por favor?",
              answer: "nota",
              en: "Can you give me the receipt, please?",
              options: ["nota", "senha", "troca", "garantia"],
            },
            {
              template: "Aceita ___ ? Às vezes tem desconto.",
              answer: "Pix",
              en: "Do you take Pix? Sometimes there's a discount.",
              options: ["Pix", "juros", "troco", "vezes"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Can I pay by card? Can I split it into three interest-free payments?",
          reference: "Posso pagar com cartão? Dá para parcelar em três vezes sem juros?",
          hint: "'Dá para + infinitive' = 'is it possible to…'. 'In three (installments)' = em três vezes. 'Interest-free' = sem juros.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'How much does it cost?' (singular) =",
        options: ["Quanto custam?", "Quanto deu?", "Quanto custa?", "Quanto vezes?"],
        correct: 2,
      },
      {
        q: "'On sale / on offer' =",
        options: ["em conta", "em promoção", "à vista", "sem juros"],
        correct: 1,
      },
      {
        q: "'What size do you wear?' (clothes) =",
        options: [
          "Que número você usa?",
          "Que tamanho você usa?",
          "Quanto você usa?",
          "Que troco você usa?",
        ],
        correct: 1,
      },
      {
        q: "'Can I try it on?' =",
        options: ["Posso levar?", "Posso experimentar?", "Posso parcelar?", "Posso pagar?"],
        correct: 1,
      },
      {
        q: "'It came out tight on me' =",
        options: ["Ficou folgado.", "Ficou apertado.", "Ficou barato.", "Ficou em conta."],
        correct: 1,
      },
      {
        q: "'I'll take it' (deciding to buy) =",
        options: ["Vou experimentar.", "Vou levar.", "Vou trocar.", "Vou parcelar."],
        correct: 1,
      },
      {
        q: "'Receipt' (for the warranty / a return) =",
        options: ["o troco", "a nota fiscal", "o desconto", "a senha"],
        correct: 1,
      },
      {
        q: "'I'll pay in cash' =",
        options: [
          "Vou pagar com cartão.",
          "Vou pagar em dinheiro.",
          "Vou parcelar.",
          "Vou pagar à vista no crédito.",
        ],
        correct: 1,
      },
      {
        q: "A price shown as '3x sem juros' means…",
        options: [
          "3% discount",
          "3 interest-free monthly installments",
          "valid for 3 days",
          "buy 3, pay for 1",
        ],
        correct: 1,
      },
      {
        q: "'Can I pay in installments?' =",
        options: [
          "Posso pagar à vista?",
          "Posso parcelar?",
          "Quanto custa?",
          "Aceita dinheiro?",
        ],
        correct: 1,
      },
    ],
  },
};
