import type { Unit } from "../../types";

export const UNIT_MARKET: Unit = {
  slug: "market",
  stage: 6,
  order: 26,
  icon: "🥕",
  title: "Market / feira",
  tagline: "Quilos, gramas, me vê um quilo de…",
  badge: "tourist",
  lessons: [
    {
      slug: "market-weights",
      title: "Weights and quantities",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Brazil buys food by the kilo, not the pound",
          body: [
            "At the Brazilian street market (<em>a feira</em>) and in the supermarket, everything is metric. Forget pounds — you'll hear three units constantly:",
            "<strong>O quilo</strong> (= 1 kg ≈ 2.2 lb). The everyday unit for fruit, veg, meat. <em>Um quilo de tomate</em> = a kilo of tomatoes. Note Brazilians often keep the food singular: <em>um quilo de tomate</em>, not 'tomates'.",
            "<strong>O grama</strong> (= gram). Used for smaller portions. <em>Duzentos gramas de queijo</em> = 200g of cheese. <em>Meio quilo</em> = 500g.",
            "<strong>A dúzia</strong> (= dozen, 12). Classic for eggs and bananas: <em>uma dúzia de ovos</em>. Half a dozen = <em>meia dúzia</em>.",
            "Fractions: <em>meio</em> (half), <em>um quarto</em> (a quarter). So <em>meio quilo</em>, <em>um quarto de quilo</em>.",
          ],
          keyPoint:
            "1 quilo = 1kg (fruit/veg/meat). 100 gramas = small portion. Uma dúzia = 12. Meio = half. Um quarto = a quarter.",
        },
        {
          type: "vocab",
          heading: "Weight & quantity",
          items: [
            { l1: "um quilo", en: "1 kilogram (1kg)", note: "The everyday unit at the feira" },
            { l1: "meio quilo", en: "half a kilo (500g)", note: "" },
            { l1: "um quarto de quilo", en: "a quarter kilo (250g)", note: "" },
            { l1: "cem gramas / duzentos gramas", en: "100g / 200g", note: "For cheese, cold cuts, small portions" },
            { l1: "uma dúzia / meia dúzia", en: "a dozen / half a dozen", note: "Eggs, bananas" },
            { l1: "um litro / meio litro", en: "1 liter / 500ml", note: "Liquids" },
            { l1: "uma sacola", en: "a (shopping) bag", note: "What you carry it all home in (BR)" },
            { l1: "um saquinho", en: "a little bag", note: "The thin plastic produce bag" },
            { l1: "um pacote", en: "a package / pack", note: "" },
            { l1: "uma fatia / duas fatias", en: "a slice / two slices", note: "" },
            { l1: "um pedaço", en: "a piece", note: "" },
            { l1: "um maço", en: "a bunch", note: "Of herbs, greens — um maço de cheiro-verde" },
            { l1: "um cacho", en: "a bunch / cluster", note: "Of grapes or bananas — um cacho de banana" },
            { l1: "um punhado", en: "a handful", note: "" },
          ],
        },
        {
          type: "tip",
          heading: "How an order sounds: 'me vê…'",
          body: "At a Brazilian feira the warmest, most local way to order is <em>«Me vê um quilo de banana, por favor.»</em> — literally 'show me / let me have a kilo of bananas.' It's friendly and ubiquitous. More neutral options: <em>«Eu queria meio quilo de tomate»</em> (I'd like…) or <em>«Me dá uma dúzia de ovos»</em> (give me…). The vendor will pick and weigh it for you.",
          example: { l1: "Me vê meio quilo de morango, por favor.", en: "Let me have half a kilo of strawberries, please." },
        },
        {
          type: "multipleChoice",
          heading: "Weight check",
          questions: [
            {
              q: "'Um quilo' equals…",
              options: ["100 grams", "1 kilogram", "1 pound", "12 units"],
              correct: 1,
              fb: "Um quilo = 1kg ≈ 2.2 lb. It's the everyday unit at the feira.",
            },
            {
              q: "You want 500g of tomatoes. You say…",
              options: ["um quarto de quilo", "meio quilo", "uma dúzia", "cem gramas"],
              correct: 1,
              fb: "Meio quilo = half a kilo = 500g.",
            },
            {
              q: "'Uma dúzia de ovos' is…",
              options: ["6 eggs", "10 eggs", "12 eggs", "a kilo of eggs"],
              correct: 2,
              fb: "Uma dúzia = a dozen = 12. Half that, meia dúzia, = 6.",
            },
            {
              q: "The warm, local way to order at the feira is…",
              options: ["Me vê um quilo de banana", "Quero comprar bananas", "Onde está a banana?", "A banana é boa?"],
              correct: 0,
              fb: "'Me vê…' (let me have / show me) is the friendly Brazilian market phrase.",
            },
          ],
        },
      ],
    },
    {
      slug: "market-buying-food",
      title: "Buying at the feira",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The feira livre — Brazil's open-air market",
          body: [
            "Once a week a street in the neighborhood fills with stalls (<em>as bancas</em>): the <em>feira livre</em>. Each vendor (<em>o feirante</em>) calls out prices, and you go banca to banca buying what's <em>fresquinho</em> (super fresh) that day.",
            "Ask the price by the kilo: <em>«Quanto está o quilo?»</em> or just <em>«Quanto é o quilo da maçã?»</em> Prices change week to week, so it's always worth asking.",
            "Tell the feirante when you'll eat it so they pick the right ripeness: <em>maduro</em> (ripe, for today) vs <em>mais verde</em> (greener, for later in the week). And there's almost always a free <em>xepa</em> deal at the end of the day when vendors clear stock cheap.",
          ],
          keyPoint:
            "Feira livre = weekly street market. Feirante = vendor, banca = stall. Ask 'Quanto está o quilo?' and say maduro (ripe) or mais verde (greener).",
        },
        {
          type: "vocab",
          heading: "At the feira & the market",
          items: [
            { l1: "a feira / a feira livre", en: "the (open-air street) market" },
            { l1: "a banca", en: "the stall" },
            { l1: "o feirante", en: "the market vendor" },
            { l1: "o mercado / o supermercado", en: "the market / the supermarket" },
            { l1: "o açougue / o açougueiro", en: "the butcher's / the butcher" },
            { l1: "a peixaria", en: "the fish shop" },
            { l1: "a padaria", en: "the bakery" },
            { l1: "a fruta", en: "fruit" },
            { l1: "a verdura / o legume", en: "leafy greens / vegetables" },
            { l1: "fresco / fresquinho", en: "fresh / nice and fresh", note: "The -inho makes it warmer, very BR" },
            { l1: "maduro", en: "ripe" },
            { l1: "mais verde", en: "greener / less ripe" },
            { l1: "orgânico", en: "organic" },
            { l1: "da estação / da época", en: "in season" },
            { l1: "o carrinho", en: "the shopping cart" },
            { l1: "a balança", en: "the scale" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the feira in São Paulo",
          setup: "You're at the fruit banca on a Saturday morning.",
          lines: [
            { speaker: "Você", l1: "Bom dia! Quanto está o quilo do tomate?", en: "Good morning! How much is a kilo of tomatoes?" },
            { speaker: "Feirante", l1: "Cinco reais o quilo, tá tudo fresquinho hoje.", en: "Five reais a kilo, it's all nice and fresh today." },
            { speaker: "Você", l1: "Me vê meio quilo, então. É pra hoje à noite.", en: "Let me have half a kilo, then. It's for tonight." },
            { speaker: "Feirante", l1: "Pra hoje? Levo esses aqui, bem maduros. Mais alguma coisa?", en: "For today? Take these here, nice and ripe. Anything else?" },
            { speaker: "Você", l1: "Uma dúzia de banana e um maço de cheiro-verde.", en: "A dozen bananas and a bunch of parsley-and-scallion." },
            { speaker: "Feirante", l1: "Prontinho. Dá oito e cinquenta no total.", en: "All set. That's eight fifty in total." },
            { speaker: "Você", l1: "Aqui está. Obrigado!", en: "Here you go. Thank you!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Market-stall fill",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "Quanto ___ o quilo da maçã?",
              answer: "está",
              en: "How much is a kilo of apples?",
              options: ["está", "tem", "vai", "faz"],
            },
            {
              template: "Me ___ meio quilo de uva, por favor.",
              answer: "vê",
              en: "Let me have half a kilo of grapes, please.",
              options: ["vê", "vou", "tem", "sou"],
            },
            {
              template: "Os tomates são pra hoje. Quero os mais ___ .",
              answer: "maduros",
              en: "The tomatoes are for today. I want the ripest.",
              options: ["maduros", "verdes", "frios", "caros"],
            },
            {
              template: "Uma ___ de ovos, por favor.",
              answer: "dúzia",
              en: "A dozen eggs, please.",
              options: ["dúzia", "fatia", "balança", "sacola"],
            },
            {
              template: "Está tudo ___ hoje? — Tá, chegou de manhã.",
              answer: "fresquinho",
              en: "Is everything nice and fresh today? — Yes, it arrived this morning.",
              options: ["fresquinho", "maduro", "caro", "verde"],
            },
          ],
        },
        {
          type: "tip",
          heading: "Feira, sacolão, quitanda — or just 'o mercado' (Portugal)",
          body: "Brazil has a whole vocabulary for buying produce: the weekly <em>feira livre</em> on the street, the cheap self-serve <em>sacolão</em>, and the small corner produce shop called a <em>quitanda</em>. In Portugal you're more likely to head to <em>o mercado</em> (a covered market hall) or <em>a praça</em>, and you won't hear 'sacolão' or 'quitanda' at all. The food and the metric units are the same — just the names of the places differ.",
          example: { l1: "BR: Vou na feira / no sacolão. · PT: Vou ao mercado.", en: "I'm going to the market." },
        },
        {
          type: "orderWords",
          heading: "Build the market sentence",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Quanto", "está", "o", "quilo", "da", "banana", "?"], en: "How much is a kilo of bananas?" },
            { tokens: ["Me", "vê", "meio", "quilo", "de", "tomate"], en: "Let me have half a kilo of tomatoes." },
            { tokens: ["É", "pra", "hoje", ",", "quero", "bem", "maduro"], en: "It's for today, I want it nice and ripe." },
            { tokens: ["Mais", "alguma", "coisa", "?", "—", "Não", ",", "só", "isso"], en: "Anything else? — No, just that." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Let me have a kilo of apples and a dozen eggs, please.",
          reference: "Me vê um quilo de maçã e uma dúzia de ovos, por favor.",
          hint: "Use the friendly 'Me vê…'. A kilo = um quilo; a dozen = uma dúzia. Brazilians often keep 'maçã' singular after a quantity.",
        },
      ],
    },
    {
      slug: "market-haggle-and-finish",
      title: "Haggling and wrapping up",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Pechinchar — the gentle art of the deal",
          body: [
            "At the feira (and street stalls in general) a little friendly bargaining, <em>pechinchar</em>, is normal and expected — especially near closing time. It's light and good-humored, not aggressive.",
            "Openers: <em>«Faz por menos?»</em> (will you do it for less?), <em>«Tá caro…»</em> (that's pricey…), <em>«Dá um desconto?»</em> (can you give a discount?), and the classic combo move <em>«Se eu levar dois, quanto fica?»</em> (if I take two, how much?).",
            "Bulk and the end-of-day clear-out (<em>a xepa</em>) are where the deals live. And when you're done, the wrap-up phrase is <em>«Só isso»</em> (just that) or <em>«É só, obrigado»</em>.",
          ],
          keyPoint:
            "Pechinchar = haggle (light & friendly). 'Faz por menos?' / 'Dá um desconto?' to ask; 'Só isso' to finish.",
        },
        {
          type: "vocab",
          heading: "Haggling & finishing up",
          items: [
            { l1: "pechinchar", en: "to haggle / bargain" },
            { l1: "a pechincha", en: "a bargain / good deal" },
            { l1: "Quanto fica?", en: "How much will it be?" },
            { l1: "Faz por menos?", en: "Will you do it for less?" },
            { l1: "Dá um desconto?", en: "Can you give a discount?" },
            { l1: "Tá caro", en: "That's expensive (casual)" },
            { l1: "Tá barato", en: "That's cheap" },
            { l1: "Mais alguma coisa?", en: "Anything else?", note: "What the vendor asks you" },
            { l1: "Só isso", en: "Just that / that's all" },
            { l1: "É tudo, obrigado", en: "That's everything, thanks" },
            { l1: "Aceita cartão?", en: "Do you take card?", note: "Many feirantes only take cash or Pix" },
            { l1: "o troco", en: "the change (money back)" },
          ],
        },
        {
          type: "dialogue",
          heading: "Closing the deal",
          setup: "It's late morning and the feirante wants to sell before packing up.",
          lines: [
            { speaker: "Você", l1: "Quanto está o quilo da manga?", en: "How much is a kilo of mangoes?" },
            { speaker: "Feirante", l1: "Seis reais o quilo.", en: "Six reais a kilo." },
            { speaker: "Você", l1: "Tá um pouco caro… faz por menos se eu levar dois quilos?", en: "That's a bit pricey… will you do less if I take two kilos?" },
            { speaker: "Feirante", l1: "Pode ser. Dois quilos por dez. Fechado?", en: "Could be. Two kilos for ten. Deal?" },
            { speaker: "Você", l1: "Fechado! Me vê os dois quilos, então.", en: "Deal! Let me have the two kilos, then." },
            { speaker: "Feirante", l1: "Mais alguma coisa?", en: "Anything else?" },
            { speaker: "Você", l1: "Não, só isso. Aceita Pix?", en: "No, just that. Do you take Pix?" },
            { speaker: "Feirante", l1: "Aceito. Aqui está o seu troco — obrigado!", en: "I do. Here's your change — thanks!" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Haggle check",
          questions: [
            {
              q: "'Pechinchar' means…",
              options: ["to weigh", "to haggle / bargain", "to wrap up", "to pay by card"],
              correct: 1,
              fb: "Pechinchar = to bargain. The good deal you land is uma pechincha.",
            },
            {
              q: "You think the price is too high. You can say…",
              options: ["Tá barato", "Só isso", "Tá caro, faz por menos?", "Mais alguma coisa?"],
              correct: 2,
              fb: "'Tá caro, faz por menos?' = it's pricey, will you do it for less? A standard, friendly opener.",
            },
            {
              q: "The feirante asks 'Mais alguma coisa?'. To finish, you say…",
              options: ["Quanto fica?", "Só isso, obrigado", "Faz por menos?", "Dá um desconto?"],
              correct: 1,
              fb: "Só isso = just that. The natural way to wrap up your order.",
            },
            {
              q: "Many Brazilian feirantes prefer payment by…",
              options: ["only credit card", "cash or Pix", "check", "foreign currency"],
              correct: 1,
              fb: "Plenty of stalls are cash- or Pix-only — worth asking 'Aceita cartão?' first.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Finish the exchange",
          items: [
            {
              template: "Tá caro… ___ por menos?",
              answer: "faz",
              en: "That's pricey… will you do it for less?",
              options: ["faz", "vê", "dá", "tem"],
            },
            {
              template: "Se eu levar dois quilos, quanto ___ ?",
              answer: "fica",
              en: "If I take two kilos, how much will it be?",
              options: ["fica", "está", "faz", "vai"],
            },
            {
              template: "Não, ___ isso. É tudo.",
              answer: "só",
              en: "No, just that. That's everything.",
              options: ["só", "mais", "muito", "bem"],
            },
            {
              template: "Você ___ cartão ou só dinheiro?",
              answer: "aceita",
              en: "Do you take card or only cash?",
              options: ["aceita", "paga", "dá", "leva"],
            },
            {
              template: "Aqui está o seu ___ . Obrigado!",
              answer: "troco",
              en: "Here's your change. Thanks!",
              options: ["troco", "saco", "quilo", "desconto"],
            },
          ],
        },
        {
          type: "pronounce",
          heading: "Say it aloud",
          items: [
            { l1: "Quanto está o quilo?", en: "How much is a kilo?", tip: "KWAN-too es-TAH oo KEE-loo" },
            { l1: "Me vê um quilo", en: "Let me have a kilo", tip: "mee VEH oong KEE-loo" },
            { l1: "Fresquinho", en: "Nice and fresh", tip: "fres-KEEN-yoo (the -nho is a soft 'ny')" },
            { l1: "Faz por menos?", en: "Will you do it for less?", tip: "fahz poor MEH-noos" },
            { l1: "Só isso, obrigado", en: "Just that, thanks", tip: "saw EE-soo oh-bree-GAH-doo" },
          ],
        },
        {
          type: "translate",
          heading: "Translate the haggle",
          direction: "en-to-l1",
          prompt: "That's a bit expensive. If I take two kilos, how much will it be?",
          reference: "Tá um pouco caro. Se eu levar dois quilos, quanto fica?",
          hint: "Use casual 'tá' for 'it's'. 'How much will it be?' = quanto fica?",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'Um quilo' =",
        options: ["100g", "1 kilogram", "1 pound", "12 units"],
        correct: 1,
      },
      {
        q: "'500 grams' in everyday Brazilian Portuguese =",
        options: ["um quarto de quilo", "meio quilo", "uma dúzia", "cem gramas"],
        correct: 1,
      },
      {
        q: "'Uma dúzia de ovos' =",
        options: ["6 eggs", "10 eggs", "12 eggs", "a kilo of eggs"],
        correct: 2,
      },
      {
        q: "The warm, local way to order at the feira is…",
        options: ["Me vê um quilo de banana", "Onde fica a banana?", "A banana é boa?", "Quero ver a banana"],
        correct: 0,
      },
      {
        q: "'O feirante' is…",
        options: ["the scale", "the stall", "the market vendor", "the shopping bag"],
        correct: 2,
      },
      {
        q: "To ask the price by weight, you say…",
        options: ["Quanto está o quilo?", "Onde está o quilo?", "Quem tem o quilo?", "Por que o quilo?"],
        correct: 0,
      },
      {
        q: "'Fresquinho' means…",
        options: ["expensive", "ripe", "nice and fresh", "frozen"],
        correct: 2,
      },
      {
        q: "'Pechinchar' means…",
        options: ["to weigh", "to haggle / bargain", "to pay by card", "to wrap up"],
        correct: 1,
      },
      {
        q: "The vendor asks 'Mais alguma coisa?'. To finish, you say…",
        options: ["Quanto fica?", "Só isso, obrigado", "Faz por menos?", "Tá caro"],
        correct: 1,
      },
      {
        q: "In Portugal you'd more likely shop at… (Brazil says feira / sacolão)",
        options: ["o sacolão", "a quitanda", "o mercado / a praça", "a feira livre"],
        correct: 2,
      },
    ],
  },
};
