import type { Unit } from "../../types";

export const UNIT_MUSEUMS: Unit = {
  slug: "museums",
  stage: 7,
  order: 31,
  icon: "🖼️",
  title: "Museums & art talk",
  tagline: "Quadro, exposição, meia-entrada, Niemeyer, Portinari.",
  badge: "culture",
  lessons: [
    {
      slug: "museums-art-vocab",
      title: "Talking about art",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "A bigger vocabulary unlocks a better visit",
          body: [
            "Art words let you read the plaques (the <em>legenda</em> next to each piece), follow a guide, and chat with locals about an exhibition.",
            "<strong>Materials & techniques:</strong> <em>óleo sobre tela</em> (oil on canvas), <em>aquarela</em> (watercolor), <em>afresco</em> (fresco), <em>escultura em mármore / bronze</em> (marble / bronze sculpture), <em>gravura</em> (engraving / print), <em>desenho</em> (drawing).",
            "<strong>Periods & movements:</strong> <em>colonial, barroco, neoclássico, romântico, moderno, modernismo, contemporâneo</em>. Brazil's own landmark is <em>o modernismo</em> — kicked off by the 1922 Semana de Arte Moderna in São Paulo.",
          ],
          keyPoint:
            "Materials (óleo, aquarela, mármore, bronze) + periods (barroco, modernismo, contemporâneo) + verbs (representa, retrata) cover most plaques.",
        },
        {
          type: "vocab",
          heading: "Art techniques & forms",
          items: [
            { l1: "a obra (de arte)", en: "work (of art)" },
            { l1: "o quadro / a pintura", en: "painting" },
            { l1: "o óleo sobre tela", en: "oil on canvas" },
            { l1: "a aquarela", en: "watercolor" },
            { l1: "o afresco", en: "fresco (paint on wet plaster)" },
            { l1: "o mosaico", en: "mosaic" },
            { l1: "a escultura", en: "sculpture" },
            { l1: "o mármore / o bronze", en: "marble / bronze" },
            { l1: "o desenho", en: "drawing" },
            { l1: "a gravura", en: "engraving / print" },
            { l1: "a moldura", en: "the frame" },
            { l1: "a tela", en: "the canvas" },
            { l1: "o restauro / o restauração", en: "restoration", note: "a restauração is the more common form" },
            { l1: "o retrato", en: "portrait" },
            { l1: "o autorretrato", en: "self-portrait" },
            { l1: "a paisagem", en: "landscape" },
            { l1: "a natureza-morta", en: "still life" },
            { l1: "a cena religiosa / mitológica", en: "religious / mythological scene" },
          ],
        },
        {
          type: "vocab",
          heading: "Talking about a piece",
          items: [
            { l1: "retrata / representa", en: "depicts / represents" },
            { l1: "é marcado/a por…", en: "is marked / characterized by…" },
            { l1: "as cores / a cor", en: "the colors / color" },
            { l1: "a luz / a sombra", en: "light / shadow" },
            { l1: "a perspectiva", en: "perspective" },
            { l1: "a composição", en: "composition" },
            { l1: "a pincelada", en: "the brushstroke" },
            { l1: "o estilo", en: "the style" },
            { l1: "o tema / o assunto", en: "the subject / theme" },
            { l1: "o/a artista", en: "artist (m / f same form)" },
            { l1: "o pintor / a pintora", en: "painter (m / f)" },
            { l1: "o escultor / a escultora", en: "sculptor" },
            { l1: "ser influenciado/a por…", en: "to be influenced by…" },
            { l1: "pertencer a (movimento, escola)", en: "to belong to (movement, school)" },
          ],
        },
        {
          type: "tip",
          heading: "Big Brazilian artists to recognize",
          body: "<strong>Modernismo:</strong> Tarsila do Amaral (her <em>Abaporu</em>, 1928, sparked the Antropofagia movement), Anita Malfatti, Di Cavalcanti (sensual carnival scenes), Cândido Portinari (his <em>Os Retirantes</em> and the UN murals — Brazil's most internationally known painter). <strong>Barroco mineiro:</strong> Aleijadinho, the sculptor of Congonhas. <strong>Contemporâneo:</strong> Beatriz Milhazes, Romero Britto (love him or hate him). Architecture is its own art here: <strong>Oscar Niemeyer</strong> shaped Brasília and designed the MAC in Niterói and the Museu do Amanhã's neighbor landmarks.",
          example: { l1: "A Tarsila do Amaral é a pintora mais famosa do modernismo.", en: "Tarsila do Amaral is the most famous painter of modernism." },
        },
        {
          type: "multipleChoice",
          heading: "Art quiz",
          questions: [
            {
              q: "'Oil on canvas' =",
              options: ["aquarela", "óleo sobre tela", "afresco", "gravura"],
              correct: 1,
              fb: "Óleo sobre tela = oil on canvas — the line you'll see on most plaques.",
            },
            {
              q: "Tarsila do Amaral is associated with…",
              options: ["Baroque sculpture", "Brazilian modernismo", "colonial portraits", "Byzantine mosaics"],
              correct: 1,
              fb: "Tarsila do Amaral was central to modernismo; her Abaporu (1928) launched the Antropofagia movement.",
            },
            {
              q: "'Sculpture in bronze' =",
              options: ["escultura em mármore", "escultura em bronze", "escultura em pedra", "escultura em madeira"],
              correct: 1,
              fb: "Em bronze = in bronze. Mármore = marble, pedra = stone, madeira = wood.",
            },
            {
              q: "Cândido Portinari is best known as…",
              options: ["an architect", "Brazil's most internationally known painter", "a watercolorist only", "a sculptor"],
              correct: 1,
              fb: "Portinari painted Os Retirantes and the UN War & Peace murals — Brazil's most globally recognized painter.",
            },
            {
              q: "'Self-portrait' =",
              options: ["o retrato", "o autorretrato", "a paisagem", "a natureza-morta"],
              correct: 1,
              fb: "Autorretrato = self-portrait. Note the double rr after auto-.",
            },
          ],
        },
      ],
    },
    {
      slug: "museums-visiting",
      title: "At the museum — tickets, audio, navigating",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Practical museum Portuguese",
          body: [
            "Ticket types in Brazil: <em>inteira</em> (full), <em>meia-entrada</em> (half-price — for students, seniors over 60, teachers, the young), <em>gratuito</em> (free). Many museums have a free day each week.",
            "Always worth asking: <em>«Tem desconto para estudante?»</em> = Is there a student discount? Bring your <em>carteirinha</em> (student ID) to claim a meia-entrada.",
            "<em>«Tem audioguia em inglês?»</em> — often yes, sometimes free, sometimes a small extra.",
            "<em>«Que horas abre / fecha?»</em> = What time does it open / close? Most close on Mondays (<em>segunda-feira</em>).",
            "<em>«É proibido tirar foto?»</em> Often photos are fine without flash; sometimes a whole show bans them.",
          ],
          keyPoint:
            "Inteira / meia-entrada / gratuito. Meia = half-price concession. Que horas abre/fecha? Most museums close Mondays.",
        },
        {
          type: "vocab",
          heading: "Museum vocabulary",
          items: [
            { l1: "o museu", en: "museum" },
            { l1: "a galeria", en: "gallery" },
            { l1: "a exposição", en: "exhibition" },
            { l1: "a exposição temporária / permanente", en: "temporary / permanent exhibition" },
            { l1: "a sala", en: "the (museum) room" },
            { l1: "o andar (térreo / primeiro)", en: "(ground / first) floor", note: "BR: térreo = ground floor" },
            { l1: "a bilheteria", en: "ticket office", note: "PT: bilheteira" },
            { l1: "o ingresso", en: "ticket (admission)", note: "the everyday BR word for an event/museum ticket" },
            { l1: "a meia-entrada", en: "half-price ticket / concession" },
            { l1: "o guarda-volumes", en: "coat / bag check" },
            { l1: "o mapa do museu", en: "museum map" },
            { l1: "o audioguia", en: "audioguide" },
            { l1: "a visita guiada", en: "guided tour" },
            { l1: "o/a guia", en: "tour guide (person)" },
            { l1: "o/a visitante", en: "visitor" },
            { l1: "a loja do museu", en: "museum shop" },
            { l1: "é proibido (tocar / fotografar)", en: "it's forbidden (to touch / photograph)" },
          ],
        },
        {
          type: "tip",
          heading: "Ingresso (BR) vs bilhete / entrada (PT)",
          body: "In Brazil your museum ticket is an <em>ingresso</em>, bought at the <em>bilheteria</em>. In Portugal you ask for a <em>bilhete</em> or <em>entrada</em> at the <em>bilheteira</em>. And the very Brazilian <em>meia-entrada</em> — half price for students, seniors, and teachers — is a legal right written into Brazilian law; in Portugal you'd just ask for the <em>desconto de estudante</em> or <em>tarifa reduzida</em>.",
          example: { l1: "BR: Uma inteira e uma meia, por favor. · PT: Um bilhete inteiro e um reduzido.", en: "One full and one concession, please." },
        },
        {
          type: "dialogue",
          heading: "At the ticket office of MASP, São Paulo",
          setup: "You arrive at the Museu de Arte de São Paulo on Avenida Paulista.",
          lines: [
            { speaker: "Você", l1: "Boa tarde. Dois ingressos para a exposição, por favor.", en: "Good afternoon. Two admission tickets for the exhibition, please." },
            { speaker: "Bilheteira", l1: "Inteira ou tem direito à meia-entrada?", en: "Full price, or do you qualify for the half-price ticket?" },
            { speaker: "Você", l1: "Uma meia para estudante — aqui está a carteirinha — e uma inteira.", en: "One student concession — here's my student ID — and one full." },
            { speaker: "Bilheteira", l1: "Perfeito. Tem audioguia em inglês, sai cinco reais a mais.", en: "Perfect. There's an audioguide in English, it's five reais extra." },
            { speaker: "Você", l1: "Pode ser um. É proibido tirar foto lá dentro?", en: "One, please. Is it forbidden to take photos inside?" },
            { speaker: "Bilheteira", l1: "Pode fotografar, mas sem flash. A exposição fica no segundo andar.", en: "You can take photos, but no flash. The exhibition is on the second floor." },
            { speaker: "Você", l1: "Obrigado! Que horas fecha?", en: "Thank you! What time does it close?" },
            { speaker: "Bilheteira", l1: "Às dezoito horas. Boa visita!", en: "At six p.m. Enjoy your visit!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Museum fill-ins",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "Tem ___ para estudante?",
              answer: "desconto",
              en: "Is there a student discount?",
              options: ["desconto", "ingresso", "horário", "preço"],
            },
            {
              template: "O ___ em inglês sai cinco reais a mais.",
              answer: "audioguia",
              en: "The English audioguide is five reais extra.",
              options: ["audioguia", "guia", "mapa", "ingresso"],
            },
            {
              template: "Que horas o museu ___ ?",
              answer: "abre",
              en: "What time does the museum open?",
              options: ["abre", "vê", "faz", "anda"],
            },
            {
              template: "A obra está na ___ do segundo andar.",
              answer: "sala",
              en: "The work is in the room on the second floor.",
              options: ["exposição", "sala", "bilheteria", "galeria"],
            },
            {
              template: "É ___ tirar foto com flash.",
              answer: "proibido",
              en: "It's forbidden to take photos with flash.",
              options: ["proibido", "aberto", "grátis", "guiado"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Two tickets, please. Is there a student discount?",
          reference: "Dois ingressos, por favor. Tem desconto para estudante?",
          hint: "Use the Brazilian 'ingresso' for ticket. 'Is there…?' = Tem…?",
        },
      ],
    },
    {
      slug: "museums-art-conversation",
      title: "Chatting about art — opinion phrases",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Sounding thoughtful in front of a painting",
          body: [
            "Brazilians love a good chat, and art is no exception. A few phrases let you join in without sounding like a know-it-all:",
            "<em>Me impressiona…</em> = It impresses me / strikes me.",
            "<em>O que eu mais gosto é…</em> = What I like most is…",
            "<em>Dá pra ver a influência de…</em> = You can see the influence of…",
            "<em>Parece quase…</em> = It almost looks like…",
            "<em>Me lembra…</em> = It reminds me of…",
            "Mix in basic art vocab (luz, sombra, pincelada, perspectiva) and you'll sound like a curious visitor, not a snob.",
          ],
          keyPoint:
            "Me impressiona / eu gosto / dá pra ver a influência de / parece quase / me lembra. Soft, observational, never faking expertise.",
        },
        {
          type: "vocab",
          heading: "Opinion phrases for art",
          items: [
            { l1: "me impressiona / me fascina", en: "it strikes me / fascinates me" },
            { l1: "o que eu mais gosto é…", en: "what I like most is…" },
            { l1: "não me convence muito", en: "it doesn't quite convince me" },
            { l1: "na minha opinião…", en: "in my opinion…" },
            { l1: "eu acho que é…", en: "I think it is…" },
            { l1: "dá pra ver a influência de…", en: "you can see the influence of…" },
            { l1: "parece quase…", en: "it almost looks like…" },
            { l1: "me lembra…", en: "it reminds me of…" },
            { l1: "é uma obra-prima", en: "it's a masterpiece" },
            { l1: "é genial / é incrível", en: "it's genius / amazing" },
            { l1: "é superestimado/a", en: "it's overrated" },
            { l1: "não entendi bem a mensagem", en: "I didn't quite get the message" },
          ],
        },
        {
          type: "dialogue",
          heading: "In front of Tarsila do Amaral's Abaporu",
          setup: "You're at the MASP with a friend, looking at a Tarsila do Amaral piece.",
          lines: [
            { speaker: "Bruna", l1: "E aí, o que você acha?", en: "So, what do you think?" },
            { speaker: "Você", l1: "Me impressiona muito. As cores são tão vivas.", en: "It really strikes me. The colors are so vivid." },
            { speaker: "Bruna", l1: "Repara como ela exagera o pé e a mão. É bem proposital.", en: "Notice how she exaggerates the foot and the hand. It's quite deliberate." },
            { speaker: "Você", l1: "Pois é, parece quase um sonho. Me lembra um pouco a paisagem do interior.", en: "Right, it almost looks like a dream. It reminds me a bit of the countryside landscape." },
            { speaker: "Bruna", l1: "Exato. A Tarsila quis criar uma arte bem brasileira, não copiada da Europa.", en: "Exactly. Tarsila wanted to create a truly Brazilian art, not copied from Europe." },
            { speaker: "Você", l1: "Eu gosto muito mais disso do que dos retratos mais clássicos. É mais original.", en: "I like this much more than the more classical portraits. It's more original." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Opinion phrases",
          items: [
            {
              template: "Me ___ muito a cor deste quadro.",
              answer: "impressiona",
              en: "I'm really struck by the color of this painting.",
              options: ["faz", "vejo", "impressiona", "tem"],
            },
            {
              template: "Na minha ___ , Portinari é o maior pintor do Brasil.",
              answer: "opinião",
              en: "In my opinion, Portinari is Brazil's greatest painter.",
              options: ["opinião", "ideia", "vez", "casa"],
            },
            {
              template: "Esta obra me ___ o modernismo.",
              answer: "lembra",
              en: "This work reminds me of modernism.",
              options: ["lembra", "vejo", "faz", "olha"],
            },
            {
              template: "Dá pra ver a ___ de Di Cavalcanti no estilo.",
              answer: "influência",
              en: "You can see Di Cavalcanti's influence in the style.",
              options: ["cor", "moldura", "influência", "sala"],
            },
            {
              template: "Eu acho que ___ uma obra-prima.",
              answer: "é",
              en: "I think it's a masterpiece.",
              options: ["é", "sou", "está", "tem"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I really like this painting. It almost looks like a photo.",
          reference: "Eu gosto muito deste quadro. Parece quase uma foto.",
          hint: "'Parece quase…' = it almost looks like… 'I like…' = eu gosto de…",
        },
        {
          type: "tip",
          heading: "Don't fake it",
          body: "Brazilians notice when someone name-drops artists to seem cultured. It's friendlier to admit <em>«Não conhecia, é lindo!»</em> = I didn't know it, it's beautiful! Curiosity beats false expertise. Asking <em>«Você pode me contar sobre esse artista?»</em> opens a real conversation — and most Brazilians will happily oblige.",
          example: { l1: "Não conhecia esse pintor. Você pode me contar mais?", en: "I didn't know this painter. Can you tell me more?" },
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'Oil on canvas' =",
        options: ["aquarela", "óleo sobre tela", "afresco", "mosaico"],
        correct: 1,
      },
      {
        q: "Tarsila do Amaral is associated with…",
        options: ["Baroque sculpture", "Brazilian modernismo", "Byzantine mosaics", "colonial portraits"],
        correct: 1,
      },
      {
        q: "'Half-price ticket / concession' (very Brazilian) =",
        options: ["inteira", "meia-entrada", "gratuito", "guarda-volumes"],
        correct: 1,
      },
      {
        q: "'Self-portrait' =",
        options: ["o retrato", "o autorretrato", "a paisagem", "a composição"],
        correct: 1,
      },
      {
        q: "Cândido Portinari is best known as…",
        options: [
          "an architect",
          "Brazil's most internationally known painter",
          "a colonial sculptor",
          "a watercolorist only",
        ],
        correct: 1,
      },
      {
        q: "In Brazil, the everyday word for a museum admission ticket is…",
        options: ["o bilhete", "a entrada", "o ingresso", "a tarifa"],
        correct: 2,
      },
      {
        q: "'You can see the influence of…' =",
        options: [
          "Dá pra ver a influência de…",
          "Você vê influência de…",
          "Influência é visível.",
          "Eu vejo de influência…",
        ],
        correct: 0,
      },
      {
        q: "'It almost looks like…' =",
        options: ["Parece quase…", "Quase é…", "Quase parece…", "Parece como…"],
        correct: 0,
      },
      {
        q: "'Is there a student discount?' =",
        options: [
          "Tem desconto para estudante?",
          "Tem preço de estudante?",
          "Estudante tem desconto?",
          "Para estudante tem preço?",
        ],
        correct: 0,
      },
      {
        q: "Oscar Niemeyer is famous as…",
        options: [
          "a modernist painter",
          "the architect of Brasília and the Niterói museum (MAC)",
          "a Baroque sculptor",
          "a watercolorist",
        ],
        correct: 1,
      },
    ],
  },
};
