import type { Unit } from "../../types";

export const UNIT_SMALL_TALK: Unit = {
  slug: "small-talk",
  stage: 7,
  order: 32,
  icon: "💬",
  title: "Small talk",
  tagline: "O tempo, o futebol, que calor! — graceful exits.",
  badge: "culture",
  lessons: [
    {
      slug: "small-talk-weather",
      title: "Como foi o fim de semana? & the weather",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Breaking the ice the Brazilian way",
          body: [
            "Brazilians warm up fast, and small talk is the on-ramp. The classic opener after a hello is <em>e aí?</em> ('hey, what's up?') or <em>tudo bem?</em> ('all good?').",
            "On a Monday you'll hear <em>«Como foi o fim de semana?»</em> = How was the weekend? A safe, friendly reply: <em>«Foi ótimo, e o seu?»</em> = It was great, and yours?",
            "And then there's the weather — the universal filler. <em>«Que calor, hein?»</em> = So hot, huh? <em>«Que frio!»</em> = So cold! <em>«Está chovendo.»</em> = It's raining.",
            "Brazil is huge and mostly warm, so heat (<em>o calor</em>) is the number-one weather complaint — followed by rain in the wet season.",
          ],
          keyPoint:
            "Openers: e aí? / tudo bem? / como foi o fim de semana? · Weather small talk: que calor!, que frio!, está chovendo.",
        },
        {
          type: "vocab",
          heading: "Openers & the weekend",
          items: [
            { l1: "E aí?", en: "Hey, what's up?", note: "Very casual opener (BR)" },
            { l1: "Tudo bem?", en: "All good? / How are you?", note: "The everyday check-in" },
            { l1: "Como foi o fim de semana?", en: "How was the weekend?", note: "Classic Monday opener" },
            { l1: "Foi ótimo / tranquilo", en: "It was great / chill", note: "tranquilo = relaxed, fine" },
            { l1: "Nada de mais", en: "Nothing much", note: "Modest weekend reply" },
            { l1: "E você?", en: "And you?", note: "Always bounce it back" },
            { l1: "O que você anda fazendo?", en: "What have you been up to?", note: "" },
            { l1: "Quanto tempo!", en: "Long time no see!", note: "" },
          ],
        },
        {
          type: "vocab",
          heading: "Weather vocabulary",
          items: [
            { l1: "o tempo", en: "the weather", note: "also means 'time' — context decides" },
            { l1: "a previsão do tempo", en: "the weather forecast", note: "" },
            { l1: "Que calor!", en: "How hot it is!", note: "The #1 Brazilian weather line" },
            { l1: "Que frio!", en: "How cold it is!", note: "" },
            { l1: "Está chovendo", en: "It's raining", note: "BR uses está + gerund" },
            { l1: "Está fazendo sol", en: "It's sunny", note: "lit. it's making sun" },
            { l1: "Está nublado", en: "It's cloudy", note: "" },
            { l1: "está abafado", en: "it's muggy / stuffy", note: "humid heat" },
            { l1: "está ventando", en: "it's windy", note: "" },
            { l1: "a chuva", en: "the rain", note: "" },
            { l1: "trinta graus", en: "thirty degrees", note: "always Celsius in Brazil" },
            { l1: "a estação chuvosa / seca", en: "the rainy / dry season", note: "" },
          ],
        },
        {
          type: "tip",
          heading: "Está vs tá — and the European 'estar a'",
          body: "In casual Brazilian speech, <em>está</em> shrinks to <em>tá</em>: <em>tá chovendo</em>, <em>tá quente</em>. It's everywhere in conversation. For the continuous, Brazil uses <em>estar + gerund</em> (<em>está chovendo</em>), while Portugal prefers <em>estar a + infinitive</em> (<em>está a chover</em>). Same idea, two structures.",
          example: { l1: "BR: Tá chovendo lá fora. · PT: Está a chover lá fora.", en: "It's raining outside." },
        },
        {
          type: "dialogue",
          heading: "Monday morning at the office",
          setup: "You run into a colleague by the coffee machine.",
          lines: [
            { speaker: "Colega", l1: "E aí, tudo bem? Como foi o fim de semana?", en: "Hey, all good? How was the weekend?" },
            { speaker: "Você", l1: "Foi ótimo, fui à praia. E o seu?", en: "It was great, I went to the beach. And yours?" },
            { speaker: "Colega", l1: "Nada de mais, fiquei em casa. Que calor, hein?", en: "Nothing much, I stayed home. So hot, huh?" },
            { speaker: "Você", l1: "Demais! Dizem que vai chover amanhã.", en: "Totally! They say it's going to rain tomorrow." },
            { speaker: "Colega", l1: "Tomara, a gente precisa de chuva.", en: "I hope so, we need rain." },
            { speaker: "Você", l1: "Verdade. Bom, bom trabalho!", en: "True. Well, have a good day's work!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Weather & opener fill-ins",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "Que ___ ! Trinta e cinco graus hoje.",
              answer: "calor",
              en: "So hot! Thirty-five degrees today.",
              options: ["calor", "frio", "tempo", "sol"],
            },
            {
              template: "Leva o guarda-chuva, está ___ .",
              answer: "chovendo",
              en: "Take the umbrella, it's raining.",
              options: ["chovendo", "fazendo", "ventando", "nublado"],
            },
            {
              template: "Como ___ o fim de semana?",
              answer: "foi",
              en: "How was the weekend?",
              options: ["foi", "é", "está", "vai"],
            },
            {
              template: "— Tudo bem? — Tudo, e ___ ?",
              answer: "você",
              en: "— All good? — Yeah, and you?",
              options: ["você", "eu", "ele", "nós"],
            },
            {
              template: "Está bem ___ hoje, muito úmido.",
              answer: "abafado",
              en: "It's really muggy today, very humid.",
              options: ["abafado", "seco", "nublado", "frio"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "How was the weekend? So hot today, huh?",
          reference: "Como foi o fim de semana? Que calor hoje, hein?",
          hint: "'How was…' = como foi…; 'so hot' = que calor; tag it with hein? for the 'huh?'.",
        },
      ],
    },
    {
      slug: "small-talk-football-plans",
      title: "Futebol & making plans",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Futebol is the national conversation",
          body: [
            "In Brazil, <em>futebol</em> is the great equalizer — everyone has a team, and asking about it opens doors.",
            "Big clubs: <em>Flamengo</em> and <em>Fluminense</em> (Rio — the <em>Fla-Flu</em> derby), <em>Corinthians</em>, <em>Palmeiras</em>, and <em>São Paulo</em> (the São Paulo derbies), plus <em>Grêmio</em> vs <em>Internacional</em> in the south. And of course the beloved <em>Seleção</em> — the national team, five-time World Cup winners.",
            "Easy openers: <em>«Você viu o jogo ontem?»</em> = Did you see the game yesterday? <em>«Para que time você torce?»</em> = Which team do you root for?",
            "If you don't follow it: <em>«Não acompanho muito futebol, mas curto o clima.»</em> = I don't follow soccer much, but I enjoy the vibe.",
          ],
          keyPoint:
            "futebol = social glue · torcer para um time = to root for a team · a Seleção = the national team. 'Did you see the game?' = Você viu o jogo?",
        },
        {
          type: "vocab",
          heading: "Football & sports",
          items: [
            { l1: "o futebol", en: "soccer / football", note: "" },
            { l1: "o jogo / a partida", en: "the game / the match", note: "" },
            { l1: "o time", en: "the team", note: "BR word (PT: a equipa)" },
            { l1: "torcer para…", en: "to root for…", note: "torço para o Flamengo" },
            { l1: "o torcedor / a torcedora", en: "fan / supporter", note: "" },
            { l1: "a Seleção", en: "the national team", note: "lit. 'the selection'" },
            { l1: "a Copa do Mundo", en: "the World Cup", note: "" },
            { l1: "o gol", en: "the goal", note: "BR spelling (PT: o golo)" },
            { l1: "o juiz / o árbitro", en: "the referee", note: "" },
            { l1: "ganhar / perder / empatar", en: "to win / lose / draw", note: "" },
            { l1: "o clássico", en: "the derby / big rivalry match", note: "" },
            { l1: "o vôlei / o basquete", en: "volleyball / basketball", note: "" },
          ],
        },
        {
          type: "vocab",
          heading: "Making plans",
          intro: "Small talk often slides into 'so, what are you up to?'",
          items: [
            { l1: "Tem planos para o fim de semana?", en: "Any plans for the weekend?", note: "" },
            { l1: "O que você vai fazer?", en: "What are you going to do?", note: "" },
            { l1: "Vamos marcar alguma coisa", en: "Let's set something up", note: "marcar = to arrange" },
            { l1: "Bora tomar um café?", en: "Wanna grab a coffee?", note: "bora = casual 'let's' (BR)" },
            { l1: "Que tal sexta?", en: "How about Friday?", note: "" },
            { l1: "Topa?", en: "You up for it?", note: "topar = to be game (BR)" },
            { l1: "Fica para a próxima", en: "Some other time / rain check", note: "" },
            { l1: "Me avisa", en: "Let me know", note: "" },
          ],
        },
        {
          type: "tip",
          heading: "Topics to handle with care",
          body: "Brazilians are open and warm, but a few topics can get heated:<br>• <strong>Política</strong> — opinions run strong and polarized; don't volunteer them with strangers.<br>• <strong>Futebol rivalries</strong> — good fun, but read the room before mocking someone's team.<br>• <strong>Crime / safety</strong> — fine to ask for advice, but avoid sweeping 'Brazil is dangerous' generalizations; people are proud of their cities.<br>• <strong>Money / salary</strong> — asking how much someone earns is awkward.<br>Always safe: food, music, beaches, family, travel, and (gently) football.",
        },
        {
          type: "dialogue",
          heading: "Talking football and making a plan",
          setup: "A neighbor stops you in the elevator.",
          lines: [
            { speaker: "Vizinho", l1: "E aí! Você viu o jogo ontem?", en: "Hey! Did you see the game yesterday?" },
            { speaker: "Você", l1: "Não vi, quem ganhou?", en: "I didn't, who won?" },
            { speaker: "Vizinho", l1: "Flamengo, dois a zero. Você torce para quem?", en: "Flamengo, two to nothing. Who do you root for?" },
            { speaker: "Você", l1: "Sinceramente, não acompanho muito, mas curto o clima.", en: "Honestly, I don't follow it much, but I enjoy the vibe." },
            { speaker: "Vizinho", l1: "Tranquilo! Bora ver o próximo num bar?", en: "No worries! Wanna watch the next one at a bar?" },
            { speaker: "Você", l1: "Topo! Me avisa quando for.", en: "I'm up for it! Let me know when it is." },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the small talk",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Você", "viu", "o", "jogo", "ontem"], en: "Did you see the game yesterday?" },
            { tokens: ["Para", "que", "time", "você", "torce"], en: "Which team do you root for?" },
            { tokens: ["Tem", "planos", "para", "o", "fim", "de", "semana"], en: "Any plans for the weekend?" },
            { tokens: ["Bora", "tomar", "um", "café"], en: "Wanna grab a coffee?" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Football & plans",
          items: [
            {
              template: "Para que time você ___ ?",
              answer: "torce",
              en: "Which team do you root for?",
              options: ["torce", "joga", "ganha", "gosta"],
            },
            {
              template: "Dois a zero — que ___ !",
              answer: "jogo",
              en: "Two to nothing — what a game!",
              options: ["jogo", "time", "gol", "juiz"],
            },
            {
              template: "Bora ___ um café depois?",
              answer: "tomar",
              en: "Wanna grab a coffee later?",
              options: ["tomar", "fazer", "ir", "marcar"],
            },
            {
              template: "Não posso hoje, fica para a ___ .",
              answer: "próxima",
              en: "I can't today, some other time.",
              options: ["próxima", "semana", "tarde", "hora"],
            },
            {
              template: "A ___ ganhou a Copa do Mundo cinco vezes.",
              answer: "Seleção",
              en: "The national team won the World Cup five times.",
              options: ["Seleção", "torcida", "equipe", "partida"],
            },
          ],
        },
      ],
    },
    {
      slug: "small-talk-exits",
      title: "Reactions & graceful exits",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "How to react and how to leave",
          body: [
            "Brazilians stack little reaction words to show they're listening. Sprinkle them in:",
            "<em>«Sério?!»</em> = Really?! / <em>«Nossa!»</em> = Wow! (the all-purpose exclamation, short for 'Nossa Senhora').",
            "<em>«Que legal!»</em> = How cool! / <em>«Que pena!»</em> = What a shame! / <em>«Que chato.»</em> = How annoying.",
            "<em>«Imagina!»</em> = Not at all! / Don't mention it.",
            "And the graceful exit — Brazilians soften goodbyes with a string of warm phrases: <em>«Já vou indo.»</em> = I'm heading off now. <em>«Foi bom te ver.»</em> = It was good to see you. <em>«A gente se vê.»</em> = We'll see each other around. <em>«Se cuida!»</em> = Take care!",
          ],
          keyPoint:
            "Reactions: sério?!, nossa!, que legal!, que pena! · Exits: tô indo, foi bom te ver, a gente se vê, se cuida.",
        },
        {
          type: "vocab",
          heading: "Reactions & exits",
          items: [
            { l1: "Sério?!", en: "Really?!", note: "" },
            { l1: "Nossa!", en: "Wow! / Geez!", note: "All-purpose exclamation (BR)" },
            { l1: "Que legal!", en: "How cool!", note: "legal = cool/nice (BR)" },
            { l1: "Que pena!", en: "What a shame!", note: "" },
            { l1: "Que chato", en: "How annoying / what a bummer", note: "" },
            { l1: "Imagina!", en: "Not at all! / Don't mention it", note: "warm 'no worries'" },
            { l1: "Tô indo / Já vou indo", en: "I'm heading off (now)", note: "tô = casual 'estou'" },
            { l1: "Foi bom te ver", en: "It was good to see you", note: "" },
            { l1: "A gente se vê", en: "We'll see each other around", note: "a gente = we (BR)" },
            { l1: "Se cuida!", en: "Take care!", note: "" },
            { l1: "Um abraço", en: "A hug (warm sign-off)", note: "also closes messages/emails" },
            { l1: "Falou! / Falou, tchau", en: "Later! / Bye!", note: "very casual sign-off (BR)" },
            { l1: "Até mais", en: "See you", note: "" },
          ],
        },
        {
          type: "tip",
          heading: "Brazilian vs European goodbyes",
          body: "Brazil leans warm and casual: <em>falou</em>, <em>a gente se vê</em>, <em>se cuida</em>, <em>um abraço</em>. Portugal sounds a bit more clipped — you'll hear <em>então?</em> (instead of 'e aí?') as an opener, and <em>até já</em> (see you in a minute) or the more final <em>adeus</em> as a goodbye. A Brazilian almost never says <em>adeus</em> — it sounds dramatic, like 'farewell forever'.",
          example: { l1: "BR: Falou, se cuida! · PT: Adeus, até já!", en: "Bye, take care! / see you soon!" },
        },
        {
          type: "dialogue",
          heading: "Wrapping up a chat",
          setup: "You've been catching up with a friend on the sidewalk.",
          lines: [
            { speaker: "Amigo", l1: "Nossa, que bom te encontrar! Quanto tempo!", en: "Wow, so good to run into you! Long time!" },
            { speaker: "Você", l1: "Pois é! Mas já vou indo, tô atrasado.", en: "Right?! But I'm heading off, I'm late." },
            { speaker: "Amigo", l1: "Tranquilo. A gente marca um café qualquer dia.", en: "No worries. Let's set up a coffee some day." },
            { speaker: "Você", l1: "Bora! Foi bom te ver, viu?", en: "Let's do it! It was good to see you, okay?" },
            { speaker: "Amigo", l1: "Igualmente. Se cuida! Um abraço.", en: "Likewise. Take care! A hug." },
            { speaker: "Você", l1: "Falou, até mais!", en: "Later, see you!" },
          ],
        },
        {
          type: "pronounce",
          heading: "Reactions & exits to practise aloud",
          items: [
            { l1: "Nossa!", en: "Wow!", tip: "NOH-sah (nasal 'o')" },
            { l1: "Que legal!", en: "How cool!", tip: "kee leh-GOW (final -al sounds like 'ow')" },
            { l1: "A gente se vê", en: "We'll see each other", tip: "ah ZHEN-chee see VEH" },
            { l1: "Se cuida", en: "Take care", tip: "see KWEE-dah" },
            { l1: "Falou", en: "Later! / Bye!", tip: "fah-LOH" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Reaction & exit phrases",
          items: [
            {
              template: "___ ?! Não acredito!",
              answer: "Sério",
              en: "Really?! I can't believe it!",
              options: ["Sério", "Nossa", "Legal", "Pena"],
            },
            {
              template: "Que ___ ! Adorei a notícia.",
              answer: "legal",
              en: "How cool! I loved the news.",
              options: ["legal", "pena", "chato", "calor"],
            },
            {
              template: "Já vou ___ , tô atrasado.",
              answer: "indo",
              en: "I'm heading off, I'm late.",
              options: ["indo", "saindo", "vindo", "fazendo"],
            },
            {
              template: "Foi bom te ___ ! A gente se vê.",
              answer: "ver",
              en: "It was good to see you! See you around.",
              options: ["ver", "ouvir", "falar", "encontrar"],
            },
            {
              template: "Se ___ ! Um abraço.",
              answer: "cuida",
              en: "Take care! A hug.",
              options: ["cuida", "vê", "vai", "fica"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Wow, really?! How cool!",
          reference: "Nossa, sério?! Que legal!",
          hint: "Three stacked reactions: nossa (wow), sério?! (really?!), que legal! (how cool!).",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "A casual Brazilian opener for 'hey, what's up?' is…",
        options: ["Adeus", "E aí?", "Então?", "Imagina"],
        correct: 1,
      },
      {
        q: "'How was the weekend?' =",
        options: [
          "Como é o fim de semana?",
          "Como foi o fim de semana?",
          "Quando foi o fim de semana?",
          "Onde foi o fim de semana?",
        ],
        correct: 1,
      },
      {
        q: "'It's raining' in Brazilian Portuguese =",
        options: ["Está a chover.", "Está chovendo.", "Faz chuva.", "Tem chuva."],
        correct: 1,
      },
      {
        q: "Brazil measures temperature in…",
        options: ["Fahrenheit", "Kelvin", "Celsius", "varies by state"],
        correct: 2,
      },
      {
        q: "'Which team do you root for?' =",
        options: [
          "Que time você tem?",
          "Para que time você torce?",
          "Qual é o seu jogo?",
          "Você joga em que time?",
        ],
        correct: 1,
      },
      {
        q: "'A Seleção' refers to…",
        options: ["a derby match", "the national team", "the league title", "the referee"],
        correct: 1,
      },
      {
        q: "'Nossa!' is closest to…",
        options: ["Please!", "Wow! / Geez!", "Goodbye!", "Let's go!"],
        correct: 1,
      },
      {
        q: "A warm Brazilian way to say 'take care' on leaving is…",
        options: ["Adeus", "Se cuida!", "Pois não", "Com licença"],
        correct: 1,
      },
      {
        q: "Which goodbye sounds dramatic/final and is rare in Brazil (more European)?",
        options: ["Falou", "A gente se vê", "Adeus", "Tchau"],
        correct: 2,
      },
      {
        q: "Translate: 'It was good to see you! See you around.'",
        options: [
          "Foi bom te ver! A gente se vê.",
          "Foi bom te ouvir! Até já.",
          "Que bom te ver! Adeus.",
          "Both A and B work and are interchangeable.",
        ],
        correct: 0,
      },
    ],
  },
};
