import type { Unit } from "../../types";

export const UNIT_OPINIONS: Unit = {
  slug: "opinions",
  stage: 8,
  order: 35,
  icon: "🗣️",
  title: "Opinions & debate",
  tagline: "Na minha opinião, concordo, no entanto…",
  badge: "advanced",
  lessons: [
    {
      slug: "opinions-stating",
      title: "Stating an opinion",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "How to lead with 'I think…' and sound natural",
          body: [
            "Brazilians have plenty of ways to open an opinion. Mix them in so you don't repeat yourself:",
            "<em>Na minha opinião…</em> = In my opinion… (neutral, works everywhere)",
            "<em>Eu acho que…</em> = I think that… (by far the most common in everyday speech)",
            "<em>Eu acredito que…</em> = I believe that… (a touch stronger / more thoughtful)",
            "<em>Para mim…</em> = For me… (slightly more personal)",
            "<em>Eu diria que…</em> = I'd say that… (soft, hedged)",
            "<em>Do meu ponto de vista…</em> = From my point of view… (more formal/written)",
            "<em>Me parece que…</em> = It seems to me that…",
          ],
          tip: {
            label: "Eu acho que rules in Brazil",
            body: "In casual Brazilian speech, eu acho que is the workhorse — far more common than eu penso que. 'Eu penso que' isn't wrong, but it sounds a little bookish. Reach for eu acho que and you'll always sound natural.",
          },
          keyPoint:
            "na minha opinião / para mim (neutral) · eu acho que (most common) · eu acredito que (stronger) · eu diria que (soft).",
        },
        {
          type: "vocab",
          heading: "Opening an opinion",
          items: [
            { l1: "na minha opinião", en: "in my opinion", note: "Neutral, works in any register" },
            { l1: "eu acho que…", en: "I think that…", note: "The everyday Brazilian default" },
            { l1: "eu acredito que…", en: "I believe that…", note: "A bit stronger / more considered" },
            { l1: "para mim…", en: "for me…", note: "More personal angle" },
            { l1: "eu diria que…", en: "I'd say that…", note: "Soft, hedged (conditional)" },
            { l1: "do meu ponto de vista", en: "from my point of view", note: "More formal/written" },
            { l1: "me parece que…", en: "it seems to me that…", note: "" },
            { l1: "na minha experiência", en: "in my experience", note: "" },
            { l1: "pessoalmente", en: "personally", note: "" },
            { l1: "sinceramente / honestamente", en: "honestly / frankly", note: "" },
            { l1: "se você quer saber", en: "if you ask me", note: "Lit. 'if you want to know' (casual)" },
            { l1: "tenho a impressão de que…", en: "I have the impression that…", note: "" },
          ],
        },
        {
          type: "tip",
          heading: "When 'I think' flips into the subjunctive",
          body: "Most opinion openers take the plain present: <em>eu acho que ela é ótima</em> (I think she's great). But the moment you turn them <strong>negative</strong>, Brazilian Portuguese switches to the subjunctive: <em>não acho que ela seja ótima</em> (I don't think she's that great). Same with <em>não acredito que / duvido que</em>. You'll drill this lightly below — for now, just register the pattern: doubt or negation → subjunctive.",
          example: { l1: "Acho que ele tem razão. → Não acho que ele tenha razão.", en: "I think he's right. → I don't think he's right." },
        },
        {
          type: "dialogue",
          heading: "Discussing a film",
          setup: "Post-cinema chat over a beer.",
          lines: [
            { speaker: "Ana", l1: "E aí, o que você achou do filme?", en: "So, what did you think of the film?" },
            { speaker: "Você", l1: "Sinceramente, gostei muito. Na minha opinião, a direção estava ótima.", en: "Honestly, I really liked it. In my opinion, the directing was great." },
            { speaker: "Ana", l1: "Concordo. E os atores?", en: "I agree. And the actors?" },
            { speaker: "Você", l1: "Eu acho que a protagonista é excelente. Me parece que ela atua com uma naturalidade incrível.", en: "I think the lead actress is excellent. It seems to me she acts with incredible naturalness." },
            { speaker: "Ana", l1: "Verdade. Mas o final, para mim, ficou um pouco fraco.", en: "True. But the ending, for me, was a bit weak." },
            { speaker: "Você", l1: "Você tem razão, para mim também. Eu esperava algo mais.", en: "You're right, for me too. I expected something more." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Pick the opener",
          items: [
            {
              template: "___ , o filme estava lindo.",
              answer: "Na minha opinião",
              en: "In my opinion, the film was beautiful.",
              options: ["Na minha opinião", "Do meu", "Para que", "Sou que"],
            },
            {
              template: "Eu ___ que você tem razão.",
              answer: "acho",
              en: "I think you're right.",
              options: ["acho", "tenho", "sou", "vou"],
            },
            {
              template: "___ , prefiro um pouco menos de sal.",
              answer: "Pessoalmente",
              en: "Personally, I prefer a bit less salt.",
              options: ["Pessoalmente", "Para você", "Concordo", "Talvez"],
            },
            {
              template: "Me ___ que ela tem razão.",
              answer: "parece",
              en: "It seems to me that she's right.",
              options: ["parece", "acho", "acredito", "diria"],
            },
            {
              template: "Não acho que ele ___ razão. (ter)",
              answer: "tenha",
              en: "I don't think he's right.",
              options: ["tem", "tenha", "ter", "tinha"],
            },
          ],
        },
      ],
    },
    {
      slug: "opinions-agree-disagree",
      title: "Agreeing and disagreeing",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Politely agreeing — and politely disagreeing",
          body: [
            "<strong>Agreeing:</strong>",
            "<em>Concordo.</em> = I agree.",
            "<em>Você tem razão.</em> = You're right.",
            "<em>Exatamente / Exato.</em> = Exactly.",
            "<em>Com certeza.</em> = For sure / Definitely.",
            "<em>Para mim também.</em> = For me too.",
            "<strong>Disagreeing softly:</strong>",
            "<em>Não concordo totalmente.</em> = I don't entirely agree.",
            "<em>Não tenho tanta certeza.</em> = I'm not so sure.",
            "<em>Eu entendo o seu ponto, mas…</em> = I see your point, but…",
            "<em>Por um lado sim, mas por outro…</em> = On the one hand yes, but on the other…",
            "<em>Não sei se concordo.</em> = I'm not sure I agree.",
          ],
          keyPoint:
            "Agree: concordo, você tem razão, exatamente, com certeza. Disagree softly: não concordo totalmente, entendo o seu ponto, mas…",
        },
        {
          type: "vocab",
          heading: "Agree / disagree phrases",
          items: [
            { l1: "concordo", en: "I agree", note: "" },
            { l1: "você tem razão", en: "you're right", note: "Lit. 'you have reason'" },
            { l1: "exatamente / exato", en: "exactly", note: "" },
            { l1: "com certeza", en: "definitely / for sure", note: "" },
            { l1: "é verdade", en: "that's true", note: "" },
            { l1: "para mim também", en: "for me too", note: "" },
            { l1: "em parte sim", en: "partly yes", note: "" },
            { l1: "não concordo totalmente", en: "I don't entirely agree", note: "Softer than a flat 'no'" },
            { l1: "não tenho tanta certeza", en: "I'm not so sure", note: "" },
            { l1: "eu entendo o seu ponto, mas…", en: "I see your point, but…", note: "" },
            { l1: "por um lado… por outro…", en: "on one hand… on the other…", note: "" },
            { l1: "discordo", en: "I disagree", note: "Direct but neutral; not rude" },
            { l1: "não é bem assim", en: "it's not quite like that", note: "Gentle pushback" },
          ],
        },
        {
          type: "tip",
          heading: "Brazilians soften disagreement",
          body: "Brazilian conversation leans warm and indirect. A blunt <em>você está errado</em> (you're wrong) lands harsh — most people would never open with it. Instead, cushion the disagreement: start with a small agreement (<em>é, mas…</em> = 'yeah, but…'), or frame it as your own uncertainty (<em>não tenho tanta certeza…</em>). Disagree with the idea, not the person.",
          example: { l1: "É, faz sentido, mas eu vejo de um jeito diferente.", en: "Yeah, that makes sense, but I see it a different way." },
        },
        {
          type: "tip",
          heading: "Brazil vs Portugal: 'concordo' and 'pois'",
          body: "<em>Concordo</em> and <em>você tem razão</em> work in both countries. But in Portugal you'll hear <em>pois</em> a lot as a filler for 'right / indeed' (BR speakers rarely use it that way), and the Portuguese tend to use <em>tu tens razão</em> with the tu form. Stick with the Brazilian <em>você tem razão</em> and you're understood everywhere.",
          example: { l1: "BR: Você tem razão. · PT: Tens razão. / Pois.", en: "You're right. / Right, indeed." },
        },
        {
          type: "dialogue",
          heading: "Polite back-and-forth",
          setup: "Friends arguing about whether Rio or São Paulo is better.",
          lines: [
            { speaker: "Marcos", l1: "Na minha opinião, São Paulo é muito melhor para morar do que o Rio.", en: "In my opinion, São Paulo is much better to live in than Rio." },
            { speaker: "Você", l1: "Eu entendo o seu ponto, mas não concordo totalmente. O Rio tem algo que São Paulo não tem.", en: "I see your point, but I don't entirely agree. Rio has something São Paulo doesn't." },
            { speaker: "Marcos", l1: "O quê, por exemplo?", en: "Like what?" },
            { speaker: "Você", l1: "A praia, a natureza. Você sai do trabalho e em vinte minutos está no mar.", en: "The beach, nature. You leave work and in twenty minutes you're at the sea." },
            { speaker: "Marcos", l1: "Exato, mas justamente por isso é mais caótico. Por um lado o charme, por outro o trânsito.", en: "Exactly, but that's exactly why it's more chaotic. On one hand the charm, on the other the traffic." },
            { speaker: "Você", l1: "Você também tem razão. Talvez dependa do que você procura.", en: "You're also right. Maybe it depends on what you're looking for." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Agreement phrases",
          items: [
            {
              template: "___ com você, é isso mesmo.",
              answer: "Concordo",
              en: "I agree with you, that's exactly it.",
              options: ["Concordo", "Razão", "Verdade", "Exato"],
            },
            {
              template: "Você tem ___ , eu deveria estudar mais.",
              answer: "razão",
              en: "You're right, I should study more.",
              options: ["razão", "verdade", "certeza", "ponto"],
            },
            {
              template: "Para mim ___ , a praia é melhor que a piscina.",
              answer: "também",
              en: "For me too, the beach is better than the pool.",
              options: ["também", "sim", "muito", "com"],
            },
            {
              template: "Eu entendo o seu ___ , mas penso diferente.",
              answer: "ponto",
              en: "I see your point, but I think differently.",
              options: ["ponto", "ideia", "razão", "lado"],
            },
            {
              template: "Por um ___ sim, mas por outro não.",
              answer: "lado",
              en: "On one hand yes, but on the other no.",
              options: ["lado", "parte", "ponto", "jeito"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I see your point, but I'm not so sure. For me, the film was a bit weak.",
          reference: "Eu entendo o seu ponto, mas não tenho tanta certeza. Para mim, o filme ficou um pouco fraco.",
          hint: "Soften the disagreement: 'eu entendo o seu ponto, mas…' + 'não tenho tanta certeza'.",
        },
      ],
    },
    {
      slug: "opinions-extended-discussion",
      title: "Building an argument & wrapping up",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Stringing thoughts together",
          body: [
            "Beyond stating and agreeing, you'll want to build arguments and close them off:",
            "<em>Em primeiro lugar / Antes de tudo…</em> = First of all…",
            "<em>Em segundo lugar / Depois…</em> = Secondly / Then…",
            "<em>Além disso…</em> = Furthermore / Besides…",
            "<em>Por exemplo…</em> = For example…",
            "<em>Por outro lado…</em> = On the other hand…",
            "<em>No entanto / Porém / Contudo…</em> = However…",
            "<em>De qualquer forma…</em> = In any case…",
            "<em>Em resumo / Enfim…</em> = In short / Anyway…",
            "<em>Dito isso…</em> = Having said that…",
          ],
          keyPoint:
            "Build: em primeiro lugar → em segundo lugar → além disso → por exemplo → por outro lado. Wrap: em resumo / enfim / dito isso.",
        },
        {
          type: "vocab",
          heading: "Discourse connectors",
          items: [
            { l1: "antes de tudo / em primeiro lugar", en: "first of all", note: "" },
            { l1: "em segundo lugar", en: "in the second place", note: "" },
            { l1: "depois / além disso", en: "then / furthermore", note: "" },
            { l1: "por exemplo", en: "for example", note: "" },
            { l1: "em particular", en: "in particular", note: "" },
            { l1: "principalmente / sobretudo", en: "above all / mainly", note: "" },
            { l1: "por outro lado", en: "on the other hand", note: "" },
            { l1: "no entanto / porém", en: "however", note: "no entanto is a touch more formal" },
            { l1: "contudo / todavia", en: "however / nevertheless", note: "More formal/written" },
            { l1: "apesar disso", en: "despite this", note: "" },
            { l1: "de qualquer forma / de qualquer jeito", en: "anyway / in any case", note: "jeito is more casual (BR)" },
            { l1: "em resumo / resumindo", en: "in short / to sum up", note: "" },
            { l1: "enfim", en: "anyway / in short", note: "Common wrap-up filler" },
            { l1: "dito isso", en: "having said that", note: "" },
            { l1: "portanto / então", en: "therefore / so", note: "" },
            { l1: "depende", en: "it depends", note: "The diplomat's answer" },
          ],
        },
        {
          type: "tip",
          heading: "No entanto, porém, mas — which one?",
          body: "All three mean roughly 'but / however', but they sit in different spots. <em>Mas</em> is the everyday 'but' and usually starts the clause. <em>Porém</em> is a slightly more formal 'however' and can come at the start or, comma-wrapped, mid-sentence. <em>No entanto</em> and <em>contudo</em> are the most formal — great for writing and reasoned debate. In casual chat, mas does most of the work; sprinkle the others to sound articulate.",
          example: { l1: "Gosto da ideia. No entanto, tenho uma dúvida.", en: "I like the idea. However, I have a doubt." },
        },
        {
          type: "dialogue",
          heading: "A reasoned argument",
          setup: "Discussing Brazilian vs American work culture.",
          lines: [
            { speaker: "Você", l1: "Na minha opinião, a cultura de trabalho no Brasil é bem diferente da americana, e em alguns aspectos melhor.", en: "In my opinion, the work culture in Brazil is quite different from the American one, and in some respects better." },
            { speaker: "Marcos", l1: "Sério? Em que sentido?", en: "Really? In what sense?" },
            { speaker: "Você", l1: "Antes de tudo, existe mais respeito pelo horário de almoço — um almoço de verdade, não um sanduíche na frente do computador. Em segundo lugar, há mais valor na família e no tempo livre.", en: "First of all, there's more respect for the lunch hour — a real lunch, not a sandwich in front of the computer. Secondly, there's more value placed on family and free time." },
            { speaker: "Marcos", l1: "É verdade. Por outro lado, porém, há vários pontos negativos — como a burocracia e os salários baixos.", en: "That's true. On the other hand, though, there are several downsides — like bureaucracy and low salaries." },
            { speaker: "Você", l1: "Exato. Por exemplo, os salários nos Estados Unidos costumam ser mais altos, mas se trabalha muito mais e com menos proteção.", en: "Exactly. For example, salaries in the US are usually higher, but you work much more and with less protection." },
            { speaker: "Marcos", l1: "Enfim, todo sistema tem prós e contras.", en: "Anyway, every system has pros and cons." },
            { speaker: "Você", l1: "Exatamente. Dito isso, pessoalmente eu prefiro o ritmo brasileiro.", en: "Exactly. Having said that, personally I prefer the Brazilian pace." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Build the argument",
          items: [
            {
              template: "___ , é preciso ouvir o outro.",
              answer: "Antes de tudo",
              en: "First of all, you have to listen to the other person.",
              options: ["Antes de tudo", "Porém", "Então", "De qualquer forma"],
            },
            {
              template: "Em segundo ___ , é importante dar a sua opinião.",
              answer: "lugar",
              en: "Secondly, it's important to give your opinion.",
              options: ["lugar", "ponto", "jeito", "lado"],
            },
            {
              template: "Por outro ___ , também é preciso ser flexível.",
              answer: "lado",
              en: "On the other hand, you also have to be flexible.",
              options: ["lado", "parte", "mão", "ponto"],
            },
            {
              template: "___ , eu prefiro a comida brasileira.",
              answer: "Em resumo",
              en: "In short, I prefer Brazilian food.",
              options: ["Em resumo", "Por exemplo", "Além disso", "Portanto"],
            },
            {
              template: "Sobretudo, não se deve ___ a calma.",
              answer: "perder",
              en: "Above all, you shouldn't lose your cool.",
              options: ["encontrar", "perder", "ter", "manter"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the argument",
          items: [
            { tokens: ["Na", "minha", "opinião", "o", "melhor", "restaurante", "é", "o", "da", "esquina"], en: "In my opinion the best restaurant is the one on the corner." },
            { tokens: ["Antes", "de", "tudo", "a", "comida", "é", "ótima", ",", "e", "além", "disso", "o", "serviço", "é", "rápido"], en: "First of all the food is great, and besides the service is fast." },
            { tokens: ["Por", "outro", "lado", ",", "porém", ",", "é", "um", "pouco", "caro"], en: "On the other hand, however, it's a bit expensive." },
            { tokens: ["Enfim", ",", "vale", "a", "pena", "pelo", "menos", "uma", "vez"], en: "Anyway, it's worth it at least once." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "In my opinion, first of all the price is too high. On the other hand, the quality is excellent.",
          reference: "Na minha opinião, antes de tudo o preço é alto demais. Por outro lado, a qualidade é excelente.",
          hint: "Three connectors stacked: 'na minha opinião' + 'antes de tudo' + 'por outro lado'. 'Too high' = alto demais.",
        },
        {
          type: "tip",
          heading: "You did it — full curriculum",
          body: "This is the last unit of 35. You've covered: sounds, greetings, numbers, articles, the present tense, the irregular verbs, possessives, questions, likes, saber vs conhecer, connectors, getting around a Brazilian city (transit, directions, hotel, help, landmarks), all of the food (the lanchonete, the restaurant, regional dishes), the past tenses (pretérito perfeito + imperfeito), the future, narration, shopping, the market, formal o senhor / a senhora, complaints, idioms, museums, small talk, the conditional, the subjunctive, and now opinions and debate. You can hold any real conversation an A2–B1 traveller would have in Brazil. <em>Parabéns!</em>",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'I think (that)…' — the most common everyday Brazilian opener =",
        options: ["Eu penso que", "Eu acho que", "Do meu ponto de vista", "Me parece que"],
        correct: 1,
      },
      {
        q: "'In my opinion' =",
        options: ["Na minha opinião", "Para você", "Com certeza", "Em resumo"],
        correct: 0,
      },
      {
        q: "'I agree' =",
        options: ["Concordo.", "Discordo.", "Tenho razão.", "Está certo de mim."],
        correct: 0,
      },
      {
        q: "'You're right' =",
        options: ["Você está errado.", "Você tem razão.", "Você diz bem.", "Você é certo."],
        correct: 1,
      },
      {
        q: "A polite, softened disagreement opener =",
        options: [
          "Você está completamente errado.",
          "Não concordo totalmente.",
          "Que bobagem.",
          "Não, não, não.",
        ],
        correct: 1,
      },
      {
        q: "'On the other hand' =",
        options: ["por outro lado", "pela outra mão", "ao outro lado", "em outro lado"],
        correct: 0,
      },
      {
        q: "'First of all' =",
        options: ["primeiro de tudo", "antes de tudo / em primeiro lugar", "no primeiro ponto", "ao início"],
        correct: 1,
      },
      {
        q: "'In short / anyway' (wrap-up) =",
        options: ["finalmente", "em resumo / enfim", "porém", "por exemplo"],
        correct: 1,
      },
      {
        q: "'I see your point, but…' =",
        options: [
          "Vejo o que você falou, mas…",
          "Eu entendo o seu ponto, mas…",
          "Eu sinto o seu ponto, porém…",
          "Compreendo a sua opinião, e…",
        ],
        correct: 1,
      },
      {
        q: "Which is correct after a negative opinion? 'Não acho que ele ___ razão.'",
        options: ["tem", "tenha", "ter", "tinha"],
        correct: 1,
      },
      {
        q: "Translate: 'In my opinion, first of all you should listen. On the other hand, you have to speak too.'",
        options: [
          "Na minha opinião, antes de tudo você deveria ouvir. Por outro lado, você também precisa falar.",
          "Para mim, primeiro, escuta. Depois, fala.",
          "Da minha opinião, antes ouço. Depois falo.",
          "Em opinião minha, ouça primeiro. Fale também.",
        ],
        correct: 0,
      },
    ],
  },
};
