import type { Unit } from "../../types";

export const UNIT_HOTEL: Unit = {
  slug: "hotel",
  stage: 3,
  order: 12,
  icon: "🏨",
  title: "Airport & hotel",
  tagline: "Check-in, réservation, chambre, réclamations.",
  lessons: [
    {
      slug: "hotel-main",
      title: "Navigating airports and hotels",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "CDG and Paris hotels",
          body: [
            "Charles de Gaulle (CDG) and Orly are the main Paris airports. CDG is vast — it has multiple terminals and a train station inside (RER B connects to central Paris in ~35 min for about €11.80). The Navigo pass covers this.",
            "Paris hotels range from tiny budget chambre d'hôtes to palatial palace hotels. Check-in (<em>l'enregistrement</em>) is typically from 2–3 pm; check-out (<em>le départ</em>) by 11 am–noon. Most receptionists speak English, but French first is always appreciated.",
          ],
        },
        {
          type: "vocab",
          heading: "Hotel vocabulary",
          items: [
            { l1: "une chambre (simple/double)", en: "a room (single/double)" },
            { l1: "une chambre avec salle de bains", en: "a room with bathroom" },
            { l1: "le petit-déjeuner inclus", en: "breakfast included" },
            { l1: "l'étage", en: "the floor / storey", note: "ground floor = rez-de-chaussée (RDC)" },
            { l1: "l'ascenseur", en: "the lift / elevator" },
            { l1: "le wifi", en: "the wifi" },
            { l1: "la réservation", en: "the reservation" },
            { l1: "l'enregistrement", en: "check-in" },
            { l1: "le départ", en: "check-out / departure" },
            { l1: "la clé / la carte magnétique", en: "the key / the key card" },
            { l1: "le sol / la moquette", en: "the floor / carpet" },
          ],
        },
        {
          type: "dialogue",
          heading: "Checking in",
          lines: [
            { speaker: "You", l1: "Bonjour. J'ai une réservation au nom de Johnson.", en: "Hello. I have a reservation under the name Johnson." },
            { speaker: "Receptionist", l1: "Oui, une chambre double pour trois nuits. Votre passeport, s'il vous plaît.", en: "Yes, a double room for three nights. Your passport, please." },
            { speaker: "You", l1: "Voilà. Est-ce que le petit-déjeuner est inclus?", en: "Here it is. Is breakfast included?" },
            { speaker: "Receptionist", l1: "Oui, le buffet est servi de sept à dix heures.", en: "Yes, the buffet is served from seven to ten." },
            { speaker: "You", l1: "Parfait. Ma chambre est à quel étage?", en: "Perfect. What floor is my room on?" },
            { speaker: "Receptionist", l1: "Au troisième étage. L'ascenseur est à gauche.", en: "On the third floor. The lift is on the left." },
          ],
        },
        {
          type: "vocab",
          heading: "Airport vocabulary",
          items: [
            { l1: "l'aéroport", en: "the airport" },
            { l1: "le terminal", en: "the terminal" },
            { l1: "l'enregistrement des bagages", en: "baggage check-in" },
            { l1: "les bagages à main", en: "hand luggage" },
            { l1: "la salle d'embarquement", en: "the departure gate" },
            { l1: "le vol", en: "the flight" },
            { l1: "le décollage / l'atterrissage", en: "take-off / landing" },
            { l1: "les douanes", en: "customs" },
            { l1: "le contrôle des passeports", en: "passport control" },
          ],
        },
        {
          type: "translate",
          heading: "Translate",
          direction: "en-to-l1",
          prompt: "Excuse me. I have a problem with my room. The shower doesn't work.",
          reference: "Excusez-moi. J'ai un problème avec ma chambre. La douche ne fonctionne pas.",
          hint: "ne fonctionne pas = doesn't work; la douche = the shower",
        },
      ],
    },
    {
      slug: "hotel-reservation",
      title: "Booking a room & amenities",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Reserving and asking what's included",
          body: [
            "To book, you'll say what you want and for when: <em>Je voudrais réserver une chambre pour deux nuits, du 5 au 7 juin</em> (from the 5th to the 7th of June). <em>Du … au …</em> is the standard 'from … to …' for dates.",
            "Hotels describe rooms by bed type: <em>un lit double</em> (one double bed), <em>deux lits simples</em> (two single beds), <em>une chambre pour deux personnes</em>. Confirm the price <em>par nuit</em> (per night) and whether <em>les taxes</em> are included.",
            "Then ask about amenities — air conditioning, safe, towels — which often decide comfort in a Paris summer.",
          ],
          keyPoint: "Book: réserver une chambre pour X nuits, du … au … Confirm price par nuit, taxes comprises.",
        },
        {
          type: "vocab",
          heading: "Booking & room types",
          items: [
            { l1: "réserver", en: "to book / reserve" },
            { l1: "une chambre pour deux personnes", en: "a room for two" },
            { l1: "un lit double / deux lits simples", en: "a double bed / two single beds" },
            { l1: "pour deux nuits, du 5 au 7", en: "for two nights, from the 5th to the 7th" },
            { l1: "le prix par nuit", en: "the price per night" },
            { l1: "taxes comprises", en: "taxes included", note: "compris/comprise = included" },
            { l1: "Est-ce que vous avez de la disponibilité?", en: "Do you have availability?" },
            { l1: "annuler / modifier une réservation", en: "to cancel / change a booking" },
          ],
        },
        {
          type: "vocab",
          heading: "Amenities & requests",
          items: [
            { l1: "la climatisation (la clim)", en: "air conditioning" },
            { l1: "le coffre-fort", en: "the safe" },
            { l1: "une serviette", en: "a towel" },
            { l1: "un oreiller / une couverture", en: "a pillow / a blanket" },
            { l1: "le ménage", en: "housekeeping / room cleaning" },
            { l1: "le room service", en: "room service" },
            { l1: "une chambre calme / côté cour", en: "a quiet room / courtyard-facing" },
            { l1: "Est-ce qu'il y a un parking?", en: "Is there parking?" },
          ],
        },
        {
          type: "dialogue",
          heading: "Booking by phone",
          lines: [
            { speaker: "You", l1: "Bonjour, je voudrais réserver une chambre pour deux nuits.", en: "Hello, I'd like to book a room for two nights." },
            { speaker: "Hôtel", l1: "Pour quelles dates?", en: "For which dates?" },
            { speaker: "You", l1: "Du 12 au 14 mai. Une chambre double, s'il vous plaît.", en: "From the 12th to the 14th of May. A double room, please." },
            { speaker: "Hôtel", l1: "Très bien. C'est cent dix euros par nuit, petit-déjeuner compris.", en: "Very well. It's €110 per night, breakfast included." },
            { speaker: "You", l1: "Est-ce qu'il y a la climatisation?", en: "Is there air conditioning?" },
            { speaker: "Hôtel", l1: "Oui, dans toutes les chambres.", en: "Yes, in all the rooms." },
          ],
        },
        {
          type: "translate",
          heading: "Translate",
          direction: "en-to-l1",
          prompt: "I'd like to book a quiet room for three nights, from the 8th to the 11th.",
          reference: "Je voudrais réserver une chambre calme pour trois nuits, du 8 au 11.",
          hint: "book = réserver; quiet room = chambre calme; from … to … = du … au …",
        },
      ],
    },
    {
      slug: "hotel-problemes",
      title: "Problems & checking out",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "When something's wrong — politely",
          body: [
            "Even nice hotels have issues. The polite opener is <em>J'ai un (petit) problème avec…</em> and the key phrase for broken things is <em>ne marche pas</em> / <em>ne fonctionne pas</em> (doesn't work).",
            "Common complaints: noise (<em>il y a trop de bruit</em>), temperature (<em>il fait trop chaud / froid</em>), cleanliness (<em>la chambre n'est pas propre</em>), or something missing (<em>il n'y a pas de serviettes</em>).",
            "At check-out, you'll settle <em>la note</em> (the bill — also <em>la facture</em>), maybe ask for a late departure (<em>un départ tardif</em>), and leave bags in <em>la consigne</em> (luggage room) if your train is later.",
          ],
          keyPoint: "Broken: ne marche pas / ne fonctionne pas. Bill: la note / la facture. Bag storage: la consigne.",
        },
        {
          type: "vocab",
          heading: "Problems & check-out",
          items: [
            { l1: "J'ai un problème avec…", en: "I have a problem with…" },
            { l1: "Le chauffage ne marche pas.", en: "The heating doesn't work." },
            { l1: "Il y a trop de bruit.", en: "There's too much noise." },
            { l1: "La chambre n'est pas propre.", en: "The room isn't clean." },
            { l1: "Il n'y a pas de serviettes.", en: "There are no towels." },
            { l1: "Est-ce que je peux changer de chambre?", en: "Can I change rooms?" },
            { l1: "la note / la facture", en: "the bill / the invoice" },
            { l1: "un départ tardif", en: "a late check-out" },
            { l1: "la consigne (à bagages)", en: "the luggage storage" },
            { l1: "Pouvez-vous appeler un taxi?", en: "Can you call a taxi?" },
          ],
        },
        {
          type: "dialogue",
          heading: "Reporting a problem & checking out",
          lines: [
            { speaker: "You", l1: "Bonjour, j'ai un problème. La climatisation ne marche pas.", en: "Hello, I have a problem. The air conditioning doesn't work." },
            { speaker: "Réception", l1: "Je suis désolé. J'envoie quelqu'un tout de suite.", en: "I'm sorry. I'll send someone right away." },
            { speaker: "You", l1: "Merci. Et demain, est-ce qu'un départ tardif est possible?", en: "Thanks. And tomorrow, is a late check-out possible?" },
            { speaker: "Réception", l1: "Oui, jusqu'à quatorze heures, sans supplément.", en: "Yes, until 2 pm, at no extra charge." },
            { speaker: "You", l1: "Parfait. Je peux laisser mes bagages à la consigne après?", en: "Perfect. Can I leave my bags in the luggage room after?" },
            { speaker: "Réception", l1: "Bien sûr, aucun problème.", en: "Of course, no problem." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Problems check",
          questions: [
            {
              q: "How do you say 'The heating doesn't work'?",
              options: ["Le chauffage est cassé une fois.", "Le chauffage ne marche pas.", "Je n'aime pas le chauffage.", "Le chauffage est chaud."],
              correct: 1,
              fb: "'ne marche pas' / 'ne fonctionne pas' = doesn't work — the go-to phrase for broken things.",
            },
            {
              q: "'La note' at check-out means…",
              options: ["the key", "the bill", "the note/message", "the receipt only"],
              correct: 1,
              fb: "'La note' (or 'la facture') is the hotel bill.",
            },
            {
              q: "Where can you leave luggage after check-out?",
              options: ["la consigne", "la réception seulement", "le coffre-fort", "l'ascenseur"],
              correct: 0,
              fb: "'La consigne (à bagages)' is the luggage-storage room.",
            },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "Ground floor in a French hotel is called…", options: ["premier étage", "rez-de-chaussée", "sous-sol", "zéro étage"], correct: 1 },
      { q: "How do you say 'breakfast included'?", options: ["le déjeuner inclus", "le petit-déjeuner inclus", "le dîner inclus", "la nourriture incluse"], correct: 1 },
      { q: "'L'enregistrement' at a hotel means…", options: ["checkout", "check-in", "passport control", "room number"], correct: 1 },
      { q: "RER B from CDG to central Paris takes about…", options: ["10 minutes", "35 minutes", "1 hour", "2 hours"], correct: 1 },
      { q: "How do you say 'Do you have a reservation?'", options: ["Avez-vous une réservation?", "Est-ce que vous restez?", "Combien de nuits?", "C'est quel étage?"], correct: 0 },
      { q: "'La douche' means…", options: ["the bathroom", "the shower", "the wardrobe", "the sink"], correct: 1 },
    ],
  },
};
