import type { Unit } from "../../types";

export const UNIT_NOMBRES_TEMPS: Unit = {
  slug: "nombres-temps",
  stage: 1,
  order: 3,
  icon: "🔢",
  title: "Numbers, days & time",
  tagline: "0–1000, les jours, les mois, quelle heure est-il?",
  badge: "core",
  lessons: [
    {
      slug: "nombres-0-100",
      title: "Numbers 0–100",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "French numbers: smooth until 70, then weird",
          body: [
            "Numbers 1–69 follow a pattern similar to Spanish or Italian. Then French gets unusual: 70 is <em>soixante-dix</em> (sixty-ten), 80 is <em>quatre-vingts</em> (four-twenties), and 90 is <em>quatre-vingt-dix</em> (four-twenty-ten).",
            "This vigesimal (base-20) quirk is a relic of older counting systems and is one of the first things every French learner notices. Belgium and Switzerland use different words (<em>septante</em>, <em>huitante</em>, <em>nonante</em>) — but in France, you use the compound forms.",
            "The good news: once you know the pattern, the logic is consistent. 71 = soixante-onze (sixty-eleven), 92 = quatre-vingt-douze (four-twenty-twelve).",
          ],
          tip: {
            label: "Why the vigesimal counting?",
            body: "Historical Celtic influence — the Gauls counted in twenties. France kept the old forms for 70–99 while most of Europe switched to decimal forms.",
          },
        },
        {
          type: "vocab",
          heading: "Numbers 1–20",
          items: [
            { l1: "un / une", en: "1", note: "un (m) / une (f)" },
            { l1: "deux", en: "2" },
            { l1: "trois", en: "3" },
            { l1: "quatre", en: "4" },
            { l1: "cinq", en: "5", note: "final q is silent" },
            { l1: "six", en: "6", note: "final x is silent before consonant" },
            { l1: "sept", en: "7" },
            { l1: "huit", en: "8" },
            { l1: "neuf", en: "9" },
            { l1: "dix", en: "10" },
            { l1: "onze", en: "11" },
            { l1: "douze", en: "12" },
            { l1: "treize", en: "13" },
            { l1: "quatorze", en: "14" },
            { l1: "quinze", en: "15" },
            { l1: "seize", en: "16" },
            { l1: "dix-sept", en: "17" },
            { l1: "dix-huit", en: "18" },
            { l1: "dix-neuf", en: "19" },
            { l1: "vingt", en: "20", note: "final t silent (but pronounced in liaison)" },
          ],
        },
        {
          type: "vocab",
          heading: "Tens and the tricky 70s–90s",
          items: [
            { l1: "trente", en: "30" },
            { l1: "quarante", en: "40" },
            { l1: "cinquante", en: "50" },
            { l1: "soixante", en: "60" },
            { l1: "soixante-dix", en: "70", note: "sixty-ten" },
            { l1: "soixante-onze", en: "71", note: "sixty-eleven" },
            { l1: "quatre-vingts", en: "80", note: "four-twenties (no s when followed by number)" },
            { l1: "quatre-vingt-un", en: "81" },
            { l1: "quatre-vingt-dix", en: "90", note: "four-twenty-ten" },
            { l1: "quatre-vingt-dix-neuf", en: "99" },
            { l1: "cent", en: "100" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Number quiz",
          questions: [
            {
              q: "How do you say 75 in French?",
              options: ["septante-cinq", "soixante-quinze", "soixante-cinq", "quatre-vingt-cinq"],
              correct: 1,
              fb: "soixante-quinze: sixty (soixante) + fifteen (quinze) = 75. This is the standard French form.",
            },
            {
              q: "What does 'quatre-vingts' literally mean?",
              options: ["Forty times two", "Four twenties", "Eighty ones", "Four-eight"],
              correct: 1,
              fb: "'quatre-vingts' = four-twenties = 80. A relic of vigesimal (base-20) counting.",
            },
            {
              q: "How do you say 91?",
              options: ["nonante et un", "quatre-vingt-onze", "soixante-treize", "quatre-vingt-un"],
              correct: 1,
              fb: "quatre-vingt-onze: four-twenty-eleven = 91.",
            },
          ],
        },
      ],
    },
    {
      slug: "nombres-temps-jours",
      title: "Time, days & months",
      estMinutes: 9,
      pages: [
        {
          type: "vocab",
          heading: "Telling time",
          intro: "France uses a 24-hour clock officially (trains, TV), but conversation uses 12-hour with context.",
          items: [
            { l1: "Quelle heure est-il?", en: "What time is it?" },
            { l1: "Il est deux heures.", en: "It's two o'clock.", note: "Liaison: deux-z-heures" },
            { l1: "Il est midi.", en: "It's noon." },
            { l1: "Il est minuit.", en: "It's midnight." },
            { l1: "Il est trois heures et demie.", en: "It's three thirty.", note: "et demie = and a half" },
            { l1: "Il est quatre heures et quart.", en: "It's four fifteen.", note: "et quart = and a quarter" },
            { l1: "Il est cinq heures moins le quart.", en: "It's quarter to five.", note: "moins le quart = minus a quarter" },
            { l1: "du matin / de l'après-midi / du soir", en: "in the morning / afternoon / evening" },
          ],
        },
        {
          type: "vocab",
          heading: "Days of the week",
          intro: "French days are not capitalized.",
          items: [
            { l1: "lundi", en: "Monday" },
            { l1: "mardi", en: "Tuesday" },
            { l1: "mercredi", en: "Wednesday" },
            { l1: "jeudi", en: "Thursday" },
            { l1: "vendredi", en: "Friday" },
            { l1: "samedi", en: "Saturday" },
            { l1: "dimanche", en: "Sunday" },
            { l1: "le week-end", en: "the weekend", note: "Yes, borrowed from English" },
          ],
        },
        {
          type: "vocab",
          heading: "Months & dates",
          intro: "Months are not capitalized either. Dates go day–month–year.",
          items: [
            { l1: "janvier / février / mars", en: "January / February / March" },
            { l1: "avril / mai / juin", en: "April / May / June" },
            { l1: "juillet / août / septembre", en: "July / August / September" },
            { l1: "octobre / novembre / décembre", en: "October / November / December" },
            { l1: "Nous sommes le lundi 5 juin.", en: "It's Monday, June 5th.", note: "French: day number then month" },
            { l1: "C'est quand, ton anniversaire?", en: "When is your birthday?" },
            { l1: "C'est le 14 juillet.", en: "It's July 14th.", note: "Bastille Day!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Fill in the number or time",
          items: [
            { template: "Il est ___ heures et demie. (3:30)", answer: "trois", en: "It is three thirty." },
            { template: "Aujourd'hui c'est ___. (the fifth)", answer: "le cinq", en: "Today is the fifth." },
            { template: "Il y a ___ jours dans une semaine. (7)", answer: "sept", en: "There are 7 days in a week." },
            { template: "___ + ___ = vingt. (10+10)", answer: "dix", en: "Ten + ten = twenty.", options: ["cinq", "dix", "sept", "huit"] },
          ],
        },
        {
          type: "translate",
          heading: "Say it in French",
          direction: "en-to-l1",
          prompt: "What time is it? It's quarter to nine in the morning.",
          reference: "Quelle heure est-il? Il est neuf heures moins le quart du matin.",
          hint: "neuf heures moins le quart = nine o'clock minus the quarter",
        },
      ],
    },
    {
      slug: "nombres-prix-ordinaux",
      title: "Big numbers, prices & ordinals",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Hundreds, thousands & paying in euros",
          body: [
            "Past 100, French stays regular: <em>cent</em> (100), <em>deux cents</em> (200), <em>mille</em> (1000), <em>un million</em> (a million). Note <em>cent</em> takes an -s when multiplied and standing alone (<em>deux cents</em>) but drops it before another number (<em>deux cent cinq</em> = 205). <em>Mille</em> never changes.",
            "France uses the euro (€). Prices are spoken with <em>euros</em> and <em>centimes</em>: <em>3,50 €</em> is 'trois euros cinquante'. Notice the comma — French uses a comma for the decimal point and a space (or period) for thousands: <em>1 250,75</em>.",
            "To ask and state prices you'll mostly use <em>Ça coûte combien?</em> (How much does it cost?) and <em>Ça fait…</em> (That comes to…), which you'll hear at every till.",
          ],
          keyPoint: "cent → cents when multiplied & final; mille is invariable. Decimal = comma. 3,50 € = 'trois euros cinquante'.",
        },
        {
          type: "vocab",
          heading: "Big numbers & money",
          items: [
            { l1: "cent", en: "100" },
            { l1: "deux cents", en: "200", note: "-s when multiplied and final" },
            { l1: "deux cent cinquante", en: "250", note: "no -s before another number" },
            { l1: "mille", en: "1000", note: "never takes -s" },
            { l1: "un million (de)", en: "a million", note: "needs 'de' before a noun: un million d'euros" },
            { l1: "l'euro (m) / les centimes", en: "the euro / the cents" },
            { l1: "Ça coûte combien?", en: "How much does it cost?" },
            { l1: "Ça fait dix euros cinquante.", en: "That comes to €10.50." },
            { l1: "C'est trop cher.", en: "It's too expensive." },
            { l1: "Vous acceptez la carte?", en: "Do you take card?" },
          ],
        },
        {
          type: "vocab",
          heading: "Ordinal numbers & floors",
          intro: "Ordinals add -ième (except 'first'). Essential for directions, floors, and dates of kings.",
          items: [
            { l1: "premier / première", en: "first", note: "the only irregular one; agrees in gender" },
            { l1: "deuxième (or second/e)", en: "second" },
            { l1: "troisième", en: "third" },
            { l1: "quatrième / cinquième", en: "fourth / fifth", note: "cinq → cinquième (add u)" },
            { l1: "neuvième", en: "ninth", note: "neuf → neuvième (f → v)" },
            { l1: "le rez-de-chaussée", en: "the ground floor", note: "NOT the 'first floor'!" },
            { l1: "le premier étage", en: "the first floor (one up)", note: "= US 'second floor'" },
            { l1: "le cinquième arrondissement", en: "the 5th district (of Paris)", note: "Paris has 20 arrondissements" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the till",
          setup: "You're buying a few things at a small shop.",
          lines: [
            { speaker: "Vendeur", l1: "Alors, ça fait douze euros quarante.", en: "So, that comes to €12.40." },
            { speaker: "You", l1: "Vous acceptez la carte?", en: "Do you take card?" },
            { speaker: "Vendeur", l1: "Oui, bien sûr. À partir de dix euros.", en: "Yes, of course. From €10 up." },
            { speaker: "You", l1: "Parfait. Et le café, c'est à quel étage?", en: "Perfect. And the café, what floor is it on?" },
            { speaker: "Vendeur", l1: "Au premier étage, après l'escalier.", en: "On the first floor, past the stairs." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Numbers in context",
          items: [
            { template: "Ça fait ___ euros. (100)", answer: "cent", en: "That comes to 100 euros." },
            { template: "J'habite au ___ étage. (3rd)", answer: "troisième", en: "I live on the third floor." },
            { template: "C'est le ___ jour. (1st, masculine)", answer: "premier", en: "It's the first day." },
            { template: "Il y a ___ habitants. (a million)", answer: "un million d'", en: "There are a million inhabitants.", options: ["un million", "un million de", "un million d'", "mille"] },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Money & ordinals check",
          questions: [
            {
              q: "How is '3,50 €' spoken in French?",
              options: ["trois point cinquante euros", "trois euros cinquante", "trois virgule cinq euros", "trois cinquante centimes"],
              correct: 1,
              fb: "Prices: number + euros + the cents. The comma is the decimal mark: trois euros cinquante.",
            },
            {
              q: "In France, 'le premier étage' is…",
              options: ["the ground floor", "one floor above the ground floor", "the basement", "the top floor"],
              correct: 1,
              fb: "Ground floor = rez-de-chaussée. Le premier étage is the next one up (the US 'second floor').",
            },
            {
              q: "Which is correct for 250?",
              options: ["deux cents cinquante", "deux cent cinquante", "deux mille cinquante", "deux cinquante cents"],
              correct: 1,
              fb: "'cent' drops its -s before another number: deux cent cinquante.",
            },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "How do you say 70 in France (not Belgium)?",
        options: ["septante", "soixante-dix", "soixante-onze", "setante"],
        correct: 1,
      },
      {
        q: "What does 'quatre-vingts' mean literally?",
        options: ["Eighty-four", "Four-twenties", "Four-eights", "Eighty"],
        correct: 1,
      },
      {
        q: "'Il est midi' means…",
        options: ["It's midnight", "It's noon", "It's my birthday", "It's Tuesday"],
        correct: 1,
      },
      {
        q: "How do you say 'It's 3:30'?",
        options: ["Il est trois heures moins demie", "Il est trois heures et demie", "Il est trente minutes trois", "Il est demi-trois"],
        correct: 1,
      },
      {
        q: "What day comes after mercredi?",
        options: ["mardi", "vendredi", "jeudi", "samedi"],
        correct: 2,
      },
      {
        q: "French dates are written…",
        options: ["month–day–year", "day–month–year", "year–month–day", "day–year–month"],
        correct: 1,
      },
      {
        q: "How do you say 81?",
        options: ["quatre-vingt-deux", "quatre-vingt-un", "soixante-vingt-un", "octante-un"],
        correct: 1,
      },
      {
        q: "'Moins le quart' in time means…",
        options: ["And a quarter", "Quarter to (minus 15 min)", "And a half", "Quarter past"],
        correct: 1,
      },
    ],
  },
};
