import type { Unit } from "../../types";

export const UNIT_URGENCES: Unit = {
  slug: "urgences",
  stage: 3,
  order: 13,
  icon: "🆘",
  title: "Emergencies & help",
  tagline: "Pharmacie, urgences, au secours, pouvez-vous m'aider?",
  lessons: [
    {
      slug: "urgences-main",
      title: "Getting help when you need it",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Emergency numbers in France",
          body: [
            "France's main emergency numbers: <strong>15</strong> (SAMU — medical), <strong>17</strong> (Police), <strong>18</strong> (Pompiers — fire), <strong>112</strong> (EU universal emergency). 112 works from any phone including no-credit mobiles.",
            "For minor medical issues, the first stop should be a <em>pharmacie</em> (pharmacy). French pharmacists are highly trained and can advise on many conditions without needing a doctor. Look for the green cross sign.",
            "Emergency rooms (<em>les urgences</em>) are in public hospitals. You don't need insurance to be treated — you may receive a bill later. Bring your passport. European EHIC cardholders get coverage; US visitors should claim via travel insurance.",
          ],
          tip: {
            label: "Pharmacie first",
            body: "French pharmacists can diagnose and treat many common issues (cuts, infections, minor illnesses). They'll direct you to a doctor if needed. This saves hours compared to going straight to urgences.",
          },
        },
        {
          type: "vocab",
          heading: "Emergency vocabulary",
          items: [
            { l1: "Au secours!", en: "Help!" },
            { l1: "Appelez le SAMU / la police!", en: "Call emergency medical / the police!" },
            { l1: "J'ai besoin d'aide.", en: "I need help." },
            { l1: "Pouvez-vous m'aider?", en: "Can you help me?" },
            { l1: "C'est urgent.", en: "It's urgent." },
            { l1: "la pharmacie", en: "the pharmacy" },
            { l1: "les urgences", en: "the emergency room / A&E" },
            { l1: "l'hôpital", en: "the hospital" },
            { l1: "le médecin", en: "the doctor" },
            { l1: "Je suis malade.", en: "I am sick." },
            { l1: "J'ai mal à…", en: "I have pain in… / My … hurts", note: "J'ai mal à la tête = I have a headache" },
            { l1: "Je suis allergique à…", en: "I am allergic to…" },
          ],
        },
        {
          type: "vocab",
          heading: "Body parts (for pain descriptions)",
          items: [
            { l1: "la tête", en: "the head", note: "J'ai mal à la tête = headache" },
            { l1: "le ventre / l'estomac", en: "the stomach / belly" },
            { l1: "le bras", en: "the arm" },
            { l1: "la jambe", en: "the leg" },
            { l1: "le dos", en: "the back" },
            { l1: "la gorge", en: "the throat" },
            { l1: "la poitrine", en: "the chest" },
            { l1: "les dents", en: "the teeth", note: "J'ai mal aux dents = toothache" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the pharmacy",
          lines: [
            { speaker: "You", l1: "Bonjour. J'ai mal à la gorge et de la fièvre.", en: "Hello. I have a sore throat and a fever." },
            { speaker: "Pharmacist", l1: "Depuis quand?", en: "Since when?" },
            { speaker: "You", l1: "Depuis hier soir.", en: "Since last night." },
            { speaker: "Pharmacist", l1: "Vous êtes allergique à un médicament?", en: "Are you allergic to any medication?" },
            { speaker: "You", l1: "Non, pas que je sache.", en: "No, not that I know of." },
            { speaker: "Pharmacist", l1: "Voilà du paracétamol et un spray pour la gorge.", en: "Here is some paracetamol and a throat spray." },
          ],
        },
        {
          type: "translate",
          heading: "Translate",
          direction: "en-to-l1",
          prompt: "Help! I need a doctor. My friend is sick.",
          reference: "Au secours! J'ai besoin d'un médecin. Mon ami est malade.",
          hint: "d'un = de + un (after besoin de); malade = sick",
        },
      ],
    },
    {
      slug: "urgences-medecin",
      title: "At the doctor: symptoms",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Describing how you feel",
          body: [
            "Beyond <em>j'ai mal à…</em>, you'll want to describe symptoms. Many use <em>avoir</em>: <em>j'ai de la fièvre</em> (I have a fever), <em>j'ai mal au cœur</em> (I feel nauseous — literally 'pain in the heart'), <em>j'ai la nausée</em>. Others are verbs: <em>tousser</em> (to cough), <em>vomir</em> (to vomit), <em>éternuer</em> (to sneeze).",
            "To say how long it's been going on, use <em>depuis</em>: <em>depuis hier</em> (since yesterday), <em>depuis trois jours</em> (for three days).",
            "At the end you may get <em>une ordonnance</em> (a prescription) to take to the pharmacy, or a <em>rendez-vous</em> (appointment) with a specialist.",
          ],
          keyPoint: "Symptoms: j'ai de la fièvre, je tousse, j'ai mal au cœur. Duration: depuis + time. ordonnance = prescription.",
        },
        {
          type: "vocab",
          heading: "Symptoms & the doctor's office",
          items: [
            { l1: "j'ai de la fièvre", en: "I have a fever" },
            { l1: "tousser", en: "to cough" },
            { l1: "éternuer", en: "to sneeze" },
            { l1: "vomir", en: "to vomit" },
            { l1: "j'ai mal au cœur", en: "I feel nauseous", note: "NOT a heart problem" },
            { l1: "j'ai un rhume / la grippe", en: "I have a cold / the flu" },
            { l1: "je suis fatigué(e) / épuisé(e)", en: "I'm tired / exhausted" },
            { l1: "une ordonnance", en: "a prescription" },
            { l1: "un médicament / un comprimé", en: "a medicine / a tablet" },
            { l1: "prendre rendez-vous", en: "to make an appointment" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the doctor",
          lines: [
            { speaker: "Médecin", l1: "Bonjour, qu'est-ce qui ne va pas?", en: "Hello, what's wrong?" },
            { speaker: "You", l1: "J'ai de la fièvre et je tousse depuis trois jours.", en: "I have a fever and I've been coughing for three days." },
            { speaker: "Médecin", l1: "Vous avez mal à la gorge?", en: "Do you have a sore throat?" },
            { speaker: "You", l1: "Oui, un peu. Et j'ai mal à la tête.", en: "Yes, a little. And I have a headache." },
            { speaker: "Médecin", l1: "C'est un gros rhume. Voici une ordonnance.", en: "It's a bad cold. Here's a prescription." },
            { speaker: "You", l1: "Merci. Je dois prendre les comprimés combien de fois par jour?", en: "Thanks. How many times a day should I take the tablets?" },
            { speaker: "Médecin", l1: "Deux fois par jour, après les repas.", en: "Twice a day, after meals." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Describe your symptoms",
          items: [
            { template: "J'ai de la ___ depuis hier. (fever)", answer: "fièvre", en: "I've had a fever since yesterday." },
            { template: "Je ___ beaucoup la nuit. (cough)", answer: "tousse", en: "I cough a lot at night." },
            { template: "Le médecin me donne une ___. (prescription)", answer: "ordonnance", en: "The doctor gives me a prescription." },
            { template: "J'ai mal ___ tête. (à la)", answer: "à la", en: "I have a headache.", options: ["à la", "au", "aux", "à l'"] },
          ],
        },
        {
          type: "translate",
          heading: "Translate",
          direction: "en-to-l1",
          prompt: "I've had a fever for two days and I have a sore throat.",
          reference: "J'ai de la fièvre depuis deux jours et j'ai mal à la gorge.",
          hint: "'for two days' (still ongoing) = depuis deux jours; sore throat = mal à la gorge",
        },
      ],
    },
    {
      slug: "urgences-vol",
      title: "Lost, stolen & safety",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "If something goes missing",
          body: [
            "Pickpocketing happens around tourist sites and on the metro. Two key verbs: <em>perdre</em> (to lose) → <em>j'ai perdu</em> (I've lost), and <em>voler</em> (to steal) → <em>on m'a volé…</em> (someone stole my…). Note the structure: French says 'one stole me my wallet.'",
            "To report a theft, go to <em>le commissariat</em> (police station) and file <em>une plainte</em> (a report). You'll need it for insurance. For a lost passport, contact <em>l'ambassade</em> or <em>le consulat</em>.",
            "Useful nouns: <em>le portefeuille</em> (wallet), <em>le sac</em> (bag), <em>le passeport</em>, <em>le téléphone</em>, <em>les papiers</em> (documents/ID).",
          ],
          keyPoint: "j'ai perdu = I've lost. On m'a volé mon… = my … was stolen. Report: porter plainte au commissariat.",
        },
        {
          type: "vocab",
          heading: "Lost & stolen vocabulary",
          items: [
            { l1: "j'ai perdu…", en: "I've lost…" },
            { l1: "on m'a volé…", en: "someone stole my…", note: "lit. 'one stole me…'" },
            { l1: "le portefeuille", en: "the wallet" },
            { l1: "le sac (à main)", en: "the (hand)bag" },
            { l1: "le passeport / les papiers", en: "the passport / the documents" },
            { l1: "le commissariat (de police)", en: "the police station" },
            { l1: "porter plainte", en: "to file a police report" },
            { l1: "l'ambassade / le consulat", en: "the embassy / the consulate" },
            { l1: "bloquer ma carte bancaire", en: "to block my bank card" },
            { l1: "le bureau des objets trouvés", en: "the lost-and-found office" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the police station",
          lines: [
            { speaker: "You", l1: "Bonjour. On m'a volé mon portefeuille dans le métro.", en: "Hello. My wallet was stolen on the metro." },
            { speaker: "Agent", l1: "Je suis désolé. Vous voulez porter plainte?", en: "I'm sorry. Do you want to file a report?" },
            { speaker: "You", l1: "Oui, s'il vous plaît. Il y avait ma carte bancaire dedans.", en: "Yes, please. My bank card was inside." },
            { speaker: "Agent", l1: "Bloquez votre carte tout de suite. Vous avez vos papiers?", en: "Block your card right away. Do you have your ID?" },
            { speaker: "You", l1: "Oui, mon passeport est à l'hôtel.", en: "Yes, my passport is at the hotel." },
            { speaker: "Agent", l1: "Bien. Remplissez ce formulaire, s'il vous plaît.", en: "Good. Fill out this form, please." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Safety check",
          questions: [
            {
              q: "How do you say 'someone stole my bag'?",
              options: ["J'ai volé mon sac.", "On m'a volé mon sac.", "Mon sac est volé moi.", "Je perds mon sac."],
              correct: 1,
              fb: "French uses 'On m'a volé mon sac' — literally 'one stole me my bag.'",
            },
            {
              q: "Where do you go to file a theft report?",
              options: ["la pharmacie", "le commissariat", "l'hôpital", "le consulat"],
              correct: 1,
              fb: "'Le commissariat' is the police station; you 'porter plainte' there.",
            },
            {
              q: "For a lost passport, you contact…",
              options: ["le commissariat only", "l'ambassade or le consulat", "les urgences", "la consigne"],
              correct: 1,
              fb: "Your country's embassy/consulate handles lost passports.",
            },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "The French medical emergency number is…", options: ["17", "18", "15", "112"], correct: 2 },
      { q: "'J'ai mal à la tête' means…", options: ["My throat hurts", "I have a headache", "I'm sick", "I need a doctor"], correct: 1 },
      { q: "For minor issues in France, the first stop should be…", options: ["the hospital", "the pharmacy", "the police", "the embassy"], correct: 1 },
      { q: "'Au secours!' means…", options: ["Excuse me!", "Help!", "Watch out!", "Stop!"], correct: 1 },
      { q: "'Je suis allergique à…' means…", options: ["I like…", "I am allergic to…", "I need…", "I am afraid of…"], correct: 1 },
      { q: "How do you say 'Call the police!'?", options: ["Appelez la police!", "Allez à la police!", "La police est là?", "Aidez la police!"], correct: 0 },
    ],
  },
};
