import type { Unit } from "../../types";

export const UNIT_NUMBERS_TIME: Unit = {
  slug: "numbers-time",
  stage: 1,
  order: 3,
  icon: "🔢",
  title: "Numbers, days & time",
  tagline: "0–1000 (and the einundzwanzig flip), dates, Uhrzeit, prices.",
  badge: "core",
  lessons: [
    {
      slug: "numbers-time-counting",
      title: "Numbers 0–1000 & the units-first flip",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "German says the ones before the tens",
          body: [
            "Counting 0–12 is just vocabulary: <em>null, eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn, elf, zwölf</em>. From 13–19 you add <strong>-zehn</strong> to the unit: <em>dreizehn</em> (13), <em>vierzehn</em> (14)… with two spelling quirks: <strong>sechzehn</strong> (16, no -s) and <strong>siebzehn</strong> (17, no -en).",
            "The tens end in <strong>-zig</strong>: <em>zwanzig</em> (20), <em>dreißig</em> (30 — note the ß!), <em>vierzig</em>, <em>fünfzig</em>, <strong>sechzig</strong> (60), <strong>siebzig</strong> (70), <em>achtzig</em>, <em>neunzig</em>.",
            "Here's the famous twist: for 21–99 you say the <strong>units first, joined by <em>und</em></strong>. 21 is <em>einundzwanzig</em> — literally 'one-and-twenty'. 47 is <em>siebenundvierzig</em> ('seven-and-forty'). It's written as one long word.",
            "Hundreds and thousands: <em>hundert</em> (100), <em>zweihundert</em> (200), <em>tausend</em> (1000). So 234 is <em>zweihundertvierunddreißig</em>.",
          ],
          keyPoint:
            "21–99 flip the order: einundzwanzig = 'one-and-twenty'. Write it as one word.",
        },
        {
          type: "vocab",
          heading: "0–20",
          items: [
            { l1: "null", en: "0" },
            { l1: "eins", en: "1", note: "becomes 'ein' before a noun: ein Euro" },
            { l1: "zwei", en: "2" },
            { l1: "drei", en: "3" },
            { l1: "vier", en: "4" },
            { l1: "fünf", en: "5" },
            { l1: "sechs", en: "6" },
            { l1: "sieben", en: "7" },
            { l1: "acht", en: "8" },
            { l1: "neun", en: "9" },
            { l1: "zehn", en: "10" },
            { l1: "elf", en: "11" },
            { l1: "zwölf", en: "12" },
            { l1: "dreizehn", en: "13" },
            { l1: "sechzehn", en: "16", note: "drops the 's' of sechs" },
            { l1: "siebzehn", en: "17", note: "drops the 'en' of sieben" },
            { l1: "zwanzig", en: "20" },
          ],
        },
        {
          type: "vocab",
          heading: "Tens, hundreds, thousand",
          items: [
            { l1: "zwanzig", en: "20" },
            { l1: "dreißig", en: "30", note: "spelled with ß, not -zig" },
            { l1: "vierzig", en: "40" },
            { l1: "fünfzig", en: "50" },
            { l1: "sechzig", en: "60", note: "drops the 's'" },
            { l1: "siebzig", en: "70", note: "drops the 'en'" },
            { l1: "achtzig", en: "80" },
            { l1: "neunzig", en: "90" },
            { l1: "(ein)hundert", en: "100" },
            { l1: "tausend", en: "1000" },
          ],
        },
        {
          type: "tip",
          heading: "Building a two-digit number",
          body: "Take the unit, add <strong>und</strong>, then the ten — all glued together. <em>5 + und + 40</em> = <strong>fünfundvierzig</strong> (45). The only oddity: '1' in this position is <em>ein</em> (no -s): <strong>einundzwanzig</strong> (21), not 'einsundzwanzig'.",
          example: { l1: "67 = siebenundsechzig", en: "seven-and-sixty" },
        },
        {
          type: "fillBlank",
          heading: "Write the number in words",
          intro: "Type the German word for each number.",
          items: [
            { template: "21 = ___", answer: "einundzwanzig", en: "twenty-one" },
            { template: "33 = ___", answer: "dreiunddreißig", en: "thirty-three" },
            { template: "48 = ___", answer: "achtundvierzig", en: "forty-eight" },
            { template: "16 = ___", answer: "sechzehn", en: "sixteen" },
            { template: "100 = ___", answer: "hundert", en: "one hundred", options: ["hundert", "tausend", "zwanzig", "zehnzig"] },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Number check",
          questions: [
            {
              q: "How do you say 21 in German?",
              options: ["zwanzigeins", "einsundzwanzig", "einundzwanzig", "zwanzigundein"],
              correct: 2,
              fb: "Units first, joined by und, '1' is 'ein': einundzwanzig.",
            },
            {
              q: "Which is 30?",
              options: ["dreizig", "dreißig", "dreizehn", "dreihundert"],
              correct: 1,
              fb: "30 is dreißig — spelled with ß, the one ten that doesn't end in -zig.",
            },
            {
              q: "'siebenundsechzig' is which number?",
              options: ["76", "67", "66", "77"],
              correct: 1,
              fb: "seven (sieben) + and + sixty (sechzig) = 67.",
            },
          ],
        },
      ],
    },
    {
      slug: "numbers-time-days-dates",
      title: "Days, months & dates",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Days, months, and how to give a date",
          body: [
            "All days of the week are <strong>masculine</strong> (<em>der</em>) and most end in <strong>-tag</strong>: <em>Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag</em>. Note <strong>Mittwoch</strong> ('mid-week') breaks the pattern. To say 'on Monday' use <strong>am</strong>: <em>am Montag</em>.",
            "Months are also masculine and look close to English: <em>Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember</em>. 'In May' = <strong>im Mai</strong>.",
            "Dates use <strong>ordinal numbers</strong> with a dot: <em>der 1. = der erste</em>, <em>der 2. = der zweite</em>, <em>der 3. = der dritte</em>. To say 'on the 3rd of October' you say <strong>am dritten Oktober</strong>. Germans write dates day-first: <strong>3.10.2026</strong>.",
          ],
          keyPoint: "Days & months are masculine. 'on Monday' = am Montag; 'in May' = im Mai.",
        },
        {
          type: "vocab",
          heading: "The week",
          intro: "All masculine; 'on X-day' uses am.",
          items: [
            { l1: "der Montag", en: "Monday", note: "am Montag = on Monday" },
            { l1: "der Dienstag", en: "Tuesday" },
            { l1: "der Mittwoch", en: "Wednesday", note: "'mid-week' — no -tag ending" },
            { l1: "der Donnerstag", en: "Thursday" },
            { l1: "der Freitag", en: "Friday" },
            { l1: "der Samstag", en: "Saturday", note: "Sonnabend in parts of the north/east" },
            { l1: "der Sonntag", en: "Sunday" },
            { l1: "das Wochenende", en: "the weekend", note: "am Wochenende = on the weekend" },
            { l1: "heute", en: "today" },
            { l1: "morgen", en: "tomorrow", note: "lowercase = tomorrow; der Morgen = the morning" },
            { l1: "gestern", en: "yesterday" },
          ],
        },
        {
          type: "vocab",
          heading: "Months & ordinals for dates",
          items: [
            { l1: "der Januar", en: "January" },
            { l1: "der März", en: "March", note: "note the ä" },
            { l1: "der Mai", en: "May", note: "im Mai = in May" },
            { l1: "der Juni", en: "June" },
            { l1: "der Juli", en: "July" },
            { l1: "der Dezember", en: "December" },
            { l1: "der erste", en: "the first (1.)", note: "der erste Mai = 1 May" },
            { l1: "der zweite", en: "the second (2.)" },
            { l1: "der dritte", en: "the third (3.)", note: "irregular — not 'drittte'" },
          ],
        },
        {
          type: "dialogue",
          heading: "Making a plan",
          setup: "Two friends fixing a day to meet in Berlin.",
          lines: [
            { speaker: "Lena", l1: "Hast du am Freitag Zeit?", en: "Do you have time on Friday?" },
            { speaker: "Du", l1: "Nein, am Freitag arbeite ich.", en: "No, on Friday I work." },
            { speaker: "Lena", l1: "Und am Wochenende?", en: "And on the weekend?" },
            { speaker: "Du", l1: "Samstag ist super. Der wievielte ist das?", en: "Saturday is great. What date is that?" },
            { speaker: "Lena", l1: "Der vierte Oktober.", en: "The fourth of October." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "On Monday I work, but on the weekend I have time.",
          reference: "Am Montag arbeite ich, aber am Wochenende habe ich Zeit.",
          hint: "Use 'am' for both. After a time phrase the verb comes second: Am Montag arbeite ich.",
        },
        {
          type: "fillBlank",
          heading: "am or im?",
          intro: "'am' for days, 'im' for months/seasons.",
          items: [
            { template: "Ich habe ___ Sonntag frei.", answer: "am", en: "I'm free on Sunday.", options: ["am", "im", "um", "in"] },
            { template: "Mein Geburtstag ist ___ Mai.", answer: "im", en: "My birthday is in May.", options: ["am", "im", "um", "an"] },
            { template: "Wir fahren ___ Wochenende nach Hamburg.", answer: "am", en: "We're going to Hamburg on the weekend.", options: ["am", "im", "um", "in"] },
          ],
        },
      ],
    },
    {
      slug: "numbers-time-clock-prices",
      title: "Telling time & prices in Euro",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Telling the time, German-style",
          body: [
            "To ask, say <strong>Wie spät ist es?</strong> or <strong>Wie viel Uhr ist es?</strong> ('What time is it?'). The reply: <em>Es ist …</em> followed by the time. <strong>Uhr</strong> means 'o'clock': <em>Es ist drei Uhr</em> = 'It's three o'clock.'",
            "For minutes past, use <strong>nach</strong> ('after'); for minutes to, use <strong>vor</strong> ('before'). <em>Viertel nach drei</em> = quarter past three; <em>Viertel vor vier</em> = quarter to four.",
            "Watch the German <strong>halb</strong>: it points to the <em>next</em> hour, not the last one. <strong>halb vier</strong> means 'half-way to four' = <em>3:30</em>, NOT 4:30. This trips up every English speaker exactly once.",
            "For schedules, shops and TV, Germans use the <strong>24-hour clock</strong>: <em>14 Uhr</em> = 2pm, <em>20 Uhr 30</em> = 8:30pm.",
          ],
          keyPoint: "halb vier = 3:30 (half-way to four), not 4:30. nach = past, vor = to.",
        },
        {
          type: "vocab",
          heading: "Clock vocabulary",
          items: [
            { l1: "die Uhr", en: "clock / o'clock", note: "drei Uhr = 3:00" },
            { l1: "die Stunde", en: "hour", note: "die Stunde, -n (f.) — a duration" },
            { l1: "die Minute", en: "minute" },
            { l1: "Viertel nach", en: "quarter past" },
            { l1: "Viertel vor", en: "quarter to" },
            { l1: "halb", en: "half (to the next hour)", note: "halb fünf = 4:30" },
            { l1: "Wie spät ist es?", en: "What time is it?" },
            { l1: "der Euro", en: "euro", note: "price said as: drei Euro fünfzig = €3.50" },
            { l1: "der Cent", en: "cent" },
            { l1: "Was kostet das?", en: "What does that cost?" },
          ],
        },
        {
          type: "tip",
          heading: "Saying a price in Euro",
          body: "Germans read prices as <em>[euros] Euro [cents]</em>, dropping the word 'Cent': <strong>3,50 €</strong> is said <em>drei Euro fünfzig</em>. Note the <strong>comma</strong> as the decimal separator. Very casually you might just hear <em>drei fünfzig</em>.",
          example: { l1: "Das macht zwölf Euro neunzig.", en: "That comes to €12.90." },
        },
        {
          type: "fillBlank",
          heading: "Read the clock",
          intro: "Choose the correct time expression.",
          items: [
            { template: "3:15 = Viertel ___ drei", answer: "nach", en: "quarter past three", options: ["nach", "vor", "halb", "um"] },
            { template: "3:45 = Viertel ___ vier", answer: "vor", en: "quarter to four", options: ["nach", "vor", "halb", "um"] },
            { template: "4:30 = halb ___", answer: "fünf", en: "half past four (half-way to five)", options: ["vier", "fünf", "drei", "sechs"] },
            { template: "2:00 = zwei ___", answer: "Uhr", en: "two o'clock", options: ["Uhr", "Stunde", "Minute", "vor"] },
          ],
        },
        {
          type: "dialogue",
          heading: "Buying a ticket at the Späti",
          setup: "You grab a drink at a late-night corner shop (Späti) and ask the time.",
          lines: [
            { speaker: "Du", l1: "Entschuldigung, wie spät ist es?", en: "Excuse me, what time is it?" },
            { speaker: "Verkäufer", l1: "Es ist halb neun.", en: "It's half past eight (8:30)." },
            { speaker: "Du", l1: "Danke. Was kostet das Wasser?", en: "Thanks. What does the water cost?" },
            { speaker: "Verkäufer", l1: "Eins fünfzig, bitte.", en: "One fifty, please (€1.50)." },
            { speaker: "Du", l1: "Hier, zwei Euro.", en: "Here, two euros." },
            { speaker: "Verkäufer", l1: "Und fünfzig Cent zurück. Danke!", en: "And fifty cents back. Thanks!" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Time & money check",
          questions: [
            {
              q: "'halb vier' means what time?",
              options: ["4:30", "3:30", "4:00", "3:15"],
              correct: 1,
              fb: "halb points to the NEXT hour: halb vier = half-way to four = 3:30.",
            },
            {
              q: "How is €3.50 normally said aloud?",
              options: ["drei Punkt fünfzig", "drei Euro fünfzig", "dreihundertfünfzig", "drei und fünfzig"],
              correct: 1,
              fb: "drei Euro fünfzig — the word 'Cent' is dropped, and the separator is a comma.",
            },
            {
              q: "'Viertel vor sieben' is…",
              options: ["7:15", "6:45", "7:45", "6:15"],
              correct: 1,
              fb: "vor = to. Quarter to seven = 6:45.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "It's half past eight. The water costs one fifty.",
          reference: "Es ist halb neun. Das Wasser kostet eins fünfzig.",
          hint: "Remember halb points to the next hour: 8:30 = halb neun.",
        },
        {
          type: "checkpoint",
          heading: "Lesson check",
          questions: [
            {
              q: "'halb zehn' is what time?",
              options: ["10:30", "9:30", "10:00", "9:15"],
              correct: 1,
            },
            {
              q: "Which preposition means 'past' when telling time?",
              options: ["vor", "nach", "um", "halb"],
              correct: 1,
            },
            {
              q: "How do you ask 'What does that cost?'",
              options: ["Wie spät ist es?", "Was kostet das?", "Wo ist das?", "Wie viel Uhr?"],
              correct: 1,
            },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "How do you say 21 in German?",
        options: ["zwanzigeins", "einundzwanzig", "einsundzwanzig", "zwanzigundeins"],
        correct: 1,
      },
      {
        q: "Which is 30?",
        options: ["dreizig", "dreißig", "dreizehn", "dreihundert"],
        correct: 1,
      },
      {
        q: "'sechsundvierzig' is which number?",
        options: ["64", "46", "66", "44"],
        correct: 1,
      },
      {
        q: "How do you say 'on Monday'?",
        options: ["im Montag", "an Montag", "am Montag", "um Montag"],
        correct: 2,
      },
      {
        q: "How do you say 'in May'?",
        options: ["am Mai", "im Mai", "in Mai", "um Mai"],
        correct: 1,
      },
      {
        q: "Which day breaks the '-tag' pattern?",
        options: ["Montag", "Freitag", "Mittwoch", "Sonntag"],
        correct: 2,
      },
      {
        q: "'halb sechs' means what time?",
        options: ["6:30", "5:30", "6:00", "5:15"],
        correct: 1,
      },
      {
        q: "'Viertel nach acht' is…",
        options: ["7:45", "8:15", "8:45", "8:30"],
        correct: 1,
      },
      {
        q: "How is €4.20 normally said?",
        options: ["vier Punkt zwanzig", "vier Euro zwanzig", "vierhundertzwanzig", "vier zwanzig Cent"],
        correct: 1,
      },
      {
        q: "How do you ask 'What time is it?'",
        options: ["Was kostet das?", "Wie spät ist es?", "Wo ist es?", "Wer ist das?"],
        correct: 1,
      },
    ],
  },
};
