import type { Unit } from "../../types";

export const UNIT_OPINIONS: Unit = {
  slug: "opinions",
  stage: 8,
  order: 35,
  icon: "🗣️",
  title: "Opinions & debate",
  tagline: "Meiner Meinung nach, agreeing & disagreeing, einerseits…andererseits.",
  badge: "advanced",
  lessons: [
    {
      slug: "opinions-stating",
      title: "Giving an opinion",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "How to lead with 'I think…' in German",
          body: [
            "You've reached the final unit. Time to put everything together — subordinate clauses, Konjunktiv, the lot — into real discussion. First, the openers:",
            "<em>Meiner Meinung nach…</em> = In my opinion… (the classic; note it's followed by verb-second, no comma).",
            "<em>Ich finde, dass…</em> / <em>Ich glaube, dass…</em> = I find / believe that… (dass sends the verb to the end — Unit 33 in action).",
            "<em>Ich denke…</em> = I think… · <em>Für mich…</em> = For me… · <em>Ich würde sagen, …</em> = I'd say… (Konjunktiv softener).",
            "<strong>Watch the word order:</strong> after <em>Meiner Meinung nach</em> the verb still comes second — <em>Meiner Meinung nach <strong>ist</strong> Berlin die beste Stadt.</em>",
          ],
          keyPoint:
            "Meiner Meinung nach + verb-second · Ich finde/glaube, dass + verb-final · Ich würde sagen… (soft). Pick one and lead with it.",
        },
        {
          type: "vocab",
          heading: "Opening an opinion",
          intro: "Fixed phrases to launch any opinion.",
          items: [
            { l1: "Meiner Meinung nach…", en: "in my opinion… (most common)", note: "Followed by verb-second word order." },
            { l1: "Ich finde, dass…", en: "I find that…", note: "dass → verb to the end." },
            { l1: "Ich glaube, dass…", en: "I believe that…" },
            { l1: "Ich denke, …", en: "I think, …" },
            { l1: "Ich bin der Meinung, dass…", en: "I'm of the opinion that…" },
            { l1: "Für mich…", en: "for me…" },
            { l1: "Ich würde sagen, …", en: "I'd say… (Konjunktiv, soft)" },
            { l1: "Ehrlich gesagt…", en: "honestly / to be honest…" },
            { l1: "Wenn du mich fragst, …", en: "if you ask me, …" },
            { l1: "Aus meiner Sicht…", en: "from my point of view…" },
            { l1: "Persönlich…", en: "personally…" },
            { l1: "Ich habe das Gefühl, dass…", en: "I have the feeling that…" },
          ],
        },
        {
          type: "dialogue",
          heading: "Talking about the city",
          setup: "Two friends discuss living in Berlin.",
          lines: [
            { speaker: "Nina", l1: "Was hältst du eigentlich von Berlin?", en: "What do you actually think of Berlin?" },
            { speaker: "You", l1: "Meiner Meinung nach ist es die spannendste Stadt Deutschlands.", en: "In my opinion it's the most exciting city in Germany." },
            { speaker: "Nina", l1: "Wirklich? Warum denn?", en: "Really? Why's that?" },
            { speaker: "You", l1: "Ich finde, dass die Mischung aus Kultur und Geschichte einzigartig ist.", en: "I find that the mix of culture and history is unique." },
            { speaker: "Nina", l1: "Ehrlich gesagt finde ich die Mieten zu hoch.", en: "Honestly, I find the rents too high." },
            { speaker: "You", l1: "Da hast du nicht ganz unrecht. Aber ich würde sagen, es lohnt sich trotzdem.", en: "You're not entirely wrong there. But I'd say it's still worth it." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Pick the opener",
          intro: "Mind the word order after each phrase.",
          items: [
            {
              template: "Meiner ___ nach ist das eine gute Idee.",
              answer: "Meinung",
              en: "In my opinion that's a good idea.",
              options: ["Meinung", "Sicht", "Gefühl", "Idee"],
            },
            {
              template: "Ich finde, ___ der Film langweilig war.",
              answer: "dass",
              en: "I find that the film was boring.",
              options: ["dass", "weil", "ob", "wenn"],
            },
            {
              template: "Ich finde, dass die Stadt zu teuer ___ . (sein)",
              answer: "ist",
              en: "I find that the city is too expensive.",
              options: ["ist", "sind", "sein", "war"],
            },
            {
              template: "Ich ___ sagen, das ist Geschmackssache.",
              answer: "würde",
              en: "I'd say that's a matter of taste.",
              options: ["würde", "werde", "will", "habe"],
            },
            {
              template: "___ gesagt, gefällt mir das nicht.",
              answer: "Ehrlich",
              en: "Honestly, I don't like that.",
              options: ["Ehrlich", "Meiner", "Für", "Aus"],
            },
          ],
        },
      ],
    },
    {
      slug: "opinions-agree-disagree",
      title: "Agreeing & disagreeing politely",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Saying yes, saying no — without a fight",
          body: [
            "<strong>Agreeing:</strong>",
            "<em>Da hast du recht.</em> = You're right (there). · <em>Genau.</em> = Exactly. · <em>Das stimmt.</em> = That's true. · <em>Das sehe ich auch so.</em> = I see it that way too. · <em>Ganz meine Meinung.</em> = My thoughts exactly.",
            "<strong>Disagreeing politely:</strong>",
            "<em>Da hast du recht, aber…</em> = You're right, but… (concede first — uses Unit 33 word order). · <em>Das sehe ich anders.</em> = I see it differently. · <em>Da bin ich anderer Meinung.</em> = I'm of a different opinion. · <em>Ich bin mir nicht sicher.</em> = I'm not sure. · <em>Das kann man so nicht sagen.</em> = You can't really say it like that.",
            "The golden move: <strong>concede, then push back</strong> — <em>Da hast du recht, <strong>aber</strong> meiner Meinung nach…</em>",
          ],
          keyPoint:
            "Agree: Da hast du recht / Genau / Das stimmt / Das sehe ich auch so. Disagree softly: Das sehe ich anders / Da bin ich anderer Meinung / Da hast du recht, aber…",
        },
        {
          type: "vocab",
          heading: "Agree / disagree phrases",
          intro: "Berliners debate happily — just keep it on the idea, not the person.",
          items: [
            { l1: "Da hast du recht.", en: "you're right (there)" },
            { l1: "Genau.", en: "exactly" },
            { l1: "Das stimmt.", en: "that's true" },
            { l1: "Das sehe ich auch so.", en: "I see it that way too" },
            { l1: "Ganz meine Meinung.", en: "my thoughts exactly" },
            { l1: "Da bin ich ganz deiner Meinung.", en: "I completely agree with you" },
            { l1: "Das sehe ich anders.", en: "I see it differently" },
            { l1: "Da bin ich anderer Meinung.", en: "I'm of a different opinion" },
            { l1: "Ich bin mir nicht sicher.", en: "I'm not sure" },
            { l1: "Das kann man so nicht sagen.", en: "you can't really say it like that" },
            { l1: "Das stimmt nicht ganz.", en: "that's not entirely true" },
            { l1: "Da muss ich dir widersprechen.", en: "I have to disagree with you there" },
          ],
        },
        {
          type: "tip",
          heading: "Concede first, then disagree",
          body: "Germans value a direct opinion, but the smooth way to disagree is to grant a point before countering it: <strong>Da hast du recht, aber…</strong> or <strong>Das stimmt, allerdings…</strong>. Bald <em>Das ist falsch</em> (that's wrong) sounds harsh; aim it at the idea — <em>Das sehe ich anders</em> (I see it differently) — not the person. <em>aber</em> keeps verb-second order; if you reach for <em>obwohl</em>, remember it sends the verb to the end.",
          example: { l1: "Da hast du recht, aber das ist nicht die ganze Wahrheit.", en: "You're right, but that's not the whole truth." },
        },
        {
          type: "dialogue",
          heading: "A friendly disagreement",
          setup: "Two flatmates debate cars vs bikes in Berlin.",
          lines: [
            { speaker: "Jonas", l1: "In Berlin braucht man kein Auto. Das Fahrrad reicht völlig.", en: "In Berlin you don't need a car. A bike is totally enough." },
            { speaker: "You", l1: "Da hast du recht, aber im Winter sehe ich das anders.", en: "You're right, but in winter I see it differently." },
            { speaker: "Jonas", l1: "Stimmt, bei Schnee ist es unangenehm.", en: "True, when it snows it's unpleasant." },
            { speaker: "You", l1: "Genau. Und mit Kindern bin ich anderer Meinung als du.", en: "Exactly. And with kids I'm of a different opinion than you." },
            { speaker: "Jonas", l1: "Das kann man so nicht sagen — es gibt ja Lastenräder.", en: "You can't really say that — there are cargo bikes, after all." },
            { speaker: "You", l1: "Da muss ich dir widersprechen, die sind sehr teuer.", en: "I have to disagree with you there, those are very expensive." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Agree or disagree?",
          intro: "Match the phrase to the situation.",
          questions: [
            {
              q: "You completely agree. You say:",
              options: ["Das sehe ich anders.", "Ganz meine Meinung.", "Das stimmt nicht.", "Da widerspreche ich."],
              correct: 1,
              fb: "Ganz meine Meinung = my thoughts exactly.",
            },
            {
              q: "You disagree, but politely:",
              options: ["Du hast unrecht!", "Das ist Quatsch.", "Das sehe ich anders.", "Genau."],
              correct: 2,
              fb: "Das sehe ich anders aims at the idea, not the person.",
            },
            {
              q: "You want to concede, then push back. Start with:",
              options: ["Da hast du recht, aber…", "Das ist falsch.", "Nein, nein, nein.", "Genau, und…"],
              correct: 0,
              fb: "Concede first, then counter with aber.",
            },
            {
              q: "You're unsure. You say:",
              options: ["Genau.", "Ich bin mir nicht sicher.", "Das stimmt.", "Ganz meine Meinung."],
              correct: 1,
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Complete the reaction",
          items: [
            {
              template: "Da hast du ___ , das ist ein guter Punkt.",
              answer: "recht",
              en: "You're right, that's a good point.",
              options: ["recht", "Meinung", "stimmt", "genau"],
            },
            {
              template: "Das ___ ich anders.",
              answer: "sehe",
              en: "I see it differently.",
              options: ["sehe", "finde", "glaube", "denke"],
            },
            {
              template: "Da bin ich anderer ___ .",
              answer: "Meinung",
              en: "I'm of a different opinion.",
              options: ["Meinung", "Sicht", "Idee", "Sache"],
            },
            {
              template: "Das ___ , da kann ich nur zustimmen.",
              answer: "stimmt",
              en: "That's true, I can only agree.",
              options: ["stimmt", "sehe", "recht", "genau"],
            },
            {
              template: "Da muss ich dir ___ .",
              answer: "widersprechen",
              en: "I have to disagree with you there.",
              options: ["widersprechen", "zustimmen", "recht", "glauben"],
            },
          ],
        },
      ],
    },
    {
      slug: "opinions-structuring-argument",
      title: "Structuring an argument & wrapping up",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Stringing a real argument together",
          body: [
            "The final skill: organizing several points into one coherent argument — then closing it cleanly.",
            "<em>Einerseits… andererseits…</em> = On the one hand… on the other hand… (the signature German balancing act).",
            "<em>Erstens… zweitens… drittens…</em> = Firstly… secondly… thirdly… · <em>Außerdem…</em> = Besides / moreover… · <em>Zum Beispiel…</em> = For example…",
            "<em>Trotzdem…</em> = Nevertheless… · <em>Deshalb / deswegen…</em> = Therefore… · <em>Zusammenfassend…</em> = To summarize… · <em>Alles in allem…</em> = All in all…",
            "<strong>Word-order reminder:</strong> einerseits, andererseits, außerdem, trotzdem and deshalb all sit in first position, so the verb comes right after — <em>Außerdem <strong>ist</strong> es teuer.</em>",
          ],
          keyPoint:
            "Balance: einerseits… andererseits… Sequence: erstens, zweitens, außerdem. Result: deshalb / trotzdem. Wrap: zusammenfassend / alles in allem.",
        },
        {
          type: "vocab",
          heading: "Discourse connectors",
          intro: "The scaffolding of an argument.",
          items: [
            { l1: "einerseits…", en: "on the one hand…" },
            { l1: "andererseits…", en: "on the other hand…" },
            { l1: "erstens / zweitens / drittens", en: "firstly / secondly / thirdly" },
            { l1: "zunächst / zuerst", en: "first of all" },
            { l1: "außerdem", en: "besides / moreover", note: "Verb comes right after it." },
            { l1: "zum Beispiel", en: "for example" },
            { l1: "trotzdem", en: "nevertheless", note: "First position → verb second." },
            { l1: "deshalb / deswegen", en: "therefore / that's why" },
            { l1: "jedoch", en: "however" },
            { l1: "dennoch", en: "yet / still" },
            { l1: "zusammenfassend", en: "to summarize / in summary" },
            { l1: "alles in allem", en: "all in all" },
            { l1: "abschließend", en: "in closing / finally" },
            { l1: "letztendlich", en: "ultimately / in the end" },
          ],
        },
        {
          type: "dialogue",
          heading: "A reasoned argument",
          setup: "Discussing whether to study abroad in Berlin.",
          lines: [
            { speaker: "You", l1: "Einerseits wäre ein Auslandsjahr in Berlin eine tolle Erfahrung.", en: "On the one hand, a year abroad in Berlin would be a great experience." },
            { speaker: "Lara", l1: "Und andererseits?", en: "And on the other hand?" },
            { speaker: "You", l1: "Andererseits ist es teuer. Erstens die Miete, zweitens die Lebenshaltungskosten.", en: "On the other hand it's expensive. Firstly the rent, secondly the cost of living." },
            { speaker: "Lara", l1: "Da hast du recht. Trotzdem würde ich es machen.", en: "You're right. Nevertheless, I would do it." },
            { speaker: "You", l1: "Außerdem lernt man die Sprache viel schneller, deshalb lohnt es sich.", en: "Besides, you learn the language much faster, so it's worth it." },
            { speaker: "Lara", l1: "Zusammenfassend: Die Vorteile überwiegen, oder?", en: "To summarize: the advantages outweigh, right?" },
            { speaker: "You", l1: "Genau. Alles in allem würde ich sagen, du solltest gehen.", en: "Exactly. All in all I'd say you should go." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Build the argument",
          intro: "Mind the verb-second order after these connectors.",
          items: [
            {
              template: "___ ist die Stadt schön, andererseits ist sie laut.",
              answer: "Einerseits",
              en: "On the one hand the city is beautiful, on the other it's loud.",
              options: ["Einerseits", "Andererseits", "Trotzdem", "Deshalb"],
            },
            {
              template: "Außerdem ___ das Wetter oft schlecht. (sein)",
              answer: "ist",
              en: "Besides, the weather is often bad.",
              options: ["ist", "sind", "sein", "es ist"],
            },
            {
              template: "Es regnet. ___ gehe ich spazieren.",
              answer: "Trotzdem",
              en: "It's raining. Nevertheless I'm going for a walk.",
              options: ["Trotzdem", "Außerdem", "Zuerst", "Zweitens"],
            },
            {
              template: "Es ist teuer, ___ fahre ich nicht hin.",
              answer: "deshalb",
              en: "It's expensive, that's why I'm not going.",
              options: ["deshalb", "einerseits", "zum Beispiel", "erstens"],
            },
            {
              template: "___ würde ich sagen, es war ein guter Tag.",
              answer: "Zusammenfassend",
              en: "To summarize, I'd say it was a good day.",
              options: ["Zusammenfassend", "Erstens", "Zum Beispiel", "Andererseits"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the argument",
          intro: "Watch the verb jump to second position after the connector.",
          items: [
            { tokens: ["Einerseits", "ist", "es", "billig", ",", "andererseits", "ist", "es", "weit"], en: "On the one hand it's cheap, on the other hand it's far." },
            { tokens: ["Außerdem", "spricht", "man", "dort", "Deutsch"], en: "Besides, people speak German there." },
            { tokens: ["Es", "regnet", ",", "trotzdem", "gehe", "ich", "raus"], en: "It's raining; nevertheless I'm going out." },
            { tokens: ["Zusammenfassend", "würde", "ich", "sagen", ",", "es", "lohnt", "sich"], en: "To summarize, I'd say it's worth it." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "On the one hand the rent is high, on the other hand the city is exciting. All in all, I'd say it's worth it.",
          reference: "Einerseits ist die Miete hoch, andererseits ist die Stadt spannend. Alles in allem würde ich sagen, es lohnt sich.",
          hint: "einerseits / andererseits both push the verb to second position; finish with 'Alles in allem würde ich sagen, …'.",
        },
        {
          type: "tip",
          heading: "You did it — the full German course",
          body: "This is the last unit of 35. You've covered: the alphabet and sounds, greetings and du/Sie, numbers, der/die/das and the cases, present tense, sein and haben, the modal verbs, separable verbs, the Perfekt and Präteritum, the dative and accusative, adjective endings, comparatives, the future, relative clauses, Berlin life (transit, directions, the Späti, the Amt), food and the Markt, subordinate clauses, the Konjunktiv II, and now structured opinion and debate. You can hold a real B1 conversation about almost anything — concede a point, push back politely, and wrap it up cleanly. <em>Ganz großartig. Glückwunsch!</em>",
        },
        {
          type: "checkpoint",
          heading: "Lesson check",
          questions: [
            {
              q: "'On the one hand… on the other hand…' =",
              options: [
                "erstens… zweitens…",
                "einerseits… andererseits…",
                "zuerst… danach…",
                "einmal… zweimal…",
              ],
              correct: 1,
            },
            {
              q: "After 'Trotzdem' at the start of a sentence, the verb comes…",
              options: ["last", "right after Trotzdem (second position)", "before Trotzdem", "nowhere"],
              correct: 1,
            },
            {
              q: "'To summarize' / 'in summary' =",
              options: ["zum Beispiel", "zusammenfassend", "außerdem", "einerseits"],
              correct: 1,
            },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'In my opinion' (most common) =",
        options: ["Ich denke", "Meiner Meinung nach", "Für mich", "Ehrlich gesagt"],
        correct: 1,
      },
      {
        q: "After 'Meiner Meinung nach' the verb comes…",
        options: ["at the end", "in second position", "before the subject only", "it's dropped"],
        correct: 1,
      },
      {
        q: "'I find that the city is expensive' =",
        options: [
          "Ich finde, dass die Stadt ist teuer.",
          "Ich finde, dass die Stadt teuer ist.",
          "Ich finde, dass ist die Stadt teuer.",
          "Ich finde, die Stadt dass teuer ist.",
        ],
        correct: 1,
      },
      {
        q: "'You're right' =",
        options: ["Da hast du recht.", "Du bist recht.", "Das hast du recht.", "Da bist du recht."],
        correct: 0,
      },
      {
        q: "Polite disagreement =",
        options: ["Das ist falsch!", "Das sehe ich anders.", "Du hast unrecht!", "Quatsch."],
        correct: 1,
      },
      {
        q: "'On the other hand' =",
        options: ["einerseits", "andererseits", "trotzdem", "außerdem"],
        correct: 1,
      },
      {
        q: "'Nevertheless' =",
        options: ["deshalb", "trotzdem", "zuerst", "zum Beispiel"],
        correct: 1,
      },
      {
        q: "'To summarize / all in all' =",
        options: ["zum Beispiel", "alles in allem", "erstens", "jedoch"],
        correct: 1,
      },
      {
        q: "The smooth way to disagree is to first…",
        options: [
          "raise your voice",
          "concede a point ('Da hast du recht, aber…')",
          "say 'Das ist falsch'",
          "stay silent",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'On the one hand it's cheap, on the other hand it's far.'",
        options: [
          "Einerseits es ist billig, andererseits es ist weit.",
          "Einerseits ist es billig, andererseits ist es weit.",
          "Einerseits ist billig es, andererseits ist weit es.",
          "Es ist einerseits billig, es ist andererseits weit.",
        ],
        correct: 1,
      },
    ],
  },
};
