import type { Unit } from "../../types";

export const UNIT_HIRAGANA: Unit = {
  slug: "hiragana",
  stage: 1,
  order: 1,
  icon: "🅰️",
  title: "Hiragana",
  tagline: "The 46 hiragana, dakuten, and the small-ya combos.",
  badge: "core",
  lessons: [
    {
      slug: "hiragana-vowels-kst",
      title: "Vowels and the k / s / t rows",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Japanese is written in syllables, not letters",
          body: [
            "Hiragana is the first of three Japanese scripts. Unlike the English alphabet, almost every hiragana stands for a whole <strong>syllable</strong> — a consonant plus a vowel, like か = <em>ka</em> or す = <em>su</em>.",
            "There are only five vowels, and they never change: <strong>あ a, い i, う u, え e, お o</strong>. Say them like <em>ah, ee, oo, eh, oh</em>. Master these five and every other row is just one of these vowels with a consonant glued in front.",
            "The whole chart is built in rows of five: the k-row (か き く け こ), the s-row (さ し す せ そ), the t-row (た ち つ て と), and so on. Learn the pattern once and the rest falls into place.",
          ],
          tip: {
            label: "Vowel order",
            body: "Japanese always lists vowels in the order <em>a-i-u-e-o</em>, not a-e-i-o-u. Drilling that order now makes every future chart easier to read.",
          },
        },
        {
          type: "pronounce",
          heading: "The five vowels",
          intro: "Hold each one short and clean. Tap to hear them.",
          items: [
            { l1: "あ", en: "a", tip: "rōmaji: a — like 'ah' in father" },
            { l1: "い", en: "i", tip: "rōmaji: i — like 'ee' in see" },
            { l1: "う", en: "u", tip: "rōmaji: u — like 'oo' in food, lips relaxed" },
            { l1: "え", en: "e", tip: "rōmaji: e — like 'eh' in bet" },
            { l1: "お", en: "o", tip: "rōmaji: o — like 'oh' in go" },
          ],
        },
        {
          type: "pronounce",
          heading: "The k-row and s-row",
          intro: "Same five vowels, now with k and s in front.",
          items: [
            { l1: "か", en: "ka", tip: "rōmaji: ka" },
            { l1: "き", en: "ki", tip: "rōmaji: ki" },
            { l1: "く", en: "ku", tip: "rōmaji: ku" },
            { l1: "け", en: "ke", tip: "rōmaji: ke" },
            { l1: "こ", en: "ko", tip: "rōmaji: ko" },
            { l1: "さ", en: "sa", tip: "rōmaji: sa" },
            { l1: "し", en: "shi", tip: "rōmaji: shi — note: NOT 'si', the s softens" },
            { l1: "す", en: "su", tip: "rōmaji: su" },
            { l1: "せ", en: "se", tip: "rōmaji: se" },
            { l1: "そ", en: "so", tip: "rōmaji: so" },
          ],
        },
        {
          type: "pronounce",
          heading: "The t-row — watch the irregulars",
          intro: "Two of these break the pattern, just like English 'shi'.",
          items: [
            { l1: "た", en: "ta", tip: "rōmaji: ta" },
            { l1: "ち", en: "chi", tip: "rōmaji: chi — NOT 'ti'" },
            { l1: "つ", en: "tsu", tip: "rōmaji: tsu — NOT 'tu'" },
            { l1: "て", en: "te", tip: "rōmaji: te" },
            { l1: "と", en: "to", tip: "rōmaji: to" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Read the kana",
          questions: [
            {
              q: "Which kana is read 'ki'?",
              qL1: "き / く / こ / か",
              options: ["き", "く", "こ", "か"],
              correct: 0,
              fb: "き = ki. The k-row goes か き く け こ (ka ki ku ke ko).",
            },
            {
              q: "How is し pronounced?",
              options: ["si", "shi", "chi", "su"],
              correct: 1,
              fb: "し is 'shi' — the s-row softens here, just like ち is 'chi' not 'ti'.",
            },
            {
              q: "Which reads 'tsu'?",
              options: ["た", "ち", "つ", "て"],
              correct: 2,
              fb: "つ = tsu, one of the t-row irregulars.",
            },
          ],
        },
      ],
    },
    {
      slug: "hiragana-nhmyrw-rows",
      title: "The n / h / m / y / r / w rows and ん",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The rest of the chart, plus the lone consonant",
          body: [
            "Now we add the n-row (な に ぬ ね の), h-row (は ひ ふ へ ほ), m-row (ま み む め も), and the shorter y-row (や ゆ よ), r-row (ら り る れ ろ), and w-row (わ を).",
            "Two things are special. The <strong>r-row</strong> isn't a hard English R — it's a light tap of the tongue, somewhere between R, L, and D. And ふ is <em>fu</em>, a soft breath, not a hard F.",
            "Finally there's <strong>ん</strong> — the only hiragana that is a single consonant with no vowel. It's the 'n' sound at the end of syllables, as in にほん (<em>nihon</em>, Japan).",
          ],
          keyPoint:
            "ん is the only standalone consonant in hiragana. It never starts a word; it closes a syllable: ほん (hon, book), せんせい (sensei, teacher).",
        },
        {
          type: "pronounce",
          heading: "n-row, h-row, m-row",
          items: [
            { l1: "な", en: "na", tip: "rōmaji: na" },
            { l1: "に", en: "ni", tip: "rōmaji: ni" },
            { l1: "ぬ", en: "nu", tip: "rōmaji: nu" },
            { l1: "ね", en: "ne", tip: "rōmaji: ne" },
            { l1: "の", en: "no", tip: "rōmaji: no" },
            { l1: "は", en: "ha", tip: "rōmaji: ha — note: read 'wa' when it marks the topic" },
            { l1: "ひ", en: "hi", tip: "rōmaji: hi" },
            { l1: "ふ", en: "fu", tip: "rōmaji: fu — soft breath, between f and h" },
            { l1: "へ", en: "he", tip: "rōmaji: he — read 'e' when it marks direction" },
            { l1: "ほ", en: "ho", tip: "rōmaji: ho" },
            { l1: "ま", en: "ma", tip: "rōmaji: ma" },
            { l1: "み", en: "mi", tip: "rōmaji: mi" },
            { l1: "む", en: "mu", tip: "rōmaji: mu" },
            { l1: "め", en: "me", tip: "rōmaji: me" },
            { l1: "も", en: "mo", tip: "rōmaji: mo" },
          ],
        },
        {
          type: "pronounce",
          heading: "y-row, r-row, w-row, and ん",
          intro: "The y and w rows have gaps — that's normal.",
          items: [
            { l1: "や", en: "ya", tip: "rōmaji: ya" },
            { l1: "ゆ", en: "yu", tip: "rōmaji: yu" },
            { l1: "よ", en: "yo", tip: "rōmaji: yo" },
            { l1: "ら", en: "ra", tip: "rōmaji: ra — light tap, between r and l" },
            { l1: "り", en: "ri", tip: "rōmaji: ri" },
            { l1: "る", en: "ru", tip: "rōmaji: ru" },
            { l1: "れ", en: "re", tip: "rōmaji: re" },
            { l1: "ろ", en: "ro", tip: "rōmaji: ro" },
            { l1: "わ", en: "wa", tip: "rōmaji: wa" },
            { l1: "を", en: "wo / o", tip: "rōmaji: wo — used only as the object particle, sounds like 'o'" },
            { l1: "ん", en: "n", tip: "rōmaji: n — the standalone final consonant" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Build real words",
          intro: "Choose the kana that completes each word.",
          items: [
            {
              template: "ほ___ (book)",
              answer: "ん",
              en: "hon — book",
              options: ["ん", "な", "の", "ぬ"],
            },
            {
              template: "に___ん (Japan)",
              answer: "ほ",
              en: "nihon — Japan",
              options: ["ほ", "は", "ふ", "へ"],
            },
            {
              template: "や___ (mountain)",
              answer: "ま",
              en: "yama — mountain",
              options: ["ま", "み", "む", "も"],
            },
            {
              template: "___り (bird)",
              answer: "と",
              en: "tori — bird",
              options: ["と", "た", "て", "ち"],
            },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Read these words",
          questions: [
            {
              q: "Read the word ねこ.",
              qL1: "ねこ",
              options: ["neko (cat)", "kone", "kone", "neku"],
              correct: 0,
              fb: "ね = ne, こ = ko → neko, 'cat'.",
            },
            {
              q: "What sound does ん add to a word?",
              options: ["a vowel 'a'", "a final 'n' consonant", "a 'wa' sound", "nothing"],
              correct: 1,
              fb: "ん is the standalone 'n' that closes a syllable, as in ほん (hon).",
            },
            {
              q: "Read the word さかな.",
              qL1: "さかな",
              options: ["sakana (fish)", "kasana", "sanaka", "nakasa"],
              correct: 0,
              fb: "さ-か-な = sa-ka-na → sakana, 'fish'.",
            },
          ],
        },
      ],
    },
    {
      slug: "hiragana-dakuten-yoon",
      title: "Dakuten, handakuten, and yōon combos",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Two little marks unlock new sounds",
          body: [
            "You already know most of the chart. Now two small marks recycle those kana into voiced sounds. The <strong>dakuten</strong> (a pair of strokes, ゛) turns k→g, s→z, t→d, h→b: か→が (ga), さ→ざ (za), た→だ (da), は→ば (ba).",
            "The <strong>handakuten</strong> (a small circle, ゜) applies only to the h-row, turning h→p: は→ぱ (pa), ひ→ぴ (pi), ふ→ぷ (pu).",
            "Then there are <strong>yōon</strong> — a kana from the -i column (き, し, ち…) plus a <em>small</em> や, ゆ, or よ. They fuse into one syllable: きゃ = <em>kya</em>, しゅ = <em>shu</em>, ちょ = <em>cho</em>. The small ゃゅょ is written smaller than a full や.",
          ],
          keyPoint:
            "Dakuten ゛ voices a kana (か→が). Handakuten ゜ makes p (は→ぱ). Small ゃゅょ after an -i kana makes one blended syllable (きゃ kya, しゅ shu).",
        },
        {
          type: "pronounce",
          heading: "Dakuten and handakuten",
          intro: "Same shapes you know, now voiced.",
          items: [
            { l1: "が", en: "ga", tip: "rōmaji: ga — か + dakuten" },
            { l1: "ぎ", en: "gi", tip: "rōmaji: gi" },
            { l1: "ざ", en: "za", tip: "rōmaji: za — さ + dakuten" },
            { l1: "じ", en: "ji", tip: "rōmaji: ji — し + dakuten" },
            { l1: "だ", en: "da", tip: "rōmaji: da — た + dakuten" },
            { l1: "で", en: "de", tip: "rōmaji: de" },
            { l1: "ば", en: "ba", tip: "rōmaji: ba — は + dakuten" },
            { l1: "ぼ", en: "bo", tip: "rōmaji: bo" },
            { l1: "ぱ", en: "pa", tip: "rōmaji: pa — は + handakuten ゜" },
            { l1: "ぴ", en: "pi", tip: "rōmaji: pi" },
            { l1: "ぷ", en: "pu", tip: "rōmaji: pu" },
          ],
        },
        {
          type: "pronounce",
          heading: "Yōon — small ya / yu / yo combos",
          intro: "An -i kana plus a small ゃ, ゅ, or ょ, blended into one beat.",
          items: [
            { l1: "きゃ", en: "kya", tip: "rōmaji: kya — き + small ゃ" },
            { l1: "きゅ", en: "kyu", tip: "rōmaji: kyu" },
            { l1: "きょ", en: "kyo", tip: "rōmaji: kyo" },
            { l1: "しゃ", en: "sha", tip: "rōmaji: sha — し + small ゃ" },
            { l1: "しゅ", en: "shu", tip: "rōmaji: shu" },
            { l1: "しょ", en: "sho", tip: "rōmaji: sho" },
            { l1: "ちゃ", en: "cha", tip: "rōmaji: cha" },
            { l1: "ちょ", en: "cho", tip: "rōmaji: cho" },
            { l1: "りょ", en: "ryo", tip: "rōmaji: ryo" },
          ],
        },
        {
          type: "tip",
          heading: "Big や vs small ゃ changes the word",
          body: "The size matters. <strong>きや</strong> (ki-ya, two beats) is not <strong>きゃ</strong> (kya, one beat). A real-world pair: <em>びよういん</em> (biyōin = beauty salon) vs <em>びょういん</em> (byōin = hospital). Get the small ょ wrong and you ask for a haircut at the ER.",
          example: { l1: "びょういん", en: "hospital (byōin) — note the small ょ" },
        },
        {
          type: "multipleChoice",
          heading: "Read the voiced and blended kana",
          questions: [
            {
              q: "What is が?",
              options: ["ka", "ga", "ha", "pa"],
              correct: 1,
              fb: "か + dakuten ゛ = が (ga).",
            },
            {
              q: "Read しゅ.",
              options: ["shiyu (two beats)", "shu (one beat)", "su", "ju"],
              correct: 1,
              fb: "し + small ゅ blend into one syllable: shu.",
            },
            {
              q: "Which mark turns は into ぱ?",
              options: ["dakuten ゛", "handakuten ゜", "a small ゃ", "nothing"],
              correct: 1,
              fb: "The handakuten (small circle ゜) makes the p-sounds from the h-row.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Spell it in hiragana",
          direction: "en-to-l1",
          prompt: "Write 'Japan' in hiragana.",
          reference: "にほん",
          hint: "ni-ho-n → use the n-row, h-row, and the standalone ん. rōmaji: nihon",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "In what order does Japanese list the five vowels?",
        options: ["a-e-i-o-u", "a-i-u-e-o", "i-u-e-o-a", "u-o-a-e-i"],
        correct: 1,
      },
      {
        q: "How is し pronounced?",
        options: ["si", "shi", "chi", "zi"],
        correct: 1,
      },
      {
        q: "Which kana reads 'tsu'?",
        options: ["た", "つ", "ち", "て"],
        correct: 1,
      },
      {
        q: "What is special about ん?",
        options: [
          "It is a vowel",
          "It is the only standalone consonant, closing a syllable",
          "It is only used in katakana",
          "It is always read 'wa'",
        ],
        correct: 1,
      },
      {
        q: "Read the word ねこ.",
        qL1: "ねこ",
        options: ["neko (cat)", "kone", "neku", "koneko"],
        correct: 0,
      },
      {
        q: "What does the dakuten ゛ do to か?",
        options: ["makes it 'pa'", "makes it 'ga'", "makes it 'kya'", "nothing"],
        correct: 1,
      },
      {
        q: "Which mark turns は into ぱ?",
        options: ["dakuten ゛", "handakuten ゜", "small ゃ", "ん"],
        correct: 1,
      },
      {
        q: "Read しゅ.",
        options: ["shi-yu (two beats)", "shu (one beat)", "ju", "su"],
        correct: 1,
      },
      {
        q: "びょういん means 'hospital'. What does the small ょ change?",
        options: [
          "Nothing, size is decorative",
          "It blends びょ into one beat, distinct from びよ",
          "It adds a vowel",
          "It voices the b",
        ],
        correct: 1,
      },
      {
        q: "How do you write 'Japan' in hiragana?",
        options: ["にほん", "にぼん", "みほん", "にほう"],
        correct: 0,
      },
    ],
  },
};
