import type { Unit } from "../../types";

export const UNIT_QUESTIONS: Unit = {
  slug: "questions",
  stage: 2,
  order: 7,
  icon: "❓",
  title: "Asking questions",
  tagline: "Quem, o que, onde, quando, por que, como, quanto?",
  badge: "core",
  lessons: [
    {
      slug: "questions-words",
      title: "The question words",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The words you need from day one",
          body: [
            "<strong>Quem?</strong> who · <strong>O que? / Que?</strong> what · <strong>Onde?</strong> where · <strong>Quando?</strong> when · <strong>Por que?</strong> why · <strong>Como?</strong> how.",
            "Add <strong>qual? / quais?</strong> (which / which ones) and <strong>quanto?</strong> (how much / how many), which change form by gender and number: <em>quanto, quanta, quantos, quantas</em>.",
            "Word order is friendly: question word + verb + (subject). <em>Onde você mora?</em> (Where do you live?), <em>O que o Marco come?</em> (What does Marco eat?), <em>Quando eles chegam?</em> (When do they arrive?).",
          ],
          keyPoint:
            "Question word first, verb next, subject optional. No 'do/does' to translate.",
        },
        {
          type: "vocab",
          heading: "Question words at a glance",
          items: [
            { l1: "quem?", en: "who?" },
            { l1: "o que? / que?", en: "what? (o que is the everyday form)" },
            { l1: "onde?", en: "where?" },
            { l1: "quando?", en: "when?" },
            { l1: "por que?", en: "why?" },
            { l1: "como?", en: "how? / what's it like? / sorry, what? (when you didn't hear)" },
            { l1: "qual? / quais?", en: "which? / which ones? (sg / pl)" },
            { l1: "quanto? / quanta?", en: "how much? (masc / fem)" },
            { l1: "quantos? / quantas?", en: "how many? (masc / fem)" },
            { l1: "de onde?", en: "from where? (De onde você é?)" },
            { l1: "para onde?", en: "to where? (Para onde você vai?)" },
            { l1: "a que horas?", en: "at what time?" },
          ],
        },
        {
          type: "tip",
          heading: "o que vs qual — 'what' isn't always 'o que'",
          body: "Use <em>o que</em> to ask for a definition or open answer: <em>O que é isso?</em> (What is that?). Use <em>qual</em> to ask someone to pick from a set, even where English says 'what': <em>Qual é o seu nome?</em> (lit. 'Which is your name?' = What's your name?), <em>Qual é o seu telefone?</em> (What's your phone number?). If a choice is implied, reach for <em>qual</em>.",
          example: { l1: "O que você quer? · Qual você prefere?", en: "What do you want? · Which one do you prefer?" },
        },
        {
          type: "multipleChoice",
          heading: "Which question word fits?",
          questions: [
            {
              q: "___ você se chama?",
              qL1: "My name is Marco.",
              options: ["Quem", "Como", "Onde", "O que"],
              correct: 1,
              fb: "'Como você se chama?' = literally 'How do you call yourself?' = What's your name?",
            },
            {
              q: "___ você mora?",
              qL1: "I live in Rio.",
              options: ["Quanto", "Quando", "Onde", "Que"],
              correct: 2,
              fb: "Onde = where.",
            },
            {
              q: "___ anos você tem?",
              qL1: "I'm 35.",
              options: ["Quanto", "Quantos", "Como", "Quem"],
              correct: 1,
              fb: "'Anos' is plural masculine → quantos.",
            },
            {
              q: "___ é aquela moça?",
              qL1: "That's my sister.",
              options: ["O que", "Como", "Quem", "Onde"],
              correct: 2,
              fb: "Quem = who.",
            },
            {
              q: "___ é o seu nome?",
              qL1: "My name is Ana.",
              options: ["O que", "Qual", "Como", "Quando"],
              correct: 1,
              fb: "For name/phone/email, Brazilians use 'qual', not 'o que': Qual é o seu nome?",
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the question",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Onde", "você", "mora", "?"], en: "Where do you live?" },
            { tokens: ["Quantos", "anos", "você", "tem", "?"], en: "How old are you?" },
            { tokens: ["Quem", "é", "aquela", "moça", "?"], en: "Who is that girl?" },
            { tokens: ["O", "que", "você", "quer", "?"], en: "What do you want?" },
          ],
        },
      ],
    },
    {
      slug: "questions-intonation",
      title: "Yes/no questions — just go up at the end",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Portuguese yes/no questions = rising intonation",
          body: [
            "English flips word order: \"You speak Portuguese → Do you speak Portuguese?\" Portuguese doesn't. You say the same sentence and just <strong>raise your voice at the end</strong>: <em>Você fala português? ↗</em>",
            "You can keep or drop the subject pronoun; both are natural: <em>Você tem fome?</em> or just <em>Tem fome?</em>",
            "Common tags at the end: <strong>né?</strong> (= 'right?', a contraction of <em>não é?</em>) and <strong>não?</strong>. <em>Você fala português, né?</em> = You speak Portuguese, right?",
          ],
          keyPoint:
            "Statement word order + rising intonation = yes/no question. 'Né?' is the Brazilian 'right?'.",
        },
        {
          type: "listen",
          heading: "Hear the rising intonation",
          intro: "TTS will say each one; the rising tone on the last syllable signals a question.",
          items: [
            { l1: "Você fala português?", en: "Do you speak Portuguese?", options: ["You speak Portuguese.", "Do you speak Portuguese?", "Speak Portuguese!", "I speak Portuguese."], correct: 1 },
            { l1: "Você tem fome?", en: "Are you hungry?", options: ["I'm hungry.", "Are you hungry?", "He's hungry.", "We're hungry."], correct: 1 },
            { l1: "Ele mora no Rio?", en: "Does he live in Rio?", options: ["I live in Rio.", "He lives in Rio.", "Does he live in Rio?", "Live in Rio!"], correct: 2 },
            { l1: "Vocês são americanos?", en: "Are you (all) American?", options: ["We are American.", "Are you all American?", "They are American.", "I am American."], correct: 1 },
          ],
        },
        {
          type: "tip",
          heading: "Né? — the little word you'll hear everywhere",
          body: "<em>Né?</em> is a crushed-down <em>não é?</em> ('isn't it?'). Brazilians stick it onto the end of statements constantly to turn them into 'right?' check-ins. It's casual but very common in everyday speech. In Portugal you'll hear <em>não é?</em> said in full more often, and the tag <em>pois?</em>.",
          example: { l1: "Está quente hoje, né?", en: "It's hot today, isn't it?" },
        },
        {
          type: "dialogue",
          heading: "Quick exchanges",
          setup: "Two strangers chatting at a café in São Paulo.",
          lines: [
            { speaker: "A", l1: "Você está de férias?", en: "Are you on vacation?" },
            { speaker: "B", l1: "Estou, sim. Vou ficar uma semana. Você é daqui?", en: "Yes, I am. I'm staying a week. Are you from here?" },
            { speaker: "A", l1: "Não, sou de Salvador, mas trabalho aqui. Você gosta da cidade?", en: "No, I'm from Salvador, but I work here. Do you like the city?" },
            { speaker: "B", l1: "Muito! Tem uma dica para o jantar?", en: "A lot! Do you have a tip for dinner?" },
            { speaker: "A", l1: "Você conhece a Vila Madalena? Tem um restaurante ótimo lá.", en: "Do you know Vila Madalena? There's a great restaurant there." },
          ],
        },
        {
          type: "orderWords",
          heading: "Form the yes/no question",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Você", "fala", "inglês", "?"], en: "Do you speak English?" },
            { tokens: ["Vocês", "têm", "uma", "reserva", "?"], en: "Do you (all) have a reservation?" },
            { tokens: ["Você", "é", "americano", ",", "né", "?"], en: "You're American, right?" },
            { tokens: ["Você", "conhece", "este", "restaurante", "?"], en: "Do you know this restaurant?" },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Are you hungry? Do you want a pizza?",
          reference: "Você tem fome? Você quer uma pizza?",
          hint: "Portuguese uses 'ter' (to have) for hunger: ter fome. No 'do' to translate — just intonation.",
        },
      ],
    },
    {
      slug: "questions-real-life",
      title: "Real-world question patterns",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The questions you'll actually use in Brazil",
          body: [
            "Some questions are fixed idioms — memorize them whole.",
            "<em>Tudo bem?</em> (How are you?) and the casual <em>Como vai?</em> (How's it going?).",
            "<em>Quanto custa?</em> (How much does it cost?) and <em>Quanto é?</em> (How much is it? — what a cashier asks for the total).",
            "<em>Com licença, onde fica…?</em> — the polite 'excuse me, where is…?'. Note <em>fica</em> (from <em>ficar</em>) is the natural verb for where things are <em>located</em>.",
            "<em>Posso…?</em> = May I…? <em>Posso pagar com cartão? Posso ver o cardápio?</em>",
          ],
        },
        {
          type: "vocab",
          heading: "Essential question phrases",
          items: [
            { l1: "Tudo bem?", en: "How are you? (lit. all well?)" },
            { l1: "Como vai?", en: "How's it going?" },
            { l1: "Quanto custa?", en: "How much does it cost?" },
            { l1: "Quanto é?", en: "How much is it? (the total)" },
            { l1: "Cadê o banheiro?", en: "Where's the bathroom? (very casual, BR)" },
            { l1: "Com licença, onde fica…?", en: "Excuse me, where is…? (located)" },
            { l1: "Posso…?", en: "May I…?" },
            { l1: "Você pode me ajudar?", en: "Can you help me?" },
            { l1: "Você fala inglês?", en: "Do you speak English?" },
            { l1: "Que horas são?", en: "What time is it?" },
            { l1: "A que horas abre / fecha?", en: "What time does it open / close?" },
            { l1: "O que você recomenda?", en: "What do you recommend?" },
          ],
        },
        {
          type: "tip",
          heading: "Cadê? — pure Brazilian shorthand for 'where is?'",
          body: "<em>Cadê…?</em> is an extremely common Brazilian way to say 'Where is…?' — it's a worn-down form of an old phrase (<em>que é de…?</em>) and simply replaces <em>Onde está…?</em> in casual speech: <em>Cadê o João?</em> = Where's João? <em>Cadê meu celular?</em> = Where's my phone? It does <strong>not</strong> exist in European Portuguese — in Portugal you'd say <em>Onde está…?</em> So Cadê is a quick way to sound Brazilian, but recognise <em>Onde está…?</em> as the standard everywhere.",
          example: { l1: "Cadê o controle remoto?", en: "Where's the remote control?" },
        },
        {
          type: "tip",
          heading: "por que / por quê / porque / porquê — the four spellings",
          body: "These trip up native speakers too. <strong>Por que</strong> (two words, no accent) opens a question: <em>Por que você está triste?</em> (Why are you sad?). <strong>Por quê</strong> (with circumflex) is used when it ends a sentence: <em>Você está triste, por quê?</em> <strong>Porque</strong> (one word) means 'because' in an answer: <em>Porque estou cansado.</em> <strong>Porquê</strong> (one word + accent) is a noun, 'the reason': <em>Não sei o porquê.</em> (I don't know the reason). Quick rule: question = por que, end of sentence = por quê, answer = porque, the-noun = porquê.",
          example: { l1: "— Por que você não veio? — Porque estava doente.", en: "— Why didn't you come? — Because I was sick." },
        },
        {
          type: "fillBlank",
          heading: "Build the question",
          items: [
            {
              template: "Com licença, ___ fica a estação?",
              answer: "onde",
              en: "Excuse me, where is the station?",
              options: ["como", "onde", "que", "quanto"],
            },
            {
              template: "___ custa a passagem?",
              answer: "Quanto",
              en: "How much does the ticket cost?",
              options: ["Quanto", "Qual", "Como", "O que"],
            },
            {
              template: "A que ___ o museu abre?",
              answer: "horas",
              en: "What time does the museum open?",
              options: ["horas", "como", "quando", "quanto"],
            },
            {
              template: "___ pagar com cartão?",
              answer: "Posso",
              en: "May I pay by card?",
              options: ["Devo", "Posso", "Quero", "Faço"],
            },
            {
              template: "___ é o seu telefone?",
              answer: "Qual",
              en: "What's your phone number?",
              options: ["O que", "Qual", "Quem", "Onde"],
            },
          ],
        },
        {
          type: "dialogue",
          heading: "Asking around in Rio",
          setup: "You're a tourist looking for the Pão de Açúcar (Sugarloaf).",
          lines: [
            { speaker: "Você", l1: "Com licença, senhora. Onde fica o Pão de Açúcar?", en: "Excuse me, ma'am. Where is the Sugarloaf?" },
            { speaker: "Senhora", l1: "É pertinho! Está vendo aquela rua? Em frente, depois à direita.", en: "It's really close! See that street? Straight ahead, then to the right." },
            { speaker: "Você", l1: "Quanto tempo a pé?", en: "How long on foot?" },
            { speaker: "Senhora", l1: "Uns dez minutos, não mais.", en: "About ten minutes, no more." },
            { speaker: "Você", l1: "E tem um bom café aqui perto?", en: "And is there a good café nearby?" },
            { speaker: "Senhora", l1: "Tem, sim! Aquele ali faz um cafezinho ótimo. Custa pouco.", en: "Yes, there is! That one over there makes a great little coffee. It's cheap." },
            { speaker: "Você", l1: "Muito obrigado, senhora!", en: "Thank you very much, ma'am!" },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Excuse me, do you speak English? How much does this cost?",
          reference: "Com licença, você fala inglês? Quanto custa isto?",
          hint: "'Excuse me' (to get attention) = Com licença. 'This' = isto/isso. Quanto custa = how much does it cost.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'Where do you live?' (Brazilian) =",
        options: ["Onde você mora?", "Onde é mora?", "Mora onde tu?", "Você onde mora?"],
        correct: 0,
      },
      {
        q: "Which is the everyday Brazilian word for 'who'?",
        options: ["Quem", "Quanto", "Qual", "Como"],
        correct: 0,
      },
      {
        q: "'How old are you?' =",
        options: ["Como você é velho?", "Quantos anos você tem?", "Que idade você é?", "Quanto anos você tem?"],
        correct: 1,
      },
      {
        q: "Brazilian yes/no questions differ from statements by…",
        options: [
          "Word order flip",
          "Adding 'do' or 'does'",
          "Rising intonation only",
          "Adding 'que' at the start",
        ],
        correct: 2,
      },
      {
        q: "For 'What's your name?', Brazilians say…",
        options: ["O que é o seu nome?", "Qual é o seu nome?", "Quem é o seu nome?", "Como é seu nome que?"],
        correct: 1,
      },
      {
        q: "'What time does it open?' =",
        options: [
          "Quando abre?",
          "A que horas abre?",
          "Que tempo abre?",
          "Como abre?",
        ],
        correct: 1,
      },
      {
        q: "'May I pay by card?' =",
        options: [
          "Pago com cartão?",
          "Posso pago com cartão?",
          "Posso pagar com cartão?",
          "Quero pagar com cartão.",
        ],
        correct: 2,
      },
      {
        q: "The very Brazilian casual way to ask 'Where is…?' is…",
        options: ["Cadê…?", "Adeus…?", "Pois não…?", "Tudo bem…?"],
        correct: 0,
      },
      {
        q: "'How much is it?' (asking the total) =",
        options: ["Quanto custa o quê?", "Quanto é?", "Quantos reais?", "Qual é?"],
        correct: 1,
      },
      {
        q: "In writing, 'because' (in an answer) is spelled…",
        options: ["por que", "por quê", "porque", "porquê"],
        correct: 2,
      },
    ],
  },
};
