import type { Unit } from "../../types";

export const UNIT_DIRECTIONS: Unit = {
  slug: "directions",
  stage: 3,
  order: 11,
  icon: "🧭",
  title: "Asking for directions",
  tagline: "Direita, esquerda, em frente — com licença, onde fica…?",
  badge: "tourist",
  lessons: [
    {
      slug: "directions-words",
      title: "Right, left, straight — and the words in between",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Six words and you can navigate",
          body: [
            "<strong>Direita</strong> (right) and <strong>esquerda</strong> (left) pair with <em>à</em> (a + a): <em>à direita</em>, <em>à esquerda</em>. To turn, you say <em>vire à direita</em> / <em>vire à esquerda</em>.",
            "<strong>Em frente</strong> = straight ahead. <strong>Siga em frente</strong> = keep going straight. You'll also hear <em>siga reto</em> (BR) — same idea. <strong>Para trás</strong> = back / backwards.",
            "Place words: <strong>perto de</strong> (near), <strong>longe de</strong> (far from), <strong>em frente a</strong> (in front of / facing), <strong>atrás de</strong> (behind), <strong>do lado de</strong> (beside / next to), <strong>entre</strong> (between).",
          ],
          keyPoint:
            "à direita / à esquerda / em frente. perto de / longe de. em frente a / atrás de / do lado de.",
        },
        {
          type: "vocab",
          heading: "Direction & location vocabulary",
          items: [
            { l1: "à direita", en: "(on/to the) right" },
            { l1: "à esquerda", en: "(on/to the) left" },
            { l1: "em frente", en: "straight ahead" },
            { l1: "siga reto", en: "go straight (BR phrasing)", note: "Common in Brazil alongside 'siga em frente'" },
            { l1: "para trás", en: "back / backwards" },
            { l1: "perto (de)", en: "near (to)" },
            { l1: "longe (de)", en: "far (from)" },
            { l1: "em frente a", en: "in front of / facing / across from" },
            { l1: "atrás (de)", en: "behind" },
            { l1: "do lado de", en: "next to / beside" },
            { l1: "ao lado de", en: "next to (also very common)" },
            { l1: "entre", en: "between" },
            { l1: "na esquina", en: "at the corner" },
            { l1: "no fim (de)", en: "at the end (of)" },
            { l1: "em cima / embaixo", en: "above / below" },
            { l1: "aqui / ali / lá", en: "here / there / over there" },
          ],
        },
        {
          type: "tip",
          heading: "Onde fica…? — the 'where is it' that locals expect",
          body: "For things that don't move (a street, a station, a museum), Brazilians ask <em>onde fica…?</em> rather than <em>onde está…?</em>. <em>Ficar</em> means 'to be located'. So: <em>Onde fica o banheiro?</em> = Where's the bathroom? <em>Onde fica a estação?</em> = Where's the station? In Portugal you'll hear the same <em>onde fica…?</em>, and also <em>onde é…?</em> for landmarks.",
          example: { l1: "Com licença, onde fica a farmácia?", en: "Excuse me, where is the pharmacy?" },
        },
        {
          type: "fillBlank",
          heading: "Where is it?",
          items: [
            {
              template: "A farmácia fica ___ do hotel.",
              answer: "do lado",
              en: "The pharmacy is next to the hotel.",
              options: ["do lado", "atrás", "longe", "embaixo"],
            },
            {
              template: "O museu fica ___ da praça.",
              answer: "perto",
              en: "The museum is near the square.",
              options: ["perto", "longe", "atrás", "embaixo"],
            },
            {
              template: "O bar fica ___ à igreja.",
              answer: "em frente",
              en: "The bar is across from the church.",
              options: ["atrás", "em frente", "embaixo", "entre"],
            },
            {
              template: "Vire à ___ no semáforo.",
              answer: "direita",
              en: "Turn right at the traffic light.",
              options: ["esquerda", "direita", "frente", "trás"],
            },
            {
              template: "A praça fica ___ da rua.",
              answer: "no fim",
              en: "The square is at the end of the street.",
              options: ["no fim", "em frente", "do lado", "perto"],
            },
          ],
        },
      ],
    },
    {
      slug: "directions-verbs",
      title: "Turn, cross, go — the action verbs",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Five verbs do most of the work",
          body: [
            "<strong>Virar</strong> = to turn. <em>Vire à direita</em> = turn right. The polite command (você) ends in <em>-e</em>: <em>vire</em>.",
            "<strong>Seguir</strong> = to follow / keep going. <em>Siga em frente</em> = keep going straight. <em>Siga reto</em> (BR) means the same.",
            "<strong>Ir</strong> = to go. <em>Vá em frente</em> = go straight ahead. Irregular: vou, vai, vai, vamos, vão.",
            "<strong>Atravessar</strong> = to cross. <em>Atravesse a rua</em> = cross the street.",
            "<strong>Chegar</strong> = to arrive / get to. <em>Como eu chego a…?</em> = How do I get to…?",
          ],
          keyPoint:
            "Polite commands (você) usually end in -e: vire, siga, atravesse. Irregulars: vá (go), pegue (take). 'Como eu chego a…?' = how do I get to…?",
        },
        {
          type: "conjugation",
          heading: "Commands (você) — the forms you'll HEAR",
          verb: "virar / seguir / ir / pegar / atravessar",
          meaning: "turn / follow / go / take / cross (você command)",
          intro: "When someone gives you directions, they use the você command. These are the forms you'll hear most often on the street.",
          tenses: [
            {
              name: "Imperative (você)",
              forms: [
                { person: "virar", form: "vire", en: "turn (command)" },
                { person: "seguir", form: "siga", en: "keep going / follow (command)" },
                { person: "ir", form: "vá", en: "go (command — irregular)" },
                { person: "pegar", form: "pegue", en: "take (command — e.g. take a street)" },
                { person: "atravessar", form: "atravesse", en: "cross (command)" },
                { person: "desculpar", form: "desculpe", en: "excuse me / sorry (to open the question)" },
              ],
            },
          ],
        },
        {
          type: "tip",
          heading: "Pegar a rua (BR) vs apanhar (PT)",
          body: "In Brazil, you <em>pega</em> a street or a bus: <em>Pegue a primeira rua à direita</em> = Take the first street on the right. In Portugal the everyday verb for 'to catch/take' transport is often <em>apanhar</em> (<em>apanhe o autocarro</em> = take the bus). For streets, both regions also simply say <em>vire na primeira à direita</em> (turn on the first one on the right).",
          example: { l1: "Pegue a segunda rua à esquerda.", en: "Take the second street on the left." },
        },
        {
          type: "dialogue",
          heading: "Asking for the Cristo Redentor lookout",
          setup: "You stop someone near the metro in Rio.",
          lines: [
            { speaker: "Você", l1: "Com licença. Você sabe onde fica a estação do trem do Corcovado?", en: "Excuse me. Do you know where the Corcovado train station is?" },
            { speaker: "Moça", l1: "Sei, sim. Siga em frente por dois quarteirões.", en: "Yes, I do. Keep going straight for two blocks." },
            { speaker: "Você", l1: "Dois quarteirões. E depois?", en: "Two blocks. And then?" },
            { speaker: "Moça", l1: "Depois vire à direita. Tá vendo aquela igreja? Logo depois da igreja, vire à esquerda.", en: "Then turn right. You see that church? Right after the church, turn left." },
            { speaker: "Você", l1: "Tá bom. E é longe daqui?", en: "Okay. And is it far from here?" },
            { speaker: "Moça", l1: "Uns dez minutos a pé. Tem placa o caminho todo.", en: "About ten minutes on foot. There are signs the whole way." },
            { speaker: "Você", l1: "Muito obrigado, você é muito gentil!", en: "Thank you very much, you're very kind!" },
          ],
        },
        {
          type: "orderWords",
          heading: "Reconstruct the directions",
          items: [
            { tokens: ["Siga", "em", "frente", "por", "cem", "metros"], en: "Keep going straight for 100 meters." },
            { tokens: ["Vire", "à", "direita", "no", "semáforo"], en: "Turn right at the traffic light." },
            { tokens: ["Pegue", "a", "segunda", "à", "esquerda"], en: "Take the second (street) on the left." },
            { tokens: ["Atravesse", "a", "praça", "e", "siga", "reto"], en: "Cross the square and keep going straight." },
            { tokens: ["Fica", "em", "frente", "à", "estação"], en: "It's across from the station." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Spot the right command",
          questions: [
            {
              q: "Which is the você command for 'turn'?",
              options: ["vira", "vire", "virar", "viram"],
              correct: 1,
              fb: "Vire is the você command for virar. The -e ending marks the polite/standard command for -ar verbs.",
            },
            {
              q: "Which is the você command for 'go' (irregular)?",
              options: ["vai", "vá", "ir", "vou"],
              correct: 1,
              fb: "Vá is the irregular command form of ir — 'go'. (vai is the statement form 'goes/are going'.)",
            },
            {
              q: "Which means 'keep going straight'?",
              options: ["Siga atrás", "Siga em frente", "Vire em frente", "Para trás sempre"],
              correct: 1,
              fb: "Siga em frente = keep going straight. In Brazil 'siga reto' means the same thing.",
            },
            {
              q: "'How do I get to the market?' =",
              options: [
                "Onde está o mercado?",
                "Como eu chego ao mercado?",
                "Quanto custa o mercado?",
                "Quando é o mercado?",
              ],
              correct: 1,
              fb: "Como eu chego a…? = How do I get to…? With 'o mercado' the a + o contracts to 'ao mercado'.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Excuse me, how do I get to the station?",
          reference: "Com licença, como eu chego à estação?",
          hint: "'Excuse me' = com licença. 'How do I get to…?' = como eu chego a…? With 'a estação', a + a contracts to 'à'.",
        },
      ],
    },
    {
      slug: "directions-real-world",
      title: "Putting it all together",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Reading directions in the wild",
          body: [
            "You'll see these compact phrases on signs all over Brazil:",
            "<em>Centro ➜</em> (Downtown this way)",
            "<em>Entrada / Saída</em> (Entrance / Exit)",
            "<em>Sentido…</em> (Toward… / in the direction of…)",
            "<em>Mão única</em> (One way — BR; PT: <em>sentido único</em>)",
            "<em>Pedestres</em> / <em>Faixa de pedestres</em> (Pedestrians / Crosswalk)",
            "<em>Proibido entrar</em> (No entry)",
          ],
        },
        {
          type: "vocab",
          heading: "Street vocabulary",
          items: [
            { l1: "a rua", en: "the street", note: "Used in addresses: Rua Augusta" },
            { l1: "a avenida", en: "the avenue", note: "Abbreviated 'Av.' — e.g. Avenida Paulista" },
            { l1: "a praça", en: "the square / plaza" },
            { l1: "o quarteirão", en: "the (city) block" },
            { l1: "a esquina", en: "the (street) corner" },
            { l1: "o semáforo", en: "the traffic light", note: "Also called 'o sinal' in Brazil" },
            { l1: "a calçada", en: "the sidewalk" },
            { l1: "a faixa de pedestres", en: "the crosswalk" },
            { l1: "o cruzamento", en: "the intersection" },
            { l1: "a rotatória", en: "the roundabout" },
            { l1: "a ponte", en: "the bridge" },
            { l1: "o ponto de referência", en: "the landmark / reference point", note: "What Brazilians ask for when lost" },
          ],
        },
        {
          type: "tip",
          heading: "Ask for a ponto de referência",
          body: "Brazilian addresses can be vague, so locals navigate by <em>pontos de referência</em> (landmarks). If directions confuse you, ask: <em>Tem algum ponto de referência?</em> = Is there a landmark? You'll get something concrete like <em>fica do lado da padaria</em> (it's next to the bakery). It's the single most useful question when you're lost in a Brazilian city.",
          example: { l1: "Qual é o ponto de referência?", en: "What's the landmark / nearby reference?" },
        },
        {
          type: "dialogue",
          heading: "Lost at night in São Paulo",
          setup: "It's late and you're trying to find your hotel.",
          lines: [
            { speaker: "Você", l1: "Com licença, acho que me perdi. Procuro a Rua Augusta, número quarenta.", en: "Excuse me, I think I'm lost. I'm looking for Rua Augusta, number forty." },
            { speaker: "Senhor", l1: "A Rua Augusta é logo ali. Tá vendo aquela ponte?", en: "Rua Augusta is right over there. You see that bridge?" },
            { speaker: "Você", l1: "Estou vendo, sim.", en: "Yes, I can see it." },
            { speaker: "Senhor", l1: "Atravesse a ponte e pegue a primeira rua à esquerda. Essa é a Augusta. O número quarenta fica uns duzentos metros adiante.", en: "Cross the bridge and take the first street on the left. That's Augusta. Number forty is about 200 meters ahead." },
            { speaker: "Você", l1: "Ótimo. É seguro a esta hora?", en: "Great. Is it safe at this hour?" },
            { speaker: "Senhor", l1: "Tranquilo. Tem bastante gente na rua. Mas fique de olho na bolsa.", en: "No worries. There are plenty of people around. But keep an eye on your bag." },
            { speaker: "Você", l1: "Muito obrigado mesmo!", en: "Thank you so much!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Fill the direction",
          items: [
            {
              template: "Atravesse na ___ de pedestres no semáforo.",
              answer: "faixa",
              en: "Cross at the crosswalk at the traffic light.",
              options: ["faixa", "esquina", "ponte", "rua"],
            },
            {
              template: "Acho que eu me ___ . Onde fica o meu hotel?",
              answer: "perdi",
              en: "I think I'm lost. Where is my hotel?",
              options: ["perdi", "cansei", "atrasei", "esqueci"],
            },
            {
              template: "No ___ , vire à direita.",
              answer: "cruzamento",
              en: "At the intersection, turn right.",
              options: ["cruzamento", "fim", "centro", "lado"],
            },
            {
              template: "O mercado fica no fim da ___ .",
              answer: "avenida",
              en: "The market is at the end of the avenue.",
              options: ["avenida", "ponte", "calçada", "esquina"],
            },
          ],
        },
        {
          type: "pronounce",
          heading: "Directions to practise aloud",
          items: [
            { l1: "Com licença", en: "Excuse me", tip: "kong lee-SEN-sah" },
            { l1: "Onde fica…?", en: "Where is…?", tip: "ONG-jee FEE-kah" },
            { l1: "Vire à direita", en: "Turn right", tip: "VEE-ree ah jee-RAY-tah" },
            { l1: "Siga em frente", en: "Keep going straight", tip: "SEE-gah eng FREN-chee" },
            { l1: "É longe daqui?", en: "Is it far from here?", tip: "eh LONG-zhee dah-KEE" },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Excuse me, I'm lost. Is the museum far from here?",
          reference: "Com licença, eu me perdi. O museu é longe daqui?",
          hint: "'I'm lost' = eu me perdi (or 'estou perdido' m / 'perdida' f). 'From here' = daqui.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'To the right' =",
        options: ["à esquerda", "à direita", "em frente", "atrás"],
        correct: 1,
      },
      {
        q: "'Keep going straight' =",
        options: ["siga em frente", "vire à direita", "para trás", "no fim"],
        correct: 0,
      },
      {
        q: "'Across from / facing the church' =",
        options: [
          "atrás da igreja",
          "perto da igreja",
          "em frente à igreja",
          "embaixo da igreja",
        ],
        correct: 2,
      },
      {
        q: "The você command for 'turn' =",
        options: ["vira", "vire", "virar", "viram"],
        correct: 1,
      },
      {
        q: "'Excuse me, I'm lost.' =",
        options: [
          "Desculpa, estou cansado.",
          "Com licença, eu me perdi.",
          "Com licença, é longe.",
          "Onde fica você?",
        ],
        correct: 1,
      },
      {
        q: "'At the corner' =",
        options: ["na esquina", "no cruzamento", "no fim", "no centro"],
        correct: 0,
      },
      {
        q: "'Take the second street on the left' (BR) =",
        options: [
          "Vira a segunda.",
          "Pegue a segunda rua à esquerda.",
          "Pegar a segunda à esquerda.",
          "Peguem a segunda rua.",
        ],
        correct: 1,
      },
      {
        q: "'Near the station' =",
        options: [
          "longe da estação",
          "perto da estação",
          "atrás da estação",
          "embaixo da estação",
        ],
        correct: 1,
      },
      {
        q: "Best way to ask 'Where is the bathroom?' (a fixed place) =",
        options: [
          "Onde está o banheiro?",
          "Onde fica o banheiro?",
          "Quando é o banheiro?",
          "Quanto é o banheiro?",
        ],
        correct: 1,
      },
      {
        q: "'Ponto de referência' means…",
        options: ["one-way street", "bus stop", "landmark / reference point", "pedestrian zone"],
        correct: 2,
      },
    ],
  },
};
