import type { Unit } from "../../types";

export const UNIT_HOTEL: Unit = {
  slug: "hotel",
  stage: 3,
  order: 12,
  icon: "🏨",
  title: "Airport & hotel",
  tagline: "Check-in, reserva, quarto, café da manhã.",
  badge: "tourist",
  lessons: [
    {
      slug: "hotel-arrival",
      title: "At the airport — the first hour",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "What you'll hear and need to say at Guarulhos",
          body: [
            "<strong>Passport control</strong> (<em>controle de passaportes</em>): the officer may ask <em>«Qual é o motivo da sua viagem?»</em> = What's the purpose of your trip? Reply <em>«Turismo / negócios / visita à família»</em>.",
            "<strong>Baggage claim</strong>: follow signs for <em>RESTITUIÇÃO DE BAGAGEM</em> (Brazil) or <em>RECOLHA DE BAGAGEM</em> (Portugal). Belts are numbered: <em>esteira 4</em> = belt 4.",
            "<strong>Lost luggage</strong>: <em>«A minha mala não chegou. Onde faço a reclamação?»</em> = My suitcase didn't arrive. Where do I file a complaint?",
            "<strong>SIM card / data</strong>: Brazilian airports have Vivo, Claro, and TIM kiosks. A tourist <em>chip</em> (that's the BR word for a SIM card) is cheap and quick to set up.",
          ],
          tip: {
            label: "Esteira vs tapete",
            body: "The baggage belt is a esteira in Brazil but o tapete (de bagagem) in Portugal. Both literally evoke a 'conveyor/carpet'. Say esteira and any Brazilian will point you right to it.",
          },
        },
        {
          type: "vocab",
          heading: "Airport essentials",
          items: [
            { l1: "o voo", en: "the flight" },
            { l1: "o controle de passaportes", en: "passport control", note: "PT spelling: controlo" },
            { l1: "a restituição de bagagem", en: "baggage claim (BR)", note: "PT: recolha de bagagem" },
            { l1: "a esteira", en: "the belt (baggage, BR)", note: "PT: o tapete" },
            { l1: "a alfândega", en: "customs" },
            { l1: "o carrinho", en: "the cart / trolley" },
            { l1: "o balcão", en: "the (service) counter / desk" },
            { l1: "a bagagem de mão", en: "carry-on baggage" },
            { l1: "a bagagem despachada", en: "checked baggage" },
            { l1: "o cartão de embarque", en: "the boarding pass" },
            { l1: "atrasado / no horário", en: "delayed / on time" },
            { l1: "a mala", en: "the suitcase" },
            { l1: "extraviado", en: "lost / mislaid (luggage)" },
          ],
        },
        {
          type: "dialogue",
          heading: "Passport control",
          setup: "You hand the officer your passport at immigration.",
          lines: [
            { speaker: "Oficial", l1: "Bom dia. Qual é o motivo da sua viagem?", en: "Good morning. What's the purpose of your trip?" },
            { speaker: "Você", l1: "Turismo. Vou ficar dez dias no Rio.", en: "Tourism. I'm staying ten days in Rio." },
            { speaker: "Oficial", l1: "Onde você vai ficar?", en: "Where are you staying?" },
            { speaker: "Você", l1: "No Hotel Copacabana, na orla.", en: "At Hotel Copacabana, by the seafront." },
            { speaker: "Oficial", l1: "Tudo certo. Boa estadia!", en: "All set. Have a good stay!" },
            { speaker: "Você", l1: "Obrigado!", en: "Thank you!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Fill in the airport scene",
          items: [
            {
              template: "A minha mala foi ___ . O que eu faço?",
              answer: "extraviada",
              en: "My suitcase was lost. What do I do?",
              options: ["extraviada", "quebrada", "velha", "leve"],
            },
            {
              template: "O meu voo está ___ de três horas.",
              answer: "atrasado",
              en: "My flight is delayed by three hours.",
              options: ["chegando", "saindo", "atrasado", "no horário"],
            },
            {
              template: "A bagagem chega na ___ número quatro.",
              answer: "esteira",
              en: "The luggage arrives at belt number four.",
              options: ["balcão", "plataforma", "esteira", "carrinho"],
            },
            {
              template: "Preciso do ___ de embarque.",
              answer: "cartão",
              en: "I need the boarding pass.",
              options: ["cartão", "cartão de crédito", "portão", "chip"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Excuse me, where can I buy a SIM card?",
          reference: "Com licença, onde posso comprar um chip?",
          hint: "Posso + infinitive = 'can I + verb'. In Brazil a phone SIM card is um chip.",
        },
      ],
    },
    {
      slug: "hotel-checkin",
      title: "Check-in",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The check-in script (you'll do this every trip)",
          body: [
            "<em>«Tenho uma reserva em nome de [your name].»</em> = I have a reservation under [name].",
            "Brazilian hotels ask for your <strong>passport</strong> and have you fill in a <em>ficha</em> (registration card): <em>«Posso ver o seu documento?»</em> They register guests for the police/Polícia Federal — totally routine.",
            "Common questions back: <em>«O café da manhã está incluído?» «Quantas noites?» «A que horas pretende sair?»</em>",
            "Useful answers: <em>«Tudo incluído, obrigado.» «Quatro noites, até domingo.» «Saio na sexta de manhã.»</em>",
          ],
          keyPoint:
            "1) Give your name. 2) Hand over passport. 3) Fill in the ficha. 4) Get the key/keycard. 5) Ask about café da manhã and wifi.",
        },
        {
          type: "vocab",
          heading: "Hotel & room vocabulary",
          items: [
            { l1: "a recepção", en: "reception desk" },
            { l1: "a reserva", en: "the reservation" },
            { l1: "o quarto", en: "the room", note: "Same word in BR and PT" },
            { l1: "o quarto de solteiro", en: "single room (one single bed)" },
            { l1: "o quarto de casal", en: "double room (one big bed)" },
            { l1: "o quarto duplo", en: "twin room (two beds)" },
            { l1: "o café da manhã (incluído)", en: "breakfast (included, BR)", note: "PT: pequeno-almoço" },
            { l1: "a chave / o cartão", en: "the key / the keycard" },
            { l1: "o elevador", en: "the elevator" },
            { l1: "o andar", en: "the floor (térreo = ground floor in BR)" },
            { l1: "o wifi / a senha", en: "wifi / password", note: "senha = password (BR); PT often: palavra-passe" },
            { l1: "o check-in / o check-out", en: "check-in / check-out" },
            { l1: "o ar-condicionado", en: "air conditioning" },
            { l1: "a diária", en: "the nightly rate / per-night price" },
            { l1: "o banheiro", en: "the bathroom (BR)", note: "PT: casa de banho / WC" },
          ],
        },
        {
          type: "tip",
          heading: "Café da manhã (BR) vs pequeno-almoço (PT)",
          body: "Breakfast is one of the biggest BR/PT splits. Brazil says <em>café da manhã</em>; Portugal says <em>pequeno-almoço</em>. Likewise the bathroom: in Brazil it's the <em>banheiro</em>, while in Portugal you ask for the <em>casa de banho</em> or just the <em>WC</em> (in Brazil <em>banheiro</em> means the room; a <em>casa de banho</em> would sound foreign). Good news: <em>quarto</em> (room) is shared by both.",
          example: { l1: "O café da manhã está incluído? — Onde fica o banheiro?", en: "Is breakfast included? — Where's the bathroom?" },
        },
        {
          type: "dialogue",
          heading: "Full check-in",
          setup: "You arrive at the hotel just after lunch.",
          lines: [
            { speaker: "Você", l1: "Boa tarde. Tenho uma reserva em nome de Connolly.", en: "Good afternoon. I have a reservation under Connolly." },
            { speaker: "Recepcionista", l1: "Um momento… Sim, aqui está. Quatro noites, quarto de casal. Posso ver o seu documento, por favor?", en: "One moment… Yes, here it is. Four nights, double room. May I see your ID, please?" },
            { speaker: "Você", l1: "Claro. Aqui está o passaporte.", en: "Of course. Here's the passport." },
            { speaker: "Recepcionista", l1: "Perfeito. O café da manhã está incluído, das sete às dez, no térreo. O wifi é gratuito, a senha está aqui.", en: "Perfect. Breakfast is included, from seven to ten, on the ground floor. The wifi is free, the password is here." },
            { speaker: "Você", l1: "Ótimo. A que horas é o check-out?", en: "Great. What time is check-out?" },
            { speaker: "Recepcionista", l1: "Ao meio-dia. Se quiser sair mais tarde, é só avisar. Aqui está o cartão — quarto 302, terceiro andar. O elevador fica no fim do corredor.", en: "At noon. If you want to leave later, just let us know. Here's the keycard — room 302, third floor. The elevator is at the end of the hall." },
            { speaker: "Você", l1: "Muito obrigado!", en: "Thank you very much!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Check-in fill-ins",
          items: [
            {
              template: "Tenho uma ___ em nome de Smith.",
              answer: "reserva",
              en: "I have a reservation under Smith.",
              options: ["reserva", "quarto", "porta", "ficha"],
            },
            {
              template: "Eu queria um quarto de ___ , com uma cama grande.",
              answer: "casal",
              en: "I'd like a double room, with one big bed.",
              options: ["solteiro", "casal", "duplo", "família"],
            },
            {
              template: "A que horas é o ___ ?",
              answer: "check-out",
              en: "What time is check-out?",
              options: ["check-out", "check-in", "café", "almoço"],
            },
            {
              template: "Posso pagar com ___ ?",
              answer: "cartão",
              en: "Can I pay by card?",
              options: ["cartão", "dinheiro vivo", "cheque", "dólares"],
            },
            {
              template: "O elevador fica no ___ do corredor.",
              answer: "fim",
              en: "The elevator is at the end of the hall.",
              options: ["meio", "fim", "canto", "começo"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the request",
          items: [
            { tokens: ["Eu", "queria", "um", "quarto", "silencioso", ",", "se", "possível"], en: "I'd like a quiet room, if possible." },
            { tokens: ["Quanto", "custa", "a", "diária", "?"], en: "How much is the nightly rate?" },
            { tokens: ["Pode", "me", "dar", "a", "senha", "do", "wifi", "?"], en: "Can you give me the wifi password?" },
            { tokens: ["A", "que", "horas", "fecha", "a", "recepção", "?"], en: "What time does reception close?" },
          ],
        },
      ],
    },
    {
      slug: "hotel-complaints",
      title: "When something's wrong — polite complaints",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The cushioned-complaint formula",
          body: [
            "Brazilians soften complaints with warmth. The pattern: <em>«Desculpa, mas…»</em> + the problem + <em>«…não está funcionando»</em>.",
            "<em>«Desculpa, mas o ar-condicionado não está funcionando.»</em> = Sorry, but the air conditioning isn't working.",
            "Even softer: <em>«Eu queria avisar de um probleminha…»</em> = I'd like to mention a small problem… (the <em>-inho/-inha</em> ending shrinks it and makes it gentler).",
            "Avoid blunt <em>«Eu quero…»</em> ('I want…') when complaining — use <em>«Eu queria…»</em> ('I'd like…') or <em>«Seria possível…?»</em> ('Would it be possible…?'). Tone matters a lot.",
          ],
          keyPoint:
            "Open with 'Desculpa, mas…' Soften with 'eu queria' / 'seria possível'. Never demand.",
        },
        {
          type: "vocab",
          heading: "When things break",
          items: [
            { l1: "não está funcionando", en: "(it) isn't working", note: "PT often: não está a funcionar" },
            { l1: "está quebrado / quebrada", en: "it's broken (m / f, BR)", note: "PT: está avariado/a" },
            { l1: "não tem água quente", en: "there's no hot water" },
            { l1: "está muito quente / frio", en: "it's too hot / cold" },
            { l1: "tem muito barulho", en: "there's a lot of noise" },
            { l1: "a luz não acende", en: "the light won't turn on" },
            { l1: "está faltando o…", en: "the … is missing" },
            { l1: "está sujo / suja", en: "it's dirty (m / f)" },
            { l1: "poderia…?", en: "could you…? (very polite)" },
            { l1: "seria possível…?", en: "would it be possible…?" },
            { l1: "trocar de quarto", en: "to change rooms" },
            { l1: "a reclamação", en: "the complaint" },
          ],
        },
        {
          type: "dialogue",
          heading: "Reporting an issue",
          setup: "You go down to reception after 11 pm.",
          lines: [
            { speaker: "Você", l1: "Boa noite. Desculpa incomodar, mas tem um problema no meu quarto.", en: "Good evening. Sorry to bother you, but there's a problem in my room." },
            { speaker: "Recepcionista", l1: "Pois não, o que aconteceu?", en: "Go ahead, what happened?" },
            { speaker: "Você", l1: "O ar-condicionado não está funcionando, e está muito quente. Seria possível mandar alguém dar uma olhada?", en: "The air conditioning isn't working, and it's very hot. Would it be possible to send someone to take a look?" },
            { speaker: "Recepcionista", l1: "Claro. Vou mandar o técnico agora mesmo. Se ele não conseguir consertar, eu troco o seu quarto.", en: "Of course. I'll send the technician right now. If he can't fix it, I'll switch your room." },
            { speaker: "Você", l1: "Muito obrigado. Pode trazer um ventilador enquanto isso?", en: "Thank you very much. Can you bring a fan in the meantime?" },
            { speaker: "Recepcionista", l1: "Já vou levar. Desculpe o transtorno.", en: "I'll bring one right away. Sorry for the trouble." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Polite complaint patterns",
          items: [
            {
              template: "Desculpa, mas a torneira está ___ .",
              answer: "quebrada",
              en: "Sorry, but the faucet is broken.",
              options: ["quebrada", "perdida", "cansada", "longe"],
            },
            {
              template: "Não tem água ___ no banheiro.",
              answer: "quente",
              en: "There's no hot water in the bathroom.",
              options: ["fria", "quente", "alta", "boa"],
            },
            {
              template: "Tem muito ___ vindo da rua.",
              answer: "barulho",
              en: "There's a lot of noise coming from the street.",
              options: ["barulho", "calor", "frio", "cheiro"],
            },
            {
              template: "Seria possível ___ de quarto?",
              answer: "trocar",
              en: "Would it be possible to change rooms?",
              options: ["pagar", "trocar", "comprar", "fechar"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Sorry, but the air conditioning isn't working and it's very hot.",
          reference: "Desculpa, mas o ar-condicionado não está funcionando e está muito quente.",
          hint: "'Isn't working' = não está funcionando. 'It's very hot' (weather/room) = está muito quente.",
        },
        {
          type: "tip",
          heading: "Tipping and small kindnesses",
          body: "Tipping at hotels in Brazil is optional and modest — a few reais for the <em>carregador</em> who brings up your bags, or for the <em>camareira</em> (housekeeper). Restaurants usually add a 10% <em>serviço</em> to the bill already. At checkout, if everything was great: <em>«Foi tudo perfeito, muito obrigado mesmo.»</em> A good online review goes a long way.",
          example: { l1: "Foi tudo perfeito, muito obrigado mesmo!", en: "Everything was perfect, thank you so much!" },
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'I have a reservation' =",
        options: [
          "Tenho um encontro.",
          "Tenho uma reserva.",
          "Faço uma reserva.",
          "Quero uma reserva.",
        ],
        correct: 1,
      },
      {
        q: "'Double room (one big bed)' =",
        options: [
          "quarto de solteiro",
          "quarto duplo",
          "quarto de casal",
          "quarto de família",
        ],
        correct: 2,
      },
      {
        q: "In Brazil, 'breakfast' is…",
        options: [
          "pequeno-almoço",
          "café da manhã",
          "almoço",
          "lanche da tarde",
        ],
        correct: 1,
      },
      {
        q: "'The air conditioning isn't working' =",
        options: [
          "O ar-condicionado está perdido.",
          "O ar-condicionado não está funcionando.",
          "O ar-condicionado não trabalha.",
          "O ar-condicionado está frio.",
        ],
        correct: 1,
      },
      {
        q: "Polite 'Would it be possible to…?' =",
        options: [
          "Eu quero…",
          "Eu tenho que…",
          "Seria possível…?",
          "Eu preciso…",
        ],
        correct: 2,
      },
      {
        q: "In Brazil, the room where you shower/use the toilet is the…",
        options: ["casa de banho", "WC", "banheiro", "lavandaria"],
        correct: 2,
      },
      {
        q: "'The wifi password' =",
        options: [
          "a senha do wifi",
          "a palavra do wifi",
          "o código do wifi",
          "a chave do wifi",
        ],
        correct: 0,
      },
      {
        q: "Translate: 'May I see your passport?'",
        options: [
          "Posso ver o teu passaporte?",
          "Posso ver o seu passaporte?",
          "Ver o passaporte?",
          "Me dá o passaporte.",
        ],
        correct: 1,
      },
      {
        q: "'I'd like to change rooms' =",
        options: [
          "Eu quero trocar de quarto.",
          "Eu queria trocar de quarto.",
          "Eu tenho que trocar de quarto.",
          "Troco de quarto.",
        ],
        correct: 1,
      },
      {
        q: "'Breakfast is included' =",
        options: [
          "O café da manhã é de graça.",
          "O café da manhã está incluído.",
          "O café da manhã está dentro.",
          "Incluo o café da manhã.",
        ],
        correct: 1,
      },
    ],
  },
};
