import type { Unit } from "../../types";

export const UNIT_HELP: Unit = {
  slug: "help",
  stage: 3,
  order: 13,
  icon: "🆘",
  title: "Emergencies & help",
  tagline: "Farmácia, pronto-socorro, pode me ajudar?",
  badge: "tourist",
  lessons: [
    {
      slug: "help-phrases",
      title: "The 10 emergency phrases",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Memorize these like you memorize 911",
          body: [
            "Brazil splits its emergencies across three numbers: <strong>190</strong> = polícia (military police), <strong>192</strong> = SAMU (ambulance), <strong>193</strong> = bombeiros (fire brigade).",
            "<strong>Socorro!</strong> = Help! (the cry you shout). Softer and more practical: <strong>Pode me ajudar?</strong> = Can you help me?",
            "<strong>Preciso de ajuda</strong> = I need help. <strong>Preciso de um médico</strong> = I need a doctor.",
            "<strong>Eu me perdi</strong> = I'm lost. <strong>Fui roubado / roubada</strong> = I was robbed (m / f).",
            "<strong>Está doendo aqui</strong> / <strong>Dói aqui</strong> = It hurts here (then point).",
          ],
          keyPoint:
            "190 polícia · 192 SAMU (ambulância) · 193 bombeiros. Socorro! / Pode me ajudar? Preciso de ajuda. Eu me perdi. Fui roubado/a.",
        },
        {
          type: "vocab",
          heading: "Emergency essentials",
          items: [
            { l1: "Socorro!", en: "Help! (the shout)" },
            { l1: "Pode me ajudar?", en: "Can you help me? (polite)" },
            { l1: "Preciso de ajuda", en: "I need help" },
            { l1: "Chame a polícia", en: "Call the police" },
            { l1: "Chame uma ambulância", en: "Call an ambulance" },
            { l1: "Preciso de um médico", en: "I need a doctor" },
            { l1: "Eu me perdi", en: "I'm lost" },
            { l1: "Fui roubado / roubada", en: "I was robbed (m / f)" },
            { l1: "Está doendo…", en: "It hurts… (then point or name body part)" },
            { l1: "Perdi minha carteira / meu passaporte", en: "I lost my wallet / passport" },
            { l1: "Roubaram meu celular", en: "They stole my phone" },
            { l1: "É uma emergência", en: "It's an emergency" },
          ],
        },
        {
          type: "tip",
          heading: "Three numbers, not one",
          body: "Unlike the single 911/112, Brazil routes emergencies separately: <strong>190</strong> for the <em>polícia militar</em>, <strong>192</strong> for <em>SAMU</em> (the ambulance service), and <strong>193</strong> for the <em>bombeiros</em> (firefighters — who also handle many rescues). If in doubt, dialing 190 will connect you and redirect. All three are free from any phone.",
          example: { l1: "Liga para o 192, é uma emergência!", en: "Call 192, it's an emergency!" },
        },
        {
          type: "tip",
          heading: "ER: pronto-socorro (BR) vs urgências (PT)",
          body: "In Brazil the emergency room is the <em>pronto-socorro</em> (often abbreviated <em>PS</em>); the public network is the <em>SUS</em>, free even for visitors in true emergencies. In Portugal the same place is called <em>urgências</em> (and the national emergency line there is 112). Same idea, different sign on the door.",
          example: { l1: "Onde fica o pronto-socorro mais próximo?", en: "Where is the nearest emergency room?" },
        },
        {
          type: "multipleChoice",
          heading: "Pick the right phrase",
          questions: [
            {
              q: "In Brazil, the number for an ambulance (SAMU) is…",
              options: ["190", "192", "193", "911"],
              correct: 1,
              fb: "192 = SAMU (ambulance). 190 = polícia, 193 = bombeiros.",
            },
            {
              q: "'Can you help me?' (polite) =",
              options: [
                "Socorro!",
                "Pode me ajudar?",
                "Quero ajuda.",
                "Ajuda você?",
              ],
              correct: 1,
              fb: "Pode me ajudar? is the everyday polite request. Socorro! is the emergency shout.",
            },
            {
              q: "'I was robbed' (female speaker) =",
              options: [
                "Fui roubado.",
                "Fui roubada.",
                "Roubei alguém.",
                "Estou roubada.",
              ],
              correct: 1,
              fb: "The past participle agrees with the speaker: roubada (f), roubado (m).",
            },
            {
              q: "'It hurts here' =",
              options: [
                "Dói você aqui.",
                "Está doendo aqui.",
                "Tenho dor você.",
                "Doer aqui.",
              ],
              correct: 1,
              fb: "Está doendo aqui or simply Dói aqui — both work.",
            },
            {
              q: "'It's an emergency' =",
              options: [
                "É uma emergência.",
                "Tenho uma emergência.",
                "É urgente!",
                "All three get the message across.",
              ],
              correct: 3,
            },
          ],
        },
      ],
    },
    {
      slug: "help-medical",
      title: "At the pharmacy & doctor",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The farmácia is your first stop",
          body: [
            "Brazilian pharmacies (<em>farmácias</em>, also called <em>drogarias</em>) are everywhere, and the pharmacist (<em>farmacêutico</em>) can recommend over-the-counter remedies for minor problems — headaches, upset stomach, allergies, colds.",
            "Many are open late or 24 hours in cities, and chains like Droga Raia, Drogasil and Pacheco are on nearly every corner. Look for the green cross.",
            "The most useful opening line is <em>«Preciso de algo para…»</em> = I need something for…",
          ],
          keyPoint:
            "Farmácia / drogaria = first medical stop. The pharmacist recommends OTC remedies. Open line: 'Preciso de algo para…'",
        },
        {
          type: "vocab",
          heading: "Pharmacy & remedies",
          items: [
            { l1: "a farmácia / a drogaria", en: "the pharmacy" },
            { l1: "o farmacêutico", en: "the pharmacist" },
            { l1: "a receita (médica)", en: "the prescription" },
            { l1: "o remédio", en: "the medicine" },
            { l1: "os comprimidos", en: "the tablets / pills" },
            { l1: "o xarope", en: "the syrup" },
            { l1: "a pomada", en: "the cream / ointment" },
            { l1: "o curativo / o band-aid", en: "the bandage / band-aid" },
            { l1: "a dor de cabeça", en: "headache" },
            { l1: "a dor de estômago", en: "stomachache" },
            { l1: "a dor de garganta", en: "sore throat" },
            { l1: "a febre", en: "fever" },
            { l1: "a tosse", en: "cough" },
            { l1: "o resfriado", en: "the cold (illness)" },
            { l1: "a alergia", en: "the allergy" },
            { l1: "sou alérgico/a a…", en: "I'm allergic to…" },
          ],
        },
        {
          type: "tip",
          heading: "Está doendo… vs Dói…",
          body: "Two natural ways to say something hurts. The progressive <em>está doendo</em> ('it's hurting') is very common in Brazil for an ongoing pain: <em>Está doendo a cabeça</em>. The simple present <em>dói</em> works too: <em>Dói a cabeça</em> / <em>Minha cabeça dói</em>. For 'I have a … pain', use <em>tenho dor de…</em> (tenho dor de cabeça).",
          example: { l1: "Está doendo muito aqui. / Dói aqui.", en: "It hurts a lot here. / It hurts here." },
        },
        {
          type: "dialogue",
          heading: "At the pharmacy",
          setup: "You walk in with a bad headache.",
          lines: [
            { speaker: "Farmacêutico", l1: "Boa tarde, pois não?", en: "Good afternoon, how can I help?" },
            { speaker: "Você", l1: "Boa tarde. Estou com uma forte dor de cabeça desde de manhã. Preciso de algo.", en: "Good afternoon. I've had a strong headache since this morning. I need something." },
            { speaker: "Farmacêutico", l1: "O senhor é alérgico a algum remédio?", en: "Are you allergic to any medicine?" },
            { speaker: "Você", l1: "Não, nada.", en: "No, nothing." },
            { speaker: "Farmacêutico", l1: "Então pode tomar este aqui. Um comprimido a cada oito horas, com bastante água. Beba bastante e tente descansar.", en: "Then you can take this one. One tablet every eight hours, with plenty of water. Drink a lot and try to rest." },
            { speaker: "Você", l1: "Perfeito, obrigado. Quanto custa?", en: "Perfect, thank you. How much is it?" },
            { speaker: "Farmacêutico", l1: "Doze reais.", en: "Twelve reais." },
          ],
        },
        {
          type: "vocab",
          heading: "Body parts",
          items: [
            { l1: "a cabeça", en: "head" },
            { l1: "o estômago / a barriga", en: "stomach / belly" },
            { l1: "as costas", en: "back" },
            { l1: "o braço / os braços", en: "arm / arms" },
            { l1: "a perna / as pernas", en: "leg / legs" },
            { l1: "o pé / os pés", en: "foot / feet" },
            { l1: "a mão / as mãos", en: "hand / hands" },
            { l1: "o dente / os dentes", en: "tooth / teeth" },
            { l1: "o ouvido / o orelha", en: "ear (inner / outer)" },
            { l1: "a garganta", en: "throat" },
            { l1: "o coração", en: "heart" },
            { l1: "a pele", en: "skin" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Symptoms",
          items: [
            {
              template: "Preciso de algo para a dor de ___ .",
              answer: "cabeça",
              en: "I need something for a headache.",
              options: ["cabeça", "carteira", "garganta", "febre"],
            },
            {
              template: "Estou com ___ de trinta e oito graus.",
              answer: "febre",
              en: "I have a fever of thirty-eight degrees.",
              options: ["tosse", "febre", "garganta", "resfriado"],
            },
            {
              template: "Sou ___ a amendoim.",
              answer: "alérgico",
              en: "I'm allergic to peanuts. (male speaker)",
              options: ["alérgico", "alérgica", "cansado", "perto"],
            },
            {
              template: "Estão doendo muito as minhas ___ .",
              answer: "costas",
              en: "My back really hurts.",
              options: ["costas", "cartas", "chaves", "contas"],
            },
            {
              template: "Estou com ___ e tosse.",
              answer: "resfriado",
              en: "I have a cold and a cough.",
              options: ["resfriado", "febre", "estômago", "cabeça"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'm allergic to penicillin. Is there an alternative?",
          reference: "Sou alérgico/a a penicilina. Tem uma alternativa?",
          hint: "'Alérgico' (m) or 'alérgica' (f). 'Tem…?' = is there…? (BR everyday).",
        },
      ],
    },
    {
      slug: "help-theft-lost",
      title: "Theft, lost items, the police",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "If something gets stolen",
          body: [
            "In big Brazilian cities, watch your phone and bag in crowds, on the metro, and at the beach. Petty theft (<em>furto</em>) is common; an armed mugging is an <em>assalto</em>.",
            "If it happens: <em>«Roubaram meu celular.»</em> = They stole my phone. Then go to a <em>delegacia</em> (police station) to file a <strong>boletim de ocorrência</strong> (the official report, abbreviated <em>B.O.</em>) — required for insurance and for replacing documents.",
            "Lost (not stolen) items: <em>«Perdi…»</em> Then ask about the <em>achados e perdidos</em> (lost-and-found).",
          ],
          keyPoint:
            "Stolen → roubaram meu… → fazer um boletim de ocorrência (B.O.) at the delegacia. Lost → perdi… → achados e perdidos.",
        },
        {
          type: "tip",
          heading: "celular (BR) vs telemóvel (PT)",
          body: "If your phone is what got stolen, the word you reach for differs by country. In Brazil a mobile phone is the <em>celular</em>; in Portugal it's the <em>telemóvel</em>. Both will be understood, but say <em>celular</em> with the Brazilian spine of this course.",
          example: { l1: "Roubaram o meu celular! (BR) · Roubaram-me o telemóvel! (PT)", en: "They stole my phone!" },
        },
        {
          type: "vocab",
          heading: "When things go wrong",
          items: [
            { l1: "a carteira", en: "the wallet" },
            { l1: "a bolsa", en: "the bag / purse" },
            { l1: "a mochila", en: "the backpack" },
            { l1: "o passaporte", en: "the passport" },
            { l1: "o celular", en: "the cell phone (BR)" },
            { l1: "as chaves", en: "the keys" },
            { l1: "roubar", en: "to rob / steal" },
            { l1: "o ladrão / a ladra", en: "the thief (m / f)" },
            { l1: "o assalto", en: "the mugging / hold-up" },
            { l1: "o boletim de ocorrência (B.O.)", en: "the police report" },
            { l1: "a delegacia", en: "the police station" },
            { l1: "a embaixada", en: "the embassy" },
            { l1: "o consulado", en: "the consulate" },
            { l1: "achados e perdidos", en: "lost and found" },
          ],
        },
        {
          type: "tip",
          heading: "'me ajuda' (BR) vs 'ajude-me' (PT)",
          body: "Brazilians put the object pronoun <em>before</em> the verb (proclisis), even at the start of a sentence: <em>Me ajuda!</em> / <em>Me ajuda, por favor.</em> European Portuguese (and formal writing) attaches it <em>after</em> the verb with a hyphen (enclisis): <em>Ajude-me!</em> Both mean 'Help me' — but spoken Brazil overwhelmingly says <em>me ajuda</em>.",
          example: { l1: "Me ajuda, por favor! (BR) · Ajude-me, por favor! (PT)", en: "Help me, please!" },
        },
        {
          type: "dialogue",
          heading: "Filing a police report",
          setup: "You arrive at the delegacia shaken up.",
          lines: [
            { speaker: "Policial", l1: "Boa tarde. Pois não?", en: "Good afternoon. How can I help?" },
            { speaker: "Você", l1: "Boa tarde. Roubaram minha carteira no ônibus. Quero fazer um boletim de ocorrência.", en: "Good afternoon. They stole my wallet on the bus. I want to file a police report." },
            { speaker: "Policial", l1: "Sinto muito. Quando foi que aconteceu?", en: "I'm sorry. When did it happen?" },
            { speaker: "Você", l1: "Faz mais ou menos uma hora, no centro.", en: "About an hour ago, downtown." },
            { speaker: "Policial", l1: "O que tinha na carteira?", en: "What was in the wallet?" },
            { speaker: "Você", l1: "Uns cem reais em dinheiro, dois cartões e a minha carteira de motorista.", en: "About a hundred reais in cash, two cards, and my driver's license." },
            { speaker: "Policial", l1: "A senhora já bloqueou os cartões?", en: "Have you already blocked the cards?" },
            { speaker: "Você", l1: "Já, liguei para o banco na hora.", en: "Yes, I called the bank right away." },
            { speaker: "Policial", l1: "Ótimo. Vou registrar a ocorrência. A senhora vai sair com uma cópia do B.O.", en: "Great. I'll register the report. You'll leave with a copy of the report." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Vocabulary in context",
          items: [
            {
              template: "___ o meu celular no metrô.",
              answer: "Roubaram",
              en: "They stole my phone on the metro.",
              options: ["Roubaram", "Perdi", "Achei", "Comprei"],
            },
            {
              template: "Quero fazer um ___ de ocorrência.",
              answer: "boletim",
              en: "I want to file a police report.",
              options: ["boletim", "pedido", "bilhete", "cartão"],
            },
            {
              template: "Perdi as ___ do quarto.",
              answer: "chaves",
              en: "I lost the room keys.",
              options: ["cartas", "chaves", "portas", "contas"],
            },
            {
              template: "Preciso ir até a ___ americana.",
              answer: "embaixada",
              en: "I need to go to the American embassy.",
              options: ["embaixada", "estação", "agência", "entrada"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the emergency sentence",
          items: [
            { tokens: ["Roubaram", "a", "minha", "carteira", "."], en: "They stole my wallet." },
            { tokens: ["Quero", "fazer", "um", "boletim", "de", "ocorrência", "."], en: "I want to file a police report." },
            { tokens: ["Onde", "fica", "a", "delegacia", "mais", "próxima", "?"], en: "Where is the nearest police station?" },
            { tokens: ["Preciso", "ligar", "para", "a", "embaixada", "."], en: "I need to call the embassy." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I lost my passport. Where is the American embassy?",
          reference: "Perdi o meu passaporte. Onde fica a embaixada americana?",
          hint: "'Perdi' = I lost. 'Onde fica…?' = where is…? 'Embaixada' takes 'americana' (feminine).",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "In Brazil, you call an ambulance (SAMU) on…",
        options: ["190", "192", "193", "911"],
        correct: 1,
      },
      {
        q: "'Help me!' (everyday Brazilian) =",
        options: ["Ajude-me!", "Me ajuda!", "Eu ajudo!", "Ajudar!"],
        correct: 1,
      },
      {
        q: "'I'm allergic to peanuts.' (male) =",
        options: [
          "Sou alérgica a amendoim.",
          "Tenho alergia para amendoim.",
          "Sou alérgico a amendoim.",
          "O amendoim me dá alergia.",
        ],
        correct: 2,
      },
      {
        q: "'They stole my wallet.' =",
        options: [
          "Roubei a carteira.",
          "Roubaram a minha carteira.",
          "A carteira está roubada.",
          "Perdi a carteira no roubo.",
        ],
        correct: 1,
      },
      {
        q: "In Brazil, the emergency room is called…",
        options: [
          "as urgências",
          "o pronto-socorro",
          "a delegacia",
          "a drogaria",
        ],
        correct: 1,
      },
      {
        q: "'I have a headache' =",
        options: [
          "Tenho a cabeça.",
          "Preciso de cabeça.",
          "Estou com dor de cabeça.",
          "Sou mal da cabeça.",
        ],
        correct: 2,
      },
      {
        q: "A 'boletim de ocorrência' is…",
        options: [
          "a restaurant complaint",
          "an official police report",
          "a visa application",
          "a hotel check-in form",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'I need a doctor.'",
        options: [
          "Quero um médico.",
          "Preciso de um médico.",
          "Tem médico?",
          "Sou um médico.",
        ],
        correct: 1,
      },
      {
        q: "'I was robbed' (female speaker) =",
        options: [
          "Fui roubado.",
          "Fui roubada.",
          "Estou roubada.",
          "Both B and C are fine.",
        ],
        correct: 1,
      },
      {
        q: "In Brazil a mobile phone is a…",
        options: [
          "telemóvel",
          "celular",
          "telefone fixo",
          "aparelho",
        ],
        correct: 1,
      },
    ],
  },
};
