import type { Unit } from "../../types";

export const UNIT_BAR: Unit = {
  slug: "bar",
  stage: 4,
  order: 15,
  icon: "☕",
  title: "At the bar / boteco",
  tagline: "Cafezinho, chope, caipirinha, salgadinhos, a conta.",
  badge: "tourist",
  lessons: [
    {
      slug: "bar-cafe-culture",
      title: "The cafezinho and the padaria",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Coffee is small, sweet, and everywhere",
          body: [
            "In Brazil, the default coffee is the <strong>cafezinho</strong> — a tiny, strong, usually pre-sweetened black coffee served in a little cup. People offer it everywhere: at the <em>padaria</em> (bakery), at work, at a friend's house, even at the mechanic.",
            "You don't go to a 'café' the way you might in Europe. The hub of daily coffee life is the <strong>padaria</strong> — part bakery, part lunch counter, part bar. You stand at the <em>balcão</em> (counter), drink fast, and pay on the way out.",
            "A coffee with a splash of hot milk is a <strong>pingado</strong> (literally 'dripped'); the bigger milky breakfast version is <strong>café com leite</strong>, almost always taken in the morning with bread.",
          ],
          keyPoint:
            "Cafezinho = small strong (often sweet) coffee. Pingado = coffee with a drop of milk. The padaria is the everyday coffee hub.",
        },
        {
          type: "vocab",
          heading: "Coffee menu basics",
          items: [
            { l1: "um cafezinho", en: "a small strong coffee (the default — often pre-sweetened)" },
            { l1: "um café", en: "a coffee (small black coffee)" },
            { l1: "um pingado", en: "coffee 'dripped' with a little hot milk" },
            { l1: "um café com leite", en: "coffee with lots of hot milk (breakfast drink)" },
            { l1: "um café expresso", en: "an espresso" },
            { l1: "um café duplo", en: "a double espresso" },
            { l1: "um café sem açúcar", en: "coffee without sugar" },
            { l1: "um café com adoçante", en: "coffee with sweetener" },
            { l1: "um descafeinado", en: "a decaf" },
            { l1: "um chá", en: "a tea" },
            { l1: "um copo de água", en: "a glass of water", note: "copo = drinking glass" },
            { l1: "um suco de laranja", en: "an orange juice", note: "suco = juice (BR)" },
          ],
        },
        {
          type: "tip",
          heading: "Suco (BR) vs sumo (PT) — and the espresso names",
          body: "In Brazil, juice is <em>suco</em>; in Portugal it's <em>sumo</em> (a <em>suco</em> in Portugal would sound odd). Espresso also splits: across Brazil it's <em>um café</em> or <em>um expresso</em>, but in Lisbon you order <em>uma bica</em>, and in Porto the same thing is <em>um cimbalino</em>. Ask for a 'bica' in São Paulo and you'll get a blank look.",
          example: { l1: "BR: um suco de laranja · PT: um sumo de laranja", en: "an orange juice" },
        },
        {
          type: "multipleChoice",
          heading: "Coffee comprehension",
          questions: [
            {
              q: "What is a 'cafezinho'?",
              options: ["a large milky coffee", "a small strong (often sweet) black coffee", "an iced coffee", "a decaf"],
              correct: 1,
              fb: "Cafezinho is the tiny, strong, frequently pre-sweetened coffee offered everywhere in Brazil.",
            },
            {
              q: "A 'pingado' is…",
              options: ["coffee with a drop of milk", "a double espresso", "black coffee, no sugar", "a tea"],
              correct: 0,
              fb: "Pingado comes from 'pingar' (to drip) — a coffee with just a little hot milk dripped in.",
            },
            {
              q: "In Brazil, the everyday hub for coffee and a quick bite is the…",
              options: ["café", "padaria", "boteco", "restaurante"],
              correct: 1,
              fb: "The padaria (bakery + counter + lunch spot) is where Brazilians grab daily coffee and bread.",
            },
            {
              q: "In Brazil, 'juice' is…",
              options: ["sumo", "suco", "jugo", "agua"],
              correct: 1,
              fb: "Suco in Brazil; sumo in Portugal. Same drink, different word.",
            },
            {
              q: "In Lisbon, you'd order an espresso by asking for…",
              options: ["um cafezinho", "uma bica", "um pingado", "um chope"],
              correct: 1,
              fb: "Lisbon: uma bica. Porto: um cimbalino. Brazil: um café / um expresso.",
            },
          ],
        },
      ],
    },
    {
      slug: "bar-ordering",
      title: "Ordering — the script",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Three phrases get you through any counter",
          body: [
            "1. <em>«Me vê um [item], por favor.»</em> = literally 'let me see a [item]', but used as 'give me / I'll have a [item]'. It's the most natural casual Brazilian way to order.",
            "2. <em>«Mais alguma coisa?»</em> = Anything else? Reply: <em>«Só isso, obrigado.»</em> ('that's all') or <em>«E um pão de queijo também.»</em> ('and a pão de queijo too').",
            "3. <em>«Quanto é?»</em> or <em>«Quanto deu?»</em> = How much is it? / How much was it? At a counter you often pay at the <em>caixa</em> (cashier).",
          ],
          keyPoint:
            "Order with 'me vê…' (casual) or 'eu queria…' (polite). Add a salgadinho. Pay with 'quanto é?'. Done.",
        },
        {
          type: "vocab",
          heading: "Salgadinhos & savory bites",
          intro: "The salty snacks that fill every padaria and boteco counter.",
          items: [
            { l1: "um salgadinho", en: "a savory snack (the whole category)" },
            { l1: "uma coxinha", en: "a teardrop-shaped fried dough filled with shredded chicken" },
            { l1: "um pão de queijo", en: "a chewy cheese bread ball (gluten-free, from Minas)" },
            { l1: "um pastel", en: "a crispy fried pastry pocket (great at street markets)" },
            { l1: "um bolinho de bacalhau", en: "a salt-cod fritter" },
            { l1: "uma esfiha", en: "an open or folded savory pastry (Lebanese-Brazilian)" },
            { l1: "um misto quente", en: "a hot ham-and-cheese toasted sandwich" },
            { l1: "um pão na chapa", en: "buttered bread toasted on the griddle" },
            { l1: "uma tapioca", en: "a tapioca-starch crêpe with fillings" },
            { l1: "um sanduíche", en: "a sandwich" },
            { l1: "uma água com gás", en: "sparkling water" },
            { l1: "um suco natural", en: "a freshly made juice" },
          ],
        },
        {
          type: "dialogue",
          heading: "Quick breakfast at the padaria",
          setup: "You walk up to the counter at 8 am.",
          lines: [
            { speaker: "Você", l1: "Bom dia!", en: "Good morning!" },
            { speaker: "Atendente", l1: "Bom dia! Pois não?", en: "Good morning! How can I help?" },
            { speaker: "Você", l1: "Me vê um pingado e um pão de queijo, por favor.", en: "Give me a coffee-with-milk and a pão de queijo, please." },
            { speaker: "Atendente", l1: "Mais alguma coisa?", en: "Anything else?" },
            { speaker: "Você", l1: "Só isso, obrigado.", en: "That's all, thank you." },
            { speaker: "Atendente", l1: "Pode pagar no caixa. Deu sete e cinquenta.", en: "You can pay at the cashier. That was seven fifty." },
            { speaker: "Você", l1: "Tá bom, valeu!", en: "Okay, thanks!" },
          ],
        },
        {
          type: "tip",
          heading: "'Me vê' and 'valeu' — sounding like a local",
          body: "<em>Me vê um café</em> sounds odd word-for-word ('see me a coffee'), but it's how Brazilians casually order — friendly and natural. For a more polite register, use <em>eu queria…</em> ('I'd like…'). And <em>valeu</em> is super-common spoken slang for 'thanks/cheers', a notch more casual than <em>obrigado</em>. Save 'valeu' for friendly settings.",
          example: { l1: "Me vê dois cafezinhos, por favor. — Valeu!", en: "Give me two little coffees, please. — Thanks!" },
        },
        {
          type: "fillBlank",
          heading: "Order builder",
          items: [
            {
              template: "___ um café e um pão de queijo, por favor.",
              answer: "Me vê",
              en: "Give me a coffee and a pão de queijo, please.",
              options: ["Me vê", "Me dá", "Eu vejo", "Both A and B work"],
            },
            {
              template: "Eu ___ um suco de laranja, por favor.",
              answer: "queria",
              en: "I'd like an orange juice, please.",
              options: ["queria", "quero não", "vou", "faço"],
            },
            {
              template: "Mais alguma ___ ?",
              answer: "coisa",
              en: "Anything else?",
              options: ["coisa", "vez", "hora", "conta"],
            },
            {
              template: "Quanto ___ ?",
              answer: "é",
              en: "How much is it?",
              options: ["é", "tem", "faz", "vai"],
            },
            {
              template: "Pode pagar no ___ .",
              answer: "caixa",
              en: "You can pay at the cashier.",
              options: ["caixa", "porta", "balcão", "copo"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the order",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Me", "vê", "um", "café", "e", "uma", "água", ",", "por", "favor"], en: "Give me a coffee and a water, please." },
            { tokens: ["Eu", "queria", "uma", "coxinha", "e", "um", "suco"], en: "I'd like a coxinha and a juice." },
            { tokens: ["Quanto", "é", "o", "pão", "de", "queijo", "?"], en: "How much is the pão de queijo?" },
            { tokens: ["Só", "isso", ",", "obrigado"], en: "That's all, thank you." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Give me a coffee and two pão de queijo, please.",
          reference: "Me vê um café e dois pães de queijo, por favor.",
          hint: "Use casual 'me vê'. Plural of pão de queijo = pães de queijo.",
        },
      ],
    },
    {
      slug: "bar-boteco",
      title: "Boteco & happy hour",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The boteco — Brazil's neighborhood bar",
          body: [
            "A <strong>boteco</strong> (or <em>botequim</em>) is the small, no-frills neighborhood bar where Brazilians gather after work for cold beer and <em>petiscos</em> (bar snacks). Plastic chairs on the sidewalk, a TV showing futebol, and friends — that's the boteco.",
            "The star drink is the <strong>chope</strong> — draft beer, served super cold in small glasses so it never goes warm. Bottled beer is <strong>cerveja</strong>, usually ordered as a big shared bottle kept on ice. The order to keep it coming: <em>«Mais um chope!»</em>",
            "The other icon is the <strong>caipirinha</strong> — cachaça (sugarcane spirit), lime, sugar, and ice. <em>Happy hour</em> (yes, the English term is used) runs roughly 6–9 pm with friends and petiscos.",
          ],
          keyPoint:
            "Boteco = casual neighborhood bar. Chope = cold draft beer. Cerveja = bottled beer. Caipirinha = the national cocktail.",
        },
        {
          type: "vocab",
          heading: "Boteco menu",
          items: [
            { l1: "um chope", en: "a draft beer (served very cold, small glass)" },
            { l1: "uma cerveja", en: "a (bottled) beer" },
            { l1: "uma cerveja long neck", en: "a long-neck bottled beer" },
            { l1: "uma caipirinha", en: "caipirinha (cachaça, lime, sugar, ice)" },
            { l1: "uma caipiroska", en: "caipirinha made with vodka instead of cachaça" },
            { l1: "uma dose de cachaça", en: "a shot of cachaça" },
            { l1: "uma taça de vinho", en: "a glass of wine" },
            { l1: "um refrigerante", en: "a soft drink" },
            { l1: "um petisco", en: "a bar snack / small plate" },
            { l1: "uma porção de batata frita", en: "a portion of fries" },
            { l1: "uma porção de mandioca frita", en: "a portion of fried cassava" },
            { l1: "uma porção de calabresa", en: "a portion of sliced sausage" },
            { l1: "amendoim", en: "peanuts" },
            { l1: "azeitonas", en: "olives" },
            { l1: "a comanda", en: "the tab / order slip the bar tracks for you" },
          ],
        },
        {
          type: "dialogue",
          heading: "Friday happy hour at the boteco",
          setup: "You and a friend grab a sidewalk table around 7 pm.",
          lines: [
            { speaker: "Garçom", l1: "Boa noite! O que vão querer?", en: "Good evening! What are you going to have?" },
            { speaker: "Você", l1: "Boa noite. Dois chopes, por favor, bem gelados.", en: "Good evening. Two draft beers, please, nice and cold." },
            { speaker: "Garçom", l1: "Vão querer alguma porção?", en: "Do you want any snack portion?" },
            { speaker: "Você", l1: "Uma porção de batata frita e uma de calabresa.", en: "A portion of fries and one of sausage." },
            { speaker: "Garçom", l1: "Perfeito. Vou anotar na comanda.", en: "Perfect. I'll note it on the tab." },
            { speaker: "Você", l1: "Depois mais um chope, tá? Valeu!", en: "Another draft after that, okay? Thanks!" },
            { speaker: "Garçom", l1: "Pode deixar!", en: "You got it! (lit. 'you can leave it')" },
          ],
        },
        {
          type: "tip",
          heading: "Chope (BR) vs imperial/fino (PT) — and the comanda",
          body: "In Brazil draft beer is <em>chope</em>; in Portugal the same draft is <em>uma imperial</em> (in the south/Lisbon) or <em>um fino</em> (in the north/Porto). Brazil's bottled beer is <em>cerveja</em>, ordered cold and shared. Also note the <strong>comanda</strong>: at most botecos a waiter tracks everything you order on one slip, and you settle it all at the end — you don't pay per round.",
          example: { l1: "BR: Mais um chope! · PT: Mais uma imperial / um fino!", en: "One more draft beer!" },
        },
        {
          type: "fillBlank",
          heading: "Boteco phrases",
          items: [
            {
              template: "Me vê dois ___ bem gelados.",
              answer: "chopes",
              en: "Give me two cold draft beers.",
              options: ["chopes", "cafés", "sucos", "vinhos"],
            },
            {
              template: "Uma ___ de batata frita, por favor.",
              answer: "porção",
              en: "A portion of fries, please.",
              options: ["porção", "taça", "dose", "comanda"],
            },
            {
              template: "Uma ___ , bem forte!",
              answer: "caipirinha",
              en: "A caipirinha, nice and strong!",
              options: ["caipirinha", "cerveja", "água", "chá"],
            },
            {
              template: "Pode anotar na ___ .",
              answer: "comanda",
              en: "You can note it on the tab.",
              options: ["comanda", "caixa", "porta", "garrafa"],
            },
            {
              template: "Mais ___ chope, por favor!",
              answer: "um",
              en: "One more draft beer, please!",
              options: ["um", "uma", "uns", "dois"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Two cold draft beers and a portion of fries, please.",
          reference: "Dois chopes bem gelados e uma porção de batata frita, por favor.",
          hint: "Draft beer = chope. 'Nice and cold' = bem gelado(s). Portion = porção.",
        },
        {
          type: "pronounce",
          heading: "Boteco words to practise aloud",
          items: [
            { l1: "chope", en: "draft beer", tip: "SHOH-pee (the final 'e' softens to 'ee' in BR)" },
            { l1: "caipirinha", en: "caipirinha", tip: "kai-pee-REEN-yah (nh = the 'ny' in canyon)" },
            { l1: "pão de queijo", en: "cheese bread", tip: "powng jee KAY-zhoo (ão is nasal)" },
            { l1: "coxinha", en: "chicken croquette", tip: "koh-SHEEN-yah" },
            { l1: "a conta, por favor", en: "the check, please", tip: "ah KOWN-tah pohr fah-VOHR" },
          ],
        },
      ],
    },
    {
      slug: "bar-conta",
      title: "Paying the bill",
      estMinutes: 7,
      pages: [
        {
          type: "intro",
          heading: "Asking for the conta and the 10%",
          body: [
            "When you're done at a boteco or restaurant, ask the waiter: <em>«A conta, por favor.»</em> ('the check, please'). At a counter padaria you instead pay at the <strong>caixa</strong> (cashier) on your way out.",
            "Most Brazilian sit-down places add a <strong>serviço (10%)</strong> — the optional-but-expected service charge, listed as <em>'serviço'</em> or <em>'taxa de serviço'</em> on the bill. It's not legally mandatory, so you can decline (<em>«sem o serviço, por favor»</em>), but paying it is the norm and replaces American-style tipping.",
            "To split: <em>«Pode dividir a conta?»</em> ('can you split the bill?'). To pay by card: <em>«Posso pagar no cartão?»</em>. Pix (instant transfer) is also everywhere now.",
          ],
          keyPoint:
            "Ask 'a conta, por favor'. Sit-down places add 10% serviço (optional but standard). Pay by cartão or Pix.",
        },
        {
          type: "vocab",
          heading: "Paying vocabulary",
          items: [
            { l1: "a conta", en: "the check / bill" },
            { l1: "o caixa", en: "the cashier / checkout" },
            { l1: "o serviço", en: "the service charge (usually 10%)" },
            { l1: "a gorjeta", en: "the tip" },
            { l1: "o cartão", en: "the (credit/debit) card" },
            { l1: "o Pix", en: "Pix (instant bank transfer, very common in BR)" },
            { l1: "dinheiro", en: "cash" },
            { l1: "o troco", en: "the change" },
            { l1: "dividir a conta", en: "to split the bill" },
            { l1: "a comanda", en: "the tab / order slip" },
          ],
        },
        {
          type: "dialogue",
          heading: "Settling up",
          setup: "You wave the waiter over at the end of the night.",
          lines: [
            { speaker: "Você", l1: "A conta, por favor.", en: "The check, please." },
            { speaker: "Garçom", l1: "Já trago. O serviço está incluído, dez por cento.", en: "I'll bring it. The service is included, ten percent." },
            { speaker: "Você", l1: "Tá ótimo. Posso pagar no cartão?", en: "Great. Can I pay by card?" },
            { speaker: "Garçom", l1: "Claro. Crédito ou débito?", en: "Of course. Credit or debit?" },
            { speaker: "Você", l1: "Crédito. E dá pra dividir em dois?", en: "Credit. And can we split it in two?" },
            { speaker: "Garçom", l1: "Dá sim, sem problema.", en: "Yes you can, no problem." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Paying comprehension",
          questions: [
            {
              q: "How do you ask for the check at a sit-down spot?",
              options: ["Quanto custa?", "A conta, por favor.", "Mais um chope.", "Pode deixar."],
              correct: 1,
              fb: "A conta, por favor = the check, please. (At a counter you'd just pay at the caixa.)",
            },
            {
              q: "The 'serviço' added to a Brazilian restaurant bill is usually…",
              options: ["20%", "10%", "5%", "nothing extra"],
              correct: 1,
              fb: "It's typically 10% — optional by law, but standard practice and it replaces American-style tipping.",
            },
            {
              q: "'Pix' refers to…",
              options: ["a cocktail", "an instant bank transfer", "a snack", "the cashier"],
              correct: 1,
              fb: "Pix is Brazil's ubiquitous instant transfer system — widely accepted even at small bars.",
            },
            {
              q: "'Pode dividir a conta?' means…",
              options: ["Can you bring the bill?", "Can you split the bill?", "Is service included?", "Can I pay cash?"],
              correct: 1,
              fb: "Dividir = to divide/split. 'Pode dividir a conta?' = can you split the bill?",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "The check, please. Can I pay by card?",
          reference: "A conta, por favor. Posso pagar no cartão?",
          hint: "Check = a conta. 'By card' = no cartão.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "A 'cafezinho' is…",
        options: ["a large iced coffee", "a small strong (often sweet) coffee", "coffee with whipped cream", "a decaf latte"],
        correct: 1,
      },
      {
        q: "A 'pingado' is coffee with…",
        options: ["a shot of cachaça", "a drop of hot milk", "no sugar", "extra water"],
        correct: 1,
      },
      {
        q: "In Brazil, 'juice' is…",
        options: ["sumo", "suco", "jugo", "água"],
        correct: 1,
      },
      {
        q: "In Lisbon, an espresso is ordered as…",
        options: ["um cafezinho", "uma bica", "um chope", "um pingado"],
        correct: 1,
      },
      {
        q: "The casual Brazilian way to order is…",
        options: ["Me vê um café", "Eu mando um café", "Dá-me um café", "Quero ver o café"],
        correct: 0,
      },
      {
        q: "A 'coxinha' is…",
        options: ["a cheese bread ball", "a salt-cod fritter", "a fried dough filled with shredded chicken", "a fried pastry pocket"],
        correct: 2,
      },
      {
        q: "In Brazil, draft beer is called…",
        options: ["uma imperial", "um fino", "um chope", "uma cerveja long neck"],
        correct: 2,
      },
      {
        q: "In Portugal, that same draft beer is…",
        options: ["um chope", "uma imperial / um fino", "uma caipirinha", "um pingado"],
        correct: 1,
      },
      {
        q: "A 'caipirinha' is made with…",
        options: ["vodka, lime, sugar", "cachaça, lime, sugar, ice", "rum and cola", "gin and tonic"],
        correct: 1,
      },
      {
        q: "The 'comanda' at a boteco is…",
        options: ["the tip", "the slip the bar tracks your order on", "the cashier", "the menu"],
        correct: 1,
      },
      {
        q: "How do you ask for the check?",
        options: ["A conta, por favor.", "Mais um chope.", "Pode deixar.", "Só isso."],
        correct: 0,
      },
      {
        q: "The 'serviço' on a Brazilian restaurant bill is usually…",
        options: ["20%", "10%", "mandatory by law", "a cover charge for bread"],
        correct: 1,
      },
    ],
  },
};
