import type { Unit } from "../../types";

export const UNIT_RESTAURANT: Unit = {
  slug: "restaurant",
  stage: 4,
  order: 16,
  icon: "🍽️",
  title: "At the restaurant",
  tagline: "Cardápio, prato do dia, pedir, a conta.",
  badge: "tourist",
  lessons: [
    {
      slug: "restaurant-menu",
      title: "The menu and how a Brazilian meal is built",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "O cardápio — reading a Brazilian menu",
          body: [
            "A meal out in Brazil is laid out in friendly, recognisable parts. <strong>A entrada</strong> = the starter (pão de alho, bolinho de bacalhau, a salad).",
            "<strong>O prato principal</strong> = the main course. This is the big plate, and in Brazil it almost always arrives with sides built in — rice, beans, farofa, and a salad are the unspoken backbone of lunch and dinner.",
            "<strong>A sobremesa</strong> = dessert. Think pudim de leite, brigadeiro, açaí, or a slice of bolo.",
            "<strong>Para beber</strong> = to drink. Brazilians love a <em>suco</em> (fresh juice), a <em>refrigerante</em> (soda), água, a beer (<em>uma cerveja</em>), or a coffee (<em>um cafezinho</em>) to finish.",
            "<strong>O prato do dia</strong> = the dish of the day — usually the best value and freshest thing on offer, written on a board or announced by the waiter.",
            "You don't have to order every part. A main with a juice is a perfectly normal lunch. Brazilians eat their big meal at midday, so lunch (<em>almoço</em>) is often heartier than dinner (<em>jantar</em>).",
          ],
          keyPoint:
            "entrada → prato principal (arroz, feijão, salada built in) → sobremesa, with algo para beber. The prato do dia is the smart-value pick.",
        },
        {
          type: "vocab",
          heading: "Menu structure",
          items: [
            { l1: "o cardápio", en: "the menu", note: "BR. In Portugal it's a ementa" },
            { l1: "a entrada", en: "the starter / appetizer" },
            { l1: "o prato principal", en: "the main course" },
            { l1: "o prato do dia", en: "the dish of the day", note: "Usually the best-value choice" },
            { l1: "a sobremesa", en: "dessert" },
            { l1: "para beber", en: "to drink (the drinks section)" },
            { l1: "a guarnição", en: "the side dish", note: "Often included with the main in Brazil" },
            { l1: "o couvert", en: "cover / bread basket charge", note: "Bread, pâtés, etc. — optional, you can refuse it" },
            { l1: "a porção", en: "a portion / shareable plate", note: "Bar-style sharing dish (fries, pastéis)" },
            { l1: "o combo / a refeição", en: "combo / set meal" },
          ],
        },
        {
          type: "vocab",
          heading: "Where Brazilians eat out",
          items: [
            { l1: "o restaurante", en: "the restaurant" },
            { l1: "o restaurante por quilo", en: "self-service by weight", note: "Pay by the weight of your plate — a Brazilian institution" },
            { l1: "a lanchonete", en: "snack bar / diner", note: "Quick bites, salgados, juices" },
            { l1: "a padaria", en: "bakery", note: "Also serves coffee, sandwiches, lunch" },
            { l1: "o boteco / o bar", en: "casual neighbourhood bar", note: "Cold beer + petiscos (small plates)" },
            { l1: "a churrascaria", en: "steakhouse", note: "Often rodízio — all-you-can-eat grilled meats" },
            { l1: "o rodízio", en: "all-you-can-eat (rotating service)", note: "Waiters circulate offering meat/pizza until you stop them" },
            { l1: "a sorveteria", en: "ice-cream shop" },
          ],
        },
        {
          type: "tip",
          heading: "Comida a quilo — the great Brazilian lunch",
          body: "The <em>restaurante por quilo</em> (also called <em>comida a quilo</em> or just <em>self-service</em>) is one of Brazil's best food inventions. You grab a plate, serve yourself from a big buffet, then put the plate on a scale at the end — you pay only for the <strong>weight</strong> of what you took. It's everywhere at lunchtime, fast, cheap, and lets you taste a bit of everything. Pro tip: heavy sides like rice and beans add up fast, so load up on the proteins and grilled veg if you want value.",
          example: { l1: "Quanto custa o quilo?", en: "How much is it per kilo?" },
        },
        {
          type: "tip",
          heading: "Cardápio (BR) vs ementa (PT), and suco vs sumo",
          body: "In Brazil the menu is <em>o cardápio</em>; in Portugal it's <em>a ementa</em> (and 'cardápio' sounds odd there). Fresh juice is <em>suco</em> in Brazil but <em>sumo</em> in Portugal. The waiter is <em>o garçom</em> in Brazil and <em>o empregado de mesa</em> in Portugal. Same restaurant, different words — Brazilians will understand 'ementa', but won't say it.",
          example: { l1: "BR: o cardápio, um suco · PT: a ementa, um sumo", en: "the menu, a juice" },
        },
        {
          type: "multipleChoice",
          heading: "Reading the menu",
          questions: [
            {
              q: "Which section lists desserts?",
              options: ["a entrada", "o prato principal", "a sobremesa", "para beber"],
              correct: 2,
              fb: "A sobremesa = dessert. A entrada is the starter; para beber is the drinks list.",
            },
            {
              q: "A 'restaurante por quilo' charges you by…",
              options: ["the number of dishes", "the weight of your plate", "a flat fee per person", "how long you stay"],
              correct: 1,
              fb: "You serve yourself, then weigh the plate — you pay for the weight of the food.",
            },
            {
              q: "The Brazilian word for the menu is…",
              options: ["a ementa", "o cardápio", "a carta", "o menu fixo"],
              correct: 1,
              fb: "o cardápio in Brazil; a ementa is the European-Portuguese word.",
            },
            {
              q: "'O prato do dia' is usually…",
              options: ["the most expensive item", "a dessert", "the best-value, freshest choice", "a children's meal"],
              correct: 2,
              fb: "The dish of the day is typically the freshest, best-value option.",
            },
            {
              q: "A 'churrascaria' serves mainly…",
              options: ["seafood", "grilled meats", "pizza", "ice cream"],
              correct: 1,
              fb: "A churrascaria is a steakhouse — often a rodízio of grilled meats.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "The menu, please. What's the dish of the day?",
          reference: "O cardápio, por favor. Qual é o prato do dia?",
          hint: "Use the Brazilian word for menu (cardápio). 'What is' = qual é.",
        },
      ],
    },
    {
      slug: "restaurant-ordering",
      title: "Getting a table and ordering",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "From the door to the order",
          body: [
            "<strong>Arriving:</strong> <em>«Boa noite, uma mesa para dois, por favor.»</em> (a table for two). For more people just swap the number — <em>para quatro</em>, etc.",
            "<strong>Getting the waiter's attention:</strong> a polite <em>«Com licença!»</em> or <em>«Garçom, por favor!»</em>. A small raised hand works too.",
            "<strong>Asking what's good:</strong> <em>«O que você recomenda?»</em> — always appreciated.",
            "<strong>Ordering:</strong> <em>«Eu vou querer…»</em> ('I'll have…') is the natural, everyday way Brazilians order. <em>«Para mim…»</em> ('for me…') works too.",
            "<strong>Drinks:</strong> <em>«Para beber, um suco de laranja e uma água sem gás.»</em>",
            "<strong>Still unsure?</strong> <em>«Pode me dar mais um minutinho?»</em> ('Can you give me one more minute?').",
          ],
          keyPoint:
            "uma mesa para dois → o cardápio → o que você recomenda? → eu vou querer… → para beber… → a conta.",
        },
        {
          type: "vocab",
          heading: "Ordering vocabulary",
          items: [
            { l1: "uma mesa para dois", en: "a table for two" },
            { l1: "o garçom / a garçonete", en: "the waiter / waitress", note: "BR. In Portugal: o empregado de mesa" },
            { l1: "Eu vou querer…", en: "I'll have… (lit. I'm going to want)", note: "The everyday way to order in Brazil" },
            { l1: "Para mim…", en: "For me…" },
            { l1: "O que você recomenda?", en: "What do you recommend?" },
            { l1: "Qual é a especialidade da casa?", en: "What's the house specialty?" },
            { l1: "sem gás / com gás", en: "still / sparkling (water)" },
            { l1: "o suco (de laranja)", en: "(orange) juice", note: "BR; PT says sumo" },
            { l1: "a caipirinha", en: "caipirinha", note: "Brazil's national cocktail — cachaça, lime, sugar" },
            { l1: "bem passado / ao ponto / mal passado", en: "well done / medium / rare", note: "How you want your meat" },
            { l1: "Pode me trazer…?", en: "Can you bring me…?" },
            { l1: "Estou pronto / pronta para pedir", en: "I'm ready to order" },
            { l1: "Pode ser", en: "That works / sure", note: "Friendly agreement" },
          ],
        },
        {
          type: "dialogue",
          heading: "Sitting down for dinner in Rio",
          setup: "It's 8 pm. You and a friend arrive at a busy restaurant in Ipanema.",
          lines: [
            { speaker: "Garçom", l1: "Boa noite! Mesa para quantas pessoas?", en: "Good evening! A table for how many people?" },
            { speaker: "Você", l1: "Boa noite. Uma mesa para dois, por favor.", en: "Good evening. A table for two, please." },
            { speaker: "Garçom", l1: "Pois não, podem me acompanhar. Aqui está o cardápio.", en: "Of course, follow me. Here's the menu." },
            { speaker: "Você", l1: "Obrigado. O que você recomenda hoje?", en: "Thank you. What do you recommend today?" },
            { speaker: "Garçom", l1: "O prato do dia é a moqueca de peixe, está saindo muito fresca. De entrada, os bolinhos de bacalhau são ótimos.", en: "The dish of the day is the fish moqueca, it's coming out very fresh. To start, the cod fritters are excellent." },
            { speaker: "Você", l1: "Então vamos querer uma porção de bolinhos para dividir, e depois a moqueca para mim.", en: "Then we'll have a portion of fritters to share, and then the moqueca for me." },
            { speaker: "Garçom", l1: "E para o seu amigo?", en: "And for your friend?" },
            { speaker: "Amigo", l1: "Para mim, o filé com arroz e feijão, bem passado.", en: "For me, the steak with rice and beans, well done." },
            { speaker: "Garçom", l1: "Perfeito. E para beber?", en: "Perfect. And to drink?" },
            { speaker: "Você", l1: "Um suco de maracujá e uma água sem gás, por favor.", en: "A passion-fruit juice and a still water, please." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Ordering blanks",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "Uma ___ para dois, por favor.",
              answer: "mesa",
              en: "A table for two, please.",
              options: ["mesa", "conta", "porção", "entrada"],
            },
            {
              template: "Eu vou ___ a moqueca de peixe.",
              answer: "querer",
              en: "I'll have the fish moqueca.",
              options: ["querer", "trazer", "pedir", "comer"],
            },
            {
              template: "O que você ___ hoje?",
              answer: "recomenda",
              en: "What do you recommend today?",
              options: ["recomenda", "quer", "traz", "gosta"],
            },
            {
              template: "Uma água ___ gás, por favor.",
              answer: "sem",
              en: "A still water, please.",
              options: ["sem", "com", "de", "para"],
            },
            {
              template: "Para ___ , um suco de laranja.",
              answer: "beber",
              en: "To drink, an orange juice.",
              options: ["beber", "comer", "mim", "mesa"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Restaurant phrases",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Uma", "mesa", "para", "quatro", ",", "por", "favor"], en: "A table for four, please." },
            { tokens: ["Eu", "vou", "querer", "o", "prato", "do", "dia"], en: "I'll have the dish of the day." },
            { tokens: ["Pode", "me", "trazer", "o", "cardápio", "?"], en: "Can you bring me the menu?" },
            { tokens: ["Para", "beber", ",", "uma", "caipirinha"], en: "To drink, a caipirinha." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "A table for two, please. I'll have the dish of the day.",
          reference: "Uma mesa para dois, por favor. Eu vou querer o prato do dia.",
          hint: "Use 'eu vou querer' for 'I'll have'. 'Dish of the day' = prato do dia.",
        },
      ],
    },
    {
      slug: "restaurant-paying",
      title: "Paying, tipping, and the by-weight scale",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "A conta, por favor",
          body: [
            "Like in much of the world, Brazilian waiters won't drop the check unprompted — just ask: <em>«A conta, por favor.»</em> or do the universal air-scribble pen gesture.",
            "<strong>The 10% service:</strong> most sit-down restaurants add a <em>serviço</em> of 10% (often labelled <em>«serviço 10%»</em> or <em>«taxa de serviço»</em>) to the bill. It's technically optional and you can decline it, but it's customary to leave it — it's the staff's tip. Beyond that 10%, extra tipping isn't expected.",
            "<strong>Paying:</strong> card is accepted almost everywhere (<em>«Aceitam cartão?»</em>). Brazil is very card- and Pix-friendly. <em>Pix</em> is the instant bank-transfer system everyone uses — many places will happily take a Pix payment.",
            "<strong>Splitting:</strong> <em>«A gente quer dividir a conta.»</em> ('We want to split the bill.') Splitting evenly is common and easy to ask for.",
            "<strong>At a por-quilo place:</strong> you don't ask for a menu check — you take your weighed plate's ticket (<em>a comanda</em>) to the cashier (<em>o caixa</em>) on the way out and pay there.",
          ],
          keyPoint:
            "Ask for a conta. The 10% serviço is the tip — leave it. Pay by cartão or Pix. Por-quilo: pay at o caixa with your comanda.",
        },
        {
          type: "vocab",
          heading: "Paying and leaving",
          items: [
            { l1: "a conta", en: "the bill / check" },
            { l1: "A conta, por favor", en: "The check, please" },
            { l1: "o serviço / a taxa de serviço", en: "the service charge (usually 10%)" },
            { l1: "a gorjeta", en: "the tip", note: "The 10% serviço is the customary tip" },
            { l1: "o cartão (de crédito / débito)", en: "(credit / debit) card" },
            { l1: "o Pix", en: "Pix (instant bank transfer)", note: "Hugely popular in Brazil" },
            { l1: "dinheiro", en: "cash" },
            { l1: "o troco", en: "the change" },
            { l1: "Pode ficar com o troco", en: "Keep the change" },
            { l1: "dividir a conta", en: "to split the bill" },
            { l1: "o caixa", en: "the cashier / checkout" },
            { l1: "a comanda", en: "the order ticket / tab", note: "What you carry to the caixa at a por-quilo place" },
            { l1: "Aceitam cartão?", en: "Do you take cards?" },
            { l1: "Estava tudo ótimo", en: "Everything was great" },
          ],
        },
        {
          type: "dialogue",
          heading: "Asking for the check",
          setup: "End of the meal. You catch the waiter's eye.",
          lines: [
            { speaker: "Você", l1: "Com licença, a conta, por favor!", en: "Excuse me, the check, please!" },
            { speaker: "Garçom", l1: "Claro. Estava tudo bem?", en: "Of course. Was everything okay?" },
            { speaker: "Você", l1: "Estava tudo ótimo, muito obrigado.", en: "Everything was great, thank you very much." },
            { speaker: "Garçom", l1: "Que bom! Aqui está a conta. O serviço de dez por cento já está incluído.", en: "Great! Here's the bill. The ten-percent service is already included." },
            { speaker: "Você", l1: "Perfeito. Vocês aceitam cartão?", en: "Perfect. Do you take cards?" },
            { speaker: "Garçom", l1: "Aceitamos cartão e Pix.", en: "We take cards and Pix." },
            { speaker: "Você", l1: "Então vou pagar no cartão de crédito.", en: "Then I'll pay by credit card." },
            { speaker: "Garçom", l1: "Já trago a maquininha. Obrigado, voltem sempre!", en: "I'll bring the card machine. Thank you, come back anytime!" },
          ],
        },
        {
          type: "tip",
          heading: "The 10% serviço is not a US-style tip",
          body: "Don't tip on top of the 10% the way you might in the United States. In Brazil the <em>serviço</em> line (usually 10%, sometimes optional) <strong>is</strong> the tip and goes to the staff. You can ask to remove it if service was genuinely bad (<em>«Sem o serviço, por favor.»</em>), but normally you just leave it. Rounding up a little extra for outstanding service is a nice gesture, but never expected.",
          example: { l1: "O serviço está incluído?", en: "Is the service charge included?" },
        },
        {
          type: "fillBlank",
          heading: "Paying-up phrases",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "A ___ , por favor.",
              answer: "conta",
              en: "The check, please.",
              options: ["conta", "comanda", "gorjeta", "mesa"],
            },
            {
              template: "Vocês ___ cartão?",
              answer: "aceitam",
              en: "Do you take cards?",
              options: ["aceitam", "querem", "trazem", "pagam"],
            },
            {
              template: "Pode ficar com o ___ .",
              answer: "troco",
              en: "Keep the change.",
              options: ["troco", "serviço", "caixa", "dinheiro"],
            },
            {
              template: "A gente quer ___ a conta.",
              answer: "dividir",
              en: "We want to split the bill.",
              options: ["dividir", "pagar", "trazer", "pedir"],
            },
            {
              template: "O ___ de dez por cento está incluído.",
              answer: "serviço",
              en: "The ten-percent service is included.",
              options: ["serviço", "troco", "cartão", "couvert"],
            },
          ],
        },
        {
          type: "pronounce",
          heading: "Restaurant phrases to practise aloud",
          items: [
            { l1: "A conta, por favor", en: "The check, please", tip: "ah KOHN-tah pohr fah-VOHR" },
            { l1: "Eu vou querer…", en: "I'll have…", tip: "eh-oo voh keh-REHR" },
            { l1: "O que você recomenda?", en: "What do you recommend?", tip: "oo kee voh-SEH heh-koh-MEN-dah" },
            { l1: "Aceitam cartão?", en: "Do you take cards?", tip: "ah-SEH-tãw kar-TÃW" },
            { l1: "Estava tudo ótimo", en: "Everything was great", tip: "es-TAH-vah TOO-doo OH-chee-moo" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Paying check",
          questions: [
            {
              q: "How do you ask for the bill?",
              options: ["O cardápio, por favor", "A conta, por favor", "Para beber, por favor", "A entrada, por favor"],
              correct: 1,
              fb: "A conta, por favor = the check, please.",
            },
            {
              q: "The 10% 'serviço' on a Brazilian bill is…",
              options: ["a government tax", "the staff tip — customary to leave", "an extra on top of your own tip", "a charge for water"],
              correct: 1,
              fb: "The serviço is the tip; you normally just leave it and don't add more.",
            },
            {
              q: "'Pix' is…",
              options: ["a dessert", "an instant bank transfer system", "a type of cocktail", "the cashier"],
              correct: 1,
              fb: "Pix is Brazil's instant bank-transfer payment, accepted almost everywhere.",
            },
            {
              q: "At a 'por quilo' restaurant you pay…",
              options: ["a flat fee per person", "by the weight of your plate, at o caixa", "only with cash", "before you eat"],
              correct: 1,
              fb: "You weigh your plate and pay for the weight at the caixa (cashier) with your comanda.",
            },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "The Brazilian word for the menu is…",
        options: ["a ementa", "o cardápio", "a carta", "o prato"],
        correct: 1,
      },
      {
        q: "'A sobremesa' is the…",
        options: ["starter", "main course", "dessert", "drinks list"],
        correct: 2,
      },
      {
        q: "A 'restaurante por quilo' charges you by…",
        options: [
          "the number of dishes",
          "the weight of your plate",
          "a flat fee per person",
          "the time you spend",
        ],
        correct: 1,
      },
      {
        q: "The everyday Brazilian way to say 'I'll have…' when ordering is…",
        options: ["Eu como…", "Eu vou querer…", "Eu peço…", "Eu trago…"],
        correct: 1,
      },
      {
        q: "'A table for two' is…",
        options: ["Uma conta para dois", "Uma mesa para dois", "Um prato para dois", "Uma porção para dois"],
        correct: 1,
      },
      {
        q: "How do you ask for the bill?",
        options: ["O cardápio, por favor", "A conta, por favor", "A entrada, por favor", "O troco, por favor"],
        correct: 1,
      },
      {
        q: "The 10% 'serviço' on the bill is…",
        options: [
          "a government tax",
          "the customary staff tip — usually left as is",
          "always mandatory and non-negotiable",
          "a charge for the bread basket",
        ],
        correct: 1,
      },
      {
        q: "'Still water' (no bubbles) is…",
        options: ["água com gás", "água sem gás", "água quente", "água da torneira"],
        correct: 1,
      },
      {
        q: "Brazil's hugely popular instant bank-transfer payment is called…",
        options: ["o troco", "o Pix", "a comanda", "o couvert"],
        correct: 1,
      },
      {
        q: "In Portugal, the menu is called… (vs Brazilian cardápio)",
        options: ["a carta", "a ementa", "o menu", "a lista"],
        correct: 1,
      },
    ],
  },
};
