import type { Unit } from "../../types";

export const UNIT_DRINKS_DIETARY: Unit = {
  slug: "drinks-dietary",
  stage: 4,
  order: 18,
  icon: "🍷",
  title: "Drinks & dietary needs",
  tagline: "Caipirinha, chope, vinho do Porto, sou vegetariano/a.",
  badge: "tourist",
  lessons: [
    {
      slug: "drinks-brazilian",
      title: "Brazilian drinks: caipirinha to caldo de cana",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "What Brazilians actually drink",
          body: [
            "The national cocktail is the <em>caipirinha</em> — <em>cachaça</em> (sugarcane spirit), lime, sugar, and ice. Order one and you'll instantly look like you know the place: <em>«Uma caipirinha, por favor.»</em>",
            "<em>Cachaça</em> (also nicknamed <em>pinga</em> or <em>branquinha</em>) is the base spirit. Beer is huge: ask for <em>uma cerveja</em> (bottled) or <em>um chope</em> (draft beer, served cold and foamy).",
            "Non-alcoholic stars: <em>o guaraná</em> (a uniquely Brazilian soda), <em>a água de coco</em> (coconut water, often drunk straight from the coconut on the beach), fresh <em>sucos</em> (juices), and <em>o caldo de cana</em> (pressed sugarcane juice from street carts).",
          ],
          keyPoint:
            "Caipirinha = the national cocktail (cachaça + lime + sugar). Chope = draft beer. Guaraná, água de coco, suco, caldo de cana = the everyday non-alcoholic stars.",
        },
        {
          type: "vocab",
          heading: "Brazilian drinks vocabulary",
          items: [
            { l1: "a caipirinha", en: "caipirinha (cachaça, lime, sugar, ice)" },
            { l1: "a cachaça", en: "cachaça (sugarcane spirit)", note: "Also called pinga or branquinha" },
            { l1: "a pinga", en: "cachaça (colloquial)", note: "Same drink, casual word" },
            { l1: "a cerveja", en: "beer (bottled / general)" },
            { l1: "o chope", en: "draft beer", note: "Served very cold, with foam (colarinho)" },
            { l1: "a caipiroska", en: "caipirinha made with vodka instead of cachaça" },
            { l1: "o guaraná", en: "guaraná (Brazilian soda)", note: "Antarctica and Kuat are common brands" },
            { l1: "a água de coco", en: "coconut water", note: "Often drunk from the coconut (no coco)" },
            { l1: "o suco", en: "juice", note: "suco de laranja / de maracujá / de abacaxi" },
            { l1: "o caldo de cana", en: "pressed sugarcane juice", note: "Also called garapa" },
            { l1: "a água", en: "water", note: "com gás / sem gás = sparkling / still" },
            { l1: "o refrigerante", en: "soft drink / soda" },
            { l1: "gelado / gelada", en: "ice-cold", note: "Brazilians love drinks estupidamente gelada" },
            { l1: "com gelo / sem gelo", en: "with ice / without ice" },
          ],
        },
        {
          type: "tip",
          heading: "Estupidamente gelada — cold is a virtue",
          body: "Brazilians prize a freezing drink. A bar advertising beer <em>«estupidamente gelada»</em> (stupidly cold) is promising it's just above freezing. If you want yours cold, say <em>«bem gelada, por favor»</em> = nice and cold, please. The opposite, a warm beer, is a near-insult.",
          example: { l1: "Uma cerveja bem gelada, por favor.", en: "A nice and cold beer, please." },
        },
        {
          type: "dialogue",
          heading: "Ordering at a beach kiosk in Rio",
          setup: "You walk up to a quiosque on Copacabana on a hot afternoon.",
          lines: [
            { speaker: "Atendente", l1: "Boa tarde! O que vai querer?", en: "Good afternoon! What'll you have?" },
            { speaker: "Você", l1: "Uma caipirinha e uma água de coco, por favor.", en: "A caipirinha and a coconut water, please." },
            { speaker: "Atendente", l1: "A caipirinha de limão tradicional ou de maracujá?", en: "Traditional lime caipirinha or passion fruit?" },
            { speaker: "Você", l1: "De maracujá. E pode ser com pouco açúcar?", en: "Passion fruit. And can it have less sugar?" },
            { speaker: "Atendente", l1: "Claro. A água de coco é na própria casca?", en: "Of course. The coconut water in the coconut itself?" },
            { speaker: "Você", l1: "Pode ser. Quanto fica tudo?", en: "Sure. How much for everything?" },
            { speaker: "Atendente", l1: "Trinta e cinco reais. Já trago.", en: "Thirty-five reais. I'll bring it right over." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Order the drink",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "Uma ___ de limão, por favor.",
              answer: "caipirinha",
              en: "A lime caipirinha, please.",
              options: ["caipirinha", "cerveja", "água", "suco"],
            },
            {
              template: "Um ___ bem gelado — a cerveja de chope.",
              answer: "chope",
              en: "A nice cold draft beer.",
              options: ["chope", "guaraná", "caldo", "vinho"],
            },
            {
              template: "Uma água de ___ , por favor.",
              answer: "coco",
              en: "A coconut water, please.",
              options: ["coco", "cana", "limão", "gás"],
            },
            {
              template: "A caipirinha leva cachaça, limão, açúcar e ___ .",
              answer: "gelo",
              en: "The caipirinha has cachaça, lime, sugar and ice.",
              options: ["gelo", "leite", "café", "sal"],
            },
            {
              template: "Um ___ de cana, comprado no carrinho da rua.",
              answer: "caldo",
              en: "A sugarcane juice, bought from the street cart.",
              options: ["caldo", "copo", "chope", "suco"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "A passion fruit caipirinha and a nice cold beer, please.",
          reference: "Uma caipirinha de maracujá e uma cerveja bem gelada, por favor.",
          hint: "Caipirinha de maracujá = passion fruit caipirinha. 'Nice and cold' = bem gelada (agrees with cerveja, feminine).",
        },
      ],
    },
    {
      slug: "drinks-wine-portugal",
      title: "Portuguese wine: vinho do Porto & vinho verde",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Wine the Portuguese way",
          body: [
            "Portugal is a wine powerhouse, and two names you must know: <em>o vinho do Porto</em> (Port — a sweet, fortified wine from the Douro valley, usually after dinner) and <em>o vinho verde</em> ('green wine' — young, slightly fizzy, low-alcohol, fantastic on a hot day).",
            "'Green' in <em>vinho verde</em> means young, not the colour — it's usually a crisp white. Order it chilled: <em>«Um vinho verde branco, bem fresco.»</em>",
            "The default safe order anywhere is the house wine: <em>«Vinho da casa, tinto (or branco).»</em> = house wine, red (or white). For Port after a meal, just say <em>«Um cálice de vinho do Porto.»</em> = a small glass of Port.",
          ],
          keyPoint:
            "Vinho do Porto = sweet fortified wine, after dinner. Vinho verde = young, slightly fizzy, served cold. Tinto = red, branco = white, vinho da casa = house wine.",
        },
        {
          type: "vocab",
          heading: "Wine vocabulary",
          items: [
            { l1: "o vinho", en: "wine" },
            { l1: "tinto / branco / rosé", en: "red / white / rosé", note: "Note: Brazilian/Portuguese red wine is 'tinto', not 'vermelho'" },
            { l1: "o vinho do Porto", en: "Port wine", note: "Fortified, sweet, from the Douro (PT)" },
            { l1: "o vinho verde", en: "vinho verde — young, lightly fizzy white (PT)" },
            { l1: "o vinho da casa", en: "house wine" },
            { l1: "uma garrafa / meia garrafa", en: "a bottle / half bottle" },
            { l1: "uma taça / um cálice", en: "a wine glass / a small (Port) glass" },
            { l1: "seco / meio-seco / suave", en: "dry / off-dry / sweet" },
            { l1: "encorpado", en: "full-bodied" },
            { l1: "leve", en: "light-bodied" },
            { l1: "frutado", en: "fruity" },
            { l1: "a safra", en: "vintage / harvest year" },
            { l1: "o espumante", en: "sparkling wine" },
            { l1: "gelado / fresco", en: "chilled / cool" },
          ],
        },
        {
          type: "vocab",
          heading: "Wines & spirits you'll see",
          items: [
            { l1: "Vinho do Porto (Douro)", en: "Port — sweet fortified, after dinner" },
            { l1: "Vinho Verde (Minho)", en: "young, crisp, slightly fizzy white" },
            { l1: "Vinho do Alentejo", en: "Alentejo reds — warm, full-bodied" },
            { l1: "Madeira", en: "Madeira — fortified wine from the island" },
            { l1: "Moscatel de Setúbal", en: "Moscatel — sweet dessert wine (PT)" },
            { l1: "a cachaça", en: "cachaça — Brazilian sugarcane spirit" },
            { l1: "a aguardente", en: "aguardente — grape/fruit brandy (PT digestivo)" },
            { l1: "a caipirinha", en: "Brazil's national cocktail (cachaça-based)" },
            { l1: "o licor Beirão", en: "Licor Beirão — popular Portuguese herbal liqueur" },
          ],
        },
        {
          type: "tip",
          heading: "Tinto, not vermelho — and BR vs PT wine words",
          body: "Red wine is always <em>vinho tinto</em> (never <em>vinho vermelho</em>) in both Brazil and Portugal. A glass of wine is <em>uma taça</em> in Brazil; in Portugal you'll also hear <em>um copo de vinho</em> for a casual glass and <em>um cálice</em> specifically for a small glass of Port. Brazil drinks far more beer and cachaça than wine, while Portugal is wine-first — but both understand all of these.",
          example: { l1: "BR: uma taça de vinho tinto · PT: um copo de vinho tinto", en: "a glass of red wine" },
        },
        {
          type: "dialogue",
          heading: "Choosing wine at dinner in Lisbon",
          setup: "The waiter asks what you'd like to drink with your meal.",
          lines: [
            { speaker: "Empregado", l1: "Para beber, querem vinho?", en: "To drink, would you like wine?" },
            { speaker: "Você", l1: "Sim. O que recomenda com o peixe?", en: "Yes. What do you recommend with the fish?" },
            { speaker: "Empregado", l1: "Um vinho verde branco, bem fresco. Acompanha lindamente.", en: "A white vinho verde, nice and cool. It pairs beautifully." },
            { speaker: "Você", l1: "Ótimo. Uma garrafa, por favor. E quanto custa?", en: "Great. A bottle, please. And how much is it?" },
            { speaker: "Empregado", l1: "Dezoito euros. No fim, posso sugerir um cálice de vinho do Porto?", en: "Eighteen euros. At the end, may I suggest a glass of Port?" },
            { speaker: "Você", l1: "Pode ser, obrigado. Adoro vinho do Porto.", en: "Sure, thank you. I love Port." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Know your wine",
          questions: [
            {
              q: "'Vinho verde' is…",
              options: [
                "a green-coloured wine",
                "a young, lightly fizzy wine (usually white), served cold",
                "a Port wine",
                "a dessert wine from Madeira",
              ],
              correct: 1,
              fb: "'Verde' (green) means young, not the colour. It's crisp, low-alcohol, slightly fizzy — usually white.",
            },
            {
              q: "How do you say 'red wine'?",
              options: ["vinho vermelho", "vinho tinto", "vinho rubro", "vinho rosado"],
              correct: 1,
              fb: "Red wine is always vinho tinto — never vinho vermelho.",
            },
            {
              q: "When is vinho do Porto typically drunk?",
              options: [
                "as an aperitif before the meal only",
                "with the main course",
                "after dinner, as a sweet fortified wine",
                "mixed with cachaça",
              ],
              correct: 2,
              fb: "Port is a sweet, fortified wine usually enjoyed after dinner, often as a cálice (small glass).",
            },
            {
              q: "'Uma garrafa de vinho da casa' means…",
              options: [
                "a glass of the house wine",
                "a bottle of the house wine",
                "a half bottle of Port",
                "a carafe of sparkling wine",
              ],
              correct: 1,
              fb: "garrafa = bottle; vinho da casa = house wine. (meia garrafa = half bottle.)",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'd like a bottle of white vinho verde, nice and cool, please.",
          reference: "Eu queria uma garrafa de vinho verde branco, bem fresco, por favor.",
          hint: "'I'd like' = eu queria. garrafa = bottle. 'Nice and cool' = bem fresco.",
        },
      ],
    },
    {
      slug: "drinks-dietary-needs",
      title: "Allergies & dietary needs",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Saying what you can and can't eat",
          body: [
            "Lead with who you are: <em>«Sou vegetariano.»</em> / <em>«Sou vegetariana.»</em> = I'm vegetarian (m/f). For vegan, <em>«Sou vegano.»</em> / <em>«Sou vegana.»</em>",
            "For allergies: <em>«Tenho alergia a…»</em> = I'm allergic to… (literally 'I have an allergy to'). For intolerance: <em>«Tenho intolerância a…»</em> = I have an intolerance to…",
            "The most useful checking questions: <em>«Isso tem leite?»</em> / <em>«Isso tem carne?»</em> = Does this have milk / meat? And the labels: <em>«sem glúten»</em> (gluten-free), <em>«sem lactose»</em> (lactose-free).",
          ],
          keyPoint:
            "Sou vegetariano/a · Sou vegano/a · Tenho alergia a… · Tenho intolerância a… · Isso tem leite/carne? · sem glúten / sem lactose.",
        },
        {
          type: "vocab",
          heading: "Diet & allergen vocabulary",
          items: [
            { l1: "vegetariano / vegetariana", en: "vegetarian (m / f)" },
            { l1: "vegano / vegana", en: "vegan (m / f)" },
            { l1: "a alergia", en: "allergy", note: "tenho alergia a… = I'm allergic to…" },
            { l1: "a intolerância", en: "intolerance", note: "tenho intolerância a lactose" },
            { l1: "sem glúten", en: "gluten-free" },
            { l1: "sem lactose", en: "lactose-free" },
            { l1: "o glúten", en: "gluten" },
            { l1: "a lactose", en: "lactose" },
            { l1: "o leite / os laticínios", en: "milk / dairy products" },
            { l1: "os ovos", en: "eggs" },
            { l1: "o trigo", en: "wheat" },
            { l1: "o amendoim", en: "peanut" },
            { l1: "as castanhas", en: "tree nuts", note: "castanha-do-pará, castanha-de-caju" },
            { l1: "os frutos do mar", en: "seafood / shellfish", note: "PT: marisco" },
            { l1: "o camarão", en: "shrimp" },
            { l1: "o peixe", en: "fish" },
            { l1: "a soja", en: "soy" },
            { l1: "a carne (de porco / de vaca)", en: "meat (pork / beef)" },
          ],
        },
        {
          type: "tip",
          heading: "Frutos do mar (BR) vs marisco (PT)",
          body: "For shellfish/seafood, Brazil says <em>frutos do mar</em> while Portugal usually says <em>marisco</em>. Both are understood, but if you're allergic, say it clearly: <em>«Tenho alergia a frutos do mar (BR) / a marisco (PT).»</em> Also note dairy: 'milk' is <em>leite</em>, but the umbrella 'dairy products' is <em>laticínios</em> — worth knowing when you ask <em>«Tem laticínios?»</em>",
          example: { l1: "Tenho alergia a camarão e a frutos do mar.", en: "I'm allergic to shrimp and seafood." },
        },
        {
          type: "dialogue",
          heading: "Flagging a milk allergy",
          setup: "Before ordering dessert, you check the ingredients.",
          lines: [
            { speaker: "Você", l1: "Com licença, eu tenho alergia a leite. Isso tem leite ou laticínios?", en: "Excuse me, I'm allergic to milk. Does this have milk or dairy?" },
            { speaker: "Garçom", l1: "Esse pudim tem, sim. Mas temos uma sobremesa de frutas sem lactose.", en: "That pudding does, yes. But we have a fruit dessert that's lactose-free." },
            { speaker: "Você", l1: "Perfeito. Ela é feita sem manteiga também?", en: "Perfect. Is it made without butter too?" },
            { speaker: "Garçom", l1: "Sim, só frutas e um pouco de mel. Sem nada de leite.", en: "Yes, just fruit and a little honey. No milk at all." },
            { speaker: "Você", l1: "Ótimo, vou querer essa. Muito obrigado.", en: "Great, I'll have that one. Thank you very much." },
          ],
        },
        {
          type: "dialogue",
          heading: "Vegetarian at a churrascaria",
          setup: "Brazilian steakhouses are meat-central. You're vegetarian.",
          lines: [
            { speaker: "Você", l1: "Sou vegetariana. O que vocês têm sem carne?", en: "I'm vegetarian. What do you have without meat?" },
            { speaker: "Garçom", l1: "Temos um bufê de saladas, queijos, palmito, arroz, feijão e legumes grelhados.", en: "We have a salad bar, cheeses, palm hearts, rice, beans and grilled vegetables." },
            { speaker: "Você", l1: "O feijão é feito com carne de porco?", en: "Is the beans made with pork?" },
            { speaker: "Garçom", l1: "A feijoada sim, mas temos um feijão simples, sem carne.", en: "The feijoada yes, but we have a plain beans, without meat." },
            { speaker: "Você", l1: "Que bom. E tem alguma opção sem glúten no bufê?", en: "Good. And is there a gluten-free option at the buffet?" },
            { speaker: "Garçom", l1: "O arroz, o feijão simples e as saladas são sem glúten.", en: "The rice, the plain beans and the salads are gluten-free." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Diet fill-ins",
          intro: "Pick the right word.",
          items: [
            {
              template: "Sou ___ , não como carne nem peixe.",
              answer: "vegetariana",
              en: "I'm vegetarian (female), I don't eat meat or fish.",
              options: ["vegetariana", "vegetariano", "vegana", "alérgica"],
            },
            {
              template: "Tenho ___ a amendoim.",
              answer: "alergia",
              en: "I'm allergic to peanuts.",
              options: ["alergia", "fome", "vontade", "medo"],
            },
            {
              template: "Vocês têm pão ___ glúten?",
              answer: "sem",
              en: "Do you have gluten-free bread?",
              options: ["sem", "com", "de", "do"],
            },
            {
              template: "Tenho intolerância a ___ , então nada de leite.",
              answer: "lactose",
              en: "I'm lactose intolerant, so no milk.",
              options: ["lactose", "glúten", "soja", "trigo"],
            },
            {
              template: "Isso ___ carne?",
              answer: "tem",
              en: "Does this have meat?",
              options: ["tem", "é", "está", "faz"],
            },
          ],
        },
        {
          type: "pronounce",
          heading: "Say it clearly (it matters for safety)",
          items: [
            { l1: "Sou vegetariano / vegetariana", en: "I'm vegetarian (m/f)", tip: "soh veh-zheh-tah-ree-AH-noo / -nah" },
            { l1: "Tenho alergia a amendoim", en: "I'm allergic to peanuts", tip: "TEH-nyoo ah-ler-ZHEE-ah ah ah-men-doh-EEN" },
            { l1: "Sem glúten", en: "Gluten-free", tip: "seng GLOO-ten" },
            { l1: "Sem lactose", en: "Lactose-free", tip: "seng lahk-TOH-zee" },
            { l1: "Isso tem leite?", en: "Does this have milk?", tip: "EE-soo teng LAY-chee" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Dietary check",
          questions: [
            {
              q: "'I'm allergic to shrimp' =",
              options: [
                "Sou camarão.",
                "Tenho alergia a camarão.",
                "Quero camarão.",
                "Não gosto de camarão.",
              ],
              correct: 1,
              fb: "Tenho alergia a… = I have an allergy to… The literal 'I have' (tenho) is the natural phrasing.",
            },
            {
              q: "A woman says she's vegan. She says…",
              options: ["Sou vegano.", "Sou vegana.", "Tenho vegana.", "Estou vegana."],
              correct: 1,
              fb: "Sou vegana — the ending agrees with the speaker's gender, and 'sou' (permanent) is correct, not 'estou'.",
            },
            {
              q: "Which question checks for milk in a dish?",
              options: [
                "Isso tem leite?",
                "Isso é leite?",
                "Onde está o leite?",
                "Quanto custa o leite?",
              ],
              correct: 0,
              fb: "Isso tem leite? = Does this have milk? 'Tem' (has) is what you want for ingredients.",
            },
            {
              q: "In Portugal, 'seafood/shellfish' is usually called…",
              options: ["frutos do mar", "marisco", "peixe", "camarão"],
              correct: 1,
              fb: "Portugal says marisco; Brazil says frutos do mar. Both understood, but marisco is the PT default.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'm vegetarian and I'm allergic to peanuts. Does this have meat or nuts?",
          reference: "Sou vegetariano/a e tenho alergia a amendoim. Isso tem carne ou castanhas?",
          hint: "Sou + vegetariano/a. 'I'm allergic to' = tenho alergia a. 'Does this have…' = Isso tem…?",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "The main spirit in a caipirinha is…",
        options: ["vodka", "cachaça", "rum", "vinho do Porto"],
        correct: 1,
      },
      {
        q: "'Chope' is…",
        options: ["sugarcane juice", "draft beer", "coconut water", "a soft drink"],
        correct: 1,
      },
      {
        q: "Which is a uniquely Brazilian soft drink?",
        options: ["guaraná", "vinho verde", "aguardente", "moscatel"],
        correct: 0,
      },
      {
        q: "'Água de coco' is…",
        options: ["sparkling water", "coconut water", "coconut liqueur", "a cocktail"],
        correct: 1,
      },
      {
        q: "Red wine is…",
        options: ["vinho vermelho", "vinho tinto", "vinho rubro", "vinho rosé"],
        correct: 1,
      },
      {
        q: "Vinho do Porto is a…",
        options: [
          "young, fizzy white wine",
          "sweet fortified wine, usually after dinner",
          "Brazilian beer",
          "sugarcane spirit",
        ],
        correct: 1,
      },
      {
        q: "'I'm vegetarian' (woman speaking) =",
        options: ["Sou vegetariano.", "Sou vegetariana.", "Estou vegetariana.", "Tenho vegetariana."],
        correct: 1,
      },
      {
        q: "'I'm allergic to peanuts' =",
        options: [
          "Sou amendoim.",
          "Tenho alergia a amendoim.",
          "Não como amendoim.",
          "Quero amendoim.",
        ],
        correct: 1,
      },
      {
        q: "'Gluten-free' =",
        options: ["sem glúten", "com glúten", "sem lactose", "anti-glúten"],
        correct: 0,
      },
      {
        q: "Which question asks 'Does this have milk?'",
        options: ["Isso é leite?", "Isso tem leite?", "Onde tem leite?", "Quanto é o leite?"],
        correct: 1,
      },
    ],
  },
};
