import type { Unit } from "../../types";

export const UNIT_MUSIC_CULTURE: Unit = {
  slug: "music-culture",
  stage: 7,
  order: 30,
  icon: "🎶",
  title: "Music & culture",
  tagline: "Samba, bossa nova, Carnaval, fado, futebol.",
  badge: "culture",
  lessons: [
    {
      slug: "music-culture-brazilian-sounds",
      title: "Brazilian sounds",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Brazil is a country of rhythms",
          body: [
            "You can't understand Brazil without its music. It's everywhere — in bars, on the beach, on the bus, at family barbecues. Each region and generation has its own sound, and people are fiercely proud of theirs.",
            "The big names you'll meet: <strong>o samba</strong> (born in Rio, the heartbeat of Carnaval), <strong>a bossa nova</strong> (the soft, jazzy 1960s sound of <em>Garota de Ipanema</em>), and <strong>a MPB</strong> — <em>Música Popular Brasileira</em>, the sophisticated singer-songwriter tradition of Caetano Veloso, Gilberto Gil, and Elis Regina.",
            "Then come the dance floors: <strong>o forró</strong> (accordion-driven music from the Northeast, danced in couples), <strong>o axé</strong> (the high-energy pop of Salvador's Carnaval), and <strong>o funk carioca</strong> (Rio's heavy, electronic street funk — completely different from American funk).",
          ],
          keyPoint:
            "samba + bossa nova + MPB = the classics · forró, axé, funk carioca = the dance floors. Music is regional and people are proud of theirs.",
        },
        {
          type: "vocab",
          heading: "Music vocabulary",
          intro: "The words to talk about what you're listening to.",
          items: [
            { l1: "a música", en: "music / a song", note: "Same word for both — context decides" },
            { l1: "a canção", en: "song", note: "More specifically a composed song" },
            { l1: "o som", en: "the sound / the music (slang)", note: "'Que som é esse?' = what's this track?" },
            { l1: "o cantor / a cantora", en: "singer (m / f)", note: "" },
            { l1: "a banda", en: "the band", note: "" },
            { l1: "o ritmo", en: "the rhythm", note: "Central to Brazilian music" },
            { l1: "a batida", en: "the beat", note: "lit. the 'hit' / drumbeat" },
            { l1: "o violão", en: "the (acoustic) guitar", note: "Note: a guitarra = electric guitar" },
            { l1: "o pandeiro", en: "the tambourine", note: "The soul of a samba circle" },
            { l1: "o cavaquinho", en: "the cavaquinho", note: "A small four-string ukulele-like guitar" },
            { l1: "a letra", en: "the lyrics", note: "" },
            { l1: "o show", en: "the (live) concert / gig", note: "Borrowed from English" },
          ],
        },
        {
          type: "tip",
          heading: "Bossa nova means 'new wave'",
          body: "<em>Bossa nova</em> literally means 'new trend' or 'new wave'. It emerged in late-1950s Rio when João Gilberto married samba's rhythm to cool jazz harmony and a whisper-quiet vocal. Tom Jobim wrote the songs; <em>Garota de Ipanema</em> ('The Girl from Ipanema') became one of the most recorded songs on Earth. If a Brazilian puts on bossa, the mood just turned mellow.",
          example: { l1: "Coloca um som de bossa nova, por favor.", en: "Put on some bossa nova, please." },
        },
        {
          type: "multipleChoice",
          heading: "Quick check",
          questions: [
            {
              q: "What does 'MPB' stand for?",
              options: ["Música Pop Brasil", "Música Popular Brasileira", "Movimento Popular do Brasil", "Música Por Bairro"],
              correct: 1,
              fb: "MPB = Música Popular Brasileira, the singer-songwriter tradition of Caetano, Gil and Elis.",
            },
            {
              q: "Which instrument is the soul of a samba circle?",
              options: ["o violão", "o pandeiro", "a guitarra", "o piano"],
              correct: 1,
              fb: "O pandeiro (tambourine) drives the rhythm in a roda de samba.",
            },
            {
              q: "'O funk carioca' is…",
              options: ["the same as American funk", "Rio's electronic street funk", "a type of bossa nova", "Northeastern accordion music"],
              correct: 1,
              fb: "Funk carioca is Rio's own heavy electronic street sound — unrelated to American funk.",
            },
            {
              q: "Forró is associated most with which region?",
              options: ["the South", "Rio de Janeiro", "the Northeast (Nordeste)", "São Paulo"],
              correct: 2,
              fb: "Forró, with its accordion and couple-dancing, comes from the Nordeste.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Fill the music word",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "Eu adoro a ___ dessa canção.",
              answer: "letra",
              en: "I love the lyrics of this song.",
              options: ["letra", "batida", "banda", "som"],
            },
            {
              template: "O ___ tocou um samba lindo no violão.",
              answer: "cantor",
              en: "The singer played a beautiful samba on the guitar.",
              options: ["cantor", "ritmo", "pandeiro", "show"],
            },
            {
              template: "Que ___ é esse? É tão dançante!",
              answer: "ritmo",
              en: "What rhythm is this? It's so danceable!",
              options: ["ritmo", "letra", "violão", "cantora"],
            },
            {
              template: "Vamos ao ___ do Gilberto Gil sábado.",
              answer: "show",
              en: "Let's go to Gilberto Gil's concert on Saturday.",
              options: ["show", "som", "ritmo", "pandeiro"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I love Brazilian music. The rhythm is wonderful.",
          reference: "Eu adoro música brasileira. O ritmo é maravilhoso.",
          hint: "'I love' = eu adoro. 'wonderful' = maravilhoso (agrees with o ritmo, m sg).",
        },
      ],
    },
    {
      slug: "music-culture-carnaval-futebol",
      title: "Carnaval, futebol & the beach",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Three Brazilian passions",
          body: [
            "<strong>O Carnaval</strong> is the biggest party on the planet. In Rio, samba schools (<em>as escolas de samba</em>) parade through <strong>o sambódromo</strong>, each with thousands of dancers, drummers (<em>a bateria</em>), and a giant theme. In Salvador, the streets fill with <em>trios elétricos</em> — trucks blasting axé. In Recife and Olinda, it's frevo and maracatu. The week before Lent, the country basically stops.",
            "<strong>O futebol</strong> is the national religion. Brazil has won the World Cup (<em>a Copa do Mundo</em>) five times — more than anyone. People support a <em>time</em> (team) the way they support a family, and a big match empties the streets. Phrases like <em>Gooool!</em> and <em>torcer pelo meu time</em> ('to root for my team') are daily vocabulary.",
            "And then there's <strong>a praia</strong> — the beach. In Rio especially, the beach is a way of life: <em>Copacabana</em>, <em>Ipanema</em>, the morning walk, the beach volleyball, the <em>água de coco</em> from a kiosk. The beach is where music, football, and friends all come together.",
          ],
          keyPoint:
            "Carnaval (escolas de samba in the sambódromo) · futebol (Copa do Mundo × 5, you torcer pelo seu time) · a praia (Rio's way of life).",
        },
        {
          type: "vocab",
          heading: "Carnaval & celebration",
          items: [
            { l1: "o Carnaval", en: "Carnival", note: "The week before Lent" },
            { l1: "a escola de samba", en: "the samba school", note: "Parades in the sambódromo" },
            { l1: "o sambódromo", en: "the Sambadrome", note: "Rio's parade stadium (designed by Niemeyer)" },
            { l1: "o desfile", en: "the parade", note: "" },
            { l1: "a fantasia", en: "the costume", note: "False friend! Not 'fantasy' — it means costume" },
            { l1: "a bateria", en: "the drum section", note: "lit. 'battery' — the school's percussion corps" },
            { l1: "o bloco", en: "the street party / parade group", note: "A bloco de rua is a roving street party" },
            { l1: "a folia", en: "the revelry / merrymaking", note: "" },
            { l1: "o trio elétrico", en: "the sound truck", note: "Salvador's mobile axé stage" },
            { l1: "a roda de samba", en: "the samba circle", note: "Informal jam where everyone gathers to play and sing" },
          ],
        },
        {
          type: "vocab",
          heading: "Futebol & the beach",
          items: [
            { l1: "o futebol", en: "football (soccer)", note: "" },
            { l1: "o time", en: "the team", note: "BR word; PT uses 'a equipa'" },
            { l1: "a torcida", en: "the fans / the crowd", note: "Collective for supporters" },
            { l1: "torcer (por)", en: "to root for / support", note: "Torço pelo Flamengo = I support Flamengo" },
            { l1: "o gol", en: "the goal", note: "BR spelling; PT writes 'o golo'" },
            { l1: "a Copa do Mundo", en: "the World Cup", note: "Brazil has won five" },
            { l1: "a partida / o jogo", en: "the match / the game", note: "" },
            { l1: "a praia", en: "the beach", note: "" },
            { l1: "a areia", en: "the sand", note: "" },
            { l1: "a água de coco", en: "coconut water", note: "The classic beach drink" },
          ],
        },
        {
          type: "tip",
          heading: "Fantasia is a false friend",
          body: "At Carnaval, <em>a fantasia</em> doesn't mean 'fantasy' — it means a <strong>costume</strong>. <em>Estou procurando uma fantasia para o Carnaval</em> = 'I'm looking for a costume for Carnival.' Likewise <em>o time</em> (team) is a Brazilian borrowing from English; in Portugal you'd say <em>a equipa</em>, and the goal is <em>o golo</em>, not <em>o gol</em>.",
          example: { l1: "Que fantasia você vai usar no bloco?", en: "What costume are you going to wear at the street party?" },
        },
        {
          type: "dialogue",
          heading: "Making plans for the weekend",
          setup: "Two friends in Rio decide what to do on Saturday.",
          lines: [
            { speaker: "Bruno", l1: "E aí, o que você vai fazer no sábado?", en: "Hey, what are you doing on Saturday?" },
            { speaker: "Marina", l1: "Tem um jogo do Flamengo à tarde. Vou assistir com a torcida no bar.", en: "There's a Flamengo match in the afternoon. I'm going to watch it with the fans at the bar." },
            { speaker: "Bruno", l1: "Boa! E de manhã? Bora pra praia?", en: "Nice! And in the morning? Shall we hit the beach?" },
            { speaker: "Marina", l1: "Bora! A gente toma uma água de coco em Ipanema.", en: "Let's go! We'll have a coconut water in Ipanema." },
            { speaker: "Bruno", l1: "Fechado. E à noite tem roda de samba na Lapa.", en: "Deal. And at night there's a samba circle in Lapa." },
            { speaker: "Marina", l1: "Perfeito. Dia cheio de música e futebol!", en: "Perfect. A day full of music and football!" },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the sentence",
          intro: "Tap the words into the correct order.",
          items: [
            { tokens: ["Eu", "torço", "pelo", "meu", "time"], en: "I root for my team." },
            { tokens: ["Vamos", "à", "praia", "no", "sábado"], en: "Let's go to the beach on Saturday." },
            { tokens: ["A", "escola", "de", "samba", "desfila", "hoje"], en: "The samba school parades today." },
            { tokens: ["Que", "fantasia", "linda", "você", "tem"], en: "What a beautiful costume you have." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Let's go to the beach and then watch the match.",
          reference: "Vamos à praia e depois assistir ao jogo.",
          hint: "'Let's go' = vamos. 'to watch the match' = assistir ao jogo (assistir takes 'a').",
        },
        {
          type: "pronounce",
          heading: "Say it aloud",
          items: [
            { l1: "o Carnaval", en: "Carnival", tip: "kar-nah-VOW (the final -al softens to '-ow')" },
            { l1: "o sambódromo", en: "the Sambadrome", tip: "sahm-BOH-droo-moo" },
            { l1: "a torcida", en: "the fans", tip: "tor-SEE-dah" },
            { l1: "a água de coco", en: "coconut water", tip: "AH-gwah jee KOH-koo" },
            { l1: "Gooool!", en: "Goal!", tip: "Drawn out as long as your lungs allow" },
          ],
        },
      ],
    },
    {
      slug: "music-culture-fado-festas",
      title: "Portugal: fado & saudade",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Crossing the Atlantic to Portugal",
          body: [
            "Brazil's music is mostly bright and outward — but Portugal's signature sound is the opposite. <strong>O fado</strong> is a melancholic song of longing, traditionally sung in the taverns of Lisbon's Alfama and Mouraria, or in Coimbra by university students. A solo voice, a Portuguese guitar (<em>a guitarra portuguesa</em>), and a classical guitar — and a room that falls silent to listen.",
            "At the heart of fado sits one untranslatable word: <strong>a saudade</strong> — a deep, bittersweet longing for someone or something absent, half sadness and half tenderness. Amália Rodrigues, the 'Rainha do Fado' (Queen of Fado), made it famous worldwide; in 2011 UNESCO recognised fado as Intangible Cultural Heritage.",
            "Portugal also knows how to party, though. In June come <strong>os Santos Populares</strong> — the Popular Saints festivals — when Lisbon (for Santo António) and Porto (for São João) fill with grilled sardines (<em>sardinhas</em>), paper decorations, street dancing, and the smell of <em>manjerico</em> (sweet basil) on every corner.",
          ],
          keyPoint:
            "PT signature = o fado (melancholic; guitarra portuguesa) built around a saudade (bittersweet longing). The big street party = os Santos Populares in June (sardines, dancing).",
        },
        {
          type: "vocab",
          heading: "Portuguese culture vocabulary",
          items: [
            { l1: "o fado", en: "fado", note: "Portugal's melancholic song tradition" },
            { l1: "a saudade", en: "saudade (bittersweet longing)", note: "Famously hard to translate" },
            { l1: "a guitarra portuguesa", en: "the Portuguese guitar", note: "Pear-shaped, twelve strings" },
            { l1: "o fadista / a fadista", en: "the fado singer (m / f)", note: "" },
            { l1: "a taberna", en: "the tavern", note: "Where fado is traditionally sung" },
            { l1: "os Santos Populares", en: "the Popular Saints (June festivals)", note: "Santo António, São João, São Pedro" },
            { l1: "a sardinha", en: "the sardine", note: "Grilled by the thousands in June" },
            { l1: "a festa", en: "the party / festival", note: "" },
            { l1: "o arraial", en: "the open-air street festival", note: "Neighbourhood party with food and dancing" },
            { l1: "a tradição", en: "the tradition", note: "" },
          ],
        },
        {
          type: "tip",
          heading: "Saudade: one word, two cultures",
          body: "<em>Saudade</em> belongs to the whole Portuguese-speaking world, but it's most identified with <strong>Portugal and the fado</strong> — the ache of distance, of emigration, of love lost to the sea. In <strong>Brazil</strong> the same word lives on, but lighter and more everyday: <em>que saudade!</em> simply means 'I miss it/you so much!' — said about a friend, a city, even a favourite dish. Same word, melancholic in a Lisbon taberna, warmly nostalgic on a Rio phone call.",
          example: { l1: "Que saudade de você!", en: "I miss you so much!" },
        },
        {
          type: "dialogue",
          heading: "A first fado night in Lisbon",
          setup: "A traveller asks a local about going to hear fado.",
          lines: [
            { speaker: "Turista", l1: "Onde posso ouvir fado de verdade?", en: "Where can I hear real fado?" },
            { speaker: "Local", l1: "Na Alfama. Há uma taberna pequena com fado vadio à noite.", en: "In Alfama. There's a small tavern with amateur fado at night." },
            { speaker: "Turista", l1: "E é preciso ficar em silêncio?", en: "And do I have to stay silent?" },
            { speaker: "Local", l1: "Sim, quando o fadista canta, todos se calam. É respeito.", en: "Yes, when the fado singer sings, everyone goes quiet. It's respect." },
            { speaker: "Turista", l1: "Que bonito. Dizem que o fado é cheio de saudade.", en: "How beautiful. They say fado is full of saudade." },
            { speaker: "Local", l1: "É a alma do fado. Vai sentir, mesmo sem perceber a letra.", en: "It's the soul of fado. You'll feel it, even without understanding the lyrics." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Culture check",
          questions: [
            {
              q: "Fado is the signature music of…",
              options: ["Brazil", "Portugal", "Angola", "Cape Verde"],
              correct: 1,
              fb: "Fado is Portugal's melancholic song tradition, especially Lisbon and Coimbra.",
            },
            {
              q: "'Saudade' best translates as…",
              options: ["happiness", "anger", "bittersweet longing", "boredom"],
              correct: 2,
              fb: "Saudade is that deep, bittersweet longing for someone or something absent.",
            },
            {
              q: "Os Santos Populares happen in…",
              options: ["December", "June", "the week before Lent", "September"],
              correct: 1,
              fb: "The Popular Saints festivals fill Portuguese streets in June, with grilled sardines and dancing.",
            },
            {
              q: "Which instrument is central to fado?",
              options: ["o pandeiro", "o cavaquinho", "a guitarra portuguesa", "o trio elétrico"],
              correct: 2,
              fb: "The pear-shaped guitarra portuguesa is fado's signature instrument.",
            },
            {
              q: "In Brazil, 'Que saudade!' usually means…",
              options: ["What a party!", "I miss it/you so much!", "How boring!", "What a goal!"],
              correct: 1,
              fb: "In everyday Brazilian use, 'que saudade!' is a warm 'I miss it/you so much!'.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Fill the cultural word",
          intro: "Choose the word that fits.",
          items: [
            {
              template: "O ___ é cantado nas tabernas de Lisboa.",
              answer: "fado",
              en: "Fado is sung in the taverns of Lisbon.",
              options: ["fado", "samba", "forró", "axé"],
            },
            {
              template: "Sinto muita ___ da minha cidade.",
              answer: "saudade",
              en: "I feel a lot of longing for my city.",
              options: ["saudade", "torcida", "fantasia", "areia"],
            },
            {
              template: "Em junho, comemos ___ nos Santos Populares.",
              answer: "sardinhas",
              en: "In June, we eat sardines at the Popular Saints festivals.",
              options: ["sardinhas", "pandeiros", "fantasias", "violões"],
            },
            {
              template: "A ___ portuguesa tem doze cordas.",
              answer: "guitarra",
              en: "The Portuguese guitar has twelve strings.",
              options: ["guitarra", "bateria", "torcida", "praia"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I really miss Lisbon. The fado is beautiful.",
          reference: "Que saudade de Lisboa. O fado é lindo.",
          hint: "Use 'que saudade de…' for 'I really miss…'. 'beautiful' = lindo (agrees with o fado, m sg).",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "What does 'MPB' stand for?",
        options: ["Música Pop Brasil", "Música Popular Brasileira", "Movimento Popular do Brasil", "Música Por Bairro"],
        correct: 1,
      },
      {
        q: "Bossa nova is most associated with…",
        options: ["the Northeast", "1960s Rio de Janeiro", "Lisbon's Alfama", "Salvador's Carnaval"],
        correct: 1,
      },
      {
        q: "At Carnaval, 'a fantasia' means…",
        options: ["a fantasy", "a costume", "a parade float", "a drum"],
        correct: 1,
      },
      {
        q: "Rio's samba schools parade in the…",
        options: ["taberna", "sambódromo", "arraial", "trio elétrico"],
        correct: 1,
      },
      {
        q: "'Torcer pelo meu time' means…",
        options: ["to play for my team", "to root for my team", "to coach my team", "to leave my team"],
        correct: 1,
      },
      {
        q: "How many World Cups has Brazil won?",
        options: ["three", "four", "five", "six"],
        correct: 2,
      },
      {
        q: "Fado is the signature music of…",
        options: ["Brazil", "Portugal", "Cape Verde", "Mozambique"],
        correct: 1,
      },
      {
        q: "'Saudade' best translates as…",
        options: ["joy", "bittersweet longing", "anger", "tiredness"],
        correct: 1,
      },
      {
        q: "Os Santos Populares (sardines, street dancing) take place in…",
        options: ["June", "December", "the week before Lent", "March"],
        correct: 0,
      },
      {
        q: "Translate: 'I love Brazilian music.'",
        options: [
          "Eu adoro música brasileiro.",
          "Eu adoro música brasileira.",
          "Eu adora música brasileira.",
          "Eu adoro brasileira música.",
        ],
        correct: 1,
      },
    ],
  },
};
