import type { Unit } from "../../types";

export const UNIT_HELP: Unit = {
  slug: "help",
  stage: 3,
  order: 13,
  icon: "🆘",
  title: "Emergencies & help",
  tagline: "Mi sono perso, può aiutarmi, sono allergico — the phrases you hope you won't need, but should know cold.",
  badge: "tourist",
  lessons: [
    {
      slug: "help-phrases",
      title: "The 10 emergency phrases",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Memorize these like you memorize 911",
          body: [
            "<strong>112</strong> is the universal Italian emergency number — police, ambulance, fire, all routed.",
            "<strong>Mi aiuti!</strong> = Help me! (a single-word emergency). Soften with <strong>Mi può aiutare?</strong> = Can you help me?",
            "<strong>Chiami la polizia / un'ambulanza!</strong> = Call the police / an ambulance! (formal command).",
            "<strong>Mi sono perso / persa</strong> = I'm lost (m / f).",
            "<strong>Sto male</strong> = I feel sick. <strong>Mi fa male qui</strong> = It hurts here (point).",
          ],
          keyPoint:
            "112 = emergency line. Mi aiuti / mi può aiutare. Sto male. Chiami la polizia / un'ambulanza.",
        },
        {
          type: "vocab",
          heading: "Emergency essentials",
          items: [
            { l1: "aiuto!", en: "help!" },
            { l1: "mi aiuti!", en: "help me! (formal command)" },
            { l1: "mi può aiutare?", en: "can you help me? (polite)" },
            { l1: "chiami la polizia", en: "call the police" },
            { l1: "chiami un'ambulanza", en: "call an ambulance" },
            { l1: "ho bisogno di un dottore", en: "I need a doctor" },
            { l1: "mi sono perso / persa", en: "I'm lost (m / f)" },
            { l1: "sto male", en: "I feel ill" },
            { l1: "mi fa male…", en: "it hurts… (then point or name body part)" },
            { l1: "ho perso il portafoglio / il passaporto", en: "I lost my wallet / passport" },
            { l1: "mi hanno rubato…", en: "they stole my… (someone stole)" },
            { l1: "è un'emergenza", en: "it's an emergency" },
          ],
        },
        {
          type: "tip",
          heading: "The 'pronto soccorso' (ER) is free for tourists",
          body: "Italy's public emergency rooms (<em>pronto soccorso</em>) will treat you regardless of insurance. You may pay a modest <em>ticket sanitario</em> (~€25-50) for non-urgent visits, but life-threatening cases are free. Bring your passport. The doctors often speak some English at major hospitals (Policlinico Umberto I, Gemelli).",
          example: { l1: "Dov'è il pronto soccorso più vicino?", en: "Where's the nearest emergency room?" },
        },
        {
          type: "multipleChoice",
          heading: "Pick the right phrase",
          questions: [
            {
              q: "Italy's universal emergency number is…",
              options: ["911", "118", "112", "100"],
              correct: 2,
            },
            {
              q: "'Call an ambulance!' (formal) =",
              options: [
                "Chiamare l'ambulanza!",
                "Chiama un'ambulanza!",
                "Chiami un'ambulanza!",
                "Voglio un'ambulanza.",
              ],
              correct: 2,
              fb: "Chiami = formal command of chiamare.",
            },
            {
              q: "'I lost my passport' =",
              options: [
                "Sono perso il passaporto.",
                "Ho perduto il passaporto.",
                "Ho perso il passaporto.",
                "Mi perde il passaporto.",
              ],
              correct: 2,
            },
            {
              q: "'It hurts here' =",
              options: [
                "Fa male qui.",
                "Mi fa male qui.",
                "Mi sono male qui.",
                "Qui è male.",
              ],
              correct: 1,
            },
            {
              q: "'It's an emergency' =",
              options: [
                "È un'emergenza.",
                "Ho un'emergenza.",
                "È urgente!",
                "All three work.",
              ],
              correct: 3,
            },
          ],
        },
      ],
    },
    {
      slug: "help-medical",
      title: "At the pharmacy & doctor",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Pharmacies in Italy are powerful first stops",
          body: [
            "Italian pharmacists (<em>farmacisti</em>) are trained to diagnose minor issues and recommend OTC medicines. For headaches, stomach upset, mild infections, allergies — go to the <em>farmacia</em> first.",
            "Identifiable by a green cross sign. Most are open 8:30am-7:30pm, closed at lunch (1-4pm), but in any neighborhood at least one stays open at night — look for the <em>farmacia di turno</em> notice.",
            "<em>«Mi serve qualcosa per…»</em> = I need something for… is the most useful opening sentence.",
          ],
          keyPoint:
            "Farmacia (green cross) = your first medical stop. Pharmacists can prescribe basic OTC. Open 8:30-1, 4-7:30; a 'farmacia di turno' is the on-duty night option.",
        },
        {
          type: "vocab",
          heading: "Pharmacy & body",
          items: [
            { l1: "la farmacia", en: "the pharmacy" },
            { l1: "il farmacista", en: "the pharmacist" },
            { l1: "la ricetta (medica)", en: "the prescription" },
            { l1: "le compresse / le pastiglie", en: "the tablets / pills" },
            { l1: "lo sciroppo", en: "the syrup" },
            { l1: "la pomata", en: "the cream / ointment" },
            { l1: "il cerotto", en: "the band-aid" },
            { l1: "il mal di testa", en: "headache" },
            { l1: "il mal di stomaco", en: "stomachache" },
            { l1: "il mal di gola", en: "sore throat" },
            { l1: "la febbre", en: "fever" },
            { l1: "la tosse", en: "cough" },
            { l1: "il raffreddore", en: "the cold (illness)" },
            { l1: "l'allergia", en: "the allergy" },
            { l1: "sono allergico/a a…", en: "I'm allergic to…" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the pharmacy",
          setup: "You walk in with a bad headache.",
          lines: [
            { speaker: "Farmacista", l1: "Buongiorno, mi dica.", en: "Good morning, tell me." },
            { speaker: "You", l1: "Buongiorno. Ho un forte mal di testa da stamattina. Mi serve qualcosa.", en: "Good morning. I have a strong headache since this morning. I need something." },
            { speaker: "Farmacista", l1: "È allergico a qualche farmaco?", en: "Are you allergic to any medicine?" },
            { speaker: "You", l1: "No, niente.", en: "No, nothing." },
            { speaker: "Farmacista", l1: "Allora Le do dell'ibuprofene. Una compressa ogni otto ore, con un po' d'acqua. Beva molto e cerchi di riposare.", en: "Then I'll give you some ibuprofen. One tablet every eight hours, with a bit of water. Drink a lot and try to rest." },
            { speaker: "You", l1: "Perfetto, grazie. Quanto costa?", en: "Perfect, thank you. How much does it cost?" },
            { speaker: "Farmacista", l1: "Quattro euro e cinquanta.", en: "Four euros fifty." },
          ],
        },
        {
          type: "vocab",
          heading: "Body parts",
          items: [
            { l1: "la testa", en: "head" },
            { l1: "lo stomaco / la pancia", en: "stomach / belly" },
            { l1: "la schiena", en: "back" },
            { l1: "il braccio / le braccia", en: "arm / arms" },
            { l1: "la gamba / le gambe", en: "leg / legs" },
            { l1: "il piede / i piedi", en: "foot / feet" },
            { l1: "la mano / le mani", en: "hand / hands" },
            { l1: "il dente / i denti", en: "tooth / teeth" },
            { l1: "l'orecchio / le orecchie", en: "ear / ears" },
            { l1: "la gola", en: "throat" },
            { l1: "il cuore", en: "heart" },
            { l1: "la pelle", en: "skin" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Symptoms",
          items: [
            {
              template: "Mi serve qualcosa per il ___ di testa.",
              answer: "mal",
              en: "I need something for a headache.",
              options: ["mal", "male", "dolore", "problema"],
            },
            {
              template: "Ho la ___ a 38 gradi.",
              answer: "febbre",
              en: "I have a fever of 38 degrees.",
              options: ["tosse", "febbre", "gola", "testa"],
            },
            {
              template: "Sono ___ alle arachidi.",
              answer: "allergico",
              en: "I'm allergic to peanuts. (male speaker)",
              options: ["allergico", "allergica", "stanco", "vicino"],
            },
            {
              template: "Mi fa molto male la ___ .",
              answer: "schiena",
              en: "My back really hurts.",
              options: ["schiena", "tasca", "carta", "fila"],
            },
            {
              template: "Ho ___ e tosse.",
              answer: "raffreddore",
              en: "I have a cold and a cough.",
              options: ["raffreddore", "febbre", "stomaco", "testa"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'm allergic to penicillin. Is there an alternative?",
          reference: "Sono allergico/a alla penicillina. C'è un'alternativa?",
          hint: "'Allergico' (m) or 'allergica' (f). 'C'è' = there is.",
        },
      ],
    },
    {
      slug: "help-theft-lost",
      title: "Theft, lost items, the police",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "If something gets stolen",
          body: [
            "Rome's main scam zones: bus 64 (Termini → Vaticano), the metro at rush hour, crowded steps near attractions. Pickpockets work in pairs — one distracts, one lifts.",
            "If it happens: <em>«Mi hanno rubato il portafoglio.»</em> = They stole my wallet. Find the nearest <em>commissariato</em> (police station) within 24h. Filing a <strong>denuncia</strong> (report) is required for insurance.",
            "Lost (not stolen) items: <em>«Ho perso…»</em> Then go to the relevant <em>ufficio oggetti smarriti</em> (lost-property office) — Termini has one, ATAC (transit) has one.",
          ],
          keyPoint:
            "Stolen → mi hanno rubato → fare denuncia at commissariato within 24h. Lost → ho perso → ufficio oggetti smarriti.",
        },
        {
          type: "vocab",
          heading: "When things go wrong",
          items: [
            { l1: "il portafoglio", en: "the wallet" },
            { l1: "il borsello / la borsa", en: "the (man's) bag / woman's purse" },
            { l1: "lo zaino", en: "the backpack" },
            { l1: "il passaporto", en: "the passport" },
            { l1: "il telefono", en: "the phone" },
            { l1: "le chiavi", en: "the keys" },
            { l1: "rubare", en: "to steal" },
            { l1: "il ladro / la ladra", en: "the thief (m / f)" },
            { l1: "il borseggiatore", en: "pickpocket" },
            { l1: "la denuncia", en: "the police report" },
            { l1: "il commissariato / la questura", en: "police station / police HQ" },
            { l1: "l'ambasciata", en: "the embassy" },
            { l1: "il consolato", en: "the consulate" },
            { l1: "l'ufficio oggetti smarriti", en: "lost-property office" },
          ],
        },
        {
          type: "dialogue",
          heading: "Filing a police report",
          setup: "You arrive at the commissariato shaking.",
          lines: [
            { speaker: "Agente", l1: "Buongiorno. Mi dica.", en: "Good morning. Tell me." },
            { speaker: "You", l1: "Buongiorno. Mi hanno rubato il portafoglio sull'autobus. Vorrei fare una denuncia.", en: "Good morning. They stole my wallet on the bus. I'd like to file a report." },
            { speaker: "Agente", l1: "Mi dispiace. Quando è successo?", en: "I'm sorry. When did it happen?" },
            { speaker: "You", l1: "Circa un'ora fa, sull'autobus sessantaquattro.", en: "About an hour ago, on bus 64." },
            { speaker: "Agente", l1: "Cosa c'era nel portafoglio?", en: "What was in the wallet?" },
            { speaker: "You", l1: "Una cinquantina di euro in contanti, due carte di credito, e la patente.", en: "About fifty euros in cash, two credit cards, and the driver's license." },
            { speaker: "Agente", l1: "Ha già bloccato le carte?", en: "Have you already blocked the cards?" },
            { speaker: "You", l1: "Sì, ho chiamato la banca subito.", en: "Yes, I called the bank right away." },
            { speaker: "Agente", l1: "Bene. Le faccio compilare il modulo. Avrà una copia della denuncia entro mezz'ora.", en: "Good. I'll have you fill out the form. You'll have a copy of the report within half an hour." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Vocabulary in context",
          items: [
            {
              template: "Mi hanno ___ il telefono in metro.",
              answer: "rubato",
              en: "They stole my phone on the metro.",
              options: ["preso", "rubato", "perso", "smarrito"],
            },
            {
              template: "Vorrei fare una ___ alla polizia.",
              answer: "denuncia",
              en: "I'd like to file a police report.",
              options: ["domanda", "denuncia", "richiesta", "lettera"],
            },
            {
              template: "Ho perso le ___ della camera.",
              answer: "chiavi",
              en: "I lost the room keys.",
              options: ["carte", "chiavi", "porte", "scarpe"],
            },
            {
              template: "Devo andare all'___ americana.",
              answer: "ambasciata",
              en: "I have to go to the American embassy.",
              options: ["aeroporto", "ambasciata", "agenzia", "albergo"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the emergency sentence",
          items: [
            { tokens: ["Mi", "hanno", "rubato", "il", "portafoglio", "."], en: "They stole my wallet." },
            { tokens: ["Vorrei", "fare", "una", "denuncia", ",", "per", "favore", "."], en: "I'd like to file a police report, please." },
            { tokens: ["Dov'è", "il", "commissariato", "più", "vicino", "?"], en: "Where is the nearest police station?" },
            { tokens: ["Ho", "bisogno", "di", "chiamare", "l'ambasciata", "."], en: "I need to call the embassy." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I lost my passport. Where is the American embassy?",
          reference: "Ho perso il passaporto. Dov'è l'ambasciata americana?",
          hint: "'Ho perso' = I lost. 'L'ambasciata' takes 'americana' (feminine).",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "Italy's universal emergency number =",
        options: ["911", "112", "118", "100"],
        correct: 1,
      },
      {
        q: "'Help me!' (formal command) =",
        options: ["Aiutami!", "Mi aiuti!", "Mi aiuto!", "Aiuta!"],
        correct: 1,
      },
      {
        q: "'I'm allergic to peanuts.' (male) =",
        options: [
          "Sono allergica alle arachidi.",
          "Ho allergia per arachidi.",
          "Sono allergico alle arachidi.",
          "Le arachidi mi danno allergia.",
        ],
        correct: 2,
      },
      {
        q: "'They stole my wallet.' =",
        options: [
          "Ho rubato il portafoglio.",
          "Mi hanno rubato il portafoglio.",
          "Hanno preso il mio portafoglio.",
          "Il portafoglio è rubato.",
        ],
        correct: 1,
      },
      {
        q: "What's a 'farmacia di turno'?",
        options: [
          "an Italian-only pharmacy",
          "the pharmacy on duty (open at night/weekends)",
          "an expensive private pharmacy",
          "a pharmacy that gives discounts",
        ],
        correct: 1,
      },
      {
        q: "'I have a headache' =",
        options: [
          "Ho la testa.",
          "Mi serve testa.",
          "Ho mal di testa.",
          "Sono male alla testa.",
        ],
        correct: 2,
      },
      {
        q: "A 'denuncia' is…",
        options: [
          "a complaint at a restaurant",
          "an official police report",
          "a visa application",
          "a hotel registration",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'I need a doctor.'",
        options: [
          "Voglio un dottore.",
          "Mi serve un dottore.",
          "Ho bisogno di un dottore.",
          "Both B and C work — both are correct.",
        ],
        correct: 3,
      },
      {
        q: "'I'm lost' (female speaker) =",
        options: [
          "Mi sono perso.",
          "Mi sono persa.",
          "Sono persa.",
          "Both B and C work.",
        ],
        correct: 3,
      },
      {
        q: "'Lost-property office' =",
        options: [
          "il commissariato",
          "l'ufficio oggetti smarriti",
          "la denuncia",
          "il consolato",
        ],
        correct: 1,
      },
    ],
  },
};
