import type { Unit } from "../../types";

export const UNIT_NARRATE_TRIP: Unit = {
  slug: "narrate-trip",
  stage: 5,
  order: 24,
  icon: "📖",
  title: "Narrating a trip",
  tagline: "Combining all the tenses to actually tell a story. The capstone of Stage 5.",
  badge: "core",
  lessons: [
    {
      slug: "narrate-structure",
      title: "How a trip story is structured",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Italian storytelling has a recognizable shape",
          body: [
            "<strong>1. Set the scene</strong> with imperfetto: <em>Era estate. Faceva caldissimo. Avevo solo uno zaino.</em>",
            "<strong>2. Drop the events</strong> with passato prossimo: <em>Sono partito da Boston. Ho preso il volo per Roma.</em>",
            "<strong>3. Add background details</strong> with imperfetto: <em>Mentre l'aereo decollava, ho pensato…</em>",
            "<strong>4. The conclusion / lesson</strong> often shifts to the present: <em>Adesso, ogni volta che penso a quel viaggio, sorrido.</em>",
            "Connector words tie it together: <em>poi, dopo, dopo di che, alla fine, all'improvviso, mentre, quando, mentre che…</em>",
          ],
          keyPoint:
            "Scene (imperfetto) → events (passato prossimo) → background of events (imperfetto) → conclusion (present). Connect with poi / dopo / mentre / quando.",
        },
        {
          type: "vocab",
          heading: "Storytelling connectors",
          items: [
            { l1: "all'inizio", en: "at the beginning" },
            { l1: "poi / e poi", en: "then / and then" },
            { l1: "dopo", en: "after / afterward" },
            { l1: "dopo di che", en: "after that" },
            { l1: "improvvisamente / all'improvviso", en: "suddenly" },
            { l1: "mentre", en: "while" },
            { l1: "quando", en: "when" },
            { l1: "subito", en: "right away" },
            { l1: "infine / alla fine", en: "finally / in the end" },
            { l1: "per fortuna", en: "luckily" },
            { l1: "per sfortuna", en: "unluckily" },
            { l1: "incredibilmente", en: "incredibly" },
            { l1: "che bello!", en: "how nice!" },
            { l1: "che peccato!", en: "what a pity!" },
          ],
        },
        {
          type: "tip",
          heading: "The 'paint and canvas' rule, restated",
          body: "Think of imperfetto as the canvas — it paints the scene, gives the weather, describes how things felt. Think of passato prossimo as the paint splash — it drops specific events onto that canvas. A story without imperfetto reads as a list. A story without passato prossimo has no plot. You need both.",
        },
        {
          type: "dialogue",
          heading: "Telling your travel story",
          setup: "Your friend asks about your last trip.",
          lines: [
            { speaker: "Marco", l1: "Allora, com'è andato il viaggio in Sicilia?", en: "So, how was the trip to Sicily?" },
            { speaker: "You", l1: "Allora, era la mia prima volta in Sicilia. Faceva caldissimo, ma era bellissimo. Sono arrivato a Palermo lunedì mattina.", en: "So, it was my first time in Sicily. It was very hot, but it was beautiful. I arrived in Palermo Monday morning." },
            { speaker: "Marco", l1: "Dove sei stato?", en: "Where did you stay?" },
            { speaker: "You", l1: "Ho prenotato un piccolo b&b in centro. Mentre cercavo l'indirizzo, mi sono perso completamente. Per fortuna una signora anziana mi ha aiutato.", en: "I booked a small B&B in the center. While I was looking for the address, I got completely lost. Luckily an elderly lady helped me." },
            { speaker: "Marco", l1: "Cosa hai mangiato?", en: "What did you eat?" },
            { speaker: "You", l1: "Di tutto! Arancini, pasta alla Norma, cannoli. Una sera ho cenato in una trattoria piccolissima — c'erano solo tre tavoli, e il pesce era freschissimo. Mi è piaciuto tantissimo.", en: "Everything! Arancini, pasta alla Norma, cannoli. One evening I dined at a tiny trattoria — there were only three tables, and the fish was very fresh. I loved it a lot." },
            { speaker: "Marco", l1: "Tornerai?", en: "Will you go back?" },
            { speaker: "You", l1: "Sicuramente. L'anno prossimo voglio vedere anche Catania e Siracusa.", en: "Definitely. Next year I want to see Catania and Siracusa too." },
          ],
        },
      ],
    },
    {
      slug: "narrate-mix-tenses",
      title: "Mixing tenses fluidly",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The three-tense braid",
          body: [
            "A polished story uses all three tenses naturally:",
            "<em><strong>Era</strong> una bella mattina di settembre. (imperfetto — scene)</em>",
            "<em><strong>Mi sono svegliato</strong> alle sei e <strong>ho preso</strong> un caffè. (passato prossimo — events)</em>",
            "<em>Mentre <strong>bevevo</strong> il caffè, <strong>ho letto</strong> la mail di Marco. (imperfetto background + passato prossimo event)</em>",
            "<em>Mi <strong>diceva</strong> che <strong>sarebbe arrivato</strong> a Roma il giorno dopo. (imperfetto + future-in-past)</em>",
            "<em>Adesso, ogni volta che penso a quel momento, sorrido. (present — conclusion)</em>",
          ],
          keyPoint:
            "Imperfetto = states, ongoing background, weather, age. Passato prossimo = events that move the story. Present = wraps it up.",
        },
        {
          type: "fillBlank",
          heading: "Choose the right tense",
          items: [
            {
              template: "Ieri ___ (essere) una bellissima giornata.",
              answer: "era",
              en: "Yesterday was a beautiful day. (description → imperfetto)",
              options: ["era", "è stato/a", "è", "sarà"],
            },
            {
              template: "Mentre ___ (camminare) per il centro, ___ (incontrare) un vecchio amico.",
              answer: "camminavo / ho incontrato",
              en: "While I was walking through the center, I met an old friend.",
              options: [
                "camminavo / ho incontrato",
                "ho camminato / incontravo",
                "cammino / incontro",
                "camminavo / incontravo",
              ],
            },
            {
              template: "Quando ero piccolo, ___ (andare) al parco ogni domenica.",
              answer: "andavo",
              en: "When I was little, I used to go to the park every Sunday.",
              options: ["andavo", "sono andato", "vado", "andrò"],
            },
            {
              template: "Marco ___ (arrivare) ieri sera alle dieci.",
              answer: "è arrivato",
              en: "Marco arrived yesterday evening at ten. (event → pp)",
              options: ["arrivava", "è arrivato", "arriva", "arriverà"],
            },
            {
              template: "Domani (io) ___ (vedere) il Colosseo.",
              answer: "vedrò",
              en: "Tomorrow I'll see the Colosseum.",
              options: ["vedevo", "ho visto", "vedo", "vedrò"],
            },
            {
              template: "(Io) ___ (essere) molto stanco quando ___ (arrivare).",
              answer: "ero / sono arrivato",
              en: "I was very tired when I arrived. (state + event)",
              options: [
                "sono stato / arrivavo",
                "ero / sono arrivato",
                "sono / sono arrivato",
                "ero / arrivavo",
              ],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the narrative",
          items: [
            { tokens: ["Era", "una", "giornata", "fredda", "di", "gennaio"], en: "It was a cold January day." },
            { tokens: ["Sono", "uscita", "presto", "per", "andare", "al", "lavoro"], en: "I left early to go to work." },
            { tokens: ["Mentre", "aspettavo", "l'autobus", ",", "ha", "cominciato", "a", "nevicare"], en: "While I was waiting for the bus, it started to snow." },
            { tokens: ["Alla", "fine", "sono", "arrivata", "in", "ufficio", "tutta", "bagnata"], en: "In the end I arrived at the office all wet." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "It was raining. I was eating dinner when the phone rang. It was my mother.",
          reference: "Pioveva. Stavo cenando quando ha squillato il telefono. Era mia madre.",
          hint: "Three imperfetti (was raining, was eating, was — state) + one event (rang).",
        },
        {
          type: "tip",
          heading: "Stare + gerundio = 'was/is -ing'",
          body: "If you want to emphasize an action in progress, Italians use <em>stare + gerundio</em>: <em>Stavo cenando</em> = I was eating dinner. (Vs <em>cenavo</em> which is also fine but less emphatic.) Gerund: <em>-ando</em> for -are verbs, <em>-endo</em> for -ere and -ire. <em>parlare → parlando, leggere → leggendo, dormire → dormendo</em>.",
        },
      ],
    },
    {
      slug: "narrate-write-your-own",
      title: "Write your own trip story",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "Time to put it all together",
          body: [
            "This lesson is mostly translation practice — you'll build up a short trip story piece by piece using all the tenses you've learned.",
            "Story setup: \"A weekend trip to Florence.\" You'll translate sentences that, together, form a complete narrative.",
            "Use the Italian model on each one — these are graded by Claude, so you'll get feedback if you go off-track.",
          ],
        },
        {
          type: "translate",
          heading: "Scene-setting (use imperfetto)",
          direction: "en-to-l1",
          prompt: "It was a Saturday morning in June. The weather was beautiful and I was happy.",
          reference: "Era un sabato mattina di giugno. Faceva bel tempo ed ero felice.",
          hint: "All description = imperfetto. 'Faceva bel tempo' = weather was nice. 'Ero felice' = I was happy.",
        },
        {
          type: "translate",
          heading: "First event (passato prossimo)",
          direction: "en-to-l1",
          prompt: "I took the train from Roma Termini at seven. The trip lasted an hour and a half.",
          reference: "Ho preso il treno da Roma Termini alle sette. Il viaggio è durato un'ora e mezza.",
          hint: "Two completed events: ho preso (avere) + è durato (essere — durare uses essere).",
        },
        {
          type: "translate",
          heading: "On arrival (mix of tenses)",
          direction: "en-to-l1",
          prompt: "When I arrived in Florence, it was hot. I went out of the station and walked to the historic center.",
          reference: "Quando sono arrivato/a a Firenze, faceva caldo. Sono uscito/a dalla stazione e ho camminato fino al centro storico.",
          hint: "Arrived (event) + was hot (background) + went out (event) + walked (event).",
        },
        {
          type: "translate",
          heading: "Background detail (imperfetto)",
          direction: "en-to-l1",
          prompt: "While I was walking, I was looking at the buildings and listening to music.",
          reference: "Mentre camminavo, guardavo gli edifici e ascoltavo la musica.",
          hint: "Three simultaneous ongoing actions = three imperfetti.",
        },
        {
          type: "translate",
          heading: "Sudden event (passato prossimo)",
          direction: "en-to-l1",
          prompt: "Suddenly I saw a small restaurant with a hand-written menu. I decided to enter.",
          reference: "All'improvviso ho visto un piccolo ristorante con un menù scritto a mano. Ho deciso di entrare.",
          hint: "Two events: ho visto + ho deciso. 'A mano' = by hand.",
        },
        {
          type: "translate",
          heading: "The meal (mix)",
          direction: "en-to-l1",
          prompt: "I ate a bistecca alla fiorentina with a glass of red wine. It was the best meal of my trip.",
          reference: "Ho mangiato una bistecca alla fiorentina con un bicchiere di vino rosso. È stato il miglior pasto del viaggio.",
          hint: "Mangiato (event). 'È stato' = it was (one specific meal, completed = passato prossimo, NOT imperfetto here).",
        },
        {
          type: "translate",
          heading: "Conclusion (present + future)",
          direction: "en-to-l1",
          prompt: "I love Florence. Next month I'll definitely go back.",
          reference: "Adoro Firenze. Il mese prossimo ci tornerò sicuramente.",
          hint: "'Ci' = there. 'Tornerò' = future of tornare. 'Sicuramente' = definitely.",
        },
        {
          type: "tip",
          heading: "Congratulations — you can narrate now",
          body: "You just told an 8-sentence story using three tenses, agreement, and connector words. That's real B1-level narrative skill. From here, you can talk about any past trip, weekend, or memory in conversational Italian. The next stages add nuance (Lei forms, conditional, subjunctive) — but the heavy structural lifting is done.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'It was raining' (background) =",
        options: ["È piovuto", "Pioveva", "Piove", "Pioverà"],
        correct: 1,
      },
      {
        q: "'I went home' (event) =",
        options: ["Andavo a casa", "Sono andato/a a casa", "Vado a casa", "Andrò a casa"],
        correct: 1,
      },
      {
        q: "'While I was eating, the phone rang' =",
        options: [
          "Mentre mangiavo, ha squillato il telefono.",
          "Mentre ho mangiato, squillava il telefono.",
          "Mentre mangiavo, squillava il telefono.",
          "Mentre ho mangiato, ha squillato il telefono.",
        ],
        correct: 0,
      },
      {
        q: "'Stavo cenando' means…",
        options: [
          "I dined",
          "I was dining (emphatic)",
          "I will dine",
          "I used to dine",
        ],
        correct: 1,
      },
      {
        q: "Gerundio of 'leggere' =",
        options: ["leggando", "leggendo", "leggito", "leggevo"],
        correct: 1,
      },
      {
        q: "'When I was little, I lived in Boston' =",
        options: [
          "Quando ero piccolo, ho abitato a Boston.",
          "Quando ero piccolo, abitavo a Boston.",
          "Quando sono stato piccolo, abitavo a Boston.",
          "Quando ero piccolo, abito a Boston.",
        ],
        correct: 1,
      },
      {
        q: "'Suddenly' =",
        options: ["mentre", "improvvisamente", "subito", "spesso"],
        correct: 1,
      },
      {
        q: "Storyteller's connector for 'and then' =",
        options: ["mentre", "e poi", "siccome", "infine"],
        correct: 1,
      },
      {
        q: "'I was tired when I arrived' =",
        options: [
          "Sono stato stanco quando arrivavo.",
          "Ero stanco quando sono arrivato.",
          "Sono stato stanco quando sono arrivato.",
          "Ero stanco quando arrivavo.",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'It was a beautiful day. I went out at 10 and walked for two hours.'",
        options: [
          "Era una bella giornata. Sono uscito alle dieci e ho camminato per due ore.",
          "È stata una bella giornata. Uscivo alle dieci e camminavo per due ore.",
          "Era una bella giornata. Uscivo alle dieci e camminavo per due ore.",
          "È stata una bella giornata. Sono uscito alle dieci e ho camminato per due ore.",
        ],
        correct: 0,
      },
    ],
  },
};
