import type { Unit } from "../../types";

export const UNIT_HOTEL: Unit = {
  slug: "hotel",
  stage: 3,
  order: 12,
  icon: "🏨",
  title: "Airport & hotel",
  tagline: "Check-in, room vocab, asking for things, polite complaints — everything you say between landing and unpacking.",
  badge: "tourist",
  lessons: [
    {
      slug: "hotel-arrival",
      title: "At the airport — the first hour",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "What you'll hear and need to say at Fiumicino",
          body: [
            "<strong>Passport control</strong>: <em>«Il motivo del Suo viaggio?»</em> = What's the purpose of your trip? Reply with <em>«Vacanza / lavoro / visita ai parenti»</em>.",
            "<strong>Baggage claim</strong>: signs say <em>RITIRO BAGAGLI</em>. Belts are numbered: <em>nastro 4</em> = belt 4.",
            "<strong>Lost luggage</strong>: <em>«Mi manca la valigia. Dove posso fare il reclamo?»</em> = My suitcase is missing. Where can I file a complaint?",
            "<strong>SIM card / data</strong>: airports have TIM, Vodafone, WindTre kiosks. A tourist SIM is ~€20 for 50GB/30 days.",
          ],
          keyPoint:
            "Passport check is fast for US/UK. Validate Leonardo Express before boarding. Lost-luggage form = 'modulo PIR' at the airline desk.",
        },
        {
          type: "vocab",
          heading: "Airport essentials",
          items: [
            { l1: "il volo", en: "the flight" },
            { l1: "il controllo passaporti", en: "passport control" },
            { l1: "il ritiro bagagli", en: "baggage claim" },
            { l1: "il nastro", en: "the belt (baggage)" },
            { l1: "la dogana", en: "customs" },
            { l1: "il carrello", en: "the cart / trolley" },
            { l1: "lo sportello", en: "the (service) counter / desk" },
            { l1: "il bagaglio a mano", en: "carry-on baggage" },
            { l1: "il bagaglio da stiva", en: "checked baggage" },
            { l1: "la carta d'imbarco", en: "the boarding pass" },
            { l1: "in ritardo / in orario", en: "delayed / on time" },
            { l1: "smarrito", en: "lost (luggage, items)" },
          ],
        },
        {
          type: "dialogue",
          heading: "Passport control",
          setup: "You hand the officer your passport.",
          lines: [
            { speaker: "Ufficiale", l1: "Buongiorno. Il motivo del Suo viaggio?", en: "Good morning. What's the purpose of your trip?" },
            { speaker: "You", l1: "Vacanza. Visito Roma per dieci giorni.", en: "Vacation. I'm visiting Rome for ten days." },
            { speaker: "Ufficiale", l1: "Dove alloggia?", en: "Where are you staying?" },
            { speaker: "You", l1: "All'Hotel Stella di Monti, in Via dei Serpenti.", en: "At Hotel Stella di Monti, on Via dei Serpenti." },
            { speaker: "Ufficiale", l1: "Va bene. Buona permanenza.", en: "Okay. Have a good stay." },
            { speaker: "You", l1: "Grazie!", en: "Thank you!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Fill in the airport scene",
          items: [
            {
              template: "La mia valigia è ___ . Cosa devo fare?",
              answer: "smarrita",
              en: "My suitcase is lost. What should I do?",
              options: ["smarrita", "rotta", "vecchia", "leggera"],
            },
            {
              template: "Il mio volo è in ___ di tre ore.",
              answer: "ritardo",
              en: "My flight is delayed by three hours.",
              options: ["partenza", "arrivo", "ritardo", "orario"],
            },
            {
              template: "Il bagaglio arriva al ___ numero quattro.",
              answer: "nastro",
              en: "The luggage arrives at belt number four.",
              options: ["sportello", "binario", "nastro", "carrello"],
            },
            {
              template: "Mi serve la ___ d'imbarco.",
              answer: "carta",
              en: "I need the boarding pass.",
              options: ["carta", "carta di credito", "porta", "carta SIM"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Excuse me, where can I buy a SIM card?",
          reference: "Mi scusi, dove posso comprare una carta SIM?",
          hint: "Posso + infinitive = 'can I + verb'. SIM card = carta SIM.",
        },
      ],
    },
    {
      slug: "hotel-checkin",
      title: "Check-in",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The check-in script (you'll do this every trip)",
          body: [
            "<em>«Ho una prenotazione a nome [your name].»</em> = I have a reservation under [name].",
            "Italian hotels need your <strong>passport</strong>: <em>«Posso vedere il Suo documento?»</em> They'll keep it for 5-10 minutes to register you with the police (this is required by law — don't worry).",
            "Common questions back: <em>«Vuole la colazione inclusa?» «A che ora pensa di partire?» «Quante notti?»</em>",
            "Useful answers: <em>«Tutto incluso, grazie.» «Parto venerdì mattina.» «Quattro notti, fino a domenica.»</em>",
          ],
          keyPoint:
            "1) Give your name. 2) Hand over passport. 3) Sign the form. 4) Receive key. 5) Ask about breakfast and Wi-Fi.",
        },
        {
          type: "vocab",
          heading: "Hotel & room vocabulary",
          items: [
            { l1: "la reception", en: "reception desk" },
            { l1: "la prenotazione", en: "the reservation" },
            { l1: "la camera singola", en: "single room" },
            { l1: "la camera doppia", en: "double room (two single beds OR shared)" },
            { l1: "la camera matrimoniale", en: "double room with one big bed" },
            { l1: "la suite", en: "the suite" },
            { l1: "la colazione inclusa", en: "breakfast included" },
            { l1: "la chiave / la chiave magnetica", en: "key / keycard" },
            { l1: "l'ascensore", en: "the elevator" },
            { l1: "le scale", en: "the stairs" },
            { l1: "il piano", en: "the floor (1° piano = 2nd floor — Italian ground floor is 0!)" },
            { l1: "il Wi-Fi / la password", en: "Wi-Fi / password" },
            { l1: "il check-out", en: "checkout" },
            { l1: "l'aria condizionata", en: "air conditioning" },
            { l1: "il riscaldamento", en: "heating" },
          ],
        },
        {
          type: "dialogue",
          heading: "Full check-in",
          setup: "You arrive at the hotel just after lunch.",
          lines: [
            { speaker: "You", l1: "Buongiorno. Ho una prenotazione a nome Connolly.", en: "Good afternoon. I have a reservation under Connolly." },
            { speaker: "Receptionist", l1: "Un attimo… Sì, eccola. Quattro notti, camera matrimoniale. Posso vedere il documento, per favore?", en: "One moment… Yes, here it is. Four nights, double room (big bed). May I see your ID, please?" },
            { speaker: "You", l1: "Certo. Ecco il passaporto.", en: "Of course. Here's the passport." },
            { speaker: "Receptionist", l1: "Perfetto. La colazione è inclusa, dalle sette alle dieci, al piano terra. Wi-Fi gratuito, la password è scritta qui.", en: "Perfect. Breakfast is included, from seven to ten, on the ground floor. Free Wi-Fi, the password is written here." },
            { speaker: "You", l1: "Ottimo. A che ora è il check-out?", en: "Excellent. What time is check-out?" },
            { speaker: "Receptionist", l1: "Le undici. Se vuole partire più tardi, ce lo dica. Ecco la chiave — camera 302, terzo piano. L'ascensore è in fondo.", en: "Eleven. If you want to leave later, let us know. Here's the key — room 302, third floor. The elevator is at the end." },
            { speaker: "You", l1: "Grazie mille!", en: "Thank you very much!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Check-in fill-ins",
          items: [
            {
              template: "Ho una ___ a nome Smith.",
              answer: "prenotazione",
              en: "I have a reservation under Smith.",
              options: ["prenotazione", "camera", "porta", "richiesta"],
            },
            {
              template: "Vorrei una camera ___ con un letto grande.",
              answer: "matrimoniale",
              en: "I'd like a double room with one big bed.",
              options: ["singola", "doppia", "matrimoniale", "tripla"],
            },
            {
              template: "A che ora è il ___ ?",
              answer: "check-out",
              en: "What time is check-out?",
              options: ["check-out", "check-in", "colazione", "pranzo"],
            },
            {
              template: "Posso pagare in ___ ?",
              answer: "contanti",
              en: "Can I pay in cash?",
              options: ["contanti", "carta", "bonifico", "dollari"],
            },
            {
              template: "L'ascensore è in ___ al corridoio.",
              answer: "fondo",
              en: "The elevator is at the end of the hallway.",
              options: ["centro", "fondo", "angolo", "davanti"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the request",
          items: [
            { tokens: ["Vorrei", "una", "camera", "tranquilla", ",", "se", "possibile"], en: "I'd like a quiet room, if possible." },
            { tokens: ["Quanto", "costa", "la", "colazione", "?"], en: "How much does breakfast cost?" },
            { tokens: ["Mi", "può", "dare", "la", "password", "del", "Wi-Fi", "?"], en: "Can you give me the Wi-Fi password?" },
            { tokens: ["A", "che", "ora", "chiude", "la", "reception", "?"], en: "What time does the reception close?" },
          ],
        },
      ],
    },
    {
      slug: "hotel-complaints",
      title: "When something's wrong — polite complaints",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The cushioned-complaint formula",
          body: [
            "Italians soften complaints. The pattern: <em>«Scusi, ma…»</em> + the problem + <em>«…non funziona / non va bene»</em>.",
            "<em>«Scusi, ma l'aria condizionata non funziona.»</em> = Excuse me, but the air conditioning isn't working.",
            "Or even softer: <em>«Vorrei segnalare un piccolo problema…»</em> = I'd like to mention a small problem…",
            "Avoid <em>«Voglio…»</em> (\"I want…\") when complaining — use <em>«Vorrei…»</em> (\"I'd like…\") or <em>«Sarebbe possibile…?»</em> (\"Would it be possible…?\"). Tone matters enormously.",
          ],
          keyPoint:
            "Open with 'Scusi, ma…' Soften with 'vorrei' / 'sarebbe possibile'. Never demand.",
        },
        {
          type: "vocab",
          heading: "When things break",
          items: [
            { l1: "non funziona", en: "(it) isn't working" },
            { l1: "è rotto / è rotta", en: "it's broken (m / f)" },
            { l1: "non c'è acqua calda", en: "there's no hot water" },
            { l1: "fa troppo caldo / freddo", en: "it's too hot / cold" },
            { l1: "c'è rumore", en: "there's noise" },
            { l1: "la luce non si accende", en: "the light doesn't turn on" },
            { l1: "manca il…", en: "the … is missing" },
            { l1: "è sporco / sporca", en: "it's dirty (m / f)" },
            { l1: "potrebbe…?", en: "could you…? (very polite)" },
            { l1: "sarebbe possibile…?", en: "would it be possible…?" },
            { l1: "cambiare camera", en: "to change rooms" },
            { l1: "il reclamo", en: "the formal complaint" },
          ],
        },
        {
          type: "dialogue",
          heading: "Reporting an issue",
          setup: "You go down to reception after 11 pm.",
          lines: [
            { speaker: "You", l1: "Buonasera. Scusi se disturbo, ma c'è un problema nella mia camera.", en: "Good evening. Sorry to bother you, but there's a problem in my room." },
            { speaker: "Receptionist", l1: "Mi dica, cosa succede?", en: "Tell me, what's happening?" },
            { speaker: "You", l1: "L'aria condizionata non funziona, e fa molto caldo. Sarebbe possibile mandare qualcuno a controllare?", en: "The air conditioning isn't working, and it's very hot. Would it be possible to send someone to check?" },
            { speaker: "Receptionist", l1: "Certo. Mando subito il tecnico. Se non riesce a sistemarla, Le do un'altra camera.", en: "Of course. I'll send the technician right away. If he can't fix it, I'll give you another room." },
            { speaker: "You", l1: "La ringrazio molto. Mi può anche portare un ventilatore intanto?", en: "Thank you very much. Can you also bring a fan in the meantime?" },
            { speaker: "Receptionist", l1: "Subito. Mi spiace per il disagio.", en: "Right away. I'm sorry for the inconvenience." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Polite complaint patterns",
          items: [
            {
              template: "Scusi, ma il rubinetto è ___ .",
              answer: "rotto",
              en: "Excuse me, but the faucet is broken.",
              options: ["rotto", "perso", "stanco", "lontano"],
            },
            {
              template: "Non c'è acqua ___ in bagno.",
              answer: "calda",
              en: "There's no hot water in the bathroom.",
              options: ["fredda", "calda", "alta", "buona"],
            },
            {
              template: "Mi ___ molto rumore dalla strada.",
              answer: "arriva",
              en: "Lots of noise reaches me from the street.",
              options: ["arriva", "viene", "esce", "manca"],
            },
            {
              template: "Sarebbe possibile ___ camera?",
              answer: "cambiare",
              en: "Would it be possible to change rooms?",
              options: ["pagare", "cambiare", "comprare", "chiudere"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Excuse me, but the heating isn't working and it's very cold.",
          reference: "Mi scusi, ma il riscaldamento non funziona e fa molto freddo.",
          hint: "Heating = riscaldamento. 'It's very cold' uses 'fare' → 'fa freddo'.",
        },
        {
          type: "tip",
          heading: "Tip jar and small things",
          body: "Tipping at hotels is optional and modest. €1-2 for the porter who carries your bags, €1-2/day for housekeeping (leave it on the pillow). At checkout, if everything was great: <em>«Tutto è stato perfetto, grazie davvero.»</em> A Google review goes much further than cash in Italy.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'I have a reservation' =",
        options: [
          "Ho un appuntamento.",
          "Ho una prenotazione.",
          "Faccio una prenotazione.",
          "Vorrei una prenotazione.",
        ],
        correct: 1,
      },
      {
        q: "'Double room with one big bed' =",
        options: [
          "camera singola",
          "camera doppia",
          "camera matrimoniale",
          "camera tripla",
        ],
        correct: 2,
      },
      {
        q: "In Italy, '1° piano' refers to…",
        options: [
          "the ground floor",
          "the second floor (American sense)",
          "the basement",
          "the rooftop",
        ],
        correct: 1,
      },
      {
        q: "'The air conditioning isn't working' =",
        options: [
          "L'aria condizionata è perduta.",
          "L'aria condizionata non funziona.",
          "L'aria condizionata non lavora.",
          "L'aria condizionata fa freddo.",
        ],
        correct: 1,
      },
      {
        q: "Polite 'Would it be possible to…?' =",
        options: [
          "Voglio…",
          "Devo…",
          "Sarebbe possibile…?",
          "Mi serve…",
        ],
        correct: 2,
      },
      {
        q: "Lost luggage form is called…",
        options: ["fattura", "ricevuta", "modulo PIR", "scontrino"],
        correct: 2,
      },
      {
        q: "'The Wi-Fi password' =",
        options: [
          "la password del Wi-Fi",
          "la parola del Wi-Fi",
          "il codice del Wi-Fi",
          "la chiave del Wi-Fi",
        ],
        correct: 0,
      },
      {
        q: "Translate: 'May I see your passport?'",
        options: [
          "Posso vedere il tuo passaporto?",
          "Posso vedere il Suo passaporto?",
          "Vedere il passaporto?",
          "Mi dia il passaporto.",
        ],
        correct: 1,
      },
      {
        q: "'I'd like to change rooms' =",
        options: [
          "Voglio cambiare camera.",
          "Vorrei cambiare camera.",
          "Devo cambiare camera.",
          "Cambio camera.",
        ],
        correct: 1,
      },
      {
        q: "'Breakfast is included' =",
        options: [
          "La colazione è gratis.",
          "La colazione è inclusa.",
          "La colazione è dentro.",
          "Includo la colazione.",
        ],
        correct: 1,
      },
    ],
  },
};
