import type { Unit } from "../../types";

export const UNIT_TRATTORIA: Unit = {
  slug: "trattoria",
  stage: 4,
  order: 16,
  icon: "🍝",
  title: "At the trattoria",
  tagline: "Antipasto, primo, secondo, contorno, dolce — and the gentle art of asking for il conto.",
  badge: "tourist",
  lessons: [
    {
      slug: "trattoria-structure",
      title: "The Italian meal structure",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "A real Italian dinner has acts, like a play",
          body: [
            "<strong>Antipasto</strong> = appetizer. Cured meats, cheese, bruschetta, sometimes fried things.",
            "<strong>Primo</strong> = first course. Pasta, risotto, soup. Always carbs.",
            "<strong>Secondo</strong> = second/main. Meat or fish, usually plain — Italians don't pile sides on the plate.",
            "<strong>Contorno</strong> = side dish. Ordered separately. Roasted potatoes, sautéed greens, grilled vegetables.",
            "<strong>Dolce</strong> = dessert. <strong>Caffè</strong> after, NEVER cappuccino. Sometimes a <strong>digestivo</strong> (grappa, amaro, limoncello).",
            "You don't have to order all of them. Two courses is normal. Skipping the primo to go straight to secondo is fine. Just don't order soup + pasta + risotto in the same meal — Italians find that weird.",
          ],
          keyPoint:
            "Antipasto → primo → secondo (+ contorno) → dolce → caffè → digestivo. Two courses is plenty for one diner.",
        },
        {
          type: "vocab",
          heading: "Menu structure",
          items: [
            { l1: "l'antipasto", en: "appetizer" },
            { l1: "il primo (piatto)", en: "first course (pasta, risotto)" },
            { l1: "il secondo (piatto)", en: "second course (meat/fish)" },
            { l1: "il contorno", en: "side dish" },
            { l1: "il dolce", en: "dessert" },
            { l1: "il caffè", en: "espresso (the post-meal kind)" },
            { l1: "il digestivo", en: "after-dinner digestive (grappa, amaro)" },
            { l1: "il menù turistico / fisso", en: "tourist / fixed-price menu" },
            { l1: "alla carta", en: "à la carte" },
            { l1: "il coperto", en: "cover charge" },
            { l1: "il servizio", en: "service charge (less common, but exists)" },
          ],
        },
        {
          type: "vocab",
          heading: "Trattoria types",
          items: [
            { l1: "il ristorante", en: "the restaurant (more formal)" },
            { l1: "la trattoria", en: "casual family restaurant" },
            { l1: "l'osteria", en: "casual rustic spot (originally wine + simple food)" },
            { l1: "la pizzeria", en: "pizzeria" },
            { l1: "la tavola calda", en: "cafeteria-style hot food" },
            { l1: "il fast food", en: "fast food (yes, that word transferred)" },
            { l1: "il bistrot", en: "bistro (modern, French-influenced)" },
            { l1: "l'enoteca", en: "wine bar (often with small plates)" },
          ],
        },
        {
          type: "tip",
          heading: "How to spot a tourist trap",
          body: "Red flags: menu translated into 5+ languages, photos of the food, a host on the sidewalk inviting you in, \"spaghetti bolognese\" on the menu (this dish doesn't exist in Italy — it's <em>tagliatelle al ragù</em> in Bologna). Real trattorias have hand-written daily menus, locals at the tables, and a brusque-but-warm staff who don't have time to coax you in.",
          example: { l1: "Avete una specialità della casa?", en: "Do you have a house specialty?" },
        },
        {
          type: "multipleChoice",
          heading: "Course order",
          questions: [
            {
              q: "Which goes FIRST in the meal structure?",
              options: ["secondo", "primo", "antipasto", "dolce"],
              correct: 2,
            },
            {
              q: "Pasta or risotto is in the…",
              options: ["antipasto", "primo", "secondo", "contorno"],
              correct: 1,
            },
            {
              q: "Meat or fish is in the…",
              options: ["primo", "secondo", "antipasto", "contorno"],
              correct: 1,
            },
            {
              q: "A 'contorno' is a…",
              options: [
                "dessert",
                "side dish (ordered separately)",
                "drink",
                "second appetizer",
              ],
              correct: 1,
            },
            {
              q: "'Spaghetti bolognese' on a Rome menu suggests…",
              options: [
                "regional authenticity",
                "tourist-trap red flag — the dish doesn't exist in Italy",
                "vegetarian option",
                "a chef from Bologna",
              ],
              correct: 1,
            },
          ],
        },
      ],
    },
    {
      slug: "trattoria-ordering",
      title: "Ordering — getting through the full meal",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The arc of ordering",
          body: [
            "<strong>Sitting down:</strong> <em>«Buonasera, abbiamo una prenotazione a nome…»</em> or <em>«Avete un tavolo per due?»</em>",
            "<strong>Getting the menu:</strong> <em>«Il menù, per favore.»</em> The waiter usually brings water and asks about wine first.",
            "<strong>Asking what's good:</strong> <em>«Cosa mi consiglia?»</em> Always rewarded.",
            "<strong>Ordering courses:</strong> <em>«Come antipasto prendo…, come primo…, e come secondo…»</em>",
            "<strong>Drinks:</strong> <em>«Una bottiglia di acqua naturale e una di frizzante.»</em> + a wine choice.",
            "<strong>The check:</strong> <em>«Il conto, per favore.»</em>",
          ],
          keyPoint:
            "Buonasera → menù → cosa consiglia → come primo… come secondo… → acqua + vino → il conto.",
        },
        {
          type: "vocab",
          heading: "Ordering vocabulary",
          items: [
            { l1: "prendo / prendiamo", en: "I'll have / we'll have" },
            { l1: "come antipasto…", en: "as an appetizer…" },
            { l1: "come primo / secondo / contorno", en: "as first / second / side" },
            { l1: "cosa mi consiglia?", en: "what do you recommend? (formal)" },
            { l1: "la specialità della casa", en: "the house specialty" },
            { l1: "fatto in casa", en: "homemade" },
            { l1: "del giorno", en: "of the day" },
            { l1: "la lista dei vini", en: "the wine list" },
            { l1: "acqua naturale / frizzante", en: "still / sparkling water" },
            { l1: "una caraffa / una bottiglia", en: "a carafe / a bottle" },
            { l1: "il conto", en: "the check / bill" },
            { l1: "lo scontrino / la ricevuta", en: "the receipt" },
            { l1: "siamo pronti", en: "we're ready (to order)" },
          ],
        },
        {
          type: "dialogue",
          heading: "Full dinner order",
          setup: "It's 8 pm. You and a friend sit down at a Trastevere trattoria.",
          lines: [
            { speaker: "Cameriere", l1: "Buonasera. Avete prenotato?", en: "Good evening. Did you reserve?" },
            { speaker: "You", l1: "Sì, a nome Smith, per due.", en: "Yes, under Smith, for two." },
            { speaker: "Cameriere", l1: "Perfetto. Accomodatevi. Acqua naturale o frizzante?", en: "Perfect. Have a seat. Still or sparkling water?" },
            { speaker: "You", l1: "Una di naturale e una di frizzante, grazie.", en: "One still and one sparkling, thanks." },
            { speaker: "Cameriere", l1: "Vino? Della casa o dalla lista?", en: "Wine? House wine or from the list?" },
            { speaker: "You", l1: "Una mezza bottiglia di rosso della casa. Cosa ci consiglia?", en: "A half bottle of house red. What do you recommend?" },
            { speaker: "Cameriere", l1: "Per cominciare, il fritto misto è ottimo. Tra i primi, le linguine alle vongole sono freschissime oggi. Come secondo, l'abbacchio scottadito è la nostra specialità.", en: "To start, the mixed fried plate is excellent. Among the firsts, the linguine with clams are very fresh today. As a main, the grilled lamb chops are our specialty." },
            { speaker: "You", l1: "Allora prendiamo un fritto misto da dividere, poi io prendo le linguine alle vongole, e per il mio amico la cacio e pepe.", en: "Then we'll take a mixed fried plate to share, then I'll have the linguine with clams, and for my friend the cacio e pepe." },
            { speaker: "Cameriere", l1: "Come secondo?", en: "And as a second course?" },
            { speaker: "You", l1: "Per ora no, vediamo dopo. Grazie.", en: "Not for now, we'll see later. Thank you." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Ordering blanks",
          items: [
            {
              template: "Avete un ___ per due?",
              answer: "tavolo",
              en: "Do you have a table for two?",
              options: ["tavolo", "menù", "ristorante", "letto"],
            },
            {
              template: "Una bottiglia di acqua ___ , per favore.",
              answer: "naturale",
              en: "A bottle of still water, please.",
              options: ["naturale", "tappata", "calda", "fredda"],
            },
            {
              template: "Cosa ci ___ , come secondo?",
              answer: "consiglia",
              en: "What do you recommend as a second course?",
              options: ["dice", "consiglia", "piace", "fa"],
            },
            {
              template: "Come ___ prendo il fritto misto.",
              answer: "antipasto",
              en: "As an appetizer I'll have the mixed fried plate.",
              options: ["primo", "secondo", "antipasto", "contorno"],
            },
            {
              template: "Il ___ , per favore.",
              answer: "conto",
              en: "The check, please.",
              options: ["scontrino", "menù", "conto", "tavolo"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Restaurant phrases",
          items: [
            { tokens: ["Abbiamo", "una", "prenotazione", "a", "nome", "Rossi"], en: "We have a reservation under Rossi." },
            { tokens: ["Vorrei", "una", "mezza", "bottiglia", "di", "vino", "rosso"], en: "I'd like a half bottle of red wine." },
            { tokens: ["Possiamo", "dividere", "l'antipasto", "in", "due", "?"], en: "Can we split the appetizer in two?" },
            { tokens: ["Il", "conto", "separato", ",", "per", "favore"], en: "Separate checks, please." },
          ],
        },
      ],
    },
    {
      slug: "trattoria-paying-leaving",
      title: "Paying, tipping, leaving",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "The check arrives only when you ask",
          body: [
            "Italian waiters NEVER drop the check unprompted. You'll sit at the table forever waiting. Just say <em>«Il conto, per favore.»</em> or do the universal scribble-in-air pen gesture.",
            "Payment: card is almost always accepted (POS = point-of-sale machine; ask <em>«Si può pagare con la carta?»</em>). Cash is also fine. American Express is sometimes refused; Visa/Mastercard always works.",
            "<strong>Tipping</strong>: NOT 18-20% like the US. Roman locals leave nothing or round up to the nearest €5. Tourists often leave €2-5 per person if service was great. Anything more is generous.",
            "Always get a <em>scontrino</em> (receipt) — by law restaurants must issue one. It's also your proof if you have an issue.",
          ],
          keyPoint:
            "Ask for il conto. Pay with card or cash. Tip €0-5 (not 20%). Take the scontrino.",
        },
        {
          type: "vocab",
          heading: "Paying and leaving",
          items: [
            { l1: "il conto", en: "the bill / check" },
            { l1: "lo scontrino / la ricevuta", en: "the receipt" },
            { l1: "la mancia", en: "the tip" },
            { l1: "la carta di credito / di debito", en: "credit / debit card" },
            { l1: "i contanti", en: "cash" },
            { l1: "il POS / il bancomat", en: "card machine / debit card (informal)" },
            { l1: "separato / insieme", en: "separate / together" },
            { l1: "diviso a metà", en: "split in half" },
            { l1: "tenga il resto", en: "keep the change" },
            { l1: "complimenti al cuoco", en: "compliments to the chef" },
            { l1: "torneremo", en: "we'll come back" },
          ],
        },
        {
          type: "dialogue",
          heading: "Asking for the check",
          setup: "End of dinner. You catch the waiter's eye.",
          lines: [
            { speaker: "You", l1: "Mi scusi, il conto per favore!", en: "Excuse me, the check please!" },
            { speaker: "Cameriere", l1: "Subito. Tutto bene la cena?", en: "Right away. Was dinner okay?" },
            { speaker: "You", l1: "Tutto buonissimo, davvero. Complimenti al cuoco.", en: "Everything was delicious, really. Compliments to the chef." },
            { speaker: "Cameriere", l1: "Grazie, glielo dico. Ecco il conto.", en: "Thank you, I'll tell him. Here's the check." },
            { speaker: "You", l1: "Si può pagare con la carta?", en: "Can I pay by card?" },
            { speaker: "Cameriere", l1: "Certo, accettiamo tutte le carte.", en: "Of course, we accept all cards." },
            { speaker: "You", l1: "Ecco. Tenga il resto, dieci euro di mancia.", en: "Here. Keep the change, ten euros tip." },
            { speaker: "Cameriere", l1: "Grazie mille, gentilissimo! Buona serata!", en: "Thank you very much, very kind! Have a good evening!" },
            { speaker: "You", l1: "Anche a Lei. Torneremo.", en: "You too. We'll come back." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Paying-up phrases",
          items: [
            {
              template: "Il ___ , per favore.",
              answer: "conto",
              en: "The check, please.",
              options: ["scontrino", "conto", "menù", "ricevuta"],
            },
            {
              template: "Si può pagare con la ___ ?",
              answer: "carta",
              en: "Can I pay by card?",
              options: ["carta", "moneta", "banconota", "mancia"],
            },
            {
              template: "Tenga il ___ .",
              answer: "resto",
              en: "Keep the change.",
              options: ["scontrino", "resto", "denaro", "menù"],
            },
            {
              template: "Possiamo pagare ___ ?",
              answer: "separati",
              en: "Can we pay separately?",
              options: ["separati", "insieme", "doppi", "totali"],
            },
            {
              template: "Mi può fare la ___ , per favore?",
              answer: "ricevuta",
              en: "Can you make the receipt, please?",
              options: ["ricevuta", "carta", "mancia", "porzione"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "The check please. Can we pay separately?",
          reference: "Il conto, per favore. Possiamo pagare separati?",
          hint: "'Separati' agrees with the implied plural 'we' (m). Use 'separate' if all-female group.",
        },
        {
          type: "tip",
          heading: "The 'tasted but didn't like' situation",
          body: "If you don't like a dish, it's NOT rude to leave food on the plate — Italians don't moralize about that. But sending a dish back is rare and considered confrontational. Better: try a few bites, leave it, mention politely <em>«Non era proprio il mio gusto, ma il resto era ottimo.»</em> at the end. They appreciate honesty without drama.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "The 5 main course types in order are…",
        options: [
          "antipasto, dolce, primo, secondo, caffè",
          "primo, secondo, antipasto, contorno, dolce",
          "antipasto, primo, secondo (+ contorno), dolce",
          "appetizer, main, salad, dessert, wine",
        ],
        correct: 2,
      },
      {
        q: "Pasta is in the…",
        options: ["secondo", "primo", "contorno", "antipasto"],
        correct: 1,
      },
      {
        q: "Side dish (separately ordered) =",
        options: ["antipasto", "primo", "secondo", "contorno"],
        correct: 3,
      },
      {
        q: "'What do you recommend?' (formal) =",
        options: [
          "Cosa mi piace?",
          "Cosa mi consiglia?",
          "Cosa è buono?",
          "Cosa devi prendere?",
        ],
        correct: 1,
      },
      {
        q: "The waiter will bring the check…",
        options: [
          "automatically after dessert",
          "only when you ask",
          "with the menu",
          "after one hour",
        ],
        correct: 1,
      },
      {
        q: "'Sparkling water' =",
        options: [
          "acqua naturale",
          "acqua frizzante",
          "acqua minerale",
          "acqua corrente",
        ],
        correct: 1,
      },
      {
        q: "Tipping in Italian restaurants is typically…",
        options: [
          "18-20%",
          "10%",
          "round up or €2-5 per person if service was good",
          "always exactly 15%",
        ],
        correct: 2,
      },
      {
        q: "'Spaghetti bolognese' on a Rome menu is…",
        options: [
          "a regional classic",
          "a tourist-trap signal — that dish doesn't exist in Italy",
          "always vegetarian",
          "the chef's specialty",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'Can we split the appetizer?'",
        options: [
          "Possiamo dividere l'antipasto?",
          "Possiamo doppia l'antipasto?",
          "Vorremmo l'antipasto in due.",
          "Si divide l'antipasto?",
        ],
        correct: 0,
      },
      {
        q: "'Compliments to the chef' =",
        options: [
          "Buon cuoco!",
          "Bravo il cuoco!",
          "Complimenti al cuoco.",
          "Tutto è stato buono.",
        ],
        correct: 2,
      },
    ],
  },
};
