import type { Unit } from "../../types";

export const UNIT_DIET_WINE: Unit = {
  slug: "diet-wine",
  stage: 4,
  order: 18,
  icon: "🍷",
  title: "Wine & dietary needs",
  tagline: "Vino della casa, allergies, vegetarian/celiac phrases — and how to taste wine like you're not afraid.",
  badge: "tourist",
  lessons: [
    {
      slug: "diet-wine-basics",
      title: "Wine: reading the menu without panic",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "You don't have to be a sommelier",
          body: [
            "Default safe order: <em>«Una caraffa di vino della casa, rosso (or bianco).»</em> = A carafe of house wine, red (or white). The house wine is usually local, cheap (€8-15/half-liter), and good enough for a casual meal.",
            "If the restaurant is fancy or wine-focused, ask <em>«Cosa ci consiglia di leggero / corposo / fruttato?»</em> = What do you recommend that's light / full-bodied / fruity?",
            "Italian wine is regional. In Rome you'll see lots of Lazio (<em>Frascati</em> for whites), Tuscan (<em>Chianti</em> for reds), Piedmont (<em>Barolo</em>, expensive), and Puglia (<em>Primitivo</em>, bold and fruity reds).",
          ],
          keyPoint:
            "Vino della casa = safe, cheap default. Caraffa / mezzo litro / litro = carafe / half-liter / liter. Ask 'leggero / corposo / fruttato' if browsing the list.",
        },
        {
          type: "vocab",
          heading: "Wine vocabulary",
          items: [
            { l1: "il vino", en: "wine" },
            { l1: "rosso / bianco / rosato", en: "red / white / rosé" },
            { l1: "spumante", en: "sparkling" },
            { l1: "il prosecco", en: "prosecco (Veneto sparkling)" },
            { l1: "vino della casa", en: "house wine" },
            { l1: "una bottiglia / mezza bottiglia", en: "a bottle / half bottle" },
            { l1: "un calice", en: "a wine glass (a single pour)" },
            { l1: "una caraffa", en: "a carafe" },
            { l1: "un quartino / mezzo litro / un litro", en: "1/4 / 1/2 / full liter" },
            { l1: "secco", en: "dry" },
            { l1: "amabile", en: "off-dry / slightly sweet" },
            { l1: "dolce", en: "sweet" },
            { l1: "leggero", en: "light-bodied" },
            { l1: "corposo", en: "full-bodied" },
            { l1: "fruttato", en: "fruity" },
            { l1: "annata", en: "vintage / year" },
          ],
        },
        {
          type: "vocab",
          heading: "Famous Italian wines you'll see",
          items: [
            { l1: "Chianti (Toscana)", en: "Chianti — light-medium red, very food-friendly" },
            { l1: "Barolo (Piemonte)", en: "Barolo — big, age-worthy red (expensive)" },
            { l1: "Brunello di Montalcino (Toscana)", en: "Brunello — also big, age-worthy red" },
            { l1: "Primitivo (Puglia)", en: "Primitivo — jammy, bold red" },
            { l1: "Nero d'Avola (Sicilia)", en: "Nero d'Avola — Sicilian dark red" },
            { l1: "Frascati (Lazio)", en: "Frascati — Roman white, light + crisp" },
            { l1: "Vermentino (Sardegna)", en: "Vermentino — coastal white, seafood pairing" },
            { l1: "Pinot Grigio (Trentino)", en: "Pinot Grigio — light white, clean" },
            { l1: "Prosecco (Veneto)", en: "Prosecco — bubbly, aperitivo standard" },
            { l1: "Lambrusco (Emilia-Romagna)", en: "Lambrusco — slightly fizzy red" },
            { l1: "Limoncello", en: "lemon liqueur (south, after-dinner)" },
            { l1: "Grappa", en: "grappa (distilled grape pomace, strong digestivo)" },
            { l1: "Amaro", en: "amaro (bitter herbal digestivo, e.g. Averna, Fernet)" },
          ],
        },
        {
          type: "dialogue",
          heading: "Ordering wine at dinner",
          setup: "Mid-meal, the waiter asks about wine.",
          lines: [
            { speaker: "Cameriere", l1: "Da bere, qualcosa di vino?", en: "To drink, something wine-wise?" },
            { speaker: "You", l1: "Sì. Cosa ci consiglia con la carbonara?", en: "Yes. What do you recommend with carbonara?" },
            { speaker: "Cameriere", l1: "Un bianco strutturato. Abbiamo un Frascati Superiore della Cantina Castelli, ottimo e locale.", en: "A structured white. We have a Frascati Superiore from Castelli winery, excellent and local." },
            { speaker: "You", l1: "Quanto costa la bottiglia?", en: "How much is the bottle?" },
            { speaker: "Cameriere", l1: "Ventidue euro. Oppure se vuole risparmiare, c'è il vino della casa a otto euro al mezzo litro.", en: "Twenty-two euros. Or if you want to save, the house wine is eight euros for half a liter." },
            { speaker: "You", l1: "Allora prendiamo il vino della casa. Mezzo litro va bene per due.", en: "Then we'll have the house wine. Half a liter is fine for two." },
            { speaker: "Cameriere", l1: "Subito.", en: "Right away." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Wine ordering",
          items: [
            {
              template: "Vorrei una ___ di Chianti.",
              answer: "bottiglia",
              en: "I'd like a bottle of Chianti.",
              options: ["bottiglia", "tazza", "caraffa", "bicchiere"],
            },
            {
              template: "Un ___ di vino bianco, per favore.",
              answer: "calice",
              en: "A glass of white wine, please.",
              options: ["calice", "metà", "litro", "porzione"],
            },
            {
              template: "Mi consiglia qualcosa di ___ e fruttato.",
              answer: "leggero",
              en: "Recommend me something light and fruity.",
              options: ["secco", "leggero", "amaro", "salato"],
            },
            {
              template: "Vorrei un ___ come digestivo.",
              answer: "amaro",
              en: "I'd like an amaro as a digestive.",
              options: ["amaro", "cappuccino", "spumante", "rosso"],
            },
            {
              template: "Una ___ di vino della casa, mezzo litro.",
              answer: "caraffa",
              en: "A carafe of house wine, half a liter.",
              options: ["bottiglia", "caraffa", "calice", "porzione"],
            },
          ],
        },
        {
          type: "tip",
          heading: "Two cheap tricks",
          body: "1) Order <em>«il vino della casa»</em> by the half-liter and 9 times out of 10 you'll get a perfectly fine wine for €8-12. 2) If you want to look knowledgeable: order a <em>Falanghina</em> (Campania white), a <em>Cesanese</em> (Lazio red), or anything labeled <em>biodynamic</em> / <em>biodinamico</em> — these are local, lesser-known, and waiters will assume you know your stuff.",
        },
      ],
    },
    {
      slug: "diet-allergies",
      title: "Allergies & dietary needs",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Italy takes food allergies seriously",
          body: [
            "EU law requires restaurants to disclose the 14 major allergens on menus or on request. Phrases below are universally understood by trained staff.",
            "<em>«Sono allergico/a a…»</em> = I'm allergic to… (m/f).",
            "<em>«Sono intollerante al…»</em> = I'm intolerant to… (e.g., al lattosio = to lactose).",
            "<em>«Non posso mangiare…»</em> = I cannot eat… — softer, doesn't require an allergy.",
            "<em>«Avete opzioni senza glutine / lattosio / latte / uova?»</em> = Do you have gluten / lactose / dairy / egg-free options?",
          ],
          keyPoint:
            "Sono allergico/a (allergy) > sono intollerante a (intolerance) > non posso mangiare (preference). Be specific to be safe.",
        },
        {
          type: "vocab",
          heading: "Diet & allergen vocabulary",
          items: [
            { l1: "vegetariano / vegetariana", en: "vegetarian (m / f)" },
            { l1: "vegano / vegana", en: "vegan (m / f)" },
            { l1: "senza glutine", en: "gluten-free" },
            { l1: "celiaco / celiaca", en: "celiac (m / f)" },
            { l1: "senza lattosio", en: "lactose-free" },
            { l1: "intollerante al lattosio", en: "lactose-intolerant" },
            { l1: "i latticini", en: "dairy products" },
            { l1: "le uova", en: "eggs" },
            { l1: "il grano / il frumento", en: "wheat" },
            { l1: "le arachidi", en: "peanuts" },
            { l1: "la frutta secca", en: "tree nuts" },
            { l1: "i crostacei", en: "shellfish" },
            { l1: "il pesce", en: "fish" },
            { l1: "la soia", en: "soy" },
            { l1: "il sedano", en: "celery (a listed allergen in EU)" },
            { l1: "kosher", en: "kosher (rare in Italy)" },
            { l1: "halal", en: "halal (search in immigrant neighborhoods)" },
          ],
        },
        {
          type: "dialogue",
          heading: "Telling the waiter about an allergy",
          setup: "Before ordering, you flag your celiac diet.",
          lines: [
            { speaker: "You", l1: "Mi scusi, prima di ordinare: sono celiaca, quindi non posso mangiare glutine. Avete piatti senza glutine?", en: "Excuse me, before ordering: I'm celiac, so I can't eat gluten. Do you have gluten-free dishes?" },
            { speaker: "Cameriere", l1: "Certo. Abbiamo la pasta senza glutine, costa due euro in più. E tutti i secondi di carne e pesce sono naturalmente senza glutine, basta non condirli con farina.", en: "Of course. We have gluten-free pasta, it costs two euros extra. And all the meat and fish mains are naturally gluten-free, as long as we don't dress them with flour." },
            { speaker: "You", l1: "Perfetto. Posso prendere le linguine senza glutine alle vongole?", en: "Perfect. Can I have the gluten-free linguine with clams?" },
            { speaker: "Cameriere", l1: "Sì. Avviso il cuoco di usare una pentola separata.", en: "Yes. I'll tell the chef to use a separate pot." },
            { speaker: "You", l1: "Grazie davvero, è molto importante per me.", en: "Thank you really, it's very important to me." },
          ],
        },
        {
          type: "dialogue",
          heading: "Vegetarian at a meat-heavy place",
          setup: "Roman trattorias love meat. You're vegetarian.",
          lines: [
            { speaker: "You", l1: "Sono vegetariano. Cosa mi può consigliare?", en: "I'm vegetarian. What can you recommend?" },
            { speaker: "Cameriere", l1: "Allora, antipasto: bruschette con pomodoro, olive, formaggi. Primi senza carne: cacio e pepe, gricia no perché c'è il guanciale, ma c'è la pasta al pomodoro e il risotto ai funghi. Come secondo, una parmigiana di melanzane.", en: "So, appetizer: bruschette with tomato, olives, cheeses. Pastas without meat: cacio e pepe — gricia no, because there's guanciale — but there's tomato pasta and mushroom risotto. As a main, an eggplant parmigiana." },
            { speaker: "You", l1: "Ottimo. Sono anche allergico alle arachidi. Ci sono in qualche piatto?", en: "Great. I'm also allergic to peanuts. Are they in any dish?" },
            { speaker: "Cameriere", l1: "No, le arachidi non si usano nella cucina romana, tranquillo.", en: "No, peanuts aren't used in Roman cuisine, no worries." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Diet fill-ins",
          items: [
            {
              template: "Sono ___ . Avete piatti vegani?",
              answer: "vegana",
              en: "I'm vegan (female). Do you have vegan dishes?",
              options: ["vegana", "vegano", "vegetariana", "celiaca"],
            },
            {
              template: "Sono ___ ai crostacei.",
              answer: "allergico",
              en: "I'm allergic to shellfish. (male)",
              options: ["allergico", "celiaco", "vegetariano", "stanco"],
            },
            {
              template: "Avete il pane ___ glutine?",
              answer: "senza",
              en: "Do you have gluten-free bread?",
              options: ["senza", "con", "di", "del"],
            },
            {
              template: "Sono ___ al lattosio.",
              answer: "intollerante",
              en: "I'm lactose intolerant.",
              options: ["allergico", "intollerante", "celiaco", "vegetariano"],
            },
            {
              template: "Non posso mangiare le ___ .",
              answer: "uova",
              en: "I can't eat eggs.",
              options: ["uova", "carne", "patate", "verdure"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'm allergic to peanuts and shellfish. Can you check with the chef?",
          reference: "Sono allergico/a alle arachidi e ai crostacei. Può controllare con il cuoco?",
          hint: "Allergico/a + alle (allergens are usually plural). 'Può + infinitive' = 'can you…' (formal).",
        },
        {
          type: "tip",
          heading: "If a dish you don't like is suggested",
          body: "Italians are direct. If a waiter recommends a dish you find unappealing (offal, tripe, rabbit), just say <em>«Non è proprio il mio gusto, preferisco qualcosa di più semplice. Cosa altro consiglia?»</em> = It's not really my taste, I prefer something simpler. What else do you recommend? No need to apologize — they just shift gears.",
        },
      ],
    },
    {
      slug: "diet-dishes-disliked",
      title: "Dishes you might want to avoid (and what they are)",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Italian cuisine includes things English speakers find weird",
          body: [
            "Italians eat the whole animal. Roman cuisine especially is built on <em>il quinto quarto</em> = the 'fifth quarter' (offal). Knowing the names spares you a surprise:",
            "<em>Trippa</em> = tripe (stomach). <em>Coda alla vaccinara</em> = oxtail stew. <em>Pajata</em> = unweaned veal intestines. <em>Cervella</em> = brains. <em>Animelle</em> = sweetbreads. <em>Lingua</em> = tongue.",
            "Also: <em>Bottarga</em> = cured fish roe. <em>Acciughe</em> = anchovies (in many sauces — like puttanesca). <em>Aringa</em> = pickled herring.",
            "<em>Lumache</em> = snails. <em>Frattaglie</em> = offal in general. <em>Sanguinaccio</em> = blood pudding/sausage.",
          ],
          keyPoint:
            "Italian menus include offal. Know the names so 'pajata' or 'trippa' doesn't surprise you. Just order something else if it's not your thing.",
        },
        {
          type: "vocab",
          heading: "Items to be aware of",
          items: [
            { l1: "la trippa", en: "tripe" },
            { l1: "la coda (alla vaccinara)", en: "oxtail (Roman stew)" },
            { l1: "la pajata", en: "unweaned veal intestines (Roman specialty)" },
            { l1: "la cervella", en: "brains" },
            { l1: "le animelle", en: "sweetbreads" },
            { l1: "la lingua", en: "tongue" },
            { l1: "il fegato", en: "liver" },
            { l1: "il rognone", en: "kidney" },
            { l1: "le lumache", en: "snails" },
            { l1: "la bottarga", en: "cured fish roe" },
            { l1: "le acciughe / le alici", en: "anchovies" },
            { l1: "il sanguinaccio", en: "blood pudding / sausage" },
            { l1: "lo zampone", en: "stuffed pig's trotter (winter dish)" },
            { l1: "il cotechino", en: "large sausage in casing (winter)" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Know what you're ordering",
          questions: [
            {
              q: "'Pajata' is…",
              options: [
                "a kind of pasta",
                "unweaned veal intestines",
                "a wine from Lazio",
                "a salad",
              ],
              correct: 1,
            },
            {
              q: "'Coda alla vaccinara' is…",
              options: [
                "a vegetarian dish",
                "oxtail stew (the 'tail' is what you're eating)",
                "a kind of bread",
                "a cured ham",
              ],
              correct: 1,
            },
            {
              q: "'Bottarga' is…",
              options: [
                "cured fish roe (grated over pasta)",
                "an Italian beer",
                "a kind of fish",
                "a dessert",
              ],
              correct: 0,
            },
            {
              q: "If you don't want offal, avoid…",
              options: [
                "trippa, pajata, cervella, animelle",
                "spaghetti, pizza, gelato",
                "carciofi, melanzane, zucchine",
                "branzino, orata, salmone",
              ],
              correct: 0,
            },
          ],
        },
        {
          type: "dialogue",
          heading: "Politely declining",
          setup: "Server recommends pajata.",
          lines: [
            { speaker: "Cameriere", l1: "Oggi le consiglio i rigatoni con la pajata, specialità romana.", en: "Today I recommend the rigatoni with pajata, a Roman specialty." },
            { speaker: "You", l1: "Grazie, ma non sono pronto per la pajata. Cosa avete di più tradizionale ma più… normale?", en: "Thanks, but I'm not ready for pajata. What do you have that's traditional but more… normal?" },
            { speaker: "Cameriere", l1: "Capisco. Le consiglio la cacio e pepe — pasta, pecorino, pepe nero. Semplicissima e romanissima.", en: "I understand. I recommend the cacio e pepe — pasta, pecorino, black pepper. Very simple and very Roman." },
            { speaker: "You", l1: "Perfetto, la cacio e pepe.", en: "Perfect, cacio e pepe." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Thanks, but I prefer something without offal. What do you recommend?",
          reference: "Grazie, ma preferisco qualcosa senza frattaglie. Cosa mi consiglia?",
          hint: "'Frattaglie' is the catch-all for offal. 'Senza' = without.",
        },
        {
          type: "tip",
          heading: "Anchovies are stealth",
          body: "Anchovies (<em>acciughe</em>, also called <em>alici</em>) are in tons of Italian dishes as a hidden umami booster — puttanesca sauce, bagna cauda, even some Caesar-style dressings. If you hate them, ask: <em>«C'è acciuga / alici dentro?»</em> = Are there anchovies in it? Most chefs will swap them out.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'House wine, half a liter' =",
        options: [
          "vino casa, mezzo litro",
          "vino della casa, mezzo litro",
          "vino di casa, litro",
          "casa-vino, mezzo",
        ],
        correct: 1,
      },
      {
        q: "Light, crisp Roman white wine =",
        options: ["Chianti", "Barolo", "Frascati", "Prosecco"],
        correct: 2,
      },
      {
        q: "'Corposo' means…",
        options: ["fruity", "full-bodied", "sparkling", "sweet"],
        correct: 1,
      },
      {
        q: "'I'm celiac' (female) =",
        options: ["Sono celiaco.", "Sono celiaca.", "Ho celiaca.", "Mi sono celiaca."],
        correct: 1,
      },
      {
        q: "'Gluten-free' =",
        options: ["senza glutine", "con glutine", "anti-glutine", "no-glutine"],
        correct: 0,
      },
      {
        q: "'Pajata' is…",
        options: [
          "a type of pasta",
          "unweaned veal intestines (Roman dish)",
          "a Roman wine",
          "a vegetable",
        ],
        correct: 1,
      },
      {
        q: "'Acciughe / alici' =",
        options: ["clams", "anchovies", "octopus", "calamari"],
        correct: 1,
      },
      {
        q: "Translate: 'I'm vegetarian, do you have any meat-free pasta?'",
        options: [
          "Sono vegetariano, avete pasta senza carne?",
          "Vorrei pasta, no carne.",
          "Non mangio carne, pasta vegetariana?",
          "Pasta senza carne, sono vegano.",
        ],
        correct: 0,
      },
      {
        q: "Tipping in Italy on top of the bill is…",
        options: [
          "expected at 18%",
          "rude — never tip",
          "optional, modest — round up or €2-5 per person",
          "always 20% like the US",
        ],
        correct: 2,
      },
      {
        q: "Strong distilled digestivo from grape pomace =",
        options: ["limoncello", "amaro", "grappa", "prosecco"],
        correct: 2,
      },
    ],
  },
};
