import type { Unit } from "../../types";

export const UNIT_SER_ESTAR: Unit = {
  slug: "ser-estar",
  stage: 1,
  order: 5,
  icon: "🧱",
  title: "Ser, estar & present tense",
  tagline: "The two 'to be' verbs plus -ar/-er/-ir regular verbs.",
  badge: "core",
  lessons: [
    {
      slug: "ser-estar-difference",
      title: "Ser vs estar — which 'to be'?",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "Spanish has two verbs for 'to be'",
          body: [
            "This is the most important distinction in Spanish grammar. <strong>Ser</strong> is for permanent or defining characteristics: identity, origin, profession, time, material. <strong>Estar</strong> is for temporary states, locations, and conditions.",
            "The rough guide: if you can say it's a core part of what something IS, use ser. If it's a state that can change, use estar.",
          ],
          tip: {
            label: "DOCTOR vs PLACE mnemonic",
            body: "Ser: Description, Occupation, Characteristic, Time, Origin, Relationship. Estar: Position, Location, Action, Condition, Emotion.",
          },
        },
        {
          type: "conjugation",
          heading: "Ser — present tense",
          verb: "ser",
          meaning: "to be (identity/origin)",
          tenses: [{ name: "Presente", forms: [
            { person: "yo", form: "soy" },
            { person: "tú", form: "eres" },
            { person: "él/ella/usted", form: "es" },
            { person: "nosotros", form: "somos" },
            { person: "vosotros", form: "sois" },
            { person: "ellos/ustedes", form: "son" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "Estar — present tense",
          verb: "estar",
          meaning: "to be (location/state)",
          tenses: [{ name: "Presente", forms: [
            { person: "yo", form: "estoy" },
            { person: "tú", form: "estás" },
            { person: "él/ella/usted", form: "está" },
            { person: "nosotros", form: "estamos" },
            { person: "vosotros", form: "estáis" },
            { person: "ellos/ustedes", form: "están" },
          ] }],
        },
        {
          type: "vocab",
          heading: "Ser or estar?",
          items: [
            { l1: "Soy español.", en: "I'm Spanish. (ser — origin/identity)", note: "ser" },
            { l1: "Soy médico.", en: "I'm a doctor. (ser — profession)", note: "ser" },
            { l1: "Son las tres.", en: "It's three o'clock. (ser — time)", note: "ser" },
            { l1: "Estoy en Madrid.", en: "I'm in Madrid. (estar — location)", note: "estar" },
            { l1: "Estás cansado.", en: "You're tired. (estar — temporary state)", note: "estar" },
            { l1: "Está enfermo.", en: "He's ill. (estar — condition)", note: "estar" },
            { l1: "El café está frío.", en: "The coffee is cold. (estar — current state)", note: "estar" },
            { l1: "La nieve es blanca.", en: "Snow is white. (ser — inherent quality)", note: "ser" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Ser or estar?",
          questions: [
            {
              q: "'She is a teacher' uses…",
              options: ["está", "es", "son", "estás"],
              correct: 1,
              fb: "Profession → ser. Ella es profesora.",
            },
            {
              q: "'The coffee is cold right now' uses…",
              options: ["es", "está", "son", "estoy"],
              correct: 1,
              fb: "Temporary current state → estar. El café está frío.",
            },
            {
              q: "'I'm in Madrid' uses…",
              options: ["soy", "es", "estoy", "somos"],
              correct: 2,
              fb: "Location → estar. Estoy en Madrid.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Ser or estar? Fill the blank",
          intro: "Choose the right form. Ask: defining trait, or changeable state?",
          items: [
            {
              template: "Yo ___ de Sevilla.",
              answer: "soy",
              en: "I'm from Seville. (origin → ser)",
              options: ["soy", "estoy", "es", "está"],
            },
            {
              template: "La sopa ___ caliente.",
              answer: "está",
              en: "The soup is hot. (current state → estar)",
              options: ["es", "está", "son", "estás"],
            },
            {
              template: "Mi hermana ___ profesora.",
              answer: "es",
              en: "My sister is a teacher. (profession → ser)",
              options: ["está", "es", "están", "estás"],
            },
            {
              template: "Nosotros ___ en el parque.",
              answer: "estamos",
              en: "We're in the park. (location → estar)",
              options: ["somos", "estamos", "estáis", "están"],
            },
            {
              template: "El libro ___ de papel.",
              answer: "es",
              en: "The book is made of paper. (material → ser)",
              options: ["está", "es", "están", "estamos"],
            },
            {
              template: "¿Cómo ___ (tú) hoy?",
              answer: "estás",
              en: "How are you today? (mood/condition → estar)",
              options: ["eres", "estás", "es", "está"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it — ser vs estar",
          direction: "en-to-l1",
          prompt: "I'm Spanish, but right now I'm in France.",
          reference: "Soy español, pero ahora estoy en Francia.",
          hint: "Nationality is identity → ser. Location → estar. Drop the subject pronoun.",
        },
      ],
    },
    {
      slug: "ser-estar-regular-verbs",
      title: "Regular -ar, -er, -ir verbs",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "Three verb families",
          body: [
            "Spanish infinitives end in <strong>-ar</strong>, <strong>-er</strong>, or <strong>-ir</strong>. Regular verbs in each family follow predictable patterns. Drop the infinitive ending and add the appropriate suffix for each person.",
            "The vast majority of Spanish verbs are -ar verbs. Learn this pattern well — most new verbs you encounter will follow it.",
          ],
          keyPoint: "-ar: -o/-as/-a/-amos/-áis/-an · -er: -o/-es/-e/-emos/-éis/-en · -ir: -o/-es/-e/-imos/-ís/-en",
        },
        {
          type: "conjugation",
          heading: "hablar (to speak) — regular -ar",
          verb: "hablar",
          meaning: "to speak",
          tenses: [{ name: "Presente", forms: [
            { person: "yo", form: "hablo" },
            { person: "tú", form: "hablas" },
            { person: "él/ella/usted", form: "habla" },
            { person: "nosotros", form: "hablamos" },
            { person: "vosotros", form: "habláis" },
            { person: "ellos/ustedes", form: "hablan" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "comer (to eat) — regular -er",
          verb: "comer",
          meaning: "to eat",
          tenses: [{ name: "Presente", forms: [
            { person: "yo", form: "como" },
            { person: "tú", form: "comes" },
            { person: "él/ella/usted", form: "come" },
            { person: "nosotros", form: "comemos" },
            { person: "vosotros", form: "coméis" },
            { person: "ellos/ustedes", form: "comen" },
          ] }],
        },
        {
          type: "vocab",
          heading: "Common verbs in context",
          items: [
            { l1: "Hablo español.", en: "I speak Spanish." },
            { l1: "¿Hablas inglés?", en: "Do you speak English?" },
            { l1: "Comemos a las dos.", en: "We eat at two." },
            { l1: "Vivo en Madrid.", en: "I live in Madrid. (vivir, -ir verb)" },
            { l1: "¿Dónde trabajas?", en: "Where do you work? (trabajar, -ar)" },
            { l1: "Necesito un taxi.", en: "I need a taxi. (necesitar, -ar)" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Conjugation check",
          questions: [
            {
              q: "What is the 'yo' form of 'hablar'?",
              options: ["hablas", "hablo", "habla", "hablamos"],
              correct: 1,
              fb: "Regular -ar: yo form drops -ar and adds -o. hablo.",
            },
            {
              q: "What is 'they eat'?",
              options: ["comemos", "comes", "comen", "come"],
              correct: 2,
              fb: "Ellos/ellas comen — third person plural -er: -en.",
            },
            {
              q: "What is 'we live' from 'vivir'?",
              options: ["vivimos", "vivemos", "viváis", "viven"],
              correct: 0,
              fb: "-ir verbs: nosotros form is -imos. vivimos.",
            },
          ],
        },
        {
          type: "tip",
          heading: "Tener for age and possession",
          body: "Spanish uses <em>tener</em> (to have) where English uses <em>be</em> for age. <em>Tengo treinta años</em> = \"I'm thirty (I have thirty years).\" Tener is also the everyday verb for possession: <em>Tengo dos hermanos</em> = \"I have two brothers.\" It's irregular: <strong>tengo, tienes, tiene, tenemos, tenéis, tienen</strong>.",
          example: { l1: "Tengo treinta años y tengo un perro.", en: "I'm thirty and I have a dog." },
        },
        {
          type: "conjugation",
          heading: "tener (to have) — irregular",
          verb: "tener",
          meaning: "to have (age, possession)",
          intro: "Note the e→ie stem change in tú, él, ellos, and the irregular yo form.",
          tenses: [{ name: "Presente", forms: [
            { person: "yo", form: "tengo", en: "I have" },
            { person: "tú", form: "tienes", en: "you have" },
            { person: "él/ella/usted", form: "tiene", en: "he/she has" },
            { person: "nosotros", form: "tenemos", en: "we have" },
            { person: "vosotros", form: "tenéis", en: "you all have" },
            { person: "ellos/ustedes", form: "tienen", en: "they have" },
          ] }],
        },
        {
          type: "orderWords",
          heading: "Build the sentence",
          intro: "Drag the words into a natural Spanish order.",
          items: [
            { tokens: ["Tengo", "veinticinco", "años"], en: "I'm twenty-five years old." },
            { tokens: ["¿Cuántos", "años", "tienes?"], en: "How old are you?" },
            { tokens: ["Mi", "hermano", "tiene", "un", "coche"], en: "My brother has a car." },
            { tokens: ["Necesito", "un", "taxi", "ahora"], en: "I need a taxi now." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it — verbs in action",
          direction: "en-to-l1",
          prompt: "I live in Barcelona and I work in a restaurant.",
          reference: "Vivo en Barcelona y trabajo en un restaurante.",
          hint: "vivir → vivo (-ir). trabajar → trabajo (-ar). Drop the 'I'.",
        },
      ],
    },
    {
      slug: "ser-estar-complex",
      title: "Ser and estar — tricky cases",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "When both ser and estar are possible — with different meanings",
          body: [
            "Some adjectives can go with either verb but mean something different. <em>Es aburrido</em> = he's a boring person (character). <em>Está aburrido</em> = he's bored right now (state). <em>Es malo</em> = he's bad/evil. <em>Está malo</em> = he's ill.",
            "Location is almost always <em>estar</em> — but not for events! <em>La fiesta es en el jardín</em> = the party is (takes place) in the garden. The location of an event uses <em>ser</em>.",
          ],
          keyPoint: "Character/identity → ser. Current state → estar. Events: ser. Location of things: estar.",
        },
        {
          type: "vocab",
          heading: "Adjectives that change meaning with ser/estar",
          items: [
            { l1: "es aburrido / está aburrido", en: "he's boring (character) / he's bored (now)" },
            { l1: "es malo / está malo", en: "he's evil/bad / he's ill" },
            { l1: "es bueno / está bueno", en: "he's good (character) / it tastes good (food)" },
            { l1: "es listo / está listo", en: "he's clever / he's ready" },
            { l1: "es seguro / está seguro", en: "it's safe / he's sure/certain" },
            { l1: "es vivo / está vivo", en: "he's sharp/clever / he's alive" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Ser or estar — tricky cases",
          questions: [
            {
              q: "'La conferencia es en Madrid' uses ser because…",
              options: ["Madrid is a city", "It's the location of an event", "Conferencia is feminine", "It's a permanent fact"],
              correct: 1,
              fb: "The location of events and meetings uses ser, not estar.",
            },
            {
              q: "'Está listo' means…",
              options: ["He's clever", "He's ready", "He's tired", "It's done"],
              correct: 1,
              fb: "Listo with estar = ready. Listo with ser = clever/smart.",
            },
          ],
        },
        {
          type: "dialogue",
          heading: "Putting it together",
          setup: "Two travelers meet at a hostel in Madrid.",
          lines: [
            { speaker: "Lucía", l1: "Hola, ¿cómo te llamas?", en: "Hi, what's your name?" },
            { speaker: "You", l1: "Me llamo Tom. Soy americano. ¿Y tú?", en: "I'm Tom. I'm American. And you?" },
            { speaker: "Lucía", l1: "Soy Lucía, soy de Valencia. ¿Cuántos años tienes?", en: "I'm Lucía, I'm from Valencia. How old are you?" },
            { speaker: "You", l1: "Tengo veintiocho años. Estoy un poco cansado del viaje.", en: "I'm twenty-eight. I'm a bit tired from the trip." },
            { speaker: "Lucía", l1: "¡Hablas muy bien el español! ¿Dónde estás ahora, en un hotel?", en: "You speak Spanish really well! Where are you staying now, in a hotel?" },
            { speaker: "You", l1: "No, estoy aquí en el hostal. Es muy barato y está cerca del centro.", en: "No, I'm here at the hostel. It's very cheap and it's near the center." },
          ],
        },
        {
          type: "translate",
          heading: "Final translation challenge",
          direction: "en-to-l1",
          prompt: "I'm twenty-eight years old, I'm from New York, and I'm a bit tired today.",
          reference: "Tengo veintiocho años, soy de Nueva York y hoy estoy un poco cansado.",
          hint: "Age → tener. Origin → ser. A temporary feeling like 'tired' → estar.",
        },
      ],
    }
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "'I'm from Spain' uses…", options: ["estoy", "soy", "es", "estás"], correct: 1 },
      { q: "'He's tired' uses…", options: ["es", "son", "está", "estoy"], correct: 2 },
      { q: "'It's three o'clock' uses…", options: ["están", "estoy", "son", "somos"], correct: 2 },
      { q: "The yo form of 'comer' is…", options: ["comes", "come", "como", "comemos"], correct: 2 },
      { q: "The nosotros form of 'hablar' is…", options: ["hablan", "habláis", "hablamos", "hablamos"], correct: 2 },
      { q: "'The library is on the corner' uses…", options: ["ser", "estar", "Either", "Neither"], correct: 1 },
      { q: "Profession/identity uses which verb?", options: ["estar", "ser", "tener", "haber"], correct: 1 },
      { q: "What is 'you (tú) speak'?", options: ["hablo", "habla", "hablas", "habláis"], correct: 2 },
      { q: "The ellos form of 'vivir' is…", options: ["vivimos", "vivís", "viven", "vive"], correct: 2 },
      { q: "'Snow is white' (permanent quality) uses…", options: ["está", "es", "son", "estás"], correct: 1 },
      { q: "'I'm 25 years old' uses…", options: ["Soy veinticinco", "Estoy veinticinco años", "Tengo veinticinco años", "Es veinticinco años"], correct: 2 },
      { q: "The yo form of 'tener' is…", options: ["teno", "tiengo", "tengo", "tiene"], correct: 2 },
    ],
  },
};
