import type { Unit } from "../../types";

export const UNIT_PRETERITO_INDEFINIDO: Unit = {
  slug: "preterito-indefinido",
  stage: 5,
  order: 21,
  icon: "📅",
  title: "Pretérito indefinido",
  tagline: "Comí, fui, estuve — completed past actions.",
  lessons: [
    {
      slug: "preterito-indefinido-regular",
      title: "Regular indefinido",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The simple past — completed actions",
          body: [
            "The pretérito indefinido expresses completed actions at a specific point in the past: 'I ate', 'she went', 'we visited'. Unlike the perfecto (which implies a link to now), the indefinido sees the action as fully finished.",
            "In Latin America this is the main past tense. In Spain it's used for more distant events (yesterday, last year) while the perfecto handles recent events.",
          ],
          keyPoint: "-ar: -é/-aste/-ó/-amos/-asteis/-aron · -er/-ir: -í/-iste/-ió/-imos/-isteis/-ieron",
        },
        {
          type: "conjugation",
          heading: "hablar — pretérito indefinido",
          verb: "hablar",
          meaning: "to speak",
          tenses: [{ name: "Pretérito indefinido", forms: [
            { person: "yo", form: "hablé" },
            { person: "tú", form: "hablaste" },
            { person: "él/ella/usted", form: "habló" },
            { person: "nosotros", form: "hablamos" },
            { person: "vosotros", form: "hablasteis" },
            { person: "ellos/ustedes", form: "hablaron" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "comer — pretérito indefinido",
          verb: "comer",
          meaning: "to eat",
          tenses: [{ name: "Pretérito indefinido", forms: [
            { person: "yo", form: "comí" },
            { person: "tú", form: "comiste" },
            { person: "él/ella/usted", form: "comió" },
            { person: "nosotros", form: "comimos" },
            { person: "vosotros", form: "comisteis" },
            { person: "ellos/ustedes", form: "comieron" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "vivir — pretérito indefinido",
          verb: "vivir",
          meaning: "to live",
          intro: "Good news: -er and -ir verbs share identical endings in the indefinido.",
          tenses: [{ name: "Pretérito indefinido", forms: [
            { person: "yo", form: "viví" },
            { person: "tú", form: "viviste" },
            { person: "él/ella/usted", form: "vivió" },
            { person: "nosotros", form: "vivimos" },
            { person: "vosotros", form: "vivisteis" },
            { person: "ellos/ustedes", form: "vivieron" },
          ] }],
        },
        {
          type: "tip",
          heading: "Watch the accents — they carry the meaning",
          body: "In regular verbs only the <em>yo</em> and <em>él/ella</em> forms take a written accent, and that accent is the whole difference between past and present. <em>Hablo</em> = I speak, but <em>habló</em> = he spoke. <em>Hablo</em> vs <em>hablé</em>: present vs I-spoke. Drop the accent and you change the tense (or the person). Note too that the <em>nosotros</em> form of -ar and -ir verbs (<em>hablamos</em>, <em>vivimos</em>) is identical to the present — context tells you which.",
          example: { l1: "Hablo con María. / Ayer hablé con María.", en: "I speak with María. / Yesterday I spoke with María." },
        },
        {
          type: "fillBlank",
          heading: "Conjugate the regular verb",
          intro: "Type the pretérito indefinido form for the subject given.",
          items: [
            {
              template: "Ayer (yo) ___ con mi jefe. (hablar)",
              answer: "hablé",
              en: "Yesterday I spoke with my boss.",
              options: ["hablo", "hablé", "habló", "hablaba"],
            },
            {
              template: "Ella ___ una manzana. (comer)",
              answer: "comió",
              en: "She ate an apple.",
              options: ["come", "comió", "comí", "comía"],
            },
            {
              template: "Nosotros ___ en Sevilla dos años. (vivir)",
              answer: "vivimos",
              en: "We lived in Seville for two years.",
              options: ["vivimos", "vivíamos", "vivís", "viviremos"],
            },
            {
              template: "Ellos ___ toda la noche. (bailar)",
              answer: "bailaron",
              en: "They danced all night.",
              options: ["bailan", "bailaron", "bailaban", "bailarán"],
            },
            {
              template: "¿Tú ___ la película? (ver)",
              answer: "viste",
              en: "Did you watch the film?",
              options: ["ves", "viste", "veías", "verás"],
            },
          ],
        },
        {
          type: "vocab",
          heading: "Irregular indefinido — the essential three",
          items: [
            { l1: "ser/ir → fui, fuiste, fue, fuimos, fuisteis, fueron", en: "to be / to go (same forms!)" },
            { l1: "tener → tuve, tuviste, tuvo, tuvimos, tuvisteis, tuvieron", en: "to have" },
            { l1: "estar → estuve, estuviste, estuvo, estuvimos, estuvisteis, estuvieron", en: "to be (location/state)" },
            { l1: "hacer → hice, hiciste, hizo, hicimos, hicisteis, hicieron", en: "to do / to make" },
            { l1: "venir → vine, viniste, vino, vinimos, vinisteis, vinieron", en: "to come" },
            { l1: "poder → pude, pudiste, pudo, pudimos, pudisteis, pudieron", en: "to be able to" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Indefinido check",
          questions: [
            {
              q: "'Ayer comí en un restaurante' means…",
              options: ["Yesterday I'm eating at a restaurant", "Yesterday I ate at a restaurant", "I used to eat at a restaurant", "I have eaten at a restaurant"],
              correct: 1,
              fb: "Ayer = yesterday. Comí = I ate (indefinido). Ayer comí = yesterday I ate.",
            },
            {
              q: "Ser and ir share the same indefinido forms. 'Fue' can mean…",
              options: ["He was OR he went", "He was (only)", "He went (only)", "He has been"],
              correct: 0,
              fb: "Fue can mean 'he was' or 'he went' — context clarifies meaning.",
            },
            {
              q: "What is 'we did' (hacer)?",
              options: ["hicemos", "hicimos", "haciamos", "hacemos"],
              correct: 1,
              fb: "Hacer, nosotros indefinido: hicimos. Note: hizo (3rd sing.) has a z not a c.",
            },
            {
              q: "Which form means 'he spoke'?",
              options: ["hablo", "hablé", "habló", "hablaba"],
              correct: 2,
              fb: "habló (with the accent on the o) = he/she spoke. hablo = I speak (present).",
            },
            {
              q: "The nosotros indefinido of -er/-ir verbs ends in…",
              options: ["-amos", "-imos", "-ieron", "-ió"],
              correct: 1,
              fb: "comimos, vivimos — both end in -imos.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Yesterday I ate at home and watched a film.",
          reference: "Ayer comí en casa y vi una película.",
          hint: "comí (comer) + vi (ver) — both indefinido. 'Vi' has no accent (it's one syllable).",
        },
      ],
    },
    {
      slug: "preterito-indefinido-irregulares",
      title: "The irregular preterites",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "A whole family with one set of endings",
          body: [
            "A core group of very common verbs is irregular in the indefinido. The good news: they all share <strong>one</strong> set of endings — and crucially, those endings carry <strong>no accent marks</strong>.",
            "The pattern: <strong>-e, -iste, -o, -imos, -isteis, -ieron</strong>. Compare <em>hablé / habló</em> (regular, accented) with <em>tuve / tuvo</em> (irregular, no accent). The trick is learning each verb's new stem; the endings then come for free.",
            "Two stand out: <strong>ser</strong> and <strong>ir</strong> are completely irregular and, oddly, share the exact same forms — <em>fui, fuiste, fue, fuimos, fuisteis, fueron</em>. Context tells them apart.",
          ],
          keyPoint: "Irregular endings (no accents): -e, -iste, -o, -imos, -isteis, -ieron. Learn the stem (tuv-, estuv-, hic-, vin-, dij-, pud-, pus-, quis-).",
        },
        {
          type: "conjugation",
          heading: "tener — pretérito indefinido (irregular)",
          verb: "tener",
          meaning: "to have",
          intro: "New stem tuv-, then the irregular endings. Note: no written accents anywhere.",
          tenses: [{ name: "Pretérito indefinido", forms: [
            { person: "yo", form: "tuve", en: "I had" },
            { person: "tú", form: "tuviste", en: "you had" },
            { person: "él/ella/usted", form: "tuvo", en: "he/she had" },
            { person: "nosotros", form: "tuvimos", en: "we had" },
            { person: "vosotros", form: "tuvisteis", en: "you all had" },
            { person: "ellos/ustedes", form: "tuvieron", en: "they had" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "ir / ser — pretérito indefinido (identical forms)",
          verb: "ir / ser",
          meaning: "to go / to be",
          intro: "Two verbs, one set of forms. 'Fui a Madrid' = I went; 'Fui profesor' = I was a teacher.",
          tenses: [{ name: "Pretérito indefinido", forms: [
            { person: "yo", form: "fui", en: "I went / I was" },
            { person: "tú", form: "fuiste", en: "you went / you were" },
            { person: "él/ella/usted", form: "fue", en: "he went / he was" },
            { person: "nosotros", form: "fuimos", en: "we went / we were" },
            { person: "vosotros", form: "fuisteis", en: "you all went / were" },
            { person: "ellos/ustedes", form: "fueron", en: "they went / were" },
          ] }],
        },
        {
          type: "vocab",
          heading: "More irregular stems to know",
          intro: "Each stem just takes the irregular endings (-e, -iste, -o, -imos, -isteis, -ieron).",
          items: [
            { l1: "estar → estuv- (estuve, estuviste, estuvo…)", en: "to be (location/state)" },
            { l1: "hacer → hic- (hice, hiciste, hizo…)", en: "to do / make", note: "hizo with z, not c" },
            { l1: "decir → dij- (dije, dijiste, dijo, dijeron)", en: "to say", note: "j-stems drop the i: dijeron, not dijieron" },
            { l1: "venir → vin- (vine, viniste, vino…)", en: "to come" },
            { l1: "poner → pus- (puse, pusiste, puso…)", en: "to put" },
            { l1: "querer → quis- (quise, quisiste, quiso…)", en: "to want" },
            { l1: "poder → pud- (pude, pudiste, pudo…)", en: "to be able to" },
            { l1: "dar → di, diste, dio, dimos, disteis, dieron", en: "to give", note: "takes -er/-ir endings, no accents" },
          ],
        },
        {
          type: "tip",
          heading: "The j-stem shortcut",
          body: "When the irregular stem ends in <em>j</em> (decir → dij-, traer → traj-, conducir → conduj-), the <em>ellos</em> ending loses its i: it's <em>-eron</em>, not <em>-ieron</em>. So <em>dijeron</em> (they said), <em>trajeron</em> (they brought), <em>condujeron</em> (they drove) — never 'dijieron'.",
          example: { l1: "Me dijeron la verdad.", en: "They told me the truth." },
        },
        {
          type: "fillBlank",
          heading: "Pick the irregular form",
          items: [
            {
              template: "(Yo) ___ que venir pronto. (tener)",
              answer: "tuve",
              en: "I had to come early.",
              options: ["tení", "tuve", "tuvo", "tenía"],
            },
            {
              template: "Ella ___ a la fiesta. (ir)",
              answer: "fue",
              en: "She went to the party.",
              options: ["fui", "fue", "iba", "fuera"],
            },
            {
              template: "Ellos no ___ nada. (decir)",
              answer: "dijeron",
              en: "They didn't say anything.",
              options: ["dijieron", "dijeron", "decían", "dijon"],
            },
            {
              template: "Nosotros ___ en Roma una semana. (estar)",
              answer: "estuvimos",
              en: "We were in Rome for a week.",
              options: ["estábamos", "estuvimos", "estamos", "estuvieron"],
            },
            {
              template: "¿Qué ___ tú el sábado? (hacer)",
              answer: "hiciste",
              en: "What did you do on Saturday?",
              options: ["hacías", "hiciste", "hizo", "haces"],
            },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Irregular preterite check",
          questions: [
            {
              q: "Why does 'tuve' have no accent while 'hablé' does?",
              options: ["A typo — it should have one", "Irregular preterites stress the stem, not the ending", "Accents are optional in Spanish", "tuve is present tense"],
              correct: 1,
              fb: "Irregular (strong) preterites pull the stress onto the stem, so the yo/él forms are unaccented: tuve, tuvo, hice, hizo, vine, vino.",
            },
            {
              q: "What is 'they brought' (traer → traj-)?",
              options: ["trajieron", "trajeron", "trayeron", "traieron"],
              correct: 1,
              fb: "j-stems drop the i in the ellos ending: trajeron.",
            },
            {
              q: "'Fuimos al cine' means…",
              options: ["We go to the cinema", "We went to the cinema", "We were going to the cinema", "We will go to the cinema"],
              correct: 1,
              fb: "fuimos = we went (or we were). Here 'al cine' signals motion → we went.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I couldn't sleep, so I made coffee and put on some music.",
          reference: "No pude dormir, así que hice café y puse música.",
          hint: "pude (poder), hice (hacer), puse (poner) — three irregular stems, no accents.",
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "l1-to-en",
          prompt: "Ayer fue un día difícil: tuve tres reuniones y no tuve tiempo de comer.",
          reference: "Yesterday was a hard day: I had three meetings and I didn't have time to eat.",
          hint: "fue (ser, here 'was') + tuve / tuve (tener).",
        },
      ],
    },
    {
      slug: "preterito-indefinido-time",
      title: "Time expressions with indefinido",
      estMinutes: 7,
      pages: [
        {
          type: "vocab",
          heading: "Time markers for the indefinido",
          items: [
            { l1: "ayer", en: "yesterday" },
            { l1: "anteayer", en: "the day before yesterday" },
            { l1: "la semana pasada", en: "last week" },
            { l1: "el año pasado", en: "last year" },
            { l1: "el lunes pasado", en: "last Monday" },
            { l1: "en 2020", en: "in 2020" },
            { l1: "hace dos días", en: "two days ago" },
            { l1: "hace un año", en: "a year ago" },
          ],
        },
        {
          type: "vocab",
          heading: "Indefinido in context",
          items: [
            { l1: "El año pasado fui a Barcelona.", en: "Last year I went to Barcelona." },
            { l1: "Ayer no pude dormir.", en: "Yesterday I couldn't sleep." },
            { l1: "¿Dónde estuviste el fin de semana?", en: "Where were you at the weekend?" },
            { l1: "Hace dos años viví en Madrid.", en: "Two years ago I lived in Madrid." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Time expressions",
          questions: [
            {
              q: "'Hace dos años' means…",
              options: ["In two years", "Two years ago", "For two years", "Two years from now"],
              correct: 1,
              fb: "Hace + time + que/verb = ago. Hace dos años fui a España = two years ago I went to Spain.",
            },
            {
              q: "'El año pasado' means…",
              options: ["Next year", "This year", "Last year", "Every year"],
              correct: 2,
              fb: "Pasado = past. El año pasado = last year.",
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the sentence",
          intro: "Put the words in order. Each one anchors a past action with a time marker.",
          items: [
            { tokens: ["La", "semana", "pasada", "fui", "al", "médico"], en: "Last week I went to the doctor." },
            { tokens: ["Hace", "dos", "años", "viví", "en", "México"], en: "Two years ago I lived in Mexico." },
            { tokens: ["Ayer", "no", "tuve", "tiempo"], en: "Yesterday I didn't have time." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Last summer we traveled to Argentina.",
          reference: "El verano pasado viajamos a Argentina.",
          hint: "viajamos (viajar, nosotros). 'El verano pasado' = last summer.",
        },
      ],
    },
    {
      slug: "preterito-indefinido-narrative",
      title: "Telling a story in the past",
      estMinutes: 8,
      pages: [
        {
          type: "dialogue",
          heading: "What did you do last weekend?",
          lines: [
            { speaker: "Lucía", l1: "¿Qué hiciste el fin de semana?", en: "What did you do at the weekend?" },
            { speaker: "Carlos", l1: "Fui a Segovia con unos amigos.", en: "I went to Segovia with some friends." },
            { speaker: "Lucía", l1: "¿Y qué visitasteis?", en: "And what did you visit?" },
            { speaker: "Carlos", l1: "El acueducto romano, claro. También comimos cochinillo.", en: "The Roman aqueduct, of course. We also ate suckling pig." },
            { speaker: "Lucía", l1: "¡Qué envidia! ¿Cuándo volvisteis?", en: "How jealous! When did you come back?" },
            { speaker: "Carlos", l1: "El domingo por la noche. Llegué a casa agotado.", en: "Sunday night. I arrived home exhausted." },
          ],
        },
        {
          type: "vocab",
          heading: "Useful time expressions with indefinido",
          items: [
            { l1: "el fin de semana pasado", en: "last weekend" },
            { l1: "el verano pasado", en: "last summer" },
            { l1: "de pequeño / cuando era niño/a", en: "as a child" },
            { l1: "en aquella época", en: "in those days / at that time" },
            { l1: "al día siguiente", en: "the next day" },
            { l1: "de repente", en: "suddenly" },
          ],
        },
        {
          type: "translate",
          heading: "Translate this past tense sentence",
          direction: "en-to-l1",
          prompt: "Last year I went to Barcelona and ate paella.",
          reference: "El año pasado fui a Barcelona y comí paella.",
          hint: "fui (ir) + comí (comer) — both indefinido",
        },
        {
          type: "orderWords",
          heading: "Reconstruct the story",
          intro: "Each line is one step in a weekend narration.",
          items: [
            { tokens: ["El", "sábado", "fui", "a", "la", "playa"], en: "On Saturday I went to the beach." },
            { tokens: ["Comimos", "en", "un", "restaurante", "del", "puerto"], en: "We ate at a restaurant by the harbor." },
            { tokens: ["De", "repente", "empezó", "a", "llover"], en: "Suddenly it started to rain." },
            { tokens: ["Volví", "a", "casa", "muy", "cansado"], en: "I came back home very tired." },
          ],
        },
        {
          type: "tip",
          heading: "Spelling change in the yo form: -car, -gar, -zar",
          body: "To keep the sound, verbs ending in <em>-car / -gar / -zar</em> change spelling in the <em>yo</em> form only. <em>-car → -qué</em> (buscar → busqué), <em>-gar → -gué</em> (llegar → llegué), <em>-zar → -cé</em> (empezar → empecé). All other forms stay regular.",
          example: { l1: "Llegué tarde y empecé a trabajar enseguida.", en: "I arrived late and started working right away." },
        },
        {
          type: "fillBlank",
          heading: "Spelling-change yo forms",
          items: [
            {
              template: "(Yo) ___ las llaves toda la mañana. (buscar)",
              answer: "busqué",
              en: "I looked for the keys all morning.",
              options: ["busé", "buscé", "busqué", "buscó"],
            },
            {
              template: "(Yo) ___ a las nueve. (llegar)",
              answer: "llegué",
              en: "I arrived at nine.",
              options: ["llegé", "llegué", "llegó", "llegaba"],
            },
            {
              template: "(Yo) ___ a estudiar español. (empezar)",
              answer: "empecé",
              en: "I started to study Spanish.",
              options: ["empezé", "empecé", "empezó", "empiezo"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I arrived home, made dinner, and called my mother.",
          reference: "Llegué a casa, hice la cena y llamé a mi madre.",
          hint: "Llegué (spelling change!), hice (hacer, irregular), llamé (llamar).",
        },
      ],
    }
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "The yo form of hablar (indefinido) is…", options: ["hablé", "hablo", "habló", "hablaba"], correct: 0 },
      { q: "The yo form of comer (indefinido) is…", options: ["comé", "como", "comí", "comía"], correct: 2 },
      { q: "'Fue' can mean…", options: ["was OR went", "was only", "went only", "has been"], correct: 0 },
      { q: "The yo form of hacer (indefinido) is…", options: ["hacé", "hice", "hizo", "hacía"], correct: 1 },
      { q: "'Ayer' means…", options: ["today", "tomorrow", "yesterday", "last week"], correct: 2 },
      { q: "'Hace dos días' means…", options: ["For two days", "In two days", "Two days ago", "Two days later"], correct: 2 },
      { q: "'La semana pasada' means…", options: ["next week", "this week", "every week", "last week"], correct: 3 },
      { q: "'Ellos hablaron' means…", options: ["They were speaking", "They speak", "They spoke", "They will speak"], correct: 2 },
      { q: "'Estuve en Madrid' means…", options: ["I am in Madrid", "I was in Madrid", "I will be in Madrid", "I have been in Madrid"], correct: 1 },
      { q: "Regular -ar indefinido: 3rd person plural ends in…", options: ["-ó", "-aron", "-eron", "-aron o -eron"], correct: 1 },
      { q: "'They said' (decir) is…", options: ["dijieron", "dijeron", "decieron", "dicieron"], correct: 1 },
      { q: "The yo form of 'llegar' (indefinido) is…", options: ["llegé", "llegué", "llegó", "llegaba"], correct: 1 },
      { q: "Irregular preterites (tuve, hice, vine) take which endings?", options: ["-é, -aste, -ó…", "-e, -iste, -o… (no accents)", "-aba, -abas, -aba…", "-aré, -arás…"], correct: 1 },
    ],
  },
};
