import type { Unit } from "../../types";

export const UNIT_IMPERFECTO: Unit = {
  slug: "imperfecto",
  stage: 5,
  order: 22,
  icon: "🌅",
  title: "Imperfecto",
  tagline: "Cuando era niño… — habitual and descriptive past.",
  badge: "core",
  lessons: [
    {
      slug: "imperfecto-intro",
      title: "The imperfecto — ongoing and habitual past",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "The imperfecto — painting the past",
          body: [
            "While the indefinido stamps past events as completed, the imperfecto paints an ongoing situation, a habitual action, or a background description. Think of it as the 'used to' or 'was/were -ing' tense.",
            "Key uses: habitual actions in the past (<em>De niño comía mucho</em> = As a child I used to eat a lot), background descriptions (<em>Hacía frío</em> = It was cold), and ongoing actions interrupted by another event.",
          ],
          keyPoint: "-ar: -aba/-abas/-aba/-ábamos/-abais/-aban · -er/-ir: -ía/-ías/-ía/-íamos/-íais/-ían",
        },
        {
          type: "conjugation",
          heading: "hablar — imperfecto",
          verb: "hablar",
          meaning: "to speak",
          tenses: [{ name: "Imperfecto", forms: [
            { person: "yo", form: "hablaba" },
            { person: "tú", form: "hablabas" },
            { person: "él/ella/usted", form: "hablaba" },
            { person: "nosotros", form: "hablábamos" },
            { person: "vosotros", form: "hablabais" },
            { person: "ellos/ustedes", form: "hablaban" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "comer — imperfecto",
          verb: "comer",
          meaning: "to eat",
          tenses: [{ name: "Imperfecto", forms: [
            { person: "yo", form: "comía" },
            { person: "tú", form: "comías" },
            { person: "él/ella/usted", form: "comía" },
            { person: "nosotros", form: "comíamos" },
            { person: "vosotros", form: "comíais" },
            { person: "ellos/ustedes", form: "comían" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "vivir — imperfecto",
          verb: "vivir",
          meaning: "to live",
          intro: "-ir verbs share the exact same endings as -er verbs.",
          tenses: [{ name: "Imperfecto", forms: [
            { person: "yo", form: "vivía" },
            { person: "tú", form: "vivías" },
            { person: "él/ella/usted", form: "vivía" },
            { person: "nosotros", form: "vivíamos" },
            { person: "vosotros", form: "vivíais" },
            { person: "ellos/ustedes", form: "vivían" },
          ] }],
        },
        {
          type: "tip",
          heading: "Two endings cover everything",
          body: "Spanish has just <em>two</em> sets of imperfecto endings. <strong>-ar</strong> verbs take <strong>-aba</strong> endings; <strong>-er and -ir</strong> verbs share the <strong>-ía</strong> endings. Notice the written accents: every -ía form carries one, and the -ar nosotros form (<em>-ábamos</em>) does too. No avoiding accents here — <em>hablábamos, comíamos, vivíamos</em>.",
          example: { l1: "Antes trabajaba en Madrid, pero vivía en las afueras.", en: "Back then I worked in Madrid, but I lived in the suburbs." },
        },
        {
          type: "vocab",
          heading: "Only 3 irregular imperfectos",
          intro: "Out of every Spanish verb, only these three are irregular in the imperfecto — memorize them and the rest are fully predictable.",
          items: [
            { l1: "ser → era, eras, era, éramos, erais, eran", en: "to be (identity)" },
            { l1: "ir → iba, ibas, iba, íbamos, ibais, iban", en: "to go" },
            { l1: "ver → veía, veías, veía, veíamos, veíais, veían", en: "to see" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Conjugate the imperfecto",
          intro: "Pick the imperfecto form — watch the accents.",
          items: [
            {
              template: "Cuando era niño, ___ mucho con mis primos. (jugar)",
              answer: "jugaba",
              en: "When I was a child, I used to play a lot with my cousins.",
              options: ["juego", "jugaba", "jugué", "jugaría"],
            },
            {
              template: "Marta ___ el periódico cada mañana. (leer)",
              answer: "leía",
              en: "Marta used to read the newspaper every morning.",
              options: ["lee", "leía", "leyó", "leería"],
            },
            {
              template: "Nosotros ___ en el centro de Sevilla. (vivir)",
              answer: "vivíamos",
              en: "We used to live in the center of Seville.",
              options: ["vivíamos", "vivimos", "vivían", "vivíais"],
            },
            {
              template: "De pequeña, yo ___ tímida. (ser)",
              answer: "era",
              en: "As a little girl, I was shy.",
              options: ["fui", "era", "soy", "estaba"],
            },
            {
              template: "Los domingos ___ a casa de la abuela. (ir, nosotros)",
              answer: "íbamos",
              en: "On Sundays we used to go to grandma's house.",
              options: ["fuimos", "íbamos", "vamos", "iban"],
            },
            {
              template: "Desde la ventana ___ el mar. (ver, yo)",
              answer: "veía",
              en: "From the window I could see the sea.",
              options: ["vi", "veía", "veo", "vería"],
            },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Imperfecto check",
          questions: [
            {
              q: "'Cuando era niño, vivía en Madrid' means…",
              options: ["When I was a child, I lived (habitually) in Madrid", "When I was a child, I went to Madrid once", "When I will be a child", "Living in Madrid as a child was temporary"],
              correct: 0,
              fb: "Era (imperfecto of ser) + vivía (imperfecto of vivir) = habitual past situation.",
            },
            {
              q: "The imperfecto is used for…",
              options: ["Completed actions at a specific time", "Habitual actions in the past / background descriptions", "Future plans", "Commands"],
              correct: 1,
              fb: "Indefinido = completed actions. Imperfecto = habitual/descriptive past.",
            },
          ],
        },
      ],
    },
    {
      slug: "imperfecto-contrast",
      title: "Imperfecto vs indefinido",
      estMinutes: 11,
      pages: [
        {
          type: "intro",
          heading: "Together in the same story",
          body: [
            "The two past tenses often appear together in narratives: the imperfecto sets the scene and background while the indefinido provides the foreground events.",
            "<em>Hacía mucho calor cuando llegué a Sevilla.</em> = It was very hot (background, imperfecto) when I arrived in Seville (event, indefinido).",
          ],
          keyPoint: "Imperfecto = background/scene. Indefinido = events/plot.",
        },
        {
          type: "vocab",
          heading: "Contrast in action",
          items: [
            { l1: "Leía cuando sonó el teléfono.", en: "I was reading when the phone rang." },
            { l1: "Todos los días iba al mercado.", en: "Every day I used to go to the market." },
            { l1: "Ayer fui al mercado.", en: "Yesterday I went to the market (once)." },
            { l1: "Era joven y vivía en Madrid.", en: "I was young and lived in Madrid. (description)" },
            { l1: "De pequeño comía mucha tortilla.", en: "As a child I used to eat lots of tortilla." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Which tense?",
          questions: [
            {
              q: "'I was reading when he arrived' — 'was reading' uses…",
              options: ["indefinido", "imperfecto", "perfecto", "presente"],
              correct: 1,
              fb: "The ongoing background action (reading) uses imperfecto. The arrival is indefinido.",
            },
            {
              q: "'Every summer we went to the beach' — 'went' uses…",
              options: ["indefinido", "imperfecto", "perfecto", "presente"],
              correct: 1,
              fb: "Habitual repeated action = imperfecto. Todos los veranos íbamos a la playa.",
            },
          ],
        },
        {
          type: "tip",
          heading: "Imperfecto vs indefinido — the decisive test",
          body: "Ask yourself one thing: <strong>was it a single, finished action with a clear endpoint?</strong> → indefinido (<em>comí una paella</em>). <strong>Was it a state, a description, a habit, or what was going on in the background?</strong> → imperfecto (<em>comía paella a menudo</em>). The same verb feels completely different:<br><br>• <em>Ayer comí paella.</em> = Yesterday I ate paella. (one event)<br>• <em>De niño comía paella todos los domingos.</em> = As a child I used to eat paella every Sunday. (habit)",
        },
        {
          type: "vocab",
          heading: "Signal words for the imperfecto",
          intro: "These markers strongly point to the imperfecto — repetition, habit, or duration.",
          items: [
            { l1: "a menudo", en: "often" },
            { l1: "siempre", en: "always" },
            { l1: "normalmente", en: "usually" },
            { l1: "todos los días / todos los veranos", en: "every day / every summer" },
            { l1: "mientras", en: "while" },
            { l1: "de niño/a", en: "as a child" },
            { l1: "en aquella época", en: "in those days" },
            { l1: "antes", en: "before / back then" },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the mixed-tense sentence",
          intro: "Background in the imperfecto, the event in the indefinido.",
          items: [
            { tokens: ["Mientras", "leía", ",", "sonó", "el", "teléfono"], alts: [["Mientras", "leía", ",", "el", "teléfono", "sonó"]], en: "While I was reading, the phone rang." },
            { tokens: ["Cuando", "era", "pequeño", ",", "vivía", "en", "Valencia"], en: "When I was little, I lived in Valencia." },
            { tokens: ["Llovía", ",", "pero", "salimos", "a", "pasear"], en: "It was raining, but we went out for a walk." },
            { tokens: ["Hacía", "calor", ",", "así", "que", "fuimos", "a", "la", "playa"], en: "It was hot, so we went to the beach." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "It was cold and I was tired, so I stayed home.",
          reference: "Hacía frío y estaba cansado/a, así que me quedé en casa.",
          hint: "Weather + state = imperfecto (hacía, estaba). The decision to stay is a single event = indefinido (me quedé).",
        },
      ],
    },
    {
      slug: "imperfecto-childhood",
      title: "Childhood memories",
      estMinutes: 11,
      pages: [
        {
          type: "vocab",
          heading: "Talking about your childhood",
          items: [
            { l1: "De pequeño/a…", en: "As a child… (when I was small)" },
            { l1: "Cuando era niño/a…", en: "When I was a child…" },
            { l1: "Solía + infinitive", en: "I used to… (habitual action)" },
            { l1: "Vivíamos en…", en: "We used to live in…" },
            { l1: "Todos los veranos íbamos a…", en: "Every summer we went to…" },
            { l1: "Mi abuela siempre hacía…", en: "My grandmother always used to make…" },
          ],
        },
        {
          type: "dialogue",
          heading: "Childhood memories",
          lines: [
            { speaker: "Elena", l1: "¿Dónde vivías de pequeña?", en: "Where did you live as a child?" },
            { speaker: "Sara", l1: "Vivía en un pueblo pequeño en Galicia. Éramos seis en casa.", en: "I lived in a small village in Galicia. There were six of us at home." },
            { speaker: "Elena", l1: "¿Cómo era la vida allí?", en: "What was life like there?" },
            { speaker: "Sara", l1: "Muy tranquila. Jugábamos en la calle hasta que oscurecía.", en: "Very quiet. We used to play in the street until it got dark." },
            { speaker: "Elena", l1: "¡Qué bonito!", en: "How lovely!" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Childhood imperfecto",
          questions: [
            {
              q: "'Solía ir al cine los sábados' means…",
              options: ["I went to the cinema one Saturday", "I used to go to the cinema on Saturdays", "I'm going to the cinema Saturday", "I should go to the cinema"],
              correct: 1,
              fb: "Soler + infinitive in imperfecto = used to. Solía ir = I used to go.",
            },
            {
              q: "'¿Cómo era la vida allí?' is asking about…",
              options: ["A single event", "The ongoing character of life there", "Future plans", "A specific day"],
              correct: 1,
              fb: "Era (imperfecto of ser) = was (ongoing state). Asking about the general character of life.",
            },
          ],
        },
        {
          type: "intro",
          heading: "Real Spanish narration uses both tenses at once",
          body: [
            "When you tell a story in Spanish, the two past tenses work together: the imperfecto sets the scene, and the indefinido drops in the events.",
            "<em>Era una tarde tranquila. Llovía desde hacía horas. Yo leía en el sofá cuando, de repente, sonó el timbre.</em>",
            "Imperfecto: era, llovía, leía (the background). Indefinido: sonó (the new event that breaks the scene).",
            "Think of the imperfecto as the painted backdrop and the indefinido as the action that happens in front of it.",
          ],
          keyPoint: "Imperfecto = the backdrop (state, habit, ongoing). Indefinido = the event that moves the story forward.",
        },
        {
          type: "fillBlank",
          heading: "Pick the right past tense",
          intro: "Decide between imperfecto (background/habit) and indefinido (single event).",
          items: [
            {
              template: "Mientras (yo) ___ , llegó mi hermano. (cenar)",
              answer: "cenaba",
              en: "While I was having dinner, my brother arrived.",
              options: ["cené", "cenaba", "ceno", "cenaría"],
            },
            {
              template: "Anoche (yo) ___ una película de Almodóvar. (ver)",
              answer: "vi",
              en: "Last night I watched an Almodóvar film. (completed event)",
              options: ["veía", "vi", "veo", "vería"],
            },
            {
              template: "De pequeña, (yo) ___ a casa de la abuela cada domingo. (ir)",
              answer: "iba",
              en: "As a girl, I used to go to grandma's house every Sunday.",
              options: ["iba", "fui", "voy", "iría"],
            },
            {
              template: "Cuando abrí la puerta, el niño ya ___ . (dormir)",
              answer: "dormía",
              en: "When I opened the door, the child was already sleeping.",
              options: ["durmió", "dormía", "duerme", "dormiría"],
            },
            {
              template: "El verano pasado (nosotros) ___ en Barcelona una semana. (estar)",
              answer: "estuvimos",
              en: "Last summer we were in Barcelona for a week. (completed, with a duration)",
              options: ["estábamos", "estuvimos", "estamos", "estaríamos"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate the memory",
          direction: "en-to-l1",
          prompt: "When I was a child, I lived in Granada. Every summer we went to the beach.",
          reference: "Cuando era niño/a, vivía en Granada. Todos los veranos íbamos a la playa.",
          hint: "Two states (was, lived) + one repeated habit (went) → all imperfecto.",
        },
        {
          type: "translate",
          heading: "Translate the scene",
          direction: "en-to-l1",
          prompt: "I was reading in the kitchen when someone knocked on the door.",
          reference: "Yo leía en la cocina cuando alguien llamó a la puerta.",
          hint: "The background action (was reading) = imperfecto; the interruption (knocked) = indefinido.",
        },
      ],
    }
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "The yo form of hablar (imperfecto) is…", options: ["hablé", "hablo", "hablaba", "hablara"], correct: 2 },
      { q: "The yo form of comer (imperfecto) is…", options: ["comí", "como", "comía", "coma"], correct: 2 },
      { q: "There are only ___ irregular verbs in the imperfecto.", options: ["2", "3", "5", "10"], correct: 1 },
      { q: "The imperfecto of ser (yo) is…", options: ["fue", "soy", "era", "sea"], correct: 2 },
      { q: "The imperfecto of ir (yo) is…", options: ["fui", "voy", "iba", "fuera"], correct: 2 },
      { q: "Imperfecto is used for…", options: ["Single completed events", "Habitual or descriptive past", "Future plans", "Commands"], correct: 1 },
      { q: "'Leía cuando llegó' — 'leía' is…", options: ["Indefinido (finished action)", "Imperfecto (background action)", "Perfecto (recent action)", "Presente"], correct: 1 },
      { q: "Which time marker suggests imperfecto?", options: ["ayer", "el lunes pasado", "de niño (as a child)", "hace dos años"], correct: 2 },
      { q: "'Todos los días comía paella' means…", options: ["One day I ate paella", "I will eat paella every day", "Every day I used to eat paella", "I have eaten paella today"], correct: 2 },
      { q: "Imperfecto -er/-ir endings start with…", options: ["-aba", "-ía", "-ó", "-ería"], correct: 1 },
    ],
  },
};
