import type { Unit } from "../../types";

export const UNIT_NARRATE_TRIP: Unit = {
  slug: "narrate-trip",
  stage: 5,
  order: 24,
  icon: "📖",
  title: "Narrating a trip",
  tagline: "Combine tenses to tell your travel story.",
  lessons: [
    {
      slug: "narrate-trip-story",
      title: "Telling your travel story",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "Weaving tenses together",
          body: [
            "Real stories use multiple tenses at once. The background is imperfecto; the events are indefinido; recent things can use perfecto; plans ahead are futuro or ir + a.",
            "The key is deciding: is this a completed event (indefinido), an ongoing situation/habit (imperfecto), or a recent action with present relevance (perfecto)?",
          ],
          keyPoint: "Event (indefinido) → Background (imperfecto) → Recent (perfecto) → Plans (ir+a/futuro).",
        },
        {
          type: "vocab",
          heading: "Sample travel narrative",
          items: [
            { l1: "El verano pasado fui a España.", en: "Last summer I went to Spain. (indefinido — event)" },
            { l1: "Hacía mucho calor, pero era precioso.", en: "It was very hot, but it was beautiful. (imperfecto — background)" },
            { l1: "Visité el Prado y comí tapas todos los días.", en: "I visited the Prado and ate tapas every day. (indefinido — events; imperfecto for habit)" },
            { l1: "Este año ya he vuelto dos veces.", en: "This year I've already been back twice. (perfecto — recent, tied to now)" },
            { l1: "El año que viene voy a quedarme un mes.", en: "Next year I'm going to stay a month. (ir + a — future plan)" },
          ],
        },
        {
          type: "vocab",
          heading: "Useful storytelling phrases",
          items: [
            { l1: "Al principio…", en: "At first…" },
            { l1: "Después / Luego…", en: "Afterwards / Then…" },
            { l1: "De repente…", en: "Suddenly…" },
            { l1: "Al final…", en: "In the end…" },
            { l1: "Lo mejor fue…", en: "The best part was…" },
            { l1: "Lo más difícil fue…", en: "The hardest part was…" },
            { l1: "Me sorprendió que…", en: "It surprised me that…" },
            { l1: "Ojalá volver.", en: "I hope to go back." },
          ],
        },
        {
          type: "tip",
          heading: "The 'canvas and brushstroke' rule",
          body: "Think of the imperfecto as the canvas — it paints the scene, the weather, how things felt, what was going on. Think of the indefinido as the brushstroke — it drops a single completed event onto that canvas. <em>Hacía sol y la gente paseaba</em> (canvas) <em>cuando, de repente, empezó a llover</em> (brushstroke). A story with only indefinido reads like a shopping list; a story with only imperfecto has no plot. You need both.",
          example: { l1: "Caminaba por la playa cuando vi a un viejo amigo.", en: "I was walking on the beach when I saw an old friend." },
        },
        {
          type: "multipleChoice",
          heading: "Narrative tenses",
          questions: [
            {
              q: "In a story, the background is told in…",
              options: ["indefinido", "imperfecto", "perfecto", "futuro"],
              correct: 1,
              fb: "Imperfecto paints the background: the weather, the setting, habits, ongoing states.",
            },
            {
              q: "'De repente' signals…",
              options: ["A habit or routine", "A background description", "A sudden event (usually indefinido)", "A future plan"],
              correct: 2,
              fb: "De repente (suddenly) signals a plot event — use indefinido. De repente entró un hombre.",
            },
            {
              q: "'Mientras paseábamos, empezó a nevar' — which verb is the event?",
              qL1: "Mientras paseábamos, empezó a nevar.",
              options: ["paseábamos", "empezó", "both", "neither"],
              correct: 1,
              fb: "Paseábamos is the ongoing background (imperfecto); empezó is the single event that breaks in (indefinido).",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Choose the right past tense",
          intro: "Decide whether each blank is background (imperfecto) or a completed event (indefinido).",
          items: [
            {
              template: "Ayer ___ (ser) un día precioso.",
              answer: "era",
              en: "Yesterday was a beautiful day. (description → imperfecto)",
              options: ["era", "fue", "es", "será"],
            },
            {
              template: "Mientras ___ (caminar) por el centro, ___ (encontrar) a un viejo amigo.",
              answer: "caminaba / encontré",
              en: "While I was walking through the center, I met an old friend.",
              options: [
                "caminaba / encontré",
                "caminé / encontraba",
                "camino / encuentro",
                "caminaba / encontraba",
              ],
            },
            {
              template: "Cuando era pequeño, ___ (ir) a la playa todos los veranos.",
              answer: "iba",
              en: "When I was little, I used to go to the beach every summer. (habit → imperfecto)",
              options: ["iba", "fui", "voy", "iré"],
            },
            {
              template: "El tren ___ (llegar) anoche a las diez en punto.",
              answer: "llegó",
              en: "The train arrived last night at ten o'clock. (event → indefinido)",
              options: ["llegaba", "llegó", "llega", "llegará"],
            },
            {
              template: "(Yo) ___ (estar) muy cansado cuando ___ (llegar) al hotel.",
              answer: "estaba / llegué",
              en: "I was very tired when I arrived at the hotel. (state + event)",
              options: [
                "estuve / llegaba",
                "estaba / llegué",
                "estoy / llegué",
                "estaba / llegaba",
              ],
            },
          ],
        },
      ],
    },
    {
      slug: "narrate-trip-practice",
      title: "Writing a trip narrative",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "The three-tense braid",
          body: [
            "A polished story braids the tenses together naturally:",
            "<em><strong>Era</strong> una mañana de septiembre. (imperfecto — scene)</em>",
            "<em><strong>Me desperté</strong> a las seis y <strong>tomé</strong> un café. (indefinido — events)</em>",
            "<em>Mientras <strong>desayunaba</strong>, <strong>leí</strong> el mensaje de Marta. (imperfecto background + indefinido event)</em>",
            "<em>Ahora, cada vez que pienso en aquel viaje, sonrío. (presente — conclusion)</em>",
          ],
          keyPoint: "Imperfecto = states, ongoing background, weather, age, habits. Indefinido = events that move the story forward. Presente = wraps it up.",
        },
        {
          type: "translate",
          heading: "Translate this narrative sentence",
          direction: "en-to-l1",
          prompt: "When I arrived, it was raining.",
          reference: "Cuando llegué, llovía.",
          hint: "llegué (indefinido) + llovía (imperfecto)",
        },
        {
          type: "translate",
          heading: "Translate this narrative sentence",
          direction: "en-to-l1",
          prompt: "Suddenly the lights went out.",
          reference: "De repente se apagaron las luces.",
          hint: "indefinido for event",
        },
        {
          type: "translate",
          heading: "Translate it (mixed tenses)",
          direction: "en-to-l1",
          prompt: "It was raining. I was eating dinner when the phone rang. It was my mother.",
          reference: "Llovía. Estaba cenando cuando sonó el teléfono. Era mi madre.",
          hint: "Three imperfectos (was raining, was eating, was — state) + one event (rang → sonó).",
        },
        {
          type: "orderWords",
          heading: "Build the narrative",
          intro: "Put the words in order to form each sentence of a little story.",
          items: [
            { tokens: ["Era", "un", "día", "frío", "de", "enero"], en: "It was a cold January day." },
            { tokens: ["Salí", "temprano", "para", "ir", "al", "trabajo"], en: "I left early to go to work." },
            { tokens: ["Mientras", "esperaba", "el", "autobús", ",", "empezó", "a", "nevar"], en: "While I was waiting for the bus, it started to snow." },
            { tokens: ["Al", "final", "llegué", "a", "la", "oficina", "empapado"], en: "In the end I arrived at the office soaked." },
          ],
        },
        {
          type: "tip",
          heading: "estar + gerundio = 'was -ing'",
          body: "To stress that an action was in progress, Spanish uses <em>estar + gerundio</em>: <em>Estaba cenando</em> = I was eating dinner. (vs <em>cenaba</em>, which is also correct but less vivid.) The gerundio: <em>-ando</em> for -ar verbs, <em>-iendo</em> for -er/-ir verbs. <em>hablar → hablando, comer → comiendo, vivir → viviendo</em>. Watch the stem changers: <em>leer → leyendo, dormir → durmiendo, pedir → pidiendo</em>.",
          example: { l1: "Estábamos durmiendo cuando llamaron a la puerta.", en: "We were sleeping when they knocked at the door." },
        },
        {
          type: "multipleChoice",
          heading: "Story check",
          questions: [
            {
              q: "'Lo mejor fue la comida' means…",
              options: ["The food was the best (past)", "The best thing was the food", "Better food", "The food is better now"],
              correct: 1,
              fb: "Lo mejor fue = the best thing was. A great phrase for describing trip highlights.",
            },
            {
              q: "'Ojalá volver' expresses…",
              options: ["A plan to return", "A wish/hope to return", "A decision to return", "A command to return"],
              correct: 1,
              fb: "Ojalá = I hope / I wish. Expresses a desire without certainty.",
            },
            {
              q: "Which sentence correctly mixes the tenses?",
              options: [
                "Estaba cansado cuando llegué.",
                "Estuve cansado cuando llegaba.",
                "Estaba cansado cuando llegaba.",
                "Estuve cansado cuando llegué.",
              ],
              correct: 0,
              fb: "Estaba cansado = ongoing state (imperfecto); llegué = the completed event (indefinido).",
            },
          ],
        },
      ],
    },
    {
      slug: "narrate-trip-oral",
      title: "Telling your story aloud",
      estMinutes: 8,
      pages: [
        {
          type: "dialogue",
          heading: "Telling someone about a trip",
          lines: [
            { speaker: "Friend", l1: "¿Cómo te fue en Sevilla?", en: "How did it go in Seville?" },
            { speaker: "You", l1: "Genial. El primer día hacía mucho calor, pero no importó.", en: "Great. The first day it was very hot, but it didn't matter." },
            { speaker: "You", l1: "Visité la Giralda y el Alcázar. Los dos son impresionantes.", en: "I visited the Giralda and the Alcázar. Both are impressive." },
            { speaker: "Friend", l1: "¿Y comiste bien?", en: "And did you eat well?" },
            { speaker: "You", l1: "Muy bien. Probé el gazpacho auténtico y el salmorejo. Son completamente distintos a lo de aquí.", en: "Very well. I tried authentic gazpacho and salmorejo. They're completely different to what we have here." },
            { speaker: "Friend", l1: "¡Qué envidia! ¿Cuándo vuelves?", en: "How jealous! When are you going back?" },
          ],
        },
        {
          type: "vocab",
          heading: "Trip narrative vocabulary",
          items: [
            { l1: "¿Cómo te fue?", en: "How did it go? / How was it for you?" },
            { l1: "Lo pasé genial / fenomenal", en: "I had a great time" },
            { l1: "Lo mejor del viaje fue…", en: "The best part of the trip was…" },
            { l1: "Lo único malo fue…", en: "The only bad thing was…" },
            { l1: "Merece la pena ir.", en: "It's worth going." },
            { l1: "Lo recomiendo totalmente.", en: "I totally recommend it." },
          ],
        },
        {
          type: "translate",
          heading: "Describe your trip",
          direction: "en-to-l1",
          prompt: "The best part of the trip was the food.",
          reference: "Lo mejor del viaje fue la comida.",
          hint: "Lo mejor del viaje fue + noun",
        },
        {
          type: "translate",
          heading: "Describe your trip",
          direction: "en-to-l1",
          prompt: "We had a great time, but the only bad thing was the weather.",
          reference: "Lo pasamos genial, pero lo único malo fue el tiempo.",
          hint: "Lo pasamos genial (indefinido) + lo único malo fue + noun",
        },
      ],
    },
    {
      slug: "narrate-trip-write-your-own",
      title: "Write your own trip story",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "Time to put it all together",
          body: [
            "This lesson is mostly translation practice — you'll build a short trip story piece by piece using all the tenses you've learned.",
            "Story setup: \"A weekend trip to Granada.\" The sentences below, together, form one complete narrative.",
            "Use the Spanish model on each one — these are graded by Claude, so you'll get feedback if you drift off-track.",
          ],
        },
        {
          type: "translate",
          heading: "Scene-setting (use imperfecto)",
          direction: "en-to-l1",
          prompt: "It was a Saturday morning in June. The weather was beautiful and I was happy.",
          reference: "Era un sábado por la mañana de junio. Hacía buen tiempo y estaba contento.",
          hint: "All description = imperfecto. 'Hacía buen tiempo' = the weather was nice. 'Estaba contento' = I was happy.",
        },
        {
          type: "translate",
          heading: "First event (indefinido)",
          direction: "en-to-l1",
          prompt: "I took the train from Madrid at seven. The trip lasted four hours.",
          reference: "Tomé el tren desde Madrid a las siete. El viaje duró cuatro horas.",
          hint: "Two completed events: tomé + duró. Both indefinido.",
        },
        {
          type: "translate",
          heading: "On arrival (mix of tenses)",
          direction: "en-to-l1",
          prompt: "When I arrived in Granada, it was hot. I left the station and walked to the old town.",
          reference: "Cuando llegué a Granada, hacía calor. Salí de la estación y caminé hasta el casco antiguo.",
          hint: "Arrived (event) + was hot (background) + left (event) + walked (event).",
        },
        {
          type: "translate",
          heading: "Background detail (imperfecto)",
          direction: "en-to-l1",
          prompt: "While I was walking, I was looking at the buildings and listening to music.",
          reference: "Mientras caminaba, miraba los edificios y escuchaba música.",
          hint: "Three simultaneous ongoing actions = three imperfectos.",
        },
        {
          type: "translate",
          heading: "Sudden event (indefinido)",
          direction: "en-to-l1",
          prompt: "Suddenly I saw a small restaurant with a handwritten menu. I decided to go in.",
          reference: "De repente vi un pequeño restaurante con una carta escrita a mano. Decidí entrar.",
          hint: "Two events: vi + decidí. 'A mano' = by hand.",
        },
        {
          type: "translate",
          heading: "The meal (mix)",
          direction: "en-to-l1",
          prompt: "I ate a paella with a glass of red wine. It was the best meal of my trip.",
          reference: "Comí una paella con una copa de vino tinto. Fue la mejor comida del viaje.",
          hint: "Comí (event). 'Fue' = it was (one specific meal, completed = indefinido, NOT imperfecto here).",
        },
        {
          type: "translate",
          heading: "Conclusion (present + future plan)",
          direction: "en-to-l1",
          prompt: "I love Granada. Next month I'm definitely going back.",
          reference: "Me encanta Granada. El mes que viene voy a volver sin falta.",
          hint: "'Me encanta' = present. 'Voy a volver' = ir + a + infinitive (future plan). 'Sin falta' = without fail / definitely.",
        },
        {
          type: "tip",
          heading: "Congratulations — you can narrate now",
          body: "You just told an eight-sentence story using three tenses, agreement, and connector words. That's real B1-level narrative skill. From here you can talk about any past trip, weekend, or memory in conversational Spanish. Later stages add nuance (usted forms, conditional, subjunctive) — but the heavy structural lifting is done.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "Background descriptions in a story use…", options: ["indefinido", "imperfecto", "perfecto", "futuro"], correct: 1 },
      { q: "Single completed story events use…", options: ["imperfecto", "perfecto", "indefinido", "presente"], correct: 2 },
      { q: "'De repente' usually signals which tense?", options: ["imperfecto", "indefinido", "futuro", "perfecto"], correct: 1 },
      { q: "'Al principio' means…", options: ["At the end", "In the middle", "At first", "Suddenly"], correct: 2 },
      { q: "'Lo mejor fue…' means…", options: ["The better is…", "The best thing was…", "It is the best", "The food was good"], correct: 1 },
      { q: "'Ojalá' expresses…", options: ["Certainty", "A command", "A wish/hope", "A past habit"], correct: 2 },
      { q: "'Hacía mucho calor' — what tense is hacía?", options: ["indefinido", "presente", "imperfecto", "futuro"], correct: 2 },
      { q: "'Llegué a Madrid' — what tense is llegué?", options: ["imperfecto", "indefinido", "perfecto", "presente"], correct: 1 },
      { q: "Recent past with present relevance uses…", options: ["indefinido", "imperfecto", "perfecto", "futuro"], correct: 2 },
      { q: "'Después' connects…", options: ["Cause and effect", "Sequence of events", "Background and foreground", "Present and future"], correct: 1 },
      { q: "'Mientras cenaba, sonó el teléfono' — which verb is the event?", options: ["cenaba", "sonó", "both", "neither"], correct: 1 },
      { q: "'Estaba cansado cuando llegué' correctly mixes…", options: ["two indefinidos", "two imperfectos", "imperfecto (state) + indefinido (event)", "indefinido (state) + imperfecto (event)"], correct: 2 },
    ],
  },
};
