import type { Unit } from "../../types";

export const UNIT_CONDITIONAL: Unit = {
  slug: "conditional",
  stage: 8,
  order: 33,
  icon: "🎩",
  title: "Conditional",
  tagline: "Me gustaría, podría, debería — polite requests.",
  lessons: [
    {
      slug: "conditional-intro",
      title: "The conditional tense",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "The conditional — polite and hypothetical",
          body: [
            "The conditional tense expresses 'would'. It's used for polite requests (<em>¿Podría ayudarme?</em> = Could you help me?), hypothetical situations (<em>En tu lugar, iría</em> = In your place, I would go), and reported speech.",
            "Like the future tense, the conditional adds endings to the full infinitive. The endings are the same as the imperfecto of -er/-ir verbs (-ía/-ías/-ía/-íamos/-íais/-ían), and irregular stems are the same as the future.",
            "<strong>Every single form carries an accent on the í</strong> — hablaría, comerías, viviríamos. That accent is not optional; it marks the stressed syllable and distinguishes the conditional from other tenses.",
          ],
          keyPoint: "Conditional = infinitive + -ía/-ías/-ía/-íamos/-íais/-ían. Same irregular stems as futuro. Every form has an accented í.",
        },
        {
          type: "conjugation",
          heading: "The three regular conjugations",
          verb: "hablar / comer / vivir",
          meaning: "to speak / to eat / to live (conditional)",
          intro: "All three verb classes use the exact same endings — added straight onto the infinitive.",
          tenses: [
            {
              name: "hablar (to speak)",
              forms: [
                { person: "yo", form: "hablaría", en: "I would speak" },
                { person: "tú", form: "hablarías", en: "you would speak" },
                { person: "él/ella/usted", form: "hablaría", en: "he/she/you would speak" },
                { person: "nosotros", form: "hablaríamos", en: "we would speak" },
                { person: "vosotros", form: "hablaríais", en: "you all would speak" },
                { person: "ellos/ustedes", form: "hablarían", en: "they/you would speak" },
              ],
            },
            {
              name: "comer (to eat)",
              forms: [
                { person: "yo", form: "comería", en: "I would eat" },
                { person: "tú", form: "comerías", en: "you would eat" },
                { person: "él/ella/usted", form: "comería", en: "he/she/you would eat" },
                { person: "nosotros", form: "comeríamos", en: "we would eat" },
                { person: "vosotros", form: "comeríais", en: "you all would eat" },
                { person: "ellos/ustedes", form: "comerían", en: "they/you would eat" },
              ],
            },
            {
              name: "vivir (to live)",
              forms: [
                { person: "yo", form: "viviría", en: "I would live" },
                { person: "tú", form: "vivirías", en: "you would live" },
                { person: "él/ella/usted", form: "viviría", en: "he/she/you would live" },
                { person: "nosotros", form: "viviríamos", en: "we would live" },
                { person: "vosotros", form: "viviríais", en: "you all would live" },
                { person: "ellos/ustedes", form: "vivirían", en: "they/you would live" },
              ],
            },
          ],
        },
        {
          type: "vocab",
          heading: "Key irregular conditionals",
          intro: "The stem changes, but the endings (-ía, -ías…) stay identical. These are the same 12 stems you learned for the future.",
          items: [
            { l1: "poder → podría", en: "could / would be able to" },
            { l1: "tener → tendría", en: "would have", note: "stem tendr-" },
            { l1: "querer → querría", en: "would want", note: "double r: quer + r-ía" },
            { l1: "hacer → haría", en: "would do / make", note: "irregular stem har-" },
            { l1: "venir → vendría", en: "would come", note: "stem vendr-" },
            { l1: "decir → diría", en: "would say", note: "irregular stem dir-" },
            { l1: "saber → sabría", en: "would know" },
            { l1: "salir → saldría", en: "would leave / go out", note: "stem saldr-" },
            { l1: "poner → pondría", en: "would put", note: "stem pondr-" },
            { l1: "deber → debería", en: "should / ought to" },
            { l1: "haber → habría", en: "there would be / would have (aux)" },
          ],
        },
        {
          type: "vocab",
          heading: "Conditional in use",
          items: [
            { l1: "Me gustaría un café.", en: "I'd like a coffee." },
            { l1: "¿Podría hablar más despacio?", en: "Could you speak more slowly?" },
            { l1: "Debería llamarla.", en: "I should call her." },
            { l1: "En tu lugar, iría.", en: "In your place, I would go." },
            { l1: "¿Te gustaría venir?", en: "Would you like to come?" },
            { l1: "Con más dinero, viajaría más.", en: "With more money, I'd travel more." },
          ],
        },
        {
          type: "tip",
          heading: "You've used 'me gustaría' for ages",
          body: "Since the very first lessons you've ordered with <em>me gustaría…</em> = I'd like… That's just the conditional of <em>gustar</em>. Spanish leans on the conditional constantly to soften a request and avoid sounding blunt — <em>quiero un café</em> (I want a coffee) sounds far more abrupt than <em>querría un café</em> or <em>me gustaría un café</em>.",
          example: { l1: "Querría reservar una mesa para dos.", en: "I'd like to book a table for two." },
        },
        {
          type: "conjugation",
          heading: "The eight you'll actually reach for",
          verb: "poder / tener / querer / hacer / deber / decir / venir / saber",
          meaning: "the most common irregular conditionals (yo form)",
          tenses: [
            {
              name: "Condicional (yo)",
              forms: [
                { person: "poder", form: "podría", en: "I could" },
                { person: "tener", form: "tendría", en: "I would have" },
                { person: "querer", form: "querría", en: "I would want / I'd like" },
                { person: "hacer", form: "haría", en: "I would do/make" },
                { person: "deber", form: "debería", en: "I should" },
                { person: "decir", form: "diría", en: "I would say" },
                { person: "venir", form: "vendría", en: "I would come" },
                { person: "saber", form: "sabría", en: "I would know" },
              ],
            },
            {
              name: "Condicional (tú)",
              forms: [
                { person: "poder", form: "podrías", en: "you could" },
                { person: "tener", form: "tendrías", en: "you would have" },
                { person: "querer", form: "querrías", en: "you'd want" },
                { person: "hacer", form: "harías", en: "you would do" },
                { person: "deber", form: "deberías", en: "you should" },
                { person: "salir", form: "saldrías", en: "you would leave" },
              ],
            },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Conditional check",
          questions: [
            {
              q: "'Me gustaría' is the conditional of…",
              options: ["gustar (to like/please)", "estar (to be)", "ir (to go)", "tener (to have)"],
              correct: 0,
              fb: "Gustar → gustaría. Me gustaría = I would like. The most polite way to express a desire.",
            },
            {
              q: "'Debería estudiar más' means…",
              options: ["I want to study more", "I should study more", "I will study more", "I used to study more"],
              correct: 1,
              fb: "Deber → debería = should/ought to. Debería estudiar más = I should study more.",
            },
            {
              q: "The conditional has the same irregular stems as…",
              options: ["The imperfecto", "The subjunctive", "The futuro simple", "The perfecto"],
              correct: 2,
              fb: "Same stems as futuro: tendr-, vendr-, podr-, querr-, har-, dir-, sabr-, saldr-.",
            },
            {
              q: "Which form is correctly accented?",
              options: ["hablaria", "hablariá", "hablaría", "háblaria"],
              correct: 2,
              fb: "Every conditional form stresses the í: hablaría, comería, viviríamos. The accent is mandatory.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Conditional drills",
          intro: "Fill in the conditional of the verb in brackets.",
          items: [
            {
              template: "Me ___ un té, por favor. (gustar)",
              answer: "gustaría",
              en: "I'd like a tea, please.",
              options: ["gusta", "gustaría", "gustará", "gustaba"],
            },
            {
              template: "¿___ ayudarme con esto? (poder — tú)",
              answer: "Podrías",
              en: "Could you help me with this?",
              options: ["Puedes", "Podrías", "Podrás", "Pudiste"],
            },
            {
              template: "(Yo) ___ ir, pero no tengo tiempo. (querer)",
              answer: "querría",
              en: "I'd want to go, but I don't have time.",
              options: ["quiero", "querría", "quería", "querré"],
            },
            {
              template: "Nosotros ___ viajar más con más dinero. (viajar)",
              answer: "viajaríamos",
              en: "We would travel more with more money.",
              options: ["viajamos", "viajaríamos", "viajaremos", "viajábamos"],
            },
            {
              template: "Él ___ venir, pero está enfermo. (venir)",
              answer: "vendría",
              en: "He would come, but he's sick.",
              options: ["viene", "vendrá", "vendría", "venía"],
            },
            {
              template: "Tú ___ llamar al médico. (deber)",
              answer: "deberías",
              en: "You should call the doctor.",
              options: ["debes", "deberías", "deberás", "debías"],
            },
          ],
        },
      ],
    },
    {
      slug: "conditional-uses",
      title: "Politeness and softening",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The three jobs of the conditional",
          body: [
            "<strong>1. Politeness</strong> — softening requests and statements. <em>Querría un café</em> is gentler than <em>Quiero un café</em>; <em>¿Podrías cerrar la puerta?</em> is far softer than <em>¡Cierra la puerta!</em>",
            "<strong>2. Hypotheticals</strong> — what 'would' happen if conditions were met. <em>Iría de vacaciones, pero no tengo dinero.</em> = I'd go on vacation, but I don't have money.",
            "<strong>3. Reported speech</strong> — \"he said he would…\". <em>Marco dijo que llegaría a las ocho.</em> = Marco said he would arrive at eight.",
          ],
          keyPoint: "Three uses: politeness (querría / me gustaría), hypothetical (iría, pero…), reported speech (dijo que llegaría).",
        },
        {
          type: "vocab",
          heading: "Common conditional phrases",
          items: [
            { l1: "Me gustaría…", en: "I'd like… (the polite default)" },
            { l1: "Querría…", en: "I'd like / I'd want… (very polite)" },
            { l1: "¿Podrías / Podría…?", en: "Could you…? (informal / formal)" },
            { l1: "Deberías…", en: "You should… (gentle advice)" },
            { l1: "Sería mejor…", en: "It would be better…" },
            { l1: "¿Sería posible…?", en: "Would it be possible…?" },
            { l1: "¿Me darías / me daría…?", en: "Would you give me…? (informal / formal)" },
            { l1: "¿Qué harías?", en: "What would you do?" },
            { l1: "Iría con mucho gusto.", en: "I'd gladly go." },
            { l1: "Tendría una pregunta.", en: "I'd have a question (very polite opener)." },
          ],
        },
        {
          type: "dialogue",
          heading: "Polite requests at a hotel",
          setup: "You need to change rooms.",
          lines: [
            { speaker: "You", l1: "Buenas tardes. Tendría una petición — ¿sería posible cambiar de habitación?", en: "Good afternoon. I'd have a request — would it be possible to change rooms?" },
            { speaker: "Recepcionista", l1: "Claro, dígame. ¿Hay algún problema?", en: "Of course, tell me. Is there a problem?" },
            { speaker: "You", l1: "La habitación es un poco ruidosa. Me gustaría algo más tranquilo, si fuera posible.", en: "The room is a bit noisy. I'd like something quieter, if possible." },
            { speaker: "Recepcionista", l1: "Entiendo. Podría darle la 405, en el cuarto piso. Sería más silenciosa.", en: "I understand. I could give you 405, on the fourth floor. It would be quieter." },
            { speaker: "You", l1: "Sería perfecto. ¿Cuándo podría mudarme?", en: "That would be perfect. When could I move?" },
            { speaker: "Recepcionista", l1: "En media hora, tras la limpieza. ¿Querría que le subiéramos las maletas?", en: "In half an hour, after cleaning. Would you like us to bring up your suitcases?" },
            { speaker: "You", l1: "No, gracias, lo hago yo. ¡Muchas gracias!", en: "No thanks, I'll do it. Thank you very much!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Apply the conditional",
          items: [
            {
              template: "¿___ traerme la carta, por favor? (poder — usted)",
              answer: "Podría",
              en: "Could you bring me the menu, please?",
              options: ["Puede", "Podría", "Debe", "Querría"],
            },
            {
              template: "¿Me ___ un agua con gas? (dar — usted)",
              answer: "daría",
              en: "Would you give me a sparkling water?",
              options: ["da", "darías", "daría", "diera"],
            },
            {
              template: "(Tú) ___ ir al gimnasio más a menudo. (deber)",
              answer: "deberías",
              en: "You should go to the gym more often.",
              options: ["debes", "deberías", "deberás", "debías"],
            },
            {
              template: "Me ___ mucho un viaje a Sevilla. (gustar)",
              answer: "gustaría",
              en: "I would really like a trip to Seville.",
              options: ["gusta", "gustaría", "gustaba", "gustará"],
            },
            {
              template: "(Nosotros) ___ salir antes, pero hay mucho tráfico. (querer)",
              answer: "querríamos",
              en: "We'd want to leave earlier, but there's a lot of traffic.",
              options: ["queremos", "querríamos", "querremos", "queríamos"],
            },
          ],
        },
        {
          type: "tip",
          heading: "Conditional vs. polite imperfecto",
          body: "Spanish also softens with the imperfecto: <em>quería un café</em> (literally 'I wanted a coffee') is a common, friendly way to order. But the conditional — <em>querría</em>, <em>me gustaría</em> — is one notch more polite and works everywhere. When in doubt with a stranger or in a formal setting, reach for the conditional.",
          example: { l1: "Querría hablar con el encargado, por favor.", en: "I'd like to speak with the manager, please." },
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Excuse me, could you tell me where the bathroom is?",
          reference: "Perdone, ¿podría decirme dónde está el baño?",
          hint: "'Podría' = could you (formal). 'Decirme' = to tell me (decir + me).",
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'd like to reserve a table for four, please.",
          reference: "Me gustaría reservar una mesa para cuatro, por favor.",
          hint: "'Me gustaría' + infinitive is the politest way to make a request.",
        },
      ],
    },
    {
      slug: "conditional-advice",
      title: "Hypotheticals, advice and wishes",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Si + imperfecto de subjuntivo + condicional",
          body: [
            "Hypothetical ('if') sentences pair the imperfecto subjunctive with the conditional: <em>Si tuviera más dinero, viajaría</em> = If I had more money, I would travel. The 'if' clause uses the imperfecto subjunctive (<em>tuviera</em>); the result uses the conditional (<em>viajaría</em>).",
            "The subjunctive half is B2 grammar (full unit later), but the conditional half is all you need to start building these sentences — and you'll hear them everywhere.",
            "For advice, Spanish leans on soft openers + the conditional: <em>Yo que tú…</em> (If I were you…), <em>Yo en tu lugar…</em> (In your place…), <em>Deberías…</em>, <em>Sería mejor…</em>",
          ],
          keyPoint: "Si tuviera… (imperfecto subjuntivo) + viajaría (conditional). For advice: Yo que tú / Yo en tu lugar / Deberías + conditional.",
        },
        {
          type: "vocab",
          heading: "Hypothetical phrases in context",
          items: [
            { l1: "Si pudiera, viviría en España.", en: "If I could, I'd live in Spain." },
            { l1: "Si tuviera tiempo, estudiaría más.", en: "If I had time, I'd study more." },
            { l1: "¿Qué harías en mi lugar?", en: "What would you do in my place?" },
            { l1: "Yo que tú, no iría.", en: "If I were you, I wouldn't go." },
            { l1: "Con más práctica, hablaría mejor.", en: "With more practice, I'd speak better." },
            { l1: "Sin el tráfico, llegaríamos a tiempo.", en: "Without the traffic, we'd arrive on time." },
          ],
        },
        {
          type: "vocab",
          heading: "Giving advice with the conditional",
          items: [
            { l1: "Yo en tu lugar…", en: "If I were you / in your place…" },
            { l1: "Yo que tú, iría al médico.", en: "If I were you, I'd go to the doctor." },
            { l1: "Te recomendaría que…", en: "I would recommend that you…" },
            { l1: "Lo haría de otra manera.", en: "I would do it differently." },
            { l1: "Deberías descansar más.", en: "You should rest more." },
            { l1: "Sería mejor no insistir.", en: "It would be better not to insist." },
            { l1: "¿No sería mejor llamarlo?", en: "Wouldn't it be better to call him?" },
            { l1: "Quizás podrías probar otra cosa.", en: "Maybe you could try something else." },
          ],
        },
        {
          type: "dialogue",
          heading: "Asking for and giving advice",
          setup: "Pablo is stressed about his boss.",
          lines: [
            { speaker: "Pablo", l1: "Tengo un problema con mi jefe. ¿Qué harías tú?", en: "I have a problem with my boss. What would you do?" },
            { speaker: "Sara", l1: "Lo siento. Yo que tú, hablaría directamente con él.", en: "I'm sorry. If I were you, I'd speak to him directly." },
            { speaker: "Pablo", l1: "¿Tú crees? Tengo miedo de que se enfade.", en: "You think so? I'm afraid he'll get angry." },
            { speaker: "Sara", l1: "Quizás podrías escribirle un correo primero, para explicarle todo con calma.", en: "Maybe you could write him an email first, to explain everything calmly." },
            { speaker: "Pablo", l1: "Sería más fácil, sí.", en: "It would be easier, yes." },
            { speaker: "Sara", l1: "Exacto. Sería mejor resolverlo antes de que crezca el problema.", en: "Exactly. It would be better to solve it before the problem grows." },
            { speaker: "Pablo", l1: "Tienes razón. Gracias, me has ayudado mucho.", en: "You're right. Thanks, you've helped me a lot." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Soft advice fill",
          items: [
            {
              template: "Yo que tú, ___ con él. (hablar)",
              answer: "hablaría",
              en: "If I were you, I'd talk with him.",
              options: ["hablo", "he hablado", "hablaría", "hablaba"],
            },
            {
              template: "___ mejor salir antes. (ser)",
              answer: "Sería",
              en: "It would be better to leave earlier.",
              options: ["Es", "Será", "Sería", "Era"],
            },
            {
              template: "Tú ___ estudiar más. (deber)",
              answer: "deberías",
              en: "You should study more.",
              options: ["debes", "deberías", "deberás", "debías"],
            },
            {
              template: "Quizás (vosotros) ___ probar otro restaurante. (poder)",
              answer: "podríais",
              en: "Maybe you could try another restaurant.",
              options: ["podéis", "podríais", "podréis", "pudisteis"],
            },
            {
              template: "¿No ___ mejor llamarlo? (ser)",
              answer: "sería",
              en: "Wouldn't it be better to call him?",
              options: ["es", "será", "sería", "era"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the advice",
          items: [
            { tokens: ["Yo", "que", "tú", ",", "iría", "a", "la", "playa"], en: "If I were you, I'd go to the beach." },
            { tokens: ["Quizás", "podrías", "llamar", "a", "tu", "madre"], en: "Maybe you could call your mother." },
            { tokens: ["Sería", "mejor", "no", "insistir", "ahora"], en: "It would be better not to insist now." },
            { tokens: ["Te", "recomendaría", "reservar", "con", "antelación"], en: "I'd recommend booking in advance." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Hypothetical & advice check",
          questions: [
            {
              q: "'Yo que tú, no iría' means…",
              options: ["You should go", "If I were you, I wouldn't go", "I don't want to go", "You shouldn't have gone"],
              correct: 1,
              fb: "Yo que tú = if I were you. A very natural way to give advice in Spanish.",
            },
            {
              q: "In a hypothetical sentence, 'si' introduces…",
              options: ["The result (conditional)", "The condition (what needs to be true)", "A question", "A command"],
              correct: 1,
              fb: "Si = if. Si tuviera dinero (condition) → viajaría (result/conditional).",
            },
            {
              q: "'Sería mejor descansar' means…",
              options: ["It is better to rest", "It would be better to rest", "It was better to rest", "Rest is the best"],
              correct: 1,
              fb: "Sería = conditional of ser. Sería mejor… = it would be better… A classic soft suggestion.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Give advice in Spanish",
          direction: "en-to-l1",
          prompt: "If I were you, I would look for another job.",
          reference: "Yo en tu lugar, buscaría otro trabajo.",
          hint: "Yo en tu lugar + conditional (buscar → buscaría)",
        },
        {
          type: "translate",
          heading: "Translate the hypothetical",
          direction: "en-to-l1",
          prompt: "With more time, I would travel all over Spain.",
          reference: "Con más tiempo, viajaría por toda España.",
          hint: "'Con más tiempo' sets the condition; the result verb goes in the conditional (viajar → viajaría).",
        },
        {
          type: "tip",
          heading: "Avoid the bare imperative when advising peers",
          body: "Telling a friend <em>«¡Haz esto!»</em> (Do this!) can land as bossy. Soften it with the conditional: <em>«Podrías hacer esto»</em> (You could do this) or <em>«Yo que tú haría esto»</em> (If I were you I'd do this). Spanish speakers appreciate the cushion — it shows you respect their choice.",
          example: { l1: "Yo que tú lo pensaría dos veces.", en: "If I were you, I'd think it over twice." },
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "The yo form of hablar (conditional) is…", options: ["hablaré", "hablaría", "hablara", "hablo"], correct: 1 },
      { q: "The conditional of 'poder' (yo) is…", options: ["puedo", "podré", "podría", "pudiera"], correct: 2 },
      { q: "'Me gustaría' means…", options: ["I like", "I liked", "I would like", "I will like"], correct: 2 },
      { q: "'Debería' means…", options: ["I will", "I would", "I should", "I must"], correct: 2 },
      { q: "Conditional endings are added to…", options: ["The stem", "The infinitive", "The past participle", "The subjunctive"], correct: 1 },
      { q: "The conditional shares irregular stems with…", options: ["The imperfecto", "The futuro", "The indefinido", "The subjunctive"], correct: 1 },
      { q: "'¿Te gustaría venir?' means…", options: ["Did you like coming?", "Would you like to come?", "Do you like coming?", "You should come"], correct: 1 },
      { q: "'En tu lugar, iría' means…", options: ["In your place, I would go", "You went in my place", "I went instead of you", "In your town, I would go"], correct: 0 },
      { q: "The conditional of 'hacer' (yo) is…", options: ["haré", "hacería", "haría", "hiciría"], correct: 2 },
      { q: "'Yo que tú, no iría' means…", options: ["I wouldn't go", "If I were you, I wouldn't go", "You shouldn't have gone", "I don't want to go"], correct: 1 },
      { q: "Which form is correctly accented?", options: ["comeria", "comería", "cómeria", "comeriá"], correct: 1 },
      { q: "The conditional of 'querer' (yo) is…", options: ["quiero", "querré", "querría", "quisiera"], correct: 2 },
      { q: "'Sería mejor llamarlo' means…", options: ["It is better to call him", "It would be better to call him", "It was better to call him", "Call him, it's better"], correct: 1 },
    ],
  },
};
