import type { Unit } from "../../types";

export const UNIT_SUBJUNCTIVE: Unit = {
  slug: "subjunctive",
  stage: 8,
  order: 34,
  icon: "🤔",
  title: "Subjunctive intro",
  tagline: "Espero que, quiero que — common trigger verbs.",
  badge: "advanced",
  lessons: [
    {
      slug: "subjunctive-intro",
      title: "What the subjunctive is",
      estMinutes: 12,
      pages: [
        {
          type: "intro",
          heading: "The subjunctive — expressing wishes and doubts",
          body: [
            "The subjunctive is a mood (not a tense) that expresses subjectivity: wishes, doubts, emotions, and hypotheticals. It sounds intimidating but the most common uses are formulaic — learn the triggers and the rest follows.",
            "The present subjunctive is formed by taking the yo present tense form, dropping the -o, and adding opposite vowel endings: -ar verbs get -e endings; -er/-ir verbs get -a endings.",
          ],
          keyPoint: "-ar subjunctive: -e/-es/-e/-emos/-éis/-en · -er/-ir subjunctive: -a/-as/-a/-amos/-áis/-an",
        },
        {
          type: "tip",
          heading: "The 'WEIRDO' triggers",
          body: "The subjunctive is triggered after verbs of: <strong>W</strong>ishes (querer que, desear que), <strong>E</strong>motions (alegrarse de que, tener miedo de que), <strong>I</strong>mpersonal expressions (es importante que), <strong>R</strong>ecommendations (recomendar que), <strong>D</strong>oubt (dudar que), <strong>O</strong>jalá. Plus: after 'que' with subject change.",
          example: { l1: "Quiero que vengas. / Espero que estés bien.", en: "I want you to come. / I hope you're well." },
        },
        {
          type: "vocab",
          heading: "Common subjunctive triggers",
          items: [
            { l1: "Quiero que…", en: "I want… (that)", note: "Subject change required" },
            { l1: "Espero que…", en: "I hope that…" },
            { l1: "Es importante que…", en: "It's important that…" },
            { l1: "Me alegra que…", en: "I'm glad that…" },
            { l1: "Ojalá…", en: "I hope… / If only… (+ subjunctive always)" },
            { l1: "Recomienda que…", en: "He/she recommends that…" },
            { l1: "Dudo que…", en: "I doubt that…" },
            { l1: "No creo que…", en: "I don't think that… (doubt triggers subjunctive)" },
          ],
        },
        {
          type: "vocab",
          heading: "Subjunctive in sentences",
          items: [
            { l1: "Espero que vengas.", en: "I hope you come." },
            { l1: "Quiero que seas feliz.", en: "I want you to be happy." },
            { l1: "Es importante que comas bien.", en: "It's important that you eat well." },
            { l1: "Ojalá haga buen tiempo.", en: "I hope the weather's good." },
            { l1: "No creo que sea verdad.", en: "I don't think it's true." },
            { l1: "Me alegra que estés aquí.", en: "I'm glad you're here." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Subjunctive check",
          questions: [
            {
              q: "'Espero que' triggers the subjunctive because it expresses…",
              options: ["A completed action", "A wish/hope (uncertain outcome)", "A fact", "A command"],
              correct: 1,
              fb: "Espero que = I hope that. Hope implies uncertainty → subjunctive.",
            },
            {
              q: "After 'Ojalá', you always use…",
              options: ["Indicative (normal present)", "Infinitive", "Subjunctive", "Future"],
              correct: 2,
              fb: "Ojalá always takes the subjunctive. Ojalá haga buen tiempo = I hope the weather is good.",
            },
            {
              q: "Why does 'No creo que sea verdad' use subjunctive?",
              options: ["'No creo' expresses doubt", "'Que' always triggers subjunctive", "Sea is irregular present", "It's a question"],
              correct: 0,
              fb: "No creer = to doubt/not think. Doubt triggers subjunctive.",
            },
          ],
        },
        {
          type: "tip",
          heading: "Indicative (fact) vs subjunctive (opinion)",
          body: "Spanish tracks whether you're stating a fact or an opinion. <em>Sé que Marta es médica.</em> = I know Marta is a doctor → certainty → indicative (es). <em>No creo que Marta sea médica.</em> = I don't think Marta is a doctor → doubt → subjunctive (sea). Verbs like <em>saber que</em>, <em>creer que</em>, <em>es verdad que</em> stay indicative because they assert a fact. Negate or doubt them — <em>no creo que</em>, <em>dudo que</em>, <em>no es verdad que</em> — and they flip to subjunctive.",
          example: { l1: "Creo que tiene razón. / No creo que tenga razón.", en: "I think he's right. / I don't think he's right." },
        },
        {
          type: "orderWords",
          heading: "Build the sentence",
          intro: "Put the words in order. Remember: trigger + que + subject + subjunctive verb.",
          items: [
            { tokens: ["Espero", "que", "vengas", "a", "la", "fiesta"], en: "I hope you come to the party." },
            { tokens: ["Quiero", "que", "seas", "feliz"], en: "I want you to be happy." },
            { tokens: ["No", "creo", "que", "tengan", "razón"], en: "I don't think they're right." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I hope you're well. I want you to come.",
          reference: "Espero que estés bien. Quiero que vengas.",
          hint: "'Espero que' + subjunctive → estés (estar). 'Quiero que' + subjunctive → vengas (venir).",
        },
      ],
    },
    {
      slug: "subjunctive-forms",
      title: "Subjunctive forms",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Build it from the 'yo' form, then swap the vowel",
          body: [
            "The reliable recipe: take the present-tense <strong>yo</strong> form, drop the <strong>-o</strong>, and add the 'opposite' vowel endings.",
            "<strong>-ar verbs</strong> use <strong>-e</strong> endings: -e, -es, -e, -emos, -éis, -en. <em>hablar → hablo → habl- → hable</em>.",
            "<strong>-er / -ir verbs</strong> use <strong>-a</strong> endings: -a, -as, -a, -amos, -áis, -an. <em>comer → como → com- → coma</em>; <em>vivir → vivo → viv- → viva</em>.",
            "Because it starts from the <strong>yo</strong> form, stem changes and irregular yo-forms carry over automatically: <em>tener → tengo → tenga</em>; <em>hacer → hago → haga</em>; <em>decir → digo → diga</em>; <em>conocer → conozco → conozca</em>.",
          ],
          keyPoint: "Drop the -o off the yo form, then add -e endings (-ar) or -a endings (-er/-ir). Irregular yo-stems carry over: tengo → tenga.",
        },
        {
          type: "conjugation",
          heading: "hablar — present subjunctive",
          verb: "hablar",
          meaning: "to speak",
          tenses: [{ name: "Subjuntivo presente", forms: [
            { person: "yo", form: "hable" },
            { person: "tú", form: "hables" },
            { person: "él/ella/usted", form: "hable" },
            { person: "nosotros", form: "hablemos" },
            { person: "vosotros", form: "habléis" },
            { person: "ellos/ustedes", form: "hablen" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "comer & vivir — the -er/-ir family",
          verb: "comer / vivir",
          meaning: "to eat / to live",
          intro: "Both -er and -ir verbs share the same -a endings in the present subjunctive.",
          tenses: [{ name: "Subjuntivo presente", forms: [
            { person: "yo", form: "coma / viva", en: "I eat / live" },
            { person: "tú", form: "comas / vivas", en: "you" },
            { person: "él/ella/usted", form: "coma / viva", en: "he/she/you (formal)" },
            { person: "nosotros", form: "comamos / vivamos", en: "we" },
            { person: "vosotros", form: "comáis / viváis", en: "you all" },
            { person: "ellos/ustedes", form: "coman / vivan", en: "they/you all" },
          ] }],
        },
        {
          type: "conjugation",
          heading: "The six irregular essentials",
          verb: "ser / ir / haber / saber / dar / estar",
          meaning: "irregular present subjunctive",
          intro: "These six don't follow the yo-form rule. Memorize them — they appear constantly after espero que, ojalá, no creo que.",
          tenses: [{ name: "yo / nosotros forms", forms: [
            { person: "ser", form: "sea — seamos", en: "to be (essence)" },
            { person: "ir", form: "vaya — vayamos", en: "to go" },
            { person: "haber", form: "haya — hayamos", en: "there to be / aux." },
            { person: "saber", form: "sepa — sepamos", en: "to know" },
            { person: "dar", form: "dé — demos", en: "to give (note accent on dé)" },
            { person: "estar", form: "esté — estemos", en: "to be (state); accents: esté, estés…" },
          ] }],
        },
        {
          type: "vocab",
          heading: "Key irregular subjunctives",
          items: [
            { l1: "ser → sea, seas, sea, seamos, seáis, sean", en: "to be (ser)" },
            { l1: "estar → esté, estés, esté, estemos, estéis, estén", en: "to be (estar)" },
            { l1: "ir → vaya, vayas, vaya, vayamos, vayáis, vayan", en: "to go" },
            { l1: "tener → tenga, tengas, tenga…", en: "to have" },
            { l1: "venir → venga, vengas, venga…", en: "to come" },
            { l1: "hacer → haga, hagas, haga…", en: "to do/make" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Subjunctive forms",
          questions: [
            {
              q: "'Espero que vengas' — 'vengas' is the subjunctive of…",
              options: ["venir (to come)", "ver (to see)", "vencer (to overcome)", "volar (to fly)"],
              correct: 0,
              fb: "Venir → venga (yo subj.) → vengas (tú subj.). Espero que vengas = I hope you come.",
            },
            {
              q: "'Ojalá haga buen tiempo' — 'haga' is the subjunctive of…",
              options: ["haber", "hablar", "hacer", "hallar"],
              correct: 2,
              fb: "Hacer → haga (present subjunctive). Ojalá haga calor = I hope it's warm.",
            },
          ],
        },
        {
          type: "fillBlank",
          heading: "Conjugate the subjunctive",
          intro: "Pick the present-subjunctive form that fits the trigger.",
          items: [
            {
              template: "Espero que ___ pronto. (llegar — tú)",
              answer: "llegues",
              en: "I hope you arrive soon.",
              options: ["llegas", "llegues", "llegarás", "llegaste"],
            },
            {
              template: "Es importante que ___ bien. (comer — tú)",
              answer: "comas",
              en: "It's important that you eat well.",
              options: ["comes", "comas", "comerás", "comías"],
            },
            {
              template: "No creo que ___ verdad. (ser)",
              answer: "sea",
              en: "I don't think it's true.",
              options: ["es", "sea", "era", "será"],
            },
            {
              template: "Quiero que (tú) ___ a casa. (ir)",
              answer: "vayas",
              en: "I want you to go home.",
              options: ["vas", "vayas", "irás", "ibas"],
            },
            {
              template: "Ojalá ___ buen tiempo mañana. (hacer)",
              answer: "haga",
              en: "I hope the weather's good tomorrow.",
              options: ["hace", "haga", "hará", "hacía"],
            },
            {
              template: "Me alegra que ___ aquí. (estar — tú)",
              answer: "estés",
              en: "I'm glad you're here.",
              options: ["estás", "estés", "estarás", "estabas"],
            },
            {
              template: "Es mejor que (ellos) ___ ahora. (salir)",
              answer: "salgan",
              en: "It's better that they leave now.",
              options: ["salen", "salgan", "saldrán", "salían"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "It's important that you eat well and sleep eight hours.",
          reference: "Es importante que comas bien y duermas ocho horas.",
          hint: "'Es importante que' + subjunctive → comas (comer), duermas (dormir, stem o→ue).",
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I don't think she knows the answer.",
          reference: "No creo que (ella) sepa la respuesta.",
          hint: "'No creo que' expresses doubt → subjunctive. saber → sepa.",
        },
      ],
    },
    {
      slug: "subjunctive-in-use",
      title: "Subjunctive in natural conversation",
      estMinutes: 10,
      pages: [
        {
          type: "vocab",
          heading: "More subjunctive trigger phrases",
          items: [
            { l1: "Que te mejores.", en: "Get well soon. (lit. may you get better — wishes)" },
            { l1: "Que descanses.", en: "Rest well / sleep well." },
            { l1: "Que te lo pases bien.", en: "Have a good time." },
            { l1: "Busco una persona que sepa cocinar.", en: "I'm looking for someone who can cook. (relative clause + unknown referent)" },
            { l1: "Cuando llegues, llámame.", en: "When you arrive, call me. (future event + subjunctive)" },
            { l1: "Para que entiendas…", en: "So that you understand… (purpose clause)" },
          ],
        },
        {
          type: "tip",
          heading: "Que + subjunctive = wishes and toasts",
          body: "Short phrases starting with <em>Que</em> + subjunctive are common social formulae. They express a wish for someone. <em>¡Que te vaya bien!</em> (may things go well for you) <em>¡Que aproveche!</em> (enjoy your meal) <em>¡Que cumplas muchos más!</em> (many happy returns).",
          example: { l1: "¡Que te mejores pronto!", en: "Get well soon! (lit. may you get better soon)" },
        },
        {
          type: "multipleChoice",
          heading: "Subjunctive in real life",
          questions: [
            {
              q: "'Cuando llegues' uses subjunctive because…",
              options: ["Llegar is irregular", "'Cuando' always takes subjunctive", "It refers to a future event that hasn't happened yet", "It's a wish"],
              correct: 2,
              fb: "Cuando + future action = subjunctive. The arrival hasn't happened yet. Once it happens, you'd use indicative: cuando llegué (when I arrived — definite past).",
            },
            {
              q: "'Busco una persona que sepa cocinar' uses subjunctive because…",
              options: ["Buscar is special", "The person is hypothetical / not specific yet", "Cocinar is irregular", "It's a command"],
              correct: 1,
              fb: "Unknown/hypothetical referent → subjunctive. If you knew a specific person: busco a María, que sabe cocinar (indicative).",
            },
          ],
        },
        {
          type: "tip",
          heading: "Time, purpose, and 'before' clauses",
          body: "Three more reliable triggers. <em>cuando</em> + a future event takes subjunctive: <em>Cuando llegues, llámame</em> (when you arrive — hasn't happened). But a habitual or past 'when' stays indicative: <em>Cuando llego, siempre como</em> (whenever I arrive). <em>para que</em> (so that) and <em>antes de que</em> (before) <strong>always</strong> take subjunctive because the second action hasn't happened yet.",
          example: { l1: "Te lo explico para que entiendas, antes de que sea tarde.", en: "I'll explain it so you understand, before it's too late." },
        },
        {
          type: "dialogue",
          heading: "Subjunctive in real conversation",
          setup: "Two friends planning the evening.",
          lines: [
            { speaker: "Lucía", l1: "¿Crees que Pablo venga esta noche?", en: "Do you think Pablo's coming tonight?" },
            { speaker: "Tú", l1: "Espero que sí, pero no estoy seguro de que pueda.", en: "I hope so, but I'm not sure he can." },
            { speaker: "Lucía", l1: "Es raro que no nos haya dicho nada todavía.", en: "It's strange he hasn't told us anything yet." },
            { speaker: "Tú", l1: "Quizá esté trabajando. Cuando termine, seguro que nos escribe.", en: "Maybe he's working. When he finishes, he'll surely text us." },
            { speaker: "Lucía", l1: "Vale. Ojalá llegue antes de que cerremos la cocina.", en: "Okay. I hope he gets here before we close the kitchen." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Triggers in context",
          intro: "Choose the subjunctive form after each trigger.",
          items: [
            {
              template: "Cuando ___ a casa, descansa. (llegar — tú)",
              answer: "llegues",
              en: "When you get home, rest.",
              options: ["llegas", "llegues", "llegarás", "llegabas"],
            },
            {
              template: "Te lo digo para que lo ___ . (saber — tú)",
              answer: "sepas",
              en: "I'm telling you so that you know it.",
              options: ["sabes", "sepas", "sabrás", "sabías"],
            },
            {
              template: "Llámame antes de que ___ . (salir — tú)",
              answer: "salgas",
              en: "Call me before you leave.",
              options: ["sales", "salgas", "saldrás", "salías"],
            },
            {
              template: "Ojalá ___ todo bien. (ir)",
              answer: "vaya",
              en: "I hope everything goes well.",
              options: ["va", "vaya", "irá", "iba"],
            },
            {
              template: "Me alegro de que ___ aquí. (estar — vosotros)",
              answer: "estéis",
              en: "I'm glad you all are here.",
              options: ["estáis", "estéis", "estaréis", "estabais"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Reorder the conversation",
          intro: "Arrange each sentence. Trigger first, then que, then the subjunctive clause.",
          items: [
            { tokens: ["Cuando", "llegues", "llámame"], en: "When you arrive, call me." },
            { tokens: ["Ojalá", "haga", "buen", "tiempo"], en: "I hope the weather's good." },
            { tokens: ["Te", "lo", "explico", "para", "que", "entiendas"], en: "I'll explain it so you understand." },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "When you finish, call me. I hope everything goes well.",
          reference: "Cuando termines, llámame. Ojalá vaya todo bien.",
          hint: "'Cuando' + future event → subjunctive (termines). 'Ojalá' always → subjunctive (vaya).",
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I'm looking for someone who can cook and speaks Spanish.",
          reference: "Busco a alguien que sepa cocinar y hable español.",
          hint: "Hypothetical/unknown person → subjunctive: sepa (saber), hable (hablar).",
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "l1-to-en",
          prompt: "Es mejor que descanses antes de que sea muy tarde.",
          reference: "It's better that you rest before it gets very late.",
          hint: "'Es mejor que' and 'antes de que' both trigger the subjunctive.",
        },
        {
          type: "tip",
          heading: "Imperfect subjunctive — coming later",
          body: "There's also the <em>imperfecto de subjuntivo</em> for hypotheticals and 'if' clauses about the past or unreal present: <em>Si fuera rico…</em> = If I were rich… The forms (fuera, tuviera, hablara, comiera) build off the <strong>ellos</strong> preterite stem. Save it for later — present subjunctive covers most of what you'll need now.",
          example: { l1: "Si tuviera tiempo, viajaría más.", en: "If I had time, I'd travel more." },
        },
      ],
    }
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      { q: "The subjunctive is triggered by expressions of…", options: ["Facts and certainties", "Wishes, doubts, emotions", "Past events", "Future certainties"], correct: 1 },
      { q: "'Ojalá' always takes…", options: ["Indicative", "Infinitive", "Conditional", "Subjunctive"], correct: 3 },
      { q: "The subjunctive of hablar (yo) is…", options: ["hablo", "hable", "hablaré", "hablaría"], correct: 1 },
      { q: "The subjunctive of ser (yo) is…", options: ["soy", "era", "sea", "sería"], correct: 2 },
      { q: "The subjunctive of ir (yo) is…", options: ["iba", "vaya", "iría", "voy"], correct: 1 },
      { q: "'No creo que…' takes the subjunctive because…", options: ["Que always takes subjunctive", "No creer expresses doubt", "Creer is irregular", "It's a question"], correct: 1 },
      { q: "'Espero que estés bien' — estés is subjunctive of…", options: ["ser", "estar", "tener", "ir"], correct: 1 },
      { q: "-ar verbs in the subjunctive use which vowel?", options: ["-a endings", "-e endings", "-o endings", "-i endings"], correct: 1 },
      { q: "The subjunctive of venir (yo) is…", options: ["vine", "vengo", "venga", "vendría"], correct: 2 },
      { q: "'Es importante que comas bien' — comas is subjunctive of…", options: ["cocer", "comer", "comprar", "conocer"], correct: 1 },
    ],
  },
};
