import type { Unit } from "../../types";

export const UNIT_OPINIONS: Unit = {
  slug: "opinions",
  stage: 8,
  order: 35,
  icon: "🗣️",
  title: "Opinions & debate",
  tagline: "'In my opinion', 'I agree/disagree', 'on the other hand'.",
  badge: "advanced",
  lessons: [
    {
      slug: "opinions-giving",
      title: "Giving an opinion",
      summary: "Natural ways to say what you think.",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "More than just 'I think…'",
          body: [
            "Saying <em>I think</em> over and over sounds flat. Native speakers vary their openers — here are the most useful ones.",
            "<strong>In my opinion, …</strong> — neutral and clear, good for any situation.",
            "<strong>Personally, …</strong> — signals it's your own view, not a fact.",
            "<strong>I reckon …</strong> — very common in informal British English (= I think / I believe).",
            "<strong>If you ask me, …</strong> — informal, slightly confiding.",
            "<strong>I'd say (that) …</strong> — soft and tentative, leaves room for others.",
            "<strong>As far as I'm concerned, …</strong> — emphatic; this is how it looks to me.",
          ],
          keyPoint:
            "In my opinion / Personally / I reckon (informal) / If you ask me / I'd say… / As far as I'm concerned…",
        },
        {
          type: "vocab",
          heading: "Opinion openers",
          intro: "Mix these in so you don't repeat 'I think'.",
          items: [
            { l1: "In my opinion, …", en: "neutral, all-purpose" },
            { l1: "Personally, …", en: "stresses it's your own view" },
            { l1: "I reckon (that) …", en: "informal British 'I think'" },
            { l1: "If you ask me, …", en: "informal, a bit confiding" },
            { l1: "I'd say (that) …", en: "soft, tentative" },
            { l1: "As far as I'm concerned, …", en: "emphatic personal view" },
            { l1: "From my point of view, …", en: "= the way I see it" },
            { l1: "To be honest, …", en: "introduces a frank opinion" },
            { l1: "It seems to me (that) …", en: "cautious, observational" },
            { l1: "I'm convinced (that) …", en: "very strong, no doubt" },
          ],
        },
        {
          type: "dialogue",
          heading: "Chatting about a new café",
          setup: "Two colleagues compare a new spot near the office.",
          lines: [
            { speaker: "Dan", l1: "Have you tried the new café on the corner?", en: "Setting up the topic." },
            { speaker: "Eve", l1: "I have. Personally, I think it's a bit overpriced.", en: "Personally — own view." },
            { speaker: "Dan", l1: "Really? If you ask me, the coffee's the best around here.", en: "If you ask me — informal opinion." },
            { speaker: "Eve", l1: "I'd say the coffee's good, but four pounds is a lot.", en: "I'd say — tentative." },
            { speaker: "Dan", l1: "To be honest, I'd pay it for a quiet table in the morning.", en: "To be honest — frank view." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Choose the opener",
          intro: "Pick the phrase that fits the register.",
          items: [
            {
              template: "___ , the film was far too long.",
              answer: "In my opinion",
              en: "Neutral, all-purpose opener.",
              options: ["In my opinion", "I'm agree", "By my opinion", "On my opinion"],
            },
            {
              template: "___ , this is the best curry in London.",
              answer: "I reckon",
              en: "Informal British 'I think'.",
              options: ["I reckon", "I am think", "By me", "In my think"],
            },
            {
              template: "As far as I'm ___ , the plan won't work.",
              answer: "concerned",
              en: "Set phrase: as far as I'm concerned.",
              options: ["concerned", "concern", "thinking", "opinion"],
            },
            {
              template: "___ , I'd choose the cheaper option.",
              answer: "Personally",
              en: "Stresses it's your own view.",
              options: ["Personally", "Personal", "By person", "In person"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Say it in English",
          direction: "en-to-l1",
          prompt: "Give your honest opinion that, personally, the city is too crowded.",
          reference: "Personally, I think the city is too crowded.",
          hint: "Start with 'Personally,' to flag it as your own view.",
        },
      ],
    },
    {
      slug: "opinions-agree-disagree",
      title: "Agreeing & disagreeing politely",
      summary: "How to push back without sounding rude.",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Disagreeing without being rude",
          body: [
            "In British English, disagreement is usually <em>softened</em>. Bluntly saying <em>'You're wrong'</em> sounds aggressive — so we cushion it.",
            "<strong>Agreeing:</strong> <em>I agree.</em> · <em>Exactly.</em> · <em>That's a good point.</em> · <em>So do I / Me too.</em> · <em>You're absolutely right.</em>",
            "<strong>Disagreeing politely:</strong> <em>I see your point, but…</em> · <em>I'm not sure I agree.</em> · <em>I take your point, however…</em> · <em>That's true, but…</em> · <em>I'm afraid I disagree.</em>",
            "Notice the pattern: <strong>acknowledge first</strong> (<em>I see your point</em>), then <strong>add 'but / however'</strong>, then give your view. That single move makes disagreement feel respectful.",
          ],
          keyPoint:
            "Agree: I agree / Exactly / That's a good point. Disagree politely: acknowledge ('I see your point') + but/however + your view.",
        },
        {
          type: "vocab",
          heading: "Agreeing & disagreeing",
          intro: "Phrases for the two halves of a discussion.",
          items: [
            { l1: "I completely agree.", en: "strong agreement" },
            { l1: "That's a good point.", en: "concedes the other side has merit" },
            { l1: "Exactly. / Absolutely.", en: "enthusiastic agreement" },
            { l1: "So do I. / Me too.", en: "agreeing you feel the same" },
            { l1: "I see your point, but…", en: "polite lead-in to disagreement" },
            { l1: "I'm not sure I agree.", en: "gentle disagreement" },
            { l1: "I take your point, however…", en: "formal, respectful pushback" },
            { l1: "That's true, but…", en: "partial agreement then a counter" },
            { l1: "I'm afraid I disagree.", en: "polite but clear 'no'" },
            { l1: "I beg to differ.", en: "formal/old-fashioned disagreement" },
          ],
        },
        {
          type: "tip",
          heading: "Soften, don't sharpen",
          body: "Compare <em>'You're wrong'</em> (harsh) with <em>'I see what you mean, but I'm not sure I agree'</em> (polite). The British habit is to <strong>acknowledge</strong> the other person before you push back, and to use hedging words like <em>'I'm afraid', 'maybe', 'I'm not sure'</em>. Attack the <strong>idea</strong>, never the person.",
          example: { l1: "I take your point, but I'd argue the opposite.", en: "Acknowledge, then disagree on the idea." },
        },
        {
          type: "dialogue",
          heading: "Debating remote work",
          setup: "Two friends discuss working from home.",
          lines: [
            { speaker: "Leo", l1: "I reckon working from home is far more productive.", en: "Opinion opener." },
            { speaker: "Nadia", l1: "I see your point, but I'm not sure I agree. I miss the team.", en: "Acknowledge + but + view." },
            { speaker: "Leo", l1: "That's a fair point. Still, the commute wastes hours.", en: "Concede, then counter." },
            { speaker: "Nadia", l1: "True, but a hybrid week gives you the best of both.", en: "Partial agreement + counter." },
            { speaker: "Leo", l1: "Actually, I think you're right about that.", en: "Coming round to agreement." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Polite or not?",
          intro: "Choose the response that sounds polite in British English.",
          questions: [
            {
              q: "Which is the most polite way to disagree?",
              options: [
                "You're completely wrong.",
                "That's nonsense.",
                "I see your point, but I'm not sure I agree.",
                "No way.",
              ],
              correct: 2,
              fb: "Acknowledging first ('I see your point') makes disagreement respectful.",
            },
            {
              q: "Your friend says 'I love this band.' You feel the same. You say:",
              options: ["So do I!", "I'm afraid I disagree.", "I take your point.", "I beg to differ."],
              correct: 0,
              fb: "'So do I' shows you share the feeling.",
            },
            {
              q: "Which phrase concedes the other side has merit before you counter?",
              options: ["You're wrong, but…", "That's a good point, but…", "No, but…", "Rubbish, but…"],
              correct: 1,
              fb: "'That's a good point, but…' acknowledges then pushes back politely.",
            },
          ],
        },
        {
          type: "translate",
          heading: "Say it in English",
          direction: "en-to-l1",
          prompt: "Politely tell someone you see their point but you don't fully agree.",
          reference: "I see your point, but I'm not sure I agree.",
          hint: "Acknowledge first ('I see your point'), then soften with 'I'm not sure I agree'.",
        },
      ],
    },
    {
      slug: "opinions-structuring-argument",
      title: "Structuring an argument",
      summary: "Connectors that organise a real discussion.",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Organising your points",
          body: [
            "To sound fluent in a discussion, structure your ideas with <em>connectors</em> rather than listing them flatly.",
            "<strong>Open / list:</strong> <em>First of all… · Secondly… · What's more / Furthermore…</em>",
            "<strong>Give a balanced view:</strong> <em>On the one hand… on the other hand…</em>",
            "<strong>Concede & counter:</strong> <em>That said… · However… · Even so…</em>",
            "<strong>Add evidence:</strong> <em>For instance… · For example…</em>",
            "<strong>Conclude:</strong> <em>All in all… · To sum up… · Overall…</em>",
            "The classic balanced structure is <strong>'On the one hand… on the other hand… To sum up…'</strong> — it shows you've weighed both sides before reaching a conclusion.",
          ],
          keyPoint:
            "List: First of all → Secondly → Furthermore. Balance: On the one hand… on the other hand. Conclude: To sum up / All in all.",
        },
        {
          type: "vocab",
          heading: "Discourse connectors",
          intro: "Words that link your argument together.",
          items: [
            { l1: "First of all, …", en: "your first point" },
            { l1: "Secondly, … / Then, …", en: "your next point" },
            { l1: "What's more, … / Furthermore, …", en: "adds a stronger point" },
            { l1: "For instance, …", en: "introduces an example" },
            { l1: "On the one hand, …", en: "first side of an argument" },
            { l1: "On the other hand, …", en: "the opposite side" },
            { l1: "However, …", en: "contrasts with what came before" },
            { l1: "That said, …", en: "concedes, then qualifies" },
            { l1: "All in all, … / Overall, …", en: "sums up the whole" },
            { l1: "To sum up, …", en: "final concluding phrase" },
          ],
        },
        {
          type: "dialogue",
          heading: "Should London ban cars in the centre?",
          setup: "A discussion at a dinner party.",
          lines: [
            { speaker: "Host", l1: "So, should we ban cars from central London?", en: "Opening the debate." },
            { speaker: "You", l1: "On the one hand, it would cut pollution and make the streets safer.", en: "On the one hand — first side." },
            { speaker: "Guest", l1: "That's a good point. On the other hand, what about people with mobility issues?", en: "Concede + other hand." },
            { speaker: "You", l1: "True. However, we could keep access for taxis and disabled drivers.", en: "However — counter." },
            { speaker: "Guest", l1: "Fair enough. For instance, that's how some European cities do it.", en: "For instance — evidence." },
            { speaker: "You", l1: "Exactly. To sum up, a partial ban seems like the sensible middle ground.", en: "To sum up — conclusion." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Pick the connector",
          intro: "Choose the linking word that fits.",
          items: [
            {
              template: "___ , the price is too high.",
              answer: "First of all",
              en: "Opening the first point.",
              options: ["First of all", "To sum up", "However", "For instance"],
            },
            {
              template: "On the one hand it's cheap; ___ the other hand, it breaks easily.",
              answer: "on",
              en: "The balanced pair: on the one hand… on the other hand.",
              options: ["on", "in", "by", "at"],
            },
            {
              template: "It's a great city. ___ , it can be expensive.",
              answer: "However",
              en: "Contrasts with the previous point.",
              options: ["However", "For instance", "First of all", "What's more"],
            },
            {
              template: "___ , I think the plan is worth trying.",
              answer: "To sum up",
              en: "Concluding the argument.",
              options: ["To sum up", "First of all", "For instance", "On the one hand"],
            },
            {
              template: "It's reliable. ___ , it's very cheap to run.",
              answer: "What's more",
              en: "Adds a further supporting point.",
              options: ["What's more", "However", "To sum up", "On the other hand"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the argument",
          intro: "Put the words in the correct order.",
          items: [
            { tokens: ["On", "the", "one", "hand", ",", "it's", "cheaper"], en: "On the one hand, it's cheaper." },
            { tokens: ["On", "the", "other", "hand", ",", "it's", "slower"], en: "On the other hand, it's slower." },
            { tokens: ["To", "sum", "up", ",", "I", "think", "it's", "worth", "it"], en: "To sum up, I think it's worth it." },
            { tokens: ["However", ",", "the", "service", "could", "be", "better"], en: "However, the service could be better." },
          ],
        },
        {
          type: "translate",
          heading: "Say it in English",
          direction: "en-to-l1",
          prompt: "Give a balanced view: on the one hand it's cheap, on the other hand it's unreliable. Then sum up that overall you'd still recommend it.",
          reference: "On the one hand it's cheap, but on the other hand it's unreliable. To sum up, overall I'd still recommend it.",
          hint: "Stack three connectors: 'On the one hand… on the other hand… To sum up…'.",
        },
        {
          type: "checkpoint",
          heading: "Lesson check",
          questions: [
            {
              q: "Which phrase introduces the opposite side of an argument?",
              options: ["First of all", "On the other hand", "For instance", "What's more"],
              correct: 1,
            },
            {
              q: "Which phrase concludes an argument?",
              options: ["First of all", "On the one hand", "To sum up", "For instance"],
              correct: 2,
            },
            {
              q: "Which introduces an example?",
              options: ["However", "For instance", "To sum up", "Secondly"],
              correct: 1,
            },
            {
              q: "Complete: 'It's reliable. ___ , it's cheap to run.'",
              options: ["What's more", "However", "On the other hand", "To sum up"],
              correct: 0,
            },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'In my opinion' is best described as:",
        options: [
          "a way to agree",
          "a neutral opinion opener",
          "a way to disagree",
          "a concluding phrase",
        ],
        correct: 1,
      },
      {
        q: "'I reckon…' is:",
        options: [
          "formal written English",
          "informal British 'I think'",
          "a way to disagree",
          "a concluding phrase",
        ],
        correct: 1,
      },
      {
        q: "Which is the most polite way to disagree?",
        options: [
          "You're wrong.",
          "That's nonsense.",
          "I see your point, but I'm not sure I agree.",
          "No way.",
        ],
        correct: 2,
      },
      {
        q: "'So do I' means:",
        options: [
          "I disagree",
          "I feel the same way",
          "I'm not sure",
          "in conclusion",
        ],
        correct: 1,
      },
      {
        q: "The classic balanced structure is:",
        options: [
          "First of all… secondly… thirdly…",
          "On the one hand… on the other hand…",
          "For instance… for example…",
          "However… however… however…",
        ],
        correct: 1,
      },
      {
        q: "Which phrase introduces an example?",
        options: ["However", "For instance", "To sum up", "On the other hand"],
        correct: 1,
      },
      {
        q: "Which phrase concludes an argument?",
        options: ["First of all", "On the one hand", "To sum up", "What's more"],
        correct: 2,
      },
      {
        q: "'I take your point, however…' is used to:",
        options: [
          "agree completely",
          "acknowledge, then disagree politely",
          "change the subject",
          "give an example",
        ],
        correct: 1,
      },
      {
        q: "Complete: 'It's a lovely flat. ___ , it's very expensive.'",
        options: ["What's more", "However", "For instance", "So do I"],
        correct: 1,
      },
      {
        q: "Which response is impolite in British English?",
        options: [
          "I'm afraid I disagree.",
          "That's a good point, but…",
          "You're completely wrong.",
          "I'm not sure I agree.",
        ],
        correct: 2,
      },
    ],
  },
};
