import type { Unit } from "../../types";

export const UNIT_NUMBERS_TIME: Unit = {
  slug: "numbers-time",
  stage: 1,
  order: 3,
  icon: "🔢",
  title: "Numbers, days & time",
  tagline: "0–1000, dates, telling time, prices. The numbers you'll quote and hear every day in Rome.",
  badge: "tourist",
  lessons: [
    {
      slug: "numbers-0-100",
      title: "Numbers 0 to 100",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Italian numbers compound predictably",
          body: [
            "Italian numbers 1–20 are mostly unique, like English. From 21 onward, they're just \"twenty-one,\" \"twenty-two\" stuck together as a single word: <em>ventuno, ventidue</em>.",
            "Two rules to remember: when adding <strong>uno</strong> or <strong>otto</strong> to a tens word (venti, trenta, ...), drop the final vowel: <em>vent</em>uno (not venti-uno), <em>trent</em>otto.",
            "Hundreds are formed with <em>cento</em>: 100 = cento, 200 = duecento, 300 = trecento. <em>Mille</em> = 1000, <em>duemila</em> = 2000.",
          ],
          tip: {
            label: "Prices are spoken whole",
            body: "When a cashier says <em>quattro e cinquanta</em>, that's €4.50 — \"four and fifty.\" The currency unit is implied. <em>Otto e venti</em> = €8.20.",
          },
        },
        {
          type: "vocab",
          heading: "1 to 20 — memorize these",
          items: [
            { l1: "uno", en: "one" },
            { l1: "due", en: "two" },
            { l1: "tre", en: "three" },
            { l1: "quattro", en: "four" },
            { l1: "cinque", en: "five" },
            { l1: "sei", en: "six" },
            { l1: "sette", en: "seven" },
            { l1: "otto", en: "eight" },
            { l1: "nove", en: "nine" },
            { l1: "dieci", en: "ten" },
            { l1: "undici", en: "eleven" },
            { l1: "dodici", en: "twelve" },
            { l1: "tredici", en: "thirteen" },
            { l1: "quattordici", en: "fourteen" },
            { l1: "quindici", en: "fifteen" },
            { l1: "sedici", en: "sixteen" },
            { l1: "diciassette", en: "seventeen" },
            { l1: "diciotto", en: "eighteen" },
            { l1: "diciannove", en: "nineteen" },
            { l1: "venti", en: "twenty" },
          ],
        },
        {
          type: "vocab",
          heading: "Tens, hundreds, and thousand",
          items: [
            { l1: "venti", en: "twenty" },
            { l1: "trenta", en: "thirty" },
            { l1: "quaranta", en: "forty" },
            { l1: "cinquanta", en: "fifty" },
            { l1: "sessanta", en: "sixty" },
            { l1: "settanta", en: "seventy" },
            { l1: "ottanta", en: "eighty" },
            { l1: "novanta", en: "ninety" },
            { l1: "cento", en: "one hundred" },
            { l1: "duecento", en: "two hundred" },
            { l1: "mille", en: "one thousand" },
            { l1: "duemila", en: "two thousand", note: "Mille → mila in plurals." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Quick count",
          questions: [
            {
              q: "Which is 'twenty-one'?",
              options: ["venti uno", "ventiuno", "ventuno", "venti-uno"],
              correct: 2,
              fb: "Drop the final vowel of venti before uno: vent + uno = ventuno.",
            },
            {
              q: "How do you say 38?",
              options: ["trenta otto", "trent'otto", "trentotto", "trenta-otto"],
              correct: 2,
              fb: "Drop the final vowel of trenta before otto: trentotto.",
            },
            {
              q: "How do you say 47?",
              options: ["quarantasette", "quarant'sette", "quattro-sette", "quaranta sette"],
              correct: 0,
              fb: "Sette starts with a consonant, so no vowel drop: quaranta + sette = quarantasette.",
            },
            {
              q: "How much is '€8.50' spoken?",
              options: [
                "otto cinquanta",
                "otto e cinquanta",
                "otto punto cinquanta",
                "ottocinquanta",
              ],
              correct: 1,
              fb: "Italian uses 'e' (and) between euros and cents.",
            },
          ],
        },
      ],
    },
    {
      slug: "numbers-time-clock",
      title: "Telling time",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Che ora è? — What time is it?",
          body: [
            "To ask the time, say <strong>Che ora è?</strong> or <strong>Che ore sono?</strong> (both common — the second is technically more correct).",
            "Times use <em>è</em> only for 1 o'clock, noon and midnight: <em>È l'una</em> (it's 1), <em>È mezzogiorno</em> (it's noon), <em>È mezzanotte</em> (it's midnight).",
            "All other hours use <em>sono</em>: <em>Sono le due</em> (it's 2), <em>Sono le tre e mezza</em> (it's half past three).",
          ],
          keyPoint:
            "1pm / noon / midnight → È. Everything else → Sono le… Half past = e mezza. Quarter past = e un quarto. Quarter to = meno un quarto.",
        },
        {
          type: "vocab",
          heading: "Time vocabulary",
          items: [
            { l1: "che ora è?", en: "what time is it?" },
            { l1: "che ore sono?", en: "what time is it? (literal: what hours are they?)" },
            { l1: "l'una", en: "1 o'clock", note: "Singular — only 1 uses 'l'una'." },
            { l1: "mezzogiorno", en: "noon" },
            { l1: "mezzanotte", en: "midnight" },
            { l1: "e mezza", en: "...thirty / half past" },
            { l1: "e un quarto", en: "...quarter past" },
            { l1: "meno un quarto", en: "quarter to..." },
            { l1: "in punto", en: "on the dot / sharp" },
            { l1: "del mattino", en: "in the morning (am)" },
            { l1: "del pomeriggio", en: "in the afternoon" },
            { l1: "di sera", en: "in the evening" },
          ],
        },
        {
          type: "dialogue",
          heading: "Asking the time at the metro",
          lines: [
            { speaker: "You", l1: "Mi scusi, che ore sono?", en: "Excuse me, what time is it?" },
            { speaker: "Romano", l1: "Sono le otto e mezza.", en: "It's 8:30." },
            { speaker: "You", l1: "Grazie. A che ora parte il prossimo treno?", en: "Thanks. What time does the next train leave?" },
            { speaker: "Romano", l1: "Alle nove meno un quarto.", en: "At 8:45." },
            { speaker: "You", l1: "Perfetto, grazie mille!", en: "Perfect, thanks so much!" },
          ],
        },
        {
          type: "fillBlank",
          heading: "What time is it?",
          items: [
            {
              template: "___ le tre e un quarto.",
              answer: "Sono",
              en: "It's 3:15.",
              options: ["È", "Sono", "Ho", "Sto"],
            },
            {
              template: "È ___ — è ora di pranzo.",
              answer: "mezzogiorno",
              en: "It's noon — it's lunchtime.",
              options: ["mezzanotte", "mezzogiorno", "le dodici", "l'una"],
            },
            {
              template: "Sono le sette ___ mezza.",
              answer: "e",
              en: "It's 7:30.",
              options: ["e", "meno", "in", "le"],
            },
            {
              template: "È ___ in punto.",
              answer: "l'una",
              en: "It's exactly 1 o'clock.",
              options: ["l'una", "una", "le una", "il una"],
            },
          ],
        },
      ],
    },
    {
      slug: "numbers-days-dates",
      title: "Days, months & dates",
      estMinutes: 9,
      pages: [
        {
          type: "vocab",
          heading: "The seven days",
          intro: "Italian days are lowercase and (except for Sunday) masculine.",
          items: [
            { l1: "lunedì", en: "Monday", note: "Stress the final ì." },
            { l1: "martedì", en: "Tuesday" },
            { l1: "mercoledì", en: "Wednesday" },
            { l1: "giovedì", en: "Thursday" },
            { l1: "venerdì", en: "Friday" },
            { l1: "sabato", en: "Saturday", note: "Stress: SAH-bah-toh." },
            { l1: "domenica", en: "Sunday", note: "Feminine. Stress: doh-MEH-nee-kah." },
          ],
        },
        {
          type: "vocab",
          heading: "The twelve months",
          items: [
            { l1: "gennaio", en: "January" },
            { l1: "febbraio", en: "February" },
            { l1: "marzo", en: "March" },
            { l1: "aprile", en: "April" },
            { l1: "maggio", en: "May" },
            { l1: "giugno", en: "June" },
            { l1: "luglio", en: "July" },
            { l1: "agosto", en: "August" },
            { l1: "settembre", en: "September" },
            { l1: "ottobre", en: "October" },
            { l1: "novembre", en: "November" },
            { l1: "dicembre", en: "December" },
          ],
        },
        {
          type: "tip",
          heading: "Italian dates are day-month-year",
          body: "12/05/2026 in Italy means <strong>12 May 2026</strong>, not December 5. When spoken: <em>il dodici maggio duemilaventisei</em>. The day comes first, then the month, then the year. Today is referred to as <em>oggi</em>, tomorrow <em>domani</em>, yesterday <em>ieri</em>.",
          example: { l1: "Oggi è il 22 maggio 2026.", en: "Today is May 22, 2026." },
        },
        {
          type: "translate",
          heading: "Translate the date",
          direction: "en-to-l1",
          prompt: "Today is Friday, June 14, 2026.",
          reference: "Oggi è venerdì, 14 giugno 2026. (Oggi è venerdì, il quattordici giugno duemilaventisei.)",
          hint: "Days and months are lowercase. Dates are spoken with 'il' before the day.",
        },
        {
          type: "pronounce",
          heading: "Say these dates aloud",
          intro: "Tap the speaker to hear, then repeat.",
          items: [
            { l1: "il primo gennaio", en: "January 1st", tip: "Primo = 1st (only ordinal used for dates)." },
            { l1: "il quindici agosto", en: "August 15th", tip: "Ferragosto — Italy's biggest summer holiday." },
            { l1: "il venticinque dicembre", en: "December 25th", tip: "Natale (Christmas)." },
            { l1: "il sei gennaio duemilaventisei", en: "January 6, 2026", tip: "L'Epifania." },
          ],
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "Translate: ventotto",
        options: ["18", "28", "82", "108"],
        correct: 1,
      },
      {
        q: "How do you say 21 in Italian?",
        options: ["venti uno", "ventuno", "venti-uno", "duemila uno"],
        correct: 1,
      },
      {
        q: "What time is 'sono le sette e mezza'?",
        options: ["7:15", "7:30", "8:30", "7:45"],
        correct: 1,
      },
      {
        q: "Which is correct for '1 o'clock'?",
        options: ["Sono l'una", "Sono le una", "È l'una", "È le una"],
        correct: 2,
      },
      {
        q: "How do you say 'quarter to nine'?",
        options: [
          "le otto e un quarto",
          "le nove meno un quarto",
          "le nove e un quarto",
          "le otto meno un quarto",
        ],
        correct: 1,
      },
      {
        q: "Which day is 'mercoledì'?",
        options: ["Monday", "Tuesday", "Wednesday", "Thursday"],
        correct: 2,
      },
      {
        q: "Which month is 'giugno'?",
        options: ["June", "July", "January", "May"],
        correct: 0,
      },
      {
        q: "In Italy, the date 03/04/2026 means…",
        options: ["March 4, 2026", "April 3, 2026", "Either is fine", "Neither"],
        correct: 1,
      },
      {
        q: "What's €4.50 spoken in Italian?",
        options: [
          "quattro punto cinquanta",
          "quattro virgola cinquanta",
          "quattro e cinquanta",
          "quattro cinquanta euro",
        ],
        correct: 2,
      },
      {
        q: "How many days are stressed on the final 'ì'?",
        options: ["3", "4", "5", "6"],
        correct: 2,
      },
    ],
  },
};
