import type { Unit } from "../../types";

export const UNIT_LANDMARKS: Unit = {
  slug: "landmarks",
  stage: 3,
  order: 14,
  icon: "🏛️",
  title: "Roman landmarks",
  tagline: "Colosseo, Vaticano, Foro Romano, Trastevere — the vocabulary to actually talk about what you're seeing.",
  badge: "culture",
  lessons: [
    {
      slug: "landmarks-monuments",
      title: "The big monuments and their names",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Italian names, not English ones",
          body: [
            "Locals don't call it the Colosseum — they call it <strong>il Colosseo</strong>. Walk up to a Roman and say \"Where is the Coliseum?\" in English and you'll be understood, but you'll never sound like more than a tourist. Learn the Italian names.",
            "<em>Il Colosseo</em>, <em>il Foro Romano</em>, <em>il Pantheon</em>, <em>la Fontana di Trevi</em>, <em>la Basilica di San Pietro</em>, <em>i Musei Vaticani</em>, <em>la Cappella Sistina</em>, <em>Piazza Navona</em>, <em>Piazza di Spagna</em>, <em>Castel Sant'Angelo</em>.",
            "Roman roads have prefixes. <em>Via</em> = street. <em>Viale</em> = avenue. <em>Vicolo</em> = alley. <em>Piazza</em> = square. <em>Largo</em> = small square / open space.",
          ],
          keyPoint:
            "Italian names are gendered: il Colosseo (m), la Basilica (f), il Pantheon (m), la Cappella (f).",
        },
        {
          type: "vocab",
          heading: "Top Rome landmarks (in Italian)",
          items: [
            { l1: "il Colosseo", en: "the Colosseum" },
            { l1: "il Foro Romano", en: "the Roman Forum" },
            { l1: "il Palatino", en: "Palatine Hill" },
            { l1: "il Pantheon", en: "the Pantheon" },
            { l1: "la Fontana di Trevi", en: "the Trevi Fountain" },
            { l1: "Piazza Navona", en: "Piazza Navona" },
            { l1: "Piazza di Spagna / la scalinata", en: "Piazza di Spagna / the Spanish Steps" },
            { l1: "la Basilica di San Pietro", en: "St. Peter's Basilica" },
            { l1: "i Musei Vaticani", en: "the Vatican Museums" },
            { l1: "la Cappella Sistina", en: "the Sistine Chapel" },
            { l1: "Castel Sant'Angelo", en: "Castel Sant'Angelo" },
            { l1: "Villa Borghese", en: "Villa Borghese (park + gallery)" },
            { l1: "il Tevere", en: "the Tiber (river)" },
            { l1: "il Vaticano", en: "the Vatican (city)" },
            { l1: "Trastevere", en: "Trastevere (neighborhood)" },
            { l1: "Monti", en: "Monti (neighborhood)" },
            { l1: "Testaccio", en: "Testaccio (neighborhood, foodie)" },
          ],
        },
        {
          type: "tip",
          heading: "Pronunciation note: c before e/i",
          body: "<em>Colosseo</em>, <em>Trastevere</em>, <em>Cappella</em>, <em>Vaticano</em>: when 'c' comes before A, O, U it's a hard /k/ (Cappella = KAH-pell-ah). Before E or I it softens to /tʃ/ (English 'ch'): <em>cena</em> = CHE-nah, <em>vicino</em> = vee-CHEE-no. <em>Colosseo</em> = ko-loh-SAY-oh (the SS is doubled — hold it).",
        },
        {
          type: "multipleChoice",
          heading: "Match the name",
          questions: [
            {
              q: "'Sistine Chapel' in Italian =",
              options: [
                "Capella Sistine",
                "la Cappella Sistina",
                "il Cappello Sistino",
                "la Chiesa Sistina",
              ],
              correct: 1,
            },
            {
              q: "'St. Peter's Basilica' =",
              options: [
                "la Basilica di Pietro",
                "la Chiesa di San Pietro",
                "la Basilica di San Pietro",
                "il Tempio di Pietro",
              ],
              correct: 2,
            },
            {
              q: "The Tiber river is…",
              options: ["il Tevere", "il Tibero", "la Tiber", "il Po"],
              correct: 0,
            },
            {
              q: "Which is the foodie/working-class neighborhood?",
              options: ["Monti", "Trastevere", "Testaccio", "Parioli"],
              correct: 2,
            },
            {
              q: "The Spanish Steps in Italian =",
              options: [
                "i Passi Spagnoli",
                "la scalinata di Trinità dei Monti / Piazza di Spagna",
                "le scale di Spagna",
                "la Piazza Spagnola",
              ],
              correct: 1,
              fb: "The steps are 'la scalinata'; the square at the base is 'Piazza di Spagna'.",
            },
          ],
        },
      ],
    },
    {
      slug: "landmarks-history-talk",
      title: "Talking about history & art",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "A few words go a long way",
          body: [
            "You don't need to be an art historian. A handful of words let you read plaques, follow tour guides, and chat about what you're seeing.",
            "<strong>Antico</strong> = ancient. <strong>Romano</strong> = Roman (the empire). <strong>Medievale</strong> = medieval. <strong>Rinascimentale</strong> = Renaissance. <strong>Barocco</strong> = Baroque.",
            "Numbers for centuries follow ordinal pattern: <em>I secolo</em> = 1st century. <em>XVII secolo</em> = 17th century. Italians often refer to centuries by name too: <em>il Quattrocento</em> = the 1400s (the 15th century).",
          ],
          keyPoint:
            "Antico (ancient), romano (Roman), medievale, rinascimentale, barocco. Centuries: il Quattrocento = 1400s.",
        },
        {
          type: "vocab",
          heading: "Art and history",
          items: [
            { l1: "il monumento", en: "the monument" },
            { l1: "il museo", en: "the museum" },
            { l1: "la chiesa", en: "the church" },
            { l1: "la basilica", en: "the basilica" },
            { l1: "il duomo / la cattedrale", en: "the cathedral" },
            { l1: "il tempio", en: "the temple" },
            { l1: "la statua", en: "the statue" },
            { l1: "la scultura", en: "the sculpture" },
            { l1: "il dipinto / il quadro", en: "the painting" },
            { l1: "l'affresco", en: "the fresco" },
            { l1: "il mosaico", en: "the mosaic" },
            { l1: "la colonna", en: "the column" },
            { l1: "l'arco", en: "the arch" },
            { l1: "la cupola", en: "the dome" },
            { l1: "la rovina / le rovine", en: "ruin(s)" },
            { l1: "lo scavo / gli scavi", en: "excavation(s)" },
            { l1: "il secolo", en: "the century" },
            { l1: "l'epoca", en: "the era / period" },
          ],
        },
        {
          type: "vocab",
          heading: "Common periods",
          items: [
            { l1: "antico", en: "ancient" },
            { l1: "romano (impero romano)", en: "Roman (Roman Empire)" },
            { l1: "paleocristiano", en: "early Christian" },
            { l1: "medievale", en: "medieval" },
            { l1: "gotico", en: "Gothic" },
            { l1: "rinascimentale (il Rinascimento)", en: "Renaissance" },
            { l1: "barocco", en: "Baroque" },
            { l1: "neoclassico", en: "neoclassical" },
            { l1: "moderno / contemporaneo", en: "modern / contemporary" },
          ],
        },
        {
          type: "dialogue",
          heading: "On a guided tour",
          setup: "A guide explains the Pantheon to your group.",
          lines: [
            { speaker: "Guida", l1: "Buongiorno a tutti. Siamo davanti al Pantheon, uno dei monumenti antichi meglio conservati al mondo.", en: "Good morning everyone. We're in front of the Pantheon, one of the best-preserved ancient monuments in the world." },
            { speaker: "Guida", l1: "Il Pantheon attuale è del secondo secolo, costruito dall'imperatore Adriano. Prima c'era un tempio più antico, distrutto da un incendio.", en: "The current Pantheon is from the second century, built by emperor Hadrian. Before, there was an older temple, destroyed by a fire." },
            { speaker: "You", l1: "Mi scusi, una domanda: la cupola è originale?", en: "Excuse me, a question: is the dome original?" },
            { speaker: "Guida", l1: "Sì, è la cupola originale di duemila anni fa. È la cupola di cemento non rinforzato più grande del mondo. Un capolavoro di ingegneria.", en: "Yes, it's the original dome from two thousand years ago. It's the largest unreinforced concrete dome in the world. A masterpiece of engineering." },
            { speaker: "You", l1: "Incredibile. E l'oculus al centro?", en: "Incredible. And the oculus in the center?" },
            { speaker: "Guida", l1: "Apertura voluta. Serviva a illuminare l'interno e ad alleggerire la cupola. Anche oggi è l'unica fonte di luce naturale.", en: "An intentional opening. It served to light the interior and to lighten the dome. Even today it's the only source of natural light." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Art-vocab fill",
          items: [
            {
              template: "La Cappella Sistina contiene gli ___ di Michelangelo.",
              answer: "affreschi",
              en: "The Sistine Chapel contains Michelangelo's frescoes.",
              options: ["affreschi", "mosaici", "quadri", "statue"],
            },
            {
              template: "Questa chiesa è del ___ , molto antica.",
              answer: "medioevo",
              en: "This church is from the Middle Ages, very old.",
              options: ["futuro", "medioevo", "Rinascimento", "Barocco"],
            },
            {
              template: "Le ___ del Foro Romano sono ben conservate.",
              answer: "rovine",
              en: "The ruins of the Roman Forum are well preserved.",
              options: ["chiese", "rovine", "statue", "fontane"],
            },
            {
              template: "La ___ del Pantheon ha duemila anni.",
              answer: "cupola",
              en: "The dome of the Pantheon is two thousand years old.",
              options: ["chiesa", "fontana", "cupola", "colonna"],
            },
            {
              template: "Bernini era un grande artista del ___ romano.",
              answer: "Barocco",
              en: "Bernini was a great artist of the Roman Baroque.",
              options: ["Rinascimento", "Gotico", "Barocco", "Medioevo"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "This church is very old. It's from the medieval period.",
          reference: "Questa chiesa è molto antica. È del periodo medievale.",
          hint: "Use 'del' (di + il) for 'from the'. Medievale is invariable for both genders.",
        },
      ],
    },
    {
      slug: "landmarks-visit",
      title: "Visiting — tickets, audioguides, photos",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "The tourist-survival phrases",
          body: [
            "<em>«Quanto costa il biglietto?»</em> = How much is the ticket? Adult <em>intero</em>, reduced <em>ridotto</em>, free <em>gratuito</em>.",
            "Most major sites offer <em>biglietto cumulativo</em> (combo) — Colosseum + Forum + Palatine on one ticket, valid 24 hours.",
            "<em>«C'è un'audioguida in inglese?»</em> = Is there an audioguide in English? Usually ~€5-8 extra.",
            "<em>«Si possono fare foto?»</em> = Can you take photos? Most outdoor sites yes; Sistine Chapel no.",
          ],
          keyPoint:
            "Biglietto intero / ridotto / gratuito. Cumulativo = combo. Audioguida ~€5-8.",
        },
        {
          type: "vocab",
          heading: "Buying tickets & visiting",
          items: [
            { l1: "il biglietto intero", en: "full-price ticket" },
            { l1: "il biglietto ridotto", en: "reduced ticket (students, kids, seniors)" },
            { l1: "il biglietto gratuito", en: "free ticket" },
            { l1: "il biglietto cumulativo", en: "combo ticket" },
            { l1: "saltafila / skip-the-line", en: "skip-the-line" },
            { l1: "l'audioguida", en: "the audioguide" },
            { l1: "la guida turistica", en: "the tour guide (person)" },
            { l1: "il tour guidato", en: "guided tour" },
            { l1: "l'ingresso", en: "entrance / admission" },
            { l1: "l'uscita", en: "exit" },
            { l1: "il guardaroba", en: "the coat check" },
            { l1: "vietato", en: "forbidden / not allowed" },
            { l1: "fare foto / fotografare", en: "to take photos" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the Colosseum ticket counter",
          setup: "You're at the Colosseo ticket window with a friend.",
          lines: [
            { speaker: "You", l1: "Buongiorno. Due biglietti cumulativi, per favore. Colosseo, Foro e Palatino.", en: "Hello. Two combo tickets, please. Colosseum, Forum, and Palatine." },
            { speaker: "Cassiere", l1: "Va bene. Adulti?", en: "Okay. Adults?" },
            { speaker: "You", l1: "Sì, due adulti.", en: "Yes, two adults." },
            { speaker: "Cassiere", l1: "Sono trentadue euro in tutto. Il biglietto vale ventiquattro ore. Vuole anche l'audioguida?", en: "That's thirty-two euros total. The ticket is valid for 24 hours. Do you want an audioguide too?" },
            { speaker: "You", l1: "Sì, due audioguide in inglese, grazie. Quanto costano?", en: "Yes, two audioguides in English, please. How much do they cost?" },
            { speaker: "Cassiere", l1: "Sei euro l'una. Si paga di là, allo sportello con la scritta «audioguide». Ecco i Suoi biglietti.", en: "Six euros each. You pay over there, at the window marked 'audioguide'. Here are your tickets." },
            { speaker: "You", l1: "Grazie. Si possono fare foto dentro il Colosseo?", en: "Thank you. Can you take photos inside the Colosseum?" },
            { speaker: "Cassiere", l1: "Sì, certo. Solo niente flash nelle stanze interne.", en: "Yes, of course. Just no flash in the inner rooms." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Visiting phrases",
          items: [
            {
              template: "Vorrei due biglietti ___ , per favore.",
              answer: "interi",
              en: "I'd like two full-price tickets, please.",
              options: ["interi", "ridotti", "cumulativi", "gratuiti"],
            },
            {
              template: "C'è uno sconto per ___ ?",
              answer: "studenti",
              en: "Is there a discount for students?",
              options: ["studenti", "studente", "scuola", "università"],
            },
            {
              template: "A che ora ___ il museo?",
              answer: "chiude",
              en: "What time does the museum close?",
              options: ["apre", "chiude", "comincia", "finisce"],
            },
            {
              template: "Si possono ___ foto qui?",
              answer: "fare",
              en: "Can you take photos here?",
              options: ["dare", "fare", "vedere", "prendere"],
            },
            {
              template: "L'audioguida in inglese ___ otto euro.",
              answer: "costa",
              en: "The English audioguide costs eight euros.",
              options: ["fa", "costa", "vale", "compra"],
            },
          ],
        },
        {
          type: "orderWords",
          heading: "Build the request",
          items: [
            { tokens: ["Vorrei", "un", "biglietto", "ridotto", "per", "studente"], en: "I'd like a reduced student ticket." },
            { tokens: ["A", "che", "ora", "apre", "la", "Cappella", "Sistina", "?"], en: "What time does the Sistine Chapel open?" },
            { tokens: ["È", "vietato", "usare", "il", "flash", "qui"], en: "It's forbidden to use flash here." },
            { tokens: ["Posso", "lasciare", "lo", "zaino", "al", "guardaroba", "?"], en: "Can I leave my backpack at the coat check?" },
          ],
        },
        {
          type: "tip",
          heading: "Free days & timing",
          body: "First Sunday of every month is FREE entry to many state museums in Italy — Colosseum, Forum, Borghese Gallery, etc. Beautiful but crowded. Also free: anyone under 18, EU residents 18-25 get 50% off. Book Vatican Museums and Borghese Gallery in advance — they sell out. Colosseum: book a timed slot; walk-up is brutal.",
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Two tickets, please. One full and one reduced for a student.",
          reference: "Due biglietti, per favore. Uno intero e uno ridotto per studente.",
          hint: "Intero (full) / ridotto (reduced). 'For a student' = per studente.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'The Sistine Chapel' =",
        options: [
          "la Chiesa Sistina",
          "la Cappella Sistina",
          "il Capello Sistino",
          "il Tempio Sistino",
        ],
        correct: 1,
      },
      {
        q: "'Reduced ticket' =",
        options: [
          "biglietto intero",
          "biglietto ridotto",
          "biglietto cumulativo",
          "biglietto gratuito",
        ],
        correct: 1,
      },
      {
        q: "'Il Quattrocento' refers to…",
        options: ["the 400s AD", "the 14th century", "the 15th century (1400s)", "the year 400"],
        correct: 2,
      },
      {
        q: "'Fresco' (painting on plaster) =",
        options: ["il quadro", "l'affresco", "il mosaico", "la scultura"],
        correct: 1,
      },
      {
        q: "'The Roman Forum ruins' =",
        options: [
          "le statue del Foro Romano",
          "le rovine del Foro Romano",
          "le chiese del Foro Romano",
          "i monumenti del Foro Romano",
        ],
        correct: 1,
      },
      {
        q: "Bernini's most famous artistic period was…",
        options: ["medievale", "rinascimentale", "barocco", "moderno"],
        correct: 2,
      },
      {
        q: "'Can I take photos?' =",
        options: [
          "Posso fare foto?",
          "Si possono fare foto?",
          "Both work — both correct.",
          "Devo fare foto?",
        ],
        correct: 2,
      },
      {
        q: "Translate: 'How much is the ticket?'",
        options: [
          "Quanto è biglietto?",
          "Quanto fa biglietto?",
          "Quanto costa il biglietto?",
          "Costo del biglietto?",
        ],
        correct: 2,
      },
      {
        q: "Free state-museum day in Italy =",
        options: [
          "every Sunday",
          "first Sunday of the month",
          "every Saturday",
          "national holidays only",
        ],
        correct: 1,
      },
      {
        q: "'Audioguide in English' =",
        options: [
          "audioguida con inglese",
          "audio in inglese",
          "audioguida in inglese",
          "audiotape inglese",
        ],
        correct: 2,
      },
    ],
  },
};
