import type { Unit } from "../../types";

export const UNIT_PASSATO_AVERE: Unit = {
  slug: "passato-avere",
  stage: 5,
  order: 20,
  icon: "⏪",
  title: "Passato prossimo (avere)",
  tagline: "Ieri ho mangiato… The workhorse past tense. Once you've got this, you can narrate anything you did.",
  badge: "core",
  lessons: [
    {
      slug: "passato-avere-formation",
      title: "How it's built: avere + past participle",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Two ingredients, one tense",
          body: [
            "Italian uses a <strong>compound past</strong> — just like English's \"I have eaten,\" but used more broadly (it covers both \"I ate\" and \"I have eaten\").",
            "Formula: <strong>avere (present) + past participle</strong>. <em>Ho mangiato</em> = I ate / I have eaten. <em>Hai parlato</em> = you spoke / have spoken.",
            "Past participle of regular verbs: <strong>-are → -ato</strong> (mangiare → mangiato), <strong>-ere → -uto</strong> (vendere → venduto), <strong>-ire → -ito</strong> (dormire → dormito).",
            "The avere conjugation never changes its rhythm: <em>ho, hai, ha, abbiamo, avete, hanno</em> + the participle. The participle stays the same regardless of subject — for now (changes come with essere and pronouns, units 21+).",
          ],
          keyPoint:
            "avere (ho/hai/ha/abbiamo/avete/hanno) + participle (-ato / -uto / -ito). Participle invariable with avere.",
        },
        {
          type: "conjugation",
          heading: "Parlare in the past",
          verb: "parlare",
          meaning: "to speak",
          tenses: [
            {
              name: "Passato prossimo",
              forms: [
                { person: "io", form: "ho parlato", en: "I spoke / have spoken" },
                { person: "tu", form: "hai parlato", en: "you spoke" },
                { person: "lui/lei", form: "ha parlato", en: "he/she spoke" },
                { person: "noi", form: "abbiamo parlato", en: "we spoke" },
                { person: "voi", form: "avete parlato", en: "you all spoke" },
                { person: "loro", form: "hanno parlato", en: "they spoke" },
              ],
            },
          ],
        },
        {
          type: "vocab",
          heading: "Regular participles to memorize",
          intro: "All -are and -ire regulars follow the pattern. -ere is mostly regular too, but watch out for the irregular list on the next page.",
          items: [
            { l1: "mangiare → mangiato", en: "ate" },
            { l1: "parlare → parlato", en: "spoke" },
            { l1: "comprare → comprato", en: "bought" },
            { l1: "guardare → guardato", en: "watched" },
            { l1: "ascoltare → ascoltato", en: "listened" },
            { l1: "abitare → abitato", en: "lived (somewhere)" },
            { l1: "lavorare → lavorato", en: "worked" },
            { l1: "viaggiare → viaggiato", en: "traveled" },
            { l1: "dormire → dormito", en: "slept" },
            { l1: "sentire → sentito", en: "heard / felt" },
            { l1: "finire → finito", en: "finished" },
            { l1: "capire → capito", en: "understood" },
            { l1: "vendere → venduto", en: "sold" },
            { l1: "credere → creduto", en: "believed" },
            { l1: "ricevere → ricevuto", en: "received" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Build the past",
          items: [
            {
              template: "Ieri (io) ___ una pizza buonissima. (mangiare)",
              answer: "ho mangiato",
              en: "Yesterday I ate a delicious pizza.",
              options: ["ho mangiato", "mangio", "mangiavo", "ho mangiare"],
            },
            {
              template: "Tu ___ con Marco? (parlare)",
              answer: "hai parlato",
              en: "Did you speak with Marco?",
              options: ["hai parlato", "parli", "parlavi", "ha parlato"],
            },
            {
              template: "Loro ___ il film insieme. (guardare)",
              answer: "hanno guardato",
              en: "They watched the film together.",
              options: ["hanno guardato", "guardano", "abbiamo guardato", "hanno guardare"],
            },
            {
              template: "Noi ___ otto ore stanotte. (dormire)",
              answer: "abbiamo dormito",
              en: "We slept eight hours last night.",
              options: ["dormiamo", "abbiamo dormito", "avete dormito", "ho dormito"],
            },
            {
              template: "Voi ___ la lezione? (capire)",
              answer: "avete capito",
              en: "Did you all understand the lesson?",
              options: ["capite", "abbiamo capito", "avete capito", "ho capito"],
            },
            {
              template: "Lei ___ un nuovo cappotto. (comprare)",
              answer: "ha comprato",
              en: "She bought a new coat.",
              options: ["ha comprato", "compra", "abbiamo comprato", "hanno comprato"],
            },
          ],
        },
      ],
    },
    {
      slug: "passato-avere-irregulars",
      title: "The irregular participles — memorize the top 15",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Most irregulars cluster in -ere verbs",
          body: [
            "There's no rule — you just memorize them. Good news: a tiny set covers ~80% of what you'll actually say. Master these 15 and you're set.",
            "Pattern hint: many irregular participles end in <strong>-tto</strong>, <strong>-sso</strong>, or <strong>-so</strong>.",
            "Daily-use irregulars: <em>fatto, detto, letto, scritto, visto, preso, messo, aperto, chiuso, vinto, perso, bevuto, venuto, rotto, risposto</em>.",
          ],
          keyPoint:
            "Irregulars don't follow rules. Memorize: fatto, detto, letto, scritto, visto, preso, messo, aperto, chiuso, vinto, perso, bevuto, venuto, rotto, risposto.",
        },
        {
          type: "vocab",
          heading: "Top 15 irregular participles",
          items: [
            { l1: "fare → fatto", en: "did / made" },
            { l1: "dire → detto", en: "said" },
            { l1: "leggere → letto", en: "read (past)" },
            { l1: "scrivere → scritto", en: "wrote" },
            { l1: "vedere → visto", en: "saw" },
            { l1: "prendere → preso", en: "took" },
            { l1: "mettere → messo", en: "put / placed" },
            { l1: "aprire → aperto", en: "opened" },
            { l1: "chiudere → chiuso", en: "closed" },
            { l1: "vincere → vinto", en: "won" },
            { l1: "perdere → perso", en: "lost (also: perduto)" },
            { l1: "bere → bevuto", en: "drank" },
            { l1: "rompere → rotto", en: "broke" },
            { l1: "rispondere → risposto", en: "answered" },
            { l1: "chiedere → chiesto", en: "asked" },
            { l1: "offrire → offerto", en: "offered" },
            { l1: "scegliere → scelto", en: "chose" },
          ],
        },
        {
          type: "tip",
          heading: "Patterns that almost help",
          body: "Many <em>-cere</em> and <em>-gere</em> verbs end in <strong>-tto</strong>: leggere → letto, scrivere → scritto, friggere → fritto. Many <em>-ndere</em> verbs end in <strong>-so</strong>: prendere → preso, accendere → acceso, spendere → speso. Useful — but every rule has exceptions, so check before guessing.",
        },
        {
          type: "fillBlank",
          heading: "Irregular participle drill",
          items: [
            {
              template: "Ho ___ tutti i compiti. (fare)",
              answer: "fatto",
              en: "I did all the homework.",
              options: ["fatto", "fato", "facuto", "fattuto"],
            },
            {
              template: "Cosa hai ___ a Marco? (dire)",
              answer: "detto",
              en: "What did you say to Marco?",
              options: ["dito", "detto", "diciuto", "dicuto"],
            },
            {
              template: "Abbiamo ___ un libro fantastico. (leggere)",
              answer: "letto",
              en: "We read a fantastic book.",
              options: ["leggevo", "letto", "leggiuto", "leggito"],
            },
            {
              template: "Loro hanno ___ il treno delle sette. (prendere)",
              answer: "preso",
              en: "They took the seven o'clock train.",
              options: ["preso", "preduto", "prendiuto", "presi"],
            },
            {
              template: "Voi avete ___ tutto il vino? (bere)",
              answer: "bevuto",
              en: "Did you (all) drink all the wine?",
              options: ["beruto", "bevuto", "buto", "berato"],
            },
            {
              template: "Lei ha ___ una bella foto. (vedere)",
              answer: "visto",
              en: "She saw a beautiful photo.",
              options: ["visto", "vediuto", "veduto", "vediato"],
            },
            {
              template: "Ho ___ il bicchiere, scusa. (rompere)",
              answer: "rotto",
              en: "I broke the glass, sorry.",
              options: ["romputo", "rotto", "rompito", "rotti"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Yesterday I wrote a letter, read a book, and watched a film.",
          reference: "Ieri ho scritto una lettera, ho letto un libro e ho guardato un film.",
          hint: "Three different participles: scritto, letto, guardato. Each gets its own 'ho'.",
        },
      ],
    },
    {
      slug: "passato-avere-time",
      title: "Time expressions that signal the past",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Pair the tense with a time word and it's natural",
          body: [
            "These time markers tell your listener \"I'm in the past now\":",
            "<em>ieri</em> = yesterday · <em>l'altro ieri / due giorni fa</em> = day before yesterday · <em>la settimana scorsa</em> = last week · <em>il mese scorso</em> = last month · <em>l'anno scorso</em> = last year · <em>poco fa</em> = a little while ago · <em>già</em> = already · <em>ancora non / non ancora</em> = not yet · <em>mai</em> = ever / never.",
            "<em>Fa</em> goes AFTER the duration: <em>tre giorni fa</em> = three days ago.",
          ],
          keyPoint:
            "Ieri / la scorsa settimana / X giorni fa / poco fa / già / mai / non ancora. 'Fa' goes after the duration.",
        },
        {
          type: "vocab",
          heading: "Past-time vocabulary",
          items: [
            { l1: "ieri", en: "yesterday" },
            { l1: "ieri sera", en: "yesterday evening / last night" },
            { l1: "l'altro ieri", en: "day before yesterday" },
            { l1: "stamattina", en: "this morning" },
            { l1: "poco fa", en: "a little while ago" },
            { l1: "tre giorni fa", en: "three days ago" },
            { l1: "la settimana scorsa", en: "last week" },
            { l1: "il mese scorso", en: "last month" },
            { l1: "l'anno scorso", en: "last year" },
            { l1: "già", en: "already" },
            { l1: "ancora", en: "still / yet" },
            { l1: "non ancora", en: "not yet" },
            { l1: "mai", en: "ever / never (with non)" },
            { l1: "spesso", en: "often" },
            { l1: "qualche volta", en: "a few times" },
          ],
        },
        {
          type: "tip",
          heading: "Hai mai…? = Have you ever…?",
          body: "Common question: <em>«Hai mai mangiato la carbonara?»</em> = Have you ever eaten carbonara? Answer: <em>«Sì, l'ho mangiata.»</em> or <em>«No, non l'ho mai mangiata.»</em> (Note: with the pronoun <em>la</em> meaning \"it,\" the participle does agree — <em>mangiata</em>, not <em>mangiato</em>. We'll cover this in detail in the pronoun unit, but get used to seeing it.)",
        },
        {
          type: "dialogue",
          heading: "Talking about your day",
          setup: "Catching up with a friend.",
          lines: [
            { speaker: "Anna", l1: "Come è andata la giornata?", en: "How did your day go?" },
            { speaker: "You", l1: "Bene! Stamattina ho lavorato dalle nove alle una. Poi ho mangiato un panino veloce.", en: "Good! This morning I worked from nine to one. Then I ate a quick sandwich." },
            { speaker: "Anna", l1: "E dopo?", en: "And after?" },
            { speaker: "You", l1: "Nel pomeriggio ho fatto una passeggiata, poi ho letto un libro al parco. Tu, cosa hai fatto?", en: "In the afternoon I took a walk, then I read a book at the park. You, what did you do?" },
            { speaker: "Anna", l1: "Ho avuto una giornata pazzesca. Tre riunioni, e poi ho preso il treno per Milano la sera.", en: "I had a crazy day. Three meetings, and then I took the train to Milan in the evening." },
            { speaker: "You", l1: "Hai già cenato?", en: "Have you eaten dinner yet?" },
            { speaker: "Anna", l1: "Non ancora. Tu?", en: "Not yet. You?" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Time + past tense",
          items: [
            {
              template: "Tre giorni ___ , ho cominciato un nuovo lavoro.",
              answer: "fa",
              en: "Three days ago, I started a new job.",
              options: ["fa", "prima", "scorso", "indietro"],
            },
            {
              template: "Hai ___ visto il Colosseo?",
              answer: "mai",
              en: "Have you ever seen the Colosseum?",
              options: ["già", "mai", "ancora", "sempre"],
            },
            {
              template: "La settimana ___ ho visitato Firenze.",
              answer: "scorsa",
              en: "Last week I visited Florence.",
              options: ["scorsa", "ultima", "passata", "prima"],
            },
            {
              template: "Non ho ___ finito i compiti.",
              answer: "ancora",
              en: "I haven't yet finished my homework.",
              options: ["già", "mai", "ancora", "spesso"],
            },
            {
              template: "Ho ___ pagato il conto, non preoccuparti.",
              answer: "già",
              en: "I've already paid the bill, don't worry.",
              options: ["già", "ancora", "mai", "fa"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Yesterday evening I ate at a restaurant in Trastevere and drank a glass of red wine.",
          reference: "Ieri sera ho mangiato in un ristorante a Trastevere e ho bevuto un bicchiere di vino rosso.",
          hint: "Two verbs with avere: ho mangiato, ho bevuto. 'Trastevere' is a neighborhood — uses 'a'.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "Passato prossimo formula =",
        options: [
          "avere/essere + participle",
          "the verb stem + -ato",
          "imperfetto + participle",
          "essere + present",
        ],
        correct: 0,
      },
      {
        q: "Participle of 'mangiare' =",
        options: ["mangiuto", "mangiato", "manginto", "mangito"],
        correct: 1,
      },
      {
        q: "Participle of 'dormire' =",
        options: ["dormato", "dormuto", "dormito", "dormo"],
        correct: 2,
      },
      {
        q: "'I ate a pizza' =",
        options: [
          "Mangio una pizza.",
          "Ho mangiato una pizza.",
          "Mangiavo una pizza.",
          "Sono mangiato una pizza.",
        ],
        correct: 1,
      },
      {
        q: "Irregular participle of 'fare' =",
        options: ["fato", "fatto", "facuto", "fauto"],
        correct: 1,
      },
      {
        q: "Irregular participle of 'leggere' =",
        options: ["leggiuto", "letto", "leggito", "lego"],
        correct: 1,
      },
      {
        q: "'They drank all the wine' =",
        options: [
          "Hanno bevuto tutto il vino.",
          "Hanno bero tutto il vino.",
          "Bevono tutto il vino.",
          "Hanno bevuti tutto il vino.",
        ],
        correct: 0,
      },
      {
        q: "'Three days ago' =",
        options: [
          "tre giorni prima",
          "fa tre giorni",
          "tre giorni fa",
          "scorsi tre giorni",
        ],
        correct: 2,
      },
      {
        q: "'Have you ever been to Rome?' =",
        options: [
          "Sei stato sempre a Roma?",
          "Hai mai stato a Roma?",
          "Sei mai stato a Roma?",
          "Sei stato mai a Roma?",
        ],
        correct: 2,
        // Sneak preview: essere takes 'sei stato' — covered in next unit.
      },
      {
        q: "Translate: 'I haven't finished the book yet.'",
        options: [
          "Ho già finito il libro.",
          "Non ho ancora finito il libro.",
          "Ho non finito il libro.",
          "Mai ho finito il libro.",
        ],
        correct: 1,
      },
    ],
  },
};
