import type { Unit } from "../../types";

export const UNIT_SHOPPING: Unit = {
  slug: "shopping",
  stage: 6,
  order: 25,
  icon: "🛍️",
  title: "Money & shopping",
  tagline: "Quanto costa, sconto, posso pagare con carta? — the everyday transactions.",
  badge: "tourist",
  lessons: [
    {
      slug: "shopping-money-basics",
      title: "Talking about money",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "Euro, cents, and 'quanto costa'",
          body: [
            "Italy uses the <strong>euro (€)</strong>. Cents = <em>centesimi</em>. €4.50 is said <em>quattro euro e cinquanta</em> — Italians drop \"cents\" most of the time. €3.99 = <em>tre euro e novantanove</em>.",
            "Asking the price: <em>«Quanto costa?»</em> (singular item) or <em>«Quanto costano?»</em> (plural). Cashiers' phrase: <em>«Quanto fa?»</em> = how much total.",
            "Discounts: <em>sconto</em> = discount. <em>In saldo</em> = on sale. <em>Saldi estivi / invernali</em> = summer / winter sales (a real season in Italy — January and July).",
            "<em>Caro</em> = expensive. <em>Economico</em> = cheap. <em>Conveniente</em> = good value.",
          ],
          keyPoint:
            "Quanto costa? (singular) / costano? (plural). Sconto = discount. Caro = expensive. €X,YY said as 'X euro e YY'.",
        },
        {
          type: "vocab",
          heading: "Money & price vocabulary",
          items: [
            { l1: "l'euro / gli euro", en: "euro (invariable plural too)" },
            { l1: "i centesimi", en: "cents" },
            { l1: "il prezzo", en: "the price" },
            { l1: "quanto costa?", en: "how much does it cost? (singular)" },
            { l1: "quanto costano?", en: "how much do they cost? (plural)" },
            { l1: "quanto fa?", en: "how much is it total?" },
            { l1: "lo sconto", en: "discount" },
            { l1: "in saldo / i saldi", en: "on sale / the sales (season)" },
            { l1: "caro / costoso", en: "expensive" },
            { l1: "economico / a buon prezzo", en: "cheap / inexpensive" },
            { l1: "il resto", en: "the change (money returned)" },
            { l1: "lo scontrino", en: "the receipt" },
            { l1: "il bancomat", en: "ATM / debit card (slang)" },
            { l1: "contanti", en: "cash" },
            { l1: "i pos", en: "card-payment machine" },
            { l1: "non ho spiccioli", en: "I don't have small change" },
          ],
        },
        {
          type: "tip",
          heading: "POS machines and the 'tap' game",
          body: "Most Italian shops accept contactless. Just hold your card or phone near the POS reader. For payments above €25 you may be asked for the PIN. American Express is sometimes refused; Visa/Mastercard always works. Cash is still king at small bakeries, markets, and old-school trattorias — carry €20-50 in small bills.",
        },
        {
          type: "multipleChoice",
          heading: "Price talk",
          questions: [
            {
              q: "'How much does it cost?' (singular item) =",
              options: [
                "Quanto fa?",
                "Quanto costa?",
                "Quanto costano?",
                "Quanto sono?",
              ],
              correct: 1,
            },
            {
              q: "'On sale' =",
              options: ["in offerta", "in saldo", "Both work", "in sconto"],
              correct: 2,
            },
            {
              q: "'I don't have small change' =",
              options: [
                "Non ho contanti.",
                "Non ho moneta.",
                "Non ho spiccioli.",
                "Non ho il resto.",
              ],
              correct: 2,
            },
            {
              q: "'Cheap' (low cost) =",
              options: ["caro", "economico", "conveniente", "Both B and C work"],
              correct: 3,
            },
            {
              q: "€4.50 is said…",
              options: [
                "quattro euro cinquanta centesimi",
                "quattro virgola cinquanta",
                "quattro euro e cinquanta",
                "Both A and C work — but C is shorter and more common",
              ],
              correct: 3,
            },
          ],
        },
      ],
    },
    {
      slug: "shopping-clothes",
      title: "Clothes shopping",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Trying on, sizes, colors",
          body: [
            "<em>«Posso provarlo / provarla?»</em> = Can I try it on? (m / f object).",
            "<em>«Avete la taglia M?»</em> = Do you have size M? Italian sizes: XS, S, M, L, XL or numeric for tops (36-50 women, 44-58 men) and shoes (35-46 EU).",
            "<em>«Mi va stretto / largo»</em> = It's tight / loose on me.",
            "<em>«Lo / la prendo»</em> = I'll take it.",
            "<em>«Posso vedere quel modello in vetrina?»</em> = Can I see that model in the window?",
          ],
          keyPoint:
            "Provare = to try on. Taglia = size. Stretto / largo = tight / loose. 'Lo / la prendo' = I'll take it.",
        },
        {
          type: "vocab",
          heading: "Clothes",
          items: [
            { l1: "i vestiti", en: "clothes" },
            { l1: "una maglietta / una t-shirt", en: "a t-shirt" },
            { l1: "una camicia", en: "a (button-up) shirt" },
            { l1: "una maglia / un maglione", en: "a sweater / heavy sweater" },
            { l1: "un vestito", en: "a dress / a suit (context)" },
            { l1: "un paio di pantaloni", en: "a pair of pants" },
            { l1: "un paio di jeans", en: "a pair of jeans" },
            { l1: "una gonna", en: "a skirt" },
            { l1: "una giacca / un cappotto", en: "a jacket / a coat" },
            { l1: "le scarpe", en: "shoes" },
            { l1: "i sandali", en: "sandals" },
            { l1: "un cappello", en: "a hat" },
            { l1: "una sciarpa", en: "a scarf" },
            { l1: "una cintura", en: "a belt" },
          ],
        },
        {
          type: "vocab",
          heading: "Colors & sizes",
          items: [
            { l1: "bianco / nero / grigio", en: "white / black / gray" },
            { l1: "rosso / blu / verde", en: "red / blue / green" },
            { l1: "giallo / arancione", en: "yellow / orange" },
            { l1: "rosa / viola", en: "pink / purple" },
            { l1: "marrone / beige", en: "brown / beige" },
            { l1: "la taglia", en: "size (clothes)" },
            { l1: "il numero", en: "size (shoes)" },
            { l1: "stretto / largo", en: "tight / loose / wide" },
            { l1: "corto / lungo", en: "short / long" },
            { l1: "una taglia più grande / piccola", en: "a size up / down" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the boutique",
          setup: "You're looking at a sweater.",
          lines: [
            { speaker: "Commessa", l1: "Buongiorno, posso aiutarLa?", en: "Hello, can I help you?" },
            { speaker: "You", l1: "Sì, mi piace questa maglia in vetrina. La avete nella mia taglia?", en: "Yes, I like this sweater in the window. Do you have it in my size?" },
            { speaker: "Commessa", l1: "Che taglia porta?", en: "What size do you wear?" },
            { speaker: "You", l1: "Solitamente una M. Posso provarla?", en: "Usually an M. Can I try it on?" },
            { speaker: "Commessa", l1: "Certo, il camerino è là in fondo a destra.", en: "Of course, the fitting room is over there in the back on the right." },
            { speaker: "You", l1: "(dopo) Mi va un po' stretta. Avete la L?", en: "(later) It's a bit tight on me. Do you have it in L?" },
            { speaker: "Commessa", l1: "Aspetti, controllo… Sì, eccola.", en: "Wait, let me check… Yes, here it is." },
            { speaker: "You", l1: "Perfetta. La prendo. Quanto costa?", en: "Perfect. I'll take it. How much is it?" },
            { speaker: "Commessa", l1: "Sessantotto euro. È in saldo, c'è il dieci percento di sconto.", en: "Sixty-eight euros. It's on sale, ten percent off." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Shopping fill",
          items: [
            {
              template: "Che ___ porta? (clothes)",
              answer: "taglia",
              en: "What size do you wear?",
              options: ["misura", "taglia", "numero", "porzione"],
            },
            {
              template: "Posso ___ questa maglia?",
              answer: "provare",
              en: "Can I try this sweater on?",
              options: ["prendere", "provare", "comprare", "vedere"],
            },
            {
              template: "Mi va un po' ___ . Avete una taglia più grande?",
              answer: "stretto",
              en: "It's a bit tight on me. Do you have a bigger size?",
              options: ["stretto", "largo", "corto", "lungo"],
            },
            {
              template: "C'è il venti percento di ___ ?",
              answer: "sconto",
              en: "Is there a 20% discount?",
              options: ["sconto", "vendita", "prezzo", "saldo"],
            },
            {
              template: "Questi pantaloni sono troppo ___ .",
              answer: "corti",
              en: "These pants are too short.",
              options: ["corte", "corti", "lunghi", "stretti"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I like this jacket. Do you have it in black, size L?",
          reference: "Mi piace questa giacca. La avete in nero, taglia L?",
          hint: "Giacca is feminine → 'la avete'. 'In nero' = in black.",
        },
      ],
    },
    {
      slug: "shopping-pay",
      title: "Paying — card, cash, receipts",
      estMinutes: 8,
      pages: [
        {
          type: "intro",
          heading: "The payment script",
          body: [
            "<em>«Si può pagare con la carta?»</em> = Can I pay by card?",
            "<em>«Pago in contanti.»</em> = I'll pay in cash.",
            "<em>«Avete il bancomat?»</em> = Do you have the card reader?",
            "<em>«Mi può fare uno scontrino?»</em> = Can you give me a receipt? (Always say yes — required by Italian law.)",
            "<em>«Tenga il resto.»</em> = Keep the change (at restaurants — usually you don't tip at shops).",
          ],
          keyPoint:
            "Pagare con la carta / in contanti. Bancomat = POS machine. Always take the scontrino.",
        },
        {
          type: "vocab",
          heading: "Payment vocabulary",
          items: [
            { l1: "pagare", en: "to pay" },
            { l1: "la carta di credito / di debito", en: "credit / debit card" },
            { l1: "i contanti", en: "cash" },
            { l1: "il bancomat", en: "POS / debit card (slang)" },
            { l1: "il pin / il codice", en: "PIN" },
            { l1: "contactless", en: "contactless (used as-is)" },
            { l1: "la moneta / le monete", en: "coin / coins" },
            { l1: "la banconota", en: "banknote / bill" },
            { l1: "spiccioli", en: "small change" },
            { l1: "lo scontrino / la ricevuta fiscale", en: "receipt / official tax receipt" },
            { l1: "la fattura", en: "invoice (for businesses)" },
            { l1: "garanzia", en: "warranty" },
            { l1: "reso / rimborso", en: "return / refund" },
          ],
        },
        {
          type: "dialogue",
          heading: "Paying at a shoe store",
          setup: "You're at the cashier with two boxes.",
          lines: [
            { speaker: "Cassiere", l1: "Allora, due paia di scarpe. Centonovantadue euro in totale.", en: "Right, two pairs of shoes. One hundred ninety-two euros total." },
            { speaker: "You", l1: "Si può pagare con la carta?", en: "Can I pay by card?" },
            { speaker: "Cassiere", l1: "Sì, contactless o con il chip. Avvicini la carta al lettore.", en: "Yes, contactless or with the chip. Hold the card near the reader." },
            { speaker: "You", l1: "Ecco fatto. Mi può fare lo scontrino, per favore?", en: "Done. Can you give me the receipt, please?" },
            { speaker: "Cassiere", l1: "Certo, eccolo. Se non Le piacciono, può fare il reso entro trenta giorni.", en: "Sure, here it is. If you don't like them, you can return them within 30 days." },
            { speaker: "You", l1: "Va bene. Devo conservare lo scontrino?", en: "Okay. Should I keep the receipt?" },
            { speaker: "Cassiere", l1: "Sì, lo scontrino è obbligatorio per il reso.", en: "Yes, the receipt is required for returns." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Pay-up fill",
          items: [
            {
              template: "Si può ___ con la carta?",
              answer: "pagare",
              en: "Can I pay by card?",
              options: ["pagare", "comprare", "fare", "vendere"],
            },
            {
              template: "Mi può fare lo ___ , per favore?",
              answer: "scontrino",
              en: "Can you give me the receipt, please?",
              options: ["scontrino", "sconto", "resto", "porte"],
            },
            {
              template: "Pago in ___ , se non Le dispiace.",
              answer: "contanti",
              en: "I'll pay in cash, if you don't mind.",
              options: ["contanti", "carta", "moneta", "spiccioli"],
            },
            {
              template: "Tenga il ___ , grazie.",
              answer: "resto",
              en: "Keep the change, thank you.",
              options: ["scontrino", "resto", "moneta", "denaro"],
            },
            {
              template: "Posso fare il ___ se non mi piace?",
              answer: "reso",
              en: "Can I return it if I don't like it?",
              options: ["reso", "rimborso", "cambio", "scambio"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "Can I pay by card? And can I have a receipt, please?",
          reference: "Si può pagare con la carta? E posso avere uno scontrino, per favore?",
          hint: "'Si può + infinitive' = impersonal 'can one…'. 'Posso avere…' = can I have…",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'How much does it cost?' (singular) =",
        options: ["Quanto costano?", "Quanto fa?", "Quanto costa?", "Quanto è?"],
        correct: 2,
      },
      {
        q: "'On sale' =",
        options: ["in offerta", "in saldo", "Both work", "in vendita"],
        correct: 2,
      },
      {
        q: "'What size do you wear?' (clothes) =",
        options: [
          "Che numero porta?",
          "Che taglia porta?",
          "Che misura porta?",
          "Che size porta?",
        ],
        correct: 1,
      },
      {
        q: "'Can I try it on?' (f object) =",
        options: ["Posso provarla?", "Posso provarlo?", "Posso provare?", "Si può provare?"],
        correct: 0,
      },
      {
        q: "'It's tight on me' =",
        options: ["Mi va largo.", "Mi va stretto.", "Mi va corto.", "Mi sta bene."],
        correct: 1,
      },
      {
        q: "Italian winter sales (i saldi invernali) start in…",
        options: ["October", "January", "March", "December"],
        correct: 1,
      },
      {
        q: "'Receipt' (legally required) =",
        options: ["il prezzo", "lo scontrino", "il pagamento", "la fattura"],
        correct: 1,
      },
      {
        q: "'I'll pay in cash' =",
        options: [
          "Pago con la carta.",
          "Pago in contanti.",
          "Pago a contante.",
          "Pago in moneta.",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'Can I have a smaller size?'",
        options: [
          "Posso avere una taglia più grande?",
          "Posso avere una taglia più piccola?",
          "Posso avere una taglia minore?",
          "Both B and C work — B is more natural.",
        ],
        correct: 3,
      },
      {
        q: "'I don't have small change' =",
        options: [
          "Non ho contanti.",
          "Non ho cambio.",
          "Non ho spiccioli.",
          "Non ho il resto.",
        ],
        correct: 2,
      },
    ],
  },
};
