import type { Unit } from "../../types";

export const UNIT_MUSEUMS: Unit = {
  slug: "museums",
  stage: 7,
  order: 31,
  icon: "🖼️",
  title: "Museums & art talk",
  tagline: "Affresco, scultura, mostra — the words you need to sound like you belong in a gallery.",
  badge: "culture",
  lessons: [
    {
      slug: "museums-art-vocab",
      title: "Talking about art",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "A bigger vocabulary unlocks a better visit",
          body: [
            "Art words let you read plaques (almost always in Italian first, English second), follow tour guides, and chat with locals about exhibitions.",
            "<strong>Materials & techniques:</strong> <em>olio su tela</em> (oil on canvas), <em>tempera</em>, <em>affresco</em> (fresco), <em>scultura in marmo / bronzo</em> (marble / bronze sculpture), <em>incisione</em> (engraving), <em>disegno</em> (drawing).",
            "<strong>Periods:</strong> <em>antico, medievale, gotico, rinascimentale, manierista, barocco, neoclassico, romantico, impressionista, moderno, contemporaneo</em>.",
          ],
          keyPoint:
            "Materials (olio, tempera, marmo, bronzo) + periods (rinascimentale, barocco, etc.) + verbs (rappresenta, raffigura) cover most plaques.",
        },
        {
          type: "vocab",
          heading: "Art techniques & forms",
          items: [
            { l1: "l'opera (d'arte)", en: "work (of art)" },
            { l1: "il quadro / il dipinto", en: "painting" },
            { l1: "l'olio su tela", en: "oil on canvas" },
            { l1: "la tempera", en: "tempera" },
            { l1: "l'affresco", en: "fresco (paint on wet plaster)" },
            { l1: "il mosaico", en: "mosaic" },
            { l1: "la scultura", en: "sculpture" },
            { l1: "il marmo / il bronzo", en: "marble / bronze" },
            { l1: "il disegno", en: "drawing" },
            { l1: "l'incisione / la stampa", en: "engraving / print" },
            { l1: "la cornice", en: "the frame" },
            { l1: "la tela", en: "the canvas" },
            { l1: "il restauro", en: "restoration" },
            { l1: "il ritratto", en: "portrait" },
            { l1: "l'autoritratto", en: "self-portrait" },
            { l1: "il paesaggio", en: "landscape" },
            { l1: "la natura morta", en: "still life" },
            { l1: "la scena religiosa / mitologica", en: "religious / mythological scene" },
          ],
        },
        {
          type: "vocab",
          heading: "Talking about a piece",
          items: [
            { l1: "raffigura / rappresenta", en: "depicts / represents" },
            { l1: "è caratterizzato/a da…", en: "is characterized by…" },
            { l1: "il chiaroscuro", en: "chiaroscuro (light-dark contrast)" },
            { l1: "la prospettiva", en: "perspective" },
            { l1: "la composizione", en: "composition" },
            { l1: "il colore", en: "color" },
            { l1: "la pennellata", en: "the brushstroke" },
            { l1: "lo stile", en: "the style" },
            { l1: "il soggetto", en: "the subject" },
            { l1: "il committente", en: "the patron / commissioner" },
            { l1: "l'artista / la artista", en: "artist (m / f same form)" },
            { l1: "il pittore / la pittrice", en: "painter (m / f)" },
            { l1: "lo scultore / la scultrice", en: "sculptor" },
            { l1: "essere influenzato da…", en: "to be influenced by…" },
            { l1: "appartenere a (corrente, scuola)", en: "to belong to (movement, school)" },
          ],
        },
        {
          type: "tip",
          heading: "Big Italian artists to recognize",
          body: "<strong>Rinascimento:</strong> Leonardo da Vinci, Michelangelo, Raffaello, Botticelli, Tiziano. <strong>Barocco:</strong> Caravaggio (intense chiaroscuro), Bernini (sculpture). <strong>Manierismo:</strong> Pontormo, Parmigianino. <strong>Settecento:</strong> Canaletto (Venetian landscapes), Tiepolo (frescoes). <strong>Novecento:</strong> Modigliani, De Chirico, Morandi. When in doubt, attribute Roman paintings to Caravaggio and Vatican frescoes to either Raffaello or Michelangelo. You'll be right 60% of the time.",
        },
        {
          type: "multipleChoice",
          heading: "Art quiz",
          questions: [
            {
              q: "'Fresco' (painting on wet plaster) =",
              options: ["il quadro", "l'olio", "l'affresco", "il mosaico"],
              correct: 2,
            },
            {
              q: "Caravaggio is famous for…",
              options: [
                "watercolors",
                "intense chiaroscuro (light-dark contrast)",
                "marble sculpture",
                "Byzantine mosaics",
              ],
              correct: 1,
            },
            {
              q: "'Sculpture in bronze' =",
              options: [
                "scultura in marmo",
                "scultura in bronzo",
                "scultura in pietra",
                "scultura in legno",
              ],
              correct: 1,
            },
            {
              q: "Bernini is best known for…",
              options: [
                "frescoes",
                "Baroque sculpture and architecture",
                "Renaissance painting",
                "modern art",
              ],
              correct: 1,
            },
            {
              q: "'Self-portrait' =",
              options: ["il ritratto", "l'autoritratto", "il paesaggio", "la natura morta"],
              correct: 1,
            },
          ],
        },
      ],
    },
    {
      slug: "museums-visiting",
      title: "At the museum — tickets, audio, navigating",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Practical museum Italian",
          body: [
            "Ticket types: <em>intero</em> (full), <em>ridotto</em> (reduced — students, seniors, kids), <em>gratuito</em> (free). Some show <em>cumulativo</em> (combo with another museum).",
            "Always ask: <em>«C'è uno sconto per studenti / per residenti UE?»</em> = Is there a student / EU resident discount?",
            "<em>«C'è l'audioguida in inglese?»</em> — yes ~€5-8 extra.",
            "<em>«C'è la coda?»</em> = is there a line? — Booking online (<em>biglietto online</em>) usually saves the wait.",
            "<em>«Si possono fare foto?»</em> Most yes, sometimes no flash, sometimes no photos at all (Sistine Chapel).",
          ],
          keyPoint:
            "Intero / ridotto / gratuito. Cumulativo = combo. Online booking saves the line. Audioguide in English ~€5-8.",
        },
        {
          type: "vocab",
          heading: "Museum vocabulary",
          items: [
            { l1: "il museo", en: "museum" },
            { l1: "la galleria", en: "gallery" },
            { l1: "la mostra", en: "exhibition" },
            { l1: "la mostra temporanea / permanente", en: "temporary / permanent exhibition" },
            { l1: "la sala", en: "the (museum) room" },
            { l1: "il piano (terra / primo / secondo)", en: "(ground / first / second) floor" },
            { l1: "la biglietteria", en: "ticket office" },
            { l1: "il guardaroba", en: "coat check" },
            { l1: "la mappa del museo", en: "museum map" },
            { l1: "l'audioguida", en: "audioguide" },
            { l1: "la guida turistica", en: "tour guide (person)" },
            { l1: "il visitatore / la visitatrice", en: "visitor" },
            { l1: "il bookshop", en: "bookshop / gift shop" },
            { l1: "il caffè del museo", en: "museum café" },
            { l1: "vietato (toccare / fotografare)", en: "forbidden (to touch / photograph)" },
            { l1: "uscita d'emergenza", en: "emergency exit" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the ticket office of the Borghese Gallery",
          setup: "You arrive without a pre-booked ticket.",
          lines: [
            { speaker: "You", l1: "Buongiorno. Vorrei due biglietti per la mostra permanente, per favore.", en: "Hello. I'd like two tickets for the permanent exhibition, please." },
            { speaker: "Cassiere", l1: "Mi dispiace, oggi è già tutto pieno. Si entra solo con prenotazione online.", en: "I'm sorry, today it's all full. You can only enter with an online reservation." },
            { speaker: "You", l1: "Ah. C'è posto per domani?", en: "Ah. Is there space for tomorrow?" },
            { speaker: "Cassiere", l1: "Vediamo… domani alle quattordici ci sono due posti.", en: "Let's see… tomorrow at 14:00 there are two spots." },
            { speaker: "You", l1: "Va bene. Quanto costano?", en: "Okay. How much do they cost?" },
            { speaker: "Cassiere", l1: "Quindici euro l'uno per gli adulti. C'è uno sconto se siete residenti UE.", en: "Fifteen euros each for adults. There's a discount if you're EU residents." },
            { speaker: "You", l1: "No, siamo americani. Va bene, due biglietti interi.", en: "No, we're American. Okay, two full tickets." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Museum fill-ins",
          items: [
            {
              template: "C'è uno ___ per studenti?",
              answer: "sconto",
              en: "Is there a student discount?",
              options: ["sconto", "biglietto", "ridotto", "prezzo"],
            },
            {
              template: "L' ___ in inglese costa cinque euro in più.",
              answer: "audioguida",
              en: "The English audioguide costs five euros extra.",
              options: ["audioguida", "guida", "audio", "ascoltatore"],
            },
            {
              template: "Si possono ___ foto qui?",
              answer: "fare",
              en: "Can you take photos here?",
              options: ["dare", "vedere", "fare", "prendere"],
            },
            {
              template: "L'opera è nella ___ a piano terra.",
              answer: "sala",
              en: "The work is in the room on the ground floor.",
              options: ["mostra", "sala", "galleria", "biglietteria"],
            },
            {
              template: "C'è la ___ ? Pensavo di prenotare online.",
              answer: "coda",
              en: "Is there a line? I thought of booking online.",
              options: ["coda", "porta", "uscita", "mappa"],
            },
          ],
        },
      ],
    },
    {
      slug: "museums-art-conversation",
      title: "Chatting about art — opinion phrases",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Sounding thoughtful in front of a painting",
          body: [
            "Italians enjoy art talk. A few phrases let you participate without sounding shallow:",
            "<em>Mi colpisce…</em> = It strikes me / impresses me.",
            "<em>Quello che mi piace di più è…</em> = What I like most is…",
            "<em>Si vede l'influenza di…</em> = You can see the influence of…",
            "<em>Sembra quasi…</em> = It almost seems / looks like…",
            "<em>Mi ricorda…</em> = It reminds me of…",
            "Mix in basic art vocab (chiaroscuro, prospettiva, pennellata) and you'll sound like a thoughtful visitor, not a know-it-all.",
          ],
          keyPoint:
            "Mi colpisce / mi piace / si vede l'influenza di / sembra quasi / mi ricorda. Soft, observational, never pretending to be an expert.",
        },
        {
          type: "vocab",
          heading: "Opinion phrases for art",
          items: [
            { l1: "mi colpisce / mi affascina", en: "it strikes me / fascinates me" },
            { l1: "quello che mi piace di più è…", en: "what I like most is…" },
            { l1: "non mi convince molto", en: "it doesn't quite convince me" },
            { l1: "secondo me…", en: "in my opinion…" },
            { l1: "trovo che sia…", en: "I find that it is…" },
            { l1: "si vede l'influenza di…", en: "you can see the influence of…" },
            { l1: "sembra quasi…", en: "it almost seems / looks like…" },
            { l1: "mi ricorda…", en: "it reminds me of…" },
            { l1: "è un capolavoro", en: "it's a masterpiece" },
            { l1: "è geniale / brillante", en: "it's genius / brilliant" },
            { l1: "è sopravvalutato/a", en: "it's overrated" },
            { l1: "non capisco bene il messaggio", en: "I don't quite understand the message" },
          ],
        },
        {
          type: "dialogue",
          heading: "In front of a Caravaggio",
          setup: "You're at San Luigi dei Francesi, looking at 'The Calling of St. Matthew'.",
          lines: [
            { speaker: "Marco", l1: "Cosa ne pensi?", en: "What do you think?" },
            { speaker: "You", l1: "Mi colpisce moltissimo. Il chiaroscuro è incredibile.", en: "It really strikes me. The chiaroscuro is incredible." },
            { speaker: "Marco", l1: "Vedi come la luce viene da destra, dove c'è la finestra dipinta? È un trucco geniale.", en: "See how the light comes from the right, where the painted window is? It's a genius trick." },
            { speaker: "You", l1: "Sì, e sembra quasi una scena di teatro. I personaggi hanno vestiti del Seicento, non dell'epoca di Gesù.", en: "Yes, and it almost looks like a theater scene. The characters wear 17th-century clothes, not Jesus's era." },
            { speaker: "Marco", l1: "Esatto. Caravaggio voleva che la gente comune si identificasse con loro.", en: "Exactly. Caravaggio wanted ordinary people to identify with them." },
            { speaker: "You", l1: "Mi piace molto di più dei dipinti più 'classici' del Rinascimento. È più diretto, più drammatico.", en: "I like it much more than the more 'classical' Renaissance paintings. It's more direct, more dramatic." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Opinion phrases",
          items: [
            {
              template: "Mi ___ molto il colore di questo dipinto.",
              answer: "colpisce",
              en: "I'm really struck by the color of this painting.",
              options: ["fa", "vedo", "colpisce", "tiene"],
            },
            {
              template: "Secondo ___ , Caravaggio è il più grande pittore del Barocco.",
              answer: "me",
              en: "In my opinion, Caravaggio is the greatest Baroque painter.",
              options: ["io", "me", "mi", "uno"],
            },
            {
              template: "Quest'opera ___ ricorda il Rinascimento.",
              answer: "mi",
              en: "This work reminds me of the Renaissance.",
              options: ["me", "mi", "ne", "ci"],
            },
            {
              template: "Si vede l' ___ di Michelangelo nello stile.",
              answer: "influenza",
              en: "You can see Michelangelo's influence in the style.",
              options: ["essere", "ammirazione", "influenza", "interesse"],
            },
            {
              template: "Trovo che ___ un capolavoro assoluto.",
              answer: "sia",
              en: "I find that it's an absolute masterpiece.",
              options: ["è", "sia", "essere", "era"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-l1",
          prompt: "I really like this painting. It almost looks like a photo.",
          reference: "Mi piace molto questo dipinto. Sembra quasi una foto.",
          hint: "'Sembra quasi…' = it almost seems / looks like…",
        },
        {
          type: "tip",
          heading: "Don't fake it",
          body: "Italians notice when foreigners are name-dropping artists to seem cultured. Better to say <em>«Non lo conoscevo, è bellissimo»</em> = I didn't know him, he's wonderful. Curiosity beats false expertise. Asking <em>«Mi può dire qualcosa su questo artista?»</em> opens up genuine conversation.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "'Fresco' (painting on wet plaster) =",
        options: ["il quadro", "l'olio", "l'affresco", "il mosaico"],
        correct: 2,
      },
      {
        q: "Caravaggio's signature technique =",
        options: [
          "perspective",
          "watercolor",
          "chiaroscuro (intense light-dark)",
          "tempera",
        ],
        correct: 2,
      },
      {
        q: "'Reduced ticket' =",
        options: ["biglietto intero", "biglietto ridotto", "biglietto gratuito", "biglietto cumulativo"],
        correct: 1,
      },
      {
        q: "'Self-portrait' =",
        options: ["il ritratto", "l'autoritratto", "il paesaggio", "la composizione"],
        correct: 1,
      },
      {
        q: "Bernini is best known for…",
        options: [
          "frescoes",
          "Baroque sculpture and architecture",
          "early Renaissance painting",
          "Byzantine mosaics",
        ],
        correct: 1,
      },
      {
        q: "'You can see the influence of…' =",
        options: [
          "Si vede l'influenza di…",
          "Tu vedi l'influenza di…",
          "Influenza è visibile.",
          "Vedo influenza di…",
        ],
        correct: 0,
      },
      {
        q: "'It almost looks like…' =",
        options: ["Sembra quasi…", "Quasi è…", "Quasi sembra…", "Sembra come…"],
        correct: 0,
      },
      {
        q: "'Is there a discount for students?' =",
        options: [
          "C'è uno sconto per studenti?",
          "C'è prezzo per studenti?",
          "Studenti hanno sconto?",
          "Per studenti c'è prezzo?",
        ],
        correct: 0,
      },
      {
        q: "'In my opinion' =",
        options: ["secondo io", "secondo me", "per me", "Both B and C work"],
        correct: 3,
      },
      {
        q: "Translate: 'I really like this painting.'",
        options: [
          "Voglio molto questo dipinto.",
          "Mi piace molto questo dipinto.",
          "Mi colpisce questo dipinto.",
          "Both B and C work and mean similar things.",
        ],
        correct: 3,
      },
    ],
  },
};
